### PR TITLE
Add OpenAI organization ID to docs

### PR DESCRIPTION
**Pull request by schop-rob**
Description: I added an example of how to reference the OpenAI API Organization ID, because I couldn't find it before. In the example, it is mentioned how to achieve this using environment variables as well as parameters for the OpenAI()-class
Issue: -
Dependencies: -
Tag maintainer: @baskaryan
Twitter @schop-rob

### CODE REVIEW

**Comment by baskaryan** [comment]
this is awesome! could we put this in the openai llm notebook instead of the generic quickstart? so in docs/extras/modules/model_io/llms/integrations/openai.ipynb (and if you want in docs/extras/modules/model_io/chat_models/integrations/openai.ipynb)

**Comment by schop-rob** [comment]
I have tried to implement your comment to the best of my ability, the user would have to read and decide which option applies to them, running all cells would not work anymore with this solution.

**Comment by baskaryan** [comment]
thanks for updating! could we comment out the organization code, or put it in markdown cells? so that that option is documented but not required

**Comment by schop-rob** [comment]
I have implemented your comment, the ORG_ID code is now part of markdown and no longer influences execution of these notebooks. On the documentation page, however, it looks like a normal code block. Let me know if this bothers you at all.

**Comment by baskaryan** [comment]
awesome, thanks @schop-rob

**Pull request merged**
