### PR TITLE
community[minor]: Add ScrapingAnt Loader Community Integration

### PR DESCRIPTION
**Pull request by kami4ka**
Added [ScrapingAnt](https://scrapingant.com/) Web Loader integration. ScrapingAnt is a web scraping API that allows extracting web page data into accessible and well-formatted markdown.

Description: Added ScrapingAnt web loader for retrieving web page data as markdown
Dependencies: scrapingant-client
Twitter: @WeRunTheWorld3

### CODE REVIEW

**Review by eyurtsev — APPROVED** [review]

**Comment by eyurtsev** [comment]
Hi @kami4ka -- failing on this lint: https://github.com/langchain-ai/langchain/issues/22866

**Comment by kami4ka** [comment]
> Hi @kami4ka -- failing on this lint: #22866

Thanks. Will adjust and push the changes!

**Comment by kami4ka** [comment]
@eyurtsev, it seems like I managed to fix those issues. Could you please take a look when you have time?

**Comment by kami4ka** [comment]
> Hi @kami4ka -- failing on this lint: #22866

@eyurtsev - it seems like everything is correct now, along with the checks. Thank you.

**Pull request merged**
