### PR TITLE
Import of `declarative_base` when SQLAlchemy <1.4

### PR DESCRIPTION
**Pull request by s16h**
In [pyproject.toml](https://github.com/hwchase17/langchain/blob/master/pyproject.toml), the expectation is `SQLAlchemy = "^1"`. But, the way `declarative_base` is imported in [cache.py](https://github.com/hwchase17/langchain/blob/master/langchain/cache.py) will only work with SQLAlchemy >=1.4. This PR makes sure Langchain can be run in environments with SQLAlchemy <1.4

### CODE REVIEW

**Comment by s16h** [comment]
In general, it feels like SQLAlchemy should be made to be an optional dependency. What do you think, @hwchase17?

**Comment by hwchase17** [comment]
> In general, it feels like SQLAlchemy should be made to be an optional dependency. What do you think, @hwchase17?

yeah let me take a look into that

im also fine just bumping the requirements to be "^1.4" - thoughts on that?

**Comment by s16h** [comment]
> im also fine just bumping the requirements to be "^1.4" - thoughts on that?

The move from 1.3 to 1.4 isn't trivial (i.e., it's not just a matter of upgrading, as I learnt earlier today). So, that'd possibly make life difficult for LangChain users —that's certainly the case for us.

**Comment by s16h** [comment]
I know you're busy with exciting stuff @hwchase17, but, thoughts on this? 😊

**Comment by hwchase17** [comment]
> I know you're busy with exciting stuff @hwchase17 (💪), but, thoughts on this? 😊

sorry for delay - agree this should be fixed. will get into the next release

**Pull request merged**
