### PR TITLE
Store and retrieve documents from remote instance

### PR DESCRIPTION
**Pull request by apurv101**
Replace this entire comment with:
  - Description: I have added documentation on how to create a remote instance of chromadb on AWS, store the documents in it, retrieve the documents from it and then query them using chains, 
  - Issue: NA,
  - Dependencies: NA,
  - Tag maintainer: @eyurtsev,
  - Twitter handle: NA

### CODE REVIEW

**Comment by baskaryan** [comment]
cc @jeffchuber

**Comment by jeffchuber** [comment]
@apurv101 thanks for the idea here! I'd rather point people to the deployment guide in Chroma's docs https://docs.trychroma.com/deployment - this also will make it easier for us (Chroma team) to maintain and make sure is up to date. I am not opposed to augmenting that with some of these ideas. Another useful idea is to add a link to the deployment docs here on langchain.

**Comment by apurv101** [comment]
I can link the client creation part to chroma docs. But the part where we
connect the remote client to langchain and query through a chain is still
missing in the docs.

**Comment by jeffchuber** [comment]
@apurv101 I think this section technically has the information? https://python.langchain.com/docs/integrations/vectorstores/chroma#basic-example-using-the-docker-container

Another idea would be to change the section to something more generic like "Connecting to a Remote Hosted Chroma" - and just not having the specific cloudformation instructions.

If there are things that would be helpful that are missing in Chroma's docs, we definitely welcome that PR! https://github.com/chroma-core/docs

**Comment by eyurtsev** [comment]
@jeffchuber Do you prefer to keep documentation on chroma side ot make sure it's up to date? If so, @apurv101 are you OK if we close the PR?

**Comment by apurv101** [comment]
Hi, yes I'm OK.

**Pull request closed without merging**
