### PR TITLE
Add support for Vertex ai multimodal embeddings

### PR DESCRIPTION
**Pull request by alexleventer**

### CODE REVIEW

**Comment by alexleventer** [comment]
Hey @rlancemartin - lmk if this is kind of what you had in mind. Thanks!

**Review by rlancemartin — COMMENTED** [review]
nice! can you please add a notebook (as shown [here](https://github.com/langchain-ai/langchain/pull/12754/files#diff-85145dbafe11ef6f778becf1993818dad38b591c39f9b5b83441ed4e775b25ab)).

**Comment by lkuligin** [comment]
thanks a lot for working on this! Why not to put it here:
https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/embeddings/vertexai.py

**Comment by alexleventer** [comment]
Example notebook added @rlancemartin

**Comment by holtskinner** [comment]
I agree with @lkuligin This should be added in the existing `VertexAIEmbeddings` class and just have a parameter for `model_name`. Depending on the model name, you'll use the PaLM or Gemini client.

**Comment by efriis** [comment]
Closing as stale. Should also be against integration package in https://github.com/langchain-ai/langchain-google if you decide to re-submit!

**Pull request closed without merging**
