### PR TITLE
add async support for llamacpp.py

### PR DESCRIPTION
**Pull request by dimaioksha**

### CODE REVIEW

**Comment by DmitryIo** [comment]
changed name and force-pushed to fyx typo in word "async"

**Comment by DmitryIo** [comment]
Fixes this issue: https://github.com/langchain-ai/langchain/issues/9865

**Comment by EgorovM** [comment]
i think we need it

**Comment by nfcampos** [comment]
Looks like a duplicate of https://github.com/langchain-ai/langchain/pull/9177

**Comment by DmitryIo** [comment]
> Looks like a duplicate of #9177

see it. Should I close this one?

**Comment by nfcampos** [comment]
I think so

**Comment by DmitryIo** [comment]
> I think so

ok, let me know if the https://github.com/langchain-ai/langchain/pull/9177 is not merged for a while, i'll do the fixes here and reopen this MR

**Comment by blademoon** [comment]
@mariansiwiak Hello. I seem to be having the same problem, only I'm having the IPython kernel crash (using a JupyterLab laptop). Can you please tell me how to solve this problem?

**Pull request closed without merging**
