### PR TITLE
Zep Authentication

### LINKED ISSUE #6282: LLMRequestsChain not enforcing headers when making http requests
### System Info

LangChain version 0.0.201

### Who can help?

@hwchase17 @agola

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Based on the documentation example, run the following script: 

```python
from langchain.llms import OpenAI
from langchain.chains import LLMRequestsChain, LLMChain
from langchain.prompts import PromptTemplate

template = """Here is a company website content :
    ----
    {requests_result}
    ----
    We want to learn more about a company's activity and the kind of
    clients they target. Perform an analysis and write a short summary.
"""

PROMPT = PromptTemplate(
    input_variables=["requests_result"],
    template=template,
)

chain = LLMRequestsChain(llm_chain = LLMChain(llm=OpenAI(temperature=0), prompt=PROMPT))

print(chain.requests_wrapper)

```

Gives 

```bash
python3 bug-langchain-requests.py
headers=None aiosession=None
```

### Expected behavior

Provided headers should be enforced

```bash
python3 bug-langchain-requests.py
headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'} aiosession=None
```

### PR DESCRIPTION
**Pull request by danielchalef**
## Description: Add Zep API Key argument to ZepChatMessageHistory and ZepRetriever
- correct docs site links
- add zep api_key auth to constructors

ZepChatMessageHistory: @hwchase17, 
ZepRetriever: @rlancemartin, @eyurtsev

### CODE REVIEW

**Comment by rlancemartin** [comment]
Thanks! Maybe you can also [re-run the notebook](https://github.com/hwchase17/langchain/blob/master/docs/extras/modules/data_connection/retrievers/integrations/zep_memorystore.ipynb) to confirm all is working following the update.

**Comment by danielchalef** [comment]
> Thanks! Maybe you can also [re-run the notebook]
 
@rlancemartin Good idea. Done!

**Comment by danielchalef** [comment]
@rlancemartin bump on this. Would love to get this merged as we have users interested in using authentication. Thanks!

**Comment by rlancemartin** [comment]
@danielchalef looks good! Can you rebase or merge `master`, resolve conflicts in `pyproject.toml` and then run `poetry lock --no-update` to re-generate `poetry.lock`? I can help if needed.

**Comment by danielchalef** [comment]
@rlancemartin Done. Waiting on CI tests to pass.

**Comment by rlancemartin** [comment]
Thanks! Hmm, still looks like a `poetry.lock` conflict?

**Comment by danielchalef** [comment]
> Thanks! Hmm, still looks like a `poetry.lock` conflict?

Weird. Looks like this happened over night. There wasn't a conflict yesterday. I've tried rebasing again but am up to date. Will delete and recreate the file.

**Comment by rlancemartin** [comment]
> > Thanks! Hmm, still looks like a `poetry.lock` conflict?
> 
> Weird. Looks like this happened over night. There wasn't a conflict yesterday. I've tried rebasing again but am up to date. Will delete and recreate the file.

Thanks, ya sorry about that. LMK if issues. I can also try on my end.

Usually just: 

```
checkout master poetry.lock
poetry lock --no-update
```

Should do it.

**Comment by danielchalef** [comment]
@rlancemartin done. no merge issues. tests are currently running.

**Comment by danielchalef** [comment]
Ugh. Fixing this. Two minutes

**Comment by rlancemartin** [comment]
Ha, ya. A lot of trouble w/ the `pyproject.toml` :P ... looks like all other tests are passing.

**Comment by danielchalef** [comment]
Yes. I keep running `poetry lock --no-update` and it doesn't produce a different output for the `pytproject` file I've checked in. The poetry.lock file has a different has to what is in master. And that's the _Only_ differernce.

**Comment by rlancemartin** [comment]
> Yes. I keep running `poetry lock --no-update` and it doesn't produce a different output for the `pytproject` file I've checked in. The poetry.lock file has a different hash to what is in master. And that's the _Only_ difference.
> 
> Would you mind taking it from here?

Looks like I can't push to your branch. But I checked out your branch and did this:

1/ sync for your fork w/ `master`
2/ on `master`, update with `git pull`
3/ on your branch (`zep-jwt-auth`): `git checkout master poetry.lock`
4/ then `poetry lock --no-update`

This should resolve it.

Maybe your master is a bit out of date?


 % git checkout master poetry.lock 
Updated 1 path from d43c1093
(langchain-new) 31treehaus@31s-MacBook-Pro langchain-fork % poetry lock --no-update

**Comment by rlancemartin** [comment]
> 1/ sync for your fork w/ `master` 2/ on `master`, update with `git pull` 3/ on your branch (`zep-jwt-auth`): `git checkout master poetry.lock` 4/ then `poetry lock --no-update`

I see the [same conflict](https://github.com/hwchase17/langchain/pull/6772) on another PR after doing the above. 

Just pinged @dev2049 on it.

**Comment by rlancemartin** [comment]
> > 1/ sync for your fork w/ `master` 2/ on `master`, update with `git pull` 3/ on your branch (`zep-jwt-auth`): `git checkout master poetry.lock` 4/ then `poetry lock --no-update`
> 
> I see the [same conflict](https://github.com/hwchase17/langchain/pull/6772) on another PR after doing the above.
> 
> Just pinged @dev2049 on it.

Was resolved by ensuring local `master` is up-to-date.

Can you confirm that in parallel w/ me getting https://github.com/hwchase17/langchain/pull/6772 in (to ensure no other issues)?

**Comment by danielchalef** [comment]
Doing so now. I'm a little confused why rebasing against upstream/master wasn't resolving this.

**Comment by rlancemartin** [comment]
> Doing so now. I'm a little confused why rebasing against upstream/master wasn't resolving this.

It should. https://github.com/hwchase17/langchain/pull/6772 is now fixed, too.

I think it's possible that your local `master` was out of date.

Looks like the conflict is resolved!

Let's get this in once tests pass. 

Sorry for the trouble.

**Pull request merged**
