### PR TITLE
feat: use latest duckduckgo_search API to call

### PR DESCRIPTION
**Pull request by Undertone0809**
# Provider the latest duckduckgo_search API

The Git commit contents involve two files related to some DuckDuckGo query operations, and an upgrade of the DuckDuckGo module to version 3.8.3. A suitable commit message could be "Upgrade DuckDuckGo module to version 3.8.3, including query operations". Specifically, in the duckduckgo_search.py file, a DDGS() class instance is newly added to replace the previous ddg() function, and the time parameter name in the get_snippets() and results() methods is changed from "time" to "timelimit" to accommodate recent changes. In the pyproject.toml file, the duckduckgo-search module is upgraded to version 3.8.3.

[duckduckgo_search readme attention](https://github.com/deedy5/duckduckgo_search): Versions before v2.9.4 no longer work as of May 12, 2023

## Who can review?

@vowelparrot

### CODE REVIEW

**Comment by Undertone0809** [comment]
@vowelparrot I run `poetry lock` command. But I have been running for a long time without any results. Is this normal?

image

**Comment by rrcgat** [comment]
Consider using the `-v|vv|vvv` option to gather more information, maybe it's a network issue.

Additionally, if you are using a generator, the type annotation for `get_snippets()` should be `Generator[str, None, None]`. Don't forget to update the `results()` function to use the latest API.

**Comment by Undertone0809** [comment]
@rrcgat Thanks

**Comment by Undertone0809** [comment]
@vowelparrot plz review

**Review by vowelparrot — APPROVED** [review]

**Pull request merged**
