### PR TITLE
Added Discord document loader

### PR DESCRIPTION
**Pull request by rajtilakjee**
- added discord.py in \langchain\document_loaders\
- modified langchain/document_loaders/__init__.py to accomodate discord.py

### CODE REVIEW

**Comment by rajtilakjee** [comment]
I am using Windows 11 and had some serious issues running Black. There is a known issue with it for Windows systems and I tried every solution given but its a no go. So even if the code is ready, I was unable to complete the common tasks involving Black starting with formatting the code, linting, etc.

**Review by hwchase17 — COMMENTED** [review]
i am more than happy to run black!

if i could ask one thing of you - could you add an example notebook to the documentation showing how to use?

**Comment by rajtilakjee** [comment]
Sure. GIve me some time.

**Comment by rajtilakjee** [comment]
Closing this PR since I found a better solution. Will submit a new PR soon. Apologies for all the confusion.

**Pull request closed without merging**
