### PR TITLE
[community] [Bugfix] base_o365 document loader metadata needs to be JSON serializable

### PR DESCRIPTION
**Pull request by MacanPN**
In order for indexer to work, all metadata in the documents need to be JSON serializable. Timestamps are not.

See here:
https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/indexing/api.py#L83-L89

@eyurtsev could you please review? It's a tiny PR :-)

### CODE REVIEW

**Comment by MacanPN** [comment]
@baskaryan , @efriis, @eyurtsev, @ccurme, @vbarda, @hwchase17 is anyone interested in picking up this tiny bugifx? Indxing documents from O365 loader does not work without it. Thanks!

**Comment by MacanPN** [comment]
Pretty pretty please @baskaryan , @efriis, @eyurtsev, @ccurme, @vbarda, @hwchase17 :-)

**Comment by efriis** [comment]
Hey! Here's a link to the review policy: https://python.langchain.com/docs/contributing/review_process/

Status is currently needs support

**Comment by MacanPN** [comment]
In case someone is looking at this and they would like to see a unit test, [here](https://github.com/langchain-ai/langchain/blob/3af4aababf976d1dfc41db7882df06fe9a59c838/libs/community/tests/unit_tests/document_loaders/parsers/test_excel_parsers.py) is the one I wrote. I am not including it in the PR since I'm having problems including `unstructured` in `pyproject.toml` without breaking some tests.

**Comment by petergoldstein** [comment]
Would love to see this fixed.  It's small and a relatively obvious bug.

**Comment by avalon-swain** [comment]
This would be a great fix

**Comment by MacanPN** [comment]
@efriis Could you please let me know what else can I do? There's 6 upvotes on the PR now, it's literally 2 lines of code (10 characters) and it keeps O365 loader from being index-able by Langchain Indexing.

**Review by ccurme — APPROVED** [review]

**Pull request merged**
