### PR TITLE
add Hybrid retriever that not require any external service

### PR DESCRIPTION
**Pull request by DayuanJiang**
- Until now, hybrid search was limited to modules requiring external services, such as Weaviate/Pinecone Hybrid Search. However, I have developed a hybrid retriever that can merge a list of retrievers using the [Reciprocal Rank Fusion](https://plg.uwaterloo.ca/~gvcormac/cormacksigir09-rrf.pdf) algorithm. This new approach, similar to Weaviate hybrid search, does not require the initialization of any external service.
  - Dependencies: No
  - Tag maintainer: @rlancemartin, @eyurtsev
  - Twitter handle: dayuanjian21687

### CODE REVIEW

**Comment by baskaryan** [comment]
@DayuanJiang this is awesome! What do you think of renaming it something like "EnsembleRetriever"? a bit clear than "hybrid", in my opinion

**Comment by DayuanJiang** [comment]
Hi @baskaryan. I appreciate your suggestion! I initially took inspiration from the term "hybrid search," but I completely agree that "EnsembleRetriever" is a more descriptive and fitting name for its capabilities. Thanks for your input!

I will soon update the name of this class to "EnsembleRetriever".

**Comment by DayuanJiang** [comment]
Hi @baskaryan.
The local lint check has been successfully passed, but an error has been raised by the online lint check without displaying its details. I have experienced this issue multiple times. Could you please guide me on accurately identifying the errors present in this code?

```poetry run mypy .
Success: no issues found in 1433 source files
poetry run black . --check
would reformat /home/runner/work/langchain/langchain/libs/langchain/tests/unit_tests/retrievers/test_hybrid_retriever.py

Oh no! 💥 💔 💥
1 file would be reformatted, [14](https://github.com/langchain-ai/langchain/actions/runs/5651480853/job/15309649962?pr=8108#step:7:15)35 files would be left unchanged.
make: *** [Makefile:77: lint] Error 1
Error: Process completed with exit code 2.
```

**Comment by baskaryan** [comment]
> Hi @baskaryan. The local lint check has been successfully passed, but an error has been raised by the online lint check without displaying its details. I have experienced this issue multiple times. Could you please guide me on accurately identifying the errors present in this code?
> 
> ```
> Success: no issues found in 1433 source files
> poetry run black . --check
> would reformat /home/runner/work/langchain/langchain/libs/langchain/tests/unit_tests/retrievers/test_hybrid_retriever.py
> 
> Oh no! 💥 💔 💥
> 1 file would be reformatted, [14](https://github.com/langchain-ai/langchain/actions/runs/5651480853/job/15309649962?pr=8108#step:7:15)35 files would be left unchanged.
> make: *** [Makefile:77: lint] Error 1
> Error: Process completed with exit code 2.
> ```

not sure why local lint was passing, but just had to run `make format` to fix a formatting issue!

**Pull request merged**
