### PR TITLE
Added source (paper pdf link) in result generated by load method of the ArxivAPIWrapper.

### PR DESCRIPTION
**Pull request by keenborder786**
Replace this comment with:
  - Description: Added source (paper pdf link) in result generated by load method of the ArxivAPIWrapper.
  - Issue: #7666
  - Tag maintainer:  @rlancemartin, @eyurtsev

### CODE REVIEW

**Comment by dcieslak19973** [comment]
Just curious about the merge process for this project - who/what decides when an MR gets merged?

**Comment by keenborder786** [comment]
@dcieslak19973 
Usually the tag-maintainers are responsible for reivews and merging the PRs.

**Comment by dcieslak19973** [comment]
@rlancemartin / @eyurtsev - would you be able to review / merge this sometime next week?

**Comment by keenborder786** [comment]
@rlancemartin / @eyurtsev any updates???

**Comment by leo-gan** [comment]
@keenborder786 Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Pull request closed without merging**
