### PR TITLE
Add Other File Utilities

### PR DESCRIPTION
**Pull request by vowelparrot**
Add other File Utilities, include
- List Directory
- Search for file
- Move
- Copy
- Remove file

Bundle as toolkit
Add a notebook that connects to the Chat Agent, which somewhat supports multi-arg input tools
Update original read/write files to return the original dir paths and better handle unsupported file paths.
Add unit tests

Update Chat OutputParser to handle the case where the LLM outputs an action followed by a false "final answer" string - > strip the action first and run with that.

### CODE REVIEW

**Comment by rick2047** [comment]
This extremely cool!! Since you have thought so much about this already, do you think it's possible to make a tool which can edit files in a given region. Something like if the agent wants to modify a function, it shouldn't be rewriting the whole file, just the method. This way we can ask agents to do more complex things without running out of context windows.

**Comment by vowelparrot** [comment]
> This extremely cool!! Since you have thought so much about this already, do you think it's possible to make a tool which can edit files in a given region. Something like if the agent wants to modify a function, it shouldn't be rewriting the whole file, just the method. This way we can ask agents to do more complex things without running out of context windows.

That's a great question! I've hacked something to do this but am not sure the most general way at the moment. Probably something with search -> chunks -> edit chunks -> rewrite?

**Comment by rick2047** [comment]
I have been looking into the AST approach. Do you think that should be a different tool? Like PythonCodeTool or something. I have some time to make this but am having trouble how to get started. Writing the functionality is simple but making a tool out of it is a bit tricky for me. Could use some guidance like how do I test this? Can't think of a minimal task.

**Comment by rick2047** [comment]
Best thing I could find was the `inspect` module, but it only allows us to get information about code, not write it.

**Comment by Ryangr0** [comment]
Wouldn't grep and sed work or something? Could just abstract the use of a bash script into a tool.

**Comment by rick2047** [comment]
> Wouldn't grep and sed work or something? Could just abstract the use of a bash script into a tool.

I was thinking about this, but I think the agent should have enough data about the file in the current system to figure out where to edit. Or am I putting too much faith in the model?

**Comment by vowelparrot** [comment]
Yeah grep and sed are some of the next tools to implement

**Pull request merged**
