### PR TITLE
openai: add text-to-speech

### PR DESCRIPTION
**Pull request by h0rv**
Description: I implemented a tool to use OpenAI text-to-speech API.

Issue: Related issue: https://github.com/langchain-ai/langchain/issues/15900 (can update issue to include all `speech` endpoints).

Dependencies: I had to update the `openai` library because some of the endpoint values were out of date with the current docs (specifically response format). 

Twitter handle: No Twitter, but do have [LinkedIn](https://www.linkedin.com/in/robby-horvath/) lol.

---

# Relevant Docs

- [Overview](https://platform.openai.com/docs/guides/text-to-speech)
- [API](https://platform.openai.com/docs/api-reference/audio/createSpeech)
- [TTS Models](https://platform.openai.com/docs/models/tts)

### CODE REVIEW

**Comment by h0rv** [comment]
I have it saving the audio file locally in `./tts/{name}.{format}` right now. Would it be a good idea to add a flag to also save the corresponding text to `./tts/{name}.txt`?

**Comment by h0rv** [comment]
I am not familiar with pytest mocking. Can I get some help on how to mock the `openai` call:

```py
response = openai.audio.speech.create(...)
```

Or would it be better to monkey patch this because its not a direct `request` call?

Thanks for thelp

**Comment by h0rv** [comment]
Hi @efriis , this is ready for review!

**Review by baskaryan — APPROVED** [review]

**Comment by h0rv** [comment]
Can look into standardizing some of the API from the work reviewed on https://github.com/langchain-ai/langchain/pull/18880

**Comment by h0rv** [comment]
Hi @eyurtsev, @efriis, this is ready for a review! I fixed the API to match https://github.com/langchain-ai/langchain/pull/18880

**Comment by h0rv** [comment]
Hi @eyurtsev and @efriis, watching the GPT-4o demo right now - would be great to get this merged!

**Review by eyurtsev — CHANGES_REQUESTED** [review]
Hi @h0rv I am not sure that this tool is re-usable enough for us to commit it into the partner package.

This looks more like a model abstraction that LangChain should start providing at some point rather than a tool. And the implementation should likely not touch the file system at all -- with this logic being left up to user code

**Pull request closed without merging**
