### PR TITLE
experimental: handle cases in LLMGraphTransformer where head or tail is None or a list

### PR DESCRIPTION
**Pull request by memgonzales**
- **Description**:

   When using `LLMGraphTransformer` on some Wikipedia articles, there are cases where `rel["head"]` or `rel["tail"]` are `None` or are lists. For example, I encountered a case where `rel["tail"]` is a list of countries like so: `[Philippines, Cambodia, China]`. These cases are currently unhandled, causing `process_response()` to crash.

   This pull request bundles two changes:
   1. Skip the entry if either is `None`.
   2. If `rel["tail"]` is a list but `rel["head"]` is not, then we connect `rel["head"]` to every item in `rel["tail"]`. A similar logic is followed if `rel["head"]` is the one that is a list. If both are lists, then the items in `rel["head"]` and the items in `rel["tail"]` are connected in a pairwise fashion.

- **Issue**:
   No issue found

- **Dependencies**:
  N/A

- **Twitter handle**: 
  `@memgonzales`

### CODE REVIEW

**Comment by memgonzales** [comment]
@baskaryan just wanted to follow up on this PR. Thanks!

**Comment by ingmars1709** [comment]
I use this change also locally. When can we expect it to be merged?

**Comment by memgonzales** [comment]
@eyurtsev I merged `master` into this PR. 
Could I request a review? Thanks!

**Comment by ingmars1709** [comment]
I recently came across a document where the invocation `rel["tail_type"]` resulted in a `KeyError`, because the `tail_type` key itself was not present in the `rel` datastructure. 

An addition on this fix would be that you also check on the presence of keys using `get`, e.g.: `rel.get("tail_type") != None`

**Comment by baskaryan** [comment]
cc @tomasonjo

**Comment by efriis** [comment]
closing and feel free to reopen against the langchain-experimental repo (this package moved)! https://github.com/langchain-ai/langchain-experimental

@tomasonjo a few PRs have been opened attempting to address this - would be great to get some eyes on a fix!

**Pull request closed without merging**
