### PR TITLE
community: Added python package install Tool

### PR DESCRIPTION
**Pull request by reachusama**
# community: Added python package install **Tool**

## Description:

**PackageInstallTool**: A Dynamic Python Package Installer for Runtime Environments

**Overview**: The `PackageInstallTool` is an essential utility for dynamically installing Python packages within a runtime environment. This tool is especially beneficial in scenarios where executing Python code necessitates the use of specific packages that are not already available in the environment.

**Functionality**: 
- **Package Installation**: It allows for the installation of single or multiple Python packages. Users can input either a single package name or a list of package names.
- **Flexibility and Error Handling**: It supports both synchronous and asynchronous operations, although the asynchronous functionality is not implemented yet. The tool also includes error handling to provide feedback in case of installation issues.

**Use Case**: This tool is ideal for environments where Python code execution is dynamic, and there's a need to ensure that all necessary packages are available. It's particularly useful in interactive or automated systems where code dependencies might vary.

**How It Works**: 
1. **Input**: The tool accepts a package name or a list of package names as input.
2. **Installation Process**: It uses the `subprocess` module to call `pip install`, ensuring that the packages are installed in the current Python environment.
3. **Feedback**: Post-installation, it provides feedback on the success or failure of the installation process.

**Benefits**: 
- **Enhanced Efficiency**: Automates the package installation process, saving time and reducing manual effort.
- **Improved Reliability**: Ensures that the necessary Python packages are available when needed, enhancing the reliability of Python code execution.

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
can we add some documentation (in the form of a jupyter notebook along with the other integrations) so that people can see an example of how to use it? a bit unclear in my mind atm

**Comment by reachusama** [comment]
@hwchase17 Please let me know what you think about this. 

If this is worth announcing, I do not use twitter but I use LinkedIn here: [Usama Shahid](https://www.linkedin.com/in/reach-usama/)

**LinkedIn username:** reach-usama
**Personal blog:** reachusama.com

**Comment by reachusama** [comment]
@hwchase17

**Review by hwchase17 — COMMENTED** [review]
thanks, its more clear. can you resolve merge conflicts? also - would be good if possible to have the example actually run the python code - that would be cool!

**Comment by reachusama** [comment]
@hwchase17 I have resolved the conflicts and already ran the Python code, as seen [here](https://langchain-cxo4lqpui-langchain.vercel.app/docs/integrations/tools/package_installer) :-)

**Comment by hwchase17** [comment]
> @hwchase17 I have resolved the conflicts and already ran the Python code, as seen [here](https://langchain-cxo4lqpui-langchain.vercel.app/docs/integrations/tools/package_installer) :-)

yeah but not as part of the agent. it would be WAY more powerful if it was run as part of the agent. would be even more powerful if you showed an initial example of running it WITHOUT this tool, showing that it errored, then running it again WITH the tool to show that it fixes it

**Comment by hwchase17** [comment]
going to close as i am not 100% sure of the benefit of this tool

**Pull request closed without merging**
