### PR TITLE
Add OpenAI Whisper Audio Loader

### PR DESCRIPTION
**Pull request by tyumentsev4**
- Description: Introducing an ability to load a transcription document of audio file using OpenAI Whisper
- Issue: None
- Dependencies: None
- Tag maintainer: @rlancemartin, @eyurtsev

### CODE REVIEW

**Comment by tyumentsev4** [comment]
@rlancemartin, @eyurtsev

**Comment by tyumentsev4** [comment]
> Hi @tyumentsev4! Thanks for the contribution! What is the goal of this PR?
> 
> Here's the current implementation in langchain for handling audio transcription
> 
> https://python.langchain.com/docs/integrations/document_loaders/youtube_audio

Hi @eyurtsev! I think it would be nice to have an interface for loading transcripts of audio files located in the file system.

**Comment by eyurtsev** [comment]
Hi @tyumentsev4 thanks for the contribution! We're moving away from having a class for every thing loader in favor of more generic loaders like the `GenericLoader`. 

This loader:

https://api.python.langchain.com/en/latest/document_loaders/langchain.document_loaders.generic.GenericLoader.html


```python

 from langchain.document_loaders.parsers.pdf import PyPDFParser

  # Recursively load all text files in a directory.
  loader = GenericLoader.from_filesystem(
      "/path/to/dir",
      glob="**/*.pdf",
      parser=PyPDFParser()
  )
```

provides more features and allows swapping out the parsers.

**Comment by eyurtsev** [comment]
@tyumentsev4 I'm closing the PR since we're trying to move away from this pattern of class per use case to instead favor composition of smaller standard building blocks

**Pull request closed without merging**
