### PR TITLE
gradient.ai LLM intregration

### PR DESCRIPTION
**Pull request by michaelfeil**
DRAFT

- **Description:** This PR implements a new LLM API to https://gradient.ai 
- **Issue:** Feature request for LLM #10745 
- **Dependencies**: No additional dependencies are introduced. 
- **Tag maintainer:** I am opening this PR for visibility, once ready for review I'll tag.

- ```make format && make lint && make test``` is running.
- added a `integration` and `mock unit` test.

### CODE REVIEW

**Comment by baskaryan** [comment]
feel free to ping when it's ready for review!

**Comment by Atry** [comment]
It would also be nice to wrap the fine-tuning API as a tool, useful when the agent wants to remember something permanently.

**Comment by Atry** [comment]
But Langchain has Memory backends, which seem similar to the concept of fine-tuning when the purpose is to remember information.

**Comment by Atry** [comment]
To be clear, my comment is just an idea, not specific to this PR. The PR looks good to me, although I am not a maintainer of Langchain.

**Comment by baskaryan** [comment]
looks great, thanks @michaelfeil!

**Pull request merged**
