### PR TITLE
docs: added region parameter for awsBedrockParamsOrDefault in ChatModelTabs.js

### PR DESCRIPTION
**Pull request by Bhargav2525**
Thank you for contributing to LangChain!

- [X] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, etc. is being modified. Use "docs: ..." for purely docs changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [X] **PR message**: 
    - **Description:**This PR contains the change in docs for in chatModelTabs.js In default parameters of awsBedrockParamsOrDefault, region should be mandatory for ChatBedRock
    - without region getting this validation error, so region should be there
   
image    
image
    
- **Twitter handle:** https://twitter.com/BhargavPrince18

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Comment by efriis** [comment]
in general the docs recommend setting this in an environment variable (similar to access creds), so will close this instead of adding to that block!

**Comment by Bhargav2525** [comment]
Everyone do that only, but people need to know right they have to use region parameter inside ChatBedRock. I am following the docs and I got the error, It took almost 20 min for me to understand that I have to give region parameter inside AwsBedrockParams. Let's give atleast region parameter remove us-east-1 value and users will give whatever they want

**Comment by efriis** [comment]
Got it. We can consider linking the [api ref](https://python.langchain.com/api_reference/aws/chat_models/langchain_aws.chat_models.bedrock.ChatBedrock.html#langchain_aws.chat_models.bedrock.ChatBedrock.region_name) for the overall classes in the tabs, but in general these tabs aren't for documenting the end-to-end use of the provider - they're just showing how the chat mdoels are used in each

**Comment by Bhargav2525** [comment]
so can i link api references to the model classes in each tab
image

**Pull request closed without merging**
