### PR TITLE
Google Scholar Search Tool using serpapi

### PR DESCRIPTION
**Pull request by keenborder786**
- **Description:** Implementing the Google Scholar Tool as requested in PR #11505. The tool will be using the [serpapi python package](https://serpapi.com/integrations/python#search-google-scholar). The main idea of the tool will be to return the results from a Google Scholar search given a query as an input to the tool.

- **Tag maintainer:** @baskaryan, @eyurtsev, @hwchase17

### CODE REVIEW

**Comment by keenborder786** [comment]
@baskaryan please review

**Comment by baskaryan** [comment]
looks great @keenborder786! could we add a notebook example to the docs

**Comment by keenborder786** [comment]
@baskaryan sure I will update the docs as well.

**Comment by keenborder786** [comment]
@baskaryan please review now. I have added docs and had to resolve some conflicts with the master.

**Comment by keenborder786** [comment]
@baskaryan, any updates....

**Comment by keenborder786** [comment]
@baskaryan

**Comment by baskaryan** [comment]
lgtm, thank you @keenborder786!

**Pull request merged**
