### PR TITLE
Pgvector template

### PR DESCRIPTION
**Pull request by manuel-soria**
Including pvector template, adapting what is covered in the [cookbook](https://github.com/langchain-ai/langchain/blob/master/cookbook/retrieval_in_sql.ipynb).

### CODE REVIEW

**Review by efriis — DISMISSED** [review]
Think this should work now! Thanks @manuel-soria . If you have a minute in the coming days, it would be great to have an ingestion script that fills some dummy data (or a `docker run postgres` command in the readme that populates a usable schema for testing).

Otherwise this will work for now, mostly for people that already have a postgres db they want to connect to!

**Comment by efriis** [comment]
Hey @manuel-soria ! Why did you undo my changes? They're necessary to get this merged.

**Comment by manuel-soria** [comment]
> Hey @manuel-soria ! Why did you undo my changes? They're necessary to get this merged.

@efriis  Sorry I didn't mean to! I think we pushed at the exact same moment, or maybe I screwed up when Lance said you couldn't push. Please go ahead and

**Comment by manuel-soria** [comment]
> Think this should work now! Thanks @manuel-soria . If you have a minute in the coming days, it would be great to have an ingestion script that fills some dummy data (or a `docker run postgres` command in the readme that populates a usable schema for testing).
> 
> Otherwise this will work for now, mostly for people that already have a postgres db they want to connect to!

@efriis I will work on that!

**Pull request merged**
