### PR TITLE
community: `YoutubeLoader` refactor & unit tests by @lsloan

### PR DESCRIPTION
**Pull request by lsloan**
**_Note_**: This PR is still in **_Draft_** mode. I've not yet completed all the requirements for an acceptable PR. I will clean up this description and move the PR to ready status when the time is right.
---
Thank you for contributing to LangChain!

- [x] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [ ] **PR message**: ***Delete this entire checklist*** and replace with
    - **Description:** a description of the change
    - **Issue:** PR #22815
      - That is a **_PR_** containing a bugfix that should be merged before this one.
    - **Dependencies:** any dependencies required for this change
    - **Twitter handle:** if your PR gets announced, and you'd like a mention, we'll gladly shout you out!

- [ ] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [ ] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Comment by lsloan** [comment]
Although I mentioned a bugfix for the `YoutubeLoader`'s `LINES` format bug in my first commit on this branch, I've decided it's more important to get that bug addressed ASAP and not be delayed by waiting for work on refactoring and unit tests.

I've opened #22815 to address the bug on its own with the hope that it will be merged quickly.

**Comment by baskaryan** [comment]
hi @lsloan, are you still working on this one?

**Comment by lsloan** [comment]
Yes, I am.  Apologies for the delay.. I expect to get back to it soon.

**Comment by efriis** [comment]
closing as stale - feel free to reopen as a full PR when you're ready for a review! While you're just working, would recommend opening PRs within your own fork to track your own progress, and only open against the main repo when you're ready for a review!

**Comment by lsloan** [comment]
OK.  Thank you for the advice and your patience.

**Pull request closed without merging**
