### PR TITLE
community: update QuipLoader to support return text instead of html format

### PR DESCRIPTION
**Pull request by shufanhao**
**Description:** 
By default, the quip API return doc as html format, this PR is to support parse html as text to stripe html format.

### CODE REVIEW

**Comment by shufanhao** [comment]
no idea why part of jobs are failure, can someone who can help ?

**Comment by hwchase17** [comment]
happy to help fix this. what is the command to install the required python package?

**Comment by shufanhao** [comment]
@hwchase17 thanks, python package: 
```
pip install quip_api
pip install beautifulsoup4
```
Also I have another PR https://github.com/langchain-ai/langchain/pull/15305, would you also help ? No python package will be installed.

**Comment by shufanhao** [comment]
@eyurtsev can you help to review PR ?

**Comment by shufanhao** [comment]
@baskaryan, @eyurtsev, @hwchase17 can you help review this PR ? it was in pending a couple of weeks. thanks.

**Comment by shufanhao** [comment]
@baskaryan, @eyurtsev, @hwchase17 mind help to take a look this PR ? I was not sure why test failure only happened on python3.10 extended tests.

**Comment by baskaryan** [comment]
@shufanhao how do we install `quip_api`? not seeing it on PyPi

**Comment by shufanhao** [comment]
> @shufanhao how do we install `quip_api`? not seeing it on PyPi

what's your mean of not seeing on PyPi ? 

install quip_api: 
```
pip install quip_api
pip install beautifulsoup4
```

**Comment by baskaryan** [comment]
> > @shufanhao how do we install `quip_api`? not seeing it on PyPi
> 
> what's your mean of not seeing on PyPi ?
> 
> install quip_api:
> 
> ```
> pip install quip_api
> pip install beautifulsoup4
> ```

strange, i get
```
ERROR: Could not find a version that satisfies the requirement quip_api (from versions: none)
ERROR: No matching distribution found for quip_api
```

**Comment by shufanhao** [comment]
> > > @shufanhao how do we install `quip_api`? not seeing it on PyPi
> > 
> > 
> > what's your mean of not seeing on PyPi ?
> > install quip_api:
> > ```
> > pip install quip_api
> > pip install beautifulsoup4
> > ```
> 
> strange, i get
> 
> ```
> ERROR: Could not find a version that satisfies the requirement quip_api (from versions: none)
> ERROR: No matching distribution found for quip_api
> ```

hmm, can you share me the whole logs ? I just tried and installed it successfully. 
```
> pip3 install quip_api
Collecting quip_api
  Using cached quip_api-1.2-py3-none-any.whl
Installing collected packages: quip_api
Successfully installed quip_api-1.2
```

**Comment by shufanhao** [comment]
close this PR and created a new one.

**Pull request closed without merging**
