### PR TITLE
Langchain: `json_chat` don't need stop sequenes

### PR DESCRIPTION
**Pull request by lin-calvin**
This is a PR about #16334
The Stop sequenes isn't meanful in `json_chat` because it depends json to work, not completions

### CODE REVIEW

**Comment by steve-carpenter** [comment]
FYI looks like you removed `llm_with_stop` but still reference it when defining the agent.

**Comment by hwchase17** [comment]
this generally is meaningful
im happy to make this optional to better support other models (seems like that was an issue)
lets maybe add a boolean flag for this, and dcoument it well?

**Comment by calvinweb** [comment]
> this generally is meaningful im happy to make this optional to better support other models (seems like that was an issue) lets maybe add a boolean flag for this, and dcoument it well?

But json_chat is depends on json,not the "Observation" string

**Comment by calvinweb** [comment]
> FYI looks like you removed `llm_with_stop` but still reference it when defining the agent.

Sry, forget to test the code before push

**Comment by hwchase17** [comment]
oftentimes the model hallucinates an Observation. we need this on by default

**Comment by calvinweb** [comment]
> oftentimes the model hallucinates an Observation. we need this on by default

So add a flag is the best soluation?

**Comment by hwchase17** [comment]
yup

**Comment by calvinweb** [comment]
> yup

Edited,or should I fire a new PR?

**Review by hwchase17 — APPROVED** [review]

**Pull request merged**
