### PR TITLE
[Feat] Add ChatModel, LLM, and Embeddings for ERNIE Bot APIs 

### PR DESCRIPTION
**Pull request by Bobholamovic**
- **Description:** 
      - Add `langchain.llms.ERNIEBot` for text completion.
      - Add `langchain.chat_models.ChatERNIEBot` for chat completion.
      - Add `langchain.embeddings.ERNIEBotEmbeddings` for sentence embeddings.
      - Integration tests and example notebooks on the new features are included in this PR, too.
  - **Issue:** None.
  - **Dependencies:** 
      - `erniebot`
  - **Tag maintainer:** @baskaryan 
  - **Twitter handle:** None.

## Differences from the existing integrations

In #9114 , #9370 , and #10496 , several integrations have been contributed to LangChain, all claiming to support Baidu's ERNIE Bot (文心一言) large language models. Taking chat models as an example, currently we have two similar chat models in LangChain to interact with ERNIE Bot APIs: `langchain.chat_models.ErnieBotChat` and `langchain.chat_models.QianfanChatEndpoint`. This pull request, however, is going to add a third one, `langchain.chat_models.ERNIEBotChat`. Here is a clarification on how the new integrations introduced in this PR differ from the existing ones.

1. The integrations introduced in this PR are enhancements to those introduced in #9114 and #9310 in the following aspects:

- The new integrations are implemented based on the official [ERNIE Bot Python SDK](https://github.com/PaddlePaddle/ERNIE-Bot-SDK), which provides additional safety and robustness, whereas the existing ones are implemeneted with raw `request` APIs.
- A new LLM, `langchain.llms.ERNIEBot`, is introduced for text completion.
- More advanced features are supported, e.g. asynchronous calling, streaming, function calling.
- More examples are added in three Jupyter Notebooks, including the examples on the usage of the advanced features.

2. The new integrations provide a way for [AI Studio](https://aistudio.baidu.com/index) users to access the ERNIE Bot APIs in LangChain, while for users of the Qianfan platform, the integrations introduced in #10496 should be the right choice.

3. The new integrations do not support the models in #10024 , as these models are not strictly ERNIE Bot models, and including them in `langchain.chat_models.ErnieBotChat` can make users confused. What's more, the `langchain.chat_models.QianfanChatEndpoint` contributed in #10496 already provides access to these models, and it is not necessary to include them again in another integration.

### CODE REVIEW

**Comment by baskaryan** [comment]
can we improve the existing classes instead of adding new ones? if the underlying integration is fundamentally there's no reason to have redundant classes

**Comment by Bobholamovic** [comment]
Sure. I've added some commits to this pull request, and here is the improvement:

I removed the exsiting implementations of `langchain.chat_models.ErnieBotChat` and `langchain.embeddings.ErnieEmbeddings`, and left deprecation notes in their documentation. The reasons behind this are:

1. The functionality of `langchain.chat_models.ErnieBotChat` and `langchain.embeddings.ErnieEmbeddings` is already covered by `langchain.chat_models.QianfanChatEndpoint` and `langchain.embeddings.QianfanEmbeddingEndpoint`. Since these APIs allow Qianfan platform users to call the ERNIE Bot LLM, I think the `QianfanChatEndpoint` and `QianfanEmbeddingEndpoint` are clearer in naming. So I removed the existing `ErnieBotChat` and `ErnieEmbeddings`.
2. The newly added chat and embeddings models, named `ChatERNIEBot` and `ERNIEBotEmbeddings`, are used to replace the removed `ErnieBotChat` and `ErnieEmbeddings`. The new integrations offer enhanced features and allow AI Studio users to use ERNIE Bot. Now `ChatERNIEBot` and `QianfanChatEndpoint` coexist in LangChain, one for Qianfan users and the other for AI Studio users. There is no overlap.

@axiangcoding Please also take a look at this PR and see if the modifications are appropriate. Thanks!

**Comment by axiangcoding** [comment]
@Bobholamovic 
I'm excited to see these changes! But please see if it is necessary to retain the original class name for migration? 
As far as I know, there are already a number of users using the old class names, and a sudden update may cause unexpected problems.

**Comment by NuODaniel** [comment]
@Bobholamovic  glad to t

**Comment by Bobholamovic** [comment]
> @Bobholamovic I'm excited to see these changes! But please see if it is necessary to retain the original class name for migration? As far as I know, there are already a number of users using the old class names, and a sudden update may cause unexpected problems.

This is a good suggestion. I've renamed the classes for compatibility issues. Please take a look.

**Comment by Bobholamovic** [comment]
> @Bobholamovic Glad to see this PR about ERNIE-Bot, I've done some similar change in this #10830. Maybe we could merge these two PR into one? Looking forward to your reply. @baskaryan

Yes, it would be nice if we can merge these two PRs, as we are doing similar jobs. Having said so, I've found the following differences between the two PRs. Please take a look:

1. In #10830 , a pair of Qianfan AK and SK are used for authentication, which makes `ErnieBot` and `ErnieBotChat` functionally the same as `QianfanLLMEndpoint` and `QianfanChatEndpoint`. This might introduce redundency in APIs.
2. In this PR, an additional retry policy is implemented for the LLM and chat bot integrations, which helps the program to recover from unexpected failures of HTTP requests.
3. Unit tests for function calling are missing from this PR.

**Comment by axiangcoding** [comment]
> > @Bobholamovic I'm excited to see these changes! But please see if it is necessary to retain the original class name for migration? As far as I know, there are already a number of users using the old class names, and a sudden update may cause unexpected problems.
> 
> This is a good suggestion. I've renamed the classes for compatibility issues. Please take a look.

I recommend compatibility with the configuration items of `ERNIE_CLIENT_ID` and `ERNIE_CLIENT_SECRET`, and prompt a warning log like `deprecated, use xxx instead`. 

Others LGTM.

**Comment by Bobholamovic** [comment]
> > > @Bobholamovic I'm excited to see these changes! But please see if it is necessary to retain the original class name for migration? As far as I know, there are already a number of users using the old class names, and a sudden update may cause unexpected problems.
> > 
> > 
> > This is a good suggestion. I've renamed the classes for compatibility issues. Please take a look.
> 
> I recommend compatibility with the configuration items of `ERNIE_CLIENT_ID` and `ERNIE_CLIENT_SECRET`, and prompt a warning log like `deprecated, use xxx instead`.
> 
> I noticed that client now use ai access token to proceed request. If the above configuration is not compatible, at least let user know, like a error log.
> 
> Others LGTM.

Done. Please see the latest update.

**Comment by axiangcoding** [comment]
@Bobholamovic i think it will works just fine for me! thanks for the update!

**Comment by Bobholamovic** [comment]
> > @Bobholamovic Glad to see this PR about ERNIE-Bot, I've done some similar change in this #10830. Maybe we could merge these two PR into one? Looking forward to your reply. @baskaryan
> 
> Yes, it would be nice if we can merge these two PRs, as we are doing similar jobs. Having said so, I've found the following differences between the two PRs. Please take a look:
> 
> 1. In [Refactor(ernie): support function_call, reimplment ernie_bot with erniebot SDK. #10830](https://github.com/langchain-ai/langchain/pull/10830) , a pair of Qianfan AK and SK are used for authentication, which makes `ErnieBot` and `ErnieBotChat` functionally the same as `QianfanLLMEndpoint` and `QianfanChatEndpoint`. This might introduce redundency in APIs.
> 2. In this PR, an additional retry policy is implemented for the LLM and chat bot integrations, which helps the program to recover from unexpected failures of HTTP requests.
> 3. Unit tests for function calling are missing from this PR.

@NuODaniel PTAL. Thanks.

**Comment by NuODaniel** [comment]
> > > @Bobholamovic Glad to see this PR about ERNIE-Bot, I've done some similar change in this #10830. Maybe we could merge these two PR into one? Looking forward to your reply. @baskaryan
> > 
> > 
> > Yes, it would be nice if we can merge these two PRs, as we are doing similar jobs. Having said so, I've found the following differences between the two PRs. Please take a look:
> > 
> > 1. In [Refactor(ernie): support function_call, reimplment ernie_bot with erniebot SDK. #10830](https://github.com/langchain-ai/langchain/pull/10830) , a pair of Qianfan AK and SK are used for authentication, which makes `ErnieBot` and `ErnieBotChat` functionally the same as `QianfanLLMEndpoint` and `QianfanChatEndpoint`. This might introduce redundency in APIs.
> > 2. In this PR, an additional retry policy is implemented for the LLM and chat bot integrations, which helps the program to recover from unexpected failures of HTTP requests.
> > 3. Unit tests for function calling are missing from this PR.
> 
> @NuODaniel PTAL. Thanks.

LGTM, there will be no redundancy between ERNIE and Qianfan. I will cancel my PR later. I recommend adding unit tests or an notebook sample for function calling in this PR.

**Comment by Bobholamovic** [comment]
> I recommend adding unit tests or an notebook sample for function calling in this PR.

@NuODaniel  Thanks for your suggestion. I've included function calling tests in this PR. 

A new description of what's introduced in this PR is as follows:

* Add `langchain.llms.ErnieBot` for text completion.
* Enhance `langchain.chat_models.ErnieBotChat` and `langchain.embeddings.ErnieEmbeddings`. 
    * The new implementation introduces more advanced features, such as streaming, asynchronous generation, and function calling. 
    * The code is refactored to base on the official ERNIE Bot SDK, which provides additional safety and robustness.
    * The overlap between `langchain.chat_models.ErnieBotChat`/`langchain.embeddings.ErnieEmbeddings` and `langchain.chat_models.QianfanChatEndpoint`/`langchain.embeddings.QianfanEmbeddingEndpoint` is eliminated. `ErnieBotChat`/`ErnieEmbeddings` is now intended to be used by AI Studio users, while `QianfanChatEndpoint`/`QianfanEmbeddingEndpoint` is designed for Qianfan users.
    * The documentation is improved. More examples are added in notebooks, including the examples on the usage of the advanced features.

@baskaryan Please take a look.

**Comment by Bobholamovic** [comment]
I have addressed the issues in linting. The CI workflow should succeed this time. Please take a look @baskaryan

**Comment by Bobholamovic** [comment]
The conflicts have been resolved.

**Comment by Bobholamovic** [comment]
Hi @baskaryan , can you take a look at this PR? Active updates to the LangChain repo are frequently causing conflits in this branch with the base branch. It would be great if we could resolve this PR early, before more conflicts arise.

**Comment by Bobholamovic** [comment]
This PR is ready for CI and review. @baskaryan PTAL. Thank you!

**Comment by axiangcoding** [comment]
any update on this PR? it appears delay for a while.

**Comment by Bobholamovic** [comment]
> any update on this PR? it appears delay for a while.

@axiangcoding All CI checks were successful, but new contributions to the master branch yesterday caused new conflicts. I have just merged changes from the master branch and resolved the conflicts. 

@baskaryan Can you please review the code? It's been weeks since the PR was proposed, and it would be great if we could resolve this PR early, before more conflicts arise. Thank you!

**Comment by Bobholamovic** [comment]
@baskaryan @hwchase17 Hi, sorry for the frequent pinging, but given that it's been literally a month since your last comment, can you please provide some more feedback (for example, this PR is not suitable for merging / this PR needs further updates / there is a problem with this PR), so that we can move on to the next step. Thanks.

**Comment by Bobholamovic** [comment]
PTAL @baskaryan

**Comment by Bobholamovic** [comment]
@baskaryan Looking forward to your reply.

**Comment by sijunhe** [comment]
Hi @baskaryan . Hope everything is well! 
We would greatly appreciate it if we could push this PR forward, as we have eager users from the ErnieBot community eagerly anticipating this implementation. We will be happy to address any remaining issues or concerns that you may have.

**Comment by baskaryan** [comment]
Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

**Comment by Bobholamovic** [comment]
> Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

Hi, I've resolved the conflicts. Please take a look.

**Comment by Bobholamovic** [comment]
The checks have passed. PTAL

**Comment by ou-bing** [comment]
@Bobholamovic Hello, I have found that many chat models do not implement the `bind_tools` method. Is there any special reason for this?

**Comment by Bobholamovic** [comment]
> @Bobholamovic Hello, I have found that many chat models do not implement the `bind_tools` method. Is there any special reason for this?

I'm not sure, but I'm guessing the reason could be that not all chat models support tool calling.

**Comment by ou-bing** [comment]
> > @Bobholamovic Hello, I have found that many chat models do not implement the `bind_tools` method. Is there any special reason for this?
> 
> I'm not sure, but I'm guessing the reason could be that not all chat models support tool calling.

Will you implement tool use related methods for `ChatERNIEbot`😄

**Comment by axiangcoding** [comment]
@ou-bing The `ChatERNIEBot` is deprecated by me. You can move to `QianfanChatEndpoint`. 
As for the `bind_tools` method, you can open a new issue for it.

**Comment by ou-bing** [comment]
> @ou-bing The `ChatERNIEBot` is deprecated by me. You can move to `QianfanChatEndpoint`. As for the `bind_tools` method, you can open a new issue for it.

I noticed that both `QianfanChatEndpoint` and `ErnieBotChat` exist in LangChain's documentation, Will these two continue to coexist for a long time?

**Comment by axiangcoding** [comment]
And @Bobholamovic , why this PR never merged? I thought it was merged long time ago...

This PR is meaningless at the moment, a pity. But i think you can help with `QianfanChatEndpoint`, some forks from Baidu is maintaining it.

**Comment by axiangcoding** [comment]
> > @ou-bing The `ChatERNIEBot` is deprecated by me. You can move to `QianfanChatEndpoint`. As for the `bind_tools` method, you can open a new issue for it.
> 
> I noticed that both `QianfanChatEndpoint` and `ErnieBotChat` exist in LangChain's documentation, Will these two continue to coexist for a long time?

`ErnieBotChat` will be removed in version 0.2.x, as stated in the documentation. I can't guarantee this though, it's something the langchain team decides, I'm just a contributor.

But i recommand move to `QianfanChatEndpoint`, some guys from Baidu are maintaining it.

**Pull request closed without merging**
