### PR TITLE
`fallback` definition

### PR DESCRIPTION
**Pull request by leo-gan**
I've added a definition to `fallback` and fixed couple misspells. It was not really clear what is the "fallback".

### CODE REVIEW

**Comment by leo-gan** [comment]
@hwchase17  Could you, please, review it?

**Comment by leo-gan** [comment]
@baskaryan Could you, please, review it?

**Comment by leo-gan** [comment]
@hwchase17 Could you, please, review it?
# testing this messaging. 95% probability that these messages are lost

**Review by hwchase17 — APPROVED** [review]
thanks

**Pull request merged**
