### PR TITLE
Create the partition if provided

### PR DESCRIPTION
**Pull request by byte911**

### CODE REVIEW

**Comment by baskaryan** [comment]
Thanks @byte911 for contribution! Could you provide a bit more detail on what this does?

**Comment by byte911** [comment]
@baskaryan I would like to insert text into a partition, and I hope that the partition can be automatically created if it does not exist. In some conditions, the collection and the partition will be created dynamically.
```
milvus = Milvus()
milvus.add_texts(..., partition_name="par1")
```

**Comment by tsingmao** [comment]
@byte911 A partition should be a list, and I believe it not only needs to be supported during automatic creation, but also in search

**Comment by filip-halt** [comment]
@byte911 As @tsingmao mentioned, in order to use the partitions there are quite a bit more changes that need to be made. Partitions need to be created, data needs to be inserted into them, and searches need to be directed at them. What is the use case for these partitions?

**Comment by leo-gan** [comment]
@byte911 Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

If this PR is not needed anymore, could you, please, let me know or close this PR?

**Comment by efriis** [comment]
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

**Pull request closed without merging**
