### PR TITLE
[OpenSearch] Add Self Query Retriever Support to OpenSearch

### PR DESCRIPTION
**Pull request by naveentatikonda**
### Description
Add Self Query Retriever Support to OpenSearch

### Maintainers
@rlancemartin, @eyurtsev, @navneet1v

### Twitter Handle
@OpenSearchProj

### CODE REVIEW

**Review by navneet1v — APPROVED** [review]

**Comment by baskaryan** [comment]
amazing, thanks @naveentatikonda !

**Comment by raghuragz47** [comment]
We dont see the changes on the latest langchain release. release #: 0.0.304

**Comment by naveentatikonda** [comment]
> @rlancemartin, @eyurtsev @baskaryan @naveentatikonda @navneet1v We dont see the changes on the latest langchain release. release #: 0.0.304

@raghuragz47 it is released an hour ago in v0.0.305

**Comment by dharmkumar61** [comment]
@rlancemartin, @eyurtsev @baskaryan @naveentatikonda @navneet1 Langchain is using "term" query to do the filter in the vector search . Is there a way to change it to "match" query or Change the Comparator default value from "term" to "match".
query='***' filter=Comparison(comparator=<Comparator.EQ: 'eq'>, attribute='***', value='****') limit=None . Any help will be appreciated .

**Comment by navneet1v** [comment]
@dharmkumar61 you can use : `Comparator.CONTAIN` which will use `match` query clause instead of `term` query clause.
Ref: https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/self_query/opensearch.py#L39

If you have some other thoughts in mind to improve please do let us know, we can have those changes.

**Comment by dharmkumar61** [comment]
@navneet1v  Thanks for your reply. Is there a way to pass this Comparator.CONTAIN as a parameter when we call 
SelfQueryRetriever.from_llm() or do we have to create custom Translater  and pass as a parameter to structured_query_translator.

**Pull request merged**
