### PR TITLE
community: refactor the type hint of `file_path` in `UnstructuredAPIFileLoader` class

### PR DESCRIPTION
**Pull request by kozistr**
* **Description**: add `None` type for `file_path` along with `str` and `List[str]` types.
    * `file_path`/`filename` arguments in `get_elements_from_api()` and `partition()` can be `None`, however, there's no `None` type hint for `file_path` in `UnstructuredAPIFileLoader` and `UnstructuredFileLoader` currently.
    * calling the function with `file_path=None` is no problem, but my IDE annoys me lol.
* **Issue**: N/A
* **Dependencies**: N/A

### CODE REVIEW

**Comment by kozistr** [comment]
@baskaryan. hi! I made a small change to the type hint! could you please check this PR? thank you

**Comment by kozistr** [comment]
hello! @efriis could you please check this PR when you are available? thanks for your time

**Review by baskaryan — COMMENTED** [review]
out of curiosity, what's loaded if file_path is None

**Comment by kozistr** [comment]
> out of curiosity, what's loaded if file_path is None

I use `file` argument instead of `file_path` to input the file-like object! 

here's an example.

```
documents: list[Document] = UnstructuredAPIFileLoader(
    file_path=None,
    file=file,  # file-like object, io.BytesIO type
    mode='elements',
    url=<unstructured-io API server URL>,
    content_type=content_type,
    metadata_filename='asdf.pdf',  # example
).load_and_split()
```

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
