### PR TITLE
community: Add groq chat model

### PR DESCRIPTION
**Pull request by gradenr**
Description: Add a Groq chat model
issue: TODO
Depdendencies: groq
Twitter handle: N/A

### CODE REVIEW

**Review by efriis — COMMENTED** [review]
Hey @gradenr ! Thoughts on converting this to a partner package / assuming you work at groq?

Community packages don't hook into the same level of integration testing, and given there's an sdk, would be better suited to one of those!

https://python.langchain.com/docs/contributing/integrations#partner-packages

**Comment by gradenr** [comment]
I am happy to move this to a partner package.

**Comment by efriis** [comment]
Amazing. Will close this for now, and feel free to reopen (or new PR) for the partner package!

Would also recommend fetching the latest master - looks like there are some conflicts already on this.

Could you also add a provider page for groq in docs/docs/integrations/providers/groq.mdx?

**Comment by gradenr** [comment]
New PR: https://github.com/langchain-ai/langchain/pull/17856

**Pull request closed without merging**
