### PR TITLE
community: Replace pypdf2 import with pypdf

### PR DESCRIPTION
**Pull request by Cokral**
Replace the dependency PyPDF2 with PyPDF. PyPDF2 is an old fork from PyPDF which hasn't been updated for 11years.

### CODE REVIEW

**Comment by leo-gan** [comment]
It makes sense. But Don't we need to validate it somehow?

**Comment by Cokral** [comment]
What do you think we should validate? I don't think we want to test that external packages work as expected, no?

**Comment by ulgens** [comment]
Where `PyPDF2` coming in the first place? I couldn't find it as dependency.

**Comment by efriis** [comment]
Hey there! This PR is against a deprecated community integration that has moved to a dedicated integration package.

I'll close it, and feel free to reopen against the integration package! https://github.com/langchain-ai/langchain-google

Fwiw I think this is a good change. Although PyPDF's docs don't make it easy to figure out which import to use!

**Pull request closed without merging**
