### PR TITLE
core: adding Sentence Window Retrieval to VectorStoreRetriever

### PR DESCRIPTION
**Pull request by rsk2327**
Thank you for contributing to LangChain!

- [x] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

Description : 
The PR implements the Sentence Window Retrieval method as one of the search types for VectorStoreRetriever.

Issue : No issues. Is a feature addition

Dependencies : No dependencies 

- [x] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, hwchase17.

### CODE REVIEW

**Comment by rsk2327** [comment]
@eyurtsev @baskaryan Would be great to get your inputs on how to scale this up to other databases as its only done for FAISS right. Should I include shell implementations for the other databases that raise NotImplementedError for now?

Also, could you help with debugging the linting errors here? 

`langchain_community/vectorstores/faiss.py:823: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[floating[_32Bit]]]", variable has type "List[float]")  [assignment]`
This is the exact same line of code at line 196 as well but that doesnt throw an error

`langchain_community/vectorstores/faiss.py:839: error: Item "str" of "Union[str, Document]" has no attribute "page_content"  [union-attr]`
Not sure why this throws an error either. page_content is an attribute of Document

**Comment by rsk2327** [comment]
@eyurtsev @hwchase17 @baskaryan @efriis Could I get a review on this?

**Review by Undertone0809 — APPROVED** [review]

**Comment by Undertone0809** [comment]
need to add test to assert it.

**Comment by rsk2327** [comment]
> need to add test to assert it.

@Undertone0809 Are you referring to general unit tests for this or for asserting the FAISS database requirement for the current implementation? For the latter, I do implement a check in the validate_search_type root_validator for the VectorStoreRetriever class.

**Review by baskaryan — COMMENTED** [review]
could we add some docs explaining how this works / why it's useful? can add to /docs/docs/integrations/vectorstores/faiss.ipynb

**Comment by rsk2327** [comment]
> could we add some docs explaining how this works / why it's useful? can add to /docs/docs/integrations/vectorstores/faiss.ipynb

Added detailed description of the method and how its useful, along with examples on how to run it

**Comment by rsk2327** [comment]
@baskaryan @eyurtsev @efriis Can i get a review on this?

**Comment by rsk2327** [comment]
@baskaryan  @eyurtsev @efriis @hwchase17

**Review by eyurtsev — CHANGES_REQUESTED** [review]
Hi @rsk2327, thank you for the contribution!

We're very cautious about adding additional functionality to the vectorstores interfaces. The interface is already very large and any additional methods just complicate it and make it more confusing.

In this case, the technique can be implemented generally without touching the vectorstore interface by combining a document store with a vectorstore.

**Comment by eyurtsev** [comment]
You could try to implement using: https://python.langchain.com/docs/modules/data_connection/retrievers/parent_document_retriever/

**Comment by rsk2327** [comment]
@eyurtsev Im aware that this introduces a change to a key component and thats why I was extra cautious of the implementation, making sure to use existing functions and only add methods in the vector database's code and not in the VectorStore's implementation. 

As you could see, most of the implementation is in the FAISS.py file and not so much in VectorStore. Im happy to work with you to ensure that the VectorStore implementation isnt affected by this change. I feel that this is the right place to add this functionality because it is alternative to Similarity Search and MMR, so it should ideally be included as an option at the same level. 

But if you still have concerns then I can implement it separately as a separate Retriever class instead.

**Comment by eyurtsev** [comment]
Hi @rsk2327, we'll likely going to move in the opposite direction in the future and remove methods like `mmr` from the vectorstores. We still haven't speced out to do this, so I don't have good advice for that right now, but we want to move in direction of reducing vectorstore interface.

What's needed for the implementation of this search technique is access to a document store + a way to implement nearest neighbor search by embedding. I believe this can be done using a parent retriever, and it immediately applies across all vectorstore implementations.

**Comment by rsk2327** [comment]
@eyurtsev Okay, if thats the case then it makes more sense to implement this as a separate retriever class. I will set that up instead. Thanks for reviewing this.

**Pull request closed without merging**
