### PR TITLE
feat: helper function to filter metadata for Chroma

### PR DESCRIPTION
**Pull request by MthwRobinson**
### Summary

Adds a utility function to filter complex (i.e. list, dict) metadata from documents. This is helpful because some vector dbs such as Chroma do not support loading list metadata. Currently, if your `Document` has a metadata item that's a list, you get the following when you run `Chroma.from_documents`. 

```python
File ~/.pyenv/versions/chromadb/lib/python3.10/site-packages/chromadb/api/types.py:140, in validate_metadata(metadata)
    138     # isinstance(True, int) evaluates to True, so we need to check for bools separately
    139     if not isinstance(value, bool) and not isinstance(value, (str, int, float)):
--> 140         raise ValueError(
    141             f"Expected metadata value to be a str, int, float or bool, got {value} which is a {type(value)}"
    142         )
    143 return metadata

ValueError: Expected metadata value to be a str, int, float or bool, got [{'text': 'CNN', 'url': '/'}] which is a <class 'list'>
```

The helper function operates on `Document` objects and you can call it like this.

```python
from langchain.vectorstore.utils import filter_complex_metadata

updated_documents = filter_complex_metadata(documents)
```

### Testing

Confirmed the notebook in [this `unstructured` PR](https://github.com/Unstructured-IO/unstructured/pull/1054) runs on the feature branch, where previously it failed. Additionally, run the following to execute the unit test:

`pytest tests/unit_tests/vectorstores/test_utils.py`

### Reviewers

- @rlancemartin 
- @eyurtsev
- @hwchase17

### CODE REVIEW

**Comment by baskaryan** [comment]
hm i wonder if this should be explicitly handled by users outside Chroma. silently changing the docs that are stored may be confusing. with explicit user handling outside Chroma, users can also use some document management of their own to be able to reconstruct docs stored in Chroma

cc @jeffchuber in case you also have thoughts

**Comment by MthwRobinson** [comment]
@baskaryan - 100% okay from my end to handle this as a preprocessing step prior to loading into Chroma. In that case would this be worth putting in [`vectorstores/utils.py`](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/utils.py)?

**Comment by eyurtsev** [comment]
Placing in vectorstore/utils.py makes sense to me. Would it help to catch the exception from chroma and re-raise it adding an explanation together with a proposal to use the metadata filter or else to massage the metadata more?

**Comment by MthwRobinson** [comment]
@eyurtsev - Moved the filter function to utils and added the error handling logic you suggested. Confirmed the following behavior:

1. `Chroma.from_documents(docs, embeddings)` raises the error with the suggestion when there's list metadata
2. `Chroma.from_documents(docs, embeddings)` loads successfully after running `filter_complex_metadata`
3. `Chroma.from_documents(docs, embeddings)` runs successfully if there's not list metadata present

**Comment by baskaryan** [comment]
landed in #9015, thank you @MthwRobinson!

**Pull request closed without merging**
