### PR TITLE
update Qdrant documentation

### PR DESCRIPTION
**Pull request by meal**
fix `from_documents` method usage for Qdrant in documentation as previous example doesn't work

### CODE REVIEW

**Review by dev2049 — COMMENTED** [review]
comment about kwargs isn't quite right. whether or not Qdrant overwrote from_documents, everything other than docs and embeddings would still have to be kwargs

**Comment by NirantK** [comment]
Looks good to me. Changes summary: 

1. Removed `prefer_grpc=True`
2. Added a note about the `from_documents` endpoint in Langchain — not specific to qdrant
3. Changed url to a kwarg with `url=url`

**Comment by joein** [comment]
Why `prefer_grpc` has been removed?

**Comment by dev2049** [comment]
> Why `prefer_grpc` has been removed?

also wondering 👆

**Comment by NirantK** [comment]
Not all APIs are implemented in gRPC yet. The official qdrant README doesn't recommend this as a _starting option_ either

```python
from qdrant_client import QdrantClient
qdrant = QdrantClient(":memory:") # Create in-memory Qdrant instance, for testing, CI/CD
# OR
client = QdrantClient(path="path/to/db")  # Persists changes to disk, fast prototyping
```

In Client-Server:
```
qdrant = QdrantClient("http://localhost:6333") # Connect to existing Qdrant instance, for production
```

That said, it should be fine both ways — gRPC will indeed be faster for insert/upsert kind of operations.

**Comment by leo-gan** [comment]
@meal Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that ping me and I push this PR for the review. Thanks!

**Pull request merged**
