### PR TITLE
integrate JinaChat

### PR DESCRIPTION
**Pull request by delgermurun**
Integration with https://chat.jina.ai/api. It is OpenAI compatible API.

- Twitter handle: [https://twitter.com/JinaAI_](https://twitter.com/JinaAI_)

cc @hwchase17, @baskaryan

### CODE REVIEW

**Comment by dev2049** [comment]
nice! if jina plans to stay in sync with openai chat api we could probably simplify this by inheriting from ChatOpenAI directly and overwriting some of the credential keys

**Comment by delgermurun** [comment]
@dev2049, thanks for looking it up so quickly.

Inheriting was also on my mind, but some properties and options aren't supported by `JinaChat`. API request payload and response schema is similar but not 1 to 1.

At the moment, `JinaChat` does not have any "model" parameter and does not support "n" options or "functions", no `proxy` etc.

**Comment by delgermurun** [comment]
Hi @dev2049, I've added a documentation notebook and fixed the lint error.
Could you please take another look at it? Thank you very much.

**Review by hwchase17 — APPROVED** [review]
thanks!

**Comment by baskaryan** [comment]
thanks @delgermurun!!

**Pull request merged**
