### PR TITLE
Adding LLM wrapper for Kobold AI

### PR DESCRIPTION
**Pull request by ausboss**

### CODE REVIEW

**Comment by baskaryan** [comment]
very cool! could we add example notebooks for these, in docs/extras/modules/model_io/models/llms/integrations/

**Comment by ausboss** [comment]
> very cool! could we add example notebooks for these, in docs/extras/modules/model_io/models/llms/integrations/

Sure! Do you want it doing anything in particular? I included a colab that showed it generating text.

**Comment by baskaryan** [comment]
> > very cool! could we add example notebooks for these, in docs/extras/modules/model_io/models/llms/integrations/
> 
> Sure! Do you want it doing anything in particular? I included a colab that showed it generating text. I can add more to it. Or if you guys want to make it. Just tell me what to do boss.

a quick snippet about the integration and showing main functionality should be enough! if you want to  e.g. https://github.com/hwchase17/langchain/blob/master/docs/extras/modules/model_io/models/llms/integrations/openai.ipynb

separately, adding docstrings to the classes / class parameters would be nice as well

**Comment by Malrama** [comment]
IIRC there already is support for "oobabooga". It's the TextGen() LLM. Works pretty well!

**Comment by ausboss** [comment]
> What is the benefit of this implementation?

This is my first time hearing about that so none probably haha. What about KoboldAI?

**Comment by Malrama** [comment]
> > What is the benefit of this implementation?
> 
> This is my first time hearing about that so none probably haha. What about KoboldAI?

KoboldAI I don't know. That probably needs implementation. But "oobabooga" can then be removed from here?

**Comment by ausboss** [comment]
- duplicate wrapper removed
- docstrings added
- example added

**Comment by baskaryan** [comment]
looks great, thanks @ausboss!

**Pull request merged**
