### PR TITLE
SQLite-backed Entity Memory

### PR DESCRIPTION
**Pull request by JoseHervas**
# SQLite-backed Entity Memory

Following the initiative of https://github.com/hwchase17/langchain/pull/2397 I think it would be helpful to be able to persist Entity Memory on disk by default

## Who can review?

Community members can review the PR once tests pass. Tag maintainers/contributors who might be interested:

@dev2049

### CODE REVIEW

**Comment by dev2049** [comment]
thanks @JoseHervas, looks like a good start! would it be possible to add an example notebook?

**Comment by JoseHervas** [comment]
Hey @dev2049 for sure 👍 

Here's the example notebook: [docs/modules/memory/examples/entity_memory_with_sqlite.ipynb](https://github.com/hwchase17/langchain/pull/5129/files#diff-f39916945254521085808cc91458013ba79530ca546a5642628b936e2dc5d262)

**Comment by dev2049** [comment]
lgtm, thanks @JoseHervas!

**Comment by glondrej** [comment]
I think SQLiteEntityStore class is missing "conn" property.

**Pull request merged**
