### PR TITLE
[Feat] Abstract class for a while loop chain

### PR DESCRIPTION
**Pull request by avinashselvam**
Implements #314 

Would be great if someone can let me know what more test cases to write and also if the `BaseWhileChain` is sufficient

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
would be great to have an example notebook for this! whats a good use case?

**Comment by avinashselvam** [comment]
Some use cases I could think of
1. The trivial - iterate through a list of inputs.
2. Repeatedly summarising/expanding till a certain word count is met.
3. Changing the tone of text till a classifier deems it good.

But some of these require the state update to use inner chain's output as well.

If you've got any ideas I'd be happy to implement them as an example notebook.

**Comment by vowelparrot** [comment]
We should bake in a "max_iterations" argument (Optional[int]) to this with a default of something like 4 or 5 so a user doesn't accidentally create an infinite loop.

**Comment by dev2049** [comment]
+1 on adding an example notebook!

**Comment by baskaryan** [comment]
stale, closing for now but feel free to reopen @avinashselvam if you come back to it!

**Pull request closed without merging**
