### PR TITLE
community: Refactor PebbloRetrievalQA

### PR DESCRIPTION
**Pull request by Raj725**
**Refactor PebbloRetrievalQA**
  - Created `APIWrapper` and moved API logic into it.
  - Created smaller functions/methods for better readability.
  - Properly read environment variables.
  - Removed unused code.
  - Updated models

**Issue:** NA
**Dependencies:** NA
**tests**:  NA

### CODE REVIEW

**Comment by Raj725** [comment]
@eyurtsev @ccurme Please review

**Review by ccurme — APPROVED** [review]
Lots of breaking changes here but will assume this is desired given your association with Daxa.

**Comment by ccurme** [comment]
I'm assuming none of the LangChain code displayed on this page will require changes? https://www.daxa.ai/pebblo :)

**Comment by Raj725** [comment]
> Lots of breaking changes here but will assume this is desired given your association with Daxa.

Thanks for the feedback! I understand there are breaking changes, but these were intentional to improve overall structure and readability, and they've been thoroughly tested.

**Comment by Raj725** [comment]
> I'm assuming none of the LangChain code displayed on this page will require changes? https://www.daxa.ai/pebblo :)

@ccurme Thanks for going the extra mile! 😊 I appreciate your attention to detail. No changes are needed for the LangChain code on that page. 👍

**Pull request merged**
