### PR TITLE
added more examples for chatbots and question answering

### PR DESCRIPTION
**Pull request by mikayelh**
# More end-to-end examples with LangChain 🚀 

Hiya, I added more examples for chatbots and question answering 
1. [JarvisBase](https://github.com/peterw/JarvisBase): An end-to-end Customer Support assistant that transcribes user voice, performs Question Answering over a scraped documentation base, & answers in natural language. 
2. [PDF Analysis Slack Chatbot](https://github.com/hollaugo/slack-financial-analysis-chatbot): Build an end-to-end Slack chatbot that chats with multiple PDF files (financial analysis in this case).
3. [Question Answering over multiple PDFs](https://www.activeloop.ai/resources/ultimate-guide-to-lang-chain-deep-lake-build-chat-gpt-to-answer-questions-on-your-financial-data/): An intro guide for building a chat with multiple PDFs solution.

# Who can review?

forgot to tag @hwchase17 - sorry!

### CODE REVIEW

**Comment by hwchase17** [comment]
for the time being, i think we're going to try to keep most examples linked to in the Use Case section to example that are jupyter notebooks in the repo (that we can edit/modify as needed)

We can add these all under `awesome-langchain-projects` though!

**Comment by mikayelh** [comment]
Not an issue, let me re-upload with notebooks!

**Comment by MateiG** [comment]
Adding the notebooks for the aforementioned examples. They include markdown and python code blocks for ease of understanding.

[JarvisBase](https://drive.google.com/file/d/1t3iXQY_mVdS5btseHq28q3TIHJ-BhpGi/view?usp=drive_link): An end-to-end Customer Support assistant that transcribes user voice, performs Question Answering over a scraped documentation base, & answers in natural language.
[PDF Analysis](https://drive.google.com/file/d/1VytRZ4QwotdS9_nxJR5vxr-MFVM6XFh5/view?usp=drive_link): Chat with multiple PDF files (financial analysis in this case).
[Youtube2Blog](https://drive.google.com/file/d/1QO7Q7Yw53v4ROzj9TBa3hvCd6ZYnc2XJ/view?usp=sharing): Using Langchain and Deep Lake to convert a series of Youtube videos into a single concise blog post.

**Comment by mikayelh** [comment]
@hwchase17 hiya! We've updated the docs keeping the requested formatting - now everything is within the LangChain repo. Would you mind going over these again?

**Pull request closed without merging**
