### PR TITLE
Relative paths in prompt loading

### PR DESCRIPTION
**Pull request by mwinterde**
# Resolve relative paths in prompt loading

## Problem Statement

Currently, `langchain.prompts.load_prompt` requires that the `path` variables of configuration files are relative to the current working directory. This requirement has disadvantages when we want to use the same configuration files in different places of a project. Therefore, it seems to be more practical to define the `path` variables relative to the configuration file than to the current working directory.

For illustration, let's take the `few_shot_prompt_example_prompt.json` example from the docs:
```
{
    "_type": "few_shot",
    "input_variables": ["adjective"],
    "prefix": "Write antonyms for the following words.",
    "example_prompt_path": "example_prompt.json",
    "examples": "examples.json",
    "suffix": "Input: {adjective}\nOutput:"
}   
```
With the current implementation, `load_prompt("few_shot_prompt_example_prompt.json")` will only work if the files `example_prompt.json` and `examples.json` lie in our current working directory:
```
CWD
few_shot_prompt_example_prompt.json
example_prompt.json
examples.json
```
That is, in the following scenario `load_prompt("examples/few_shot_prompt_example_prompt.json")` wouldn't work:

```
CWD
|-- examples
|   |-- few_shot_prompt_example_prompt.json
|   |-- example_prompt.json
|   |-- examples.json
```

## Changes

- Temporarily adding the parameter `prompt_dir` (the parent directory of the configuration file) to the `config` dict
- Using this parameter to resolve relative paths when loading templates, example prompts and examples
- Removing the parameter from the `config` dict before the initialization of the final prompt template
- Changing the working directory of respective unit tests to test the capability of `load_prompt` to deal with relative path definitions

## Remarks

- There may be more elegant ways of dealing with this issue, but I haven't seen an option that wouldn't involve a major restructuring of the module. Any ideas?
- While I think this a valuable change, it may break existing applications of some users

### CODE REVIEW

**Comment by dev2049** [comment]
could you already achieve this with absolute paths?

**Comment by mwinterde** [comment]
> could you already achieve this with absolute paths?

You mean by specifying absolute paths in the `few_shot_prompt_example_prompt.json`? If so, it would help if the code is only used on one platform, but portability would become a problem. But maybe I'm misunderstanding your comment.

**Comment by mwinterde** [comment]
To concretize my suggestion a little bit more:

If we assume the project structure from above:
```
CWD
|-- examples
|   |-- few_shot_prompt_example_prompt.json
|   |-- example_prompt.json
|   |-- examples.json
```

Currently, if I want to call `load_prompt("examples/few_shot_prompt_example_prompt.json")`from the working directory,  `few_shot_prompt_example_prompt.json` needs to take the following form:
```
{
    (...)
    "example_prompt_path": "examples/example_prompt.json",
    "examples": "examples/examples.json",
    (...)
}   
```

From my perspective it would be more intuitive and practical if it needs to take the following form:
```
{
    (...)
    "example_prompt_path": "example_prompt.json",
    "examples": "examples.json",
    (...)
}   
```

**Comment by leo-gan** [comment]
@mwinterde Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

**Pull request closed without merging**
