### PR TITLE
Added template_format to from_template_file

### PR DESCRIPTION
**Pull request by htahboub**
Issue: #10519

There is no clear reason for `PromptTemplate.from_template` and `PromptTemplate.from_file` to be implemented so differently. I added the ability to `PromptTemplate.from_file` to infer `input_variables` from the template when they are not given by using the new `template_format` parameter. Also made sure to maintain backward compatibility. Added a few tests for the new functionality.

### CODE REVIEW

**Comment by HTahboub** [comment]
Hey @baskaryan, was wondering if you had a chance to check these changes out?

**Comment by HTahboub** [comment]
@baskaryan just pinging in case this was missed.

**Comment by sradu** [comment]
I've been meaning to try out LCEL and all my templates are jinja. Would love to have this committed so I can run `ChatPromptTemplate` with it.

**Comment by HTahboub** [comment]
@eyurtsev maybe you can take a look?

**Comment by HTahboub** [comment]
Closing pull request as it was ignored and the code has changed a lot since. Can't keep updating this PR hoping it will be pulled one day.

**Pull request closed without merging**
