### PR TITLE
docs: Fix pixelation in stack graphic

### PR DESCRIPTION
**Pull request by gkermit**
This change updates the stack graphic displayed in the top-level README. The LangChain tile is pixelated in the current graphic.

### CODE REVIEW

**Comment by gkermit** [comment]
@efriis

**Comment by gkermit** [comment]
@hwchase17

**Comment by gkermit** [comment]
@efriis

**Comment by efriis** [comment]
Which browser are you using, and why does this fix it for that browser?

On macos chrome this doesn't change anything

**Comment by efriis** [comment]
Doesn't look different in my version (17.4.1) of safari either :(

Would love to understand the change, and generally not opposed as long as it won't create issues in other browsers! Appreciate the contribution

**Review by efriis — APPROVED** [review]
oh fascinating - in safari it renders differently in github.com (the top-level readme you called out), but not when hosted in the python.langchain.com docs.

Will merge it in, and if you can spare a minute to explain how we can make this not happen in the future, that would be super helpful!

I believe these were just exported from figma.

**Comment by gkermit** [comment]
Thanks for taking a look! I also found it confusing while verifying my change. The svg file was pixelated only when hosted on github. Rendering the original file in a browser by itself showed no issues. I fixed it by opening the file in adobe illustrator and reexporting it. No other changes.

**Comment by efriis** [comment]
Well if it works it works 🤷 

Thanks @gkermit for the fix!

**Pull request merged**
