### PR TITLE
Use EggTimer to simplify timeout logic

### PR DESCRIPTION
**Pull request by mssalvatore**
## Description

[EggTimer](https://pypi.org/project/egg-timer/) is a simple Python library that makes handling timeouts easier. Instead of tracking time elapsed, start times, and performing calculations, using EggTimer is a simple as `timer = EggTimer(); timer.set(TIMEOUT)`. Timeout can be checked by calling `timer.is_expired() -> bool`.

This PR modifies the `Agent` and `BlockchainDocumentLoader` to use EggTimer.

## A note about dependencies

I don't think there's a way to make this dependency optional, since it's used by the Agent. LMK if there's something different I should do.

## Tag Maintainer
Agents: @vowelparrot 
DataLoaders: @rlancemartin @eyurtsev

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
this is cool, but not sure we want to introduce a new dependency for this

**Comment by mssalvatore** [comment]
> this is cool, but not sure we want to introduce a new dependency for this

@hwchase17 Yeah, I hear you. It is a fairly light-weight and stable dependency, though.

Pros:
- Makes the code easier to read
- Reduces the risk of defects surrounding timer logic
- Reduces duplicate timout logic
- Sets a precedent. As LangChain continues to grow, there's likely to be more timers. Starting to use this now could keep future timer-related code simpler and help reduce defects.
- EggTimer handles edge cases most developers may not think of. For example, what happens to the code in this PR if the system clock is changed during the timeout window? What is the impact of that behavior? That issue can be simply resolved without EggTimer, but with EggTimer you don't need to worry about it.

Cons:
- New dependency

It's up to you whether or not the benefits are worth the cost. Writing timeouts is not rocket science; duplicating the timeout logic throughout the code is unlikely to result in a catastrophic failure down the road.

**Comment by leo-gan** [comment]
@mssalvatore Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by mssalvatore** [comment]
@leo-gan Looks like there are some failures because `AgentIterator` calls a protected method on `AgentExecutor`, which breaks encapsulation.

https://github.com/langchain-ai/langchain/blob/5272e42b0de2a056271ebea8245cba1e29863621/libs/langchain/langchain/agents/agent_iterator.py#L475-L476

Options are:
1. Don't do that! Handle this logic within `AgentIterator` itself.
2. Make `AgentExecutor._should_continue()` public
3. Something else?

**Comment by efriis** [comment]
Hey @mssalvatore ! Appreciate your work on egg timer. I tend to agree with Harrison that the value of an extra dependency is unclear here, so i'll close this PR.

Happy to reevaluate as the egg-timer community grows, or the value-add story to langchain becomes clearer and larger.

**Pull request closed without merging**
