### PR TITLE
Upgrade to Pydantic v2

### PR DESCRIPTION
**Pull request by srhinos**
This PR should encompass (most of) the changes needed to support [Pydantic v2](https://docs.pydantic.dev/2.0/blog/pydantic-v2-final/)

Relevant Issue: https://github.com/langchain-ai/langchain/issues/6841

Dependency wise, had to bump Pydantic (ofc) and `autodoc-pydantic` which has a yanked 2.0.0 pypi deploy which is being used as a Release Candidate for pydantic v2 support.

Currently, the following deps are preventing poetry from resolving a lock file:
- zep-python (issue opened here - https://github.com/getzep/zep-python/issues/58)
- octoai-sdk (closed source xdd)
- chromadb (issue opened here - https://github.com/chroma-core/chroma/issues/893)
- spacy (issue here - https://github.com/explosion/spaCy/issues/12611)
- steamship (issue opened here - https://github.com/steamship-core/python-client/issues/503)
- langsmith (closed source xdd)

@baskaryan

Opened as a draft because until poetry resolves the lock file and downstream packages get resolved, it shouldn't be merged.

Also since PR guidelines suggests, twitter handle is SexualRhino_

### CODE REVIEW

**Comment by tasansal** [comment]
any luck pushing this forward? if you can give some history/roadmap/todo I can see if there is anything I can help with :)

**Comment by srhinos** [comment]
This is really only blocked by dependencies so until those get resolved (they’re all linked in the description), not much I can do to finalize this PR :(
  

  
If you wanna go tackle the chromadb issue or the steamship issue, both have maintainers interested in getting fixes in. Spacy doesn’t look like it’ll be getting a fix anytime soon so pending langchain completely removing the dependency, it’ll be blocked on that getting fixed as well :(
  

  
There’s a half solution that could be done to unpin the version and implement a try, catch over every pydantic import to try for the v1 import so v2 can at least be resolved by poetry but it’ll mean all dependencies blocking pure v2 will throw errors.   
  
  
  
  
  
  
  

  
  
>

**Comment by quitrk** [comment]
>  Spacy doesn’t look like it’ll be getting a fix anytime soon so pending langchain completely removing the dependency, it’ll be blocked on that getting fixed as well :(

Looks like they actually merged Pydantic v2 support and it's available starting with v3.6.1

**Comment by baskaryan** [comment]
v2 should be supported as of langchain==0.0.267, we'd love to hear if that's working for folks. See #9337 for more detailed info.

**Comment by eyurtsev** [comment]
@srhinos thank you for the PR! Handled via v1/v2 compatibility for now

**Pull request closed without merging**
