### PR TITLE
add support for weaviate vectorstore using weaviate's v4 beta client

### PR DESCRIPTION
**Pull request by SavvasMohito**
Hi there, a few days ago I created #14531 and asked to add support for Weaviate's new v4 python client which is currently in beta. As I mentioned in that issue, I started working on it myself and I believe I have created a working weaviate vectorstore using their new client.

## Changelog

* Uses the new weaviate-client **v4** with updated syntax and functions. The new client is faster and safer to use because of Weaviate's new [gRPC API](https://weaviate.io/developers/weaviate/api/grpc).
* Added a new function to support [BM25 keyword search](https://weaviate.io/developers/weaviate/search/bm25).
* Changed the delete function to use batch for faster execution (there was a [TODO](https://github.com/langchain-ai/langchain/blob/b9ef92f2f4bb1e4322dff040c4474c0922fbf546/libs/community/langchain_community/vectorstores/weaviate.py#L526) for it)
* The function names and attributes have remained the same from the original weaviate vectorstore.

As this version of weaviate's client is still in beta, I think it is wise to add this as a new vectorstore, without replacing the existing one. For this reason, I did not change the original weaviate.py vectorstore file, but I added a new one called weaviate_v4.py. This way users using the original weaviate vectorstore will not be affected, but they'll be able to try the new vectorstore if they wish.

The are no dependencies other than having installed weaviate-client pre-release >= v4.
I also added a file in docs/docs, which is the same as the original one for weaviate but with the new client's structure.
I ran `make format`, `make lint` and `make test` before committing. :)

I did not create a unit test file because I saw there are almost none for other vectorstores. Let me know if it's essential and I may try to create one.

My Twitter (or X) handle is @mantzouranidis. Thanks for your work, I hope my contribution helps.

### CODE REVIEW

**Comment by dsolito** [comment]
Hi, is there a chance to see this supported soon in the next release?

**Comment by baskaryan** [comment]
Hey @SavvasMohito, thanks for the contribution! The weaviate integration has been moved into its own package and repo to allow for better versioning, testing and direct maintenance from the Weaviate team. https://github.com/langchain-ai/langchain-weaviate

I believe that already supports v4 client, correct me if i'm wrong @efriis @hsm207

**Comment by SavvasMohito** [comment]
Great, thanks for letting me know @baskaryan !

**Comment by dsolito** [comment]
thank you for the info

**Pull request closed without merging**
