### PR TITLE
Add unit tests for StructuredChatOutputParser and handle variant action format

### PR DESCRIPTION
**Pull request by rogerbock**
- Description: I added unit tests for StructuredChatOutput Parser (there were none previously). I also noticed in testing with chat-bison that it sometimes produced action output in a slightly different format, so I added an additional regular expression to correctly handle that output format.
  - Issue: N/A
  - Dependencies: None
  - Tag maintainer: @hinthornw
  - Twitter handle: N/A

### CODE REVIEW

**Comment by rogerbock** [comment]
This is my first time contributing to a repo that has a Vercel integration. How do I see the output of the automated tests? I created a Vercel account, but clicking on the Details link just takes me to a 404 page.

**Comment by rogerbock** [comment]
Tagging @hwchase17 in case I tagged the wrong person originally. Hopefully this is a simple PR to approve - it is mostly just adding unit tests.

**Comment by leo-gan** [comment]
@rogerbock Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by rogerbock** [comment]
@leo-gan I resolved the merge conflicts. Let me know if you need anything else - thanks!

**Comment by rogerbock** [comment]
My team is no longer using this class so from my perspective I no longer need this merged, although others may benefit from it. In general, it is probably good to have a more robust parser and unit tests for it, but at this point (seven months after the PR was submitted) someone other than me should resolve the merge conflicts if they consider this worth having in langchain.

**Comment by nfcampos** [comment]
No longer relevant

**Pull request closed without merging**
