### PR TITLE
community[patch]: Add test case for MoonshotChat

### PR DESCRIPTION
**Pull request by ZhangShenao**
Add test case for `MoonshotChat`.

### CODE REVIEW

**Comment by ZhangShenao** [comment]
@efriis @ccurme  The CI failure seems unrelated to this pr.

**Comment by ZhangShenao** [comment]
@ccurme @efriis Please review this pr.

**Review by ccurme — APPROVED** [review]

**Comment by ccurme** [comment]
Hi @ZhangShenao, thanks for this.

Langchain has a suite of standard tests for chat models in the [standard-tests](https://github.com/langchain-ai/langchain/tree/master/libs/standard-tests) library, which is already a test dependency of langchain-community. I believe all functionality here + more is covered by them. You'd just need to import the standard tests and `xfail` those that test for functionality that isn't implemented.

Here is an example implementation for integration tests: https://github.com/langchain-ai/langchain/blob/master/libs/community/tests/integration_tests/chat_models/test_litellm_standard.py

And unit tests: https://github.com/langchain-ai/langchain/blob/master/libs/community/tests/unit_tests/chat_models/test_litellm.py

Could be a separate PR if you're interested in contributing this.

**Comment by ZhangShenao** [comment]
> Hi @ZhangShenao, thanks for this.
> 
> Langchain has a suite of standard tests for chat models in the [standard-tests](https://github.com/langchain-ai/langchain/tree/master/libs/standard-tests) library, which is already a test dependency of langchain-community. I believe all functionality here + more is covered by them. You'd just need to import the standard tests and `xfail` those that test for functionality that isn't implemented.
> 
> Here is an example implementation for integration tests: https://github.com/langchain-ai/langchain/blob/master/libs/community/tests/integration_tests/chat_models/test_litellm_standard.py
> 
> And unit tests: https://github.com/langchain-ai/langchain/blob/master/libs/community/tests/unit_tests/chat_models/test_litellm.py
> 
> Could be a separate PR if you're interested in contributing this.

Thank you for your guidance! I have a basic understanding of the usage of testing, and I am very willing to contribute to it!

**Pull request merged**
