### PR TITLE
allow passing HTTP headers in AzureOpenAI class

### PR DESCRIPTION
**Pull request by SDonkelaarGDD**
- **Description:** Some organisations expose Azure OpenAI endpoints via some proxies that need additional HTTP headers. This PR supports for that by allowing the user to set custom headers when initialising the AzureOpenAI class. These custom headers can be used when making requests.
  - **Issue:** it aims to fix the issue #11593
  - **Dependencies:** -

### CODE REVIEW

**Comment by maiqingqiang** [comment]
AzureOpenAI supports the ability to configure headers.

https://github.com/langchain-ai/langchain/blob/56653c53aae55f8638a673764c8784dca93718da/libs/langchain/langchain/llms/openai.py#L178-L179

```python
AzureChatOpenAI(
   model_kwargs={
            "headers": {
            },
        }
)
```

**Comment by SDonkelaarGDD** [comment]
> AzureOpenAI supports the ability to configure headers.
> 
> https://github.com/langchain-ai/langchain/blob/56653c53aae55f8638a673764c8784dca93718da/libs/langchain/langchain/llms/openai.py#L178-L179
> 
> ```python
> AzureOpenAI(
>    model_kwargs={
>             "headers": {
>             },
>         }
> )
> ```

Nice catch. However, the OpenAIEmbeddings class also allow you to set model_kwargs. It can be confusing that is possible to set headers directly when using OpenAIEmbeddings but not when using AzureOpenAI. What do you think?

**Comment by baskaryan** [comment]
Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

**Comment by TheShoes** [comment]
I am also trying to get this to work.  I am trying the modelKwargs route but that does not seem to be working. 
secondly it keeps saying 
Error: Azure OpenAI Completion Deployment name not found
Even though my deployment name is in.   the error goes away if I use azureOpenAIEmbeddingsApiDeploymentName
but that does not seem right

**Comment by SDonkelaarGDD** [comment]
> Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

No problem! 

I saw that the original `AzureOpenAI` class is now deprecated. The advice is to use `AzureChatOpenAI` class instead, which allows you to set headers using `default_headers`. Hence I don't think this is be relevant anymore and closed the PR.

**Pull request closed without merging**
