### PR TITLE
**community**: "GoogleNationalWeatherAPI: Return the current temperature for a given location, using the Google Maps API and National Weather Service API"

### PR DESCRIPTION
**Pull request by JAlexMcGraw**
Description: Created a new class for returning the current temperature in Fahrenheit for a US location, using the Google Maps API and National Weather Service API. Requires a Google API key. 

Dependencies: Requires the "googlemaps" package

Twitter Handle: JAlexMcGraw

------------

- [ ] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [ ] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

NOTE: "make lint" and "make format" both error for me, and I'm unsure why.

make format error

```
poetry run ruff format .
warning: `ruff format` is a work-in-progress, subject to change at any time, and intended for internal use only.
ruff failed
  Cause: Could not read .: 
  Cause: Is a directory (os error 21)
make: *** [format] Error 2
```

make lint error

```
./scripts/check_pydantic.sh .
./scripts/lint_imports.sh
langchain_community/utilities/google_weatherservice.py:from langchain.pydantic_v1 import BaseModel, Field, root_validator
langchain_community/utilities/google_weatherservice.py:from langchain.tools import BaseTool
make: *** [lint] Error 1
```

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, hwchase17.

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
lint is wrong, you can run `make format` from that directory to fix some of it

**Comment by JAlexMcGraw** [comment]
I'm unsure what else I need to do/test for this code to meet the standards needed for the repo. Is there anything else needed from my end?

**Comment by JAlexMcGraw** [comment]
![@baskaryan] I'm not sure who I should tag for review, so wanted to reach out to you for review. If you need me to change anything about this PR, please let me know!

**Comment by baskaryan** [comment]
@JAlexMcGraw think you may have pulled in more changes than you intended to, may be easier to start fresh branch

**Comment by JAlexMcGraw** [comment]
@baskaryan Sounds good! I'll start on a fresh one. Thanks!

**Pull request closed without merging**
