### PR TITLE
community: Add tool_calls support for ChatTongyi Model, allowing it to be used as the LLM of the lastest tool calling agent

### PR DESCRIPTION
**Pull request by liushuaikobe**
- **Description:** Added tool calls support for the ChatTongyi Model (which was [officially supported](https://help.aliyun.com/zh/dashscope/developer-reference/api-details#86ef4d304bwsb) recently), now the ChatTongyi can be used as the LLM of a [tool calling agent](https://python.langchain.com/docs/modules/agents/agent_types/tool_calling/) seamlessly.

example usage:

``` python
llm = ChatTongyi(model_name="qwen-max")
tools = [TavilySearchResults(max_results=1)]
prompt = ChatPromptTemplate.from_messages(
  [
      (
          "system",
          "You are a helpful assistant. Make sure to use the tavily_search_results_json tool for information.",
      ),
      ("placeholder", "{chat_history}"),
      ("human", "{input}"),
      ("placeholder", "{agent_scratchpad}"),
  ]
)
# Construct the Tools agent
agent = create_tool_calling_agent(llm, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
agent_executor.invoke({"input": "what is LangChain?"})
```

or simply:

``` python
class GetWeather(BaseModel):
  """Get the current weather in a given location"""

  location: str = Field(
      ...,
      description="The city and state, e.g. San Francisco, CA",
  )
llm = ChatTongyi(model_name="qwen-max")
llm_with_tools = llm.bind_tools([GetWeather])
llm_with_tools.invoke("what is the weather like in HangZhou, China")
```

- **Dependencies:** no new dependencies required.

### CODE REVIEW

**Comment by ccurme** [comment]
Thanks for this @liushuaikobe. This appears duplicated with https://github.com/langchain-ai/langchain/pull/20725 so I'm closing it for now. Would appreciate your review and/or testing on that PR if you can.

**Comment by liushuaikobe** [comment]
@ccurme Thank you for your review and I'm also grateful for [#20725](https://github.com/langchain-ai/langchain/pull/20725)!

Actually, this PR employs a more "langchain" approach and aligns better with the original design of langchain.. 

1. It utilizes [`tool_call_chunks`](https://github.com/langchain-ai/langchain/pull/21366/files#diff-b0fa39b5b280efca9cfb65876f57d73f3e887f7a7fabb8fd8c586831e1ea017aR194) in `AIMessageChunk` for handing the streaming output of AI message with tool calls. It also defines an [inner subclass](https://github.com/langchain-ai/langchain/pull/21366/files#diff-b0fa39b5b280efca9cfb65876f57d73f3e887f7a7fabb8fd8c586831e1ea017aR194) of `AIMessageChunk` to handle the limitations of Tongyi LLM API appropriately.
2. The utility method [`message_chunk_to_message`](https://github.com/langchain-ai/langchain/pull/21366/files#diff-b0fa39b5b280efca9cfb65876f57d73f3e887f7a7fabb8fd8c586831e1ea017aR194) from the core library is used when converting a message or message chunk into a dictionary.
3. Explicitly passes the [`incremental_output`](https://github.com/langchain-ai/langchain/pull/21366/files#diff-b0fa39b5b280efca9cfb65876f57d73f3e887f7a7fabb8fd8c586831e1ea017aR570) parameter when calling the `bind` method for tool binding, clearly demonstrating the requirements of the Tongyi LLM API. Moreover, I have also included [additional comments](https://github.com/langchain-ai/langchain/pull/21366/files#diff-b0fa39b5b280efca9cfb65876f57d73f3e887f7a7fabb8fd8c586831e1ea017aR527) for clearer explanations and better code understanding.

Hence, this PR entails minimal code changes while fully supporting tool calling agents with the Tongyi LLM. 

I would greatly appreciate it if this PR could be reopened and reviewed once again.

**Comment by ccurme** [comment]
@liushuaikobe thanks for the work you did here. We merged https://github.com/langchain-ai/langchain/pull/20725. Would appreciate your improvements to that implementation.

**Comment by jlcoo** [comment]
@liushuaikobe @ccurme

**Pull request closed without merging**
