### PR TITLE
community[patch]: add skipped test for inner product normalization

### PR DESCRIPTION
**Pull request by careywyr**
fix method _max_inner_product_relevance_score_fn when DistanceStrategy is MAX_INNER_PRODUCT
[#14948](https://github.com/langchain-ai/langchain/issues/14948)

### CODE REVIEW

**Comment by efriis** [comment]
@careywyr will chat with the team about this tomorrow - I think we might just want to do this on FAISS and not the base class because different vectorstores return different types of scores. Will keep you updated!

**Comment by careywyr** [comment]
@efriis Thanks for your review. I'm looking forward to the revised version. 🤝

**Comment by efriis** [comment]
Hey @careywyr curious your thoughts on this.

To start, I believe the relevance score normalization feature is an old one that needs some rethinking. To begin with, I think normalizing inner product scores relies on the dimensionality of the vectors, which this function won't have access to.

I wrote a skipped test to confirm this is the output you're targeting from this (the current implementation returns 8, and the one you implemented returns 5).

The *right* way to do this will probably have to wait until v0.2, which will be a major version bump that can introduce some interface changes, and knowing that, I'm curious how you'd want these relevance scores handled.

**Comment by careywyr** [comment]
Hi, @efriis . Thanks for your response.

In the process of using Langchain to operate FAISS, I have normalized all vectors myself. Additionally, in some scenarios where I need to manually calculate cosine similarity (I might get some results through non-vector search methods, but use vectorized methods for calculating similarity), I hope that Langchain can also return the original inner product. Of course, since cosine similarity is within [-1, 1], I intend to use the method of (similarity + 1) / 2 to ensure the results are within [0, 1]. However, I did not consider the differences between various vector search libraries and that normalization might be a default process.

In fact, I am just a beginner in AI, and my understanding comes from some basic learning. I think that as long as the inner product is used as the similarity algorithm, regardless of the vector library used, the final result should be equal to the cosine similarity values calculated manually after direct vectorization (if the vectors are not normalized, then they should be forcibly normalized).

**Pull request merged**
