### PR TITLE
Wrapper function for OpenAI Function in LLMChain

### PR DESCRIPTION
**Pull request by enjuichang**
- Description: This pull request does two things: 1) Add wrapper function for pydantic model, JSON Schema, and dictionary to function calls in LLM Chain. 2) Add an additional class for the output parser class so pydantic model returns a string that could be added to AIMessage for memory storage.
  - Issue: #6933 
  - Dependencies: N/A
  - Tag maintainer: @baskaryan
  - Twitter handle: #7t_eric

### CODE REVIEW

**Comment by coditamar** [comment]
@CodiumAI-Agent please review

**Comment by enjuichang** [comment]
@CodiumAI-Agent please check again

**Comment by enjuichang** [comment]
@CodiumAI-Agent please review

**Comment by baskaryan** [comment]
@enjuichang thanks for contribution! landed some similar functions [here](https://github.com/hwchase17/langchain/blob/master/langchain/chains/openai_functions/base.py), wondering if that covers your use case

**Comment by enjuichang** [comment]
hey @baskaryan! looks good. One thing that probably needs to change is the memory system. I don't know if you guys took a look into this but in `ChatOpenAI`, the `AIMessage` is appended as a list, so the output parser [here](https://github.com/hwchase17/langchain/blob/master/langchain/chains/openai_functions/base.py#L163C54-L163C54) would actually fail since the output is a pydantic class.

I added [this](https://github.com/hwchase17/langchain/blob/e78ce0d2ecdc0b1a3a6d514da4bdc22c54b9e64d/langchain/output_parsers/openai_functions.py#L52C1-L53C1) temporary get around to solve this but let me know if you have any other ideas about this!

**Comment by baskaryan** [comment]
> hey @baskaryan! looks good. One thing that probably needs to change is the memory system. I don't know if you guys took a look into this but in `ChatOpenAI`, the `AIMessage` is appended as a `string`, so the output parser [here](https://github.com/hwchase17/langchain/blob/master/langchain/chains/openai_functions/base.py#L163C54-L163C54) would actually fail since the output is a pydantic class.
> 
> I added [this](https://github.com/hwchase17/langchain/blob/e78ce0d2ecdc0b1a3a6d514da4bdc22c54b9e64d/langchain/output_parsers/openai_functions.py#L52C1-L53C1) temporary get around to solve this but let me know if you have any other ideas about this!

hm yea interesting point. my first thought is i'd probably create a custom memory that would convert the original output to str before saving it. that way you can still use the structured output in downstream logic

something like 
```python
class StructuredChatMemory(BaseChatMemory):

    def _get_input_output(
      self, inputs: Dict[str, Any], outputs: Dict[str, str]
    ) -> Tuple[str, str]        
      input, output = super()._get_input_output(inputs, outputs)
      if isinstance(output, BaseModel):
        output = output.json(indent=2)
      return input, output
```


what do you think?

**Comment by enjuichang** [comment]
Yeah that looks good!

**Comment by baskaryan** [comment]
closing pr for now, @enjuichang let me know if im missing anything!

**Comment by enjuichang** [comment]
@baskaryan is this implemented/scheduled?

> > hey @baskaryan! looks good. One thing that probably needs to change is the memory system. I don't know if you guys took a look into this but in `ChatOpenAI`, the `AIMessage` is appended as a `string`, so the output parser [here](https://github.com/hwchase17/langchain/blob/master/langchain/chains/openai_functions/base.py#L163C54-L163C54) would actually fail since the output is a pydantic class.
> > I added [this](https://github.com/hwchase17/langchain/blob/e78ce0d2ecdc0b1a3a6d514da4bdc22c54b9e64d/langchain/output_parsers/openai_functions.py#L52C1-L53C1) temporary get around to solve this but let me know if you have any other ideas about this!
> 
> hm yea interesting point. my first thought is i'd probably create a custom memory that would convert the original output to str before saving it. that way you can still use the structured output in downstream logic
> 
> something like
> 
> ```python
> class StructuredChatMemory(BaseChatMemory):
> 
>     def _get_input_output(
>       self, inputs: Dict[str, Any], outputs: Dict[str, str]
>     ) -> Tuple[str, str]        
>       input, output = super()._get_input_output(inputs, outputs)
>       if isinstance(output, BaseModel):
>         output = output.json(indent=2)
>       return input, output
> ```
> 
> what do you think?

**Pull request closed without merging**
