### PR TITLE
community: add token usage to bedrock models' responses if available

### PR DESCRIPTION
**Pull request by AlexisGado**
- **Description:** Get token usage (if available) from the response body of bedrock model responses and pass it to the `llm_output` field of `ChatGeneration`
- **Issue:** Solves #11906 for some models

### CODE REVIEW

**Comment by AlexisGado** [comment]
@baskaryan @3coins, tiny reminder! Thanks 😄

**Comment by dmenini** [comment]
Hi, I opened a similar PR a couple of weeks ago: https://github.com/langchain-ai/langchain/pull/19127#issuecomment-2019208568

Here I'm using the Bedrock headers to extract the token counts, which should work across different providers (hopefully). Maybe it would be great if you could confirm that such headers are also available for meta models (unfortunately I only have access to anthropic models). Thanks!

**Comment by baskaryan** [comment]
thanks @AlexisGado! as @dmenini #19127 implements same functionality and just landed — ok to close this pr?

**Comment by hwchase17** [comment]
these models are now in their own integration packages

**Pull request closed without merging**
