### PR TITLE
Fix: (issue #13825) Getting an error with DallEAPIWrapper

### PR DESCRIPTION
**Pull request by ggeutzzang**
- **Description:** As of OpenAI's Python package 1.0, the existing DallEAPIWrapper does not work correctly, so the example in the LangChain Documentation link below does not work either. 
https://python.langchain.com/docs/integrations/tools/dalle_image_generator 
Also, since OpenAI only supports DALL-E version 2 or version 3, I modified the DallEAPIWrapper to support it. 

  - **Issue:** #13825 

  - **Twitter handle:** ggeutzzang

### CODE REVIEW

**Comment by silvhua** [comment]
There seems to be a typo in `quality=self.qualtity,` (libs/langchain/langchain/utilities/dalle_image_generator.py line 66)

**Comment by ggeutzzang** [comment]
> There seems to be a typo in `quality=self.qualtity,` (libs/langchain/langchain/utilities/dalle_image_generator.py line 66)

Thanks, I fixed

**Review by hwchase17 — APPROVED** [review]
thanks!

**Comment by dentro-innovation** [comment]
Hey guys short question: 

If I load the tool like this:
```
from langchain.agents import load_tools
image_gen_tool = load_tools(["dalle-image-generator"])[0]

tools = [DuckDuckGoSearchRun(), {"type": "code_interpreter"}, image_gen_tool]

agent = OpenAIAssistantRunnable.create_assistant(
    name="code interpreter with duckduckgo search and dalle",
    instructions="You are a helpful assistant. You can search the internet, and write and run code, and create images.",
    tools=tools,
    model="gpt-4-1106-preview",
    as_agent=True,
)
```

How can I change the model_name?
The default is `dall-e-2` but I wanna override it to use `dall-e-3`. 
Somehow I couldn't find a way.

**Pull request merged**
