### PR TITLE
Update docs to specify Indexing-API-compatible vectorstores

### PR DESCRIPTION
**Pull request by RyanZotti**
**Description:** Update Indexing API docs to specify vectorstores that are compatible with the Indexing API. I add a unit test to remind developers to update the documentation whenever they add or change a vectorstore in a way that affects compatibility. For the unit test I repurposed existing code from [here](https://github.com/langchain-ai/langchain/blob/v0.0.311/libs/langchain/langchain/indexes/_api.py#L245-L257).

This is my first PR to an open source project. This is a trivially simple PR whose main purpose is to make me more comfortable submitting Langchain PRs. If this PR goes through I plan to submit PRs with more substantive changes in the near future. 

**Issue:** Resolves [10482](https://github.com/langchain-ai/langchain/discussions/10482).

**Dependencies:** No new dependencies.

**Twitter handle:** None.

### CODE REVIEW

**Comment by eyurtsev** [comment]
@RyanZotti Amazing! Thank you very much!

**Comment by RyanZotti** [comment]
@eyurtsev Does this mean that the PR will be merged into master? If not, is there anything else I should do?

**Comment by eyurtsev** [comment]
@RyanZotti yeah, PR is failing tests right now if you want to speed up merging, you can resolve the bot tests otherwise I'll comandeer to resolve tests and merge (may take a few days)

**Comment by eyurtsev** [comment]
Comandeering to handle linting

**Pull request merged**
