### PR TITLE
docs: `graphs` update

### PR DESCRIPTION
**Pull request by leo-gan**
Issue: The `graph` code was moved into the `community` package a long ago. But the related documentation is still in the [use_cases](https://python.langchain.com/docs/use_cases/graph/integrations/diffbot_graphtransformer) section and not in the `integrations`.
Changes:
- moved the `use_cases/graph/integrations` notebooks into the `integrations/graphs`
- renamed files and changed titles to follow the consistent format
- redirected old page URLs to new URLs in `vercel.json` and in several other pages
- added descriptions and links when necessary
- formatted into the consistent format

### CODE REVIEW

**Comment by leo-gan** [comment]
@eyurtsev Any comments?

**Review by efriis — APPROVED** [review]
Just confirming others onboard before merging

**Comment by leo-gan** [comment]
@efriis Thanks!!!

**Comment by eyurtsev** [comment]
@leo-gan looks good

**Pull request merged**
