### PR TITLE
[Community] - Added bind_tools and with_structured_output for ChatZhipuAI

### PR DESCRIPTION
**Pull request by keenborder786**
- **Description:** This PR implements the `bind_tool` functionality for ChatZhipuAI as requested by the user. ChatZhipuAI models support tool calling according to the `OpenAI` tool format, as outlined in their official documentation [here](https://open.bigmodel.cn/dev/api#glm-4).
- **Issue:**  ##23868

### CODE REVIEW

**Comment by keenborder786** [comment]
@eyurtsev

**Comment by keenborder786** [comment]
@eyurtsev please review

**Comment by keenborder786** [comment]
@eyurtsev

**Comment by Macbook-Specter** [comment]
@keenborder786 Hello, after I modified the local file based on your submission, I reported an error when running the code:
```
tools = [TavilySearchResults(max_results=5)]
tool_map = {t.name: t for t in tools}

def inject_state(message, state):
    tool_calls = []
    for tool_call in message.tool_calls:
        tool_call_copy = deepcopy(tool_call)
        tool_call_copy["args"]["state"] = state
        tool_calls.append(tool_call_copy)
    return tool_calls

# 定义工具调用节点
def call_tool(state, config):
    messages = state['messages']
    last_message = messages[-1]
    tool_messages = []
    for tool_call in inject_state(last_message, state):
        tool_messages.append(tool_map[tool_call["name"]].invoke(tool_call, config))
    return {"messages": tool_messages}


zhipuai.py", line 174, in _convert_message_to_dict
    raise TypeError(f"Got unknown type '{message.__class__.__name__}'.")
TypeError: Got unknown type 'ToolMessage'.
```

**Comment by keenborder786** [comment]
@Macbook-Specter let me have a look

**Comment by keenborder786** [comment]
@Macbook-Specter can you send me the entire traceback please?

**Comment by keenborder786** [comment]
@ccurme please review.

**Comment by ccurme** [comment]
Thanks for this. This PR adds support for `with_structured_output` but IMO does not add support for tool calling, because (as @Macbook-Specter finds) we don't implement support for `ToolMessage`. So the model has no way of processing results from tools. Ideally, we'd have:

- Tool calls populated on [AIMessage.tool_calls](https://github.com/langchain-ai/langchain/blob/420534c8ca637b985cb74b5828fd955e4ab48585/libs/core/langchain_core/messages/ai.py#L72) attribute in `_convert_dict_to_message`
- `ToolMessage` handled in `_convert_message_to_dict`
- If streaming tool calls are supported, [AIMessage.tool_call_chunks](https://github.com/langchain-ai/langchain/blob/420534c8ca637b985cb74b5828fd955e4ab48585/libs/core/langchain_core/messages/ai.py#L220) populated in `_convert_delta_to_message_chunk`.

Langchain has a suite of standard tests for chat models in the [standard-tests](https://github.com/langchain-ai/langchain/tree/master/libs/standard-tests) library, which is already a test dependency of `langchain-community`. This would help test for tool calling functionality.

Here is an example implementation for integration tests: https://github.com/langchain-ai/langchain/blob/master/libs/community/tests/integration_tests/chat_models/test_litellm_standard.py

We can add `xfails` (as in the example) if needed where tests are failing. But this will at least illuminate the failures and provide tests for the functionality implemented here.

**Review by ccurme — APPROVED** [review]

**Pull request merged**
