### PR TITLE
Harrison/vertex

### PR DESCRIPTION
**Pull request by hwchase17**

### CODE REVIEW

**Comment by hwchase17** [comment]
@Jflick58 - i tried to take your notebooks from #4891  and add here (after updating the names to be consistent). would you mind taking a final look to make sure all looks good?

**Comment by Jflick58** [comment]
Looks good to me - thanks @hwchase17

**Comment by dev2049** [comment]
thank you all! @lkuligin @Ark-kun @sasha-gitg @Jflick58 🙏

**Comment by pierreembacher** [comment]
Ah I see. I was probably too impatient. I had already found it yesterday in the documentation and tried it in Colab. I try it again locally. Thanks!

**Comment by khallbobo** [comment]
I believe the parameters are being ignored in this implementation.  From the vertexai examples, you need to pass the params to send_message and not to start_chat.  So top_p, top_k, temperature, max_output_tokens seem to be ignored with this code.

**Comment by khallbobo** [comment]
It's actually a bug in the vertexai library.  It ignores the params passed to start_chat().  Only those passed to send_message() will be used. @hwchase17 @lkuligin

**Comment by plasticine** [comment]
For other travellers https://github.com/googleapis/python-aiplatform/issues/2263

**Comment by lkuligin** [comment]
this would be fixed on the Vertex side, thanks.

**Comment by khallbobo** [comment]
You can fix it here by passing the Params to send_message rather than
start_chat.  For now, Params are ignored when using the latest vertex and
langchain releases.

Thanks -
Keith

**Pull request merged**
