### PR TITLE
community: SQL Lantern template

### PR DESCRIPTION
**Pull request by gustavo-yt**
<!-- Thank you for contributing to LangChain!

Replace this entire comment with:
  - **Description:** SQL Lantern template

### CODE REVIEW

**Comment by dqii** [comment]
Hi! Was this PR and others (https://github.com/langchain-ai/langchain/pull/16586, https://github.com/langchain-ai/langchain/pull/16523) closed by accident? We are still waiting on a review.

**Comment by dqii** [comment]
@efriis do you need anything from us on these?

**Review by efriis — COMMENTED** [review]
Should this use the lantern connector from #12951 instead? Or is this the recommended way to interact with lantern?

**Comment by efriis** [comment]
closing as stale without answer to above

**Pull request closed without merging**
