### PR TITLE
migrate openai audio api

### PR DESCRIPTION
**Pull request by redheli**
for issue https://github.com/langchain-ai/langchain/issues/13162
migrate openai audio api, as [openai v1.0.0 Migration Guide](https://github.com/openai/openai-python/discussions/742)

### CODE REVIEW

**Comment by baskaryan** [comment]
awesome @redheli! only thing is we probably want to do this in a backwards compatible way. OpenAI LLM is one example of how to do this. can give it a stab if you don't have time

**Comment by redheli** [comment]
> awesome @redheli! only thing is we probably want to do this in a backwards compatible way. OpenAI LLM is one example of how to do this. can give it a stab if you don't have time

let me try first, I will update the code now, follow OpenAI LLM, make backwards compatible

**Comment by redheli** [comment]
@baskaryan please help review again, Thanks.
The PR rebased already.

**Comment by redheli** [comment]
@baskaryan ready to review

**Review by hwchase17 — APPROVED** [review]

**Pull request merged**
