### PR TITLE
implement async exec for base.py

### PR DESCRIPTION
**Pull request by mzamini92**
Can we such a method for async? The return type is specified as `asyncio.Task[Dict[str, str]]` to represent the dictionary return type wrapped in an `asyncio.Task`. `Since _acall()` is an asynchronous method, any coroutine calls within it should be awaited. So, we use await when calling `run_manager.on_text()` to properly await the completion of the asynchronous operation.

### CODE REVIEW

**Comment by leo-gan** [comment]
@mzamini92 Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Review by mzamini92 — COMMENTED** [review]
type-checking errors solved

**Review by mzamini92 — COMMENTED** [review]
typo errors solved

**Review by mzamini92 — COMMENTED** [review]
AsyncCallbackManagerForChainRun fixed

**Review by mzamini92 — COMMENTED** [review]
update the method signature of _call in my ToTChain class

**Review by mzamini92 — COMMENTED** [review]
fix errors

**Review by mzamini92 — COMMENTED** [review]
I've created the _async_acall_helper method to contain the asynchronous logic.

**Pull request closed without merging**
