### PR TITLE
core: added FakeVectorStore

### PR DESCRIPTION
**Pull request by lkuligin**
#9292

### CODE REVIEW

**Comment by lkuligin** [comment]
@eyurtsev @hwchase17 could you take a look, please?

**Comment by leo-gan** [comment]
@baskaryan Could you, please, review it? It looks like very helpful addition.

**Comment by baskaryan** [comment]
out of curiosity how are you imagining using this?

**Comment by efriis** [comment]
@lkuligin if you want to write some unit tests for some of the in-library chains and runnables, it might demonstrate the use case a bit better.

Otherwise, I'll probably close this, and you can continue using it in your codebase for unit testing custom chains!

**Comment by leo-gan** [comment]
We also have plenty Fake classes: LLM, Embeddings. It makes sense to make Fake classes for all modules. So, I like this Fake vector store.

**Comment by nejch** [comment]
Thanks for this @lkuligin, I was able to use this in combination with a `FakeStreamingListLLM`  to test incorporating chain building into a django app with a chatbot and custom contexts. So just adding another voice/use case here it might make sense since there's similar fake classes already provided with the package :bow:

**Review by eyurtsev — CHANGES_REQUESTED** [review]
Let's move the in memory vectorstore into core! It relies on numpy, but we can make it into an optional dependency?

**Review by efriis — APPROVED** [review]
moved to core!

**Comment by eyurtsev** [comment]
Here's a PR that should resolve this issue: https://github.com/langchain-ai/langchain/pull/23986

**Comment by eyurtsev** [comment]
Closing this as we merged the in memory vectorstore

**Pull request closed without merging**
