### PR TITLE
feat: adding paygo api support for Azure ML / Azure AI Studio

### PR DESCRIPTION
**Pull request by santiagxf**
- **Description:** Introducing support for LLMs and Chat models running in Azure AI studio and Azure ML using the new deployment mode pay-as-you-go (model as a service).
- **Issue:** NA
- **Dependencies:** None.
- **Tag maintainer:** @prakharg-msft @gdyre 
- **Twitter handle:** @santiagofacundo

Examples added:
* [docs/docs/integrations/llms/azure_ml.ipynb](https://github.com/santiagxf/langchain/blob/santiagxf/azureml-endpoints-paygo-community/docs/docs/integrations/chat/azureml_endpoint.ipynb)
* [docs/docs/integrations/chat/azureml_chat_endpoint.ipynb](https://github.com/santiagxf/langchain/blob/santiagxf/azureml-endpoints-paygo-community/docs/docs/integrations/chat/azureml_chat_endpoint.ipynb)

### CODE REVIEW

**Review by gdyre — APPROVED** [review]

**Review by hwchase17 — COMMENTED** [review]
not sure im set up to test this - am i correct in assuming you are the PM and/or eng working on this product and so can probably vouch for its correctness?

**Comment by santiagxf** [comment]
> not sure im set up to test this - am i correct in assuming you are the PM and/or eng working on this product and so can probably vouch for its correctness?

Hi @hwchase17! Indeed I'm the PM working on our new set of serverless APIs in Azure AI. I also asked engineering to review the PR. Please feel free to make any comment or suggestion. You will also see a follow-up PR introducing streaming but since it was missing in the original implementation, I'd rather file different PRs to keep them easy to review. Looking forward to having a deeper integration with langchain!

**Comment by santiagxf** [comment]
@hwchase17 I addressed the linting errors showing on the docs. Please let me know if we are good to go. Thanks!

**Comment by santiagxf** [comment]
Maybe @dev2049 or @baskaryan can help with this PR?

**Comment by santiagxf** [comment]
@efriis would you give us a hand with this PR? We haven't been able to get someone to take a look at it. Thanks!

**Review by hwchase17 — COMMENTED** [review]
apologies for delay in review!

**Review by hwchase17 — APPROVED** [review]

**Comment by santiagxf** [comment]
@hwchase17, we have updated the PR to include the changes introduced in `langchain==0.1` and the separation in `langchain_community` package. How can we move forward with this PR? It has been opened for a while.

**Comment by santiagxf** [comment]
@hwchase17 I fixed the integration tests that were failing in the CI/CD. Please let us know!

**Comment by santiagxf** [comment]
@hwchase17 any chance we can review and merge it this week?

**Comment by santiagxf** [comment]
Thanks @baskaryan for running the integration tests. It looks we missed including this commit: https://github.com/langchain-ai/langchain/commit/d266b3ea4a5dc85fe895b93090d89aa311f8c48e while pulling changes. Can we please trigger integration tests again?

**Comment by hwchase17** [comment]
sorry for delay @santiagxf , merging in!

**Pull request merged**
