### PR TITLE
[annotation improvement] Make AgentType->Class Conversion More Scalable

### PR DESCRIPTION
**Pull request by skcoirz**
In the current solution, AgentType and AGENT_TO_CLASS are placed in two separate files and both manually maintained. This might cause inconsistency when we update either of them. 

— latest —
based on the discussion with hwchase17, we don’t know how to further use the newly introduced AgentTypeConfig type, so it doesn’t make sense yet to add it. Instead, it’s better to move the dictionary to another file to keep the loading.py file clear. The consistency is a good point. Instead of asserting the consistency during linting, we added a unittest for consistency check. I think it works as auto unittest is triggered every time with clear failure notice. (well, force push is possible, but we all know what we are doing, so let’s show trust. :>)

~~This PR includes~~
- ~~Introduced AgentTypeConfig as the source of truth of all AgentType related meta data.~~
- ~~Each AgentTypeConfig is a annotated class type which can be used for annotation in other places.~~
- ~~Each AgentTypeConfig can be easily extended when we have more meta data needs.~~
- ~~Strong assertion to ensure AgentType and AGENT_TO_CLASS are always consistent.~~
- ~~Made AGENT_TO_CLASS automatically generated.~~

~~Test Plan:~~
- ~~since this change is focusing on annotation, lint is the major test focus.~~
- ~~lint, format and test passed on local.~~

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
id actually prefer NOT to introduce `AgentTypeConfig` yet - i think its a bit unclear what else should go on here, etc. does introducing this `AgentTypeConfig` provide any benefit?

to be clear, i love the idea of moving AGENT_TO_CLASS to a separate file. I just dont know if the config is needed

**Comment by skcoirz** [comment]
> id actually prefer NOT to introduce `AgentTypeConfig` yet - i think its a bit unclear what else should go on here, etc. does introducing this `AgentTypeConfig` provide any benefit?
> 
> to be clear, i love the idea of moving AGENT_TO_CLASS to a separate file. I just dont know if the config is needed

sure, @hwchase17 , if so, I can simply move AGENT_TO_CLASS to this file with a clear assert to make sure it’s consistent with AgentType. Does it work for you? Thanks.

**Comment by hwchase17** [comment]
> > id actually prefer NOT to introduce `AgentTypeConfig` yet - i think its a bit unclear what else should go on here, etc. does introducing this `AgentTypeConfig` provide any benefit?
> > to be clear, i love the idea of moving AGENT_TO_CLASS to a separate file. I just dont know if the config is needed
> 
> sure, @hwchase17 , if so, I can simply move AGENT_TO_CLASS to this file with a clear assert to make sure it’s consistent with AgentType. Does it work for you? Thanks.

what do you mean consistent with agent type?

**Comment by hwchase17** [comment]
but yes in general that sounds great

**Comment by skcoirz** [comment]
> > > id actually prefer NOT to introduce `AgentTypeConfig` yet - i think its a bit unclear what else should go on here, etc. does introducing this `AgentTypeConfig` provide any benefit?
> > > to be clear, i love the idea of moving AGENT_TO_CLASS to a separate file. I just dont know if the config is needed
> > 
> > 
> > sure, @hwchase17 , if so, I can simply move AGENT_TO_CLASS to this file with a clear assert to make sure it’s consistent with AgentType. Does it work for you? Thanks.
> 
> what do you mean consistent with agent type?

The idea is to confirm AGENT_TO_CLASS covers all items in AgentType esp. when there is a new AgentType.item introduced. Ideally, we want to raise the error during lint time, so that the future author would know there are other places to update just in case.

**Comment by hwchase17** [comment]
> > > > id actually prefer NOT to introduce `AgentTypeConfig` yet - i think its a bit unclear what else should go on here, etc. does introducing this `AgentTypeConfig` provide any benefit?
> > > > to be clear, i love the idea of moving AGENT_TO_CLASS to a separate file. I just dont know if the config is needed
> > > 
> > > 
> > > sure, @hwchase17 , if so, I can simply move AGENT_TO_CLASS to this file with a clear assert to make sure it’s consistent with AgentType. Does it work for you? Thanks.
> > 
> > 
> > what do you mean consistent with agent type?
> 
> The idea is to confirm AGENT_TO_CLASS covers all items in AgentType esp. when there is a new AgentType.item introduced. Ideally, we want to raise the error during lint time, so that the future author would know there are other places to update just in case.

ah got it

lets just add a unit test for that?

**Comment by skcoirz** [comment]
> > > > > id actually prefer NOT to introduce `AgentTypeConfig` yet - i think its a bit unclear what else should go on here, etc. does introducing this `AgentTypeConfig` provide any benefit?
> > > > > to be clear, i love the idea of moving AGENT_TO_CLASS to a separate file. I just dont know if the config is needed
> > > > 
> > > > 
> > > > sure, @hwchase17 , if so, I can simply move AGENT_TO_CLASS to this file with a clear assert to make sure it’s consistent with AgentType. Does it work for you? Thanks.
> > > 
> > > 
> > > what do you mean consistent with agent type?
> > 
> > 
> > The idea is to confirm AGENT_TO_CLASS covers all items in AgentType esp. when there is a new AgentType.item introduced. Ideally, we want to raise the error during lint time, so that the future author would know there are other places to update just in case.
> 
> ah got it
> 
> lets just add a unit test for that?

sure, either works. Updating now. Thanks for the quick feedback. :)

**Review by hwchase17 — APPROVED** [review]
looks great, thanks!

**Comment by skcoirz** [comment]
> looks great, thanks!

Thank You for the realtime review! This is awesome! :D

**Pull request merged**
