### PR TITLE
Add Google GenAppBuilder as Tools

### PR DESCRIPTION
**Pull request by julienmiquel**

### CODE REVIEW

**Review by julienmiquel — COMMENTED** [review]
ok

**Comment by hwchase17** [comment]
some documentation probably needed here

**Comment by leo-gan** [comment]
@julienmiquel Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

If this PR is not needed anymore, could you, please, let me know or close this PR?

**Comment by holtskinner** [comment]
FYI - This PR might be obsolete due to the Vertex AI Search retriever being added. I don't see any functionality in this PR that isn't already covered by the retriever, but if there is, then it should be added to the existing retriever.

https://python.langchain.com/docs/integrations/retrievers/google_vertex_ai_search

Vertex AI Search used to be named Enterprise Search on Gen App Builder, and the "Gen App Builder" name is no longer being used.

**Pull request closed without merging**
