### PR TITLE
Issam/hf embeddings

### PR DESCRIPTION
**Pull request by issam9**
Add support of HuggingFace embedding models

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
a few nits but otherwise this looks great to me!

there may be some linting things (i need to figure out a better way to check that before merging) but i can always take care of after merging!

thanks - this is awesome. do you have a twitter where i can give you a shoutout?

**Review by hwchase17 — COMMENTED** [review]
oh can you actually add sentence_transformers to requirements.txt after the `faiss` entry?

**Comment by issam9** [comment]
I added 3 commits. Thank you for your help. My twitter handle is: abdrahman_issam

**Comment by hwchase17** [comment]
> I added 3 commits. Thank you for your help. My twitter handle is: abdrahman_issam

awesome! will merge this in tmrw night and cut a new release on Tuesday!

**Comment by hwchase17** [comment]
> > I added 3 commits. Thank you for your help. My twitter handle is: abdrahman_issam
> 
> awesome! will merge this in tmrw night and cut a new release on Tuesday!

and thank you for adding this :) I think having support for the open source embedding models will be very important/useful

**Pull request merged**
