### PR TITLE
I added support for views into the SQLDatabase class

### PR DESCRIPTION
**Pull request by wadihpazos**
Currently the SQLDatabase class does not support reflecting views. These simple changes adds view support.  Made it optional with a flag in the constructor that defaults to existing behavior.

### CODE REVIEW

**Review by hwchase17 — APPROVED** [review]
nice, love it - thanks!

**Comment by wadihpazos** [comment]
@hwchase17 : Thank you for approving the changes. How do they get merged and released.  Sorry. First time I'm contributing to a public repo.  I saw that only 3/6 lint checks passed but not sure how to resolve the issues?

**Comment by hwchase17** [comment]
> @hwchase17 : Thank you for approving the changes. How do they get merged and released. Sorry. First time I'm contributing to a public repo. I saw that only 3/6 lint checks passed but not sure how to resolve the issues?

i can fix lint and then merge! will be in tmrws release

**Comment by hwchase17** [comment]
> @hwchase17 : Thank you! Would love any tips on how I could have done the process completely in case I have another bug/feature to work on. Sure the issues with lint are environmental for me. Also, assuming then you'll close this PR or is that on me to do? Finally, will I be listed as a contributor once the PR is merged? Thx!

there is a `make format` and `make lint` command you can run locally that will format and lint the code respectively!

**Comment by zzy9v4** [comment]
Very nice. thank you!

**Pull request merged**
