### PR TITLE
langchain[patch]: fix `OutputType` of OutputParsers and fix legacy API in OutputParsers

### PR DESCRIPTION
**Pull request by hmasdev**
# Description

This pull request aims to address specific issues related to the ambiguity and error-proneness of the output types of certain output parsers, as well as the absence of unit tests for some parsers. These issues could potentially lead to runtime errors or unexpected behaviors due to type mismatches when used, causing confusion for developers and users. Through clarifying output types, this PR seeks to improve the stability and reliability.

Therefore, this pull request

- fixes the `OutputType` of OutputParsers to be the expected type;
  - e.g. `OutputType` property of `EnumOutputParser` raises `TypeError`. This PR introduce a logic to extract `OutputType` from its attribute.
- and fixes the legacy API in OutputParsers like `LLMChain.run` to the modern API like `LLMChain.invoke`;
  - Note: For `OutputFixingParser`,  `RetryOutputParser` and `RetryWithErrorOutputParser`, this PR introduces `legacy`  attribute with False as default value in order to keep the backward compatibility
- and adds the tests for the `OutputFixingParser` and `RetryOutputParser`.

The following table shows my expected output and the actual output of the `OutputType` of OutputParsers.
I have used this table to fix `OutputType` of OutputParsers.

| Class Name of OutputParser | My Expected `OutputType` (after this PR)| Actual `OutputType` [evidence](#evidence) (before this PR)| Fix Required |
|---------|--------------|---------|--------|
| BooleanOutputParser | `<class 'bool'>` | `<class 'bool'>` | NO |
| CombiningOutputParser | `typing.Dict[str, Any]` | `TypeError` is raised | YES |
| DatetimeOutputParser | `<class 'datetime.datetime'>` | `<class 'datetime.datetime'>` | NO |
| EnumOutputParser(enum=MyEnum) | `MyEnum` | `TypeError` is raised | YES |
| OutputFixingParser | The same type as `self.parser.OutputType` | `~T` | YES |
| CommaSeparatedListOutputParser | `typing.List[str]` | `typing.List[str]` | NO |
| MarkdownListOutputParser | `typing.List[str]` | `typing.List[str]` | NO |
| NumberedListOutputParser | `typing.List[str]` | `typing.List[str]` | NO |
| JsonOutputKeyToolsParser | `typing.Any` | `typing.Any` | NO |
| JsonOutputToolsParser | `typing.Any` | `typing.Any` | NO |
| PydanticToolsParser | `typing.Any` | `typing.Any` | NO |
| PandasDataFrameOutputParser | `typing.Dict[str, Any]` | `TypeError` is raised | YES |
| PydanticOutputParser(pydantic_object=MyModel) | `<class '__main__.MyModel'>` | `<class '__main__.MyModel'>` | NO |
| RegexParser | `typing.Dict[str, str]` | `TypeError` is raised | YES |
| RegexDictParser | `typing.Dict[str, str]` | `TypeError` is raised | YES |
| RetryOutputParser | The same type as `self.parser.OutputType` | `~T` | YES |
| RetryWithErrorOutputParser | The same type as  `self.parser.OutputType` | `~T` | YES |
| StructuredOutputParser | `typing.Dict[str, Any]` | `TypeError` is raised | YES |
| YamlOutputParser(pydantic_object=MyModel) | `MyModel` | `~T` | YES |

NOTE: In "Fix Required", "YES" means that it is required to fix in this PR while "NO" means that it is not required.

# Issue

No issues for this PR.

# Twitter handle

- [hmdev3](https://twitter.com/hmdev3)

# Questions:

1. Is it required to create tests for legacy APIs `LLMChain.run` in the following scripts?
   - libs/langchain/tests/unit_tests/output_parsers/test_fix.py;
   - libs/langchain/tests/unit_tests/output_parsers/test_retry.py.

2. Is there a more appropriate expected output type than I expect in the above table?
   - e.g. the `OutputType` of `CombiningOutputParser` should be SOMETHING...

# Actual outputs (before this PR)

<div id='evidence'></div>

<details><summary>Actual outputs</summary>

## Requirements

- Python==3.9.13
- langchain==0.1.13

```python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import langchain
>>> langchain.__version__
'0.1.13'
>>> from langchain import output_parsers
```

### `BooleanOutputParser`

```python
>>> output_parsers.BooleanOutputParser().OutputType
<class 'bool'>
```

### `CombiningOutputParser`

```python
>>> output_parsers.CombiningOutputParser(parsers=[output_parsers.DatetimeOutputParser(), output_parsers.CommaSeparatedListOutputParser()]).OutputType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\workspace\venv\lib\site-packages\langchain_core\output_parsers\base.py", line 160, in OutputType
    raise TypeError(
TypeError: Runnable CombiningOutputParser doesn't have an inferable OutputType. Override the OutputType property to specify the output type.
```

### `DatetimeOutputParser`

```python
>>> output_parsers.DatetimeOutputParser().OutputType
<class 'datetime.datetime'>
```

### `EnumOutputParser`

```python
>>> from enum import Enum
>>> class MyEnum(Enum):
...     a = 'a'
...     b = 'b'
...
>>> output_parsers.EnumOutputParser(enum=MyEnum).OutputType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\workspace\venv\lib\site-packages\langchain_core\output_parsers\base.py", line 160, in OutputType
    raise TypeError(
TypeError: Runnable EnumOutputParser doesn't have an inferable OutputType. Override the OutputType property to specify the output type.
```

### `OutputFixingParser`

```python
>>> output_parsers.OutputFixingParser(parser=output_parsers.DatetimeOutputParser()).OutputType
~T
```

### `CommaSeparatedListOutputParser`

```python
>>> output_parsers.CommaSeparatedListOutputParser().OutputType
typing.List[str]
```

### `MarkdownListOutputParser`

```python
>>> output_parsers.MarkdownListOutputParser().OutputType
typing.List[str]
```

### `NumberedListOutputParser`

```python
>>> output_parsers.NumberedListOutputParser().OutputType
typing.List[str]
```

### `JsonOutputKeyToolsParser`

```python
>>> output_parsers.JsonOutputKeyToolsParser(key_name='tool').OutputType
typing.Any
```

### `JsonOutputToolsParser`

```python
>>> output_parsers.JsonOutputToolsParser().OutputType
typing.Any
```

### `PydanticToolsParser`

```python
>>> from langchain.pydantic_v1 import BaseModel
>>> class MyModel(BaseModel):
...     a: int
...
>>> output_parsers.PydanticToolsParser(tools=[MyModel, MyModel]).OutputType
typing.Any
```

### `PandasDataFrameOutputParser`

```python
>>> output_parsers.PandasDataFrameOutputParser().OutputType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\workspace\venv\lib\site-packages\langchain_core\output_parsers\base.py", line 160, in OutputType
    raise TypeError(
TypeError: Runnable PandasDataFrameOutputParser doesn't have an inferable OutputType. Override the OutputType property to specify the output type.
```

### `PydanticOutputParser`

```python
>>> output_parsers.PydanticOutputParser(pydantic_object=MyModel).OutputType
<class '__main__.MyModel'>
```

### `RegexParser`

```python
>>> output_parsers.RegexParser(regex='$', output_keys=['a']).OutputType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\workspace\venv\lib\site-packages\langchain_core\output_parsers\base.py", line 160, in OutputType
    raise TypeError(
TypeError: Runnable RegexParser doesn't have an inferable OutputType. Override the OutputType property to specify the output type.
```

### `RegexDictParser`

```python
>>> output_parsers.RegexDictParser(output_key_to_format={'a':'a'}).OutputType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\workspace\venv\lib\site-packages\langchain_core\output_parsers\base.py", line 160, in OutputType
    raise TypeError(
TypeError: Runnable RegexDictParser doesn't have an inferable OutputType. Override the OutputType property to specify the output type.
```

### `RetryOutputParser`

```python
>>> output_parsers.RetryOutputParser(parser=output_parsers.DatetimeOutputParser()).OutputType
~T
```

### `RetryWithErrorOutputParser`

```python
>>> output_parsers.RetryWithErrorOutputParser(parser=output_parsers.DatetimeOutputParser()).OutputType
~T
```

### `StructuredOutputParser`

```python
>>> from langchain.output_parsers.structured import ResponseSchema
>>> response_schemas = [ResponseSchema(name="foo",description="a list of strings",type="List[string]"),ResponseSchema(name="bar",description="a string",type="string"), ]
>>> output_parsers.StructuredOutputParser.from_response_schemas(response_schemas).OutputType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\workspace\venv\lib\site-packages\langchain_core\output_parsers\base.py", line 160, in OutputType
    raise TypeError(
TypeError: Runnable StructuredOutputParser doesn't have an inferable OutputType. Override the OutputType property to specify the output type.
```

### `YamlOutputParser`

```python
>>> output_parsers.YamlOutputParser(pydantic_object=MyModel).OutputType
~T
```

<div>

### CODE REVIEW

**Review by eyurtsev — APPROVED** [review]

**Comment by eyurtsev** [comment]
Thank you @hmasdev PR looks great. Appreciate all the test coverage and sorry it took so long to get this merged

**Comment by alessnet** [comment]
Hello guys @hmasdev, @eyurtsev 

In the OutputFixingParser, the new code uses "ainvoke" instead of arun. No problem there.

However, the new code using ainvoke uses "input" instead of "completion" of a template input, and thus the "NAIVE_FIX_PROMPT" (default prompt) crashers with "missing template variable 'completion'". 

```python
if self.legacy and hasattr(self.retry_chain, "arun"):
    completion = await self.retry_chain.arun(
        instructions=self.parser.get_format_instructions(),  # noqa: E501
        completion=completion,
        error=repr(e),
    )
else:
    try:
        completion = await self.retry_chain.ainvoke(
            dict(
                instructions=self.parser.get_format_instructions(),  # noqa: E501
                input=completion,
                error=repr(e),
            )
        )
```

Do I need to create a new bug for that?

**Comment by benobytes** [comment]
@alessnet 
Seconding this, I am now getting all kind of weird errors now, when I try to use this. 
```
KeyError: "Input to PromptTemplate is missing variables {'completion'}.  Expected: ['completion', 'error', 'prompt'] Received: ['input', 'prompt', 'error']"
```
I tried to fix it by overwriting the input prompt.
```py
OLD_NAIVE_COMPLETION_RETRY_WITH_ERROR = """Prompt:
{prompt}
Completion:
{input}

Above, the Completion did not satisfy the constraints given in the Prompt.
Details: {error}
Please try again:"""
OLD_NAIVE_RETRY_WITH_ERROR_PROMPT = PromptTemplate.from_template(
    NAIVE_COMPLETION_RETRY_WITH_ERROR
)
```

However, I now get validation errors:
```
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Generation
     | text
     |   str type expected (type=type_error.str)
```

**Comment by hmasdev** [comment]
@alessnet 
Thanks for pointing that out. I agree that.
@benobytes 
Thanks for trying to solve it. Could you show us a reproducible sample code?
Replacing `{completion}` with `{input}` in `NAIVE_FIX_PROMPT` seems to work for me.

@eyurtsev 
What do you think? I think that a new PR should be created to 
- replace `{completion}` with `{input}` in `NAIVE_FIX_PROMPT`;
  - See the example code to check whether this works
- update [libs/langchain/langchain/output_parsers/fix.py#L66-L88](https://github.com/langchain-ai/langchain/blob/langchain%3D%3D0.2.6/libs/langchain/langchain/output_parsers/fix.py#L66-L88) and [libs/langchain/langchain/output_parsers/fix.py#L103-L125](https://github.com/langchain-ai/langchain/blob/langchain%3D%3D0.2.6/libs/langchain/langchain/output_parsers/fix.py#L103-L125);
- specify `IntputType` and `OutputType` of `retry_chain`
  - e.g. define `RetryChainInputSchema` with `pydantic` and change `retry_chain: Union[RunnableSerializable, Any]` to `retry_chain: Union[Runnable[InputSchema, str], Any]` in [libs/langchain/langchain/output_parsers/fix.py#L26](https://github.com/langchain-ai/langchain/blob/langchain%3D%3D0.2.6/libs/langchain/langchain/output_parsers/fix.py#L26) . ;
- add tests with `retry_chain` except `RunnablePassthrough()`.

## Example Code of an error pointed out by @alessnet and a simple solution

- `parser_noretry`: an OutputFixingParser instance without retries which is used for checking whether it raises OutputParserException;
- `parser_asis`: an OutputFixingParser instance using `NAIVE_FIX_PROMPT` to retry;
- `parser_tobe`: an OutputFixingParser instance using `NAIVE_FIX_PROMPT_` to retry. `NAIVE_FIX_PROMPT_`  is a string in which `{completion}` is replaced by `{input}` in `NAIVE_FIX_PROMPT`.

```python
>>> # Preparation
>>> from langchain_openai import OpenAI
>>> from langchain.output_parsers import OutputFixingParser
>>> from langchain.output_parsers import DatetimeOutputParser
>>> from langchain.output_parsers.prompts import NAIVE_FIX_PROMPT, NAIVE_FIX, PromptTemplate
>>> llm = OpenAI()
>>>
>>> # Naive Fix
>>> NAIVE_FIX_PROMPT_ = PromptTemplate.from_template(NAIVE_FIX.replace('{completion}','{input}'))
>>>
>>> # create parser
>>> parser_noretry = OutputFixingParser(retry_chain=NAIVE_FIX_PROMPT|llm, parser=DatetimeOutputParser(), max_retries=0)
>>> parser_asis = OutputFixingParser(retry_chain=NAIVE_FIX_PROMPT|llm, parser=DatetimeOutputParser(), max_retries=2)
>>> parser_tobe = OutputFixingParser(retry_chain=NAIVE_FIX_PROMPT_|llm, parser=DatetimeOutputParser(), max_retries=2)
>>>
>>> # check the result of parse
>>> parser_noretry.parse('2001-01')
...{OMITTED}...
langchain_core.exceptions.OutputParserException: Could not parse datetime string: 2001-01
>>> parser_asis.parse('2001-01')
...{OMITTED}...
KeyError: "Input to PromptTemplate is missing variables {'completion'}.  Expected: ['completion', 'error', 'instructions'] Received: ['instructions', 'input', 'error']"
>>> parser_tobe.parse('2001-01')
datetime.datetime(2001, 1, 1, 0, 0)
```

<details><summary>system_info</summary>

```sh
 $ python -m langchain_core.sys_info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.2.10
> langchain: 0.2.6
> langsmith: 0.1.77
> langchain_openai: 0.1.13
> langchain_text_splitters: 0.2.2
> langchainhub: 0.1.20

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve
```

</div>

**Comment by benobytes** [comment]
@hmasdev Thanks for the response, I managed to recreate it here. 

```py
# Preparation
from langchain_openai import ChatOpenAI
from langchain.output_parsers import RetryWithErrorOutputParser
from langchain_core.output_parsers.pydantic import PydanticOutputParser
from langchain_core.prompts import PromptTemplate, ChatPromptTemplate
from pydantic.v1 import BaseModel


llm = ChatOpenAI(model="gpt-4o")

# Naive Fix
OLD_NAIVE_COMPLETION_RETRY_WITH_ERROR = """Prompt:
{prompt}
Completion:
{input}

Above, the Completion did not satisfy the constraints given in the Prompt.
Details: {error}
Please try again:"""
OLD_NAIVE_RETRY_WITH_ERROR_PROMPT = PromptTemplate.from_template(OLD_NAIVE_COMPLETION_RETRY_WITH_ERROR)


# Example model
class Joke(BaseModel):
    subject: str
    action: str
    location: str

# We change the subject to int to force a failure and output fix.
class FalseJoke(BaseModel):
    subject: int
    action: str

# Get the Pydantic output parser and the retry parser
pydantic_parser = PydanticOutputParser(pydantic_object=FalseJoke)
retry_parser = RetryWithErrorOutputParser.from_llm(
    parser=pydantic_parser,
    llm=llm,
    max_retries=3,
    prompt=OLD_NAIVE_RETRY_WITH_ERROR_PROMPT,
)
# Example input
example_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", "You tell funny jokes! {instructions}"),
        ("human", "Tell me a joke about a {subject}."),
    ]
)

# Get the completion
prompt = example_prompt.invoke({
    "instructions": PydanticOutputParser(pydantic_object=Joke).get_format_instructions(),
    "subject": "chicken"
})
completion = llm.invoke(prompt).content

# Parse the completion
retry_parser.parse_with_prompt(completion=completion, prompt_value=prompt)
```

This provides the following error:
```
ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)
```

**Comment by hmasdev** [comment]
I have created a PR: #23967 

- corrected keyword arguments given to `retry_chain`;
- add a test when using the default prompt:
  - `NAIVE_FIX_PROMPT` for `OutputFixingParser`;
  - `NAIVE_RETRY_PROMPT` for `RetryOutputParser`;
  - `NAIVE_RETRY_WITH_ERROR_PROMPT` for `RetryWithErrorOutputParser`;
- add comments on `retry_chain` input and output types;

NOTE:

- I decided to modify keyword argument names for backward compatibility, though I proposed to update prompt in https://github.com/langchain-ai/langchain/pull/19792#issuecomment-2198597292
- and gave up to specify `IntputType` and `OutputType` of `retry_chain` because type annotation like `retry_chain: Union[Runnable, Any]` does not work:
   ```python
   RuntimeError: no validator found for <class 'langchain_core.runnables.base.Runnable'>, see `arbitrary_types_allowed` in Config
   ```

**Comment by sad-zero** [comment]
@benobytes 
The error is caused by the `ChatOpenAI` class.

`PydanticOutputParser` inherits from `JsonOutputParser`. The `parse` method in `JsonOutputParser` accepts only a `string`.

Here is the relevant code:

```python
class PydanticOutputParser(JsonOutputParser):
    def parse(self, text: str):
        return super().parse(text)

class JsonOutputParser:
    def parse(self, text: str):
        return self.parse_result([Generation[text=text]])
    
    def parse_result(self, result: List[Generation], *, partial: bool = False):
        text = result[0].text.strip()
        ...
```

`RetryWithErrorOutputParser` or `OutputFixingParser` attempt to retry the previous response of the LLM to parse it. However, at this point, `ChatBaseModel` (which `ChatOpenAI` inherits from) responds with a `BaseMessage`, not a `string`. Therefore, `JsonOutputParser` can't parse the response.

To fix this, you can modify your code as follows:

```python
from langchain_openai import OpenAI
...
llm = OpenAI(...)
...
```

**Comment by benobytes** [comment]
@sad-zero Hmmm... I have always been using the ChatOpenAI and only recently after updating has this issues arisen. I have some traces of this working correctly, it seemed to wrap it in an LLM Chain prior. Thanks for the solve though.

**Comment by sad-zero** [comment]
@benobytes 
Yes, this issue seems recent. It arises because of different response types:

- When using `ChatBaseModel`, the Legacy chain returns a string type.
- However, the LCEL chain returns a BaseMessage type.

Here's an example illustrating this:

```python
from langchain.chains.llm import LLMChain
from langchain.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain.schema import HumanMessage
from langchain_google_vertexai import ChatVertexAI

chat_llm = ChatVertexAI(model_name="gemini-1.5-flash")

# Creating a prompt template
prompt = ChatPromptTemplate.from_messages([
    ("system", "Act as a helpful assistant."),
    MessagesPlaceholder(variable_name="messages"),
])

# Setting up chains
legacy_chain = LLMChain(prompt=prompt, llm=chat_llm)
lcel_chain = prompt | chat_llm

# Example message
messages = [HumanMessage(content="Hello~")]

# Running both chains
legacy_res = legacy_chain.run({"messages": messages})
lcel_res = lcel_chain.invoke({"messages": messages})

# Outputting types of results
print(f"type: {type(legacy_res)}")  # type: str
print(f"type: {type(lcel_res)}")    # type: AIMessage
```

It appears there might be an unexpected bug causing this difference.

**Pull request merged**
