### PR TITLE
Swap in Sympy instead of numexpr for more expressive LLMMath tool

### PR DESCRIPTION
**Pull request by zoeqevans**
- Description: Swapped in `sympy` instead of `numexpr` in the LLMMath Chain
  - Issue: Relevant to #8363 
  - Dependencies: None
  - Tag maintainer: @hinthornw 

Note that we already use `sympy` in the symbolic math tool, so this actually removes a dependency!

`numexpr` is actually quite fragile to input, whereas `sympify` is really quite hard to break. Take the iconic Langchain tool example mixing information retrieval and numerical calculation: _"Who is Leo DiCaprio's girlfriend? What is her current age raised to the 0.43 power?"_ (from this [tutorial page](https://python.langchain.com/docs/modules/agents/how_to/intermediate_steps)).

If you make the maths more exotic ("What is the first prime number larger than her age?", "What is the factorial of her age?", etc.) `numexpr` will raise an exception. `sympy` handles these with flying colours.

I used the chain from that example, with the prompt:
```
"In the sky, I am the number of sisters who dance, Bound by myth, in a celestial trance. On Earth, I am the continents that span, Holding diverse life, since time began.
What number am I?

Now multiply that number by the age of Zoe Saldana's partner, and raise it to the 2.43rd power.
Take the fourth digit of the answer, then take the factorial of that, and call it X.
What's the smallest prime number greater than X?
"""
```
and with `sympy`, my chain passed with flying colours :)

### CODE REVIEW

**Comment by baskaryan** [comment]
i wonder if for backwards compatibility / flexibility we should introduce something like an "engine" parameter that lets' folks choose which they want to use (and uses appropriate prompt based on that)

**Comment by leo-gan** [comment]
@montyevans Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

**Comment by efriis** [comment]
Looks like this isn't being worked on anymore. I'll close for now, and if you resume work, feel free to reopen!

**Comment by nloeff** [comment]
@efriis if there is interest I can restart work on this PR

**Pull request closed without merging**
