### PR TITLE
Incorrect argument count handling

### PR DESCRIPTION
**Pull request by swappysh**
Throwing ToolException when incorrect arguments are passed to tools so that that agent can course correct them.

# Incorrect argument count handling

I was facing an error where the agent passed incorrect arguments to tools. As per the discussions going around, I started throwing ToolException to allow the model to course correct.

## Who can review?

Community members can review the PR once tests pass. Tag maintainers/contributors who might be interested:

### CODE REVIEW

**Review by hwchase17 — APPROVED** [review]
thanks! great catch

**Comment by swappysh** [comment]
Looks ready to merge. @hwchase17 thanks! 🎉

**Comment by swappysh** [comment]
Fixed the test error and formatted the code

**Comment by swappysh** [comment]
@hwchase17 All checks passed, this can be merged.

**Pull request merged**
