### PR TITLE
add new field

### PR DESCRIPTION
**Pull request by zhanghexian**

### CODE REVIEW

**Comment by eyurtsev** [comment]
@zhanghexian Thanks for your contribution! Would you be able to include a PR summary explaining what the goal of the PR is? It's helpful to be able to review the implementation.

**Comment by zhanghexian** [comment]
We dynamically extend the data fields stored in vearch vector database. The previous version only supported fixed fields, but now supports all the fields you want to set.Thanks!

**Comment by zhanghexian** [comment]
anything else need?please tell me thanks!

**Comment by zhanghexian** [comment]
please check my new code,which supports all the fields you want to set.Thanks!

**Pull request closed without merging**
