### PR TITLE
Add amazon_bedrock_chat to get_type_to_cls_dict

### PR DESCRIPTION
**Pull request by austinmw**
**Description:** Add `BedrockChat` to `get_type_to_cls_dict` map

### CODE REVIEW

**Comment by efriis** [comment]
Hey @austinmw ! I don't think we want to add the bedrock `chat_model` to the `llms` package like this. Could you use `from langchain.chat_models import BedrockChat` in your code as-is?

**Comment by austinmw** [comment]
Hi, I notice that downstream libraries like NeMo guardrails use `get_type_to_cls_dict` in order to determine which class to call. So currently you can specify `engine: 'amazon_bedrock'`, but it's not possibly to specify to use the chat class:

https://github.com/NVIDIA/NeMo-Guardrails/blob/5f2541edb3e1115d48fc219e6e4d287d2d759ca1/nemoguardrails/llm/providers.py#L47

**Comment by efriis** [comment]
Got it. I think this is something that should be handled on the NeMo guardrails side instead to add the chat models. 

This dictionary ultimately maps names to `BaseLLM`, which `BedrockChat` does not subclass (that's a `BaseChatModel` instead)

However, the way NeMo uses the dictionary would be compatible with both because it requires entries to be `BaseLanguageModel`, which is the superclass of both `BaseLLM` and `BaseChatModel`.

If you need `BedrockChat` in your work, it looks like you can do something like the following in guardrails
```
from langchain.chat_models.bedrock import BedrockChat
from nemoguardrails.llm.providers import register_llm_provider
register_llm_provider('BedrockChat', BedrockChat)
```

Let me know if you have any other thoughts! Otherwise I'll close this

**Comment by austinmw** [comment]
Sounds good!

**Pull request closed without merging**
