### PR TITLE
added missing req chromadb tiktoken

### PR DESCRIPTION
**Pull request by qpo**
<!-- Thank you for contributing to LangChain!

Replace this comment with:
added missing req chromadb tiktoken

@baskaryan

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
why are these required? cc @baskaryan

**Comment by baskaryan** [comment]
> why are these required? cc @baskaryan

docs/requirements.txt is only for api reference, don't think we need chroma or tiktoken for that?

**Comment by qpo** [comment]
I was only able to run the examples in https://python.langchain.com/docs/get_started/quickstart once I installed these two.

**Comment by baskaryan** [comment]
> I was only able to run the examples in https://python.langchain.com/docs/get_started/quickstart once I installed these two.

ooh interesting, could your provide the code + errors where it failed?

**Pull request closed without merging**
