### PR TITLE
commit two document_loaders to support xml file and java file

### PR DESCRIPTION
**Pull request by imaginespark**
Fixes # (issue)

#### Before submitting

####@eyurtsev

Tag maintainers/contributors who might be interested:

### CODE REVIEW

**Comment by hwchase17** [comment]
what exactly is going on in the java file?

docs/example notebook would be helpful

**Comment by imaginespark** [comment]
> what exactly is going on in the java file?
> 
> docs/example notebook would be helpful

@hwchase17 Thank you for your reply, I will to read the example later. xml.py just can parse the xml file, and java.py will load the original java code to pretrain or finetuning.

**Comment by imaginespark** [comment]
@hwchase17 why my request for a document loader named xml.py can't be passed, I have submitted the request three days ago, but another developer submit the same xml.py can be passed yesterday, which exists some obvious error about its module comments "Loader that loads Microsoft Excel files".

**Comment by baskaryan** [comment]
looks like an unstructured xml loader has been added in #5955, and i believe the TextLoader already allows for encoding detection, so will closing for now. @imaginespark let me know if i missed something!

**Pull request closed without merging**
