### PR TITLE
community[minor],core[major]: Move GraphVectorStore to community

### PR DESCRIPTION
**Pull request by eyurtsev**
* This PR moves graph vectorstore to community until there is more than one implementation based on it and the abstraction gets battle-tested.
* Renaming Node and Link to GraphStoreNode and GraphStoreLink as Node is already as a langgraph primitive.

### CODE REVIEW

**Comment by eyurtsev** [comment]
Hi @cbornet, we're going to move the implementation to community for now. I think the strategy going forward will be to get community contributed abstractions contributed to langchain_community prior to being adopted into core to get battle-tested / proved as useful

**Comment by eyurtsev** [comment]
@cbornet were you planning on adding implementations to the langchain_astradb partner package?

**Comment by eyurtsev** [comment]
@cbornet touched based internally, we'll keep in core for now with `@beta` decorator. We wanted to update the names of `Node` and `Link`  to avoid collision with langgraph primitives `Node`. Let us know if `GraphStoreNode` and `GraphStoreLink` are OK or if you have a better suggestion?

**Comment by cbornet** [comment]
What about `GraphNode`/`GraphLink` to keep the names short ?

**Comment by eyurtsev** [comment]
Closing in favor of: https://github.com/langchain-ai/langchain/pull/24195

**Pull request closed without merging**
