### PR TITLE
Bedrock cohere embedding support

### PR DESCRIPTION
**Pull request by celmore25**
- **Description:** adding cohere embedding support to bedrock embedding class
  - **Issue:** N/A
  - **Dependencies:** None
  - **Tag maintainer:** @3coins 
  - **Twitter handle:** celmore25

### CODE REVIEW

**Comment by celmore25** [comment]
@3coins see test script below...
```python
import boto3
import os

region = os.environ.get("AWS_REGION")
boto3_bedrock = boto3.client(
    service_name='bedrock-runtime',
    region_name=region,
)

from langchain.embeddings import BedrockEmbeddings

print('----------------Cohere Test----------------')
embedding_model = BedrockEmbeddings(
    client=boto3_bedrock,
    model_id="cohere.embed-english-v3",
)
output = embedding_model.embed_query("hello my name is clay")
print(f"The embedding vector has {len(output)} values\n{output[0:3]+['...']+output[-3:]}")
output = embedding_model.embed_documents(["hello my name is clay", "hello my name is piyush"])
print(f"The output has {len(output)} docs")

print('\n----------------Cohere Test with Kwargs----------------')
embedding_model = BedrockEmbeddings(
    client=boto3_bedrock,
    model_id="cohere.embed-english-v3",
    model_kwargs={"input_type": "search_document"}
)
output = embedding_model.embed_query("hello my name is clay")
print(f"The embedding vector has {len(output)} values\n{output[0:3]+['...']+output[-3:]}")
output = embedding_model.embed_documents(["hello my name is clay", "hello my name is piyush"])
print(f"The output has {len(output)} docs")

print('\n----------------Titan Tests----------------')
embedding_model = BedrockEmbeddings(
    client=boto3_bedrock,
    model_id="amazon.titan-embed-text-v1",
)
output = embedding_model.embed_query("hello my name is clay")
print(f"The embedding vector has {len(output)} values\n{output[0:3]+['...']+output[-3:]}")
output = embedding_model.embed_documents(["hello my name is clay", "hello my name is piyush"])
print(f"The output has {len(output)} docs")
```

**Review by efriis — COMMENTED** [review]
Thanks for the contribution @celmore25 ! 2 requests:

- remove `EmbeddingInputOutputAdapter` (this abstraction is more confusing than it's worth)
- move logic into if statements in `_embedding_func` to handle amazon vs. cohere

Thanks!

**Comment by celmore25** [comment]
@efriis - thanks for looking over. updates have been made and the linting error from above should be fixed because of this last commit as well.

**Review by efriis — APPROVED** [review]

**Comment by efriis** [comment]
Thanks @celmore25 !

**Comment by efriis** [comment]
Btw @celmore25 - looks like the documented output on the blog post should have an extra set of square brackets around it if you can ping that team :)

https://aws.amazon.com/blogs/aws/amazon-bedrock-now-provides-access-to-cohere-command-light-and-cohere-embed-english-and-multilingual-models/

**Comment by celmore25** [comment]
Oh yes interesting - there should be two vectors which are output from that. Just ran the code and that's what I got as well. Will follow up internally with them :)

**Comment by celmore25** [comment]
@efriis - thank you for feedback! @sebsto updated this just now. Always appreciated!

**Comment by efriis** [comment]
Phenomenal. Thanks @sebsto !

**Pull request merged**
