### PR TITLE
add  vearch vectorstore

### PR DESCRIPTION
**Pull request by zhanghexian**

### CODE REVIEW

**Comment by baskaryan** [comment]
hey @zhanghexian, what's the change here?

**Comment by zhanghexian** [comment]
No change,thanks!



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 12, 2023 05:58 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [langchain-ai/langchain] add  vearch vectorstore (PR #10432)




 
hey @zhanghexian, what's the change here?

**Comment by zhanghexian** [comment]
hello, I added veach in init.py file ,but it show that mypacket import but not used. how i can fix this,commit by demo?but the demo i commit before.thanks!

**Comment by zhanghexian** [comment]
hello,now my commit keeps reporting this error: the packet imported but not used,please give me some hint ,thanks

**Pull request closed without merging**
