### PR TITLE
doc: update the openai_function_agent document

### PR DESCRIPTION
**Pull request by DayuanJiang**
- **Description:** This pull request updates the openai_function_agent document. The update enhances the document in three significant ways:
    - Firstly, it eliminates imports that lead to import errors such as `langchain_experimental`.
    - Secondly, it initializes the agent by directly calling the `OpenAIFunctionsAgent`, instead of using the less intuitive `initialize_agent`.
    - Lastly, it substitutes the tools with those that don't require additional external services, simplifying the process for users to reproduce the notebook.
  - **Tag maintainer:** @baskaryan

### CODE REVIEW

**Comment by GetsEclectic** [comment]
i appreciate this update, i was just looking at creating a similar pr

**Comment by eyurtsev** [comment]
@baskaryan / @hwchase17 We've used the same question in a bunch of the agents, but I do think that using a freely available tool (e.g., wikipedia) makes for a nicer on ramp experience

**Comment by efriis** [comment]
Hey @DayuanJiang ! This doc was rewritten in LCEL in the meantime. I like the change if you're game to update the example to be LCEL, and otherwise we can close this and add it to the todo list :)

**Comment by DayuanJiang** [comment]
Hello @efriis, I am glad to assist in updating the example to LCEL. However, considering that the library's structure has significantly changed since the PR was issued a month ago, would it be more efficient to close this PR and issue a new one with the update to prevent conflicts?

Additionally, I have another PR (#11246) that delineates the differences between `OpenAIMultiFunctionsAgent` and `OpenAIFunctionsAgent`. Unfortunately, it has not received any response from the maintainers since it was issued a month ago. If you possess merge permissions, could you kindly review it?

**Comment by efriis** [comment]
Works for me! I'll check out #11246

**Pull request closed without merging**
