### PR TITLE
OpenSearch : Add OpenSearch as semantic cache

### PR DESCRIPTION
**Pull request by naveentatikonda**
### Description
Use OpenSearch vector store as Semantic Cache.

### Twitter Handle
**@OpenSearchProj**

### CODE REVIEW

**Comment by naveentatikonda** [comment]
> Run `make format ` to format the code style. Run `make lint` to checkout before pushing.

I tried to run it. But, it is not showing all these errors on my local.

**Comment by naveentatikonda** [comment]
@hwchase17 @baskaryan Can I get this PR reviewed ?

**Review by Undertone0809 — APPROVED** [review]

**Comment by naveentatikonda** [comment]
@hwchase17 @baskaryan Did you get a chance to review this PR ?

**Review by baskaryan — APPROVED** [review]

**Comment by naveentatikonda** [comment]
@efriis @baskaryan Can you please help to merge this PR. I rebased it with master. I'm not sure if I need to do something to fix the failing Vercel check

**Comment by naveentatikonda** [comment]
@baskaryan @hwchase17 @efriis @eyurtsev @nfcampos Can someone please prioritize this PR and merge it asap. Thanks!

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
