### PR TITLE
Fix problem with sql_chain and quotation marks: normalize_sql_cmd

### LINKED ISSUE #3305: Problem with sql_chain and quotation marks
Hi,

I observed an issue with sql_chain and quotation marks. 
The SQL that was send had quotation marks around and triggered an error in the DB.

This is the DB engine:
```python
from sqlalchemy import create_engine
engine = create_engine("sqlite:///:memory:")
```

The solution is very simple. Just detect and remove quotation marks from 
the beginning and the end of the generated SQL statement.

What do you think?

PS: <s>I can not replicate the error at the moment. So can not not provide any concrete error message. Sorry.</s>

PPS: see code to reproduce and error message below

### PR DESCRIPTION
**Pull request by PhilipMay**
fixes #3305

### CODE REVIEW

**Comment by PhilipMay** [comment]
I am not 100% sure if this locale solution (`@staticmethod` in `SQLDatabaseChain`) is the right solution.

Are there more places where this kind of normalization is needed or even implemented? Should that normalization
be on a more generic place in the code?

**Comment by PhilipMay** [comment]
This is ready for review please.

**Comment by anabranch** [comment]
@PhilipMay , I hit this issue too.

One problem that might come up I believe with this implementation is the following query.

```
"SELECT * FROM blah_table where x='F'
```

I'm not sure if it's more likely that quotations **aren't mirrored** (e.g., starts with `"` ends with `'`) or whether it's more likely that a quotation would be omitted (like in my above example). If I read your implementation right, it remove the final `'` from the query, even though it should keep it.

Not sure of the right answer here, but wanted to bring it up to make sure we're covering all the edge cases effectively.

**Comment by PhilipMay** [comment]
Hi @anabranch 

> If I read your implementation right, it remove the final ' from the query, even though it should keep it.

That is not right. The code below sais: 

"(if it starts and ends with double quotation mark) or (if it starts and ends with single quotation mark)"

If it starts with double and ends with single -> nothing will be changed. IMO that also would be incorrect SQL.

```python
            if (
                (sql_cmd.startswith('"') and sql_cmd.endswith('"'))
                or (sql_cmd.startswith("'") and sql_cmd.endswith("'"))
            ) and (len(sql_cmd) >= 2):
```

Does that resolve your reservations? @anabranch

**Comment by PhilipMay** [comment]
@hwchase17 can you please approve the workflows?

**Comment by PhilipMay** [comment]
Ok. So checks are green. IMO this can be merged. :-)

**Comment by hansvdam** [comment]
I'm not sure, but to me the problem is that the prompt template is wrong in asking for an SQL-statement with quotes. I think it is better to just not do that:
https://github.com/hwchase17/langchain/pull/4101

**Comment by PhilipMay** [comment]
> I'm not sure, but to me the problem is that the prompt template is wrong in asking for an SQL-statement with quotes. I think it is better to just not do that: #4101

I agree. #4101 would be useful. But removing the quotes - just in case - would also be useful IMO.

**Comment by leo-gan** [comment]
@PhilipMay Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

If this PR is not needed anymore, could you, please, let me know?

**Comment by efriis** [comment]
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

**Pull request closed without merging**
