### PR TITLE
community: Ontotext GraphDB QA Chain Implementation Improvements

### PR DESCRIPTION
**Pull request by nelly-hateva**
- **Description:** Ontotext GraphDB QA Chain Implementation Improvements : Use the SPARQLWrapper library for querying the server, which doesn't swallow the server error message. Validate the generated SPARQL query on the server side, not in the client. 
- **Issue:** N/A
- **Dependencies:** SPARQLWrapper
- **Twitter handle:** @OntotextGraphDB

### CODE REVIEW

**Comment by nelly-hateva** [comment]
@baskaryan Hello. Please, review this, when you have the time

**Comment by nelly-hateva** [comment]
@baskaryan Hello. Please, review this, when you have the time

**Comment by nelly-hateva** [comment]
@efriis Hello. Please, review this, when you have the time

**Comment by efriis** [comment]
Hey! Closing because this changes enough files to be a high-risk change without a real motivation for it.

If you want to submit again, try to change as little as possible to get your change done - this makes your PR more reviewable. Also please file a motivating issue before making a big change like this - that way we can comment on the motivation before you invest effort in a change that we can't merge in!

**Pull request closed without merging**
