### PR TITLE
core: add try block to merge_dicts

### PR DESCRIPTION
**Pull request by economy**
- **Description:** add try block to merge_dicts in utils 
  - **Issue:** #16441 
  - **Dependencies:** None

### CODE REVIEW

**Comment by Dobiichi-Origami** [comment]
@efriis PTAL

**Comment by hwchase17** [comment]
when does this occur? im guessin theres a deeper issue

**Comment by Dobiichi-Origami** [comment]
@hwchase17 
Further information included in comments: #16441

**Comment by baskaryan** [comment]
closing for now, please see https://github.com/langchain-ai/langchain/issues/16441#issuecomment-1922015976

**Pull request closed without merging**
