### PR TITLE
Text splitter for Markdown files by header

### PR DESCRIPTION
**Pull request by rlancemartin**
This creates a new kind of text splitter for markdown files.

The user can supply a set of headers that they want to split the file on.

We define a new text splitter class, `MarkdownHeaderTextSplitter`, that does a few things:

(1) For each line, it determines the associated set of user-specified headers 
(2) It groups lines with common headers into splits

See notebook for example usage and test cases.

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
not sure we need `sorted(splits, key=lambda x: (-len(x[0]), -x[0].count('#')))`

**Review by hwchase17 — COMMENTED** [review]
tbh probably best reviewd by writing a bunch of test cases and ensuring it works

**Comment by rlancemartin** [comment]
> tbh probably best reviewd by writing a bunch of test cases and ensuring it works

Done. Added to notebook.

**Comment by rlancemartin** [comment]
> not sure we need `sorted(splits, key=lambda x: (-len(x[0]), -x[0].count('#')))`

Re-organized code a bit; we no longer do this.

**Pull request merged**
