### PR TITLE
fix: change sparkllm spark_app_url to spark_api_url

### PR DESCRIPTION
**Pull request by fu1996**
community: fix - change sparkllm spark_app_url to spark_api_url

- **Description:** 
  - Change the variable name from `sparkllm spark_app_url` to `spark_api_url` in the community package.

### CODE REVIEW

**Comment by liugddx** [comment]
Please change the doc. https://github.com/langchain-ai/langchain/blob/d9e6ca22799fe54482f5ca02eead6a23f0006c31/docs/docs/integrations/chat/sparkllm.ipynb#L37

**Review by liugddx — APPROVED** [review]
LGTM

**Review by baskaryan — APPROVED** [review]

**Comment by fu1996** [comment]
Hi everyone, it's just a small change. Can someone help merge it? 😊

**Comment by fu1996** [comment]
Hi, sorry to bother you. I have resolved the conflict and if possible, I would like to merge it.

**Pull request merged**
