### PR TITLE
Community[minor]: Added checksum in while send data to pebblo-cloud

### PR DESCRIPTION
**Pull request by dristysrivastava**
- **Description:** 
            - Updated checksum in doc metadata
            - Sending checksum and removing actual content, while sending data to `pebblo-cloud` if `classifier-location `is `pebblo-cloud` in `/loader/doc` API
            - Adding `pb_id` i.e. pebblo id to doc metadata
            - Refactoring as needed.
            - Sending `content-checksum` and removing actual content, while sending data to `pebblo-cloud` if `classifier-location `is `pebblo-cloud` in `prmopt` API
- **Issue:** NA
- **Dependencies:** NA
- **Tests:** Updated
- **Docs** NA

### CODE REVIEW

**Comment by dristysrivastava** [comment]
@srics @Raj725 Please review

**Comment by srics** [comment]
> @srics @Raj725 Please review

LGTM

**Review by srics — APPROVED** [review]

**Review by Raj725 — APPROVED** [review]

**Review by Raj725 — APPROVED** [review]

**Review by Raj725 — APPROVED** [review]

**Review by srics — APPROVED** [review]
LGTM

**Comment by dristysrivastava** [comment]
@eyurtsev  Please review

**Comment by srics** [comment]
@eyurtsev @hwchase17 Can you pls help to review & land this PR? A significantly big enterprise user is waiting for this update. It is reviewed and signed off by [pebblo](https://github.com/daxa-ai/pebblo) maintainers.

**Review by eyurtsev — APPROVED** [review]

**Pull request merged**
