### PR TITLE
Fixed tool names snake_case

### PR DESCRIPTION
**Pull request by jatinchawda1503**
#16396
Fixed
1. golden_query
2. google_lens
3. memorize
4. merriam_webster
5. open_weather_map
6. pub_med
7. stack_exchange
8. generate_image
9. wikipedia

### CODE REVIEW

**Comment by Lord-Haji** [comment]
It makes sense to standardize but I don't see a point to make a PR this short. This doesn't fix anything the only thing causing issues was spaces in the tool names

**Comment by jatinchawda1503** [comment]
@Lord-Haji, Thanks for review. So do I revert the changes?
I have validated the names, but I don't see any tool names with space. 
Ideally, I thought standardizing it would make more sense to avoid future errors when someone is creating a tool while referring to this tool's code.

**Comment by baskaryan** [comment]
I believe duckduckgo and google search tools have spaces and need to be fixed. but we can also include the current changes, most tools have snake_cased names and it'd be nice to be consistent about that.

**Comment by jatinchawda1503** [comment]
thanks @baskaryan, Sure I will fix that too.

**Review by baskaryan — APPROVED** [review]

**Comment by baskaryan** [comment]
thank you @jatinchawda1503!

**Pull request merged**
