### PR TITLE
Add Generation.text error log

### PR DESCRIPTION
**Pull request by dinggege1024**
you could trace this background
https://github.com/hwchase17/langchain/issues/3654

### CODE REVIEW

**Comment by dinggege1024** [comment]
@hwchase17  Please review this pull request and provide some suggestions, tks

**Comment by vowelparrot** [comment]
I'd prefer to either/both:
- Handle this upstream -> if the response of `_generation` isn't a string, then the typing is wrong and we should fix that in the LLM wrapper
- Handle this in the `Generation` model itself -> if the validation error message isn't helpful then we can do so there

**Comment by dinggege1024** [comment]
> I'd prefer to either/both:
> 
> * Handle this upstream -> if the response of `_generation` isn't a string, then the typing is wrong and we should fix that in the LLM wrapper
> * Handle this in the `Generation` model itself -> if the validation error message isn't helpful then we can do so there
> 
> Are there examples where this is occuring?

image
 I used LLM with our api, i goes wrong with response in above pic. Before debug, i can not understand what happen.


-- Handle this in the Generation model itself -> if the validation error message isn't helpful then we can do so there
Updated pr, Is the solution mentioned above? Tks

@vowelparrot

**Comment by hwchase17** [comment]
agree with @vowelparrot this probably isnt the best place to handle it

`I used LLM with our api, i goes wrong with response in above pic` theres probably some misconfiguration of your LLM wrapper going on, i would fix that

**Comment by dinggege1024** [comment]
> agree with @vowelparrot this probably isnt the best place to handle it
> 
> `I used LLM with our api, i goes wrong with response in above pic` theres probably some misconfiguration of your LLM wrapper going on, i would fix that

Thks for reply, if fixed up please show me the way~

**Comment by baskaryan** [comment]
stale, closing but let me know if you're still seeing issues!

**Pull request closed without merging**
