### PR TITLE
📖 refactored `conversational_retrieval`

### LINKED ISSUE #9133: DOC: `API Reference` `langchain.agents Functions ` table unreadable
### Issue with current documentation:

 `API Reference` `langchain.agents Functions` table unreadable:
image
The `name` column is soo long, which makes the `description` column unreadable.

It is because of this value:
`agents.agent_toolkits.conversational_retrieval.openai_functions.create_conversational_retrieval_agent`

### Idea or request for content:

Make the namespace [and name] of this function shorter.

### PR DESCRIPTION
**Pull request by leo-gan**
Fixed #9133 issue.

1. Refactored `conversational_retrieval` by removing unnecessary nesting.
Current nesting makes `API Reference` unreadable (see the `description` column that is 6-char width):
image
It makes the full function name (with namespace) soo long, which makes the `description` column unreadable.
The resulting namespace+name is still too long.

2. renamed function `create_conversational_retrieval_agent` -> `create_agent`. Old name kept for backward compatibility

NOTE: The problem of too-long namespaces is also addressed in #8398 Please, review #8398 !!!!!

@baskaryan, @hinthorn

### CODE REVIEW

**Comment by baskaryan** [comment]
are there some unintentional commits in here? seems to touch not just docs

**Comment by leo-gan** [comment]
> are there some unintentional commits in here? seems to touch not just docs

Sorry. The PR name is confusing. Changed it. 
This PR **changes** code for sure. The purpose of it is to decrease namespace nesting and hence make docs readable.

**Comment by leo-gan** [comment]
@baskaryan

**Comment by leo-gan** [comment]
@eyurtsev

**Comment by leo-gan** [comment]
@hwchase17 Could you, please, review it?
# testing this messaging. 95% probability that these messages are lost

**Pull request closed without merging**
