### PR TITLE
Fixed streaming support using callback handler for Google genai

### PR DESCRIPTION
**Pull request by hasansustcse13**
- **Description:** Fixed streaming support using callback handler for Google genai. Callback handler not working with the `ChatGoogleGenerativeAI` which has been fixed in this PR. 
  - **Issue:** langchain-ai/langchain-google#120 langchain-ai/langchain#15006

### CODE REVIEW

**Comment by hasansustcse13** [comment]
@efriis Could you please look into this PR? Our current project has a large dependency on it.

**Comment by efriis** [comment]
Hey @hasansustcse13 ! This isn't the interface to follow anymore. Instead, you should stream using `.stream()` instead!

Let me know if you have any other questions.

Erick

**Comment by hasansustcse13** [comment]
@efriis Streaming doesn't work if I don't use **LangChain Expression Language (LCEL)**. In our project, we have used streaming using a Callback handler(on_llm_new_token) and different kinds of built-in chains.  As Gemini is not implanted the same as OpenAI, it does not work with a callback handler (on_llm_new_token). To need to support streaming in Gemini along with other LLM we have to convert all the code to LCEL. I believe this will be faced by other users also. That's why I have made the Change in the PR. Is there any other way to support streaming without LCEL and with a minimal changes? 

```
from langchain.chains import LLMChain
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI

prompt_template = "Tell me details about the Company {name} with 4 bullet point?"


def gemini_stream():
    llm = ChatGoogleGenerativeAI(model="gemini-pro", google_api_key='AIzaSyliRCeTRontPQ')
    llm_chain = LLMChain(llm=llm, prompt=PromptTemplate.from_template(prompt_template), verbose=True)
    for content in llm_chain.stream({'name': "Google"}):
        print(content)


def gemini_stream_with_lang_expression():
    llm = ChatGoogleGenerativeAI(model="gemini-pro", google_api_key='AIzaSyCuQ')
    prompt = PromptTemplate.from_template(prompt_template)
    chain = prompt | llm | StrOutputParser()
    for content in chain.stream({'name': "Google"}):
        print(content)


if __name__ == '__main__':
    # This is not working though I have use .stream() method. It gives the output after finising the completetion completely.
    gemini_stream()

    # This is working
    # gemini_stream_with_lang_expression()

```

**Comment by andrei-rusu** [comment]
I've also bumped into this problem, and I don't understand why this PR was closed. I was trying to set up a streaming agent as in [this example](https://github.com/langchain-ai/streamlit-agent/blob/main/streamlit_agent/basic_streaming.py) with Gemini, but ``on_llm_new_token`` indeed does not fire... I thought using a callback handler was the way to achieve per-token streaming for displaying (instead of per-chunk).

If there is another way to achieve this now, I would like to know (And probably the streamlit agent examples need to be rewritten accordingly).

**Comment by pseudotensor** [comment]
@efriis I also agree with @hasansustcse13 that you are probably confused.  One does not just invoke llm.stream() directly, but it pass an llm with callback into something like load_qa_chain, then streaming is broken for gemini but not other models.

**Comment by atuncer** [comment]
Is there a version that I can import via pip

**Comment by rushikeshvizerto7** [comment]
how to use map reduce chain type with gemini models using chatgooglegenerativeai and also get streaming responses at the same time using custom callback handler where I want token level streaming by appending in a queue

**Comment by RushikeshKothawade07** [comment]
how to use map reduce chain type with gemini models using chatgooglegenerativeai and also get streaming responses at the same time using custom callback handler where I want token level streaming by appending in a queue

**Comment by efriis** [comment]
try `ChatGoogleGenerativeAI(...).bind(stream=True)`

**Pull request closed without merging**
