### PR TITLE
Add GenerativeAgent

### PR DESCRIPTION
**Pull request by BeautyyuYanli**
Relate to #2859

### CODE REVIEW

**Comment by vowelparrot** [comment]
Thanks for doing this!

**Comment by hidaris** [comment]
I would like to ask how long it takes for an interview on your machine, I need about 10s+ in a cpu environment

**Comment by BeautyyuYanli** [comment]
> I would like to ask how long it takes for an interview on your machine, I need about 10s+ in a cpu environment

~10s

**Comment by hidaris** [comment]
> > I would like to ask how long it takes for an interview on your machine, I need about 10s+ in a cpu environment
> 
> ~10s

I see that the demo of the original paper seems very fast, is there any possible room for optimization?

**Comment by BeautyyuYanli** [comment]
> 

We use 4~5 API calls for every conversation response. It may be redundent and need to be optimized.

**Pull request merged**
