### PR TITLE
support add_embeddings for elasticsearch

### PR DESCRIPTION
**Pull request by kennethchoe**
- **Description:** Provide a way to use different text for embedding.
      -  For example, if you are ingesting stack-overflow Q&As for RAG, you would want to embed the questions and return the answer(s) for the hits. With this change, the consumer of langchain can implement that easily.
      - I noticed the similar function is added on faiss.py with #1912 which was for performance reason, but I see the same function can be used to achieve what I thought. So instead of changing Document class to have embedding_content, I mimicked the implementation of faiss.py.
      - The test should provide some guidance on how to use it. It would be more intuitive if I just pass texts and embedding_texts as separate arguments, but I chose to use `zip`-ed object for the consistency with faiss.py implementation.
      - I plan to make similar pull request for OpenSearch.
  - **Issue:** N/A
  - **Dependencies:** None other than the existing ones.

### CODE REVIEW

**Comment by kennethchoe** [comment]
@baskaryan could you take a look at this one? I see Codespell failure was due to a method `aadd()` in utils.py, which I did not change, and it means async-add, so it is really not a spelling error and not sure how to resolve it.

This one is similar but more involving than #11050 due to refactoring that was needed. Please let me know.

**Comment by baskaryan** [comment]
cc @joemcelroy

**Review by joemcelroy — APPROVED** [review]
Thanks for your contribution! Ran integration tests and look good.

**Comment by baskaryan** [comment]
thank you @kennethchoe and @joemcelroy!

**Pull request merged**
