### PR TITLE
Azure DocumentIntelligenceLoader/Parser support update with latest SDK

### PR DESCRIPTION
**Pull request by zifeiq**
- **Description:**
 Add DocumentIntelligenceLoader & DocumentIntelligenceParser implementation using the latest Azure Document Intelligence SDK with markdown support.
The core logic resides in DocumentIntelligenceParser and DocumentIntelligenceLoader is a mere wrapper of the parser.
The parser will takes api_endpoint and api_key and creates DocumentIntelligenceClient for the user. 4 parsing modes are supported:
1. Markdown (default)
2. Single
3. Page 
4. Object

UT and notebook are also updated accordingly.

  - **Dependencies:** Azure Document Intelligence SDK: azure-ai-documentintelligence [azure-sdk-for-python/sdk/documentintelligence/azure-ai-documentintelligence at 7c42462ac662522a6fd21b17d2a20f4cd40d0356 · Azure/azure-sdk-for-python (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-python%2Ftree%2F7c42462ac662522a6fd21b17d2a20f4cd40d0356%2Fsdk%2Fdocumentintelligence%2Fazure-ai-documentintelligence&data=05%7C01%7CZifei.Qian%40microsoft.com%7C298225aa3e31468a863108dbf07374ff%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638368150928704292%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oE0Sl4HERnMKdbkV9KgBV46Z2xytcQAShdTWf7ZNl%2Bs%3D&reserved=0).

### CODE REVIEW

**Comment by ruoccofabrizio** [comment]
@baskaryan @efriis hey guys, can you help us getting this PR merged?

**Comment by zifeiq** [comment]
> @baskaryan @efriis hey guys, can you help us getting this PR merged?
Thanks @ruoccofabrizio !
Hi @baskaryan  @efriis, really appreciate if you could take some time to review this code change and let me know your feedback. :)

**Comment by luzhang06** [comment]
Hi @baskaryan AND @efriis, we are from Azure AI Document Intelligence team. With Azure AI Document Intelligence (especially the latest support to office and html files + output to markdown). We believe it will benefit a lot to people who are doing RAG. With this PR, they can now extract document content and structure from any scanned or digital pdf, image, office or html file, then output to markdown with Langchain document loader. It can be then easily integrated with MarkdownHeaderSplitter for semantic document chunking. 

Appreciate your time reviewing the PR!

**Review by hwchase17 — COMMENTED** [review]
the code itself looks good, but please don't update the langchain stubs! lets only update langchain-community, otherwise its going to cause compatability issues. notebooks should import from langchain-community

**Comment by zifeiq** [comment]
> the code itself looks good, but please don't update the langchain stubs! lets only update langchain-community, otherwise its going to cause compatability issues. notebooks should import from langchain-community

Hi, thanks for the review and comment!
But I noticed that previous implemented 3-rd party APIs still keep a wrapper class under langchain, so I followed the same pattern. So do you suggest that I remove the wrappers update? Also, will the wrappers of the old implementation be deprecated soon?

**Comment by hwchase17** [comment]
> > the code itself looks good, but please don't update the langchain stubs! lets only update langchain-community, otherwise its going to cause compatability issues. notebooks should import from langchain-community
> 
> Hi, thanks for the review and comment! But I noticed that previous implemented 3-rd party APIs still keep a wrapper class under langchain, so I followed the same pattern. Do you suggest that I remove the wrappers update? Also, will the wrappers of the old implementation be deprecated soon?

Yes, please remove the wrapper (so that there are no changes langchain). The old wrappers that are imported in LangChain will be removed in a future version. They are currently only there for backwards compatability

**Comment by zifeiq** [comment]
> > > the code itself looks good, but please don't update the langchain stubs! lets only update langchain-community, otherwise its going to cause compatability issues. notebooks should import from langchain-community
> > 
> > 
> > Hi, thanks for the review and comment! But I noticed that previous implemented 3-rd party APIs still keep a wrapper class under langchain, so I followed the same pattern. Do you suggest that I remove the wrappers update? Also, will the wrappers of the old implementation be deprecated soon?
> 
> Yes, please remove the wrapper (so that there are no changes langchain). The old wrappers that are imported in LangChain will be removed in a future version. They are currently only there for backwards compatability

Thanks for the confirmation! Just updated accordingly.

**Comment by luzhang06** [comment]
@hwchase17 changes have been made accordingly. Can you please help review and approve the workflow?

**Review by efriis — APPROVED** [review]

**Pull request merged**
