### PR TITLE
Improve vespa interface

### PR DESCRIPTION
**Pull request by dev2049**
Still WIP. If we like this I can clean up and land, and in subsequent PR add self query retriever support (we'll just need to write translator from our internal query lang to YQL)

Screenshot 2023-05-11 at 7 50 31 PM

### CODE REVIEW

**Comment by dev2049** [comment]
@filippo82 , @jobergum would love your thoughts

**Review by hwchase17 — APPROVED** [review]

**Comment by jobergum** [comment]
This is super cool, @dev2049. Thank you so much for your effort on this! This makes the Vespa retriever much more useful. 

For the cord19 API, where we extend Vespa with more functionality ([app](https://github.com/vespa-cloud/cord-19-search)),  there are several interesting queries you can use to demonstrate this functionality. 

[Sample query request ](https://api.cord19.vespa.ai/search/?query=environmental+impact+due+to+pandemic+travel+restrictions&ranking.profile=colbert&summary=short&restrict=doc&collapse.enable=true&collapse.similarity.threshold=0.85&hits=10)

- Prefer using summary=short as summary=default with "select *" also returns specter_embedding and colbert document embeddings
- Prefer using cord_uid as the id (from within fields)
- You can switch on and off the bolding of terms with `&bolding=false` which might be handy for piping the results into the pipelines. That would probably be an interesting demo to ask questions about covid, powered by retrieval of this API. 

There are also several ranking implementations. 
- `ranking=colbert` multi-vector ranking
- `ranking=hybrid-colbert` combination of bm25 and colbert maxsim
- `ranking=bm25` plain bm25

**Comment by filippo82** [comment]
Cool stuff @dev2049 💪🏻 

I have a few comments:

---

As suggested by @jobergum in #4008, we should also allow the user to insert [native Vespa embedders](https://docs.vespa.ai/en/embedding.html#embedding-a-query-text). This is an example:

```python
        {
            "yql": "select content from paragraph where userQuery() or {targetHits: 100}nearestNeighbor(embedding, first_query)",
            "query": "Where is Waldo?",
            "input.query(first_query)": "embed(bertModel, Where is Waldo?)",  # <-- This guy here
            "type": "weakAnd",
            "hits": 5,
            "ranking": "documentation",
            "locale": "en-us"
        }
```

One could extend the `from_params` factory with a `native_embedders` `dict` argument:

```python
native_embedders = {
    "first_query": "bertModelOne",
    "second_query": "bertModelTwo",
}

for input_query, embedder in native_embedders.items():
   body[f"input.query({input_query})"] = f"embed({embedder}, {query})"
``` 

---

I think that having both `metadata_fields` and `_filter` might be redundant. Let me try to explain why.
Currently, providing a field inside `metadata_fields` is useful only if then that field is referenced inside `_filter`. I think they could be merged into a `metadata_filters` dictionary which looks like this:

```python
metadata_filters = {
    "title": "contains Japan",
    "year": "> 2023",
}
```

The `metadata_filters` should not be part of the `from_params` factory method but should only be passed to the `get_relevant_documents_with_filter` method.

---

I emphasise that these above are mainly high-level thoughts and I might be wrong 🙏🏻

**Comment by dev2049** [comment]
> ...
> The `metadata_filters` should not be part of the `from_params` factory method but should only be passed to the `get_relevant_documents_with_filter` method.
> 
> I emphasise that these above are mainly high-level thoughts and I might be wrong 🙏🏻

re embedders - from_params pipes arbitrary kwargs into the query body, so you should already be able to add whatever else you want there

re metadata_fields - the main point of this param is to determine what fields are returned in the retrieved documents. not clear to me that this is something people would want to update every time they call get_relevant_documents_with_filter, and would prefer to keep main interfaces minimal (in terms of number of params) when possible

**Comment by dev2049** [comment]
> > ...
> > The `metadata_filters` should not be part of the `from_params` factory method but should only be passed to the `get_relevant_documents_with_filter` method.
> > I emphasise that these above are mainly high-level thoughts and I might be wrong 🙏🏻
> 
> re embedders - ~from_params pipes arbitrary kwargs into the query body, so you should already be able to add whatever else you want there~ ah take it you meant you should be able to pass these in to get_relevant_documents_with_filter
> 
> re metadata_fields - the main point of this param is to determine what fields are returned in the retrieved documents. not clear to me that this is something people would want to update every time they call get_relevant_documents_with_filter, and would prefer to keep main interfaces minimal (in terms of number of params) when possible

will land as-is but am happy to add more functionality in future pr's

**Pull request merged**
