### PR TITLE
remove Value error "pyspark is not installed. Please install it with `pip i…

### PR DESCRIPTION
**Pull request by Jurik-001**
Description: You cannot execute spark_sql with versions prior to 3.4 due to the introduction of pyspark.errors in version 3.4.
And if you are below you get 3.4 "pyspark is not installed. Please install it with pip nstall pyspark" which is not helpful. Also if you not have pyspark installed you get already the error in init. I would return all errors. But if you have a different idea feel free to comment.

Issue: None
Dependencies: None
Maintainer:

### CODE REVIEW

**Comment by baskaryan** [comment]
cc @gengliangwang

**Review by gengliangwang — APPROVED** [review]
+1, makes sense

**Comment by baskaryan** [comment]
thanks @Jurik-001!

**Comment by Jurik-001** [comment]
Hey @baskaryan, i did not found any personal contact point, so I try it with this comment. 
I am new to LangChain and ask myself why spark_sql is build as a tool and not as chain, like for example llm_math?

**Pull request merged**
