### PR TITLE
Bagatur/nuclia

### PR DESCRIPTION
**Pull request by baskaryan**

### CODE REVIEW

**Comment by baskaryan** [comment]
@ebrehault looks like nuclia working with protobuf>3.19 but seems that isn't enforced by the package requirements?

**Comment by ebrehault** [comment]
@baskaryan right, we need protobuf 4.23, but where should I enforce that to not break other people integration based on protobuf 3?

**Comment by baskaryan** [comment]
> @baskaryan right, we need protobuf 4.23, but where should I enforce that to not break other people integration based on protobuf 3?

we definitely shouldn't enforce in langchain, but nucliadb-protos probably should? so that when in CI it's installed it'd force protobuf to be updated. either way can just move the tests to integration tests for now

**Comment by ebrehault** [comment]
Thank you @baskaryan (sorry for the late answer, I was on vacation).
I will fix the `nucliadb-protos` deps.

**Pull request merged**
