### PR TITLE
infra: Consistent lxml requirements

### LINKED ISSUE #19040: Inconsistent lxml dependency between `langchain` and `langchain-text-splitters`
### Checked other resources

- [x] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
conda install langchain=0.1.12 zeep=4.2.1
```

### Error Message and Stack Trace (if applicable)

```
Could not solve for environment specs
The following packages are incompatible
├─ langchain 0.1.12**  is installable and it requires
│  ├─ langchain-text-splitters >=0.0.1,<0.1 , which requires
│  │  └─ lxml >=5.1.0,<6.0.0 , which can be installed;
│  └─ lxml >=4.9.2,<5.0.0 , which can be installed;
└─ zeep 4.2.1**  is not installable because it requires
   └─ lxml >=4.6.0 , which conflicts with any installable versions previously reported.
```

### Description

I'm trying to install latest langchain along with some other packages depending on lxml. It appears that `langchain` requires `lxml >=4.9.2,<5.0.0` but `langchain-text-splitters` requires `lxml >=5.1.0,<6.0.0` which are incompatible. Since the former depends on the latter, it makes dependency resolution fail.

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.19045
> Python Version:  3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:27:34) [MSC v.1937 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.1.31
> langchain: 0.1.12
> langchain_community: 0.0.28
> langsmith: 0.1.24
> langchain_text_splitters: 0.0.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

### PR DESCRIPTION
**Pull request by Randl**
Update the dependency for lxml to be consistent among different packages; should fix https://github.com/langchain-ai/langchain/issues/19040

### CODE REVIEW

**Comment by tjaffri** [comment]
https://github.com/docugami/dgml-utils/pull/24 is merged and published as dgml-utils 0.3.3. Let me know if we can help resolve downstream issues. FYI @kenzie28.

**Comment by eyurtsev** [comment]
why are there so many changes across other lock files?

**Comment by eyurtsev** [comment]
Another question is whether we need to be pinning to a particular lxml major version. Would we be able to expand the range of major versions we're supporting to users don't get stuck unable to use langchain or some other package because of lxml version mismatch (lxml is a popular package)

**Comment by Randl** [comment]
@eyurtsev I agree, we can settle for >4.9,<6

**Pull request merged**
