### PR TITLE
[Core]: On Tool End Obersvation Casting Fix

### PR DESCRIPTION
**Pull request by keenborder786**
Fixes the following issue #18760 raised by @eyurtsev

### CODE REVIEW

**Review by eyurtsev — COMMENTED** [review]
This might break a bunch of user code -- I'm going to scope out how to do this without introducing breaking changes

**Comment by keenborder786** [comment]
okay, please let me know about the scope so I can integrate that within this PR. Thank you. @eyurtsev

**Comment by eyurtsev** [comment]
Keep PR open for now in case we decide to make a breaking here

**Comment by eyurtsev** [comment]
OK I think we can actually do this! It's a breaking change, but not one that I think will affect many users, and likely better to do this than to implement a work-around.

The remaining changes we need to make:

1. `git grep on_tool_end` across the code base to find all tracer/callback handlers
2. update the type signature from `str` to `Any`
3. Add a cast to string inside the handler itself

```python
    def on_tool_end(self, output: str, *, run_id: UUID, **kwargs: Any) -> Run:
        """End a trace for a tool run."""
``

--

We can then follow up with another PR to actually fix astream_events:

1. Add a unit test that includes the snippet of code I posted in the original issue -- goes here: https://github.com/langchain-ai/langchain/blob/bc6249c889a4fe208f8f145e80258eb3de20d2d4/libs/core/tests/unit_tests/runnables/test_runnable_events.py#L48-L48
2. Remove the cast to str in BaseTracer on_tool_end (that this PR will introduce) https://github.com/langchain-ai/langchain/blob/bc6249c889a4fe208f8f145e80258eb3de20d2d4/libs/core/langchain_core/tracers/base.py#L507-L507
3. Celebrate!

**Comment by eyurtsev** [comment]
Yeah we should get both sync and async methods good catch @adreo00

**Comment by eyurtsev** [comment]
@keenborder786 let me know if you're OK taking this on or want me to commandeer! Would be nice to merge a fix next week :)

**Comment by keenborder786** [comment]
Ok. Yes I am taking this.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by keenborder786** [comment]
@eyurtsev please review.

**Comment by keenborder786** [comment]
I will create the second PR for test that you have mentioned.

**Comment by eyurtsev** [comment]
Looks good! On mobile right now, so won't merge until at my laptop later tonight.

**Comment by eyurtsev** [comment]
Had no time over the weekend, taking a look now

**Pull request merged**
