### PR TITLE
community: Finally add llama-cpp async support

### PR DESCRIPTION
**Pull request by dimaioksha**
Thank you for contributing to LangChain!

- [x] **community**: "add LlamaCpp async support"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- **Description:** Add llama-async support
- **Issue:** [the issue](https://github.com/langchain-ai/langchain/issues/9865) # it fixes, if applicable 
- **Dependencies:** I was suprised when I saw that changes from these PR are not still merged. This PR applies changes from https://github.com/langchain-ai/langchain/pull/9177 and https://github.com/langchain-ai/langchain/pull/10908 since they are not active
- **Twitter handle:** if your PR gets announced, and you'd like a mention, we'll gladly shout you out!

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, hwchase17.

### CODE REVIEW

**Comment by DmitryIo** [comment]
@baskaryan
Hello, can you make a review?

**Review by baskaryan — COMMENTED** [review]
how is this different from the default LLM implementations of acall and astream?

**Comment by dimaioksha** [comment]
> how is this different from the default LLM implementations of acall and astream?

`acall` and `astream` use under the hood `_astream` and `_acall` methods

As stated here https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/language_models/llms.py#L1220 `_acall` method should be overriden to reduce the overhead of using `run_in_executor`

Also the it is true for _astream as it uses llamacpp client streaming under the hood https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/language_models/llms.py#L581

And we it saves log_probs when generating each chunk

**Comment by baskaryan** [comment]
> > how is this different from the default LLM implementations of acall and astream?
> 
> `acall` and `astream` use under the hood `_astream` and `_acall` methods
> 
> As stated here https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/language_models/llms.py#L1220 `_acall` method should be overriden to reduce the overhead of using `run_in_executor`
> 
> Also it is true for `_astream` as it uses `llama-cpp-python` client streaming under the hood https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/language_models/llms.py#L581
> 
> And we it saves log_probs when generating each chunk

aren't we still just running sync functions in executors in all these implementations?

**Comment by dimaioksha** [comment]
> > > how is this different from the default LLM implementations of acall and astream?
> > 
> > 
> > `acall` and `astream` use under the hood `_astream` and `_acall` methods
> > As stated here https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/language_models/llms.py#L1220 `_acall` method should be overriden to reduce the overhead of using `run_in_executor`
> > Also it is true for `_astream` as it uses `llama-cpp-python` client streaming under the hood https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/language_models/llms.py#L581
> > And we it saves log_probs when generating each chunk
> 
> aren't we still just running sync functions in executors in all these implementations?

Unfortunately `llama-cpp-python` does not provide async interfaces. It uses threads, and I thouhght that async somehow processes inside llama.cpp (vendor), but now I think I missunderstand it. 
Here is an example how they handle async in open-ai compatible server: https://github.com/abetlen/llama-cpp-python/blob/main/llama_cpp/server/app.py#L293

Should I rewrite current implementation to use `await starlette.concurrency.run_in_threadpool`?
Starlette is a dependence inside `community` package: https://github.com/langchain-ai/langchain/blob/master/libs/community/poetry.lock#1847

**Comment by dimaioksha** [comment]
tested with async langchain callback + tested with fastapi async backend, works good — returns `StreamingReponse` and I can show it appearing chunk by chunk (also works with multiple requests)

**Pull request closed without merging**
