### PR TITLE
fix: missing parameter in POST/PUT/PATCH HTTP requests

### PR DESCRIPTION
**Pull request by nirga**
@hinthornw

### CODE REVIEW

**Comment by hwchase17** [comment]
@nirga i updated - does this still work?

**Comment by nirga** [comment]
Yes @hwchase17 it works. BTW while we're at it, I'd suggest adding `res.status_code` in `TextRequestsWrapper` since specifically for PUT/POST/PATCH request sometime the body is empty which confuses the `Requests*ToolWithParsing` LLM. But I can do that in a separate PR.

**Comment by hwchase17** [comment]
> Yes @hwchase17 it works. BTW while we're at it, I'd suggest adding `res.status_code` in the responses of `TextRequestsWrapper` since specifically for PUT/POST/PATCH request sometime the body is empty which confuses the `Requests*ToolWithParsing` LLM. But I can do that in a separate PR.

@nirga if that information is needed, the normal requests wrapper can just be used

**Comment by nirga** [comment]
> > Yes @hwchase17 it works. BTW while we're at it, I'd suggest adding `res.status_code` in the responses of `TextRequestsWrapper` since specifically for PUT/POST/PATCH request sometime the body is empty which confuses the `Requests*ToolWithParsing` LLM. But I can do that in a separate PR.
> 
> @nirga if that information is needed, the normal requests wrapper can just be used

Yeah I know, I think it should be in the `TextRequestsWrapper` as well since it's used by agents who need this info. NVM, I'll open an issue for that and we can discuss there.

**Pull request merged**
