### PR TITLE
Add possibility to use the additional_kwargs field in basemessages

### PR DESCRIPTION
**Pull request by eavanvalkenburg**
# Add possibility to use the additional_kwargs field in basemessages

This add the option to override the save_context method of the BaseChatMessageHistory in a particular memory to add additional info in the kwargs field of the BaseMessage class, implemented for each chat_message_history. 

Ideally this get's extended to have the chain actually fill that in, potentially with callbacks, so that for instance you can store the no. of tokens and costs for each message (or just the outputs) or something.

@hwchase17 probably something for you to have a look at!

### CODE REVIEW

**Comment by amitmukh** [comment]
This is one of the key ask from customer to give the flexibility to add additional information as part of memory to get saved in Cosmos or other external data store.

**Comment by hwchase17** [comment]
throwing out some other options/ideas:

should we expose an interface `append_message` that appends an arbitrary message? that way users can construct the `Message` object outside and pass it in. would also just treat the current methods as helper functions for when you want to store only a string... but if you want to store other things, you can just construct a Message outside (arbitrarily so) and do that. would be even more flexible and forward proof, at the cost of a little more writing for users in the short term

**Comment by eavanvalkenburg** [comment]
@hwchase17 I think we can make the case for both, one to add direct context to a specific message (this one) and one for adding additional "non AI nor Human nor System" messages to a storage, both have value, but I do see them as slightly different cases. One difference for instance could be that these kwargs are ignored when putting history in a prompt but the other message type is included to provide additional context to the conversation, for instance adding a plan (from plan and execute flows) to storage so that one can retrieve and continue that (just spitballing).

**Comment by hwchase17** [comment]
even if they wanted to add direct context to a specific message though, they could still use a generic `append_messages` method though right? They'd just construct it outside

**Comment by eavanvalkenburg** [comment]
Ah ok, I see the logic now, what I then don't have clear yet is what the lowest custom code solution is to do this and if we can easily create this for something common like adding the costs to the kwargs, but I guess that's true in either approach.

**Pull request closed without merging**
