### PR TITLE
core: fix: remove comments in json strings.

### PR DESCRIPTION
**Pull request by lichengwu**
Description: This change removes single line // and multi-line /* */ comments from JSON strings using a regex substitution. The purpose of this update is to ensure that JSON content can be parsed correctly without being affected by the presence of comments, which are not supported in standard JSON format. The regex substitution is performed using the re.sub method with the pattern r'//.*?\n|/\*.*?\*/' and the flags=re.S to ensure proper handling of newline characters within the comments.

### CODE REVIEW

**Comment by lichengwu** [comment]
@hwchase17

**Comment by baskaryan** [comment]
thanks @lichengwu! could we add another test case for having // inside a string

**Comment by lichengwu** [comment]
> thanks @lichengwu! could we add another test case for having // inside a string

When I was using the agent function, I noticed that some models generate context that includes JSON comments. Therefore, I expanded the testing scope based on the existing method. Are you suggesting that I should write a new pytest testing method?  @baskaryan

**Comment by lichengwu** [comment]
What else needs to be done to merge this request?

**Comment by lichengwu** [comment]
@baskaryan  @hwchase17  Can this code be merged？

**Comment by baskaryan** [comment]
@lichengwu seems to be failing tests

**Pull request closed without merging**
