### PR TITLE
RFC: Let each LM define it's own fastest/cheapest/test versions

### PR DESCRIPTION
**Pull request by dev2049**
E.g. i didn't know that Anthropic claude-v1 is best, claude-instant-v1 is fastest/cheapest, test allows for testing without api key. As user would be great if i didn't have to memorize and stay up to date with all these random strings for each provider

### CODE REVIEW

**Comment by nfcampos** [comment]
Why wouldn't the test model always be the cheapest model?

**Comment by agola11** [comment]
@nfcampos that's not always the case. For example, Anthropic has a "test" model meant to be used specifically for integration testing and is available to all users (so everyone can run the int tests). It's not meant to be used outside testing.

**Comment by nfcampos** [comment]
Very true, good point. But eg Cohere instead of a test model has a test api key, feels hard to make this generic enough for all integrations?

**Comment by dev2049** [comment]
> Very true, good point. But eg Cohere instead of a test model has a test api key, feels hard to make this generic enough for all integrations?

im assuming each LLM class would implement and maintain these themselves

**Comment by leo-gan** [comment]
> 

Good point. I also thought about it. 
We can add some parameter to the model (and any other integration classes) as `Tags`: Optional[List[Enum)]  With the Enum values like: `Free`, `Cheapest`, `Fastest`, `2023-02` (as the publishing date), etc. Then we use it for different tasks. 
BTW: `Cheapest`, `Fastest` terms. They work in the context that there are other `Not so cheap` etc. This context is not global, so those comparable terms are questionable.

**Pull request closed without merging**
