### PR TITLE
fix: Problem with embeddings in new versions of clickhouse.

### PR DESCRIPTION
**Pull request by MarceloNunesAlves**
Starting with Clickhouse version 24.8, a different type of configuration has been introduced in the vectorized data ingestion, and if this configuration occurs, an error occurs when generating the table. As can be seen below:

Screenshot from 2024-09-04 11-48-00

### CODE REVIEW

**Comment by MarceloNunesAlves** [comment]
Hey @eyurtsev!

Could you review the code please?

**Comment by efriis** [comment]
Howdy! Marking as needs support per our review policy. If someone from clickhouse lets us know this is correct happy to accelerate it through - @mneedham maybe?

**Comment by mneedham** [comment]
This change looks good to me.

**Comment by MarceloNunesAlves** [comment]
@efriis, do you think you need someone else to review?

Thank you so much!

**Comment by MarceloNunesAlves** [comment]
@efriis,

When running the pipeline, an error occurred that did not occur on my local machine because the configuration is different, sorry.

image

**Comment by MarceloNunesAlves** [comment]
@efriis, could you review my code, please? I need this fix to use clickhouse latest.

Thank you so much

**Comment by MarceloNunesAlves** [comment]
@ccurme, could you review my code, please?

**Review by efriis — APPROVED** [review]

**Pull request merged**
