### PR TITLE
community: Add support for filtering + metadata retrieval for Azure CosmosDB NoSQL vector store

### PR DESCRIPTION
**Pull request by loiccordone**
- **Description:** First draft of a PR to add filtering to the new Azure CosmosDB NoSQL vector store
  - **Issue:** #23089 
  - **Dependencies:** None

Sorry, I'm not familiar with contributing to Langchain, I'm fully aware this is not of sufficient quality to be merged.
But I hope it'll start an initiative!

- [ ] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.
Not done yet sorry

- [ ] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Could you take a look @aayush3011 please? Thank you very much!

### CODE REVIEW

**Comment by baskaryan** [comment]
apologies for the slow review, seems the pr has accumulated some non-trivial merge conflicts :/

**Comment by leonardobaggio** [comment]
+1 filtering is a essential tool for vector store, also a great way to implement security measures during retrieval

**Comment by lucamartinsm** [comment]
> +1 filtering is a essential tool for vector store, also a great way to implement security measures during retrieval @ccurme @efriis

Agreed. This would be very useful. Upvoting!

**Comment by efriis** [comment]
hey team I'll close this for now and feel free to reopen after addressing merge conflicts as bagatur commented back in september. thanks!

**Pull request closed without merging**
