### PR TITLE
community: Feature/oxylabs components

### PR DESCRIPTION
**Pull request by Ulumanshu**
Package: Oxylabs Search Wrapper API

- **Description:** This merge request introduces the implementation of the OxylabsSearchWrapperAPI
along with the OxylabsSearchRun and OxylabsSearchResults tools within the LangChain package.
These additions provide seamless integration with the Oxylabs API, enabling enhanced search capabilities.
- **Issue:** N/A
- **Dependencies:** To use this functionality, please ensure the Oxylabs SDK is installed:
```bash
pip install oxylabs
```

### CODE REVIEW

**Comment by Ulumanshu** [comment]
@baskaryan
Hello, could you please review the PR when you have a moment?

**Comment by Ulumanshu** [comment]
@ccurme can you please take a look?

**Comment by efriis** [comment]
hey! would you be open to publishing your own package following [this guide](https://python.langchain.com/docs/contributing/how_to/integrations/) and just contributing docs?

**Comment by Ulumanshu** [comment]
> hey! would you be open to publishing your own package following [this guide](https://python.langchain.com/docs/contributing/how_to/integrations/) and just contributing docs?

Hi, thank you for your response. I am awaiting a decision from all the concerned parties and will get back to you as soon as I receive an answer. (reading the docs while waiting)

**Comment by Ulumanshu** [comment]
> > hey! would you be open to publishing your own package following [this guide](https://python.langchain.com/docs/contributing/how_to/integrations/) and just contributing docs?
> 
I am writing to follow up on your suggestion. We understand the proposal to publish this as a standalone package. However, the functionality aligns closely with LangChain's core objectives and could be highly beneficial to the broader community. We would prefer the Oxylabs integration to be included as part of the langchain community modules, with a commitment from our side to maintain it.

**Comment by Ulumanshu** [comment]
@efriis Hi,
I’m following up on our PR to the langchain-community submitted on November 7. We’d like to check on its status and see if there’s anything we can do to assist the process.

**Comment by Ulumanshu** [comment]
Hi @baskaryan, @efriis, @eyurtsev, @ccurme, @vbarda, @hwchase17,

I'm following up on the PR submitted to the LangChain community on November 7 regarding the Oxylabs components. We are eager to understand the status of the review and see if there's anything further we can do to assist the process. If there are any further steps we can take, please let us know.

Looking forward to your feedback. Thank you for your time!

Best regards,
Ulumanshu

**Comment by efriis** [comment]
hey there! sorry for the delay. 

This adds a net-new community integration or feature, which has been replaced by dedicated integration packages. I'll close this PR, and would recommend reopening with just docs updates, as well as registering your package in `libs/packages.yml`! We'll be able to review simple PRs that only modify these two things much faster :)

Here's that guide linked again (it's been improved since I originally sent it), and if you have questions, feel free to leave them in the comments on those pages so others can see them! https://python.langchain.com/docs/contributing/how_to/integrations/

To be clear, you would open a new PR with the exact same documentation added as this PR, so your integration will be just as discoverable (potentially more discoverable long-term) than a community integration!

**Pull request closed without merging**
