### PR TITLE
lancedb template code

### PR DESCRIPTION
**Pull request by akashAD98**
as per contribution guidance verified all code format & submitting pr

### CODE REVIEW

**Comment by efriis** [comment]
get `TypeError: Type is not JSON serializable: numpy.ndarray` when running it with question "where did harrison work"

**Comment by efriis** [comment]
This is likely an issue in the LanceDB integration, not this template. It looks like it's attaching numpy arrays as metadata to the documents, thereby making them not serializable. Would recommend passing the vectors around as List[float] instead of numpy.ndarray!

But also, including the embeddings in the metadata of documents is generally unnecessary. Maybe only pass it back to the user if they request it with some parameter?

**Comment by akashAD98** [comment]
Okay got it let me work on it

**Comment by efriis** [comment]
Will close for now, and feel free to open a PR against the integration package, and then reopen this once that's in + published to community!

**Pull request closed without merging**
