### PR TITLE
docs: edit links, direct for notebooks

### PR DESCRIPTION
**Pull request by efriis**

### CODE REVIEW

**Comment by eyurtsev** [comment]
awesome!!

**Review by eyurtsev — APPROVED** [review]
Looks fantastic thank you!!

**Comment by baskaryan** [comment]
dunno why but title is messed up here and not in master https://langchain-git-erick-docs-edit-links-direct-for-4ab7b8-langchain.vercel.app/v0.2/docs/how_to/streaming/

**Comment by efriis** [comment]
Great catch - was a regex error

**Pull request merged**
