### PR TITLE
community:Adding Konko Completion endpoint 

### PR DESCRIPTION
**Pull request by shivanimodi16**
This PR introduces update to Konko Integration with LangChain.

1. **New Endpoint Addition**: Integration of a new endpoint to utilize completion models hosted on Konko. 

2. **Chat Model Updates for Backward Compatibility**: We have updated the chat models to ensure backward compatibility with previous OpenAI versions. 

4. **Updated Documentation**: Comprehensive documentation has been updated to reflect these new changes, providing clear guidance on utilizing the new features and ensuring seamless integration.

Thank you to the LangChain team for their exceptional work and for considering this PR. Please let me know if any additional information is needed.

### CODE REVIEW

**Comment by shivanimodi16** [comment]
@baskaryan just wanted to follow up on this pull request.

**Comment by shivanimodi16** [comment]
Hi @hwchase17,  following up on the above. It would be great to have this merged soon as we are planning to have a launch for our new endpoint next week. Thank you for looking into it!

**Review by baskaryan — COMMENTED** [review]
no need to update libs/langchain, could we remove those changes

**Comment by shivanimodi16** [comment]
Hi @baskaryan,
Thanks for checking it out.  Quick question - we've incorporated new models categorized under 'llm', unlike our previous setup. I've introduced 'konko.py' into the 'llm' category. For this integration to function properly, shouldn't we include this new addition in the 'init' file within 'libs/langchain'?

**Comment by shivanimodi16** [comment]
@baskaryan, waiting for your response. Our product has gone live, and applications integrating Langchain are experiencing issues. Your attention to finalizing this pull request would be greatly valued, particularly in addressing any existing problems.

**Comment by shivanimodi16** [comment]
@baskaryan just bring it up on your threads

**Comment by shivanimodi16** [comment]
@eyurtsev I noticed you've been reviewing other integration PRs and was wondering if you could take a look at this one too. Would really appreciate it!

**Comment by baskaryan** [comment]
> Hi @baskaryan, Thanks for checking it out. Quick question - we've incorporated new models categorized under 'llm', unlike our previous setup. I've introduced 'konko.py' into the 'llm' category. For this integration to function properly, shouldn't we include this new addition in the 'init' file within 'libs/langchain'?

sorry for delay! all new integrations live in `libs/community` and only need to be added to `__init__` files there. the `libs/langchain` init files only contain old imports for backwards compatibility, which will be removed in the next minor version release of `langchain`

**Comment by shivanimodi16** [comment]
> > Hi @baskaryan, Thanks for checking it out. Quick question - we've incorporated new models categorized under 'llm', unlike our previous setup. I've introduced 'konko.py' into the 'llm' category. For this integration to function properly, shouldn't we include this new addition in the 'init' file within 'libs/langchain'?
> 
> sorry for delay! all new integrations live in `libs/community` and only need to be added to `__init__` files there. the `libs/langchain` init files only contain old imports for backwards compatibility, which will be removed in the next minor version release of `langchain`

@baskaryan That makes sense! Thank you for clarifying that :)
I have reverted those changes. Let me know if some other changes are required or we are good to merge this PR.

**Review by baskaryan — APPROVED** [review]
lgtm, thank you @shivanimodi16!

**Comment by shivanimodi16** [comment]
Thanks for the quick review, @baskaryan! It would be great if we could merge this PR soon :)

**Pull request merged**
