### PR TITLE
Allow use of non-default QDrant vector key

### PR DESCRIPTION
**Pull request by mahmoudajawad**
Context https://github.com/hwchase17/langchain/issues/2594

### CODE REVIEW

**Review by kacperlukawski — CHANGES_REQUESTED** [review]
It should generally work, but the same vector name should also be used when creating the collection. Currently, if we provide a `vector_key` and the collection does not exist, it won't be created properly.

**Comment by mahmoudajawad** [comment]
@kacperlukawski, agree. Will introduce more changes to retain current good behaviour of the class.

**Comment by kacperlukawski** [comment]
@mahmoudajawad Do you still need that feature? I can continue on that topic.

**Comment by mahmoudajawad** [comment]
I just drifted away in time lines and left this behind. Let me get back to it within two days and complete it. Thanks, @kacperlukawski.

**Pull request closed without merging**
