### PR TITLE
📖 docs: fixed `integrations/document loaders` toc

### PR DESCRIPTION
**Pull request by leo-gan**
Fixed navbar:
- renamed several files, so ToC is sorted correctly
- made ToC items consistent: formatted several Titles
- added several links
- reformatted several docs to a consistent format
- renamed several files (removed `_example` suffix)
- added renamed files to the `docs/docs_skeleton/vercel.json`

### CODE REVIEW

**Comment by leo-gan** [comment]
@baskaryan

**Comment by leo-gan** [comment]
@baskaryan I fixed paths in vercel.json The same as the previous PR.

**Comment by leo-gan** [comment]
@baskaryan

**Comment by leo-gan** [comment]
@eyurtsev

**Comment by leo-gan** [comment]
@baskaryan Please review.

**Comment by leo-gan** [comment]
@baskaryan Could you, please, review it?

**Comment by leo-gan** [comment]
@baskaryan Could you, please, review it?

**Comment by leo-gan** [comment]
@hwchase17  Could you, please, review it?

**Review by hwchase17 — APPROVED** [review]

**Pull request merged**
