### PR TITLE
community: Add missing async similarity_distance_threshold handling in RedisVectorStoreRetriever

### PR DESCRIPTION
**Pull request by HugoMichard**
Add missing async similarity_distance_threshold handling in RedisVectorStoreRetriever

  - **Description:** added method `_aget_relevant_documents` to  `RedisVectorStoreRetriever` that overrides parent method to add support of `similarity_distance_threshold` in async mode (as for sync mode)
  - **Issue:** #16099
  - **Dependencies:** N/A
  - **Twitter handle:** N/A

### CODE REVIEW

**Review by baskaryan — APPROVED** [review]
lgtm, cc @Spartee @tylerhutcherson

**Comment by HugoMichard** [comment]
fixed linting error in [985a75d](https://github.com/langchain-ai/langchain/commit/985a75d495bed3826b35062c9fdee897580c01cc)

**Comment by HugoMichard** [comment]
@baskaryan @Spartee @tylerhutcherson 
Hi, do you have any news regarding this PR ? 

It would allow me to simplify my code greatly when using LangChain in my custom async APIs

**Review by baskaryan — APPROVED** [review]

**Comment by baskaryan** [comment]
sorry for delay, thank you @HugoMichard!

**Comment by tylerhutcherson** [comment]
Apologies for the delay, glad this made it in!

**Pull request merged**
