### PR TITLE
[Community]Enable retrieval api calls in PebbloRetrievalQA

### PR DESCRIPTION
**Pull request by rahul-trip**
Description: Enable app discovery and Prompt/Response apis in PebbloSafeRetrieval
Documentation: NA
Unit test: N/A

### CODE REVIEW

**Comment by rahul-trip** [comment]
Hi @baskaryan 
Kindly review/merge.

**Comment by rahul-trip** [comment]
Hi @eyurtsev ,
Kindly review this PR.

**Comment by eyurtsev** [comment]
I'm on vacation until next week will review once back

**Comment by rahul-trip** [comment]
Hi @efriis / @ccurme

Kindly review/merge this PR.

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
