### PR TITLE
Bug Fix - #8415

### PR DESCRIPTION
**Pull request by pranaychandekar**
- Issue: #8415

### CODE REVIEW

**Comment by pranaychandekar** [comment]
@baskaryan Please merge this

**Comment by baskaryan** [comment]
are we sure we want to create the cache during lookup? shouldn't it be created before

**Comment by pranaychandekar** [comment]
@baskaryan The current flow of llm predict or langchain execution is like this:
1. cache lookup if the cache is not None
2. predict if not present in cache
3. if step 2, then create cache object and update cache

with this PR I have just shifted the cache creation to step 1. So if the cache is None, then it will be created and a lookup will be performed. This way cache won't be created at step 3 and we won't miss checking cache for the first llm predict call.

You are right about creating it at startup. But that way we will have to analyze all the other cache implementations and make changes to base cache for cache intialization. As of now, the cache initializations are happening within the respective implementations. 

This PR change would atleast fix the bug for GPTCache.

**Comment by baskaryan** [comment]
makes sense, thanks @pranaychandekar!

**Pull request merged**
