### PR TITLE
📖 docs: compact api reference

### PR DESCRIPTION
**Pull request by leo-gan**
Updated design of the "API Reference" text
Here is an example of the current format:
image

It changed to
`langchain.retrievers.ElasticSearchBM25Retriever` format. The same format as it is in the API Reference Toc.

It also resembles code: 
`from langchain.retrievers import ElasticSearchBM25Retriever` (namespace THEN class_name)

Current format is
`ElasticSearchBM25Retriever from langchain.retrievers` (class_name THEN namespace) 

This change is in line with other formats and improves readability.

 @baskaryan

### CODE REVIEW

**Comment by baskaryan** [comment]
maybe we should just make it actually like code `from langchain.retrievers import ElasticSearchBM25Retriever`? or just the class name, since code block already shows where it's imported from? cc @hinthornw

**Comment by leo-gan** [comment]
> maybe we should just make it actually like code `from langchain.retrievers import ElasticSearchBM25Retriever`? or just the class name, since code block already shows where it's imported from? cc @hinthornw

Here we have a link to the `ElasticSearchBM25Retriever` class in API Reference. That is the real value of it.
Code `from langchain.retrievers import ElasticSearchBM25Retriever` is enough but we need to add this ^ link to this code. I don't know how to do this. :(

**Comment by leo-gan** [comment]
> maybe we should just make it actually like code `from langchain.retrievers import ElasticSearchBM25Retriever`? or just the class name, since code block already shows where it's imported from? cc @hinthornw

@baskaryan Yes, "just the class name" works better. It is much cleaner. 
It would be nice to **sort** the reference list, but I don't know JS. I've tried a couple of things but they didn't work.

**Comment by leo-gan** [comment]
@baskaryan Any thoughts?

**Comment by leo-gan** [comment]
@baskaryan Thanks!

**Pull request merged**
