### PR TITLE
feat: new integration `wasm_chat`

### PR DESCRIPTION
**Pull request by apepkuss**
Adds `WasmChat` integration. `WasmChat` runs GGUF models locally or via chat service in lightweight and secure WebAssembly containers. In this PR, `WasmChatService` is introduced as the first step of the integration. `WasmChatService` is driven by [llama-api-server](https://github.com/second-state/llama-utils) and [WasmEdge Runtime](https://wasmedge.org/).

### CODE REVIEW

**Comment by apepkuss** [comment]
@baskaryan Could you please help review this PR? The failures reported by the previous GitHub action have been fixed. Thanks a lot!

**Review by baskaryan — APPROVED** [review]

**Comment by apepkuss** [comment]
@baskaryan The conflicts have been resolved. Thanks!

**Comment by apepkuss** [comment]
@baskaryan It seems this PR has been approved, but not merged. Are there any other steps I can do so that it can be merged into the main branch ASAP? Thanks a lot!

**Comment by apepkuss** [comment]
Great! It seems all required checks have been passed. Thanks!

**Review by hwchase17 — APPROVED** [review]

**Comment by apepkuss** [comment]
@hwchase17 @baskaryan Thanks for the review!

**Comment by pannous** [comment]
can this also be used to give the agents an unrestricted (or metered) code sandbox

**Comment by juntao** [comment]
> can this also be used to give the agents an unrestricted (or metered) code sandbox

I believe the purpose of this work is to provide an alternative LLM backend for LangChain. This backend runs in a Wasm sandbox. Why?

* The Wasm sandbox is secure and isolates the LLM inference code from the rest of the agent. The Wasm sandbox can meter the LLM inference code in it. It can also be orchestrated and managed by cloud-native tools.
* Compared with Python-based LLM backend, the Wasm solution is much smaller, simpler, and often faster.
* Compared with C++ based LLM backends, the Wasm backend is portable across devices with many different CPUs, GPUs, accelerators, and OSes.

However, the agent still runs in the LangChain environment. You could "sandbox" it by wrapping it in a VM or container. But, the agent itself is not in the Wasm sandbox.

**Pull request merged**
