### PR TITLE
Add Inference Endpoint Support

### PR DESCRIPTION
**Pull request by enoreyes**

### CODE REVIEW

**Comment by enoreyes** [comment]
This is a wrapper around Hugging Face's Inference Endpoints. This is the easiest way to deploy an Open Source LLM - see this blog for examples of running Flan-T5 XXL:

https://www.philschmid.de/deploy-t5-11b

I think adding support for this is big, and I'm going to be demo'ing an application of the "doc-chat" app running on Hugging Face's documentation with Flan-T5 XXL so I need this to be added for that.

**Comment by hwchase17** [comment]
awesome!! excited to get this in and see the doc-chat app live

**Comment by enoreyes** [comment]
Hey @hwchase17 I'm having trouble getting the listing set - it looks like the imports are being done in the wrong format but I can't quite figure out how to handle.

**Comment by hwchase17** [comment]
> Hey @hwchase17 I'm having trouble getting the linting set - it looks like the imports are being done in the wrong format but I can't quite figure out how to handle.

i will fix!

**Pull request merged**
