### PR TITLE
Embeddings Callbacks

### PR DESCRIPTION
**Pull request by hinthornw**
Similar to https://github.com/hwchase17/langchainjs/pull/1859 from the JS lib (though haven't made serializable yet). 

Example run: https://dev.smith.langchain.com/public/674633d8-9c38-4cdc-bd11-53202879fad1/r

Would like alignment on 
- New base class vs update existing
- Whether OK to stop supporting 'chunk_size' at call time for a handful

And this still doesn't address our retriever -> vector store -> embeddings flows. Will need to update a lot of those similarity score methods to accept callbacks since they're all called under the hood.

### CODE REVIEW

**Comment by DanilMartyniuk** [comment]
@hwchase17 , greetings! Is it possible to introduce this changes in the next closest versions? What else should be changed to integrate it into main branch?

**Comment by hinthornw** [comment]
Mainly just needs reviews :)

**Comment by leo-gan** [comment]
@hinthornw Hi , could you, please, resolve the merging issues?

**Comment by lkNGAT** [comment]
Having callbacks would be really important for my LLM application. I would like to track the number of tokens used over time.
Could you please consider finishing this PR?

**Pull request closed without merging**
