### PR TITLE
Community: Basic Logging and Human input to ShellTool

### PR DESCRIPTION
**Pull request by krishnashed**
- **Description:** As Shell tool is very versatile, while integrating it into applications as openai functions, developers have no clue about what command is being executed using the ShellTool. All one can see is:
image

Summarising my feature request:
1. There's no visibility about what command was executed.
2. There's no mechanism to prevent a command to be executed using ShellTool, like a y/n human input which can be accepted from user to proceed with executing the command., 
  - **Issue:** the issue #15931 it fixes if applicable,
  - **Dependencies:** There isn't any dependancy,
  - **Twitter handle:** @krishnashed

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
printing seems fine (would prefer logging)

for asking for human input, id prefer NOT an argument to _run - it doesnt seem like the LLM should decide, but seems like should be a param on the class so the user can set

**Comment by krishnashed** [comment]
Thanks @hwchase17 for reviewing the PR. I'll implement as instructed, and get back!

**Review by hwchase17 — APPROVED** [review]

**Comment by krishnashed** [comment]
@hwchase17 I still need to write test cases, then you can merge the PR

**Comment by krishnashed** [comment]
@hwchase17 I've completed the feature and also written tests for it, could you please check and merge the PR ?

**Review by baskaryan — APPROVED** [review]

**Comment by krishnashed** [comment]
@baskaryan The linting issues are fixed, you could please merge the PR ?

**Pull request merged**
