### PR TITLE
Adding support for amazon personalize Integration

### PR DESCRIPTION
**Pull request by pranava-amzn**
## Amazon Personalize support on Langchain

This PR introduces an integration with [Amazon Personalize](https://aws.amazon.com/personalize/) to help you to retrieve recommendations and use them in your natural language applications. This integration provides two new components:

1. An `AmazonPersonalize` client, that provides a wrapper around the Amazon Personalize API.
2. An `AmazonPersonalizeChain`, that provides a chain to pull in recommendations using the client, and then generating the response in natural language. 

Here is some sample code to explain the usage.

```python
from langchain.utilities import AmazonPersonalize
from langchain.chains import AmazonPersonalizeChain
from langchain.llms.bedrock import Bedrock

recommender_arn = "<insert_arn>"

client=AmazonPersonalize(
    credentials_profile_name="default",
    region_name="us-west-2",
    recommender_arn=recommender_arn
)
bedrock_llm = Bedrock(
    model_id="anthropic.claude-v2", 
    region_name="us-west-2"
)

chain = AmazonPersonalizeChain.from_llm(
    llm=bedrock_llm, 
    client=client
)
response = chain({'user_id': '1'})
```

Reviewer: @3coins

### CODE REVIEW

**Review by 3coins — APPROVED** [review]
@pranava-amzn 
Looks great! Thanks for adding this. 🚀

**Comment by 3coins** [comment]
cc @baskaryan for help with merging this.

**Comment by 3coins** [comment]
@baskaryan 
Let me know if there is anything I can do to move this forward. Thanks!

**Comment by pranava-amzn** [comment]
Hi @baskaryan, Need your help with this PR. Let me and @3coins know. Thanks!

**Review by hwchase17 — COMMENTED** [review]
i think adding this is a whole new use case is a bit extreme. i would probably suggest a cookbook

other than that, looks good

**Comment by pranava-amzn** [comment]
> i think adding this is a whole new use case is a bit extreme. i would probably suggest a cookbook
> 
> other than that, looks good

@hwchase17 Thanks for reviewing. I'll move the docs to cookbook and update the PR in a bit. Appreciate your inputs on this :)

**Comment by 3coins** [comment]
@hwchase17 
Correct me if I am wrong, but are you suggesting to moving the complete code to the cookbook? Although, this use case hasn't been explored before, there are parallels in other providers that might warrant a new module for this. Here is a similar service that GCP provides.
https://cloud.google.com/recommendations

**Comment by baskaryan** [comment]
landed in #17436

**Pull request closed without merging**
