### PR TITLE
docs: `modules` pages simplified

### LINKED ISSUE #5627: DOC: repetitive parts in Modules pages
### Issue with current documentation:

Pages in Modules: Models, Prompts, Memory, ... 
They all have repeated parts. See a picture. 

image

### Idea or request for content:
The whole "Go Deeper" section can be removed and instead, the links from removed items added to the above items. For example "Prompt Templates" link is added to the "LLM Prompt Templates" in the above text. Etc.
This significantly decreases the size of the page and improves user experience. No more repetitive items.
_No response_

### PR DESCRIPTION
**Pull request by leo-gan**
# docs: modules pages simplified

Fixed #5627  issue

Merged several repetitive sections in the `modules` pages. Some texts, that were hard to understand, were also simplified.

## Who can review?

@hwchase17
@dev2049

### CODE REVIEW

**Comment by leo-gan** [comment]
@dev2049 Gentle reminder.

**Comment by leo-gan** [comment]
@hwchase17 Gentle reminder.

**Comment by leo-gan** [comment]
@hwchase17 Gentle reminder.

**Comment by leo-gan** [comment]
@dev2049 Gentle reminder

**Comment by leo-gan** [comment]
@hwchase17 Can you, review it?

**Review by hwchase17 — APPROVED** [review]

**Pull request merged**
