### PR TITLE
community: integrate with model Yuan2.0

### PR DESCRIPTION
**Pull request by cauwulixuan**
1. integrate with [`Yuan2.0`](https://github.com/IEIT-Yuan/Yuan-2.0/blob/main/README-EN.md)
2. update `langchain.llms`
3. add a new doc for [Yuan2.0 integration](docs/docs/integrations/llms/yuan2.ipynb)

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
please do not update the langchain entrypoints! those are deprecated, should be imported directly from langchain_community

otherwise lgtm

**Comment by cauwulixuan** [comment]
> please do not update the langchain entrypoints! those are deprecated, should be imported directly from langchain_community

Thanks for your reply.

Is that mean, I don't need modify `libs/langchain/langchain/llms/__init__.py`? 

and I should use `from langchain_community.llms.yuan2 import Yuan2` instead of `from langchain.llms.yuan2 import Yuan2`, right?

**Comment by hwchase17** [comment]
> > please do not update the langchain entrypoints! those are deprecated, should be imported directly from langchain_community
> 
> Thanks for your reply.
> 
> Is that mean, I don't need modify `libs/langchain/langchain/llms/__init__.py`?
> 
> and I should use `from langchain_community.llms.yuan2 import Yuan2` instead of `from langchain.llms.yuan2 import Yuan2`, right?

yes, exactly

**Comment by cauwulixuan** [comment]
@hwchase17 Hi, I fixed some errors, could you help to review it again?  Thanks for your time.

**Comment by cauwulixuan** [comment]
Sorry to bother you again. Could you tell me what your plans? May I know when the PR can be merged? I have other PRs depended on this feature. @hwchase17 @

**Review by baskaryan — APPROVED** [review]

**Comment by cauwulixuan** [comment]
Thanks for your approval, I can see some checks were failed. Should I do anything to pass all checks? @baskaryan

**Comment by cauwulixuan** [comment]
@hwchase17 I noticed that some checks have failed, and it seems there's nothing I can modify. Is there anything specific you would like me to do? BTW, now I can see this pr is approved by @baskaryan , and may I know your merge plan? I have some other work that depends on this pull request. Thanks you guys...

**Comment by cauwulixuan** [comment]
Seems like this pr was closed and reopened. Hope everything goes well...
We would greatly appreciate it if we could push this PR forward, as I can see, now 5 checks failed with some errors:
```
tests/integration_tests/llms/test_yuan2.py:2: in <module>
    from langchain.schema import LLMResult
E   ModuleNotFoundError: No module named 'langchain'
```
I have no idea why this would happen, any ideas? @hwchase17 @baskaryan

**Comment by cauwulixuan** [comment]
Any updates here? @hwchase17 @baskaryan

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
