### PR TITLE
partners: validate api key

### PR DESCRIPTION
**Pull request by AndrewEffendi**
fixes issue #27365
Adds an error message notifying the user that they are using an invalid character in their api key

### CODE REVIEW

**Comment by efriis** [comment]
would rather not in case openai changes their api key format!

**Comment by jasonkaedingrhino** [comment]
> would rather not in case openai changes their api key format!

@efriis 
I agree that a regex test is too heavy-handed. However, would it be appropriate to "check" the API key from an encoding perspective, since just blindly passing strings down into the HTTP client is where we end up with esoteric HTTP client errors about encodings?

**Comment by AndrewEffendi** [comment]
What about instead of using regex, we check if it raise a UnicodeEncodeError when we try to encode the api key?
```python
if self.openai_api_key:
    api_key = self.openai_api_key.get_secret_value()
    try:
        api_key.encode('ascii')
    except UnicodeEncodeError:
        raise ValueError("Invalid API key: Only ASCII characters are allowed.")
```

**Comment by jasonkaedingrhino** [comment]
FWIW - I have since realized that the stack trace is actually pointing back down to `openai` library directly.

I decided to open an [issue](https://github.com/openai/openai-python/issues/1793) there.

**Pull request closed without merging**
