### PR TITLE
Improvements to the Clarifai integration

### PR DESCRIPTION
**Pull request by zeiler**
- Improved docs
 - Improved performance in multiple ways through batching, threading, etc.
 - fixed error message 
 - Added support for metadata filtering during similarity search.

@baskaryan PTAL

### CODE REVIEW

**Comment by zeiler** [comment]
hey @baskaryan can I get a review please, should be good to merge. Thanks.

**Comment by zeiler** [comment]
@hwchase17 can we merge please?

**Comment by zeiler** [comment]
@baskaryan @hwchase17 @agola11 @rlancemartin checking in to see how we can merge this PR. Eager to get this in as we need it for an event later this week.

**Comment by baskaryan** [comment]
sorry for delay, lgtm! thanks @zeiler!

**Pull request merged**
