### PR TITLE
[HuggingFace Pipeline] add streaming support

### PR DESCRIPTION
**Pull request by openvino-dev-samples**

### CODE REVIEW

**Comment by OpenVINO-dev-contest** [comment]
@baskaryan @ccurme could you help to review, thanks

**Comment by Jofthomas** [comment]
Hey @OpenVINO-dev-contest, thanks for making this change.

It would be better to implement the stops with `stop_strings ` but while they work in model.generate(), this new parameter does not seem to be correctly passed to the pipeline. Hence, The StoppingCriteriaList works for me at this moment, but should be changed later on ( I'll dig transformers with the team ).

At first glance, PR looks good to me.

**Review by ccurme — COMMENTED** [review]
Hi @OpenVINO-dev-contest, thanks for this. Could you please add tests to the `partners/huggingface/` implementation?

**Comment by OpenVINO-dev-contest** [comment]
> Hi @OpenVINO-dev-contest, thanks for this. Could you please add tests to the `partners/huggingface/` implementation?

done

**Review by ccurme — APPROVED** [review]

**Pull request merged**
