### PR TITLE
Implement AgentExecutorIterator

### PR DESCRIPTION
**Pull request by SlapDrone**
- Description: Implements a `.iter()` method for the `AgentExecutor` class. This allows hooking into and intercepting intermediate agent steps.
  - Issue: #6925 
  - Dependencies: None
  - Tag maintainer: @vowelparrot @agola11 
  - Twitter handle: @SlapDron3 @lacicocodes

### CODE REVIEW

**Comment by SlapDrone** [comment]
For any questions/feedback myself and @Lacico wrote this.

**Comment by dev2049** [comment]
woah, super cool. will find time to properly review but for now would be awesome to have a demo notebook (probably in docs/extras/modules/agents/how_to dir)

**Comment by SlapDrone** [comment]
Great, good idea. Will cook a notebook up when have time on Sunday evening.

**Comment by Lacico** [comment]
We've added an [example notebook](https://github.com/hwchase17/langchain/blob/b5a5e9ae68931f4f62ab780c5d2f00578c5c17fd/docs/extras/modules/agents/how_to/agent_iter.ipynb) demonstrating how to verify output generated by the agent at each step.

**Comment by SlapDrone** [comment]
Hey folks, anyone had the chance to review this? @dev2049 @vowelparrot @agola11

**Review by hwchase17 — COMMENTED** [review]
this is pretty cool. sorry for delayed comment. not going to lie - dont have a ton of time to actively review it.... but since it doesnt change too much existing code, im relatively fine landing. i'd mildy prefer to land it in langchain.experimental and not modifying agent at all (could have ux of `for step in create_iter_agent(agent, "question")` or something like that).

thoughts on that? if that were the case id be very happy to land asap. would also make it easier to change without regards for backwards compatibility

**Comment by SlapDrone** [comment]
Hey @hwchase17, no worries and thanks for taking a look. We were also wary of touching agent so went heavy on the tests and made only an additive change.

Had a chat with @Lacico and we are happy to hold off a bit for a full-fledged review from @baskaryan or another maintainer so we can all gain the necessary confidence that it won't break anything.

**Comment by Lacico** [comment]
Heya @baskaryan, do you know when/if you'll have time to give these changes a review? Thanks.

**Comment by SlapDrone** [comment]
Hey folks. Let us know if there's anything we can do to help here. If it makes a difference, we're using this in a major project so would be happy to maintain this class.

**Comment by baskaryan** [comment]
apologies for the delay. this is awesome, thanks @SlapDrone and @Lacico!

**Pull request merged**
