### PR TITLE
Internal code deprecation API

### PR DESCRIPTION
**Pull request by eyurtsev**
Proposal for an internal API to deprecate LangChain code.

This PR is heavily based on: https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/_api/deprecation.py

This PR only includes deprecation functionality (no renaming etc.). 
Additional functionality can be added on a need basis (e.g., renaming parameters), but best to roll out as an MVP to test this 
out.

DeprecationWarnings are ignored by default. We can change the policy for the deprecation warnings, but we'll need to make sure we're not creating noise for users due to internal code invoking deprecated functionality.

### CODE REVIEW

**Comment by eyurtsev** [comment]
Doing minimal work to add type hints to this code, but I don't think we want to spend much effort (it's hard, but not super useful)

**Review by hinthornw — COMMENTED** [review]
Oh I quite like this - haven't tried using it yet though

**Comment by eyurtsev** [comment]
Ready for review. It's not attached to anything yet, so little risk from it. I'll roll it out to predict and parse and update code to correctly modify sphinx documentation so we get deprecation warnings in docs

**Comment by eyurtsev** [comment]
@baskaryan let me know if i can merge

**Comment by baskaryan** [comment]
> @baskaryan let me know if i can merge

ship it 🚢

**Pull request merged**
