### PR TITLE
fix SQL toolkit table listing tool name

### LINKED ISSUE #7440: list_tables_sql_db is not a valid tool, try another one.
### System Info

langchain: 0.0.215
python: 3.10.11
OS: Ubuntu 18.04

### Who can help?

_No response_

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

While querying a SQL database, the agent gets stuck in an infinite loop due to `list_tables_sql_db` not being a valid tool.

```
> Entering new  chain...
Action: list_tables_sql_db
Action Input: 
Observation: list_tables_sql_db is not a valid tool, try another one.
Thought:I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
Action: list_tables_sql_db
Action Input: 
Observation: list_tables_sql_db is not a valid tool, try another one.
Thought:I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
Action: list_tables_sql_db
Action Input: 
Observation: list_tables_sql_db is not a valid tool, try another one.
Thought:I don't know how to answer this question.
Thought: I now know the final answer
Final Answer: I don't know

> Finished chain.
```

### Expected behavior

The agent should get the list of tables by using the `list_tables_sql_db` tool and then query the most relevant one.

### PR DESCRIPTION
**Pull request by saswat0**
- Description: This PR fixes the erroneous naming convention of the `list_tables_sql_db` tool used for querying the list of tables present in a database. This is a minor fix which renames all the occurrences of the above tool with the one described in the tool's description.
- Issue: Fixes #7440 
- Dependencies: None
- Maintainer: @hinthornw

### CODE REVIEW

**Comment by baskaryan** [comment]
@hinthornw seems spark sql tool already has this name, should we rename the spark one to indicate it's spark?

**Comment by saswat0** [comment]
@baskaryan Should there be 2 separate tools for the same job?

**Comment by leo-gan** [comment]
@baskaryan FYI ^

**Comment by efriis** [comment]
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

**Pull request closed without merging**
