### PR TITLE
jw metaphor v3

### PR DESCRIPTION
**Pull request by jeffzwang**
- add metaphor search new api fields
- update example notebook
- clear output
- add new field, fix ipynb formatting

### CODE REVIEW

**Comment by baskaryan** [comment]
looks like this was landed in #6387, lemme know if there's anything we're missing @jeffzwang!

**Comment by jeffzwang** [comment]
> looks like this was landed in #6387, lemme know if there's anything we're missing @jeffzwang!

hey @baskaryan I think this was not landed actually - I don't see the update on the website?

**Comment by baskaryan** [comment]
> > looks like this was landed in #6387, lemme know if there's anything we're missing @jeffzwang!
> 
> hey @baskaryan I think this was not landed actually - I don't see the update on the website?

is this not updated (e.g. has an Adding Filter section) 
https://python.langchain.com/docs/modules/agents/tools/integrations/metaphor_search?

**Comment by jeffzwang** [comment]
> > > looks like this was landed in #6387, lemme know if there's anything we're missing @jeffzwang!
> > 
> > 
> > hey @baskaryan I think this was not landed actually - I don't see the update on the website?
> 
> is this not updated (e.g. has an Adding Filter section) https://python.langchain.com/docs/modules/agents/tools/integrations/metaphor_search?

it is not updated

**Pull request closed without merging**
