### PR TITLE
#4532 Add Vertex AI PaLM Models

### LINKED ISSUE #4532: Vertex AI PaLM Support
### Feature request

If unaware, Google has opened PaLM into public preview in Vertex AI in GCP. This uses different client libraries from the general-use PaLM API that was implemented in the base Langchain support for PaLM. 

### Motivation

As an enterprise user, I'd like to leverage the model endpoints that meet my organization's security and privacy requirements with LangChain. 

### Your contribution

I can open a PR, but as folks from Google like @brotchie having contributed, I wanted to make sure I wasn't duplicating work if I did this.

### PR DESCRIPTION
**Pull request by Jflick58**
# Add Vertex AI PaLM Models

Adds the following model integrations for GCP Vertex AI versions of PaLM: 
  - Embeddings
  - Chat Models
  - LLM 

Fixes #4532

### CODE REVIEW

**Comment by Jflick58** [comment]
@hwchase17 @agola11  hoping we can get this reviewed soon - seems like the issue I raised was gaining a lot of traction.

**Comment by dev2049** [comment]
@Jflick58 may very well be my ignorance but what's difference between this and #4594

**Comment by Jflick58** [comment]
Shoot. I didn’t know that one existed. There was a series of issues about this and no one ever indicated a PR was made. 

If I had to make a case for this PR, after a brief look at the other: I think I stayed closer to LangChain constructs and included a wide test suite and docs.

**Comment by sidsathi** [comment]
@Jflick58 Awesome work. Hoping this gets reviewed soon!

**Comment by hwchase17** [comment]
we'll work on figuring out how best to get Vertex support in asap! working with the vertex team

**Comment by Jflick58** [comment]
Closed in favor of #5049

**Pull request closed without merging**
