### PR TITLE
chore(openllm): simplified interface with new API

### PR DESCRIPTION
**Pull request by aarnphm**
Depends on https://github.com/bentoml/OpenLLM/pull/518 to be released for 0.3.15

twitter handle: @aarnphm_

cc @baskaryan this is ready from OpenLLM.

Signed-off-by: Aaron <29749331+aarnphm@users.noreply.github.com>

### CODE REVIEW

**Comment by aarnphm** [comment]
cc @baskaryan for a review this is now READY

**Comment by aarnphm** [comment]
kindly ask @baskaryan again

**Comment by aarnphm** [comment]
@baskaryan I have addressed all linting issues I believe

**Comment by aarnphm** [comment]
cc @baskaryan I have updated to the new refactor.

**Comment by HerzogVolpe** [comment]
will this branch be merged?

**Comment by aarnphm** [comment]
You can install from our fork for now.

**Comment by baskaryan** [comment]
sorry for the delay @aarnphm. updated the branch and opened a pr #19894, feel free to merge that into here if it looks good to you or i can just land that pr

**Pull request closed without merging**
