### PR TITLE
Pass HuggingFacePipeline kwargs on inference

### PR DESCRIPTION
**Pull request by sergey-volokhin**
**Description:**

Pass HuggingFacePipeline kwargs at inference, not just when it's instantiated, so that changing the arguments of the pipeline would actually affect the result, e.g.
```python
from langchain import HuggingFacePipeline

pipe = HuggingFacePipeline.from_model_id(
    task="text-generation",
    device=1,
    model_id="meta-llama/Llama-2-7b-chat-hf",
    pipeline_kwargs={
        'max_length': 100,
        'temperature': 0.1
    },
)

pipe('hello, how are you?')  # this can return up to 100 tokens w temperature 0.1

pipe.pipeline_kwargs['temperature'] = 0.9
pipe.pipeline_kwargs['max_length'] = 50
pipe('hello, how are you?')  # this can return up to 50 tokens w temperature 0.9
```
**Issue:**
None
**Dependencies:**
None 
**Tag maintainer:**
None
**Twitter handle:**
None

### CODE REVIEW

**Comment by baskaryan** [comment]
hm not super familiar with what kwargs should be passed in during pipeline instantiation vs at inference time, is there an argument that we should have a separate inference_kwargs param to handle you're example?

**Comment by sergey-volokhin** [comment]
> hm not super familiar with what kwargs should be passed in during pipeline instantiation vs at inference time, is there an argument that we should have a separate inference_kwargs param to handle your example?

All arguments for pipeline inference can be supplied at instantiation and stored into [`self._forward_params`](https://github.com/huggingface/transformers/blob/0a55d9f7376f72ad3ff296d4249840021b03bcc4/src/transformers/pipelines/base.py#L830C44-L830C44), but the reverse is not true, there are some arguments at instantiation that can't be passed at inference. Most of the such arguments aren't relevant (like `image_processor` or `feature_extractor`, which are only used for images), and I am not sure how relevant are the rest, like `framework` (i.e. torch vs tf), `modelcard`, `revision` [etc](https://github.com/huggingface/transformers/blob/0a55d9f7376f72ad3ff296d4249840021b03bcc4/src/transformers/pipelines/base.py#L760). 
The only argument that is definitely useful is `torch_dtype`, so it is not currently possible to change that type using `HuggingFacePipeline.from_model_id` without inference breaking. The only solution is to pass `transformers.pipeline` directly. 
Would it make more sense to make `torch_dtype` a separate argument for `.from_model_id` instead of making an entire dictionary?

**Comment by sergey-volokhin** [comment]
Actually, in the current version the fix breaks if instantiating the pipeline using `__init__`, because `self.pipeline_kwargs` and `self.model_kwargs` are `None`, instead of `{}`, like when instantiating using `.from_model_id` ([here](https://github.com/langchain-ai/langchain/blob/116cc7998cac563894bdf0037259db767882b55c/libs/langchain/langchain/llms/huggingface_pipeline.py#L125) and [here](https://github.com/langchain-ai/langchain/blob/116cc7998cac563894bdf0037259db767882b55c/libs/langchain/langchain/llms/huggingface_pipeline.py#L86)):

I think that the default values of [`model_kwargs`](https://github.com/langchain-ai/langchain/blob/116cc7998cac563894bdf0037259db767882b55c/libs/langchain/langchain/llms/huggingface_pipeline.py#L51C40-L51C40) and [`pipeline_kwargs`](https://github.com/langchain-ai/langchain/blob/116cc7998cac563894bdf0037259db767882b55c/libs/langchain/langchain/llms/huggingface_pipeline.py#L53) should be changed to `{}` to maintain the parity:

```python
# code from the `.from_model_id` example in the documentation
from langchain.llms import HuggingFacePipeline 
hf = HuggingFacePipeline.from_model_id(
    model_id="gpt2",
    task="text-generation",
    pipeline_kwargs={"max_new_tokens": 10},
)
```
```
hf.model_kwargs == {}
hf.pipeline_kwargs == {"max_new_tokens": 10}
```
and
``` python
# code from the direct passing example in the documentation
from langchain.llms import HuggingFacePipeline
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

model_id = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id)
pipe = pipeline(
    "text-generation", model=model, tokenizer=tokenizer, max_new_tokens=10
)
hf = HuggingFacePipeline(pipeline=pipe)
```
```
hf.model_kwargs is None
hf.pipeline_kwargs is None
```

**Comment by Davido111200** [comment]
Hi all, I wonder if we have got the solution to this? Thanks

**Comment by baskaryan** [comment]
Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

**Pull request closed without merging**
