### PR TITLE
community: integrate China Mobile Ecloud vector search

### PR DESCRIPTION
**Pull request by liuyonghengheng**
- **Description:** integrate China Mobile Ecloud vector search, 
  - **Dependencies:** elasticsearch==7.10.1

### CODE REVIEW

**Comment by liuyonghengheng** [comment]
Hi @efriis ，please help us rerun the check flow ，thanks

**Review by efriis — COMMENTED** [review]
- revert all changes in libs/langchain (these are new classes, so they'll only be in community for backwards compatibility)


general question: would it be possible to just use the Elastic vector store with a custom base url set? What is different about this implementation?

**Comment by liuyonghengheng** [comment]
> * revert all changes in libs/langchain (these are new classes, so they'll only be in community for backwards compatibility)
> 
> general question: would it be possible to just use the Elastic vector store with a custom base url set? What is different about this implementation?

the Ecloud ES is based on ES7.10.2（Apache License 2.0），we custom develop some models and functions，and it is not fully compatible with the bussiness ES。 we developed knn model and it is not compatible with bussiness ES too. and some Ecloud users want to use this feature on langchain, so we are trying to integrate it into this project

**Comment by liuyonghengheng** [comment]
Hi @efriis what should i do now，and do you hava more questions about our pr or you can give us some suggestions？thanks！

**Comment by liuyonghengheng** [comment]
Hi @efriis can you help us rerun the checkflow ？we have reverted all changes in libs/langchain， thanks

**Review by efriis — APPROVED** [review]

**Comment by liuyonghengheng** [comment]
Hi @efriis we have fixed the new conflicts and fixed the lint error, cloud you please help us review the code and rerun the checkflow?

**Comment by liuyonghengheng** [comment]
Hi @baskaryan  cloud you please help us rerun the checkflow? Thanks!

**Pull request merged**
