### PR TITLE
community: add some modifications to bypass human verification from document_loaders on url_playwright.py

### PR DESCRIPTION
**Pull request by Kev744**
I add a context variable for mimicking human control on website to url_playwright.py code in order to bypass human verification websites (e.g. Cloudfare) when loading websites

### CODE REVIEW

**Comment by eyurtsev** [comment]
Could you expose user agent as a parameter?

**Review by eyurtsev — CHANGES_REQUESTED** [review]
could you expose as a parameter to the initializer

**Comment by baskaryan** [comment]
is this same as #21911? if so can i close this one?

**Comment by Kev744** [comment]
> is this same as #21911? if so can i close this one?

Yes almost the same because in my newer version I added an additional functionnal functionnality.

**Pull request closed without merging**
