### PR TITLE
docs: Add docstrings for CassandraChatMessageHistory class and package namespace function.

### PR DESCRIPTION
**Pull request by ashvin-a**
- Modified docstring for CassandraChatMessageHistory in libs/community/langchain_community/chat_message_history/cassandra.py.

- Added docstring for _package_namespace function in docs/api_reference/create_api_rst.py

### CODE REVIEW

**Comment by ashvin-a** [comment]
@efriis

**Review by efriis — APPROVED** [review]

**Comment by ashvin-a** [comment]
@efriis I would like to get approval for the workflows. Sorry for the trouble. Thanks

**Review by efriis — APPROVED** [review]

**Comment by ashvin-a** [comment]
@efriis I have made changes to pass the lint test. Sorry for the trouble my man 😭.

**Comment by ashvin-a** [comment]
@efriis Could you please approve this PR? Thanks in advance.

**Comment by ccurme** [comment]
Thanks @ashvin-a. See contributing guidelines [here](https://python.langchain.com/v0.2/docs/contributing/code/setup/#formatting-and-linting) for a one-liner that will format your code so you don't need to battle the linter :)

**Comment by ashvin-a** [comment]
Sure, I'll check it out. Thanks so much.

**Pull request merged**
