### PR TITLE
Add Enum for agent types

### PR DESCRIPTION
**Pull request by Shrined**
This pull request adds an enum class for the various types of agents used in the project, located in the `agent_types.py` file. Currently, the project is using hardcoded strings for the initialization of these agents, which can lead to errors and make the code harder to maintain. With the introduction of the new enums, the code will be more readable and less error-prone.

The new enum members include:

- ZERO_SHOT_REACT_DESCRIPTION
- REACT_DOCSTORE
- SELF_ASK_WITH_SEARCH
- CONVERSATIONAL_REACT_DESCRIPTION
- CHAT_ZERO_SHOT_REACT_DESCRIPTION
- CHAT_CONVERSATIONAL_REACT_DESCRIPTION

In this PR, I have also replaced the hardcoded strings with the appropriate enum members throughout the codebase, ensuring a smooth transition to the new approach.

### CODE REVIEW

**Comment by Shrined** [comment]
Addressed the issue where hardcoded strings instead of the AgentType enums were still being used in some of the examples within the documentation.

**Review by hwchase17 — COMMENTED** [review]
this is awesome.

thinking about backwards compatibility - this will still work for people on the old version, right? because the string is still the same under the hood?

**Comment by Shrined** [comment]
> this is awesome.
> 
> thinking about backwards compatibility - this will still work for people on the old version, right? because the string is still the same under the hood?

Yes, exactly. Due to the AgentType class inheriting from str, the underlying string representation is maintained, ensuring backwards compatibility for users on older versions.

**Review by hwchase17 — COMMENTED** [review]
thanks!

**Pull request merged**
