### PR TITLE
community : add exllamav2 library for GPTQ & EXL2 models

### PR DESCRIPTION
**Pull request by AmineDjeghri**
Added 3 files : 
- Library : ExLlamaV2 
- Test integration
- Notebook

### CODE REVIEW

**Review by baskaryan — APPROVED** [review]

**Comment by fzyzcjy** [comment]
Hi, is there any updates? Thanks!

**Comment by baskaryan** [comment]
failing CI, please run tests and lint
```bash
cd libs/community
make format
make lint
make test
```

**Comment by AmineDjeghri** [comment]
@fzyzcjy  @baskaryan 
i did some updates and i think it's working now 
https://github.com/AmineDjeghri/langchain/actions/runs/8637101856

**Comment by AmineDjeghri** [comment]
i can't access to Vercel details to see what is the problem

**Comment by baskaryan** [comment]
> i can't access to Vercel details to see what is the problem Also, i have this in the forked repo : https://github.com/AmineDjeghri/langchain/actions/runs/8647269906

broken link
```

Exhaustive list of all broken links found:
--
02:37:02.985 |  
02:37:02.985 | - On source page path = /docs/integrations/llms/exllamav2/:
02:37:02.985 | -> linking to A%20fast%20inference%20library%20for%20running%20LLMs%20locally%20on%20modern%20consumer-class%20GPUs/ (resolved as: /docs/integrations/llms/exllamav2/A%20fast%20inference%20library%20for%20running%20LLMs%20locally%20on%20modern%20consumer-class%20GPUs/)


```

**Comment by AmineDjeghri** [comment]
Thanks, i updated the broken link.
the Deployment seems to pass !

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
