### PR TITLE
Fix for AzureOpenAI 

### PR DESCRIPTION
**Pull request by louis-li**
Fix for issue: https://github.com/hwchase17/langchain/issues/1243

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
@gojira does this look good to you?

**Comment by gojira** [comment]
Looking

**Comment by gojira** [comment]
@louis-li  this should not be necessary - can you try following this notebook 

https://github.com/hwchase17/langchain/blob/master/docs/modules/llms/integrations/azure_openai_example.ipynb

**Comment by gojira** [comment]
The model name is used with OpenAI LLM to get the token metadata etc.

**Comment by louis-li** [comment]
Azure OpenAI doesn't need it, it only needs deployment_name.

**Comment by viaminds** [comment]
Just as a note to this issue: @louis-li  is right, only deployment name is needed. 
And when importing both AzureOpenAi and OpenAi, it is trying to validate the api key against OpenAi instead of AzureOpenAi. 
For instance , with this imports : 
_from langchain.llms import AzureOpenAI
import os
from openai.embeddings_utils import get_embedding, cosine_similarity_
it´s throwing this error : 
_Incorrect API key provided: **********************. You can find your API key at https://platform.openai.com/account/api-keys_.

**Comment by TSPereira** [comment]
> Just as a note to this issue: @louis-li is right, only deployment name is needed. And when importing both AzureOpenAi and OpenAi, it is trying to validate the api key against OpenAi instead of AzureOpenAi. For instance , with this imports : _from langchain.llms import AzureOpenAI import os from openai.embeddings_utils import get_embedding, cosine_similarity_ it´s throwing this error : _Incorrect API key provided: **********************. You can find your API key at https://platform.openai.com/account/api-keys_.

I also have this issue. I think the setup of the correct environment keys is done for `AzureChatOpenAI` but not for `AzureOpenAI`

**Pull request closed without merging**
