### PR TITLE
Jacob/docs new

### PR DESCRIPTION
**Pull request by jacoblee93**
CC @ccurme @baskaryan

### CODE REVIEW

**Comment by leo-gan** [comment]
@jacoblee93 Hey Jacob. Is it possible to split this PR into smaller PRs, by one PR per one independent change? We agreed to make changes in small PR because it is faster to progress, better in quality, and easier for contributors and reviewers. Thanks!

**Comment by jacoblee93** [comment]
> @jacoblee93 Hey Jacob. Is it possible to split this PR into smaller PRs, by one PR per one independent change? We agreed to make changes in small PR because it is faster to progress, better in quality, and easier for contributors and reviewers. Thanks!

Hey! In this case we've decided to do it all at once in order to reduce the amount of structural changes to developers. 

Vercel build is here if you're keen on having a look:

https://langchain-git-jacob-docsnew-langchain.vercel.app/docs/get_started/introduction

**Comment by leo-gan** [comment]
@jacoblee93 It seems that this one-go was needed.
Nice!
- navbar style is much better! 
- top-menu is better
- I have couple ideas about the `Components` menu but it should be another PR

**Comment by jacoblee93** [comment]
@baskaryan ready for review!

Still want to add a style guide but that shouldn't block.

**Comment by jacoblee93** [comment]
Style guide added @baskaryan - ready to go!

**Pull request merged**
