### PR TITLE
Dev/doc chat with message hisotry using rag

### PR DESCRIPTION
**Pull request by rongchenlin**
In the past tutorials, the docs introduced how to use RAG to enhance the capabilities of the chat question and answer system. However, if we want to introduce RAG into a conversation with chat memory, so that we can enhance the customization capabilities in a conversation with chat history. In this tutorial, we will be based on the original chat record saved in Sqlite, allowing users to pass in the previous conversation blog of lilianweng data to expand RAG in chat conversations. We will try this in the Sqlite, so that we can chat in the message history using RAG.

### CODE REVIEW

**Comment by rongchenlin** [comment]
@sbusso hello, can you help me, why i can't pass the ci ? thanks so much!

**Comment by sbusso** [comment]
> @sbusso hello, can you help me, why i can't pass the ci ? thanks so much!

may I know why you mention me?

**Comment by rongchenlin** [comment]
> > @sbusso hello, can you help me, why i can't pass the ci ? thanks so much!
> 
> may I know why you mention me?

Sorry to bother you, I am new to Github, I thought you were the maintainer of the project, so I mentioned you

**Comment by rongchenlin** [comment]
@eyurtsev hello, can you help me, why i can't pass the ci ? thanks so much!

**Comment by baskaryan** [comment]
@rongchenlin what's the difference between this and https://python.langchain.com/docs/use_cases/question_answering/chat_history?

**Pull request closed without merging**
