### PR TITLE
OpenAIEmbeddings: retry_min_seconds/retry_max_seconds parameters

### PR DESCRIPTION
**Pull request by adumont**
- **Description:** new parameters in OpenAIEmbeddings() constructor (retry_min_seconds and retry_max_seconds) that allow parametrization by the user of the former min_seconds and max_seconds that were hidden in _create_retry_decorator() and _async_retry_decorator()
  - **Issue:** #9298, #12986
  - **Dependencies:** none
  - **Tag maintainer:** @hwchase17
  - **Twitter handle:** @adumont

make format ✅
make lint ✅
make test ✅

### CODE REVIEW

**Comment by adumont** [comment]
cc @hwchase17

**Review by hwchase17 — APPROVED** [review]

**Comment by adumont** [comment]
The ratelimit is imposed by OpenAI (or Azure). So this won't remove it. But
instead of retrying every 4 sec for example, you can override the default
values. For example in my case when I trigger an  RateLimitError , the
message indicates I have to wait 40 sec, so I set the min to 40sec. Like
that I know it won't retry until 40 sec.
--
Alex

**Comment by afmurillo** [comment]
Hello Alex,

Thank you for your response. Yes, I had tried that with previous verions of langchain and openai (following your suggestion before this commit was merged). Nevertheless, in this case I don't get the message indicating the time to wait. I even overode the default values with 60 second as minimum and still did not work.

**Comment by PilotGFX** [comment]
Hello folks. Updating to the last update solved the rate limit error i was getting when using ada for embeddings.

**Pull request merged**
