### PR TITLE
SVM-based SKLearnVectorStore and filtering options for SKLearnVectorStores

### PR DESCRIPTION
**Pull request by mbrner**
In this PR I have made two additions to `SKLearnVectorStore`

## SVM based VectorStore: 

Instead of kNN, an SVM can be used for the retrieval step. This "trick" recently got some attention due to [this tweet](https://twitter.com/karpathy/status/1647025230546886658?s=2). The tweet also discusses possible advantages (better retrieval quality) and disadvantages (slower than kNN).

For the implementation, I split the `SKLearnVectorStore` class and created an abstract class `SKLearnVectorStoreBase` for which `_similarity_index_search_with_score` needs to be implemented. This abstract class is used to implement a kNN- and SVM-based vector store.

## Filtering

Both the kNN and SVM vector stores can now be used with metadata filters. The filters are either strings, where a `==` comparison is performed, or a callable that is called with the value of the metadata entry and should return a bool. When using filters, the retrieval algorithm must always be retrained, which slows down the retrieval step in the case of kNN.

Edit: I think  @dev2049 is the maintainer for this part of the code.

### CODE REVIEW

**Review by hwchase17 — APPROVED** [review]
we actually already have this in svm.py!

**Comment by mbrner** [comment]
> we actually already have this in svm.py!

Damn, missed that retriever. Update so that the vector store and the retriever use the same code for the retrieval step (`langchain.retrievers.svm.retrieve`). 

I think a vector store as a complement to the retriever has its value in the simplicity of use, especially with the filtering options.

**Comment by mbrner** [comment]
Anything I've got to change to get this merged?  @dev2049

**Comment by mbrner** [comment]
@hwchase17 Anything I can do to get this PR through?

**Comment by leo-gan** [comment]
@mbrner Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by efriis** [comment]
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

**Pull request closed without merging**
