### PR TITLE
OpenAI latest Update fixes

### PR DESCRIPTION
**Pull request by parthjain99**

### CODE REVIEW

**Comment by baskaryan** [comment]
hi @parthjain99, were you seeing issues using langchain and openai>=1? if so what version of langchain did you have?

**Comment by parthjain99** [comment]
langchain == 0.0.333

**Comment by adazoulay** [comment]
Also getting an error related to openai 1.2.2 when using the latest version of langchain.
- `[AttributeError: module ‘openai’ has no attribute ‘error’](https://community.openai.com/t/attributeerror-module-openai-has-no-attribute-error/486676)`

**Comment by hwchase17** [comment]
should be fixed in recent versions

**Pull request closed without merging**
