### PR TITLE
core[major]: AsyncCallbackManagerForToolRun no longer casts return object to string

### PR DESCRIPTION
**Pull request by adreo00**
- **Description:** Stops `AsyncCallbackManagerForToolRun` from converting the output to str
- **Issue:** #20372
- **Dependencies:** None

### CODE REVIEW

**Comment by adreo00** [comment]
Due to this being an async callback, I'm not sure how I could add tests to this code, but am open to suggestions. Issue https://github.com/langchain-ai/langchain/issues/20372 is able to reproduce this issue, but is not minimal enough to be included as a unit test.

**Comment by adreo00** [comment]
@eyurtsev I'm sure your slammed with other issues, but any chance you could take a look at this considering how close this PR is to the one you and @keenborder786 authored: https://github.com/langchain-ai/langchain/pull/18932

**Review by eyurtsev — APPROVED** [review]

**Comment by eyurtsev** [comment]
cc @baskaryan

**Comment by eyurtsev** [comment]
Will be released as part of 0.2.x

**Pull request merged**
