### PR TITLE
[llms-openai-proxy]Solve issue#1423: add open.proxy params loading from environment

### PR DESCRIPTION
**Pull request by peter65374**
This PR is to solve the issue#1423.
Add http_proxy loading from environment in openai.py for both BaseOpenAI and OpenAIChat. It is an optional env variables not mandatory.

This is my first PR, so I am not sure of the code formatting and lint. Please correct or assign issue to me to make it if any.

### CODE REVIEW

**Comment by hwchase17** [comment]
for other instances where we need to set attributes of the openai client (eg https://langchain.readthedocs.io/en/latest/modules/llms/integrations/azure_openai_example.html) we just set environment variables

can we do that here? or is this something that needs to be passed in at run time?

**Comment by peter65374** [comment]
> for other instances where we need to set attributes of the openai client (eg https://langchain.readthedocs.io/en/latest/modules/llms/integrations/azure_openai_example.html) we just set environment variables
> 
> can we do that here? or is this something that needs to be passed in at run time?

It seems that I finally figured out the How-to solve the issue. AzureOpenAI sample seems not the answer since not all of attributes are extracted from env setting in "openai/openai-python/__init__.py" 
However, [langchain/ecosystem/Helicone docs](https://langchain.readthedocs.io/en/latest/ecosystem/helicone.html#how-to-enable-helicone-caching) show a valid example, which is straight and cool.

Tried in Juypter, it worked. I will withdraw my PR after a while.

**Comment by Prayforhanluo** [comment]
@peter65374  老哥，能给AzureOpenAI加proxy的示例吗？我没看太明白这个Helicone里面怎么设置代理

**Comment by ever82** [comment]
https://python.langchain.com/docs/modules/model_io/models/llms/integrations/openai

os.environ["OPENAI_PROXY"] = "http://proxy.yourcompany.com:8080"

I had the same issue, and it was resolved by following the settings mentioned above.

**Comment by peter65374** [comment]
@Prayforhanluo  If you use FastAPI server, refer to code as below
'''python
@asynccontextmanager
async def lifespan(app: FastAPI):
    load_dotenv() # load .env variables, e.g. OPENAI_API_KEY / SERPER_API_KEY
    openai.proxy = os.getenv("HTTP_PROXY")
    api_logger.info(f"PROXY is setup at {openai.proxy}")
    yield

# api_jumper = FastAPI()
api_jumper = FastAPI(lifespan=lifespan)'''

To define your proxy in your .env file, e.g. "HTTP_PROXY="http://127.0.0.1:9991"

**Pull request closed without merging**
