### PR TITLE
fix: MergedDataLoader is compatible with load with parameters such as ConfluenceLoader

### PR DESCRIPTION
**Pull request by chyroc**
Replace this entire comment with:
  - **Description:** [a description of the change, ](fix: MergedDataLoader is compatible with load with parameters such as ConfluenceLoader)
  - **Issue:** https://github.com/langchain-ai/langchain/issues/12923
  - **Dependencies:** no
  - **Tag maintainer:** 
  - **Twitter handle:** @chyroc_

Please make sure your PR is passing linting and testing before submitting. Run `make format`, `make lint` and `make test` to check this locally.

See contribution guidelines for more information on how to write/run tests, lint, etc: 
https://github.com/langchain-ai/langchain/blob/master/.github/CONTRIBUTING.md

If you're adding a new integration, please include:
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/extras` directory.

If no one reviews your PR within a few days, please @-mention one of @baskaryan, @eyurtsev, @hwchase17.
 -->

### CODE REVIEW

**Comment by chyroc** [comment]
Sorry to bother you, could you please review this PR for me? If there are any problems, I will correct them immediately. @baskaryan

**Comment by chyroc** [comment]
@eyurtsev Sorry to bother you, could you please review this PR for me? If there are any problems, I will correct them immediately.

**Comment by chyroc** [comment]
@baskaryan Sorry to bother you, could you please review this PR for me? If there are any problems, I will correct them immediately.

**Comment by chyroc** [comment]
@eyurtsev Sorry to bother you, could you please review this PR for me? If there are any problems, I will correct them immediately.

**Comment by hwchase17** [comment]
we probbly dont want to override the signature of load

**Pull request closed without merging**
