### PR TITLE
feat(community): add support for similarity_score_threshold search in…

### PR DESCRIPTION
**Pull request by mspronesti**
See https://github.com/langchain-ai/langchain/issues/20600#issuecomment-2075569338 for details.

@chrislrobert

### CODE REVIEW

**Review by baskaryan — APPROVED** [review]

**Comment by chrislrobert** [comment]
@mspronesti Thanks for this. I think, though, that you still need `_select_relevance_score_fn()` and `similarity_search_with_score()` implementations in `AzureSearch` for this to work. I've been working happily with this version:

```
class ExtendedAzureSearch(AzureSearch):
    """Extended AzureSearch class with support for similarity_score_threshold searches."""

    def _select_relevance_score_fn(self) -> Callable[[float], float]:
        return self._azure_relevance_score_fn

    @staticmethod
    def _azure_relevance_score_fn(score: float) -> float:
        """Returns Azure's similarity score as-is."""

        # see https://learn.microsoft.com/en-us/azure/search/vector-search-ranking#scores-in-a-vector-search-results
        return score

    def similarity_search_with_score(
        self, *args: Any, **kwargs: Any
    ) -> List[Tuple[Document, float]]:
        """Run similarity search with distance."""

        # bridge into the AzureSearch class to run similarity search with distance
        return self.vector_search_with_score(*args, **kwargs)
```

It's been a while since I put that together and, unfortunately, I didn't keep good notes. I think that I based the implementation on the Pinecone class, plus the Azure Search scoring discussion at https://learn.microsoft.com/en-us/azure/search/vector-search-ranking#scores-in-a-vector-search-results. (Also had to contend with the LangChain-SDK incompatibility discussed at https://github.com/langchain-ai/langchain/issues/9985#issuecomment-1809631413.)

Finally, I don't know if it's fully okay for `AzureSearch.similarity_search()` to raise a not-allowed exception once the new search type is supported. (It's maybe okay if that function never gets called for that search type?)

**Comment by mspronesti** [comment]
@chrislrobert Not sure I see your point here :/ This (supposed) patch relies on `similarity_search_with_relevance_scores` from `AzureSearch`, filtering according to the threshold. Why do you think this wouldn't work? 

Btw, I wanted to open this PR as a WIP, sorry for that. I hope that @baskaryan tested this before merging. It seemed to work fine for me.

**Comment by chrislrobert** [comment]
Well, @mspronesti, I'm not sure just now, but:

1. There's no `similarity_search_with_score()` implementation in `AzureSearch`, and it's not clear to me when that gets called vs. `similarity_search_with_relevance_scores()`.
2. There's also no `_asimilarity_search_with_relevance_scores()` implementation in `AzureSearch`, and the base class version requires `_select_relevance_score_fn()`. I use async calls for my overall chain, so even if the search part ended up synchronous I'd want the rest to stay async.

So I think it's just a matter of which contexts will or won't be supported. I don't think `similarity_search_with_relevance_scores()` happens to cover my `ConversationalRetrievalChain` use case, but I believe you that there are at least a nonzero number of workflows that would be supported by this change here.

**Comment by chrislrobert** [comment]
@mspronesti I don't know, I'd have to test it end-to-end. I didn't add that stuff randomly, but as a result of trial-and-error, as I tried to get the `ConversationalRetrievalChain` working with Azure. I had an old implementation with Pinecone that was working fine, there were a number of examples out there, but when I tried to swap in the `AzureSearch` implementation I ended up with a bunch of errors to resolve. The thing is that I'm not directly calling the retriever at all: it's being used as a retriever called by other chains. To the extent that it fails to implement various endpoints, it trips up those chains. (Perhaps also, in the past few months, some of those issues themselves have gone away, I just don't know.)

And FWIW, I agree with you: it looks like true `async` support is needed, and my hack is just working around the issue there. I honestly don't understand how so many LangChain bits have been able to stay synchronous-only for so long. async support seems pretty fundamental for production use cases.

**Comment by mspronesti** [comment]
@chrislrobert I will have a look at this in the following days -- unless someone gets ahead of me :-) -- and I will tag you on the PR if I were to find a solution.

**Comment by chrislrobert** [comment]
@mspronesti, the latest version (0.2.10) seems to work now, following a bunch of work to add async support (like, namely, https://github.com/langchain-ai/langchain/pull/22075). Unfortunately, there's a new regression in issue #24740. But things are veeery close to fully working now in the base `AzureSearch` implementation. (You can see in my `ExtendedAzureSearch` class, in #24740, that I now only need to override to fix the regression, not for the `similarity_score_threshold` support.)

**Pull request merged**
