### PR TITLE
partners/pinecone: release 0.2.2

### PR DESCRIPTION
**Pull request by efriis**

### CODE REVIEW

**Comment by walterheck** [comment]
@efriis when wil this be published?

**Comment by efriis** [comment]
thanks for the shout - 0.2.1 attempt going out here: https://github.com/langchain-ai/langchain/actions/runs/12439137476/job/34732428243

the pinecone integration tests are pretty flaky because of slow consistency guarantees from the service, so hopefully this one goes out correctly! trying to work with the pinecone team to get the test instance improved or them to manage the package like some other vector stores :)

**Comment by walterheck** [comment]
@efriis thanks for the effort. Looks like it failed, can you give it another push?

I'm getting dependency issues like this:

```
#10 10.73 Collecting pinecone-client<6.0.0,>=5.0.0 (from langchain-pinecone==0.2.0->-r requirements.txt (line 18))
#10 10.73   Downloading pinecone_client-5.0.0-py3-none-any.whl.metadata (19 kB)
#10 10.75 ERROR: Cannot install -r requirements.txt (line 21) and langchain-pinecone because these package versions have conflicting dependencies.
#10 10.75 
#10 10.75 The conflict is caused by:
#10 10.75     pinecone 5.4.2 depends on pinecone-plugin-inference<4.0.0 and >=2.0.0
#10 10.75     pinecone-client 5.0.1 depends on pinecone-plugin-inference<2.0.0 and >=1.0.3
#10 10.75     pinecone 5.4.2 depends on pinecone-plugin-inference<4.0.0 and >=2.0.0
#10 10.75     pinecone-client 5.0.0 depends on pinecone-plugin-inference==1.0.2
#10 10.75 
```

**Comment by efriis** [comment]
filed #29020 and sent it to the pinecone team. I think there might actually be some compatibility issues that are causing the integration tests to hang indefinitely.

**Pull request merged**
