### PR TITLE
community: Refactor CassandraDatabase wrapper

### PR DESCRIPTION
**Pull request by cbornet**
* Introduce individual `fetch_` methods for easier typing.
* Rework some docstrings to google style
* Move some logic to the tool
* Merge the 2 cassandra utility files

### CODE REVIEW

**Comment by cbornet** [comment]
It would be nice if this can be reviewed and merged before the 0.17 release to not introduce breaking changes (the cassandra tool is not yet part of a release).

**Comment by eyurtsev** [comment]
Are any users importing from casandra_database.py? If so, should we re-import there for backwards compatibility?

**Review by eyurtsev — APPROVED** [review]

**Comment by cbornet** [comment]
> Not yet as casandra_database.py has not been part of a release yet.

Well, now that 1.17 has been released, it's not true anymore 😞 .
So I can keep things in cassandra_database.py. But now we have 2 utility modules for cassandra...
What do you prefer ?

**Comment by baskaryan** [comment]
> > Not yet as casandra_database.py has not been part of a release yet.
> 
> Well, now that 1.17 has been released, it's not true anymore 😞 . So I can keep things in cassandra_database.py. But now we have 2 utility modules for cassandra... What do you prefer ?

we should keep around a version of `cassandra_database.py` that re-exports everything it does in current version, something like
```python
from langchain_community.utilities.cassandra import CassandraDatabase

__all__ = ["CassandraDatabase"]
```

**Comment by cbornet** [comment]
I've rolled back to keep both files for the moment. We can see what to do with that later.

**Pull request merged**
