### PR TITLE
Mask PipelineAI API Key

### PR DESCRIPTION
**Pull request by faisale**
**Description:** Add masking of the API key for Mystic AI's PipelineAI when printed.
**Issue:** #12165
**Dependencies:** None
**Tag maintainer:** @eyurtsev

### CODE REVIEW

**Comment by faisale** [comment]
Is this PR still viable? I can make some changes if needed.

**Comment by baskaryan** [comment]
> Is this PR still viable? I can make some changes if needed.

you'll want to port the code over to libs/community/langchain_community. otherwise lgtm!

**Comment by faisale** [comment]
> [baskaryan](/baskaryan)

Thanks baskaryan! I'll handle this in the coming weeks.

**Review by eyurtsev — CHANGES_REQUESTED** [review]
@faisale apologies for failing to review this on time! I took a look at the code on master and it looks like a change like this has already been merged! Appreciate your contribution!

**Comment by faisale** [comment]
All good. Thanks for wrapping it up!

**Pull request closed without merging**
