### PR TITLE
 feat: Add support for the Solidity language

### PR DESCRIPTION
**Pull request by 0xJord4n**
## Add Solidity programming language support for code splitter.

Twitter: @0xjord4n_

#### Who can review?

Tag maintainers/contributors who might be interested:
@hwchase17

### CODE REVIEW

**Review by rlancemartin — COMMENTED** [review]
Thanks for the contribution! 

(1) Can you please add a short notebook with example usage in `docs/modules/indexes/text_splitters/examples/`. 
(2) Also, run `make format` (if you are set up w/ Poetry [here](https://github.com/hwchase17/langchain/blob/master/.github/CONTRIBUTING.md))*.

*I can do this for you if you are not set up for run formatting.

**Comment by rlancemartin** [comment]
Also, please run `make format` to resolve lint errors. 

LMK if you don't have poetry, etc set up and I can run for you.

**Comment by 0xJord4n** [comment]
> Also, please run `make format` to resolve lint errors.
> 
> LMK if you don't have poetry, etc set up and I can run for you.

Yes sir, I'm doing the poetry etc setup

**Comment by rlancemartin** [comment]
Thanks!

**Pull request merged**
