### PR TITLE
HuggingFaceEndpoint: Correct Example for ImportError

### PR DESCRIPTION
**Pull request by KonstantinHebenstreit**
When I try to import the Class HuggingFaceEndpoint I get an Import Error: cannot import name 'HuggingFaceEndpoint' from 'langchain'. (langchain version 0.0.88)
These two imports work fine: from langchain import HuggingFacePipeline and from langchain import HuggingFaceHub.

So I corrected the import statement in the example. There is probably a better solution to this, but this fixes the Error for me.

### CODE REVIEW

**Review by hwchase17 — APPROVED** [review]
ah perfect - will update this so it can just be `from langchain.llms import HuggingFaceEndpoint`, but thank you for flagging!

**Comment by KonstantinHebenstreit** [comment]
That is also not working in my case unfortunately...
from langchain.llms import HuggingFaceEndpoint
ImportError: cannot import name 'HuggingFaceEndpoint' from 'langchain.llms'

But again, this works: from langchain.llms import HuggingFaceHub

> ah perfect - will update this so it can just be `from langchain.llms import HuggingFaceEndpoint`, but thank you for flagging!

**Comment by hwchase17** [comment]
> That is also not working in my case unfortunately... from langchain.llms import HuggingFaceEndpoint ImportError: cannot import name 'HuggingFaceEndpoint' from 'langchain.llms'
> 
> But again, this works: from langchain.llms import HuggingFaceHub
> 
> > ah perfect - will update this so it can just be `from langchain.llms import HuggingFaceEndpoint`, but thank you for flagging!

yup will need to update the __init__ file as well

**Comment by KonstantinHebenstreit** [comment]
Changed the init file. Is there something else to be done to make it work?
For me "from langchain.llms import HuggingFaceEndpoint" works now.

**Comment by KonstantinHebenstreit** [comment]
Also changed the general init file to make "from langchain import HuggingFaceEndpoint" possible

**Review by hwchase17 — APPROVED** [review]

**Comment by hwchase17** [comment]
> Also changed the general init file to make "from langchain import HuggingFaceEndpoint" possible

im gonna remove this once its merged in actually - i actually dont want this to be possible, trying to enforce things are loaded from their modules

**Pull request merged**
