### PR TITLE
Passing the `model_kwargs` correctly while maintaing backward compatability

### PR DESCRIPTION
**Pull request by keenborder786**
- **Description:** `Model_Kwargs` was not being passed correctly to `sentence_transformers.SentenceTransformer` which has been corrected while maintaing backward compatability
- **Issue:** #28436

### CODE REVIEW

**Comment by keenborder786** [comment]
@ccurme

**Comment by keenborder786** [comment]
@ccurme

**Comment by keenborder786** [comment]
@ccurme

**Review by efriis — COMMENTED** [review]
@keenborder786  ooc do you understand why this BgeEmbeddings are a different class? Should we deprecate this integration in favor of using `langchain_huggingface.HuggingFaceEmbeddings`?

**Comment by keenborder786** [comment]
> @keenborder786 ooc do you understand why this BgeEmbeddings are a different class? Should we deprecate this integration in favor of using `langchain_huggingface.HuggingFaceEmbeddings`?

Yes, you are right, we should deprecate `HuggingFaceBgeEmbeddings` because I see no difference except for the fact certain instructions are being concatenated as a suffix to the given text which needs to be embedded. 

@efriis should I raise the deprecation warning in the same PR.

**Comment by efriis** [comment]
yes please. I would actually prefer to not modify the behavior as well just in case anyone is passing kwargs in a way they're not expecting, and folks can migrate for the correct behavior!

**Comment by keenborder786** [comment]
@efriis done

**Review by efriis — APPROVED** [review]

**Comment by sam-bercovici** [comment]
The HuggingFaceBgeEmbeddings accepts:
query_instruction = "search_query:",
embed_instruction = "search_document:"

The HuggingFaceEmbeddings does NOT accept those parameters.

How can the HuggingFaceEmbeddings used instead of HuggingFaceBgeEmbeddings

**Comment by sam-bercovici** [comment]
The HuggingFaceBgeEmbeddings accepts:
query_instruction = "search_query:",
embed_instruction = "search_document:"

The HuggingFaceEmbeddings does NOT accept those parameters.

How can the HuggingFaceEmbeddings used instead of HuggingFaceBgeEmbeddings

**Pull request merged**
