### PR TITLE
core: Fix incorrect load of chat prompt from configuration file

### PR DESCRIPTION
**Pull request by DougTrajano**
In this PR, we are fixing an issue when loading LLMChain from a config or file. I detected this issue when I was logging a LLMChain in the Databricks MLflow Model Registry.

<details>
  <summary>Code to reproduce the error</summary>

```python
import mlflow
import mlflow.langchain
from langchain.chains import LLMChain
from langchain_community.chat_models import ChatDatabricks
from langchain.output_parsers.json import StrOutputParser
from langchain.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate
)

SYSTEM_PROMPT = "You are an AI Assistant."

message = "What is the Databricks?"

prompt_template = ChatPromptTemplate(
    messages=[
        SystemMessagePromptTemplate.from_template(SYSTEM_PROMPT),
        HumanMessagePromptTemplate.from_template("{message}"),
    ]
)

llm = ChatDatabricks(
    endpoint="gpt4-chat",
    temperature=0.7
)

chain = LLMChain(
    llm=llm,
    prompt=prompt_template,
    output_parser=StrOutputParser()
)

with mlflow.start_run():
    logged_model = mlflow.langchain.log_model(
        chain,
        artifact_path="model",
        input_example={"message": message},
        pip_requirements=[
            "langchain==0.1.5",
            "langchain-community==0.0.17",
            "langchain-core==0.1.18",
            "langchain-openai==0.0.5",
            "mlflow==2.10.0"
        ]
    )
```

</details>

The current logic of `_load_chat_prompt()` loads only the first message and always as a human message, since it uses `ChatPromptTemplate.from_template()`, which accepts only one message and assumes that it comes from a human. It's questioned in the PR that introduced the `_load_chat_prompt()` https://github.com/langchain-ai/langchain/pull/13818#issuecomment-1839665503

My proposed solution includes an attribute named `type` in these classes:

- `HumanMessagePromptTemplate`
- `AIMessagePromptTemplate`
- `SystemMessagePromptTemplate`

This attribute will be saved in the config file when calling `LLMChain.save()` function, and we will use it in the `_load_chat_prompt()` function to mount a defined message format `(user_type, message)`.

My proposed solution produces the following `model.yaml`:

As you can see, we have a field `type` in each message value.

```yaml
_type: llm_chain
llm:
  _type: databricks-chat
  endpoint: gpt4-chat
  extra_params: {}
  max_tokens: null
  n: 1
  stop: null
  target_uri: databricks
  temperature: 0.7
llm_kwargs: {}
memory: null
metadata: null
name: null
output_key: text
output_parser:
  _type: simple_json_output_parser
  diff: false
  name: null
prompt:
  _type: chat
  input_types: {}
  input_variables:
  - comment
  messages:
  - additional_kwargs: {}
    prompt:
      _type: prompt
      input_types: {}
      input_variables: []
      name: null
      output_parser: null
      partial_variables: {}
      template: "You are an AI Assistant."
      template_format: f-string
      validate_template: false
    type: system
  - additional_kwargs: {}
    prompt:
      _type: prompt
      input_types: {}
      input_variables:
      - comment
      name: null
      output_parser: null
      partial_variables: {}
      template: '{comment}'
      template_format: f-string
      validate_template: false
    type: human
  name: null
  output_parser: null
  partial_variables: {}
  validate_template: false
return_final_only: true
tags: null
verbose: false
```

### CODE REVIEW

**Comment by DougTrajano** [comment]
@baskaryan

**Comment by DougTrajano** [comment]
@baskaryan, @eyurtsev, @hwchase17

**Comment by DougTrajano** [comment]
@efriis @eyurtsev can you review this PR?

**Review by baskaryan — COMMENTED** [review]
prompts can be seralized and loaded using 

```python
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.load import dumpd
from langchain_core.load.load import load
import json

prompt = ChatPromptTemplate.from_template("foo {bar}")
with open("foo.json", "w") as f:
  json.dump(dumpd(prompt), f)
with open("foo.json", "r") as f:
  reloaded = load(json.load(f))
```

**Comment by DougTrajano** [comment]
> prompts can be seralized and loaded using
> 
> ```python
> from langchain_core.prompts import ChatPromptTemplate
> from langchain_core.load import dumpd
> from langchain_core.load.load import load
> import json
> 
> prompt = ChatPromptTemplate.from_template("foo {bar}")
> with open("foo.json", "w") as f:
>   json.dump(dumpd(prompt), f)
> with open("foo.json", "r") as f:
>   reloaded = load(json.load(f))
> ```

It doesn't work when using [mlflow.langchain](https://mlflow.org/docs/latest/_modules/mlflow/langchain.html) flavor as it uses [langchain.chains.loading.load_chain()](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/loading.py#L589-L596) to load the entire chain, not the prompts isolated.

**Comment by DougTrajano** [comment]
@baskaryan you can reproduce the behavior by running the following code:

```python
import os
from langchain.chains import LLMChain
from langchain_openai import OpenAI
from langchain.prompts import (
    SystemMessagePromptTemplate,
    ChatPromptTemplate,
    HumanMessagePromptTemplate
)

import mlflow

# Ensure the OpenAI API key is set in the environment
assert "OPENAI_API_KEY" in os.environ, "Please set the OPENAI_API_KEY environment variable."

# Initialize the OpenAI model and the prompt template
llm = OpenAI(temperature=0.9)
prompt = ChatPromptTemplate(
    messages=[
        SystemMessagePromptTemplate.from_template("You are a helpful AI assistant."),
        HumanMessagePromptTemplate.from_template("What is a good name for a company that makes {product}?")
    ]
)

# Create the LLMChain with the specified model and prompt
chain = LLMChain(llm=llm, prompt=prompt)

print(f"Chain before training: {chain}")

# Log the LangChain LLMChain in an MLflow run
with mlflow.start_run():
    logged_model = mlflow.langchain.log_model(chain, "langchain_model")

# Load the logged model using MLflow's Python function flavor
loaded_model = mlflow.langchain.load_model(logged_model.model_uri)

print(f"Loaded model: {loaded_model}")
```

Output:

> Chain before training: prompt=ChatPromptTemplate(input_variables=['product'], messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], template='You are a helpful AI assistant.')), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['product'], template='What is a good name for a company that makes {product}?'))]) llm=OpenAI(client=<openai.resources.completions.Completions object at 0x0000010519A00E90>, async_client=<openai.resources.completions.AsyncCompletions object at 0x0000010519A15750>, temperature=0.9, openai_api_key=SecretStr('**********'), openai_proxy='')

> 
> Loaded model: prompt=ChatPromptTemplate(input_variables=[], messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], template='You are a helpful AI assistant.'))]) llm=OpenAI(client=<openai.resources.completions.Completions object at 0x0000010519A19A50>, async_client=<openai.resources.completions.AsyncCompletions object at 0x0000010519A76A90>, temperature=0.9, openai_api_key='sk-foo', openai_proxy='')

As you can see, I am fixing two issues:

- Incorrectly load of Prompt type.
- Only load the first prompt message.

**Review by baskaryan — COMMENTED** [review]
could we add a unit test?

**Comment by DougTrajano** [comment]
> could we add a unit test?

Yeap, I added it.

**Comment by DougTrajano** [comment]
Hi @baskaryan there's something else from my side?

**Comment by DougTrajano** [comment]
@baskaryan ping

**Comment by hwchase17** [comment]
sorry for the delay here. there is a new preffered serialization method that relies on things being Serializable, that is the prefered method going forward. if this is a blocker, please reach out directly, would love to learn more

**Pull request closed without merging**
