### PR TITLE
Parnters: Using `embed_with_retry` and `async_embed_with_retry` for OpenAI Embedding

### PR DESCRIPTION
**Pull request by keenborder786**
- **Description:** As the issue points out, the attributes `retry_max_seconds` and `retry_min_seconds` are not being used in `OpenAIEmbebeddings` in `langchain_openai` partners package like they are being used in deprecated version of `OpenAIEmbebeddings`. Therefore I have switched the invocation of embedding through same function as in the deprecated version of `OpenAIEmbebeddings` which is through `embed_with_retry` and `async_embed_with_retry`.
- **Issue:**  #26084

### CODE REVIEW

**Comment by keenborder786** [comment]
@efriis

**Comment by efriis** [comment]
I believe this was removed intentionally when openai released their v1 sdk, which had retries for common errors built-in: https://github.com/openai/openai-python/tree/93aa548201af70646fe651cc01fd875f32b00202?tab=readme-ov-file#retries

Could you confirm this functionality makes sense? If so can add a comment to the attributes clarifying that those retries are handled internally

**Comment by keenborder786** [comment]
@efriis sure let me check

**Comment by keenborder786** [comment]
@efriis you are right, no need .

**Comment by efriis** [comment]
great thanks for checking!

**Pull request closed without merging**
