### PR TITLE
fixed a concurrency bug in abatch

### PR DESCRIPTION
**Pull request by lkuligin**
Replace this entire comment with:
  - **Description:** made `abatch` actually concurrent 
  - **Issue:** it processed batch sequentially before

### CODE REVIEW

**Comment by eyurtsev** [comment]
@lkuligin thanks for catching! Any chance you could add a unit test?

**Comment by lkuligin** [comment]
> @lkuligin thanks for catching! Any chance you could add a unit test?

yes, will do!

**Comment by nfcampos** [comment]
hi folks, I think this is on purpose, to respect max_concurrency param, otherwise no matter what value gets sent it always runs as many in parallel as possible

**Comment by lkuligin** [comment]
@nfcampos ok, thanks, it makes sense now :).
I've added a comment and made it aligned with how ChatModels are implemented. But it's a minor change then.

**Comment by nfcampos** [comment]
Hi @lkuligin thanks for this! This is actually on purpose as LLMs have a custom batch method called generate which does a single api call for supported LLMs whereas this doesn't exist for chat models. That's why the implementations are different.

**Pull request closed without merging**
