### PR TITLE
docs[callbacks]: update to callbacks documentation

### LINKED ISSUE #19361: Document on_retriever_x callbacks
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Callbacks are a bit out of date: https://python.langchain.com/docs/modules/callbacks/

We need to document updates in the supported callbacks

### PR DESCRIPTION
**Pull request by sepiatone**
**Description:** Update to the Callbacks documentation
**Issue:** fixes #19361, and partially #16379 #20493
**Dependencies:** None

### CODE REVIEW

**Comment by sepiatone** [comment]
@eyurtsev 
* listed out the events in a table (rather than a pseudo-code listing).
* changed the examples to follow lcel
* added support in the `StdOutCallbacksHandler` for events `on_llm_start`, `on_llm_end`, `on_retriever_start` and `on_retriever_end`
* added an example for setting a callback with a retriever
* changed the flow (i've used the tools page as a guide)

-- --

* please check the lcel examples
* i'm not sure how to set the `verbose=True` option

**Comment by eyurtsev** [comment]
Thank you! Looks good overall. I'll need to test out the stdout error changes since there are no unit tests included and update the constructor arguments. We generally want to discourage users from using them since they are non-inheritable. Likely merge time is tomorrow.

**Comment by eyurtsev** [comment]
@sepiatone I made the following changes:

1) i updated the information about constructor vs. request time callbacks since that's a source of confusion to a lot of users. 
2) remove the changes from the standard output handler (not needed for this PR). If we want to update it, we can do it, but we should add unit tests etc
3) replaced with the callback handler used in set_debug which has a lot more output by default

**Comment by eyurtsev** [comment]
I'll double check it renders nicely and then will merge if all looks good

**Comment by eyurtsev** [comment]
New concepts here: https://github.com/langchain-ai/langchain/pull/22040

**Comment by eyurtsev** [comment]
Closing in favor of the new callback concepts. Copied over relevant content! Thank you @sepiatone

**Pull request closed without merging**
