### PR TITLE
OpenAI functions dont work with async streaming... #6225

### LINKED ISSUE #6225: OpenAI functions dont work with async streaming...
### System Info

Version: 0.0.200

### Who can help?

@hwchase17 , @agola11 
- I have a PR ready ... creating an issue so I can pair it

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

...
openai.py
 async def _agenerate( ...

has different implementation than def generate...

when running the chain with `acall` >> 
1. fails on 
inner_completion += token  # token is null, raises error

and after fix the function call was not captured...

### Expected behavior

the same as `generate`

### PR DESCRIPTION
**Pull request by ju-bezdek**
Related to this https://github.com/hwchase17/langchain/issues/6225

Just copied the implementation from `generate` function to `agenerate` and tested it.

Didn't run any official tests thought

Fixes #6225

#### Who can review?

Tag maintainers/contributors who might be interested:
  @hwchase17, @agola11

### CODE REVIEW

**Review by hwchase17 — APPROVED** [review]
thanks!

**Comment by gbrlmtrz** [comment]
I just cam to open this same issue. I am to see someone already came with a solution. Do we have an ETA for release?

**Comment by ju-bezdek** [comment]
Couldnt get peotry working on my machine to run the formatting ... finally got it working... not sure whether I followed the right workflow right now, but the formatting is fixed (literally just different spacing) and the tests passed

**Comment by vesper8** [comment]
Also waiting for this to be merged.. hopefully soon!

**Review by hwchase17 — APPROVED** [review]
thanks!

**Pull request merged**
