### PR TITLE
Update token number calculation method for GPT-3.5 and GPT-4

### PR DESCRIPTION
**Pull request by Aratako**
The official documentation has been updated to support token counting for GPT-4.
https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb

I have made changes to `get_num_tokens_from_messages` function.
With this update, the model name is now passed as an argument when calling the function. For non-OpenAI language models, where the `model_name` parameter is not present, an empty string is passed instead (and not used).

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
since `get_num_tokens_from_messages` is on the llm, cant we jsut use `self.model_name` internally to the llm?

**Comment by Aratako** [comment]
> since `get_num_tokens_from_messages` is on the llm, cant we jsut use `self.model_name` internally to the llm?

Thank you. You're absolutely right. When the `model` is not passed as an argument to the `get_num_tokens_from_message` function, it's better to use `model = self.model_name` as the default value, and if it's passed, use that `model` instead, which would make the code simpler.
I'm currently on a business trip and won't be able to make the changes for about two days, but if it's okay later, I'll make the changes myself. Alternatively, you can make the changes there if you prefer.

**Comment by Aratako** [comment]
I have made changes to the implementation according to your comments. Is this okay now?

**Review by rtwfroody — COMMENTED** [review]
Should get_num_tokens() be updated in a similar way?

**Pull request merged**
