### PR TITLE
Fix SelfAskOutputParser (from langchain.agents.self_ask_with_search.output_parser)

### PR DESCRIPTION
**Pull request by jeanbaptistepriez**
# Description of the change

By replacing hard coded position of "follow up" and "final output" pattern with regex pattern matching using "re" I reduce failed outputs like markdown list or any multiline outputs

Example of the issue:
```
from langchain import OpenAI, SerpAPIWrapper
from langchain.agents import initialize_agent, Tool
from langchain.agents import AgentType

llm = OpenAI(temperature=0)
search = SerpAPIWrapper()
tools = [
    Tool(
        name="Intermediate Answer",
        func=search.run,
        description="useful for when you need to ask with search",
    )
]

self_ask_with_search = initialize_agent(
    tools, llm, agent=AgentType.SELF_ASK_WITH_SEARCH, verbose=True
)
out = self_ask_with_search.run(
    "List men and women Rolland Garros winners between 2020 and 2023?"
)
-------------------------
> Entering new AgentExecutor chain...
 Yes.
Follow up: Who won the men's Rolland Garros in 2020?
Intermediate answer: Three-time defending champion Rafael Nadal defeated Novak Djokovic in the final, 6–0, 6–2, 7–5 to win the men's singles tennis title at the 2020 French Open.

Follow up: Who won the women's Rolland Garros in 2020?
Intermediate answer: Iga Świątek defeated Sofia Kenin in the final, 6–4, 6–1 to win the women's singles tennis title at the 2020 French Open.

Follow up: Who won the men's Rolland Garros in 2021?
Intermediate answer: Novak Djokovic defeated Stefanos Tsitsipas in the final, 6–7(6–8), 2–6, 6–3, 6–2, 6–4 to win the men's singles tennis title at the 2021 French Open.

Follow up: Who won the women's Rolland Garros in 2021?
Intermediate answer: Barbora Krejčíková defeated Anastasia Pavlyuchenkova in the final, 6–1, 2–6, 6–4 to win the women's singles tennis title at the 2021 French Open.

Follow up: Who won the men's Rolland Garros in 2022?
Intermediate answer: Rafael Nadal defeated Casper Ruud in the final, 6–3, 6–3, 6–0 to win the men's singles tennis title at the 2022 French Open. It was his record-extending ...

Follow up: Who won the women's Rolland Garros in 2022?
Intermediate answer: Iga Świątek defeated Coco Gauff in the final, 6–1, 6–3 to win the women's singles tennis title at the 2022 French Open. It was her second French Open title, ...

Follow up: Who won the men's Rolland Garros in 2023?
Intermediate answer: Novak Djokovic defeated Casper Ruud in the final, 7–6(7–1), 6–3, 7–5 to win the men's singles tennis title at the 2023 French Open. It was his third French ...

Follow up: Who won the women's Rolland Garros in 2023?
Intermediate answer: World number one Iga Swiatek clinched her third French Open and fourth Grand Slam title of her career on Saturday with an epic three-set ...
---------------------------------------------------------------------------
OutputParserException                     Traceback (most recent call last)
...
File /usr/local/Caskroom/miniconda/base/envs/py_3_10/lib/python3.10/site-packages/langchain/agents/self_ask_with_search/output_parser.py:17, in SelfAskOutputParser.parse(self, text)
     15 if not any([follow in last_line for follow in self.followups]):
     16     if self.finish_string not in last_line:
---> 17         raise OutputParserException(f"Could not parse output: {text}")
     18     return AgentFinish({"output": last_line[len(self.finish_string) :]}, text)
     20 after_colon = text.split(":")[-1].strip()

OutputParserException: Could not parse output: So the final answer is: 
2020: Men's - Rafael Nadal, Women's - Iga Świątek 
2021: Men's - Novak Djokovic, Women's - Barbora Krejčíková 
2022: Men's - Rafael Nadal, Women's - Iga Świątek 
2023: Men's - Novak Djokovic, Women's - Iga Świątek
```

Using regex matching now we obtain a correct answer:

```
> Entering new AgentExecutor chain...
 Yes.
Follow up: Who won the men's singles at the 2020 French Open?
Intermediate answer: Rafael Nadal
Follow up: Who won the women's singles at the 2020 French Open?
Intermediate answer: Iga Swiatek
Follow up: Who won the men's singles at the 2021 French Open?
Intermediate answer: Novak Djokovic
Follow up: Who won the women's singles at the 2021 French Open?
Intermediate answer: Barbora Krejčíková
Follow up: Who won the men's singles at the 2022 French Open?
Intermediate answer: Rafael Nadal
Follow up: Who won the women's singles at the 2022 French Open?
Intermediate answer: Iga Swiatek
Follow up: Who won the men's singles at the 2023 French Open?
Intermediate answer: Novak Djokovic
Follow up: Who won the women's singles at the 2023 French Open?
Intermediate answer: Iga Swiatek
So the final answer is: 
2020: Rafael Nadal (men's singles) and Iga Swiatek (women's singles)
2021: Novak Djokovic (men's singles) and Barbora Krejčíková (women's singles)
2022: Rafael Nadal (men's singles) and Iga Swiatek (women's singles)
2023: Novak Djokovic (men's singles) and Iga Swiatek (women's singles)

> Finished chain.
```

### CODE REVIEW

**Comment by baskaryan** [comment]
thanks @jeanbaptistepriez! could we add some unit tests for this?

**Comment by jeanbaptistepriez** [comment]
> thanks @jeanbaptistepriez! could we add some unit tests for this?

Unit tests have been added (but I'm not able to execute `make test` I obtain multiple issues not linked to those new tests => those new tests are working using `pytest` in the dedicated folder).

**Comment by jeanbaptistepriez** [comment]
@baskaryan any update?

**Comment by leo-gan** [comment]
@jeanbaptistepriez Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by efriis** [comment]
Looks like this isn't being worked on anymore. I'll close for now, and if you resume work, feel free to reopen!

@jeanbaptistepriez if you're having trouble setting up unit testing locally, feel free to ask for help in Discord or try running them in docker! https://github.com/langchain-ai/langchain/blob/master/.github/CONTRIBUTING.md#testing

**Pull request closed without merging**
