### PR TITLE
- Pubmed integration

### PR DESCRIPTION
**Pull request by ybshr**
This pull request adds the Pubmed integration to LangChain. The Pubmed integration allows users to retrieve scientific publications and related metadata from the Pubmed database.

The integration includes the following changes:
- Implemented a Pubmed API client to communicate with the Pubmed database.
- Added a new module, pubmed.py, to handle Pubmed-specific functionality.
- Created functions to search for publications based on keywords, retrieve publication details by PMID (Pubmed ID), and fetch related metadata.

This integration enhances the capabilities of LangChain by enabling users to access a wide range of scientific publications and leverage the Pubmed database's extensive resources. Researchers, students, and anyone interested in the scientific literature can benefit from this integration to gather valuable information and incorporate it into their natural language processing tasks.

I have followed the guidelines provided by the LangChain project, including formatting, and lining. The code has been thoroughly reviewed to ensure its quality and adherence to project standards.

Please review this pull request and let me know if any further changes or additions are required. I am open to feedback and eager to collaborate with the LangChain team to incorporate the Pubmed integration into the project.

Thank you for considering this contribution!

Best regards,
Younis Bashir

### CODE REVIEW

**Comment by eyurtsev** [comment]
@younis-ba thank you! This is fantastic! Do you happen to have any sample data? Ideally we can get as much test coverage around the internal python massaging code (i.e., everything but the web request); e.g., parsing XML or JSON response from the pub med web server

**Comment by eyurtsev** [comment]
@hwchase17 This is a fantastic feature. Is there any organization for tools? Do we have a set of core tools vs. integration tools?

**Comment by younis-ba** [comment]
@eyurtsev You're welcome! I'm glad you liked it! 


I have implemented the test script following the structure of the `Arxiv`  tool. Please review it and provide your feedback.

Regarding this notebook 
https://github.com/younis-ba/LangChain/blob/main/langchain.ipynb, when integrating the Pubmed functionality, 

I will collect  XML and JSON responses from the pub med web server that can help improve the test coverage of the internal Python massaging code. These samples cover different scenarios and serve as valuable test cases.

If you have any further questions or need assistance with reviewing the test script or the notebook URL implementation, please let me know. I'm here to help!

**Comment by hwchase17** [comment]
this looks pretty good! the only thing left is to add example notebooks - probably one in tools, one in retrievers. could you add?

**Pull request merged**
