### PR TITLE
docs: `document_transformers` consistency

### PR DESCRIPTION
**Pull request by leo-gan**
- Updated `document_transformers` examples: titles, descriptions, links
- Added `integrations/providers` for missed document_transformers

### CODE REVIEW

**Comment by leo-gan** [comment]
@baskaryan Could you, please, review it?

**Comment by leo-gan** [comment]
@hwchase17  Could you, please, review it?

**Comment by leo-gan** [comment]
@baskaryan Could you, please, review it?

**Comment by leo-gan** [comment]
@hwchase17 Could you, please, review it?
# testing this messaging. 95% probability that these messages are lost

**Review by hwchase17 — APPROVED** [review]
thanks

**Pull request merged**
