### PR TITLE
Support for Vertex AI MedLM models

### PR DESCRIPTION
**Pull request by dingusagar**
Thank you for contributing to LangChain!

- [ ] **Support for Vertex AI MedLM models*: "langchain: support for medlm-large model in langchain"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [ ] **PR message**: ***Delete this entire checklist*** and replace with
    - **Description:** a description of the change
    - **Issue:** the issue # it fixes, if applicable
    - **Dependencies:** langchain-google-vertexai
    - **Twitter handle:** @dingusagar

- [ ] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [ ] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Comment by dingusagar** [comment]
Relates to the issue here https://github.com/langchain-ai/langchain-google/issues/231

**Comment by baskaryan** [comment]
all langchain + google integrations now live in the https://github.com/langchain-ai/langchain-google repo, can we open this pr against the packages there?

**Comment by lkuligin** [comment]
+1, please, re-open this PR, and I don't think we need a separate instance for this, it works well with existing `ChatVertexAI` models.

**Comment by ccurme** [comment]
Closing as this is better implemented in [langchain-google](https://github.com/langchain-ai/langchain-google) (let me know if I've misunderstood the discussion here).

**Pull request closed without merging**
