### PR TITLE
Modifying generations.append to solve problem with OpenLLM

### LINKED ISSUE #9923: LangChain cannot deal with new OpenLLM Version (0.2.27)
### System Info

LangChain: 0.0.275
OpenLLM: 0.2.27
Python: 3.11.1

on Ubuntu 22.04 / Windows 11

### Who can help?

@agola11, @hwchase17

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### On the server side:
1. `conda create --name openllm python=3.11`
2. `conda activate openllm`
3. `pip install openllm`
4. `openllm start llama --model_id meta-llama/Llama-2-13b-chat-hf`

### On the client side / my local machine:
1. `conda create --name openllm python=3.11`
2. `conda activate openllm`
3. `pip install openllm`
4. Execute the following script:

```python
from langchain.llms import OpenLLM

llm = OpenLLM(server_url='http://<server-ip>:3000')
print(llm("What is the difference between a duck and a goose?"))
```

Then, the following error comes up (similar scripts produce the same error):
```bash
File "C:\Users\<User>\.virtualenvs\<env-name>-wcEN-LyC\Lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)
```

I could solve the error manually by adapting `langchain/llms/base.py` at line 985 to the following line:
```python
generations.append([Generation(text=text["text"], generation_info=text)])
```

### Expected behavior

I would expect, the provided example script works fine, successfully requests text generation from the deployed server, and returns that text to the user / program.

### PR DESCRIPTION
**Pull request by victorleaoo**
# Description

Added the generation_info=text in the generations.append on the _generate function, to fix generation with OpenLLM model deployment.

# Issue

Fix: https://github.com/langchain-ai/langchain/issues/9923

# Twitter

@vitinleao1

### CODE REVIEW

**Comment by baskaryan** [comment]
sounds like the problem is with OpenLLM not with the LLM base class. OpenLLM._call should be returning a string not a dict, we should update that. something like editing libs/langchain/llms/open_llm.py L267-271 to be
```python
        if self._client:
            result = self._client.query(prompt, **config.model_dump(flatten=True))
        else:
            assert self._runner is not None
            result = self._runner(prompt, **config.model_dump(flatten=True))
        if isinstance(result, str):
            return result
        elif isinstance(result, dict) and "text" in result:
            return result["text"]
        else:
            raise ValueError(f"Expected result to be str or dict, got {result}."
```

or if it's known that result is always dict then we don't need the dict check. cc @aarnphm

**Comment by aarnphm** [comment]
Hey there, I have recently update the one-shot generation to return dictionary, and I was about to also make a PR to update this on LangChain.

I will take a look this for the PR @victorleaoo

**Comment by aarnphm** [comment]
I think this is best to update the implementation on openllm instead of changing it in base.

I will create a PR for this

**Comment by baskaryan** [comment]
fixed in #10523, thank you @victorleaoo and @aarnphm!

**Pull request closed without merging**
