### PR TITLE
align chroma vectorstore get with chromadb to enable where filtering

### PR DESCRIPTION
**Pull request by ChrisPappalardo**
allows for where filtering on collection via get

  - Description: aligns langchain chroma vectorstore get with underlying [chromadb collection get](https://github.com/chroma-core/chroma/blob/main/chromadb/api/models/Collection.py#L103) allowing for where filtering, etc.
  - Issue: NA
  - Dependencies: none
  - Tag maintainer: @rlancemartin, @eyurtsev
  - Twitter handle: @pappanaka

### CODE REVIEW

**Review by hwchase17 — APPROVED** [review]
thanks!

**Comment by ChrisPappalardo** [comment]
> thanks!

You bet.  I just fixed the chromadb typing imports that were causing linting errors.

**Review by rlancemartin — COMMENTED** [review]
Thanks! Maybe you should add an example of where filter to [the notebook](https://github.com/rlancemartin/langchain/blob/master/docs/extras/modules/data_connection/vectorstores/integrations/chroma.ipynb)?

**Comment by rlancemartin** [comment]
Also, please run `make format` to resolve Lint error. LMK if problems, and I can help w/ that.

**Comment by ChrisPappalardo** [comment]
@rlancemartin Done.  Let me know if you want me to squash these commits.

**Comment by ChrisPappalardo** [comment]
Both ```make format``` and ```poetry run ruff .``` now pass without issues.

**Pull request merged**
