### PR TITLE
Add concurrent insertion of vector rows in the Cassandra Vector Store

### PR DESCRIPTION
**Pull request by hemidactylus**
Using the newest `cassIO`, the Cassandra Vector Store can now perform concurrent DB insertion in its `add_texts` method, hence improving its performance.

#### Linter unrelated errors

Running the linter, the following (likely unrelated) was observed:

```
langchain/vectorstores/mongodb_atlas.py:137: error: Argument 1 to "insert_many" of "Collection" has incompatible type "List[Dict[str, Sequence[object]]]"; expected "Iterable[Union[MongoDBDocumentType, RawBSONDocument]]"  [arg-type]
langchain/vectorstores/mongodb_atlas.py:186: error: Argument 1 to "aggregate" of "Collection" has incompatible type "List[object]"; expected "Sequence[Mapping[str, Any]]"  [arg-type]
langchain/vectorstores/qdrant.py: error: Name "grpc" is not defined  [name-defined]
```

Happy to be pointed at a fix, if the above is somehow caused by the code in this PR!

### CODE REVIEW

**Comment by hemidactylus** [comment]
This last commit adapts the Cassandra Vector Store to the newest cassIO library, which introduces a few improvements (including interface changes). Also the `delete` method is implemented.
Moreover, an important non-deterministic source of trouble is identified and healed in the associated integration test (related to the MMR search test). There, test coverage is also extended to the `delete` methods.

Sorry about the `poetry.lock` conflict :(

**Comment by jbellis** [comment]
@rlancemartin could you take a look at this Cassandra followup?

**Comment by jbellis** [comment]
Rebased.  But when trying to run tests I get

```
$ poetry run pytest tests/integration_tests/vectorstores/test_cassandra.py 
Warning: Found deprecated key 'default' or 'secondary' in pyproject.toml configuration for source azure-sdk-dev. Please provide the key 'priority' instead. Accepted values are: 'default', 'primary', 'secondary', 'supplemental', 'explicit'.
Warning: Found deprecated priority 'secondary' for source 'azure-sdk-dev' in pyproject.toml. Consider changing the priority to one of the non-deprecated values: 'default', 'primary', 'supplemental', 'explicit'.
Warning: In a future version of Poetry, PyPI will be disabled automatically if at least one custom source is configured with another priority than 'explicit'. In order to avoid a breaking change and make your pyproject.toml forward compatible, add PyPI explicitly via 'poetry source add pypi'. By the way, this has the advantage that you can set the priority of PyPI as with any other source.
ImportError while loading conftest '/home/jonathan/Projects/langchain/tests/integration_tests/vectorstores/conftest.py'.
tests/integration_tests/vectorstores/conftest.py:7: in <module>
    from langchain.document_loaders import TextLoader
langchain/__init__.py:6: in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
langchain/agents/__init__.py:2: in <module>
    from langchain.agents.agent import (
langchain/agents/agent.py:16: in <module>
    from langchain.agents.tools import InvalidTool
langchain/agents/tools.py:4: in <module>
    from langchain.callbacks.manager import (
langchain/callbacks/__init__.py:11: in <module>
    from langchain.callbacks.manager import (
langchain/callbacks/manager.py:35: in <module>
    from langchain.callbacks.tracers.langchain import LangChainTracer
langchain/callbacks/tracers/__init__.py:3: in <module>
    from langchain.callbacks.tracers.langchain import LangChainTracer
langchain/callbacks/tracers/langchain.py:11: in <module>
    from langchainplus_sdk import LangChainPlusClient
E   ModuleNotFoundError: No module named 'langchainplus_sdk'
```

Am I doing it wrong?

**Comment by jbellis** [comment]
Test problem was due to me not re-running `poetry install`

**Comment by rlancemartin** [comment]
> Test problem was due to me not re-running `poetry install`

Glad you figured it out! I just kicked off tests.

**Review by rlancemartin — APPROVED** [review]

**Comment by rlancemartin** [comment]
@jbellis please run `make format` to resolve Lint error.

**Comment by hemidactylus** [comment]
@rlancemartin Hello, the linter/code style should be happy now :)

**Comment by rlancemartin** [comment]
Thanks! Do you mind doing this -

1/ sync for your fork w/ `master`
2/ on master, update with `git pull`
3/ on your branch: `git checkout master poetry.lock`
4/ then `poetry lock --no-update`

Looks like recent updates to `pyproject.toml / poetry.lock` are going in, which is making review / testing painful :) 

I'm seeing repeated merge conflicts on other PRs that are modifying `pyproject.toml`.

**Comment by rlancemartin** [comment]
The repeated conflict with `poetry.lock` is odd. My local master was up-to-date after 6728 went it, but I still saw this merge conflict reported in the PR after re-generating `poetry.lock`. It looks like you might be creating a new branch? Tag me on that and we should be able to get this in shortly.

**Comment by hemidactylus** [comment]
@rlancemartin Sorry, I might have inadvertently done something untoward.
I wanted to sync my fork to upstream (including this branch), saw conflicts in the github UI and went with a force reset of upstream. That was a few minutes ago.
I think I zapped away the very content of this PR (looking at the code).

**Comment by rlancemartin** [comment]
No problem. You should have the branch locally, and can force push your local branch to recover all.

**Comment by hemidactylus** [comment]
Thank you! I actually did a git reset --hard on my pc but @jbellis  will do the forcepush in a few minutes. Sorry about this and thank you for helping!

**Comment by jbellis** [comment]
I pushed it back to where I left it yesterday after the reformat.  Doesn't look like that is showing up on this PR page but I confirmed that the branch at https://github.com/hemidactylus/langchain/tree/SL-cassandra-vectorstore-2 is where it should be.

**Comment by hemidactylus** [comment]
@rlancemartin  perhaps the PR should be re-opened somehow? I see "no new commits" so I cannot reopen with this comment (yet the branch is restored).

**Comment by rlancemartin** [comment]
> @rlancemartin perhaps the PR should be re-opened somehow? I see "no new commits" so I cannot reopen with this comment (yet the branch is restored).

Hmm there are still no commits?

**Comment by hemidactylus** [comment]
Thank you, I went with the "new PR" option (#7017). Thank you again!

**Pull request closed without merging**
