### PR TITLE
adding argument support for SupabaseVectorStore's postgres functions.

### PR DESCRIPTION
**Pull request by aHardReset**
- **Description:** `SupabaseVectorStore` has some limitations using postgres functions since is limited to a function with only one parameter `query_embedding`, this PR intends to add as many arguments as you need, hence allowing to create functions with other parameters than `query_embedding`,  this PR also allows the use of `postgres_filter` from `SupabaseVectorStore`.
Usage
```python
vector_store = SupabaseVectorStoreMixin(embedding=embeddings, client=supabase, table_name="document", query_name="match_documents_mmr")
matched_docs = vector_store.max_marginal_relevance_search(query, k=2, fetch_k=5, sql_fn_args={
    "stack": "python", # stack is a parameter in the supabase postgres' function.
})
```
  - **Issue:** #10994 ,
  - **Dependencies:** None,
  - **Tag maintainer:** for a quicker response, tag the relevant maintainer (see below),
  - **Twitter handle:** AHardReset

### CODE REVIEW

**Comment by baskaryan** [comment]
cc @gregnr

**Comment by gregnr** [comment]
Nice one @aHardReset! A couple things I noticed:
- Removing `filter` from those methods would be a breaking change for anyone using them. Do we have a strategy around breaking changes @baskaryan?
- `postgrest_filter` (with the `t`) wasn't a typo - it refers to filters passed to the [PostgREST API](https://postgrest.org/en/stable/references/api/tables_views.html) which Supabase uses to interface with the database
- We should probably document this change

Otherwise LGTM, will be good to provide more flexibility to the vector store 👍

**Comment by baskaryan** [comment]
> Nice one @aHardReset! A couple things I noticed:
> 
> * Removing `filter` from those methods would be a breaking change for anyone using them. Do we have a strategy around breaking changes @baskaryan?
> * `postgrest_filter` (with the `t`) wasn't a typo - it refers to filters passed to the [PostgREST API](https://postgrest.org/en/stable/references/api/tables_views.html) which Supabase uses to interface with the database (and used by the [self-querying retriever](https://github.com/langchain-ai/langchain/blob/b4354b769442fb94a700abc02a18c2bffb1fa806/libs/langchain/langchain/retrievers/self_query/supabase.py))
> * We should probably document this change
> 
> Otherwise LGTM, will be good to provide more flexibility to the vector store 👍

strong preference to avoid breaking changes except where really needed

**Comment by baskaryan** [comment]
Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

**Comment by aHardReset** [comment]
@baskaryan I don't remember what I did here. Feel free to close it.

**Pull request closed without merging**
