### PR TITLE
partners[anthropic]: update docstring of the ChatAnthropic and AnthropicLLM classes

### PR DESCRIPTION
**Pull request by sepiatone**
**Description:** Update docstring of the ChatAnthropic and AnthropicLLM classes
**Issue:** Not applicable
**Dependencies:** None

### CODE REVIEW

**Comment by sepiatone** [comment]
update with changes after pr review of a similar change langchain-ai/langchain#18637

**Comment by sepiatone** [comment]
update - add a model name in the call to ChatAnthropic() based on review comment received for langchain-ai/langchain#18868

**Comment by sepiatone** [comment]
@efriis 

please review this pr when convenient

**Comment by sepiatone** [comment]
@efriis  Please review this pr. The change is minor but it (slightly) improves the usability of the system.

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
