### PR TITLE
Vectara summarization

### PR DESCRIPTION
**Pull request by ofermend**
- **Description:** Adding Summarization to Vectara, to reflect it provides not only vector-store type functionality but also can return a summary. 
Also added:
* MMR capability (in the Vectara platform side)
* Updated templates
* Updated documentation and IPYNB examples

  - **Tag maintainer:** @baskaryan
  - **Twitter handle:** @ofermend

### CODE REVIEW

**Comment by efriis** [comment]
Yes! If you merge in master, you'll notice most of these files have moved to the langchain-community lib. If you could merge that in (it's all in master), that would be great!

More info if curious: https://github.com/langchain-ai/langchain/discussions/14243

**Comment by ofermend** [comment]
Okay let me merge master in, move things around, and I'll test everything then update the PR
I noticed that self-query vectara remains in the original location - does that need to move to the new community location too?

**Comment by efriis** [comment]
Feel free to leave the self query one where it is for now - we'll handle that with the rest at that time.

**Comment by ofermend** [comment]
@efriis - any updates on merging this in? Anything else missing?

**Comment by efriis** [comment]
I think it's just failing lint if you want to take a look!

**Comment by ofermend** [comment]
fixed that lint issue. Anything else I'm missing?

**Comment by efriis** [comment]
It's still failing lint. I'll take a look later today! Make sure you're running mypy 0.0.991 and ruff 0.1.5 in community!

**Comment by ofermend** [comment]
Thanks. Pls let me know. THe failures I see above are unrelated to Vectara (Power BI or something)

**Comment by efriis** [comment]
Assuming you didn't mean to change those files in this PR?

**Comment by ofermend** [comment]
Not at all. Sorry maybe did so mistakenly during a previous "make format" that went bad?

**Comment by efriis** [comment]
Can't edit this branch. Merging in #14970

**Pull request closed without merging**
