### PR TITLE
added rrf argument in ApproxRetrievalStrategy class __init__()

### PR DESCRIPTION
**Pull request by HwangJohn**
- **Description: To handle the hybrid search with RRF(Reciprocal Rank Fusion) in the Elasticsearch, rrf argument was added for adjusting 'rank_constant' and 'window_size' to combine multiple result sets with different relevance indicators into a single result set. (ref: https://www.elastic.co/kr/blog/whats-new-elastic-enterprise-search-8-9-0), 
  - **Issue:** the issue # it fixes (if applicable),
  - **Dependencies:** No dependencies changed,
  - **Tag maintainer:** @baskaryan,

Nice to meet you,
I'm a newbie for contributions and it's my first PR.

I only changed the langchain/vectorstores/elasticsearch.py file.
I did make format&lint 
I got this message,
```shell
make lint_diff  
./scripts/check_pydantic.sh .
./scripts/check_imports.sh
poetry run ruff .
[ "langchain/vectorstores/elasticsearch.py" = "" ] || poetry run black langchain/vectorstores/elasticsearch.py --check
All done! ✨ 🍰 ✨
1 file would be left unchanged.
[ "langchain/vectorstores/elasticsearch.py" = "" ] || poetry run mypy langchain/vectorstores/elasticsearch.py
langchain/__init__.py: error: Source file found twice under different module names: "mvp.nlp.langchain.libs.langchain.langchain" and "langchain"
Found 1 error in 1 file (errors prevented further checking)
make: *** [lint_diff] Error 2
```

Thank you

### CODE REVIEW

**Comment by baskaryan** [comment]
cc @joemcelroy

**Comment by HwangJohn** [comment]
I think the position of rrf parameter in the _search/query methods is better than in the class ApproxRetrievalStrategy member variable.

**Review by joemcelroy — COMMENTED** [review]
Hi there,

So there are some upcoming changes we will be doing to retrieval so I would prefer that it remains at strategy level.

The other suggestion is that it should be part of the ApproxStrategy interface rather than be the `query` method as isn't very accessible.

```

db = ElasticsearchStore.from_documents(
    docs, 
    embeddings, 
    es_url="http://localhost:9200", 
    index_name="test",
    strategy=ElasticsearchStore.ApproxRetrievalStrategy(
        hybrid=True,
        rrf=False
    )
)
```

This makes `rrf` a class variable which simplifies access and how the developer will specify this configuration.

Also need tests for this change please :)

**Comment by eyurtsev** [comment]
@joemcelroy would you be willing to review?

**Comment by eyurtsev** [comment]
@joemcelroy sorry tagged you by accident, didn't notice you already had reviewed

**Comment by HwangJohn** [comment]
@joemcelroy 
First of all, thank you for your guidance.

As you mentioned above, I proceeded with 3 tasks.

1. restored the position of `rrf` argument.
2. added optional `fetch_k` argument in similarity_search().
3. added test code `test_similarity_search_approx_with_hybrid_search_rrf()` in TestElasticsearch class.

but implementation of "1. restored the position of `rrf` argument" is a little bit different.
You mentioned `rrf=False`, I changed it as `rrf={"rank_constant": 1, "window_size": 5}`

The reason is that I thought the users can pass the rrf parameters(rank_constant, window_size).

If you think this implementation is not profer, pz let me know how to fix it.

**Comment by joemcelroy** [comment]
I see, I thought you just wanted to switch rrf off, which was a reasonable request. Being able to provide configuration to `rrf` is a good idea too!

So i support that rrf can either be a boolean or a dict. 

- By default its true and when true,  its`rrf: {}`
- When false, `rrf` is not part of the request and is omitted
- When a dict, pass in the dict values to the `rrf` key. Example: 

```python
    strategy=ElasticsearchStore.ApproxRetrievalStrategy(
        hybrid=True,
        rrf={"rank_constant": 1, "window_size": 5}
    )

    strategy=ElasticsearchStore.ApproxRetrievalStrategy(
        hybrid=True,
        rrf=True # default value
    )

    strategy=ElasticsearchStore.ApproxRetrievalStrategy(
        hybrid=True,
        rrf=False
    )
 ```

**Comment by HwangJohn** [comment]
@joemcelroy 
I updated the rrf types and test codes as you mentioned.

**Review by joemcelroy — APPROVED** [review]
Thank you!! Ran integration tests and passes.

**Pull request merged**
