### PR TITLE
community: add KafkaChatMessageHistory

### PR DESCRIPTION
**Pull request by changliu-0520**
Add chat history store based on Kafka.

Files added: 
`libs/community/langchain_community/chat_message_histories/kafka.py`
`docs/docs/integrations/memory/kafka_chat_message_history.ipynb`

New issue to be created for future improvement:
1. Async method implementation.
2. Message retrieval based on timestamp.
3. Support for other configs when connecting to cloud hosted Kafka (e.g. add `api_key` field)
4. Improve unit testing & integration testing.

### CODE REVIEW

**Comment by changliu-0520** [comment]
Hi @baskaryan @ccurme @eyurtsev , could you please take a look at this PR to add chat message store based on Kafka ? 
I will also create a follow up issue as mentioned in the PR description.

**Comment by changliu-0520** [comment]
Hi @eyurtsev Gentle ping on this. When you get a chance, could you please review this PR ?  Thank you!

**Comment by isahers1** [comment]
@changliu-0520 Sorry for the delay. Can you please update the doctoring for KafkaChatMessageHistory. You can look at the ChatOpenAI doctoring for a good example. Just make sure to include code blocks correctly

**Comment by changliu-0520** [comment]
@isahers1 Thanks for the review. I've updated the docstring.  Please let me know if we need further changes.

**Pull request merged**
