### PR TITLE
community: Add initial tests for AzureSearch vector store

### PR DESCRIPTION
**Pull request by mattgotteiner**
**Description:** AzureSearch vector store has no tests. This PR adds initial tests to validate the code can be imported and used.
**Issue:** N/A
**Dependencies:** azure-search-documents and azure-identity are added as optional dependencies for testing

### CODE REVIEW

**Comment by mattgotteiner** [comment]
@pamelafox had the idea to test this by manually reverting the following pr
#17599

I can confirm these tests would catch the regression that PR fixed

**Comment by mattgotteiner** [comment]
@baskaryan please take a look. It would be great to have some test coverage on the Azure Search vector store

**Comment by mattgotteiner** [comment]
@baskaryan

**Review by baskaryan — APPROVED** [review]

**Comment by mattgotteiner** [comment]
Thanks @baskaryan I fixed how I was patching, hopefully the tests run now.

**Comment by baskaryan** [comment]
still seeing some lint issues in community, you can run formatter linter locally with
```bash
cd libs/community
poetry install --with lint,typing,test
make format
make lint
```

**Comment by mattgotteiner** [comment]
FYI @baskaryan  i think the build is stuck, but please take a look

**Comment by baskaryan** [comment]
@mattgotteiner still some lint issues. you can run linter locally with
```bash
cd libs/community
make format
make lint
```
to see what's going on

**Comment by mattgotteiner** [comment]
> @mattgotteiner still some lint issues. you can run linter locally with
> 
> ```shell
> cd libs/community
> make format
> make lint
> ```
> 
> to see what's going on

sorry I lost track of this. just tried to fix it

**Comment by mattgotteiner** [comment]
@baskaryan  this is finally passing CI. Please let me know if you can merge it

**Comment by mattgotteiner** [comment]
Hi @baskaryan  do you think you can please take another look?

**Comment by mattgotteiner** [comment]
Hi @baskaryan  any chance this PR can be merged? It's passing CI now. Please let me know

**Comment by mattgotteiner** [comment]
Thanks!

**Pull request merged**
