### PR TITLE
community: Add SparkLLM Text Embedding Model and SparkLLM introduction

### PR DESCRIPTION
**Pull request by liugddx**
Thank you for contributing to LangChain!

Checklist:

- [x] PR title: Please title your PR "package: description", where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"
- [x] PR message: **Delete this entire template message** and replace it with the following bulleted list
    - **Description:** Add SparkLLM Text Embedding Model and SparkLLM introduction
    - **Issue:** #17672 
    - **Dependencies:** No
    - **Twitter handle:** No
- [x] Pass lint and test: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified to check that you're passing lint and testing. See contribution guidelines for more information on how to write/run tests, lint, etc: https://python.langchain.com/docs/contributing/
- [x] Add tests and docs: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

### CODE REVIEW

**Comment by liugddx** [comment]
@baskaryan PTAL, thanks.

**Comment by liugddx** [comment]
@efriis @eyurtsev @hwchase17 kindly pin.

**Comment by liugddx** [comment]
@baskaryan Can you help me with the ci problem?

**Comment by baskaryan** [comment]
> @baskaryan Can you help me with the ci problem?

looks like there's a number of lines that are too long https://github.com/langchain-ai/langchain/actions/runs/7960221654/job/21728761889?pr=17573. To check the fix you can run linting locally with
```bash
cd libs/community
poetry install --with lint,typing
make format
make lint
```

**Comment by liugddx** [comment]
> > @baskaryan Can you help me with the ci problem?
> 
> looks like there's a number of lines that are too long https://github.com/langchain-ai/langchain/actions/runs/7960221654/job/21728761889?pr=17573. To check the fix you can run linting locally with
> 
> ```shell
> cd libs/community
> poetry install --with lint,typing
> make format
> make lint
> ```

Thank you @baskaryan,  this helps me a lot.

**Comment by liugddx** [comment]
> > > @baskaryan Can you help me with the ci problem?
> > 
> > 
> > looks like there's a number of lines that are too long https://github.com/langchain-ai/langchain/actions/runs/7960221654/job/21728761889?pr=17573. To check the fix you can run linting locally with
> > ```shell
> > cd libs/community
> > poetry install --with lint,typing
> > make format
> > make lint
> > ```
> 
> Thank you @baskaryan, this helps me a lot.

Another question, I executed `make format` and `make lint` and got an error. Can it automatically format the code?

image

**Comment by liugddx** [comment]
@baskaryan PTAL, thanks.

**Review by baskaryan — APPROVED** [review]

**Comment by liugddx** [comment]
Can you help me merge this pr?

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
