### PR TITLE
deepinfra support for chat_models

### PR DESCRIPTION
**Pull request by ichernev**
Add deepinfra chat models support.

### CODE REVIEW

**Comment by efriis** [comment]
All good! We're actually refactoring the locations of a bunch of integrations of this style, so this won't make it in until next week (I'll set a reminder to return to it). There will likely be some file movement required, and will follow up next week!

**Comment by ichernev** [comment]
@efriis please review

**Comment by ichernev** [comment]
@efriis ping

**Comment by efriis** [comment]
#15784 because https://python.langchain.com/docs/contributing/faq#how-do-i-allow-maintainers-to-edit-my-pr

**Pull request closed without merging**
