### PR TITLE
CPAL

### PR DESCRIPTION
**Pull request by borisdev**
# Causal program-aided language (CPAL) chain

## Motivation

This builds on the recent Program-aided Language ([PAL](https://arxiv.org/abs/2211.10435)) approach to stop LLM hallucination. The problem with the [PAL](https://arxiv.org/abs/2211.10435) approach is that it hallucinates on a math problem with a nested chain of dependence. The innovation here is that this new CPAL approach includes causal structure to fix hallucination.

For example, using the below word problem, PAL answers with 5, and CPAL answers with 13.

    "Tim buys the same number of pets as Cindy and Boris."
    "Cindy buys the same number of pets as Bill plus Bob."
    "Boris buys the same number of pets as Ben plus Beth."
    "Bill buys the same number of pets as Obama."
    "Bob buys the same number of pets as Obama."
    "Ben buys the same number of pets as Obama."
    "Beth buys the same number of pets as Obama."
    "If Obama buys one pet, how many pets total does everyone buy?"

The CPAL chain represents the causal structure of the above narrative as a causal graph or DAG, which it can also plot, as shown below. 

complex-graph

.

The two major sections below are:

1. Technical overview
2. Future application

Also see [this jupyter notebook](https://github.com/borisdev/langchain/blob/master/docs/extras/modules/chains/additional/cpal.ipynb) doc.

### CPAL versus PAL

Like [PAL](https://arxiv.org/abs/2211.10435), CPAL intends to reduce large language model (LLM) hallucination. 

The CPAL chain is different from the PAL chain for a couple of reasons. 

* CPAL adds a causal structure (or DAG) to link entity actions (or math expressions).  
* The CPAL math expressions are modeling a chain of cause and effect relations, which can be intervened upon, whereas for the PAL chain math expressions are projected math identities. 

PAL's generated python code is wrong. It hallucinates when complexity increases. 

```python
def solution():
    """Tim buys the same number of pets as Cindy and Boris.Cindy buys the same number of pets as Bill plus Bob.Boris buys the same number of pets as Ben plus Beth.Bill buys the same number of pets as Obama.Bob buys the same number of pets as Obama.Ben buys the same number of pets as Obama.Beth buys the same number of pets as Obama.If Obama buys one pet, how many pets total does everyone buy?"""
    obama_pets = 1
    tim_pets = obama_pets
    cindy_pets = obama_pets + obama_pets
    boris_pets = obama_pets + obama_pets
    total_pets = tim_pets + cindy_pets + boris_pets
    result = total_pets
    return result  # math result is 5
```

CPAL's generated python code is correct.

```python
story outcome data
    name                                   code  value      depends_on
0  obama                                   pass    1.0              []
1   bill               bill.value = obama.value    1.0         [obama]
2    bob                bob.value = obama.value    1.0         [obama]
3    ben                ben.value = obama.value    1.0         [obama]
4   beth               beth.value = obama.value    1.0         [obama]
5  cindy   cindy.value = bill.value + bob.value    2.0     [bill, bob]
6  boris   boris.value = ben.value + beth.value    2.0     [ben, beth]
7    tim  tim.value = cindy.value + boris.value    4.0  [cindy, boris]

query data
{
    "question": "how many pets total does everyone buy?",
    "expression": "SELECT SUM(value) FROM df",
    "llm_error_msg": ""
}
# query result is 13
```

Based on the comments below, CPAL's intended location in the library is `experimental/chains/cpal` and PAL's location is`chains/pal`.

### CPAL vs Graph QA

Both the CPAL chain and the Graph QA chain extract entity-action-entity relations into a DAG.

The CPAL chain is different from the Graph QA chain for a few reasons.

* Graph QA does not connect entities to math expressions
* Graph QA does not associate actions in a sequence of dependence.
* Graph QA does not decompose the narrative into these three parts:
  1. Story plot or causal model
  4. Hypothetical question
  5. Hypothetical condition 

### Evaluation

Preliminary evaluation on simple math word problems shows that this CPAL chain generates less hallucination than the PAL chain on answering questions about a causal narrative. Two examples are in [this jupyter notebook](https://github.com/borisdev/langchain/blob/master/docs/extras/modules/chains/additional/cpal.ipynb) doc.

### "Describe as Narrative, Test as Code"

The thesis here is that the Describe as Narrative, Test as Code approach allows you to represent a causal mental model both as code and as a narrative, giving you the best of both worlds.

#### Why describe a causal mental mode as a narrative?

The narrative form is quick. At a consensus building meeting, people use narratives to persuade others of their causal mental model, aka. plan. You can share, version control and index a narrative.

#### Why test a causal mental model as a code?

Code is testable, complex narratives are not. Though fast, narratives are problematic as their complexity increases. The problem is LLMs and humans are prone to hallucination when predicting the outcomes of a narrative. The cost of building a consensus around the validity of a narrative outcome grows as its narrative complexity increases. Code does not require tribal knowledge or social power to validate. 

Code is composable, complex narratives are not. The answer of one CPAL chain can be the hypothetical conditions of another CPAL Chain. For stochastic simulations, a composable plan can be integrated with the [DoWhy library](https://github.com/py-why/dowhy). Lastly, for the futuristic folk, a composable plan as code allows ordinary community folk to design a plan that can be integrated with a blockchain for funding.  

An explanation of a dependency planning application is [here.](https://github.com/borisdev/cpal-llm-chain-demo)

--- 
Twitter handle: @boris_dev

### CODE REVIEW

**Comment by borisdev** [comment]
@hwchase17
@vowelparrot

**Question:** Is this PR draft worthwhile to continue working on?

**Context**: Before I work on the tests and assign the PR, I wanted to make sure you think it has a shot to meet what you are looking for, especially since it is not coming from a github issue.

**Comment by vowelparrot** [comment]
This is really cool. I'll take a closer look at the code later tonight, but I absolutely think this is something we'd like to include in the library. If it's too complicated, then we could at least put in the `experimental/` directory to start cc @hwchase17 @eyurtsev 

ps I'm a big fan of the DoWhy library also btw.

**Comment by hwchase17** [comment]
super interesting. yeah lets include in experimental for now

**Comment by borisdev** [comment]
> @borisdev is attempting to deploy a commit to the **LangChain** Team on [Vercel](https://vercel.com).
> 
> A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=LangChain&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%229e5079fd00fcb7c77c90359c3adb527c13762400%22%7D%2C%22id%22%3A%22Qmc8RFX4gMUHfPxAkUSsnmZoCmzs8w2X35gwVqA9AYgo6a%22%2C%22org%22%3A%22hwchase17%22%2C%22prId%22%3A6255%2C%22repo%22%3A%22langchain%22%7D).

This was an accident on my part. Please ignore.

**Comment by borisdev** [comment]
> @borisdev is attempting to deploy a commit to the **LangChain** Team on [Vercel](https://vercel.com).
> 
> A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=LangChain&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%229e5079fd00fcb7c77c90359c3adb527c13762400%22%7D%2C%22id%22%3A%22Qmc8RFX4gMUHfPxAkUSsnmZoCmzs8w2X35gwVqA9AYgo6a%22%2C%22org%22%3A%22hwchase17%22%2C%22prId%22%3A6255%2C%22repo%22%3A%22langchain%22%7D).

accident

**Comment by borisdev** [comment]
@dev2049 

My TODOs for tomorrow:

- replace prints with proper integration test results  
- unit tests
- lint errors
- better doc strings

**Comment by borisdev** [comment]
@vowelparrot 
@hwchase17 

The PR is ready for review. Thanks.

**Comment by borisdev** [comment]
re-open

**Comment by borisdev** [comment]
s

**Comment by borisdev** [comment]
re-open

**Comment by borisdev** [comment]
re-open

**Comment by borisdev** [comment]
@vowelparrot 
@hwchase17
@eyurtsev 

I think the PR is ready for review.

- [x] unit tests
- [x] Jupyter notebook doc (PAL vs CPAL)
- [x] verbose
- [x] I moved my code to the `experimental` directory
- [x] replace prints with proper integration test results  
- [x] better doc strings
- [x] rename templates
- [x] patch/mock `networkx`
- [x] replaced `causal_mental_model` with `causal_operations` 
- [x] graphviz draw
- [x] lint errors
- [x] unit test `test_all_subclasses_implement_unique_type` fails. https://github.com/hwchase17/langchain/issues/7451. Workaround by moving my unit test into integration tests.

**Comment by borisdev** [comment]
lint tests and unit tests pass

Screenshot 2023-07-10 at 5 15 22 PM

**Comment by baskaryan** [comment]
@borisdev this is awesome and looks pretty good to me!

**Pull request merged**
