### PR TITLE
Community: adding linearization config to AmazonTextractPDFLoader

### PR DESCRIPTION
**Pull request by lvieirajr**
- **Description:** Adding an optional parameter `linearization_config` to the `AmazonTextractPDFLoader` so the caller can define how the output will be linearized, instead of forcing a predefined set of linearization configs. It will still have a default configuration as this will be an optional parameter.
- **Issue:** #17457
- **Dependencies:** The same ones that already exist for `AmazonTextractPDFLoader`
- **Twitter handle:** [@lvieirajr19](https://twitter.com/lvieirajr19)

### CODE REVIEW

**Comment by lvieirajr** [comment]
@schadem You might have opinions here since you wrote the initial version of this loader integration.

**Review by baskaryan — COMMENTED** [review]
cc @3coins

**Comment by schadem** [comment]
@lvieirajr Thank you for your contribution. Totally makes sense and the implementation looks good to me. Tested and works.

**Comment by eyurtsev** [comment]
@lvieirajr  the notebook looks corrupt in the preview, could you double check the notebook?

**Comment by lvieirajr** [comment]
@eyurtsev I couldn't find any issues, I ran the notebook locally and it looked fine.
Screenshot 2024-02-17 at 3 44 31 AM

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
