### PR TITLE
docs[minor],community[patch]: Minor tutorial docs improvement, minor import error quick fix. 

### PR DESCRIPTION
**Pull request by Robert-Jia00129**
minor changes to module import error handling and minor issues in tutorial documents.

### CODE REVIEW

**Review by eyurtsev — COMMENTED** [review]
Looks good generally.

It looks like the notebooks contain 2 TODO statements, should these be deleted?

**Comment by Robert-Jia00129** [comment]
> Looks good generally.
> 
> It looks like the notebooks contain 2 TODO statements, should these be deleted?

Thanks for catching. One TODO is not fixed yet. I notice on the website there are no API document for `SqliteSaver`. But the API references seem to be generated not within the notebook. I wonder where should I look into to fix this?

**Comment by eyurtsev** [comment]
@Robert-Jia00129  https://langchain-ai.github.io/langgraph/reference/checkpoints/#sqlitesaver

**Comment by Robert-Jia00129** [comment]
> @Robert-Jia00129 https://langchain-ai.github.io/langgraph/reference/checkpoints/#sqlitesaver

Sorry for the confusion, I mean in the rendered website for this jupyter notebook (https://python.langchain.com/v0.2/docs/tutorials/qa_chat_history/), there are no API references to `sqlitesaver`. 

I think all the API references are auto-generated (as they are not in Jupyter Notebook cells), so I wonder where should I look at to resolve this unreferenced API reference.

**Comment by eyurtsev** [comment]
@Robert-Jia00129 ah if you'd like to do that, leave it for a separate PR

This is the code that generates api references. It doesn't catch any imports from langgraph right now

https://github.com/langchain-ai/langchain/blob/master/docs/scripts/generate_api_reference_links.py

**Comment by Robert-Jia00129** [comment]
Thanks. The TODOs are removed. And I'll update the API reference in another PR.

**Comment by eyurtsev** [comment]
Thanks @Robert-Jia00129

**Pull request merged**
