### PR TITLE
add chat agent

### PR DESCRIPTION
**Pull request by hwchase17**

### CODE REVIEW

**Comment by yakigac** [comment]
@hwchase17 
I think that's great idea to use json to parse. But when I tested LLMs ignore the rule especially in 2nd or latter conversation. 

How about using SystemMessageTemplate for the rule explanation and AIMessageTemplate for the agent_scratchpad like below?

Success for the first question:
image

Failure for the 2nd question (LLM ignores the rule):
image

Success for the 2nd question:
image

**Comment by mrbende** [comment]
This seems like it would resolve my issue I am seeing [here](https://github.com/hwchase17/langchain/issues/1371#issuecomment-1459262703)...

I'd like to try and implement this with the Prompt Selector offered [here](https://github.com/hwchase17/langchain/blob/master/langchain/chains/question_answering/stuff_prompt.py)...

Any ideas as to when this functionality might be merged to main?

Thanks!

**Comment by hwchase17** [comment]
will be merged in tmrw

will change to system message, thanks for the tip

**Comment by yakigac** [comment]
Thanks! how do you think about this?
> AIMessageTemplate for the agent_scratchpad

Of course, I respect your decision.

**Comment by hwchase17** [comment]
> @hwchase17 Thanks! how do you think about this?
> 
> > AIMessageTemplate for the agent_scratchpad
> 
> Of course, I respect your decision.

its a good question. i thought about it a bit - i got better results when putting in a human message

that being said, maybe i was just using the wrong prompt? do you have one that works well? always down to make another agent!

**Comment by yakigac** [comment]
AI template made better results for some of my cases as I posted the images. Not always.

But I think earlier is better. I will follow you. We can fix it later if we need it. It will not be destractive.

**Comment by libratiger** [comment]
still the same problem for the langchain version 0.0.116

**Comment by kenndanielso** [comment]
Still having this problem.

**Comment by mrbende** [comment]
I am still having this problem as well. There doesn't seem to be a clear method to combine conversation memory, tools/agents, and the ChatOpenAI endpoint. I am using `ConversationalAgent.create_prompt()` to create the prompt. Is there any documentation/resolution to this? Thanks!

**Comment by mrbende** [comment]
Still having the problem on `langchain==0.0.123`

**Comment by Travis-Barton** [comment]
I am still having this problem:

```
def pandas_cell_formatter(text='', row='', column='', error=None):
    # find the right features 
    features = parse_correct_features(row, column)
    prompt = f'you are looking for the {row} and {column} cell in the table. Currently the '\
             f'cell contains the text: {text}\n Please format the text so that it can be '\
             f'more easily read in a spreadsheet. Feel free to make lists, add units, or '\
             f'anything else that will make the data more readable. '\
             f'If the information you need is not in this prompt, you can use the '\
             f'ClinicalTrials.gov API to get the data you need. You have access to the ' \
             f'requests tool to make API calls. ' \
             f'Use these features: {features}. ' \
             f'URLs look like this example: ' \
             f'https://clinicaltrials.gov/api/query/study_fields?expr=heart+attack&fields=NCTId,Condition,BriefTitle. '
    if error:
        prompt += f'The last time you tried this you got the error: `{error}`\nMake changes accordingly'

    model = ChatOpenAI(openai_api_key=os.environ['OPENAI_API_KEY'], temperature=0,
                       model_name="gpt-4")
    llm = OpenAI(temperature=0)
    request_tool = load_tools(['requests_get'], llm=llm)[0]
    tools = [
        request_tool
    ]
    executor = initialize_agent(tools=tools, llm=model, verbose=True)
    result = executor.run(input=prompt)
    return result

```

**Pull request merged**
