### PR TITLE
Vectorstore relevance fn fix

### PR DESCRIPTION
**Pull request by dangoldbj**
**Description:**

- The changes fixes the normalization in the relevance score functions.
- Some vector databases use `cosine` to indicate `cosine similarity` while some use it to indicate `cosine distance`.
  - SemaDB uses `cosine` metric to indicate `cosine distance`. https://rapidapi.com/semafind-semadb/api/semadb/details
  - Elasticsearch uses `cosine` metric to indicate `cosine similarity`. https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html#dense-vector-params
  - Neo4j uses `cosine` metric to indicate `cosine similarity`. https://neo4j.com/docs/cypher-manual/current/indexes-for-vector-search/#indexes-vector-create
  - Momento uses `cosine_similarity` metric to indicate `cosine similarity`. https://github.com/momentohq/client-sdk-python/blob/main/src/momento/requests/vector_index/similarity_metric.py
  - pgvector uses `cosine distance`. https://github.com/pgvector/pgvector#pgvector
  - Pinecone uses `cosine` metric to indicate `cosine similarity`. https://docs.pinecone.io/docs/indexes#distance-metrics
  - FAISS does not directly support `cosine similarity` nor `cosine distance`. https://github.com/facebookresearch/faiss/blob/main/faiss/MetricType.h#L44
  - TimescaleVector is built on top of pgvector, hence uses `cosine distance`.
  - Chroma uses `cosine` metric to indicate `cosine distance`. https://docs.trychroma.com/usage-guide#changing-the-distance-function
  - Redis uses `cosine` metric to indicate `cosine distance`. https://redis.io/docs/interact/search-and-query/advanced-concepts/vectors/

**Issue:**
https://github.com/langchain-ai/langchain/issues/11587
https://github.com/langchain-ai/langchain/issues/13437
https://github.com/langchain-ai/langchain/issues/7384
https://github.com/langchain-ai/langchain/issues/11386
https://github.com/langchain-ai/langchain/issues/12697

Twitter handle: dangoldbj

@baskaryan, @eyurtsev, @hwchase17

### CODE REVIEW

**Comment by younes-io** [comment]
@dangoldbj : is OpenSearch included in this?

**Comment by dangoldbj** [comment]
> @dangoldbj : is OpenSearch included in this?

@younes-io  I think OpenSearch vector store is correctly implemented.
https://opensearch.org/docs/latest/search-plugins/knn/approximate-knn/#spaces does use `cosineSimilarity` to indicate `cosine distance`. However in the implementation, https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/opensearch_vector_search.py#L270C5-L270C5 the score is converted back to `cosine similarity`

**Comment by younes-io** [comment]
you're right..
btw, i don't see in OpenSearch vector store implementation a way to do [hybrid search](https://opensearch.org/docs/latest/query-dsl/compound/hybrid) (RRF).. I want to do keyword search and use the similarity search and combine them in an Ensemble retriever.. Ofc, I wish there was a way to call search pipelines using OpenSearch vector implementation so that OpenSearch takes care of all of the hybrid search directly since it supports since 2.10 but LangChain doesn't seem to support it for now, right ? Have you done sth like this using OpenSeachVectorSearch ?
thank you

**Comment by hwchase17** [comment]
this has a lot of merge conflicts so i am going to close. we will revisitng our vectorstore abstractions in ~1 month and will reference this

**Pull request closed without merging**
