### PR TITLE
docs: update documentation for Vertex Embeddings Models

### PR DESCRIPTION
**Pull request by Adi8885**
- **Description:update documentation for Vertex Embeddings Models
    - **Issue:NA
    - **Dependencies:NA
    - **Twitter handle:NA

### CODE REVIEW

**Comment by Adi8885** [comment]
@efriis @lkuligin Can you help here? I'm not sure why vercel deployment keeps failing. I'm not able to view details either.

**Comment by efriis** [comment]
ScreenShot 2024-08-27 at 01 32 32PM

**Comment by Adi8885** [comment]
> ScreenShot 2024-08-27 at 01 32 32PM

Thanks It worked !

**Comment by efriis** [comment]
would love a review from @lkuligin ! format looks good to me

**Pull request merged**
