### PR TITLE
CassandraCache and CassandraSemanticCache can handle any "Generation"

### PR DESCRIPTION
**Pull request by hemidactylus**
Hello,
this PR improves coverage for caching by the two Cassandra-related caches (i.e. exact-match and semantic alike) by switching to the more general `dumps`/`loads` serdes utilities.

This enables cache usage within e.g. `ChatOpenAI` contexts (which need to store lists of `ChatGeneration` instead of `Generation`s), which was not possible as long as the cache classes were relying on the legacy `_dump_generations_to_json` and `_load_generations_from_json`).

Additionally, a slightly different init signature is introduced for the cache objects:
- named parameters required for init, to pave the way for easier changes in the future connect-to-db flow (and tests adjusted accordingly)
- added a `skip_provisioning` optional passthrough parameter for use cases where the user knows the underlying DB table, etc already exist.

Thank you for a review!

### CODE REVIEW

**Comment by baskaryan** [comment]
worth noting changing init signature and serder logic are both breaking changes so we should be sure they're worth making

**Comment by hemidactylus** [comment]
I agree, which is why I had thought a bit about this before making these choices. Here's my reasoning on these two points:

1. Serdes. Since these classes are used for caching, missing items pre-post-migration is supposedly not a dramatic thing, compared to the extended support for Chat* storage one gains. I could add logic to catch the json exception and silently return a cache miss (just a warning, no error) in case an "old format" entry is encountered, that would probably be a net gain. Given the "disposable" nature of cache items, I thought adding a legacy-compatibility layer would have been more a burden than an advantage.
2. The init signature. This is more speculative, but one thing that is in the making on the CassIO side is another connection method `cassio.init(...)`, followed by lightweight init of possibly several classes leaving session/keyspace unspecified (i.e. default). As a named-parameter paradigm is anyway very common in all things around LLM/GenAI tooling in my experience (with everything evolving so fast!) I took the plunge and thought "better now than later". But on this point I am slightly less certain than on the previous.

**Comment by baskaryan** [comment]
> I agree, which is why I had thought a bit about this before making these choices. Here's my reasoning on these two points:
> 
> 1. Serdes. Since these classes are used for caching, missing items pre-post-migration is supposedly not a dramatic thing, compared to the extended support for Chat* storage one gains. I could add logic to catch the json exception and silently return a cache miss (just a warning, no error) in case an "old format" entry is encountered, that would probably be a net gain. Given the "disposable" nature of cache items, I thought adding a legacy-compatibility layer would have been more a burden than an advantage.
> 2. The init signature. This is more speculative, but one thing that is in the making on the CassIO side is another connection method `cassio.init(...)`, followed by lightweight init of possibly several classes leaving session/keyspace unspecified (i.e. default). As a named-parameter paradigm is anyway very common in all things around LLM/GenAI tooling in my experience (with everything evolving so fast!) I took the plunge and thought "better now than later". But on this point I am slightly less certain than on the previous.
> 
> In any case, I am deeply grateful for the extremely fast reaction to this PR :)

1. thinking catching json errors and warning would be great! beyond that, agree cache misses are fairly harmless
2. think for CassandraCache fine to keep change (not actually breaking) but would prefer not to break SemanticCache until we're more confident of what right init should look like. Can still change typing to Optional though

**Comment by hemidactylus** [comment]
Thank you for sharing your thoughts. I agree with both points. Here's an update where:
1. errors from malformed cache entries are handled softly with a warning, no exceptions, just yet another cache miss;
2. while I was at it, compatibility with the legacy format for cached entries is recovered (a warning is logged)
3. restored the init method in the semantic cache somewhat: kept the parameter order unchanged, just made session/keyspace Optional as you suggest. Once the `init()` method of cassIO is fleshed out fully and makes it to PyPI, this might be revised, but it's fine for me not to anticipate it here.

Cheers!

**Pull request merged**
