### PR TITLE
community: Add pebblo safe document loader

### PR DESCRIPTION
**Pull request by srics**
- **Description:** Pebblo opensource project enables developers to safely load data to their Gen AI apps. It identifies semantic topics and entities found in the loaded data and summarizes them in a developer-friendly report.
  - **Dependencies:** none
  - **Twitter handle:** srics

@hwchase17

### CODE REVIEW

**Comment by srics** [comment]
@baskaryan, @eyurtsev, @hwchase17
Maintainers: can you pls review and provide your initial thoughts/comments? Thanks!

**Review by hwchase17 — APPROVED** [review]

**Comment by srics** [comment]
> looks like some CI failures. otherwise, lgmt

Thanks, I will push a fix.

**Comment by srics** [comment]
> > looks like some CI failures. otherwise, lgmt
> 
> Thanks, I will push a fix.

@hwchase17 CI lint issues fixed, pls review/merge

**Comment by srics** [comment]
@hwchase17 fixed the CI issues,  pls review

**Pull request merged**
