### PR TITLE
Fixed Office365 tool __init__.py files, tests, and get_tools() function

### PR DESCRIPTION
**Pull request by sdelgadoc**
## Description
Added Office365 tool modules to `__init__.py` files
## Issue
As described in Issue https://github.com/hwchase17/langchain/issues/6936, the Office365 toolkit can't be loaded easily because it is not included in the `__init__.py` files.
## Reviewer
@dev2049

### CODE REVIEW

**Comment by sdelgadoc** [comment]
PR has one lint error with little details on how to fix. Let me know if you want me to edit anything. Otherwise, hopefully it has everything necessary to merge.

**Comment by baskaryan** [comment]
you should be able to fix by running `make format` (more on formatting/linting/testing here https://github.com/hwchase17/langchain/blob/master/.github/CONTRIBUTING.md#-common-tasks)

**Comment by sdelgadoc** [comment]
> you should be able to fix by running `make format` (more on formatting/linting/testing here https://github.com/hwchase17/langchain/blob/master/.github/CONTRIBUTING.md#-common-tasks)

Thanks @baskaryan, worked like a charm!

**Review by hwchase17 — APPROVED** [review]
thanks!

**Pull request merged**
