### PR TITLE
docs: Fix outdated doc as no templates on master

### PR DESCRIPTION
**Pull request by Mingqi2**
Thank you for contributing to LangChain!

- [x] **PR title**: **docs: update project_template readme as no templates dir on master**
  - Where "package" is whichever of langchain, community, core, etc. is being modified. Use "docs: ..." for purely docs changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [x] **PR message**: 
    - **Description:** 
    templates dir is only keeped on v0.2 branch. Master has removed it. However our master branch still has the outdated readme to let user add those templates packages. It's failed of course.
    - **Solution**: update the lines and tell user to use them on v0.2
  

- [ ] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [ ] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Comment by Mingqi2** [comment]
@baskaryan @ccurme could you please help to review this small PR? Thanks!

**Comment by efriis** [comment]
hey there! templates are in the v0.2 branch and are not compatible with langchain 0.3. As we encourage new use cases to be implemented with langgraph, we recommend starting with those templates! I'll put up a PR deleting this section of the readme, and adding a warning to the command if used.

**Comment by efriis** [comment]
oh I see this is just for the project template. I actually think this is ok because it's in a deprecated command, and I'll just add the warning instead!

**Comment by Mingqi2** [comment]
> oh I see this is just for the project template. I actually think this is ok because it's in a deprecated command, and I'll just add the warning instead!

Good. Thanks for your feedbacks.

**Pull request closed without merging**
