### PR TITLE
fixed regex to match sources for all cases, also includes source

### PR DESCRIPTION
**Pull request by nik1097**

### CODE REVIEW

**Comment by baskaryan** [comment]
thanks @nik1097! could we add a unit test?

**Comment by nik1097** [comment]
hey @baskaryan I updated the unit tests. However, I'm having issues with linting/formatting my code change. The make commands to be working. Could you help me out please?

**Comment by nik1097** [comment]
@baskaryan never mind I got it to work. Thanks! :)

**Comment by baskaryan** [comment]
awesome, thanks @nik1097!

**Pull request merged**
