### PR TITLE
Quote tool names

### LINKED ISSUE #1358: ValueError: Could not parse LLM output:
`agent_chain = initialize_agent( tools=tools, llm= HuggingFaceHub(repo_id="google/flan-t5-xl"), agent="conversational-react-description", memory=memory, verbose=False)

agent_chain.run("Hi")`

**throws error. This happens with Bloom as well. Agent only with OpenAI is only working well.**

`_(self, inputs, return_only_outputs)
    140 except (KeyboardInterrupt, Exception) as e:
    141     self.callback_manager.on_chain_error(e, verbose=self.verbose)
--> 142     raise e
    143 self.callback_manager.on_chain_end(outputs, verbose=self.verbose)
...
---> 83     raise ValueError(f"Could not parse LLM output: "{llm_output}")
     84 action = match.group(1)
     85 action_input = match.group(2)

ValueError: Could not parse LLM output: Assistant, how can I help you today?`

### PR DESCRIPTION
**Pull request by Atry**
- **Description:** Quote tool names in prompt templates
  - **Issue:** https://github.com/langchain-ai/langchain/issues/1657 https://github.com/langchain-ai/langchain/issues/1477 https://github.com/langchain-ai/langchain/issues/1358
  - **Tag maintainer:** @hwchase17

The original prompt template is ambiguous because it does not tell whether the tool names should be quoted or not. This PR makes it clear that the tool names should be quoted. It fixes #1358 for Nous-Hermes-Llama2-13b according to my tests.

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
hmmm this might be a bit problematic because it changes a good amount of prompts (which we're hesitant to do to an extent because it could have unanticipated effects)

**Comment by Atry** [comment]
Most open source LLM does not work without this PR. How can it be worse?

**Comment by baskaryan** [comment]
Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

**Comment by hwchase17** [comment]
closing due to inactivity and merge conflicts

**Pull request closed without merging**
