### PR TITLE
Create `.devcontainer`

### PR DESCRIPTION
**Pull request by batmanscode**
An easier way to set up for new contributors using Codespaces or VSCode.

### CODE REVIEW

**Comment by batmanscode** [comment]
Addresses #1038

**Review by hwchase17 — COMMENTED** [review]
what would be the best way for me to test this?

**Comment by batmanscode** [comment]
> what would be the best way for me to test this?


You can go to my branch and start a Codespace like this:
image

Once it's created and your terminal is ready, you can try `make format` or any other commands in your contribution guide and they should just work!

You should also be able to create a Codespace right from this PR like this:
image


More info on Codespaces here: https://docs.github.com/en/codespaces/getting-started/quickstart

**Comment by leo-gan** [comment]
It seems this PR is resolved.

**Pull request closed without merging**
