### PR TITLE
docs: `integrations/providers/unstructured` update

### PR DESCRIPTION
**Pull request by leo-gan**
Updated a page with existing document loaders with links to examples. Fixed formatting of one example.

### CODE REVIEW

**Comment by leo-gan** [comment]
@efriis Could you please check the Vercel errors? I don't have access to them. Thanks!

**Comment by leo-gan** [comment]
@eyurtsev  Could you please check the Vercel errors? I don't have access to them. Thanks!
`docs_build` works fine locally. I've checked all new and changed links.

**Comment by leo-gan** [comment]
@baskaryan  Could you please send me the Vercel errors? I don't have access to them. Thanks!
docs_build works fine locally. I've checked all new and changed links.

**Comment by leo-gan** [comment]
@efriis Could you please send me the Vercel errors? I don't have access to them. Thanks!
docs_build works fine locally. I've checked all new and changed links.

**Comment by baskaryan** [comment]
> @efriis Could you please send me the Vercel errors? I don't have access to them. Thanks! docs_build works fine locally. I've checked all new and changed links.

broken link
```
[ERROR] Error: Docusaurus found broken links!
09:35:41.421 |  
09:35:41.421 | Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
09:35:41.421 | Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
09:35:41.421 |  
09:35:41.422 | Exhaustive list of all broken links found:
09:35:41.422 |  
09:35:41.422 | - On source page path = /docs/integrations/providers/unstructured:
09:35:41.422 | -> linking to /docs/integrations/document_loaders/unstructured
09:35:41.422
```

**Review by efriis — APPROVED** [review]

**Comment by leo-gan** [comment]
@efriis Thanks!

**Pull request merged**
