### PR TITLE
feat: Added class to support huggingface text generation inference server

### PR DESCRIPTION
**Pull request by gsaivinay**
[Text Generation Inference](https://github.com/huggingface/text-generation-inference) is a Rust, Python and gRPC server for generating text using LLMs.

This pull request add support for self hosted Text Generation Inference servers.

feature: #4280

### CODE REVIEW

**Comment by gsaivinay** [comment]
@dcbark01 😃  coincidence 

I've raised issue #4280 and also PR #4244 but then closed it and recreated this PR so that it'll not be lost in backlog.

**Comment by dcbark01** [comment]
@gsaivinay, awesome, I'm good with whatever is easiest. Thanks for working on this. It should make working with local LLMs a lot easier!

**Comment by gsaivinay** [comment]
@dcbark01 I hope any of the maintainers check either of our PR and approve so that many of us can use this feature.

**Review by dev2049 — COMMENTED** [review]
thanks @gsaivinay! couple comments

**Comment by gsaivinay** [comment]
thanks @dev2049 , I've now updated accordingly.

**Pull request merged**
