### PR TITLE
core: In RunnableSequence pass kwargs to the first step

### PR DESCRIPTION
**Pull request by nfcampos**
- This is a pattern that shows up occasionally in langgraph questions, people chain a graph to something else after, and want to pass the graph some kwargs (eg. stream_mode)

### CODE REVIEW

**Review by efriis — DISMISSED** [review]
Just being clear, this basically make the following easier (and equivalent):

Possible previously:
```
chain = r1.bind(**my_kwargs) | r2.bind(**my_kwargs) | r3.bind(**my_kwargs)
chain.invoke(input)
```

Possible now:
```
chain = r1 | r2 | r3
chain.invoke(input, **my_kwargs)
```

**Comment by nfcampos** [comment]
No, kwargs are passed only to first step in sequence

**Comment by efriis** [comment]
That feels unintuitive to me. I have a slight preference for requiring people to `bind()` in this case. 

For the specific case of graph into something else, why not
```
chain = graph.bind(**my_kwargs) | my_next_step
chain.invoke(input)
```

An equivalently valid use case feels like having some sort of "pre" step before the graph that computes/gathers inputs, which wouldn't work for this interface

**Comment by efriis** [comment]
Or maybe a `RunnableSequence.bind_step(step_num, **kwargs)`?

So would be
```
chain = graph | my_next_step
chain.bind_step(0, **my_kwargs).invoke(input)
```

**Comment by nfcampos** [comment]
No I think this is quite natural? After all the input is also passed only to the first step, not to all others

**Review by efriis — APPROVED** [review]
Fair. Should we add kwarg-forwarding to `RunnableParallel` too?

**Pull request merged**
