### PR TITLE
[Feat] `langchain.register`: dynamically register custom tools and agents

### LINKED ISSUE #1360: Feature Request: Add decorator function to register custom components (agents, tools, etc)
### Motivation

Using configuration files are great for fast prototyping but given the current state of the framework, it is limited to pre-defined agents, tools and other components. Currently the `load_tools()` function is implemented to load pre-defined tools via tool name.

https://github.com/hwchase17/langchain/blob/fe7dbecfe6f5c4f9ad3237148fb25c91cf5be9f6/langchain/agents/load_tools.py#L179

For custom implementations, I don't suppose we can use the above function to load them.

### Proposed solution

I suggest we create a decorator function for all components which can be initialised via config file. We can take inspiration from the ClassyVision project: 

https://github.com/facebookresearch/ClassyVision/blob/74e83dd97afbc9371b336304af09548f5080fa9c/classy_vision/models/__init__.py#L27

Even Pytorch Lightning Flash has a similar concept: https://lightning-flash.readthedocs.io/en/latest/general/registry.html?highlight=registry

### Benefits

Enabling fast prototyping for users in a deep learning research/experimentation fashion can greatly speed up development of applications using LangChain.

### PR DESCRIPTION
**Pull request by ajndkr**
## Description

Closes #1360.

### ✨ Highlights

Introducing `langchain.register` module: collection of decorator functions to dynamically register new tools and agents. This module will allow users to register custom agents or tools with the LangChain's internal registry to load them via config.

### Changelog

- ✨ added `langchain.register` module to register custom tools and agents
- ✅ added unit tests for `langchain.register` module

### TODO

- [x] add `register` module
- [x] write unit tests
- [ ] update docs

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
i think i like this a lot! definitely like it as it makes it easy for anyone to "register" a tool in their code and then call in the loader

are there any downsides to this?

**Comment by hwchase17** [comment]
> That's great to hear!
> 
> I don't think there are any downsides right now because my changes are meant to be backwards compatible. But I do think I'm limiting the potential of this feature. Right now, I am targeting tools and agents. Can you please suggest other components (if any) which can benefit from this `register` feature?

i think tools and agents are teh main ones - those are the ones that we "load from a string reference" the most/only

**Comment by ajndkr** [comment]
alright! I will focus on them for now.

**Comment by ajndkr** [comment]
@hwchase17 I will need some guidance to update the docs. Where do you suggest I add documentation for this feature?

**Comment by hwchase17** [comment]
> @hwchase17 I will need some guidance to update the docs. Where do you suggest I add documentation for this feature?

i can help with docs! fair warning, it may be a bit before i have cycles to review and get this in properly (we'll probably want to do in typescript at the same time)

**Comment by ajndkr** [comment]
> i can help with docs! fair warning, it may be a bit before i have cycles to review and get this in properly (we'll probably want to do in typescript at the same time)

That's alright. In the meantime, I can work on implementing this feature for typescript. I am mainly a python user but this can be a good exercise for me to learn typescript.

**Comment by dev2049** [comment]
stale, closing for now. let me know if there's anything in here we still want

**Pull request closed without merging**
