### PR TITLE
docs: Fix URL formatting in deprecation warnings

### PR DESCRIPTION
**Pull request by artemmukhin**
**Description**

Updated the URLs in deprecation warning messages. The URLs were previously written as raw strings and are now formatted to be clickable HTML links.

Example of a broken link in the current API Reference: https://api.python.langchain.com/en/latest/chains/langchain.chains.openai_functions.extraction.create_extraction_chain_pydantic.html

Screenshot 2024-06-18 at 13 21 07

### CODE REVIEW

**Comment by artemmukhin** [comment]
How to preview API Reference changes? I see that Vercel workflow has been cancelled so `Visit Preview` mentioned in the [Contributing docs](https://python.langchain.com/v0.1/docs/contributing/documentation/technical_logistics/#verify-documentation-changes) doesn't work.

**Comment by eyurtsev** [comment]
@artemmukhin firs time contributors need their PR approved before it'll run and a vercel preview will be generated. Just kicked off the build for you

**Comment by hwchase17** [comment]
i dont think vercel will build these docs (since they are the api reference docs, whcih are built elsewhere)

**Comment by artemmukhin** [comment]
Wow, that's incredibly fast PR processing. Much appreciated!

**Pull request merged**
