### PR TITLE
Batched length functions for text splitters

### PR DESCRIPTION
**Pull request by bhperry**
# Batched length functions for text splitters

Allows text splitters to take advantage of batched length functions instead of only calculating length on a single split at a time. This is particularly noticeable when using tokenized length functions, and even more so with huggingface "fast" tokenizers which have major performance improvements with batched input.

Additionally, by keeping track of the lengths of splits in the RecursiveCharacterTextSplitter and passing them into merge function it reduces the number of times that the same text needs to be re-tokenized.

Experimentally I've found that this speeds up text splitting around 5x when using a tokenized length function (of course depends heavily on the text being split, number of splits required, etc.)

@hwchase17

### CODE REVIEW

**Comment by bhperry** [comment]
@hwchase17 passing local lint and unit-tests now

**Comment by bhperry** [comment]
pinging @hwchase17 for review

**Comment by leo-gan** [comment]
@bhperry Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by bhperry** [comment]
@leo-gan fixed, thanks!

**Comment by leo-gan** [comment]
@baskaryan Please, review this old PR. TNX!

**Comment by bhperry** [comment]
@baskaryan @leo-gan review?

**Comment by hwchase17** [comment]
this is cool but lots of merge conflicts (sorry for delay in review). Now that text splitters is its own package, it should be opened against that

**Pull request closed without merging**
