### PR TITLE
add a "ycall" feature for creating user-friendly backend services eaiser 

### PR DESCRIPTION
**Pull request by pengqu123**
add a "ycall" feature for creating backend services by langchain with user-friendly interactions easier:
Now we can use "call" to return all the intermediate_steps, but when we build services, we usually need a user-friendly way of interaction (waiting for the final result takes too long now). Therefore, we hope to get the intermediate results in real-time, so that our service can synchronize update with external services in real-time. This PR uses "yield" to pass each update of intermediate results, so we can build friendlier service with "ycall".

### CODE REVIEW

**Comment by agola11** [comment]
Hi @pengqu123 thanks for your PR. We currently support custom callback handlers. To kick off events from intermediate results you can implement a `BaseCallbackHandler` and add it to the `CallbackManager`. These events can be sent to client through sockets, server side events or other mechanism.
See here for the code: https://github.com/hwchase17/langchain/blob/master/langchain/callbacks/base.py
See here for example implementation: https://github.com/hwchase17/langchain/blob/master/langchain/callbacks/streamlit.py

Do you explicitly need a generator interface or can you work with Callbacks? Would rather not add a new method to agent if possible.

**Comment by pengqu123** [comment]
@agola11 Thank you very much for your discussion. In fact, we have used the callback approach before, but we encountered many pain points that needed to be investigated or resolved.
(1) SharedCallbackManager is a singleton and is not friendly to concurrency.
(2) When doing chat-related applications, we usually need to record the chatroom_id and message_id, and we need to find a way to pass them to the callback, and we need to support parallel scenarios.
(3) We need to confirm send_event in the custom callback one by one refer to stdout callback.

To be honest, at first, I also didn't think the generator was an elegant solution, but it pragmatically solved all the pain points.
(1) It directly returns results, although the results are yielded step by step, but the generator is a pythonic solution.
(2) Completely use LangChain as an independent module in the backend service.
(3) From a teamwork perspective, researchers only need to provide a better agent and an example, and engineers can directly wrap them into backend services. Researchers do not need to know about business scenarios such as chatroom_id and message_id, and backend engineers do not need to know about LangChain's code such as callbacks.

**Comment by agola11** [comment]
@pengqu123 thanks for all of that context! Very helpful. Here are some of my points related to your discussion.

(1) Can you elaborate on this? SharedCallbackManager is actually a thread safe singleton but the problem is that custom callback handlers themselves might not be. There are a couple scenarios in which you might not want to use `SharedCallbackManager` in favor of the local version `CallbackManager`. One scenario is when you're using asyncio, which uses an event loop on one thread. To avoid collisions in callback handling, you can create a new agent with a new local callback manager on every new request. This callbackhandler can be instantiated with the detail of a particular request (i.e. client id, socket connection, etc.)
Here is a snippet in which we are using local callback managers in chatlangchain: https://github.com/hwchase17/chat-langchain/blob/master/query_data.py. ... The other scenario is when you don't want to worry about making your callback handlers thread-safe. In the context of a flask application or similar framework, each request is usually handled by its own worker thread, to not worry about thread safety you can avoid global state by instantiating new agents, callback managers, etc for every request.

(2) Can you expand more on parallel scenarios?

(3) Not sure I follow, sorry!

Hope we can figure something out here and sorry if I'm not fully understanding your use case. We think callback handling is generally a more flexible solution for most scenarios and would like to use it as much as possible to avoid having multiple methods doing similar things. If that's totally not possible for your use case then we can think about adding generators in some form.

**Comment by pengqu123** [comment]
@agola11 Thanks for your reply! Let me try to explain（2）and（3）

(2) Can you expand more on parallel scenarios?
There are many requests sent to the backend, and to simplify, each request include query, chatroom_id, and message_id. Therefore, if we send intermediate results out in the custom callback, we must include the chatroom_id and message_id in the response. This way, the generated text of the response can appear in the correct chatroom.

(3) Not sure I follow, sorry!
“We need to confirm send_events in the custom callback one by one refer to stdout callback.” 

Sorry, let me explain this in more detail. This actually describes the work status of backend engineers in the teamwork I mentioned earlier. Because when the backend engineer customizes the callback, they will carefully write the code for sending messages according to langchain/callbacks/stdout.py. However, in fact, this work efficiency is not high. We can imagine that a researcher implements an example and displays the result through the console output. The backend engineer then has to learn how to customize the callback carefully, but in fact, now we can collect intermediate results through return_intermediate_steps=True. Why not yield them through a generator? because while callback handling is a very flexible solution, in real-world work scenarios, both researchers and backend engineers don't want to study it unless it's absolutely necessary.

**Comment by didmar** [comment]
FYI I had exactly the same need and came up with a quick-and-dirty solution: overriding `__call__` and `_call` in the `AgentExecutor` to yield the intermediate results.
See this gist: https://gist.github.com/didmar/112b5886993cea00a6d88c3df39771b6
Would be great to have something like that cleanly integrated.

**Pull request closed without merging**
