### PR TITLE
huggingface: docstrings

### PR DESCRIPTION
**Pull request by leo-gan**
Added missed docstrings. Format docstrings to the consistent format (used in the API Reference)

### CODE REVIEW

**Comment by leo-gan** [comment]
@mateusz-wosinski-ds Could you, please, check the errors in this PR? It is something with the package dependencies. 
Thanks!

**Comment by leo-gan** [comment]
@Jofthomas Could you, please, check the PR errors? It is something with the package dependencies. 
Thanks!

**Comment by ccurme** [comment]
Fixing CI here: https://github.com/langchain-ai/langchain/pull/23197

**Review by ccurme — APPROVED** [review]

**Comment by leo-gan** [comment]
@ccurme Thanks!

**Pull request merged**
