### PR TITLE
Multi-modal RAG for Medical Domain

### PR DESCRIPTION
**Pull request by MSCetin37**
**Description:** This notebook to demonstrate multi-modal RAG which uses both image and text description generated by open source vision models (ex. video-llama, video-llava etc.) as text embeddings and frames as image embeddings to perform vector similarity search using VDMS.

This cookbook aims to leverage a proven framework to enhance system robustness, privacy, and security through the integration of advanced technologies. Key technologies include a Multi-Modal Vector Database, RAG, and Large Language Models (LLMs), which are essential for simplifying the data preparation process, enhancing the integration of multimodal data, and facilitating the effective use of accumulated knowledge, even in offline environments.

This project is driven by the need to reduce the dependency on extensive expert involvement, which often acts as a significant bottleneck in the medical field. By automating and streamlining data queries and responses, the Multi-Modal RAG application will empower medical professionals and researchers to make faster, more informed decisions. Moreover, ensuring data security and privacy is crucial for maintaining the integrity and confidentiality of sensitive medical information, thus fostering trust and compliance with global data protection regulations such as HIPAA and GDPR.

**Issue:** N/A
**Dependencies:** N/A

### CODE REVIEW

**Comment by MSCetin37** [comment]
@ccurme or @eyurtsev could someone please review?

**Comment by MSCetin37** [comment]
@ccurme or @eyurtsev could someone please review??

**Comment by MSCetin37** [comment]
@ccurme or @eyurtsev could someone please review??

**Comment by ccurme** [comment]
There are already multiple multi-modal RAG cookbooks, several of which use the key technologies demonstrated here (e.g., VDMS, OpenCLIPEmbeddings, and Ollama). I'm not sure another is warranted, even if the domain is new. Let me know if I'm mistaken.

**Comment by MSCetin37** [comment]
@ccurme 
This cookbook demonstrates a unique method of searching for image similarity by utilizing metadata to create prompts with VDMS. This approach achieves better performance in terms of image similarity, leading to more relevant metadata information compared to other vector databases. Would you be interested in reconsidering ?

**Pull request closed without merging**
