### PR TITLE
Fix bug in doctran document transformers

### PR DESCRIPTION
**Pull request by liaokongVFX**
The latest doctran library no longer supports asynchrony.

The doctran library has removed support for asynchrony during this modification.
https://github.com/psychic-api/doctran/commit/22ec68d1fefaf3a141083489452ed0f82cb03a88

### CODE REVIEW

**Comment by liaokongVFX** [comment]
@baskaryan

**Comment by baskaryan** [comment]
cc @jasonwcfan

**Comment by jasonwcfan** [comment]
@liaokongVFX thanks for the fix, the intent behind making the library synchronous is to give people flexibility on how they want to run it.

**Comment by liaokongVFX** [comment]
@baskaryan  Hi,baskaryan. Can we merge it now?

**Comment by hwchase17** [comment]
sorry for delay, fixed in https://github.com/langchain-ai/langchain/pull/15264

**Pull request closed without merging**
