### PR TITLE
Removing Dria Index completely

### PR DESCRIPTION
**Pull request by anilaltuner**
Remove Dria from public package LangChain

Description: This PR removes the Dria integration from the public package LangChain. The change eliminates all associated files, references, and dependencies related to Dria to streamline the package and ensure consistency with current project requirements.

Tests and Docs
No new tests are required as this PR pertains to the removal of an existing component.
Updated the documentation to reflect the absence of Dria in the package. Removed any examples or references to Dria in the docs/docs/integrations directory.

### CODE REVIEW

**Comment by anilaltuner** [comment]
Hey Erik! 

I did not noticed documentation about that and try removing myself. 

Dria's retriever component changed to completely different functionality and the library's components are removed. So, all Dria retriever functionality must removed on Langchain Integrations.

Thanks for your help!

**Comment by efriis** [comment]
got it - do/did you work on dria? could you link me to some documentation related to this? [all of their docs](https://dria.co/docs/integrations/langchain) still seem to be up, so I'm going to close this and happy to reopen if

1. it's shown that dria is no longer in service
2. the PR is updated to keep all files and instead remove the Dria implementation to raise an error on init
3. CI is passing

easiest one to get out of the way is [1]!

**Comment by anilaltuner** [comment]
We'll remove docs from our website, this one is deprecated.

The problem is here;

https://python.langchain.com/docs/integrations/retrievers/dria_index/

It's a misdirection for people using Langchain or Dria. For Langchain, the 2nd item seems more accurate. It is most useful to apply 1-2

**Comment by anilaltuner** [comment]
Hey @efriis! Any update on this? 

https://python.langchain.com/docs/integrations/retrievers/dria_index/

Dria docs still available on langchain docs

**Comment by efriis** [comment]
let me know when you remove the docs, or add a warning to that docs page saying these features are deprecated. a bunch of the pages at https://dria.co/docs/ reference the langchain integration and show how to use it

As mentioned before, steps would be:

1. it's shown that dria is no longer in service (e.g. by adding a big banner to the langchain/dria docs at dria.co saying retrieval is no longer in service)
2. the PR is updated to keep all the code and instead remove the Dria implementation to raise an error on init
3. CI is passing

**Comment by anilaltuner** [comment]
Hey @efriis, we removed old version of https://dria.co/docs/  and new version has nothing to do about langchain integration and old version. Can we now remove Dria's langchain documentation page? It misleads Dria's users and usage

**Comment by anilaltuner** [comment]
Hey @efriis, any update on that? Is there an any thing I can help you?

**Pull request closed without merging**
