### PR TITLE
community: Add support for Upstash Vector

### PR DESCRIPTION
**Pull request by CahidArda**
## Description

Adding `UpstashVectorStore` to utilize [Upstash Vector](https://upstash.com/docs/vector/overall/getstarted)!

#17012 was opened to add Upstash Vector to langchain but was closed to wait for filtering. Now filtering is added to Upstash vector and we open a new PR. Additionally, [embedding feature](https://upstash.com/docs/vector/features/embeddingmodels) was added and we add this to our vectorstore aswell.

## Dependencies

[upstash-vector](https://pypi.org/project/upstash-vector/) should be installed to use `UpstashVectorStore`. Didn't update dependencies because of [this comment in the previous PR](https://github.com/langchain-ai/langchain/pull/17012#pullrequestreview-1876522450).

## Tests

Tests are added and they pass. Tests are naturally network bound since Upstash Vector is offered through an API.

There was [a discussion in the previous PR about mocking the unittests](https://github.com/langchain-ai/langchain/pull/17012#pullrequestreview-1891820567). We didn't make changes to this end yet. We can update the tests if you can explain how the tests should be mocked.

### CODE REVIEW

**Review by baskaryan — APPROVED** [review]

**Comment by CahidArda** [comment]
Thanks for the review @baskaryan!

Should we resolve all the failing CI checks to merge this PR or are we waiting for review/approval from other people?

I didn't try to resolve all CI issues because we want to offer some functionality on top of what is possible with the VectorStore interface (like [embeddings](https://upstash.com/docs/vector/features/embeddingmodels)). Since you approved the PR I am not making further changes

**Comment by baskaryan** [comment]
> Thanks for the review @baskaryan!
> 
> Should we resolve all the failing CI checks to merge this PR or are we waiting for review/approval from other people?
> 
> I didn't try to resolve all CI issues because we want to offer some functionality on top of what is possible with the VectorStore interface (like [embeddings](https://upstash.com/docs/vector/features/embeddingmodels)). Since you approved the PR I am not making further changes

Resolving CI failures would be great!

**Comment by CahidArda** [comment]
Hi again @baskaryan,

CI errors are resolved. Used VCR to record the integration tests aswell!

**Comment by CahidArda** [comment]
Hi @baskaryan,

It looks like all tests pass except Vercel deployment, which got `Canceled by a more recent commit in the same branch` error

**Pull request merged**
