### PR TITLE
core[patch]: fix mutating tool calls

### PR DESCRIPTION
**Pull request by ccurme**
In some cases tool calls are mutated when passed through a tool.

### CODE REVIEW

**Comment by ccurme** [comment]
Failing test: https://github.com/langchain-ai/langchain/actions/runs/10097590132/job/27922826716?pr=24677

**Review by eyurtsev — APPROVED** [review]

**Comment by eyurtsev** [comment]
@ccurme is this related to any issues you saw?

**Comment by ccurme** [comment]
> @ccurme is this related to any issues you saw?

Yes, ran into this using this tool: https://github.com/langchain-ai/langchain/blob/dfbd12b38447b37d0f724cba2d1150daacf7ed90/libs/community/langchain_community/tools/requests/tool.py#L50

**Comment by hinthornw** [comment]
This PR (and deepcopying in general) breaks anything containing a lock.

**Comment by hinthornw** [comment]
OOC: why /how would the string/ simple tool mutate it?

**Pull request merged**
