### PR TITLE
community: Add Snowflake model session handling via keyfile and external sessions

### PR DESCRIPTION
**Pull request by zaramzamzam**
# Description

- Implement session creation using keyfile for secure access without password
  - Keyfiles can be encrypted, with passwords stored in SNOWFLAKE_KEYFILE_PASSWORD
- Add session as a parameter for external session management
  - Enables running langchain inside Snowflake with existing session handling
  - External sessions passed to the model are not closed on completion
- Added comprehensive tests:
  - Session creation tests (keyfile, parameter-passed sessions)
  - Tests for varied environment variables and session configurations

- Updated the documentation at [snowflake.ipynb](https://github.com/langchain-ai/langchain/blob/fe87e411f29134c9544c68331c8bff151313cc15/docs/docs/integrations/chat/snowflake.ipynb)

### CODE REVIEW

**Comment by zaramzamzam** [comment]
Hi,

I added some more options to connect to the Snowflake models, but I can only integration test the variant of adding the Session directly and connecting via a keyfile.

**Comment by efriis** [comment]
cc @sfc-gh-nmoiseyev - I think this should be done as part of the move of the snowflake chat models to the integration package https://github.com/langchain-ai/langchain-snowflake

**Comment by zaramzamzam** [comment]
Hi,

I hope the latest commit fixes the errors in the CI/CD pipeline.

For the unittests I mock the package import now which is a bit ugly. Maybe someone has a better idea.

For the integrationtests I removed the option to pass a Session to the model.
- this removes the need to have snowpark installed
- this results in not testing this passing of a session directly

**Comment by zaramzamzam** [comment]
I think now all checks should succeed 🤞

**Comment by zaramzamzam** [comment]
Looks like I forgot to run make format again.

Is there a possibility to have make format, make lint run before commit?
I could not see any pre-commit config.

**Comment by efriis** [comment]
believe some of the session mechanics were superceded by #27753 - if you want to reopen with just the changes related to aliasing feel free!

**Comment by zaramzamzam** [comment]
@efriis Sorry for the delay.

I do not see anything in the mentioned PR that changes the session creation behavior.
From what I read it still only allows username/password authentication.

But not via a Keyfile or directly passing in a Session.

**Pull request closed without merging**
