### PR TITLE
Harrison/map reduce merge

### PR DESCRIPTION
**Pull request by hwchase17**

### CODE REVIEW

**Review by JohnNay — CHANGES_REQUESTED** [review]
Error I get when running the same code that worked before:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 1
----> 1 chain({"input_documents": docs, "question": "What is the primary issue at play here?"}, return_only_outputs=True)

File ~/PycharmProjects/langchain/langchain/chains/base.py:97, in Chain.__call__(self, inputs, return_only_outputs)
     93 if self.verbose:
     94     print(
     95         f"\n\n\033[1m> Entering new {self.__class__.__name__} chain...\033[0m"
     96     )
---> 97 outputs = self._call(inputs)
     98 if self.verbose:
     99     print(f"\n\033[1m> Finished {self.__class__.__name__} chain.\033[0m")

File ~/PycharmProjects/langchain/langchain/chains/combine_documents/base.py:49, in BaseCombineDocumentsChain._call(self, inputs)
     47 # Other keys are assumed to be needed for LLM prediction
     48 other_keys = {k: v for k, v in inputs.items() if k != self.input_key}
---> 49 output = self.combine_docs(docs, **other_keys)
     50 return {self.output_key: output}

File ~/PycharmProjects/langchain/langchain/chains/combine_documents/map_reduce.py:113, in MapReduceDocumentsChain.combine_docs(self, docs, token_max, **kwargs)
    109 while num_tokens is not None and num_tokens > token_max:
    110     new_result_doc_list = _split_list_of_docs(
    111         result_docs, length_func, token_max, **kwargs
    112     )
--> 113     result_docs = _reduce_chunks(
    114         new_result_doc_list, self.combine_document_chain, **kwargs
    115     )
    116     num_tokens = self.combine_document_chain.prompt_length(
    117         result_docs, **kwargs
    118     )
    119 output = self.combine_document_chain.combine_docs(result_docs, **kwargs)

File ~/PycharmProjects/langchain/langchain/chains/combine_documents/map_reduce.py:44, in _reduce_chunks(doc_list, combine_document_chain, **kwargs)
     42 combined_metadata = docs[0].metadata
     43 for doc in docs[1:]:
---> 44     for k, v in doc.metadata:
     45         if k in combined_metadata:
     46             combined_metadata[k] += f", {v}"

ValueError: too many values to unpack (expected 2)
```

**Comment by JohnNay** [comment]
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 chain({"input_documents": docs, "question": "What is the primary issue at play here?"}, return_only_outputs=True)

File ~/PycharmProjects/langchain/langchain/chains/base.py:97, in Chain.__call__(self, inputs, return_only_outputs)
     93 if self.verbose:
     94     print(
     95         f"\n\n\033[1m> Entering new {self.__class__.__name__} chain...\033[0m"
     96     )
---> 97 outputs = self._call(inputs)
     98 if self.verbose:
     99     print(f"\n\033[1m> Finished {self.__class__.__name__} chain.\033[0m")

File ~/PycharmProjects/langchain/langchain/chains/combine_documents/base.py:49, in BaseCombineDocumentsChain._call(self, inputs)
     47 # Other keys are assumed to be needed for LLM prediction
     48 other_keys = {k: v for k, v in inputs.items() if k != self.input_key}
---> 49 output = self.combine_docs(docs, **other_keys)
     50 return {self.output_key: output}

File ~/PycharmProjects/langchain/langchain/chains/combine_documents/map_reduce.py:113, in MapReduceDocumentsChain.combine_docs(self, docs, token_max, **kwargs)
    109 while num_tokens is not None and num_tokens > token_max:
    110     new_result_doc_list = _split_list_of_docs(
    111         result_docs, length_func, token_max, **kwargs
    112     )
--> 113     result_docs = _reduce_chunks(
    114         new_result_doc_list, self.combine_document_chain, **kwargs
    115     )
    116     num_tokens = self.combine_document_chain.prompt_length(
    117         result_docs, **kwargs
    118     )
    119 output = self.combine_document_chain.combine_docs(result_docs, **kwargs)

File ~/PycharmProjects/langchain/langchain/chains/combine_documents/map_reduce.py:46, in _reduce_chunks(doc_list, combine_document_chain, **kwargs)
     44         for k, v in doc.metadata.items():
     45             if k in combined_metadata:
---> 46                 combined_metadata[k] += f", {v}"
     47     result_docs.append(Document(page_content=result, metadata=combined_metadata))
     48 return result_docs

TypeError: unsupported operand type(s) for +=: 'int' and 'str'
```

**Review by JohnNay — CHANGES_REQUESTED** [review]
Wondering if we can do the `_split_list_of_docs` differently potentially. brainstorming some ideas rn

**Comment by JohnNay** [comment]
This branch works now after https://github.com/hwchase17/langchain/pull/344/commits/bf4aa317b9bb6c03b2c9363427ded43513c6c2e1.

**Comment by JohnNay** [comment]
Not a bug, but where are these messages coming from?

```
Token indices sequence length is longer than the specified maximum sequence length for this model (3606 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1098 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1165 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1243 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1315 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1406 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1556 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1662 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1771 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1848 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1962 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (2071 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (2148 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (2203 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (2323 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (2407 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (2528 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (2630 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (2757 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (2899 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (3026 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1039 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1168 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1315 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1397 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1456 > 1024). Running this sequence through the model will result in indexing errors
```

**Comment by hwchase17** [comment]
> Token indices sequence length is longer than the specified maximum sequence length for this model (1456 > 1024). Running this sequence through the model will result in indexing errors

i think thats the huggingface tokenizer...

**Comment by hwchase17** [comment]
> > Token indices sequence length is longer than the specified maximum sequence length for this model (1456 > 1024). Running this sequence through the model will result in indexing errors
> 
> i think thats the huggingface tokenizer...

which is being used to count tokens

**Comment by JohnNay** [comment]
ah, that's what I figured. Prob fine to leave that output from it coming through

**Review by JohnNay — APPROVED** [review]
tested it and it seems to work well.

**Comment by devonbrackbill** [comment]
Just tested it as well, and confirmed it works. (Also getting the lengthy "Token indices sequence length is longer than the specified maximum sequence length for this model", but can ignore it.)

**Comment by gpalrepo** [comment]
I am continuing to the get the message though it still works. Is there anyway to suppress the message

**Pull request merged**
