### PR TITLE
core: update load chat prompt template multi mesages

### PR DESCRIPTION
**Pull request by jhpiedrahitao**
- **Description:** update load chat prompt template  method to allow chat prompt templates 
       with multiple messages (loles) when using file loading (load from config)
  - **Issue:**  https://github.com/langchain-ai/langchain/discussions/21672

### CODE REVIEW

**Review by baskaryan — COMMENTED** [review]
could we add a unit test for the change

**Comment by jhpiedrahitao** [comment]
@baskaryan please take a look when you have the time

**Comment by ccurme** [comment]
Closing as I believe this functionality exists:

```python
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.load import dumpd
from langchain_core.load.load import load
import json

prompt = ChatPromptTemplate(
    [
        ("system", "system message is {system_message}"),
        ("user", "user message is {user_message}"),
    ]
)

with open("foo.json", "w") as f:
  json.dump(dumpd(prompt), f)

with open("foo.json", "r") as f:
  reloaded = load(json.load(f))
```

See guide here: https://python.langchain.com/docs/how_to/serialization/

Let me know if this does not cover your use case. Thank you!

**Comment by jhpiedrahitao** [comment]
@ccurme I think this not covers loading a full conversation (multiple turns with roles in a template), The current implementation loads only one message into the chat template

**Comment by ccurme** [comment]
> @ccurme I think this not covers loading a full conversation (multiple turns with roles in a template), The current implementation loads only one message into the chat template

I may not be understanding the issue. In the example above, `reloaded` will contain multiple messages with different roles.

This appears to replicate and pass the test you added:
```python
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.load import dumpd
from langchain_core.load.load import load
import json

prompt = ChatPromptTemplate(
    [
        ("system", "You are a comedian"),
        ("user", "Tell me a {adjective} joke about {content}."),
    ]
).partial(content="dogs")

with open("foo.json", "w") as f:
  json.dump(dumpd(prompt), f)

with open("foo.json", "r") as f:
  reloaded = load(json.load(f))


expected_prompt = ChatPromptTemplate(
    input_variables=["adjective"],
    partial_variables={"content": "dogs"},
    messages=[
        ("system", "You are a comedian"),
        ("human", "Tell me a {adjective} joke about {content}."),
    ],
)
assert reloaded == expected_prompt
```

Would you mind sharing a failing test that uses the `langchain_core.load` module to illustrate the issue?

**Comment by jhpiedrahitao** [comment]
Hi @ccurme this is the case in which you load the prompt template using the 

load_prompt method from  langchain_core.prompts.loading

in cases where the user has not necessarily initially created ChatPromptTemplate object, but only defined it in the default structure as here libs/core/tests/unit_tests/examples/simple_chat_prompt.json

**Pull request closed without merging**
