### PR TITLE
Add BGE embeddings support

### PR DESCRIPTION
**Pull request by manmax31**
- Description:  [BGE-large](https://huggingface.co/BAAI/bge-large-en) embeddings from BAAI are at the top of [MTEB leaderboard](https://huggingface.co/spaces/mteb/leaderboard). Hence adding support for it.
- Tag maintainer: @baskaryan
- Twitter handle: @ManabChetia3

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
are there any differences between this class and the normal huggingface class?

**Comment by manmax31** [comment]
The only difference is it requires a prompt for retrieval like the Instructor models.

________________________________

**Comment by hwchase17** [comment]
> 

ah, and we cant use the instructor embeddings cause different package and everything?

**Comment by manmax31** [comment]
Yes.

Good thing is Bge supports sentence transformers.
Would have been cleaner if instructor supported sentence transformers as well.

On the other hand, Bge also has their own https://github.com/FlagOpen/FlagEmbedding/tree/master



________________________________

**Review by hwchase17 — APPROVED** [review]
added an example nb, otherwise lgmt

**Pull request merged**
