### PR TITLE
github action: Add dead link check for .mdx files

### PR DESCRIPTION
**Pull request by liugddx**
- **Description:** Add dead link check for .mdx files.   I checked the logs and found that files with .mdx suffix were not checked.
 https://github.com/langchain-ai/langchain/actions/runs/8409525467/job/23026924465#logs
- @baskaryan, @efriis, @eyurtsev, @hwchase17.

### CODE REVIEW

**Comment by liugddx** [comment]
image

**Comment by baskaryan** [comment]
cc @bracesproul

**Comment by eyurtsev** [comment]
thank you @liugddx

**Comment by liugddx** [comment]
> thank you @liugddx

My pleasure～

**Pull request merged**
