### PR TITLE
refactor confluence loader to reduce http requests

### PR DESCRIPTION
**Pull request by haoqixu**
`ConfluenceLoader` fetches the restrictions for each page in `is_public_page()` without backoff retries. This can cause the `requests.exceptions.HTTPError: Rate limit exceeded.` error.

Expand the restrictions of pages when getting page contents to reduce the http requests.

#### Who can review?

Tag maintainers/contributors who might be interested:@eyurtsev

### CODE REVIEW

**Comment by hwchase17** [comment]
this changes existing functionality right?

**Comment by haoqixu** [comment]
> this changes existing functionality right?

No. The PR just changes the params for getting pages to expand the `restrictions` property. So we don't need the additional http requests to get the restrictions when checking if the page is public.

The tests fail because the mocked page content has no `restrictions` property.

Related API Reference: https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-content/#api-wiki-rest-api-content-get

**Comment by leo-gan** [comment]
@haoqixu Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by baskaryan** [comment]
Hi @haoqixu, is this still relevant? Has some merge conflicts. Happy to re-review if you want to update

**Comment by haoqixu** [comment]
I no longer follow this PR. It is ok to close it.

**Pull request closed without merging**
