### PR TITLE
Fix GPT4All bug w/ "n_ctx" param 

### PR DESCRIPTION
**Pull request by rlancemartin**
Running `GPT4All` per the [docs](https://python.langchain.com/docs/modules/model_io/models/llms/integrations/gpt4all), I see:

```
$ from langchain.llms import GPT4All
$ model = GPT4All(model=local_path)
$ model("The capital of France is ", max_tokens=10)
TypeError: generate() got an unexpected keyword argument 'n_ctx'
```

It appears `n_ctx` is [no longer a supported param](https://docs.gpt4all.io/gpt4all_python.html#gpt4all.gpt4all.GPT4All.generate) in the GPT4All API from https://github.com/nomic-ai/gpt4all/pull/1090.

It now uses `max_tokens`, so I set this.

And I also set other defaults used in GPT4All client [here](https://github.com/nomic-ai/gpt4all/blob/main/gpt4all-bindings/python/gpt4all/gpt4all.py).

Confirm it now works:
```
$ from langchain.llms import GPT4All
$ model = GPT4All(model=local_path)
$ model("The capital of France is ", max_tokens=10)
< Model logging > 
"....Paris."
```

### CODE REVIEW

**Comment by rlancemartin** [comment]
@bwv988 @Chae4ek maybe once of you could have a quick skim (since i saw you recently put up PRs related to GPT4All)?

**Comment by Chae4ek** [comment]
`max_tokens` is the same as `n_predict`. According to the docs `n_predict` exists for backwards compatibility, so you can safely replace it with `max_tokens`.
However, `n_ctx` refers to the size of the models' window - maximum number of tokens in conversation that a model can "remember". Models have an upper bound for this param, if it goes beyond it, it can lead to a strange output, but it's fine to have a smaller bound.
idk if they will support this param. You can remove it I guess.

**Comment by rlancemartin** [comment]
> nomic-ai/gpt4all#668

Ya, I've used `n_ctx` with other Llama models. I'm a bit confused though: AFIACT, GPT4All is broken on master b/c we are passing `n_ctx` to the `generate` method of the GPT4All client. Is this reproduced? Did their API change? I assume this used to be a valid parameter.  If others were seeing this bug using GPT4All, I assume there would have been more urgency to fix ASAP (though I'm not sure when it was introduced). Today was the first time I tried using GPT4All, and I noticed that it seemed to be non-functional due to this bug!

**Comment by Chae4ek** [comment]
Here's the breaking change: https://github.com/nomic-ai/gpt4all/commit/46a0762bd5a7e605e9bd63e4f435b482eff026f6#diff-8408b8ad7c4660cb748f61513e5aa4e38cc3cee45f658d28eb16a72c2c47c391L190
not so long ago.

I was looking through their code for fun and it was never implemented. In fact, `n_ctx` is set from the model file, i.e. the `n_ctx` param doesn't affect anything. I hope they will do it though

**Comment by rlancemartin** [comment]
> Here's the breaking change: [nomic-ai/gpt4all@46a0762#diff-8408b8ad7c4660cb748f61513e5aa4e38cc3cee45f658d28eb16a72c2c47c391L190](https://github.com/nomic-ai/gpt4all/commit/46a0762bd5a7e605e9bd63e4f435b482eff026f6#diff-8408b8ad7c4660cb748f61513e5aa4e38cc3cee45f658d28eb16a72c2c47c391L190) not so long ago.
> 
> I was looking through their code for fun and it was never implemented. In fact, `n_ctx` is set from the model file, i.e. the `n_ctx` param doesn't affect anything. I hope they will do it though

Nice find, thanks for clarifying!

**Comment by rlancemartin** [comment]
> Here's the breaking change: [nomic-ai/gpt4all@46a0762#diff-8408b8ad7c4660cb748f61513e5aa4e38cc3cee45f658d28eb16a72c2c47c391L190](https://github.com/nomic-ai/gpt4all/commit/46a0762bd5a7e605e9bd63e4f435b482eff026f6#diff-8408b8ad7c4660cb748f61513e5aa4e38cc3cee45f658d28eb16a72c2c47c391L190) not so long ago.
> 
> I was looking through their code for fun and it was never implemented. In fact, `n_ctx` is set from the model file, i.e. the `n_ctx` param doesn't affect anything. I hope they will do it though

One thing I should be wary of: this PR will cause a breakage for users that (1) update LangChain but (2) do not update the Nomic / GPT4All client. I can add some error handling to make it backwards compatible.

**Comment by transitive-bullshit** [comment]
Would it make sense to add a PR to `gpt4all` to add a `langchain` test to help mitigate future breaking changes?

**Comment by AndriyMulyar** [comment]
This all looks kosher above. Thanks for the quick fix.

 n_ctx is read only parameter that should have never been exposed in gpt4all. The c backend manages it, not the user.

Setting it previously had no effect.

The major version bump of gpt4all now exposes only read/write parameters in generate and should in general be faster.

Please take a look at the chat session mode which makes chatbot session inference much faster by preserving KV caches. Maybe this has a place in langchain.

**Comment by AndriyMulyar** [comment]
> Would it make sense to add a PR to `gpt4all` to add a `langchain` test to help mitigate future breaking changes?

Yes, this would be great.

**Pull request merged**
