### PR TITLE
Add improved sources splitting in BaseQAWithSourcesChain

### LINKED ISSUE #7184: Issue: RetrievalQAWithSourcesChain gives error 'too many values to unpack (expected 2)' after running.
Hello,

I'm using _langchain_ for QA with court case documents. More specifically, the RetrievalQAWithSourcesChain to retrieve the answer and document source information. However, when running the chain with embedded documents, I get the following error:

```
ValueError: too many values to unpack (expected 2)
Traceback:


    response = qa({"question": pregunta}, return_only_outputs=True)
File "C:\Anaconda3\envs\iagen_3_10\lib\site-packages\langchain\chains\base.py", line 166, in __call__
    raise e
File "C:\Anaconda3\envs\iagen_3_10\lib\site-packages\langchain\chains\base.py", line 160, in __call__
    self._call(inputs, run_manager=run_manager)
File "C:\Anaconda3\envs\iagen_3_10\lib\site-packages\langchain\chains\qa_with_sources\base.py", line 132, in _call
    answer, sources = re.split(r"SOURCES:\s", answer)

```

The passed documents are the sections from the court case. I added the following **metadata** fields:

1. Source: PDF file name.
2. Section: Name of the section
3. Section_chunk:  Numeral value used for identification in case the section was divided into chunks.
4. Page: Page where the section chunk starts.

The documents are passed as retriever to the chain with FAISS (FAISS.from_documents(documents, self.embeddings)).

I tried out two approaches (both resulting in the same error): 
1. providing the _load_qa_chain_ as chain 
2. creating it using the class method **_.from_chain_type_**

My question is why does this error ocurrs. And also, if the type of metadata used may cause the errors.
Thank you in advance!

### PR DESCRIPTION
**Pull request by ds-jakub-kucinski**
## Type:
Improvement

---

## Description:
Running QAWithSourcesChain sometimes raises ValueError as mentioned in issue #7184:
```
ValueError: too many values to unpack (expected 2)
Traceback:

    response = qa({"question": pregunta}, return_only_outputs=True)
File "C:\Anaconda3\envs\iagen_3_10\lib\site-packages\langchain\chains\base.py", line 166, in __call__
    raise e
File "C:\Anaconda3\envs\iagen_3_10\lib\site-packages\langchain\chains\base.py", line 160, in __call__
    self._call(inputs, run_manager=run_manager)
File "C:\Anaconda3\envs\iagen_3_10\lib\site-packages\langchain\chains\qa_with_sources\base.py", line 132, in _call
    answer, sources = re.split(r"SOURCES:\s", answer)
```
This is due to LLM model generating subsequent question, answer and sources, that is complement in a similar form as below:
```
<final_answer>
SOURCES: <sources>
QUESTION: <new_or_repeated_question>
FINAL ANSWER: <new_or_repeated_final_answer>
SOURCES: <new_or_repeated_sources>
```
It leads the following line
```
 re.split(r"SOURCES:\s", answer)
```
to return more than 2 elements and result in ValueError. The simple fix is to split also with "QUESTION:\s" and take the first two elements:
```
answer, sources = re.split(r"SOURCES:\s|QUESTION:\s", answer)[:2]
```

Sometimes LLM might also generate some other texts, like alternative answers in a form:
```
<final_answer_1>
SOURCES: <sources>

<final_answer_2>
SOURCES: <sources>

<final_answer_3>
SOURCES: <sources>
```
In such cases it is the best to split previously obtained sources with new line:
```
sources = re.split(r"\n", sources.lstrip())[0]
```

---

## Issue:
Resolves #7184

---

## Maintainer:
@baskaryan

### CODE REVIEW

**Comment by baskaryan** [comment]
could we add some unit tests

**Comment by KentonParton** [comment]
Would it not be preferred to merge all the sources mentioned into one final sources string?

Here is a code snippet to accomplish this:

```python
import re

def extract_sources(answer):
    # Use a regular expression to find all occurrences of "SOURCES:" followed by the list of sources
    sources_matches = re.findall(r"SOURCES:\n((?:- \[.*?\]\(.*?\)\n?)+)", answer)

    # Combine all the matched sources into a single string, separating each source with a newline
    combined_sources = "\n".join(source.strip() for group in sources_matches for source in group.split("\n") if source.strip())

    return f"SOURCES:\n{combined_sources}"


answer = """To write a query, you can use the following methods:

1. Using Pinecone SDK:
```python
const queryResponse = await index.query({
  vector: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
  filter: { genre: { $in: ["comedy", "documentary", "drama"] } },
  topK: 1,
  includeMetadata: true,
});
console.log(queryResponse.data);
```
Source: [Pinecone Documentation - Query Data](https://docs.pinecone.io/docs/query-data)

2. Using cURL:
```bash
curl -i -X POST https://YOUR_INDEX-YOUR_PROJECT.svc.YOUR_ENVIRONMENT.pinecone.io/query \
  -H 'Api-Key: YOUR_API_KEY' \
  -H 'Content-Type: application/json' \
  -d '{
    "vector": [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
    "filter": {"genre": {"$in": ["comedy", "documentary", "drama"]}},
    "topK": 1,
    "includeMetadata": true
  }'
```
Source: [Pinecone Documentation - Metadata Filtering](https://docs.pinecone.io/docs/metadata-filtering)

SOURCES:
- [Pinecone Documentation - Query Data](https://docs.pinecone.io/docs/query-data)
- [Pinecone Documentation - Metadata Filtering](https://docs.pinecone.io/docs/metadata-filtering)

To perform Generative Question-Answering (GQA) using LangChain, you can follow these steps:

1. Initialize a RetrievalQA object:
```python
from langchain.chat_models import ChatOpenAI
from langchain.chains import RetrievalQA

llm = ChatOpenAI(
    openai_api_key=OPENAI_API_KEY,
    model_name='gpt-3.5-turbo',
    temperature=0.0
)

qa = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vectorstore.as_retriever()
)
```

2. Run the query:
```python
qa.run(query)
```

SOURCES:
- [Pinecone Documentation - LangChain](https://docs.pinecone.io/docs/langchain)"""

sources = extract_sources(answer)
print(sources)
```

**Comment by KentonParton** [comment]
@ds-jakub-kucinski what are your thoughts on the above suggestion? I am happy to make the updates and add tests if you'd prefer?

**Comment by ds-jakub-kucinski** [comment]
@KentonParton I believe that merging all sources into a single final sources string might not be the best approach. As I mentioned earlier, there are instances where language models (LLMs) simply reiterate the input question, the previously generated answer, and the sources. Consequently, combining the sources could lead to duplication. Moreover, in cases where the model generates alternative answers, the corresponding sources are directly tied to those alternate answers. Incorporating these into the initial answer could result in inaccuracies.

On the other hand, the model might also generate irrelevant content, such as new questions, answers, and sources. Adding these to the final sources would be inappropriate. While handling alternative responses might seem reasonable, there is no way to handle all possible cases and formats. In many cases, it might even be impossible to decide whether the following text is an alternative response or not just by looking at the string (without additional LLM steps).

Based on our testing, the model consistently produces the first answer and sources that are closely linked to the provided question and context. Thus, we believe that the most accurate approach is to only return the first answer and its associated sources.

Thanks, but there's no need for you to add tests. We are in the process of adding them.

**Comment by ds-jakub-kucinski** [comment]
@baskaryan I moved source splitting into separate method and added unit tests

**Comment by KentonParton** [comment]
Thanks for the details @ds-jakub-kucinski. I hadn't considered sources referenced from previous messages.

**Comment by ds-jakub-kucinski** [comment]
@baskaryan Could you please run the workflows and make a code review?

**Pull request merged**
