### PR TITLE
Template_n/lancedb rag template

### PR DESCRIPTION
**Pull request by akashAD98**
added lancedb template .

### CODE REVIEW

**Comment by akashAD98** [comment]
@efriis can you please check it .its long pending item .

**Review by hwchase17 — COMMENTED** [review]
you have commited some pycache items, those shouldnt be commited

**Comment by akashAD98** [comment]
@hwchase17 thanks for your attention,i just removed it.please check it now

**Comment by efriis** [comment]
They're still there.

**Comment by akashAD98** [comment]
@efriis my bad. removed all now

**Comment by akashAD98** [comment]
Not sure what’s wrong, can someone please help me to fix it?? My code is correct but it’s failing somehow

**Comment by efriis** [comment]
Hey @akashAD98! The error messages should print out both in the files tab as well as if you run `make lint` at the monorepo root locally.

Will close this for now, and feel free to reopen if you get it to pass CI!

**Pull request closed without merging**
