### PR TITLE
docs: add aws support to how-to-guides

### PR DESCRIPTION
**Pull request by ebranchy**
This PR adds support to the how-to documentation for using AWS Bedrock and Sagemaker Endpoints. 

Because AWS services above dont presently use API keys to access LLMs I've amended more of the source code than would normally be expected.

### CODE REVIEW

**Review by theagenticguy — APPROVED** [review]

**Comment by laithalsaadoon** [comment]
@baskaryan Would you mind taking a look? 🙏

**Comment by efriis** [comment]
happy to add ChatBedrock. SagemakerEndpoint actually isn't the right type (it's not a chat model, so it shouldn't be added to the chat model tabs)

**Comment by ebranchy** [comment]
Do you want me to update the PR with just Bedrock?

**Comment by ebranchy** [comment]
@efriis - i've pulled out the SageMaker elements and left just Bedrock.

**Review by efriis — APPROVED** [review]

**Pull request merged**
