### PR TITLE
community: Corrected aload func to be asynchronous from webBaseLoader

### PR DESCRIPTION
**Pull request by yeounhak**
- **Description:** The aload function, contrary to its name, is not an asynchronous function, so it cannot work concurrently with other asynchronous functions.

- **Issue:** #28336 

- **Test: **: Done

- **Docs: ** [here](https://github.com/yeounhak/langchain/blame/e0a95e5646f086c696e43de2a3dac0f230063341/docs/docs/integrations/document_loaders/web_base.ipynb#L201)

- **Lint: ** All checks passed

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Comment by yeounhak** [comment]
I understand you might be busy, but I would greatly appreciate it if you could provide comments on this PR.

@baskaryan @efriis @eyurtsev @ccurme @vbarda @hwchase17

**Review by efriis — COMMENTED** [review]
tapping in @eyurtsev on the WebBaseLoader type ignore in #19936

I think this one might be funky for backwards compatibility reasons. I'm open to a breaking bugfix here

**Comment by eyurtsev** [comment]
Thanks for spending the time on this! I suggest a way to partially handle the problem without making a breaking change to this code since it's used by a lot of people as is

**Review by eyurtsev — COMMENTED** [review]
sorry forgot to actually submit the comments

**Comment by yeounhak** [comment]
I will make the revisions based on the comments and resubmit the pull request. Thank you!

**Comment by yeounhak** [comment]
✅ [What I've done]
1. Implementing the load() function to execute concurrently in a new thread for Jupyter environment users.

2. Keep aload() as a synchronous version with a warning message stating the following:
   -  Users should replace aload() with load().
   -  Or they can replace it with alazy_load().

3. Add 'a' prefix for the scrape_all function


⏳ [What remains to do]
Include a warning message specifying in which version the aload() function will be updated to an asynchronous version.

**Review by ccurme — APPROVED** [review]
Thank you @yeounhak!

I've made some updates:

- Keep `.scrape_all` as this is in the public API (your updating the tests in other integrations previews what developers would have to do if we deleted it).
- Keep behavior of synchronous loading unchanged.
- Update docs.

So in effect we are
1. Implementing `.ascrape_all` (includes a slight refactor)
2. Implementing `.alazy_load`
3. Deprecating `aload`.

**Pull request merged**
