### PR TITLE
Add OCI Generative AI new model and structured output support

### PR DESCRIPTION
**Pull request by raveharpaz**
- [X] **PR title**: 
 community: Add new model and structured output support

- [X] **PR message**: 
    - **Description:** add support for meta llama 3.2 image handling, and JSON mode for structured output 
    - **Issue:** NA
    - **Dependencies:** NA
    - **Twitter handle:** NA

- [x] **Add tests and docs**: 
  1. we have updated our unit tests,
  2. no changes required for documentation.

- [x] **Lint and test**: 
make format, make lint and make test we run successfully

### CODE REVIEW

**Review by ccurme — COMMENTED** [review]
@raveharpaz do you want to add any tests? Seems scary to update core functionality with no tests.

---

Separately, would you be interested in publishing an Oracle OSS integration package (e.g., `langchain-oracle` or `langchain-oci`)? We've published a walkthrough on this process here:

https://python.langchain.com/docs/contributing/how_to/integrations/

We are encouraging contributors of LangChain integrations to go this route. This way we don't have to be in the loop for reviews, you're able to properly integration test the model, and you have control over versioning.

Docs would continue to be maintained in the `langchain` repo.

Let me know what you think!

**Comment by raveharpaz** [comment]
Hi @ccurme , thanks for the feedback
1. new features have been thoroughly tested with our services/models. these tests cannot be shared due to confidential connection details, and the existing unit tests (based on mocked io) cover the essentials.
2. Yes, the package version is in the works and should be available soon

**Review by ccurme — APPROVED** [review]

**Comment by AndOliver46** [comment]
Hi @raveharpaz, thanks for adding image support for meta 3.2.

By the PR title, it seems that MetaProvider is now supporeting json_mode for structured_output, but isnt working for me...

Getting this error:
Error: TypeError('Unrecognized keyword arguments: response_format')."

With this call:
llm.with_structured_output(None, method="json_mode", include_raw=True).invoke(mensagens)

Do you have any idea? Or maybe works only with Cohere?

**Comment by raveharpaz** [comment]
@AndOliver46 , thanks for the msg. You are correct, it only works for Cohere at the moment. We'll be adding support for llama some time soon

**Pull request merged**
