### PR TITLE
Add support for Postgres full-text cache

### PR DESCRIPTION
**Pull request by jasongill**
The current implementation of FulltextLLMCache does not work with very long prompts on Postgres due to the prompt column being set as a primary key. This patch adds a new schema, PostgresFulltextLLMCache, which uses Postgres TSVector full-text searching for prompts, which not only supports much longer prompts but also works much faster.

Additionally, the SQLAlchemyCache class has been modified to allow for specifying a cache_schema which defaults to the existing FullLLMCache but would allow for changing to the new Postgres-only PostgresFulltextLLMCache or any future custom cache schemas.

Please note that this is my first contribution to a Python project (a language I am just now revisiting, having last used Python 20 years ago), so feel free to reject or tear this apart as you see fit. Thanks for the great work on this project, amazing help in the fast-changing world of LLMs!

### CODE REVIEW

**Comment by jasongill** [comment]
Actually, disregard this - I see that the code I was using locally and copied in would require additional dependences (sqlalchemy_utils) to be added to the project. I'll resubmit a more general PR that just allows for specifying a custom cache schema.

Anyone who's reading this because you had issues using Postgres with the cache, try using some variation of my code but be sure to include
```
from sqlalchemy import Sequence
from sqlalchemy_utils.types.ts_vector import TSVectorType
```
to get the required classes to load.

**Review by hwchase17 — COMMENTED** [review]
this looks great! i think it makes a lot of sense. i think there may be 1 or 2 lint errors, but im happy to clean those up

what would be great though is if you could add a comment to the docstring about `prompt_tsv` - it took me a while to understand what it was and im still not sure i understand whats that nice/needed, so i think more documentation there would be great for the future!

**Comment by hwchase17** [comment]
ah good call on the dependencies. maybe the proper place for that is in the examples then (after the custom cache schema)? like an example notebook?

**Comment by jasongill** [comment]
@hwchase17  Yes, I think the issue right now is that SQLAlchemyCache is hard coded to load the "FullLLMCache" class (schema) so it can't be overridden by the user. Perhaps just doing something similar to my changes to the SQLAlchemyCache class itself:

https://github.com/hwchase17/langchain/pull/469/commits/fb558ed777fbd62e66dcf7bf9ceb809c8d0c1ead#diff-c3df233f3f011b5f20418c51538041dd60bc613da5123df0ebdcdc1637147ab9R69-R100

would allow users to create their own schema classes (like I did) and load them, without having to also make their own copy of the SQLAlchemyCache (which is what I've done to get around this, for now, and didn't realize I had added some imports to my local copy before submitting the PR).

I suspect there's probably a "better way" of doing this as well, since you'd want your custom SQLAlchemy schema to match the same fields/names (response, prompt, llm, idx) required by the SQLAlchemyCache class, but I'm not sure if there is a way to define that

**Pull request closed without merging**
