### PR TITLE
Refactor SQL dialect prompts to eliminate code duplication.

### PR DESCRIPTION
**Pull request by himalayahall**
Refactored code to eliminate multiple copies of the query prompt (prompt per dialect). Now, there is a single copy of the prompt and all placeholders are encapsulated in **SqlQueryDialect** enumeration class. This should make it much easier and less error to add new SQL dialects and/or extend prompt template (e.g. adding new hints for the LLM). Code changes have been formatted, linted, and tested.

#### Who can review?
@hwchase17

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
tbh im actually not a huge fan of this. although this is less duplication, i think it makes it (1) less clear what the prompt for a given dialect is, (2) more complicated to change it for whatever reason (should we need to)

**Comment by himalayahall** [comment]
My 2 cents:

I am of the opinion the re-factoring highlights the **small** differences between the SQL dialects, which (currently) is limited to a couple of SQL functions (row limit and timestamp) and the quote character.

Point taken that the need many arise for dialect specific changes. I feel that a localized place to handle cross-cutting concerns makes it easier to maintain code in the long run. Having said that, this refactor **does not** prohibit copy/paste versions of the prompt, although this could also be accomplished using switch-case on dialect. 

An added benefit is that highlighting the dialect nuances in one place will make developers of **all** dialects understand and appreciate the commonalities and differences.

Cheers.

**Comment by leo-gan** [comment]
@himalayahall Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by himalayahall** [comment]
Hi Leonid,

Having a hard time figuring out lint failures (logs are no longer available on Git). On my machine I had run test prior to commit, but not lint. Any help would be appreciated!

**Comment by himalayahall** [comment]
Refactored to make it MUCH easier to add/delete/modify SQL dialects

**Comment by efriis** [comment]
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

I tend to agree with Harrison that this makes the prompts less readable to folks trying to understand what is actually happening in query construction though.

**Pull request closed without merging**
