### PR TITLE
Upgrade CI poetry version to 1.5.1.

### PR DESCRIPTION
**Pull request by obi1kenobi**
Poetry v1.5.1 was released on May 29, almost 3 months ago. Probably a safe upgrade.

### CODE REVIEW

**Comment by baskaryan** [comment]
think there's somewhere in CONTRIBUTING.md we specify which version folks should use, should update too

**Comment by obi1kenobi** [comment]
Good call, I will look for it. Thoughts on adding a check to CI for the right poetry version as well?

**Comment by baskaryan** [comment]
> Good call, I will look for it. Thoughts on adding a check to CI for the right poetry version as well?

Think that'd be great

**Comment by obi1kenobi** [comment]
I'll add the poetry check to CI in a separate PR.

**Comment by baskaryan** [comment]
should we actually update the poetry.lock file to be 1.5.1 while we're at it

**Comment by baskaryan** [comment]
> should we actually update the poetry.lock file to be 1.5.1 while we're at it

oh see it's a sep pr

**Review by baskaryan — APPROVED** [review]

**Review by eyurtsev — APPROVED** [review]

**Pull request merged**
