### PR TITLE
docs: `ecosystem` change

### PR DESCRIPTION
**Pull request by leo-gan**
move `Additional_resources` items into `Ecosystem` group
Rationale: ToC groups composed from <3 items are too small. These small groups spent precious ToC space and distract user attention.
Here I merge two small groups.

Maintainer responsibilities:
@dev2049

### CODE REVIEW

**Comment by dev2049** [comment]
we had it like this before but got feedback from other folks that ecosystem was a confusing grouping. maybe we wait to gather more feedback?

**Comment by leo-gan** [comment]
> we had it like this before but got feedback from other folks that ecosystem was a confusing grouping. maybe we wait to gather more feedback?

I agree that "Ecosystem" is a too broad term and hence confusing. 
Still, [PyTorch uses this term](https://pytorch.org/ecosystem/). 

This PR is a trade-off between moving "Additional resources" items into "Ecosystem" or opposite, moving "Ecosystem" items into "Additional resources". The latter doesn't work because "YouTube" and "Gallery" can be part of the "Ecosystem" but the "Integrations" cannot be part of the "Additional resources". So, decision was to move "YouTube" and "Gallery" into the "Ecosystem". 

How about renaming "Ecosystem" to "Resources" (as [in PyTorch again](https://pytorch.org/resources/))? 

BTW @hwchase17 insisted on "Ecosystem" vs "Integrations" the last time.

**Comment by leo-gan** [comment]
@hwchase17 Can you, please, give feedback about ^? Thanks!

**Comment by leo-gan** [comment]
@rlancemartin  Please review it. Thanks!

**Comment by leo-gan** [comment]
@baskaryan Please review it. Thanks!

**Pull request closed without merging**
