### PR TITLE
[feat]: Adding memory to Sql Database Chain

### PR DESCRIPTION
**Pull request by keenborder786**
Replace this comment with:
  - Description: SQL Database Chain does not allow to pass in memory to its chain.
  - Issue: This has been requested in issue #6918
  - Tag maintainer:  @hwchase17

### CODE REVIEW

**Comment by keenborder786** [comment]
- I have added memory to both SQLDatabaseChain and SQLDatabaseSequentialChain. So that user can do something like this:
```python

db = SQLDatabase.from_uri("connection_string")
llm = OpenAI(model_name="gpt-3.5-turbo-16k", temperature=0)
memory = ConversationBufferMemory(memory_key="history", input_key="input")
prompt = PromptTemplate(
    input_variables=["input", "table_info", "history"],
    template=_DEFAULT_TEMPLATE,
)
while True:
    db_chain = SQLDatabaseChain.from_llm(
        llm, db, memory=memory, prompt=prompt, verbose=True
    )
    db_chain.run(input())
```

- In order to make memory work with default prompts for SQL-Database Chain, I have added a function called `validate_sql_chain_memory` in newly created utils.py module for `sql_database` chains package. This makes sure that memory_key and input_key are **history** and **input** respectively otherwise it raises a `ValueError`.  
- Also added test for SQL-Database chains with and without memory.

**Comment by keenborder786** [comment]
@hwchase17 please have a look and let me know if this looks good. This is a much needed feature.

**Comment by Soul-AI-LLM** [comment]
Agree. This is much needed feature! Thanks for pulling this!

**Comment by keenborder786** [comment]
@hwchase17 any updates

**Comment by keenborder786** [comment]
Closing this PR since this became really messy. Refactored the current PR features in the newly opened PR:  #7546

**Pull request closed without merging**
