### PR TITLE
chore: change chatCompletion function  to latest api change

### PR DESCRIPTION
**Pull request by Nishkarsh1606**
- **Description:** Updated the method of obtaining chat completions to be compatible with the latest OpenAI API. OpenAI has deprecated `chatCompletion` in their recent release. This update replaces the deprecated method with the current `client.chat.completions` method, ensuring compatibility with the latest API standards.

- **Twitter handle:** @nish306 

I have made sure the PR is passing linting and testing before submitting. I have run `make format`, `make lint`, and `make test` to check this locally.

### CODE REVIEW

**Comment by baskaryan** [comment]
change should already be landed, let me know if what's in master works for you @Nishkarsh1606!

**Comment by Nishkarsh1606** [comment]
@baskaryan i am using the latest version and I am still getting the following error (i installed langchain and openai as dependencies a couple of minutes ago!)
`Traceback (most recent call last):
  File "/Users/nishkarsh/Desktop/Projects/test-langchain/main.py", line 24, in <module>
    llm = ChatOpenAI(temperature=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nishkarsh/Desktop/Projects/test-langchain/.venv/lib/python3.11/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/Users/nishkarsh/Desktop/Projects/test-langchain/.venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  `openai` has no `ChatCompletion` attribute, this is likely due to an old version of the openai package. Try upgrading it with `pip install --upgrade openai`. (type=value_error)`
  
  
  Also, in chat_models i see we're still invoking the previous method for chatCompletion: 
  `        try:
            values["client"] = **openai.ChatCompletion**
        except AttributeError:
            raise ValueError(
                "`openai` has no `ChatCompletion` attribute, this is likely "
                "due to an old version of the openai package. Try upgrading it "
                "with `pip install --upgrade openai`."
            )
        if values["n"] < 1:
            raise ValueError("n must be at least 1.")
        if values["n"] > 1 and values["streaming"]:
            raise ValueError("n must be 1 when streaming.")
        return values`

**Comment by dosuken123** [comment]
@Nishkarsh1606 @baskaryan  Tested locally and confirmed that `0.0.331rc2` fixes the issue.

```
from langchain.chat_models import ChatOpenAI

print(ChatOpenAI().predict("What's your name?"))
#=> I am an AI language model developed by OpenAI and I don't have a personal name. You can simply refer to me as GPT-3. How can I assist you today?
```

```
Shinyas-Air:test-openai shinya$ pip show langchain
Name: langchain
Version: 0.0.331rc2
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author: 
Author-email: 
License: MIT
Location: /Users/shinya/.asdf/installs/python/3.10.13/lib/python3.10/site-packages
Requires: aiohttp, anyio, async-timeout, dataclasses-json, jsonpatch, langsmith, numpy, pydantic, PyYAML, requests, SQLAlchemy, tenacity
Required-by: 
```

```
Shinyas-Air:test-openai shinya$ pip show openai
Name: openai
Version: 1.1.1
Summary: Client library for the openai API
Home-page: 
Author: 
Author-email: OpenAI <support@openai.com>
License: 
Location: /Users/shinya/.asdf/installs/python/3.10.13/lib/python3.10/site-packages
Requires: anyio, distro, httpx, pydantic, tqdm, typing-extensions
Required-by: 
```

**Comment by hwchase17** [comment]
this should be fixed through other prs!

**Pull request closed without merging**
