### PR TITLE
updated API Reference `langchain.agents` functions table

### PR DESCRIPTION
**Pull request by leo-gan**
The `agents.agent_toolkits.conversational_retrieval.openai_functions.create_conversational_retrieval_agent` is a too long name.
It makes the ['agents/functions' table](https://api.python.langchain.com/en/latest/api_reference.html#id2) inside API Reference unreadable.
I've hidden this function from the API Reference.
Note: This is a temporary solution! There should be more elegant solution.

### CODE REVIEW

**Comment by eyurtsev** [comment]
Is there anyway to abbreviate the link created by the auto summary?

**Comment by leo-gan** [comment]
> Is there anyway to abbreviate the link created by the auto summary?

@eyurtsev I've tried this but I didn't find how to do this. It seems, it is inside the [Docusaurus 2](https://docusaurus.io/) package.

**Review by baskaryan — COMMENTED** [review]
@leo-gan @eyurtsev what if for names greater than some length we ... the middle. eg
```
if len(full_name) > 51:
  full_name = full_name[:24] + "..." + full_name[-24:]
```
since it still links to actual docs page shouldn't change user experience too much?

**Comment by leo-gan** [comment]
> @leo-gan @eyurtsev what if for names greater than some length we ... the middle. eg
> 
> ```
> if len(full_name) > 51:
>   full_name = full_name[:24] + "..." + full_name[-24:]
> ```
> 
> since it still links to actual docs page shouldn't change user experience too much?

@baskaryan I can try it. Not sure it works, because it looks like the full_name is used to form a link. So, it may break the link. Let's try it. 
Note: Vercel does not rebuild API Reference for PRs ("View deployment" button in the PR). So, we see the result only after merging, right?

**Comment by leo-gan** [comment]
@baskaryan I've done it. Could you, please, check it?

**Comment by leo-gan** [comment]
@baskaryan Opps... Sorry. This bug is fixed.

**Comment by leo-gan** [comment]
@baskaryan I've done it. Could you, please, check it?

**Comment by baskaryan** [comment]
hm doesn't seem to be showing at all now https://api.python.langchain.com/en/bagatur-api-reference-agents-functions/api_reference.html#module-langchain.agents

**Comment by leo-gan** [comment]
> hm doesn't seem to be showing at all now https://api.python.langchain.com/en/bagatur-api-reference-agents-functions/api_reference.html#module-langchain.agents

Yes, the links for the reduced names are broken, and rows with such links are not generated.
Funny fact: It solves the original problem. The table is readable now.
@baskaryan It is up to you. Is it a broken table OR a missed row in this table :thinking:

**Comment by leo-gan** [comment]
@baskaryan Any comments?

**Comment by efriis** [comment]
Hey @leo-gan - I think it'd be better to display the information in a difficult-to-read way than to have it remove information that is too long for now.

I'll look into ways we can format the outputted table, such that long boxes like this can word wrap (or hide the middle with ...) instead.

**Comment by efriis** [comment]
Done in #13378

**Pull request closed without merging**
