### PR TITLE
fix 'Event loop is closed' error

### PR DESCRIPTION
**Pull request by jxyer**
- Description: `asyncio.run()` will automatically close the event loop and trigger an error when calling `_ProactorBasePipeTransport.__del__`, whereas `asyncio.run_until_complete()` will not.
  - Issue: #10086

### CODE REVIEW

**Review by hwchase17 — APPROVED** [review]
seems reasonable

**Review by hwchase17 — CHANGES_REQUESTED** [review]
actually... i try running the webresearch and this runs into an error

**Comment by jxyer** [comment]
in progress

**Comment by jxyer** [comment]
I added a new pr and turned this off

**Pull request closed without merging**
