### PR TITLE
Add Support for direct usage of llm LLamaCpp in LlamaCppEmbeddings

### PR DESCRIPTION
**Pull request by bfortunato**
- **Description:** Add support for using a llm LLamaCpp directly by introducing a new parameter, `model`, to the `LlamaCppEmbeddings` constructor. This allows users to provide a llm LLamaCpp instance directly, in addition to the existing method of specifying the model path.
- **Issue:** N/A
- **Dependencies:** N/A
- **Tag maintainer:** @bfortunato

### CODE REVIEW

**Comment by daniilpastukhov** [comment]
Any update on this please?

**Comment by bfortunato** [comment]
I don’t know. I’m available if I can do something to go ahead.

**Review by baskaryan — COMMENTED** [review]
could you already initialize as
```python
model = LlamaCpp(...)
embeddings = LlamaCppEmbeddings(client=model.client, model_path=model.model_path)
```
in which case main improvement would be to update validate_environment to check if a client was already passed in, so that it doesn't reload the client for no reason?

**Comment by baskaryan** [comment]
> could you already initialize as
> 
> ```python
> model = LlamaCpp(...)
> embeddings = LlamaCppEmbeddings(client=model.client, model_path=model.model_path)
> ```
> 
> in which case main improvement would be to update validate_environment to check if a client was already passed in, so that it doesn't reload the client for no reason?

closing per ^, let me know if you disagree

**Pull request closed without merging**
