### PR TITLE
Harrison/image

### PR DESCRIPTION
**Pull request by hwchase17**

### CODE REVIEW

**Comment by slavakurilyak** [comment]
Excellent progress! It would be great to see this code finalized as this pull request creates a path for multimodal learning.

**Comment by slavakurilyak** [comment]
Here's my explanation for this pull request, which can be used to update the docs:

---

This code consists of a Jupyter notebook that shows how to generate images from a prompt synthesized using OpenAI Language Learning Model (LLM) and Dall-E API. It can be divided into two parts: running as a chain and running as a tool with an agent.

The first part describes how to generate images from a prompt by creating an LLMChain, setting up the prompt using PromptTemplate, and running DallEAPIWrapper with the prompt. It uses a langchain package to accomplish these tasks.

The second part describes how to run the tool with an agent, which takes advantage of langchain's pre-built functionality and allows the user to interactively execute different actions. In this case, the tool is the Dall-E Image Generator, which can be used to generate images from a text description. The user provides a description of an image to the agent, which then generates the image using Dall-E API and returns it to the user.

To use the code, you would need to set up the OpenAI API key, as well as the required packages, such as Pydantic and OpenCV. You can then run the code in a Jupyter notebook or any other environment that supports it.

**Comment by baskaryan** [comment]
a bit late, but still very much appreciated @slavakurilyak !

**Comment by sanzgiri** [comment]
Hi @baskaryan - its great to see this get merged finally :-) Could I get added to the list of contributors? I did not see my name. Thanks!

**Comment by baskaryan** [comment]
> Hi @baskaryan - its great to see this get merged finally :-) Could I get added to the list of contributors? I did not see my name. Thanks!

Unfortunately the contributor list is auto-generated based on who opened the PR that landed into master (harrison in this case) and im not sure how to override that. But if you want to open up a small follow up PR i'm happy to land, want you to get the credit you deserve! Could be something really simple, like slightly changing a header or comment in the notebook

**Pull request merged**
