### PR TITLE
add where_document filter for chroma

### PR DESCRIPTION
**Pull request by PTTrazavi**
- Description: add where_document filter parameter in Chroma
  - Issue: [10082](https://github.com/langchain-ai/langchain/issues/10082)
  - Dependencies: no
  - Tag maintainer: for a quicker response, tag the relevant maintainer (see below),
  - Twitter handle: no

@hwchase17

### CODE REVIEW

**Comment by baskaryan** [comment]
cc @jeffchuber

**Comment by jeffchuber** [comment]
@baskaryan the feature is good....

@PTTrazavi can we add this consistently across all search methods? can we also add a test for it to ensure that it doesn't get removed in the future?

**Comment by PTTrazavi** [comment]
OK, I added "where_document" across all search methods.

**Comment by baskaryan** [comment]
thanks @PTTrazavi!

**Comment by baskaryan** [comment]
thanks @PTTrazavi!

**Pull request merged**
