### PR TITLE
Add Tags to each Model to Specify Streaming Availibilty

### PR DESCRIPTION
**Pull request by adarshxs**
### Added such tags in documentation for each model, to specify the availability of streaming responses:

Model currently supports streaming &#x2705;

Model currently supports streaming &#x274C;

### CODE REVIEW

**Comment by baskaryan** [comment]
very cool! my only worry is that this'll require some effort to maintain and will only confuse if it isn't maintained. any thoughts on how we might be able to automate?

**Comment by adarshxs** [comment]
Sure I'll look into it and update the PR

**Comment by adarshxs** [comment]
@baskaryan is github workflows a good idea to automate the same?

**Review by hwchase17 — COMMENTED** [review]
hm. i dont love thats its modifying the documentation. imo this is probably a bit too much to be worth adding

i think the best thing to do is just to make sure for models that DO support streaming, we highlight that functionality in the docs

**Comment by adarshxs** [comment]
Fair. Thanks!

**Pull request closed without merging**
