### PR TITLE
Vectara upd2

### PR DESCRIPTION
**Pull request by ofermend**
Update to Vectara integration 
- By user request added "add_files" to take advantage of Vectara capabilities to process files on the backend, without the need for separate loading of documents and chunking in the chain.
- Updated vectara.ipynb example notebook to be broader and added testing of add_file()
 
  @hwchase17 - project lead

### CODE REVIEW

**Review by rlancemartin — APPROVED** [review]
lgtm

**Comment by rlancemartin** [comment]
@ofermend can you please have a look at the Lint errors - 
```
langchain/vectorstores/vectara.py:153: error: Argument "files" to "post" of "Session" has incompatible type "Dict[str, Sequence[Iterable[Sequence[object]]]]"; expected "Optional[Union[Mapping[str, Union[Union[SupportsRead[Union[str, bytes]], str, bytes], Tuple[Optional[str], Union[SupportsRead[Union[str, bytes]], str, bytes]], Tuple[Optional[str], Union[SupportsRead[Union[str, bytes]], str, bytes], str], Tuple[Optional[str], Union[SupportsRead[Union[str, bytes]], str, bytes], str, Mapping[str, str]]]], Iterable[Tuple[str, Union[Union[SupportsRead[Union[str, bytes]], str, bytes], Tuple[Optional[str], Union[SupportsRead[Union[str, bytes]], str, bytes]], Tuple[Optional[str], Union[SupportsRead[Union[str, bytes]], str, bytes], str], Tuple[Optional[str], Union[SupportsRead[Union[str, bytes]], str, bytes], str, Mapping[str, str]]]]]]]"  [arg-type]
langchain/vectorstores/vectara.py:194: error: Unsupported target for indexed assignment ("Optional[Dict[Any, Any]]")  [index]
```

We can get this in once those are resolved.

**Comment by ofermend** [comment]
Should be fixed now

**Comment by rlancemartin** [comment]
Thanks! Just added minor formatting.

**Pull request merged**
