### PR TITLE
fix(llms): on_llm_start could change prompts

### PR DESCRIPTION
**Pull request by zizhong**
- Description: on_llm_start could change prompts
  - Issue: the issue #8725 
  - Tag maintainer: @baskaryan @agola11

### CODE REVIEW

**Comment by 4wuyoon** [comment]
@zizhong  Thanks!!

**Comment by baskaryan** [comment]
not sure i fully understand — are we saying we want callbacks to be able to change prompts? I don't think we do, callbacks should be used for auxiliary functionality that doesn't interfere with core component logic

**Comment by zizhong** [comment]
Here https://github.com/langchain-ai/langchain/issues/8725#issuecomment-1668696107I described a reasonable usage for anonymization. @baskaryan Please feel free to let me know what your thoughts are. Thanks!

**Comment by baskaryan** [comment]
closing per discussion

**Pull request closed without merging**
