### PR TITLE
Awstextract Text Extraction

### PR DESCRIPTION
**Pull request by ghost**
Added aws texract extraction python file to the document loader module . This will help in extracting  images text with aws texract service.

### CODE REVIEW

**Comment by mofahad** [comment]
If wanted I can add pdf extraction with aws textract .

**Review by hwchase17 — COMMENTED** [review]
this is great! some import stuff, but i can clean that up. 

would be very very helpful to have an example notebook

**Comment by hwchase17** [comment]
looks like there is an unexcpetec llm api chain in here? and the notebook is for that?

would love to have a notebook just for aws tesseract

**Comment by mofahad** [comment]
Yeah I accidentally merged my previous branch containing llm api code into this branch.will add notebook for aws textract one.

**Pull request merged**
