### PR TITLE
get rid of google-api-python-client as it is has a huge filesystem footprint

### PR DESCRIPTION
**Pull request by Nantero1**
**Description:** 
Refactored the `GoogleSearchAPIWrapper` to utilize the `requests` library for direct interactions with the Google Custom Search API. This eliminates the dependency on the `google-api-python-client` library, significantly reducing the filesystem footprint.

**Reasoning:** 
Upon closer inspection, I discovered that the `googleapiclient` has a filesystem footprint of 84.8 MiB. This is particularly heavy for applications, especially when the primary use-case is just a single call to Google Search. I use langchain in a AWS lambda environment and getting rid of `google-api-python-client` greatly helped me to be able to run my agent serverless. Further reasoning:

1. **Microservice Architecture:** In a microservices ecosystem, each service ideally should be lightweight and singular in function. Including bulky libraries for minimal features increases the overhead without proportionate benefits.

2. **AWS Lambdas:** AWS Lambda has packaging size limits. For languages like Python, the deployment package size (zipped) should be under 50 MB for direct upload and under 250 MB when uploaded from S3. Reducing unnecessary bulk is crucial for efficient AWS Lambda deployments.

3. **Optimized Docker Images:** Large libraries increase the size of Docker images, which subsequently affects deployment times, scaling efficiency, and even costs (especially in serverless environments where you pay per execution time).

4. **Faster Start Times:** In cloud functions or similar serverless architectures, a lighter package means faster cold starts.

Making this change is a step towards optimized, efficient, and cost-effective deployments, especially in serverless and microservice environments. 

**Dependencies:** 
- `requests`

**Tag maintainer:** 
@hinthornw

Please help me to test this, I hope some GitHub actions will test this PR, the change is rather small and inside a private function, so I hope all tests will pass.

### CODE REVIEW

**Comment by eyurtsev** [comment]
@baskaryan do we want to make this backwards compatible for existing users?

**Comment by eyurtsev** [comment]
@baskaryan upgraded you into a reviewer since you're linting

**Comment by Nantero1** [comment]
> @baskaryan do we want to make this backwards compatible for existing users?

@eyurtsev, what have I missed? My intention was to make a non-breaking change. In my opinion, the user-facing interface isn't changed. I hope existing users won't even notice.

**Comment by Nantero1** [comment]
> @baskaryan upgraded you into a reviewer since you're linting

Thanks for linting, `ruff` seems cool, will use it with my own projects. 

All checks have passed, what do you think about this PR? :)

**Comment by leo-gan** [comment]
@baskaryan Could you, please, review it?

**Review by efriis — COMMENTED** [review]
Hey @BenLinnik ! Sorry for the delay here. I dig this change, and I agree with @baskaryan that we should do this without breaking changes.

The two I see are:
1. If the env doesn't have `requests` already installed, this breaks
2. If I manually configured `search_engine`, this breaks

What are your thoughts on leaving the existing implementation in place, but passing through a `client_type: Union[Literal['googleapiclient'], Literal['requests']] = 'googleapiclient'` and making the new `base_url` optional? If the user opts into using the requests-based one, it would skip the logic around googleapiclient.

**Comment by BenLinnik** [comment]
> Hey @BenLinnik ! Sorry for the delay here. I dig this change, and I agree with @baskaryan that we should do this without breaking changes.
> 
> The two I see are:
> 
> 1. If the env doesn't have `requests` already installed, this breaks
> 2. If I manually configured `search_engine`, this breaks
> 
> What are your thoughts on leaving the existing implementation in place, but passing through a `client_type: Union[Literal['googleapiclient'], Literal['requests']] = 'googleapiclient'` and making the new `base_url` optional? If the user opts into using the requests-based one, it would skip the logic around googleapiclient.

Really like this idea. Would like to improve this PR by implementing it. Sorry for the late response. Will do so in the next days. Thanks for all the reviewers and good comments!

**Comment by hwchase17** [comment]
closing due to inactivity

**Pull request closed without merging**
