### PR TITLE
Add example of running Q&A over structured data using the `Airbyte` loaders and `pandas`

### PR DESCRIPTION
**Pull request by homanp**
- Description: Added example of running Q&A over structured data using the `Airbyte` loaders and `pandas`
  - Dependencies: any dependencies required for this change,
  - Tag maintainer: @hwchase17 
  - Twitter handle: @pelaseyed

### CODE REVIEW

**Comment by baskaryan** [comment]
this is awesome! i'm not sure it deserves it's own notebook though, since it's not really a standalone integration but a combination of two independent ones. maybe this example could be appended to https://python.langchain.com/docs/integrations/document_loaders/airbyte_stripe as a "as an extension, see how you could then analyze loaded data..." kind of section?

**Review by hwchase17 — COMMENTED** [review]
i think this is relatively fine

**Comment by homanp** [comment]
> this is awesome! i'm not sure it deserves it's own notebook though, since it's not really a standalone integration but a combination of two independent ones. maybe this example could be appended to https://python.langchain.com/docs/integrations/document_loaders/airbyte_stripe as a "as an extension, see how you could then analyze loaded data..." kind of section?

Hey!

Should I add it to each loader?

**Comment by homanp** [comment]
> this is awesome! i'm not sure it deserves it's own notebook though, since it's not really a standalone integration but a combination of two independent ones. maybe this example could be appended to https://python.langchain.com/docs/integrations/document_loaders/airbyte_stripe as a "as an extension, see how you could then analyze loaded data..." kind of section?

Perhaps the docs should have a standalone section with recipes for things like this. Would probably decrease the amount issues/questions people create/have in the repo

**Review by hwchase17 — APPROVED** [review]

**Pull request merged**
