### PR TITLE
community: Adding HEADER to the list of supported locations

### PR DESCRIPTION
**Pull request by balvisio**
**Description:** adds headers to the list of supported locations when generating the openai function schema

### CODE REVIEW

**Review by baskaryan — COMMENTED** [review]
believe we'd need to actually add functionality to support header properties, eg see how query_params and path_params properties are used

**Comment by balvisio** [comment]
I created an OpenAPI spec example with a `required = true` header param. I added HEADER to the list of allowed locations and then invoked `openapi_spec_to_openai_fn` and the result seems expected.

Code below:

```
import json

from langchain.chains.openai_functions.openapi import openapi_spec_to_openai_fn
from langchain.utilities.openapi import OpenAPISpec
from langchain_community.tools.openapi.utils.api_models import APIPropertyLocation
from langchain_community.tools.openapi.utils.api_models import SUPPORTED_LOCATIONS

SUPPORTED_LOCATIONS.add(APIPropertyLocation.HEADER)

text = """
{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Swagger Petstore",
    "license": {
      "name": "MIT"
    }
  },
  "servers": [
    {
      "url": "http://petstore.swagger.io/v1"
    }
  ],
  "paths": {
    "/pets/{petId}": {
      "get": {
        "summary": "Info for a specific pet",
        "operationId": "showPetById",
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "required": true,
            "description": "The id of the pet to retrieve",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "header_param",
            "in": "header",
            "required": true,
            "description": "A header param",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "query_param",
            "in": "query",
            "description": "A query param",
            "schema": {
              "type": "string"
            }
          },
        ],
      }
    }
  }
}
"""

spec = OpenAPISpec.from_text(text)
pet_openai_functions, pet_callables = openapi_spec_to_openai_fn(spec)
print(json.dumps(pet_openai_functions, indent=2))
```

Output: As I was expecting there is a `parameters`, a `headers` and `path_params` block. Am I missing something?

```
[
  {
    "name": "showPetById",
    "description": "Info for a specific pet",
    "parameters": {
      "type": "object",
      "properties": {
        "params": {
          "type": "object",
          "properties": {
            "query_param": {
              "type": "string",
              "description": "A query param"
            }
          },
          "required": []
        },
        "headers": {
          "type": "object",
          "properties": {
            "header_param": {
              "type": "string",
              "description": "A header param"
            }
          },
          "required": [
            "header_param"
          ]
        },
        "path_params": {
          "type": "object",
          "properties": {
            "petId": {
              "type": "string",
              "description": "The id of the pet to retrieve"
            }
          },
          "required": [
            "petId"
          ]
        }
      }
    }
  }
]
```

**Comment by baskaryan** [comment]
> I created an OpenAPI spec example with a `required = true` header param. I added `APIPropertyLocation.HEADER` to the list of `SUPPORTED_LOCATIONS` and then invoked `openapi_spec_to_openai_fn` and the result seems expected.
> 
> Code below:
> 
> ```
> import json
> 
> from langchain.chains.openai_functions.openapi import openapi_spec_to_openai_fn
> from langchain.utilities.openapi import OpenAPISpec
> from langchain_community.tools.openapi.utils.api_models import APIPropertyLocation
> from langchain_community.tools.openapi.utils.api_models import SUPPORTED_LOCATIONS
> 
> SUPPORTED_LOCATIONS.add(APIPropertyLocation.HEADER)
> 
> text = """
> {
>   "openapi": "3.0.0",
>   "info": {
>     "version": "1.0.0",
>     "title": "Swagger Petstore",
>     "license": {
>       "name": "MIT"
>     }
>   },
>   "servers": [
>     {
>       "url": "http://petstore.swagger.io/v1"
>     }
>   ],
>   "paths": {
>     "/pets/{petId}": {
>       "get": {
>         "summary": "Info for a specific pet",
>         "operationId": "showPetById",
>         "parameters": [
>           {
>             "name": "petId",
>             "in": "path",
>             "required": true,
>             "description": "The id of the pet to retrieve",
>             "schema": {
>               "type": "string"
>             }
>           },
>           {
>             "name": "header_param",
>             "in": "header",
>             "required": true,
>             "description": "A header param",
>             "schema": {
>               "type": "string"
>             }
>           },
>           {
>             "name": "query_param",
>             "in": "query",
>             "description": "A query param",
>             "schema": {
>               "type": "string"
>             }
>           },
>         ],
>       }
>     }
>   }
> }
> """
> 
> spec = OpenAPISpec.from_text(text)
> pet_openai_functions, pet_callables = openapi_spec_to_openai_fn(spec)
> print(json.dumps(pet_openai_functions, indent=2))
> ```
> 
> Output: As I was expecting there is a `parameters`, a `headers` and `path_params` block. Am I missing something?
> 
> ```
> [
>   {
>     "name": "showPetById",
>     "description": "Info for a specific pet",
>     "parameters": {
>       "type": "object",
>       "properties": {
>         "params": {
>           "type": "object",
>           "properties": {
>             "query_param": {
>               "type": "string",
>               "description": "A query param"
>             }
>           },
>           "required": []
>         },
>         "headers": {
>           "type": "object",
>           "properties": {
>             "header_param": {
>               "type": "string",
>               "description": "A header param"
>             }
>           },
>           "required": [
>             "header_param"
>           ]
>         },
>         "path_params": {
>           "type": "object",
>           "properties": {
>             "petId": {
>               "type": "string",
>               "description": "The id of the pet to retrieve"
>             }
>           },
>           "required": [
>             "petId"
>           ]
>         }
>       }
>     }
>   }
> ]
> ```

ah nice! in that case would we add something like ^ as a unit test

**Comment by balvisio** [comment]
Added unit test

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
