### PR TITLE
feat: Add `task_type` and `auto_truncate` to `VertexAIEmbeddings`

### PR DESCRIPTION
**Pull request by holtskinner**
- Added `task_type` and `auto_truncate` fields to `VertexAIEmbeddings`.
- https://cloud.google.com/python/docs/reference/aiplatform/latest/vertexai.language_models.TextEmbeddingInput

### CODE REVIEW

**Comment by baskaryan** [comment]
cc @lkuligin

**Comment by lkuligin** [comment]
SGTM, but it has been partially addressed here: #13999 (it's waiting to be merged for a while already)

**Comment by baskaryan** [comment]
looks like there's some conflicts after #13999

**Comment by hwchase17** [comment]
going to close, as its been partially addressed and has merge conflicts
if functionality is still missing, please open a new pr off master and we'll take a look!

**Pull request closed without merging**
