### PR TITLE
[agent][property type] Change allowed_tools to Set as Duplicate doesn’t make sense

### PR DESCRIPTION
**Pull request by skcoirz**
- ActionAgent has a property called, `allowed_tools`, which is declared as `List`. It stores all provided tools which is available to use during agent action.
- This collection shouldn’t allow duplicates. The original datatype List doesn’t make sense. Each tool should be unique. Even when there are variants (assuming in the future), it would be named differently in load_tools. 

Test:
- confirm the functionality in an example by initializing an agent with a list of 2 tools and confirm everything works.
```python3
def test_agent_chain_chat_bot():
	from langchain.agents import load_tools
	from langchain.agents import initialize_agent
	from langchain.agents import AgentType
	from langchain.chat_models import ChatOpenAI
	from langchain.llms import OpenAI
	from langchain.utilities.duckduckgo_search import DuckDuckGoSearchAPIWrapper

	chat = ChatOpenAI(temperature=0)
	llm = OpenAI(temperature=0)
	tools = load_tools(["ddg-search", "llm-math"], llm=llm)

	agent = initialize_agent(tools, chat, agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
	agent.run("Who is Olivia Wilde's boyfriend? What is his current age raised to the 0.23 power?")
test_agent_chain_chat_bot()
```
Result:
Screenshot 2023-05-01 at 7 58 11 PM

### CODE REVIEW

**Review by vowelparrot — APPROVED** [review]

**Review by hwchase17 — COMMENTED** [review]
do all existing agent examples work with this? this is changing the type and default, so lets doulbe check that

**Comment by skcoirz** [comment]
@hwchase17 sure I can run through all examples in Jupiter. Anything else you would want me do?

**Comment by skcoirz** [comment]
@vowelparrot please take a look when you have time. Thank you so much. :)

**Comment by hwchase17** [comment]
this breaks a bunch of notebooks

**Comment by skcoirz** [comment]
Weird, I have tested the entry point. Sorry about that. Let me take a look
now.

**Comment by skcoirz** [comment]
@hwchase17 , do you mind sharing which notebook is broken? I just re-tested a few and they all work very well. For example, https://github.com/hwchase17/langchain/blob/63175eb6966fdcc10367b3e32cf8fd5116951fef/docs/modules/agents/agent_executors/examples/agent_vectorstore.ipynb

Would like to know which is broken, so that I can avoid it in the future. Thank you so much.

screenshots of the re-tested notebook on top of this branch.

Screenshot 2023-05-02 at 7 41 53 PM
Screenshot 2023-05-02 at 7 41 44 PM

**Comment by vowelparrot** [comment]
Looks like a lot of the `custom_agent_*` notebooks

**Comment by skcoirz** [comment]
thanks @vowelparrot for the late night response. I’ll take it look at them.

**Comment by skcoirz** [comment]
Ah I know why. When there is no tools provided, the old logic used None as default value vs this PR uses empty Set() as default value. This is not touched because in real use cases, there are always tools provided to agents.

But in the custom example where FakeAgent is provided, it’s not initialized with any tools, so it’s expecting the default None value. When it’s None, it will bypass tools_consistency check. (code here: https://github.com/hwchase17/langchain/blob/master/langchain/agents/agent.py#L632)

This seems wrong. Shouldn’t we always assert all provided tooling be a part of the allowed tools? Otherwise we don’t need the concept of allowed_tools?

**Pull request merged**
