### PR TITLE
langchain: add Jina Reranker in retrievers module

### PR DESCRIPTION
**Pull request by JoanFM**
- **Description:** Adapt JinaEmbeddings to run with the new Jina AI Rerank API
- **Twitter handle:** https://twitter.com/JinaAI_

- [ ] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [ ] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

### CODE REVIEW

**Comment by baskaryan** [comment]
@JoanFM feel free to ping when it's ready for review!

**Comment by JoanFM** [comment]
> @JoanFM feel free to ping when it's ready for review!

Hey @baskaryan ,

This is now ready for review.

**Comment by JoanFM** [comment]
Hey team, is there any timeline for the review of this PR?

FYI @baskaryan

**Review by baskaryan — APPROVED** [review]

**Comment by JoanFM** [comment]
Hey @baskaryan ,

is there anything missing for this to be merged?

**Pull request merged**
