### PR TITLE
community[patch]: fix import in language parser

### PR DESCRIPTION
**Pull request by Rakib-hosen**
- **Description:** Resolving import error in language_parser.py during "from langchain.langchain.text_splitter import Language - **Issue:** the issue #17536
- **Dependencies:** NO
- **Twitter handle:** @iRakibHosen

### CODE REVIEW

**Review by baskaryan — APPROVED** [review]

**Comment by baskaryan** [comment]
thanks @Rakib-hosen!

**Comment by Rakib-hosen** [comment]
@baskaryan thank you so much. this was my first commit to opensource.

**Comment by SomanathSankaran** [comment]
still facing the issue
langchain version (0.15 to 0.17) I have tried
python version '3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]'

**Comment by baskaryan** [comment]
> still facing the issue langchain version (0.15 to 0.17) I have tried python version '3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]'

fix hasn't been released yet, will be in langchain-community==0.0.21

**Pull request merged**
