### PR TITLE
Add real support for RetryParsers?

### PR DESCRIPTION
**Pull request by sudranga**
For retry parser to work, the prompt needs to be available. I don't see how this is hooked up in the current implementation of  LLMChain. The LLMChain must provide the prompt and the corresponding generation to the appropriate output parser (I.e. the llm code must invoke parse_with_prompt). The real output parser could either use the base implementation of parse_with_prompt (i.e. simply call parse) or override it.

Don't think schema changes affects consumers(don't think a lot of people are subclassing output_parser). 

Added test cases.

### CODE REVIEW

**Comment by sudranga** [comment]
@baskaryan I am not sure if RetryOutputParsers are properly supported. I had to do these changes to do retries with the booleanparser used by the llm filter chain (Please see https://github.com/langchain-ai/langchain/issues/11408). Please let me know if the changes make sense?

**Comment by timxieICN** [comment]
Any update on this PR? @sudranga - perhaps you need to tag someone to review it?

**Comment by sudranga** [comment]
@baskaryan Let me know if these changes look appropriate.

**Comment by timxieICN** [comment]
Any update @sudranga @baskaryan ?

**Comment by sudranga** [comment]
@timxieICN I don't have anything to add to this PR. @baskaryan What are your thoughts?

**Comment by louisoutin** [comment]
Currently we cannot really use RetryParser. It expects to use parse_with_prompt instead of parse. Not easy to add it to a given chain. Any news on this PR?

**Comment by sudranga** [comment]
@louisoutin I don't know. For some reason, there's no interest in merging this PR.  If one of the repo owners agrees that this PR is useful, i will resolve the branch conflicts appropriately.

**Comment by Kirushikesh** [comment]
@sudranga one naive question, new to LangChain here. I was going over the documentation of Retry Parsers, how to collect the bad_response in the code. When i add the parser to a LLM Chain and if the output from the llm is not structured i was getting the RuntimeError from the parser. 

To implement the RetryOutputParser you need the bad_response/partial_completion from the previous chain to pass right? How do i get that, in the documentation they initialised the bad_response instead of collecting from the chain directly

**Comment by sudranga** [comment]
@hwchase17 @baskaryan I'm not sure what you want to do with this PR? If you think the PR is appropriate, i can resolve the conflicts.

**Comment by baskaryan** [comment]
Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

**Comment by sudranga** [comment]
@baskaryan Please check.

**Comment by sudranga** [comment]
@baskaryan Do you have any concerns?

**Comment by sudranga** [comment]
@baskaryan I redid the pull request(to address merge conflicts) because i assumed you would take a look. Now, there is a merge conflict again.
This particular topic of retry parsers seems to be of interest to folks. It takes time and effort to produce a PR.  I'm disappointed that this effort has been of no value towards improving langchain.
@hwchase17 ^^

**Comment by austinmw** [comment]
Any updates on this?

**Comment by hwchase17** [comment]
@sudranga thanks for putting in the effort here, and sorry for the delay in reviewing. At this point in time, I am going to close this PR. we are considering how to best support retries for output parsers and will likely involve a larger refactor. I very much apologize for the delay in review and poor communication here

**Pull request closed without merging**
