### PR TITLE
Core: Added partial functionality to PipelinePromptTemplate

### PR DESCRIPTION
**Pull request by Aarya2004**
**Description:** Added extra logic in the PipelinePromptTemplate to support partial assignments primarily by overriding the partial method from BasePromptTemplate
**Issue:** Fixes issue #27868
**Dependencies:** No dependencies required or new dependencies added

**Add tests**
Added test in test_pipeline_prompt.py to check for this case.

**Lint and test**: Done

### CODE REVIEW

**Comment by Aarya2004** [comment]
Hello @efriis! Sorry for the ping, but you had reviewed a PR related to Prompt Templates recently (#28011) so I was hoping you would be able to review this too. Let me know if you have any questions, thank you!

**Review by efriis — COMMENTED** [review]
I think this is ok. Quickly discussing with team to see what we want to do with PipelinePromptTemplate because it's not that intuitive of an abstraction, and it might make sense to just implement as a RunnableSequence of RunnableAssigns instead...

i.e. I think this does the same thing from my understanding:
```
keys_and_prompts: list[tuple[str, PromptTemplate]] = ...


chain = RunnablePassthrough()
for key, prompt in keys_and_prompts:
  chain = chain | RunnablePassthrough.assign(key, prompt)

chain = chain | lambda x: x[keys_and_prompts[-1][0]]
```

**Comment by Aarya2004** [comment]
Sounds good, I wasn't sure if this complied with how PipelinePromptTemplate is 'supposed' to be used but I thought it made sense as a functionality given that the PromptTemplate class implements this function (and PipelinePromptTemplate used a list of these PromptTemplates for its functionality) but I do see how it makes sense through your code. Thanks for taking a look at the code, let me know what you and the team decide!

**Comment by efriis** [comment]
Are you using it personally? If so could you check if the code snippet solves your use case?

**Comment by Aarya2004** [comment]
No I'm not, I'm just trying to fix the issue #27868

**Comment by efriis** [comment]
got it. I can respond there, and I'll close this because it introduces a new bug, where `partial` implements a different interface (stateful mutation instead of stateless wrap)

**Comment by Aarya2004** [comment]
Thank you!

**Pull request closed without merging**
