### PR TITLE
Docs: fix link and missing package

### PR DESCRIPTION
**Pull request by rodrigo-f-nogueira**
**Issue:** fix broken links and missing package on colab example

### CODE REVIEW

**Review by leo-gan — APPROVED** [review]
LGTM
@rodrigo-f-nogueira Thank you for fixing it!

**Comment by rodrigo-f-nogueira** [comment]
Hi @leo-gan, is there something with the code here? I'm asking because I saw multiple failures in the CI jobs but no error shows in this PR

**Comment by leo-gan** [comment]
@rodrigo-f-nogueira Probably, errors are not related to your code. My guess, it is something with the last changes in CI/CD workflows.

**Comment by rodrigo-f-nogueira** [comment]
@leo-gan, it is all good now, right?

**Comment by leo-gan** [comment]
@efriis Can you, please, merge it? Thanks
CC @rodrigo-f-nogueira

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
