### PR TITLE
Feat: Adding token usage for ChatOpenAI. Resolves #1519, resolves #1429 

### LINKED ISSUE #1429: OpenAIChat token usage callback returns 0
When I try to get token usage from **get_openai_callback**, I always get 0. Replacing **OpenAIChat** with **OpenAI** works.

Reproducable example (langchain-0.0.100):

```
from langchain.llms import OpenAIChat
from langchain.callbacks import get_openai_callback

llm = OpenAIChat(temperature=0)

with get_openai_callback() as cb:
    result = llm("Tell me a joke")
    print(cb.total_tokens)
```

### LINKED ISSUE #1519: Token Usage tracking doesn't seem to work for ChatGPT (with streaming off)
Using the callback method described here, the Token Usage tracking doesn't seem to work for ChatOpenAI. Returns "0" tokens. I've made sure I had streaming off, as I think I read that the combination is not supported at the moment.

https://langchain.readthedocs.io/en/latest/modules/llms/examples/token_usage_tracking.html?highlight=token%20count

### PR DESCRIPTION
**Pull request by stephenleo**
- Added in the `on_llm_end` callback into ChatOpenAI's `__call__` 
- fixed multiple linting errors arising from above change
- added in tests to `chat_models/test_openai.py`

### CODE REVIEW

**Comment by lenohard** [comment]
how to make the total_tokens work for streaming mode as well? like 
```
chat = ChatOpenAI(streaming=True, callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]), verbose=True, temperature=0.7)
``
I tested the commit finding it only works for non-streaming mode.

**Comment by stephenleo** [comment]
That's right, the streaming mode doesn't support token_usage even for the OpenAI llm

https://langchain.readthedocs.io/en/latest/modules/llms/streaming_llm.html?highlight=token_usage

**Comment by hwchase17** [comment]
on_llm_end is already called on the BaseLanguageModel class, we just need to propogate things up there

**Comment by hwchase17** [comment]
https://github.com/hwchase17/langchain/pull/1785

**Comment by stephenleo** [comment]
Awesome! #1785 adds much of the functionality of this PR. Will debug the 0 token_usage on the new master and re-submit a cleaner PR

**Pull request closed without merging**
