### PR TITLE
Fix "additional_kwargs["arguments"] already exists in this message, but with a different type." for Azure openai API. 

### PR DESCRIPTION
**Pull request by superken01**
- **Description:** This PR addresses an issue with the OpenAI API streaming response, where initially the key (arguments) is provided but the value is None. Subsequently, it updates with {"arguments": "{\n"}, leading to a type inconsistency that causes an exception. The specific error encountered is ValueError: additional_kwargs["arguments"] already exists in this message, but with a different type. This change aims to resolve this inconsistency and ensure smooth API interactions.
  - **Issue:** None.
  - **Dependencies:** None.
  - **Tag maintainer:** @eyurtsev,

### CODE REVIEW

**Comment by eyurtsev** [comment]
@superken01 Thanks for the contribution! Would you be willing to add unit test, and in code doc-strings to explain the scenario? It's core schema so very helpful to have full test coverage (and definitely more documentation than we currently have)

**Comment by superken01** [comment]
@eyurtsev, I have added a docstring and a unit test. Would you please take a look at it?

**Comment by ruanwz** [comment]
image


after applying  this change, I have the above strange output in langserve using rag-multi-index-router template. can you please check it? Thanks!

**Comment by cdvm-matiria** [comment]
This is still an issue. Is there any way to resolve this?

**Comment by hendrik-hog** [comment]
I would also love to get this merged. I'd be happy to help with anything if it's needed @eyurtsev

**Comment by hwchase17** [comment]
thanks for flagging this - i think this is updated through another pr

thanks again for flagging!

**Pull request closed without merging**
