### PR TITLE
Add ability to add extra fields to AzureSearch VectorStore when adding documents

### LINKED ISSUE #6134: Add ability to add extra fields to AzureSearch VectorStore when adding documents
### Feature request

Currently the AzureSearch VectorStore allows the user to specify a filter that can be used to filter (in the traditional search engine sense) a search index become doing a vector similarity search.  This reduces the search space to improve speed as well as to help focus the vector search on the correct subset of documents.

This filtering feature is very hard to effectively use because the current method for adding documents (add_texts) only allows an id, content, content_vector, and metadata fields.  None of these fields are suitable for filtering, so this requires the user to go back and add fields manually to the search index.

I propose that we allow the end user to specify extra fields that are added when creating these vectors.  The end user would do something like this:

```
extra_fields = {"extra_fields": {"important_field_1": 123, "important_field_2": 456}}

documents.append(doc1)
documents.append(doc2)
documents.append(doc3)

vector_store.add_documents(documents, **extra_fields)
```

Then when the user queries this vector store late they can do something like this:
```
retriever.search_kwargs = {'filters': "important_field_1 eq 123"}

qa = RetrievalQA.from_chain_type(
            llm=llm,
            chain_type="stuff",
            retriever=retriever,
        )
```

### Motivation

My motivation was need for a project I'm working on, but I felt this was a needed general feature, as I stated in the feature request:

This filtering feature is very hard to effectively use because the current method for adding documents (add_texts) only allows an id, content, content_vector, and metadata fields.  None of these fields are suitable for filtering, so this requires the user to go back and add fields manually to the search index.

### Your contribution

Hopefully this makes sense, let me know if any clarifications are needed, once the bug #6131 is fixed I will submit a PR that implements this, I have it working locally and just need to write appropriate unit tests.  Unit tests will not be possible until this bug is fixed.

### PR DESCRIPTION
**Pull request by CameronVetter**
Fixes #6134 

This PR adds a feature to the ACS Vectorstore for adding extra fields beyond the required fields when adding documents into an Azure Cognitive Search Vectorstore.  By adding these extra fields , when later querying the vectorstore, the search engine's filtering capabilities can be used to narrow the number of records when doing the vector comparison.

The usage of this feature is:

```
extra_fields = {"extra_fields": {"important_field_1": 123, "important_field_2": 456}}

documents.append(doc1)
documents.append(doc2)
documents.append(doc3)

vector_store.add_documents(documents, **extra_fields)
```

Then when the user queries this vector store late they can do something like this:
```
retriever.search_kwargs = {'filters': "important_field_1 eq 123"}

qa = RetrievalQA.from_chain_type(
            llm=llm,
            chain_type="stuff",
            retriever=retriever,
        )
```

#### Who can review?

Tag maintainers/contributors who might be interested:
@hwchase17
@dev2049
@ruoccofabrizio

Twitter: poshporcupine

### CODE REVIEW

**Comment by jbueza-railtownai** [comment]
Thanks @CameronVetter -- My team is looking forward to this functionality! Much appreciated! 🙏

**Comment by jbueza-railtownai** [comment]
Hi @CameronVetter -- Just wanted to follow up on this PR, would be great to get an update! 🙏

**Comment by CameronVetter** [comment]
@jbueza-railtownai I do not believe there is anything I can do to more this forward, this needs a maintainer to take the next step.  Which is probably:

@hwchase17
@dev2049

**Comment by ruoccofabrizio** [comment]
@CameronVetter Thanks for the idea. I think this should be a little bit more structural to support an end to end flow. I'll sync with the team next week.

**Comment by jbueza-railtownai** [comment]
Thanks @CameronVetter and @ruoccofabrizio -- we appreciate the update!

**Comment by ruoccofabrizio** [comment]
@CameronVetter integrated in #6843 relying only on the metadata dictionary for additional fields. It supports also custom index creation directly within LangChain.

**Comment by CameronVetter** [comment]
> @CameronVetter integrated in #6843 relying only on the metadata dictionary for additional fields. It supports also custom index creation directly within LangChain.

I'm not sure I agree with copy/pasting this bug fix into a larger feature PR when this valid and simple PR is ready to merge. It would have been better to get this fix in quickly for the people waiting for it when it was ready last week...  I suppose as long as it gets into the code base ASAP...

**Comment by ruoccofabrizio** [comment]
> > @CameronVetter integrated in #6843 relying only on the metadata dictionary for additional fields. It supports also custom index creation directly within LangChain.
> 
> I'm not sure I agree with copy/pasting this bug fix into a larger feature PR when this valid and simple PR is ready to merge. It would have been better to get this fix in quickly for the people waiting for it when it was ready last week... I suppose as long as it gets into the code base ASAP...

First, this is not a bug fix. Second, this is not copy/pasting as you are using an additional field instead of relying on the metadata dictionary which is already part of the standard LangChain document structure. Also, not giving the ability to add extra fields in the index definition as per this PR creates the need to work outside of the framework to add additional fields, which is not ideal.

**Comment by CameronVetter** [comment]
> > > @CameronVetter integrated in #6843 relying only on the metadata dictionary for additional fields. It supports also custom index creation directly within LangChain.
> > 
> > 
> > I'm not sure I agree with copy/pasting this bug fix into a larger feature PR when this valid and simple PR is ready to merge. It would have been better to get this fix in quickly for the people waiting for it when it was ready last week... I suppose as long as it gets into the code base ASAP...
> 
> First, this is not a bug fix. Second, this is not copy/pasting as you are using an additional field instead of relying on the metadata dictionary which is already part of the standard LangChain document structure. Also, not giving the ability to add extra fields in the index definition as per this PR creates the need to work outside of the framework to add additional fields, which is not ideal.

Looking at the overall code structure it sure seems like a lot of the design for this was intended functionality that was missed in the original implementation, thus my calling it a bug.  I could see the argument for it being though, I initially didn't classify it as a bug and only thought of it as one later.

The creation of the index as a side effect of trying to use a vector store that is not there is not desirable, and runs against the pattern of all of the other vector store implementations within langchain, so I'm not sure that adding even more to that is going in the right direction.  I think it would be better to remove that completely and instead give examples of how to create the example and follow already established patterns.

Agreed, using metadata is an improvement.  In the spirit  of getting this merged I'm closing this.  See #6843

**Comment by SimplyJuanjo** [comment]
Any news on that #6843 @CameronVetter @ruoccofabrizio ???

we would really love this #6843 to be merge @hwchase17

**Comment by niknik39** [comment]
Wondering if this will be released, or if there's another way to add and populate extra fields?

**Comment by Hungreeee** [comment]
Azure metadata does not support multi-level index field, thus we have to populate the fields with separate ones rather than using a single "metadata" field. This whole thing needs to be revamped.

**Pull request closed without merging**
