### PR TITLE
Feature : Support for Hugging Face streaming dataset

### PR DESCRIPTION
**Pull request by azamiftikhar1000**
### https://github.com/hwchase17/langchain/issues/2864
Enhanced the Hugging Face loader to support [streaming-enabled](https://huggingface.co/docs/datasets/stream) datasets, expanding its capabilities.

### CODE REVIEW

**Comment by vowelparrot** [comment]
Thanks for the PR! I believe @eyurtsev is working on an iterable data loading interface - we'll try to make sure this fits in with what we're building towards before landing

**Comment by azamiftikhar1000** [comment]
> Thanks for the PR! I believe @eyurtsev is working on an iterable data loading interface - we'll try to make sure this fits in with what we're building towards before landing

Make sense, thank you!

**Comment by eyurtsev** [comment]
Hi @azamiftikhar1000, 

A lazy iteration method was added to the interface: https://github.com/hwchase17/langchain/pull/3659

Notable change is that this method does not have a text splitter. I'm thinking about adding text splitting and batching via a composition, so it won't be included by default when doing lazy iteration.

For context it's a part the following sequence of changes: https://github.com/hwchase17/langchain/pull/2833#issuecomment-1509097756

**Comment by azamiftikhar1000** [comment]
> Hi @azamiftikhar1000,
> 
> A lazy iteration method was added to the interface: #3659
> 
> Notable change is that this method does not have a text splitter. I'm thinking about adding text splitting and batching via a composition, so it won't be included by default when doing lazy iteration.
> 
> For context it's a part the following sequence of changes: [#2833 (comment)](https://github.com/hwchase17/langchain/pull/2833#issuecomment-1509097756)

Actually, it makes a lot of sense to have a new method for handling lazy loading and to implement lazy loading for all iterable loaders, not just Hugging Face. Thanks for that!

**Comment by eyurtsev** [comment]
lazy load now exists on the interface, if anyone wants can also pass through the streaming flag to allow loading without the download

**Pull request closed without merging**
