### PR TITLE
community[patch]: GPTCache pydantic validation error on lookup

### PR DESCRIPTION
**Pull request by theinhumaneme**
Description:
this change fixes the pydantic validation error when looking up from GPTCache, the `ChatOpenAI` class returns `ChatGeneration` as response which is not handled.
use the existing `_loads_generations` and `_dumps_generations` functions to handle it

Trace
```
  File "/home/theinhumaneme/Documents/NebuLogic/conversation-bot/development/scripts/chatbot-postgres-test.py", line 90, in <module>
    print(llm.invoke("tell me a joke"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theinhumaneme/Documents/NebuLogic/conversation-bot/venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 166, in invoke
    self.generate_prompt(
  File "/home/theinhumaneme/Documents/NebuLogic/conversation-bot/venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 544, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theinhumaneme/Documents/NebuLogic/conversation-bot/venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 408, in generate
    raise e
  File "/home/theinhumaneme/Documents/NebuLogic/conversation-bot/venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 398, in generate
    self._generate_with_cache(
  File "/home/theinhumaneme/Documents/NebuLogic/conversation-bot/venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 585, in _generate_with_cache
    cache_val = llm_cache.lookup(prompt, llm_string)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theinhumaneme/Documents/NebuLogic/conversation-bot/venv/lib/python3.11/site-packages/langchain_community/cache.py", line 807, in lookup
    return [
           ^
  File "/home/theinhumaneme/Documents/NebuLogic/conversation-bot/venv/lib/python3.11/site-packages/langchain_community/cache.py", line 808, in <listcomp>
    Generation(**generation_dict) for generation_dict in json.loads(res)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theinhumaneme/Documents/NebuLogic/conversation-bot/venv/lib/python3.11/site-packages/langchain_core/load/serializable.py", line 120, in __init__
    super().__init__(**kwargs)
  File "/home/theinhumaneme/Documents/NebuLogic/conversation-bot/venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Generation
type
  unexpected value; permitted: 'Generation' (type=value_error.const; given=ChatGeneration; permitted=('Generation',))
```

Although I don't seem to find any issues here, here's an [issue](https://github.com/zilliztech/GPTCache/issues/585) raised in GPTCache. Please let me know if I need to do anything else

Thank you

### CODE REVIEW

**Comment by theinhumaneme** [comment]
@eyurtsev could you please look into this and merge if all is okay

Thank You

**Comment by theinhumaneme** [comment]
What do i need to do to get this auto merged? into the source

@eyurtsev please guide me

**Review by eyurtsev — APPROVED** [review]

**Comment by eyurtsev** [comment]
thank you!

**Comment by theinhumaneme** [comment]
@eyurtsev do i need to add the extra line at the end of the file for the checks to be passed?

**Comment by eyurtsev** [comment]
@theinhumaneme i don't remember the rules to be honest : ) -- I mostly rely on `make format` to auto fix linting issues

**Comment by theinhumaneme** [comment]
hello, please check this commit, I used black formatter, as the make format is changing around 400+ files, i looked at the actions logs and fixed the issue where it was failing.

output of my `make format`
```
(venv) theinhumaneme@MSI-DESKTOP:~/Documents/GitHub/langchain/libs/community$ make format
poetry run ruff format .
410 files reformatted, 1215 files left unchanged
poetry run ruff --select I --fix .
warning: `ruff <path>` is deprecated. Use `ruff check <path>` instead.
All checks passed!
```

**Comment by theinhumaneme** [comment]
yay everything passes :D

**Comment by eyurtsev** [comment]
We format using ruff it's mostly compatible with black but runs much faster

**Pull request merged**
