### PR TITLE
feat: Increased compatibility with new and old versions for dalle

### PR DESCRIPTION
**Pull request by majiayu000**
- **Description:** Increased compatibility with all versions openai for dalle, 

This pr add support for openai version from 0 ~ 1.3.

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
we probably dont want to make this Serializable = True yet (we are being pretty selective in how we do that)

Could we remove that from this PR? I like the idea of making it more OpenAI compatible

**Comment by majiayu000** [comment]
> we probably dont want to make this Serializable = True yet (we are being pretty selective in how we do that)
> 
> Could we remove that from this PR? I like the idea of making it more OpenAI compatible


Thanks for the feedback. I delete the serializable function, make it like other tools.

**Review by hwchase17 — COMMENTED** [review]
we can also delete lc_secrets and lc_attributes

**Comment by majiayu000** [comment]
we finally delete all lc functions.

**Review by hwchase17 — APPROVED** [review]
thanks!

**Pull request merged**
