### PR TITLE
fix: filtering in opensearch was not working

### PR DESCRIPTION
**Pull request by RomuloPaiva01**
- changed the filtering inside the query (boolean filtering)

### CODE REVIEW

**Comment by efriis** [comment]
Hey @RomuloPaiva01 ! Could you link the docs for the filter format you're matching? Seems like the recommendations in some related issues have been different

Looks like some potentially related issues:
#12240
#12179

**Comment by baskaryan** [comment]
cc @naveentatikonda

**Review by nicoloboschi — APPROVED** [review]

**Comment by RomuloPaiva01** [comment]
> Hey @RomuloPaiva01 ! Could you link the docs for the filter format you're matching? Seems like the recommendations in some related issues have been different
> 
> Looks like some potentially related issues: #12240 #12179

Hey @efriis thank you very much for the reply!

https://opensearch.org/docs/latest/search-plugins/knn/filter-search-knn/

In the documentation, boolean filtering is described as an after-filtering process. This means that the filtering step should be added after the KNN (as per my change), rather than before, as it was previously.

**Comment by efriis** [comment]
Hey @RomuloPaiva01 ! I actually don't see the array format you've implemented here in the docs you linked. The closest I see is this https://opensearch.org/docs/latest/search-plugins/knn/filter-search-knn/#scoring-script-filter

which implements the existing interface, where `query.bool.filter` is a dict, not a list.

I'm going to close this for now. Could you check your opensearch version and see if maybe you're on an old version?

**Pull request closed without merging**
