### PR TITLE
Fixed issues connecting to self-hosted qdrant server 

### PR DESCRIPTION
**Pull request by misbahsy**
This allows for the option to self-host a qdrant server and call it from the code as shown below:

```python
qdrant_client = QdrantClient(host='localhost', port=6333)
qdrant = Qdrant.from_documents(docs, embeddings, client=qdrant_client, prefer_grpc=True)

### CODE REVIEW

**Review by kacperlukawski — CHANGES_REQUESTED** [review]
@misbahsy Thanks for your contribution! In what scenario do you prefer to create an instance of `QdrantClient` on your own? I would like to know when it might be necessary. With the current setup you can actually do the same thing even simpler, also for self-hosted Qdrant:

```qdrant = Qdrant.from_documents(docs, embeddings, host='localhost', port=6333, prefer_grpc=True)```

I like the idea of putting Qdrant arguments to method params, though, and I will make some changes, as it seems to ease the usage.

**Comment by misbahsy** [comment]
@kacperlukawski , I am looking to self-host Qdrant server to avoid paying for the Qdrant managed cloud service. When I tried using the method you shared, it kept giving me an error pointing at 

```python
qdrant_host = get_from_dict_or_env(kwargs, "host", "QDRANT_HOST")
kwargs.pop("host")
```
Hence, I added the few lines proposed, which fixed it for me. Will appreciate any fix to it tbh.

**Comment by kacperlukawski** [comment]
@misbahsy Could you please share the stack trace of the error?

**Comment by misbahsy** [comment]
sorry for the delay. I tested your suggestion and it works well. Thanks again.

**Pull request closed without merging**
