### PR TITLE
[Documentation] Minor documentation prior to NVIDIA Integration announcement

### PR DESCRIPTION
**Pull request by VKudlay**
- **Description:** Modification of descriptions for marketing purposes and transitioning towards `platforms` directory if possible. 
  - **Issue:** Some marketing opportunities, lodging PR and awaiting later discussions. 
  - 

This PR is intended to be merged when decisions settle/hopefully after further considerations. Submitting as Draft for now. Nobody @'d yet.

### CODE REVIEW

**Comment by VKudlay** [comment]
@hinthornw Hey Will! Sorry to bug again. Minor marketing changes/typo in URL for embedding model link. Was told to ask about platforms again if only while platforms is still in its current state (pre-lightening of the general list to include only a few), but obv if it won't happen then (I can make the reversion/the changes are obvious). The other revisions should just be minor marketing wording and won't cause any issues/(and the obv hyperlink update). Time sensitivity is Monday before some announcements go out.

**Comment by baskaryan** [comment]
looks like there's some merge conflicts to resolve

**Comment by VKudlay** [comment]
Hey @baskaryan! I know there was one in an earlier commit, but it should be resolved... What did you do to find it (so I can resolve it)?

**Comment by VKudlay** [comment]
Oh! I see what you mean. Mb

**Comment by VKudlay** [comment]
@baskaryan Ok! I see! So the most critical issue has already been fixed upstream (which is good; there was a misspelled URL). For the other spelling issues, those are included in this PR. 

One of the asks was to try to move it into `platforms`... but it looks like the `providers` version has already been Google SEO'd. I'm guessing messing with that now would be a bad idea right now, huh?

**Comment by VKudlay** [comment]
Ok! Word stuff, links, markdown, phrasing is all good afaik. Looked over all the links

**Comment by VKudlay** [comment]
@baskaryan Alright, all good now! Just lmk what's the decision on the mdx and it should be fully ready from there :D

**Review by hinthornw — APPROVED** [review]

**Pull request merged**
