### PR TITLE
Switched from PyPDFLoader to pypdfium2

### PR DESCRIPTION
**Pull request by jerrytigerxu**
I mentioned this in the discussions, but I found that using PyPDFLoader (which uses the pypdf module) is considerably slower than using pypdfium2 with its .PdfDocument() method. With pydfium2, the total load time is cut down by over 500%, especially with bulky PDF files.

### CODE REVIEW

**Comment by dev2049** [comment]
thanks for adding! for backwards compatibility think we should just create a new class (also would be a bit strange if PyPDFLoader didn't actually use pypdf)

**Review by hwchase17 — COMMENTED** [review]
+1 to @dev2049 comment! but this is very useful as a new loader!

**Comment by dev2049** [comment]
@jerrytigerxu happy to take over if you'd like

**Comment by jerrytigerxu** [comment]
@dev2049 Sure sounds good!

**Pull request merged**
