### PR TITLE
refactor: extract token text splitter function

### PR DESCRIPTION
**Pull request by JensMadsen**
# Token text splitter for sentence transformers

The current TokenTextSplitter only works with OpenAi models via the `tiktoken` package. This is not clear from the name `TokenTextSplitter`. In this (first PR) a token based text splitter for sentence transformer models is added. In the future I think we should work towards injecting a tokenizer into the TokenTextSplitter to make ti more flexible. 
Could perhaps be reviewed by @dev2049

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
looks great - can we add an exmaple notebook?

**Comment by JensMadsen** [comment]
hi @hwchase17. I have added a notebook AND I have modified the code a little to avoid a warning thrown by the tokenizer. Also the last integration test is now more explicit. Furthermore, I have changed the default chunk overlap (200) which does not make sense for a token based splitter IMHO. Perhaps the same should be done with the tiktoken based splitter?

**Review by hwchase17 — APPROVED** [review]
thanks - lgtm!

**Comment by JensMadsen** [comment]
@hwchase17 Can/should I do something about the failing tests?

**Pull request merged**
