### PR TITLE
community: add VolcEngine Maas V3 support

### PR DESCRIPTION
**Pull request by halfrost**
**Description:**
This PR adds support for VolcEngine Maas V3 to the LangChain community package. It introduces new classes `VolcEngineMaasLLMV3` and `VolcEngineMaasChatV3` that allow users to interact with the VolcEngine Maas V3 API for both LLM and chat functionalities. The implementation includes methods for generating and streaming responses with support for handling stop tokens.

**Issue:**
This PR does not fix a specific issue but adds a new feature to the community package.

**Dependencies:**
- `volcengine-python-sdk` for interacting with the VolcEngine Maas V3 API.

**Twitter handle:** 
If your PR gets announced, and you'd like a mention, we'll gladly shout you out! Please provide your Twitter handle.

### Add tests and docs

- Added unit tests for `VolcEngineMaasLLMV3` and `VolcEngineMaasChatV3` to ensure the new integration works as expected.
- Included an example notebook in `docs/docs/integrations` directory demonstrating the usage of the new VolcEngine Maas V3 integration.

### Lint and test

- Ran `make format` to format the code.
- Ran `make lint` to ensure code quality.
- Ran `make test` to run all tests and ensure everything works correctly.

Additional guidelines followed:
- Optional dependencies are imported within functions.
- No new dependencies were added to `pyproject.toml`.
- Changes are backward compatible.
- The new integration was added to the community package without re-importing in the main `langchain` package.

### CODE REVIEW

**Comment by halfrost** [comment]
@baskaryan

**Comment by halfrost** [comment]
@sbusso @jarib @zeke @deepblue

**Review by efriis — COMMENTED** [review]
fixed some formatting issues. Would it be possible to add this to the existing Volc Engine integration instead of implementing it completely separately?

If you could attach some documentation about the old vs. the new platform both being supported but being different, that would be helpful.

Also, could you take a look at CI failures?

I'll mark this as a draft, and when the above are addressed, please mark it as ready to review again, and I'll take a look!

**Comment by efriis** [comment]
closing as stale

**Comment by halfrost** [comment]
@efriis Hi efriis, we still need this pr. I got delayed by some other tasks, but I’m now able to address the issues mentioned above.

1. Regarding the version issue, our V1 and V3 versions are not compatible, so we need to maintain both versions for now. In the future, we will gradually phase out the V1 version.
2. As for the CI issue, I'll work on fixing it over the next few days.

Please reopen this PR again

**Comment by efriis** [comment]
Hey @halfrost feel free to open a new PR and reference this one when you have a chance to work on it!

**Comment by halfrost** [comment]
Hi @efriis , I open a new PR in here: https://github.com/langchain-ai/langchain/pull/25874. Please help me to review it again. Thanks

**Comment by halfrost** [comment]
Hi @efriis , I open a new PR in here: https://github.com/langchain-ai/langchain/pull/25874. Please help me to review it again. Thanks

**Pull request closed without merging**
