### PR TITLE
Removed redundant and potentially error cause validation for single doc OpenAI embedding

### PR DESCRIPTION
**Pull request by Hase-U**
The line here should actually be a length comparison with the text as token
https://github.com/hwchase17/langchain/blob/18ec22fe56049aaea446406daab6d66d172dd48f/langchain/embeddings/openai.py#L210

But realistically, there is no need to use a function like ```len(encode(text))``` here, and we can use self._get_len_safe_embeddings by default.
All langchain users will need to install tiktoken, but it's natural to think that using tiktoken is also necessary when using openai's embedding.

So the difference from the current situation is
- tiktoken needs to be installed.
- all docs will be encoded at the client side and sent to openai.

### CODE REVIEW

**Comment by Hase-U** [comment]
Also, PR means that the use of ```_get_len_safe_embeddings``` is completely defaulted.
So please note that [this PR](https://github.com/hwchase17/langchain/pull/3778
) over here needs to be merged first.

**Comment by Hase-U** [comment]
#3811 

Also, as pointed out here, embeddings/openai.py imports tiktoken in a different way than elsewhere in langchain, so I adjusted it accordingly.
However, since this is a problem of how to write the code, I think that nothing has changed functionally.
the attribute error seems to be caused by other reason

**Review by shawnesquivel — APPROVED** [review]
I reached the same conclusion on my fork. #3811  has more documentation on why this is the right fix.

**Comment by shawnesquivel** [comment]
Was your embeddings `model` parameter OK with the default (text-embedding-ada-002)? Personally, I had to change model to GPT2 as per #3811.

```
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tiktoken/registry.py", line 60, in get_encoding
    raise ValueError(f"Unknown encoding {encoding_name}")
ValueError: Unknown encoding text-embedding-ada-002
```

https://github.com/hwchase17/langchain/blob/master/langchain/embeddings/openai.py#L107
Change:
model: str = "GPT2"

**Comment by leo-gan** [comment]
@Hase-U Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by efriis** [comment]
This PR no longer lines up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Would you be interested in updating to the new format, or would it be better to close this and someone can work on a new PR off the current state of the library (using this as a reference implementation)?

**Pull request closed without merging**
