### PR TITLE
Support for the spatial geometry datatype for databases

### PR DESCRIPTION
**Pull request by aksharahegde**
**Description**
Support for the spatial geometry datatype for databases while creating embedding in SQLDatabaseChain.

**Issue:** #5799

**Dependencies**
Added **GeoAlchemy2** library

@dev2049

### CODE REVIEW

**Review by hwchase17 — CHANGES_REQUESTED** [review]
sorry what exactly does this do?

regardless, we almost certainly do not want to add as a required dependency

**Comment by leo-gan** [comment]
@aksharahegde Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

**Comment by aksharahegde** [comment]
> @aksharahegde Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

Sure @leo-gan. I will check for adding optional dependency and update the PR. Thanks

**Comment by efriis** [comment]
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

**Comment by vlasvlasvlas** [comment]
how can i help here?

**Pull request closed without merging**
