### PR TITLE
Update defaults for text splitters

### PR DESCRIPTION
**Pull request by nfcampos**
Fixes # (issue)

#### Who can review?

Tag maintainers/contributors who might be interested:

### CODE REVIEW

**Review by dev2049 — COMMENTED** [review]
a bit worried about changing default behavior for these for backwards compatibility

**Comment by nfcampos** [comment]
The current behaviour sounds almost like a bug, given 4000 tokens + a tiny prompt is over the context size of almost all models?

**Comment by nfcampos** [comment]
Updated per review

**Comment by leo-gan** [comment]
@nfcampos Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by efriis** [comment]
@nfcampos closing but happy to reimplement against current master if helpful. I think probably works well now that context windows have grown.

**Pull request closed without merging**
