### PR TITLE
Synthetic data generation

### PR DESCRIPTION
**Pull request by mateusz-wosinski-ds**
### Description

Implements synthetic data generation with the fields and preferences given by the user. Adds showcase notebook.
Corresponding prompt was proposed for langchain-hub.

### Example

```
output = chain({"fields": {"colors": ["blue", "yellow"]}, "preferences": {"style": "Make it in a style of a weather forecast."}})
print(output)

# {'fields': {'colors': ['blue', 'yellow']},
 'preferences': {'style': 'Make it in a style of a weather forecast.'},
 'text': "Good morning! Today's weather forecast brings a beautiful combination of colors to the sky, with hues of blue and yellow gently blending together like a mesmerizing painting."}
```

### Twitter handle 

@deepsense_ai @matt_wosinski

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
i would probably vote to move this into experimental, at least to start

otherwise looks good! if you dont have time, i can also move it

**Comment by mateusz-wosinski-ds** [comment]
moved :)

**Comment by mateusz-wosinski-ds** [comment]
@hwchase17 do you think it is ready to merge?

**Comment by mateusz-wosinski-ds** [comment]
@hwchase17 could you please look at this and merge if everything is fine? :pray: Thank your for all the help! :raised_hands:

**Comment by mateusz-wosinski-ds** [comment]
@hwchase17 I filled a form to langchain-hub with the prompt used here. I guess it is a right way to add this module :thinking:

**Comment by baskaryan** [comment]
thank you @mateusz-wosinski-ds!

**Pull request merged**
