### PR TITLE
Handling inline references to .ipynb files

### PR DESCRIPTION
**Pull request by 169**
### Description

I found that [the OpenAI Adapter document](https://python.langchain.com/docs/integrations/adapters/openai) cannot correctly jump to other internal links. Clicking on the link will download it as an ipynb file.

If it works normally on both jupyter notebook and doc websites, additional processing needs to be done, that is, replacing the link before rendering.

I added 2 scripts and tested `make docs_build` and `./vercel_build.sh`. In both cases, the link can be generated correctly without affecting the original ipynb file content.

@efriis Please review this.

### CODE REVIEW

**Comment by efriis** [comment]
Hey @169 ! Actually going to go with #14325 for now. I'm still iterating on our docs build in pursuit of making everything mdxv2 compatible for docusaurus 3, and the fewer custom scripts we're reliant on through that, the less likely the docs will break again :).

Great shout though! Found a few actually broken links in addition to the ipynb rewrite ones through exploring `ipynb` files for it.

If you find other broken (or downloading) links, please let me know!

**Comment by 169** [comment]
@efriis OK Before, I also considered adding quarto [configuration file](https://quarto.org/docs/projects/scripts.html#pre-and-post-render) to solve the problem, namely `pre-render` and `post-render`, but in fact they also use additional scripts, and it is not easy to determine the source when a problem occurs. It is better to add it directly to in a bash script.

**Comment by 169** [comment]
I did see another format problem, that is, the format displayed by docusaurus admonitions is incorrect. 

For [example](https://python.langchain.com/docs/expression_language/how_to/message_history#example-messages-input-dict-output):
Screenshot 2023-12-06 at 10 20 01 AM

In the tips, the markdown url is not displayed accurately, there are several such links, but they are all displayed incorrectly. but it seems to be a bug in docusaurus.

**Comment by efriis** [comment]
Great catch! @bracesproul started work in #14349 it looks like

**Comment by 169** [comment]
@bracesproul @efriis They don't look as expected:
Screenshot 2023-12-07 at 8 13 04 AM

**Pull request closed without merging**
