### PR TITLE
Fix InvalidVectorQuery error

### PR DESCRIPTION
**Pull request by DSgUY**
- Description:  Fixed the InvalidVectorQuery error in several functions of the AzureSearch class in azuresearch.py. The changes were based on the code found in [this Azure cognitive-search-vector-pr sample](https://github.com/Azure/cognitive-search-vector-pr/blob/main/demo-python/code/azure-search-vector-recall-python-sample.ipynb).
- Issue:  This addresses an observed InvalidVectorQuery error when using AzureSearch with vectors.
- Dependencies: With this fix, the import `from azure.search.documents.models import Vector` is no longer necessary and has been removed.
- Tag maintainer: @rlancemartin, @eyurtsev
- Issue: #7841

### CODE REVIEW

**Comment by finnless** [comment]
What `azure-search-documents` version are you using here? For me this change allows the most recent prerelease `11.4.0b6` to work.

**Comment by DSgUY** [comment]
> What `azure-search-documents` version are you using here? For me this change allows the most recent prerelease `11.4.0b6` to work.

azure-search-documents==11.4.0b6
yes.

**Comment by finnless** [comment]
You should be able to change that requirement here:
https://github.com/hwchase17/langchain/blob/cbf2fc8af892a7fbf0e61f2b0ab4fa5029fcebf6/libs/langchain/pyproject.toml#L114-L114
to:
```toml
 azure-search-documents = {version = "^11.4.0b6", optional = true} 
```

You can also delete this segment.
https://github.com/hwchase17/langchain/blob/cbf2fc8af892a7fbf0e61f2b0ab4fa5029fcebf6/libs/langchain/pyproject.toml#L358-L361

Make sure you rebase or merge your changes to follow the [repo restructure](https://github.com/hwchase17/langchain/discussions/8043).

**Comment by finnless** [comment]
Looks like #6843 will fix this.

**Comment by ruoccofabrizio** [comment]
@DSgUY Please use 11.4.0a20230509004 with the current implementation. When #6843 is merged you can move to 11.4.0b6+

pip install --index-url https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-python/pypi/simple/ azure-search-documents==11.4.0a20230509004

**Comment by DSgUY** [comment]
> Looks like #6843 will fix this.

Ok. So we can close my PR?

**Comment by baskaryan** [comment]
closing for now, let me know if I missed something

**Pull request closed without merging**
