### PR TITLE
Stop sequences in fireworks, plus notebook updates

### PR DESCRIPTION
**Pull request by tjaffri**
The new Fireworks and FireworksChat implementations are awesome! Added in this PR https://github.com/langchain-ai/langchain/pull/11117 thank you @ZixinYang 

However, I think stop words were not plumbed correctly. I've made some simple changes to do that, and also updated the notebook to be a bit clearer with what's needed to use both new models.

Tagging model maintainer @baskaryan

### CODE REVIEW

**Comment by baskaryan** [comment]
lgtm, would be good to have @ZixinYang take a look, too

**Comment by ZixinYang** [comment]
btw, @tjaffri could you also help to change the title of the notebook? https://python.langchain.com/docs/integrations/chat/fireworks
So that it can be Fireworks, not ChatFireworks

**Comment by tjaffri** [comment]
> btw, @tjaffri could you also help to change the title of the notebook? https://python.langchain.com/docs/integrations/chat/fireworks So that it can be Fireworks, not ChatFireworks. Thanks a lot!!!

Good catch... I didn't even notice there was this other notebook! So actually its title is correct... there are TWO notebooks:

1. Fireworks: https://python.langchain.com/docs/integrations/llms/fireworks
2. ChatFireworks: https://python.langchain.com/docs/integrations/chat/fireworks 

I actually only updated the first one and put my chat related notebook updates in that one... I will just move that section from the second one to the first one, which should do the trick...

**Comment by ZixinYang** [comment]
> > btw, @tjaffri could you also help to change the title of the notebook? https://python.langchain.com/docs/integrations/chat/fireworks So that it can be Fireworks, not ChatFireworks. Thanks a lot!!!
> 
> Good catch... I didn't even notice there was this other notebook! So actually its title is correct... there are TWO notebooks:
> 
> 1. Fireworks: https://python.langchain.com/docs/integrations/llms/fireworks
> 2. ChatFireworks: https://python.langchain.com/docs/integrations/chat/fireworks
> 
> I actually only updated the first one and put my chat related notebook updates in that one... I will just move that section from the second one to the first one, which should do the trick...

Sounds good. For the notebook under chat folder. I would like to change the title to Fireworks as well in order to align with other APIs. Other APIs use chat model in the notebook but keeps their name in title. I feel in this way, it is easier to search our Fireworks notebook from side bar.

**Comment by tjaffri** [comment]
> Sounds good. For the notebook under chat folder. I would like to change the title to Fireworks as well in order to align with other APIs. Other APIs use chat model in the notebook but keeps their name in title. I feel in this way, it is easier to search our Fireworks notebook from side bar.

done... please let me know if it looks ok to you

**Comment by ZixinYang** [comment]
@tjaffri Looks good! Thanks again for the change. The instructions in the notebook have also been greatly improved. @baskaryan could you help to merge the changes. Thanks!

**Pull request merged**
