### PR TITLE
community: add async support for redis chat message history 

### PR DESCRIPTION
**Pull request by GrozniyToaster**
Thank you for contributing to LangChain!

- [x] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [ ] **PR message**:
    - **Description:** add async support for redis chat history 
    - **Issue:** the issue # it fixes, if applicable
    - **Dependencies:** any dependencies required for this change
    - **Twitter handle:** if your PR gets announced, and you'd like a mention, we'll gladly shout you out!

- [X] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Review by baskaryan — COMMENTED** [review]
cc @bsbodden

**Comment by bsbodden** [comment]
@GrozniyToaster (cc/ @tylerhutcherson) A new [partner package](https://python.langchain.com/v0.2/docs/contributing/integrations/#partner-package-in-langchain-repo) at https://github.com/langchain-ai/langchain-redis which eventually supersede the community package (AFAIK).  The base VectorStore class in langchain-core has several async methods that use `await run_in_executor`. 
The new package uses the RedisVL library under the cover and RedisVL has full support for redis-py async client, see `get_async_redis_connection` (https://github.com/redis/redis-vl-python/blob/main/redisvl/redis/connection.py) 
So perhaps take a look at the new partner package and see whether this contribution is already covered there or whether the async support can be improved.

**Comment by efriis** [comment]
closing because this should be done in langchain-ai/langchain-redis!

**Comment by GrozniyToaster** [comment]
Hello 

I looked at the package listed above.

It seems more optimized and cool, but it uses redis json (I looked mainly at [chat message memory](https://github.com/langchain-ai/langchain-redis/blob/main/libs/redis/langchain_redis/chat_message_history.py#L44))  

This extension does not seem to be included in [vanilla redis](https://redis.io/docs/latest/develop/data-types/), which is available to everyone

Also, in teams where we work with LLM, we use keydb as an alternative to redis and it also does not support such specific modules

It seems to me that the implementation presented here is also not bad and can work as an option if advanced redis is not used 


Maybe it’s worth adding it to the package under discussion if everything related to this repository is collected there

**Pull request closed without merging**
