### PR TITLE
[Partner]: Fix huggingface tei support

### PR DESCRIPTION
**Pull request by plageon**
Update former pull request: https://github.com/langchain-ai/langchain/pull/22595.

Modified `libs/partners/huggingface/langchain_huggingface/embeddings/huggingface_endpoint.py`, where the API call function does not match current [Text Embeddings Inference API](https://huggingface.github.io/text-embeddings-inference/#/Text%20Embeddings%20Inference/embed).
One example is:
```json
{
  "inputs": "string",
  "normalize": true,
  "truncate": false
}
```
Parameters in `_model_kwargs` are not passed properly in the latest version. By the way, the issue *[why cause 413? #50](https://github.com/huggingface/text-embeddings-inference/issues/50)* might be solved.

### CODE REVIEW

**Comment by plageon** [comment]
@efriis

**Comment by plageon** [comment]
@efriis

**Review by efriis — APPROVED** [review]
lgtm - fyi @Jofthomas

**Comment by efriis** [comment]
https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/inference/_client.py#L207-L215

**Pull request merged**
