### PR TITLE
fix redis/base.py result.content to result.prompt

### PR DESCRIPTION
**Pull request by linusic**
- **Description:** fix redis/base.py `result.content` to `result.prompt`
  - **Issue:** AttributeError: 'Document' object has no attribute 'content'
  - **Dependencies:** None
  
Code
```python
...
# llm = GooglePalm(...)
# embedding = GooglePalmEmbeddings(...)
llm = OpenAI(...)
embedding = OpenAIEmbeddings(...)

redis_cache = RedisSemanticCache(
    redis_url="redis://...:6379", 
    embedding=embedding,
    score_threshold=0.01
)
langchain.llm_cache = redis_cache
...
langchain.llm_cache._cache_dict['...'].similarity_search_with_score(query="hello world")`
```

🛑Debug in LangChain src code:
source

❌Error(OpenAI and PaLM both) and print debug log:
openai

✅**Success and output result shape after the fix(`result.content` to `result.prompt`)**:
```python
# PaLM
[(Document(page_content='hello world', metadata={'id': 'doc:cache:4d4460ad591fb739063de9681c18b075:d4e9339a552a4b2aaf936da3fcdb2f5f', 'return_val': '[{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "output", "Generation"], "kwargs": {"text": "```\\n#include <stdio.h>\\n\\nint main() {\\n  printf(\\"Hello, world!\\\\n\\");\\n  return 0;\\n}\\n```"}}]', 'llm_string': "[('_type', 'google_palm'), ('stop', None)]"}),
  0.0),
 (Document(page_content='reverse the word: hello', metadata={'id': 'doc:cache:4d4460ad591fb739063de9681c18b075:d55bc99d03f946f3a7dc4e1cf363dc23', 'return_val': '[{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "output", "Generation"], "kwargs": {"text": "```\\nolleh\\n```"}}]', 'llm_string': "[('_type', 'google_palm'), ('stop', None)]"}),
  0.2481), ...]
```
```python
# OpenAI
[(Document(page_content='hello world', metadata={'id': 'doc:cache:f4d6fdd07c9be488b08c67b57ea4744c:ecc00d18e86a426190b8ed719f41da95', 'return_val': '[{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "output", "Generation"], "kwargs": {"text": "\\n\\nHello world is a common phrase used to express a greeting or acknowledgment of someone or something. It is often used as a friendly greeting when meeting someone for the first time.", "generation_info": {"finish_reason": "stop", "logprobs": null}}}]', 'llm_string': "[('_type', 'openai'), ('frequency_penalty', 0), ('logit_bias', {}), ('max_tokens', 256), ('model_name', 'text-davinci-003'), ('n', 1), ('presence_penalty', 0), ('request_timeout', None), ('stop', None), ('temperature', 0.7), ('top_p', 1)]"}),
  0.0),
 (Document(page_content='reverse the word: hello', metadata={'id': 'doc:cache:f4d6fdd07c9be488b08c67b57ea4744c:d8314c01a7454f6ebf02253f238269c8', 'return_val': '[{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "output", "Generation"], "kwargs": {"text": "\\n\\nolleh", "generation_info": {"finish_reason": "stop", "logprobs": null}}}]', 'llm_string': "[('_type', 'openai'), ('frequency_penalty', 0), ('logit_bias', {}), ('max_tokens', 256), ('model_name', 'text-davinci-003'), ('n', 1), ('presence_penalty', 0), ('request_timeout', None), ('stop', None), ('temperature', 0.7), ('top_p', 1)]"}),
  0.1373),...]
```

### CODE REVIEW

**Comment by baskaryan** [comment]
cc @Spartee

**Review by Spartee — CHANGES_REQUESTED** [review]
This is actually coming from the fact that the Redis semantic cache overrides the ``content_key`` with ``prompt`` 

see: https://github.com/langchain-ai/langchain/blob/8e0cb2eb84539b249198f98f7647a1f24b2392c2/libs/langchain/langchain/cache.py#L444


and the ``similarity_search_with_scores`` doesn't use ``getattr`` for the ``content_key`` like the ``..by_vector`` does.


And so the correct way to fix this is to do

```python
doc = Document(page_content=getattr(result, self._schema.content_key),
               metadata=metadata)
```

See ``Redis.similarity_search_by_vector`` for the example.

**Comment by linusic** [comment]
> This is actually coming from the fact that the Redis semantic cache overrides the `content_key` with `prompt`
> 
> see:
> 
> https://github.com/langchain-ai/langchain/blob/8e0cb2eb84539b249198f98f7647a1f24b2392c2/libs/langchain/langchain/cache.py#L444
> 
> and the `similarity_search_with_scores` doesn't use `getattr` for the `content_key` like the `..by_vector` does.
> 
> And so the correct way to fix this is to do
> 
> ```python
> doc = Document(page_content=getattr(result, self._schema.content_key),
>                metadata=metadata)
> ```
> 
> See `Redis.similarity_search_by_vector` for the example.

Thank you for your feedback and suggested changes.
When I can't find this attribute, I should indeed think about reflection.

**Review by Spartee — APPROVED** [review]
LGTM 

FYI @baskaryan

**Pull request closed without merging**
