### PR TITLE
community: add milvus hybrid search retriever

### PR DESCRIPTION
**Pull request by BuxianChen**
**Description:**
I add milvus hybrid search retriever. The PR messages remains to complete, and I need some advices for the implementation. The code that I already committed can run successfully, but need to be improved, refactor, lint (I have some problem in format, lint, etc).

Here are my plans, and need some helps:

1. May refactor the code, need some advises. Meanwhile, I need do more tests, I believe there are many bugs in my current implementation.
2. Pass the lint, format, mypy checks, add docstrings and type hints.
3. Add more functional: support hybrid search, single vector search and query (i.e. no vector sematic search) by `MilvusHybridSearchRetriever`.

**Dependencies:**

```
Milvus>=2.4.0
pymilvus>=2.4.0
```

**Docs**
- an example notebook showing its use. It lives in `docs/docs/integrations/retrievers/milvus_hybrid_search.ipynb`.

Thank you for contributing to LangChain!

- [ ] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [ ] **PR message**: ***Delete this entire checklist*** and replace with
    - **Description:** a description of the change
    - **Issue:** the issue # it fixes, if applicable
    - **Dependencies:** any dependencies required for this change
    - **Twitter handle:** if your PR gets announced, and you'd like a mention, we'll gladly shout you out!

- [ ] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  5. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [ ] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, hwchase17.

### CODE REVIEW

**Comment by ohadeytan** [comment]
Hi, that looks very good @BuxianChen! 

As part of a group in IBM Research, we are looking for similar needs: building and using a Milvus vector store with the ability to do hybrid search. We would like to continue to use `langchain` rather than using `pymilvus` directly. 

@efriis can you clarify what is the intention with this and similar PRs related to hybrid search?
I saw that under the `partners` directory you have a `HybridSearchRetriever`, but it lacks the creation of the collection and similar setting that exists in this PR and in regular `MilvusVertorStore`.

We are willing to implement and submit PRs with your guidance.

**Comment by BuxianChen** [comment]
@ohadeytan Hi, I think this PR is out of date, maybe as well as `langchain_community/retrievers/milvus.py`, maybe all things related to Milvus should be placed to `partner` directory.

My PR was completed before their partner [PR](https://github.com/langchain-ai/langchain/pull/21077/files), but theirs has been merged. But as you point out, their implement lack of the creation of the collection and similar setting in regular `MilvusVertorStore`.

I think you can communicate with langchain's core dev, then integrate the missing part to `partner` directory. I think this work should some refactor, as I borrowed a lot code from `MilvusVertorStore`.

Best wishes!

**Comment by BuxianChen** [comment]
By the way, I think the awkward things are:
- `BaseVectorStore` is assumed to with a dense vector embedding.
- `BaseRetriever` has no abstract interface like `add_document`.

I'm also confused about how to deal with that.

**Comment by ohadeytan** [comment]
@BuxianChen, yeah, it seems they are moving to the `partners` directory, but the question remains, did they support this kind of changes and can provide feedback and guidance.

**Comment by zc277584121** [comment]
Thank you for you contribution.
Vector store may refer to "dense vector store", and maybe sparse and hybrid functions need to be placed under Retriever. There is now an implementation of MilvusCollectionHybridSearchRetriever. 
https://python.langchain.com/v0.2/docs/integrations/retrievers/milvus_hybrid_search/
Here what you see is
```python
collection = Collection(
    ...
)
retriever = MilvusCollectionHybridSearchRetriever(
    collection=collection,
    ...
)
```
In the near future, MilvusClient SDK will support hybrid. 
The best ideal implementation will be like this:
```python
from pymilvus import MilvusClient

client = MilvusClient("milvus_demo.db")

MilvusHybridSearchRetriever(
    client=client,
    ...
)
```

**Comment by efriis** [comment]
closing because should be in partner package! seems like it might already be there too

**Pull request closed without merging**
