### PR TITLE
core: fix chain.ainvoke() will result in streaming output

### LINKED ISSUE #20980: chain.ainvoke() will result in streaming output
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

no at the moment

### Error Message and Stack Trace (if applicable)

_No response_

### Description

In langraph we use chain.ainvoke() in inner node and  app.astream_events() for the whole graph app.  But we found out that the chain.ainvoke() output streaming tokens.

We I dived into the code, and found maybe because of the following code:

https://github.com/langchain-ai/langchain/blob/804390ba4bcc306b90cb6d75b7f01a4231ab6463/libs/core/langchain_core/language_models/chat_models.py#L684-L701

`type(self)._astream` is `ChatOpenAI._astream`
`kwargs` is a empty {}, which dose not have `stream` key from params.
The langgraph app have a `LogStreamCallbackHandler` in the run_manager.handlers.
So the `if statement` is `True` and the code generated streaming output which is not expected.

May be you should add key 'stream' to `kwargs` from `params`. And I have tried it solved my problem.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
> Python Version:  3.11.2 (main, Feb 21 2024, 12:24:36) [Clang 15.0.0 (clang-1500.1.0.2.5)]

Package Information
-------------------
> langchain_core: 0.1.46
> langchain: 0.1.16
> langchain_community: 0.0.34
> langsmith: 0.1.22
> langchain_openai: 0.0.6
> langchain_text_splitters: 0.0.1
> langgraph: 0.0.39

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve

### PR DESCRIPTION
**Pull request by Huarong**
Thank you for contributing to LangChain!

- [x] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [x] **PR message**: ***Delete this entire checklist*** and replace with

fix https://github.com/langchain-ai/langchain/issues/20980

- [x] **Add tests and docs**: If you're adding a new integration, please include
test scripts:
```
import asyncio
from langchain_core.runnables import chain
from langchain_openai import ChatOpenAI

model = ChatOpenAI()

@chain
async def thingy(inputs):
    return await model.ainvoke(inputs["prompt"])


async def main():
    async for event in thingy.astream_events({"prompt": "hello"}, version="v1"):
        print(event)


if __name__ == "__main__":
    asyncio.run(main())
```

before the PR:
```
{'event': 'on_chain_start', 'run_id': '62f8260b-b3d5-4b17-9804-05c90fba1fd1', 'name': 'thingy', 'tags': [], 'metadata': {}, 'data': {'input': {'prompt': 'hello'}}, 'parent_ids': []}
{'event': 'on_chat_model_start', 'name': 'ChatOpenAI', 'run_id': '5afa9f8a-8e57-47cf-96fd-1d55d85ddc33', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'input': {'messages': [[HumanMessage(content='hello')]]}}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '5afa9f8a-8e57-47cf-96fd-1d55d85ddc33', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content='', id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '5afa9f8a-8e57-47cf-96fd-1d55d85ddc33', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content='Hello', id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '5afa9f8a-8e57-47cf-96fd-1d55d85ddc33', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content='!', id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '5afa9f8a-8e57-47cf-96fd-1d55d85ddc33', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content=' How', id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '5afa9f8a-8e57-47cf-96fd-1d55d85ddc33', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content=' can', id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '5afa9f8a-8e57-47cf-96fd-1d55d85ddc33', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content=' I', id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '5afa9f8a-8e57-47cf-96fd-1d55d85ddc33', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content=' assist', id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '5afa9f8a-8e57-47cf-96fd-1d55d85ddc33', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content=' you', id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '5afa9f8a-8e57-47cf-96fd-1d55d85ddc33', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content=' today', id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '5afa9f8a-8e57-47cf-96fd-1d55d85ddc33', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content='?', id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '5afa9f8a-8e57-47cf-96fd-1d55d85ddc33', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content='', response_metadata={'finish_reason': 'stop'}, id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}, 'parent_ids': []}
{'event': 'on_chat_model_end', 'name': 'ChatOpenAI', 'run_id': '5afa9f8a-8e57-47cf-96fd-1d55d85ddc33', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'input': {'messages': [[HumanMessage(content='hello')]]}, 'output': {'generations': [[{'text': 'Hello! How can I assist you today?', 'generation_info': {'finish_reason': 'stop'}, 'type': 'ChatGeneration', 'message': AIMessage(content='Hello! How can I assist you today?', response_metadata={'finish_reason': 'stop'}, id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}]], 'llm_output': None, 'run': None}}, 'parent_ids': []}
{'event': 'on_chain_stream', 'run_id': '62f8260b-b3d5-4b17-9804-05c90fba1fd1', 'tags': [], 'metadata': {}, 'name': 'thingy', 'data': {'chunk': AIMessage(content='Hello! How can I assist you today?', response_metadata={'finish_reason': 'stop'}, id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}, 'parent_ids': []}
{'event': 'on_chain_end', 'name': 'thingy', 'run_id': '62f8260b-b3d5-4b17-9804-05c90fba1fd1', 'tags': [], 'metadata': {}, 'data': {'output': AIMessage(content='Hello! How can I assist you today?', response_metadata={'finish_reason': 'stop'}, id='run-5afa9f8a-8e57-47cf-96fd-1d55d85ddc33')}, 'parent_ids': []}
```

after the PR:
```
{'event': 'on_chain_start', 'run_id': 'eca9cf22-b294-4ac1-8504-acf09724ac32', 'name': 'thingy', 'tags': [], 'metadata': {}, 'data': {'input': {'prompt': 'hello'}}, 'parent_ids': []}
{'event': 'on_chat_model_start', 'name': 'ChatOpenAI', 'run_id': 'f964b3e1-6066-49cf-8191-5a51c2a10dc5', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'input': {'messages': [[HumanMessage(content='hello')]]}}, 'parent_ids': []}
{'event': 'on_chat_model_end', 'name': 'ChatOpenAI', 'run_id': 'f964b3e1-6066-49cf-8191-5a51c2a10dc5', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_type': 'chat', 'ls_model_name': 'gpt-3.5-turbo', 'ls_temperature': 0.7}, 'data': {'input': {'messages': [[HumanMessage(content='hello')]]}, 'output': {'generations': [[{'text': 'Hello! How can I assist you today?', 'generation_info': {'finish_reason': 'stop', 'logprobs': None}, 'type': 'ChatGeneration', 'message': AIMessage(content='Hello! How can I assist you today?', response_metadata={'token_usage': {'completion_tokens': 9, 'prompt_tokens': 8, 'total_tokens': 17}, 'model_name': 'gpt-3.5-turbo', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None}, id='run-f964b3e1-6066-49cf-8191-5a51c2a10dc5-0')}]], 'llm_output': {'token_usage': {'completion_tokens': 9, 'prompt_tokens': 8, 'total_tokens': 17}, 'model_name': 'gpt-3.5-turbo', 'system_fingerprint': None}, 'run': None}}, 'parent_ids': []}
{'event': 'on_chain_stream', 'run_id': 'eca9cf22-b294-4ac1-8504-acf09724ac32', 'tags': [], 'metadata': {}, 'name': 'thingy', 'data': {'chunk': AIMessage(content='Hello! How can I assist you today?', response_metadata={'token_usage': {'completion_tokens': 9, 'prompt_tokens': 8, 'total_tokens': 17}, 'model_name': 'gpt-3.5-turbo', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None}, id='run-f964b3e1-6066-49cf-8191-5a51c2a10dc5-0')}, 'parent_ids': []}
{'event': 'on_chain_end', 'name': 'thingy', 'run_id': 'eca9cf22-b294-4ac1-8504-acf09724ac32', 'tags': [], 'metadata': {}, 'data': {'output': AIMessage(content='Hello! How can I assist you today?', response_metadata={'token_usage': {'completion_tokens': 9, 'prompt_tokens': 8, 'total_tokens': 17}, 'model_name': 'gpt-3.5-turbo', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None}, id='run-f964b3e1-6066-49cf-8191-5a51c2a10dc5-0')}, 'parent_ids': []}
```

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Review by eyurtsev — CHANGES_REQUESTED** [review]
What issue is this behavior causing in your application? I believe the way that things work currently is how most folks would want the astream_events API to work with token by token output from the model

**Comment by eyurtsev** [comment]
Newest core allows you to disable streaming explicitly on the BaseChatModel:

https://github.com/langchain-ai/langchain/blob/089f5e6cad4092185798a045c39c017ae790a8f2/libs/core/langchain_core/language_models/chat_models.py#L224-L224

**Comment by Huarong** [comment]
> What issue is this behavior causing in your application? I believe the way that things work currently is how most folks would want the astream_events API to work with token by token output from the model

I'm building a agent using `langgraph`. Some of the nodes in the graph are streaming and some are not streaming. The non streaming node are defined by calling `chain.avinoke()` like the one in the above test script.
I run the graph with `graph. astream_events()` and eventually all the node are streaming out tokens like the example above.
**The issue is that I do not want the nodes with `chain.ainvoke()` are being streaming.**
I'll try the disable_streaming parameter. Thanks a lot. @eyurtsev

**Comment by eyurtsev** [comment]
Going to close this PR! Will follow up in the issue.

**Pull request closed without merging**
