### PR TITLE
core[minor], langchain[patch]: `tools` dependencies refactoring

### PR DESCRIPTION
**Pull request by leo-gan**
The `langchain.tools` [namespace](https://api.python.langchain.com/en/latest/langchain_api_reference.html#module-langchain.tools) can be completely eliminated by moving one class and 3 functions into `core`. It makes sense since the class and functions are very core.

### CODE REVIEW

**Comment by leo-gan** [comment]
@eyurtsev Please review it.

**Comment by leo-gan** [comment]
@eyurtsev Could you, please, review it? Thanks

**Comment by leo-gan** [comment]
@eyurtsev Could you, please, review it? Thanks

**Comment by eyurtsev** [comment]
Roughly ~1 week. Reviewing changes for langchain vs. langchain-core, so we can break the dependency on langchain-community

**Review by eyurtsev — APPROVED** [review]

**Comment by leo-gan** [comment]
@eyurtsev Thanks!

**Pull request merged**
