### PR TITLE
langchain: add unify support

### PR DESCRIPTION
**Pull request by djl11**
**Description:** Added support for unify, an LLM dynamic router with single-sign-on for all providers + models
**Dependencies:** unifyai
**Twitter handle:** letsunifyai

### CODE REVIEW

**Comment by djl11** [comment]
Hey @efriis, happy to get this added? Any more clarifications I can provide?

**Review by efriis — COMMENTED** [review]
Hey team! Still failing CI if you could fix those failing tests.

Could you also add the standard chat model tests? Both [unit](https://github.com/langchain-ai/langchain/blob/master/libs/partners/ai21/tests/unit_tests/test_standard.py) and [integration](https://github.com/langchain-ai/langchain/blob/master/libs/partners/ai21/tests/integration_tests/test_standard.py)

for future reference, if you open PRs from personal forks instead of org ones, it makes collaboration easier due to some shortcomings of github: https://python.langchain.com/docs/contributing/faq/#how-do-i-allow-maintainers-to-edit-my-pr

**Comment by hello-fri-end** [comment]
> Hey team! Still failing CI if you could fix those failing tests.
> 
> Could you also add the standard chat model tests? Both [unit](https://github.com/langchain-ai/langchain/blob/master/libs/partners/ai21/tests/unit_tests/test_standard.py) and [integration](https://github.com/langchain-ai/langchain/blob/master/libs/partners/ai21/tests/integration_tests/test_standard.py)
> 
> for future reference, if you open PRs from personal forks instead of org ones, it makes collaboration easier due to some shortcomings of github: https://python.langchain.com/docs/contributing/faq/#how-do-i-allow-maintainers-to-edit-my-pr

Hey @efriis, apologies for the super delayed response here. Everyone on the team has been extremely occupied with the launch due to which this comment slipped from our radar. 

I have added the standard unit & integration tests. However, it seems the workflows need your approval to run. Happy to fix these whenever you can review again. Thanks!

**Comment by hello-fri-end** [comment]
Hey @efriis, I have fixed all the failing tests on the CI and everything seems to be passing now. Can you please take a look again? Thanks!

**Comment by efriis** [comment]
Hey team! Let's convert this to a community integration.

The main file to migrate is the `chat_models.py` file into `langchain_community/chat_models/unify.py` and convert the sdk imports to optional imports. And the docs will need to be updated to reflect the changed import.

I'll close this PR for now, and feel free to ping me the new PR when it's ready!

As mentioned before, it would be great if you could open it from a [personal branch instead of a github organization repo.](https://python.langchain.com/docs/contributing/faq/#how-do-i-allow-maintainers-to-edit-my-pr)

**Pull request closed without merging**
