### PR TITLE
Support for Request Body containing Reference : OpenAPI functions 

### PR DESCRIPTION
**Pull request by anujmehta**
Thank you for contributing to LangChain!

- [x] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [x] **PR message**: ***Delete this entire checklist*** and replace with
    - **Description:** In OpenAPI spec for a POST method if the request body contains a Reference to another object then the schema of the Reference object is not sent to LLM and it leads to LLM creating incorrect payload. Additionally for a complex payload the schema was not sent to LLM. The PR tries resolves such issues.
    -In below screenshot we have a complex payload and this PR tries to handle schema of **"address"** and **"hobbies"** attributes as shown below

Screenshot 2024-03-31 at 7 38 21 PM

 - **Issue:** 19750
 - **Dependencies:** None
 - **Twitter handle:** https://twitter.com/anujmehta

.

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, hwchase17.

### CODE REVIEW

**Comment by anujmehta** [comment]
@baskaryan @efriis Can you please review this PR?

**Review by baskaryan — COMMENTED** [review]
could we add a unit test for this change?

**Comment by anujmehta** [comment]
@baskaryan I had updated the PR with unit tests cases. Also I have tried to add more description here in PR, will add details in linked issue also. Request you to kindly review the PR.

**Comment by anujmehta** [comment]
@baskaryan @efriis Please review this PR

**Comment by anujmehta** [comment]
@baskaryan @dosobot I need small help with this PR. Looks like build was failing due to lint and test failure. I had pushed changes for lint but I am unable to identify solution for test failure which is failing due to module missing. Please let me know whom can I reach out for help?

Looks like my build is failing due to module not found "openapi-pydantic" in following test class https://github.com/anujmehta/langchain/blob/request-body-reference/libs/community/tests/unit_tests/utilities/test_openapi.py.  I am unable to find solution for it as the dependency is already present at https://github.com/anujmehta/langchain/blob/request-body-reference/libs/community/pyproject.toml#L22 and is added to extended_testing https://github.com/anujmehta/langchain/blob/request-body-reference/libs/community/pyproject.toml#L244.

**Comment by anujmehta** [comment]
@baskaryan @efriis @hwchase17 Gentle reminder. Can you please help me with above query?

**Comment by anujmehta** [comment]
> @baskaryan @dosubot I need small help with this PR. Looks like build was failing due to lint and test failure. I had pushed changes for lint but I am unable to identify solution for test failure which is failing due to module missing. Please let me know whom can I reach out for help?
> 
> Looks like my build is failing due to module not found "openapi-pydantic" in following test class https://github.com/anujmehta/langchain/blob/request-body-reference/libs/community/tests/unit_tests/utilities/test_openapi.py. I am unable to find solution for it as the dependency is already present at https://github.com/anujmehta/langchain/blob/request-body-reference/libs/community/pyproject.toml#L22 and is added to extended_testing https://github.com/anujmehta/langchain/blob/request-body-reference/libs/community/pyproject.toml#L244.

@olgavrou @agola11 @3coins @sjwhitmore I see your valuable contribution to Langchain. Can you please help me in resolving this minor issue so that I can merge the PR?

**Review by baskaryan — APPROVED** [review]

**Comment by hwchase17** [comment]
i believe is resolved with https://github.com/langchain-ai/langchain/pull/19002

**Pull request closed without merging**
