### PR TITLE
experimental: Mixin to allow tool calling features for non tool calling chat models

### PR DESCRIPTION
**Pull request by lalanikarim**
ToolCallingLLM mixin will allow tool calling features on non tool calling chat models until tool calling is supported natively.
Notebook added to demonstrate use case with LiteLLM.
Integration tests added.
Original code extracted from OllamaFunctions. OllamaFunctions rewritten to use ToolCallingLLM

### CODE REVIEW

**Comment by lalanikarim** [comment]
@baskaryan @ccurme @eyurtsev I could use some assistance with this PR.
It is failing the integrations docs lint check. I attempted to add docs strings to meet the chat model template.
However something still seems to be an issue.
Please advise on how I might resolve this issue.

**Comment by lalanikarim** [comment]
@baskaryan @ccurme @eyurtsev 
Can please get some feedback on this PR? 
Thanks

**Comment by lalanikarim** [comment]
Changes from #22859 incorporated into ToolCallingLLM

**Comment by lalanikarim** [comment]
@baskaryan @ccurme @bracesproul Can I please get feedback on this PR? Thanks.

**Comment by lalanikarim** [comment]
@baskaryan @ccurme @efriis @eyurtsev @hwchase17 
Can I please get some feedback on this? 
Thanks

**Comment by lalanikarim** [comment]
@baskaryan @efriis @ccurme @eyurtsev  @hwchase17 
Can I please get feedback on this PR? TIA

**Comment by lalanikarim** [comment]
@baskaryan @efriis @ccurme @eyurtsev @hwchase17
Can I please get feedback on this PR? TIA

**Comment by AtmehEsraa** [comment]
@lalanikarim 

https://drive.google.com/file/d/1cSKSz1Bp_4wLpsOeg0YBDlHM2Ixd__9B/view?usp=sharing

could you please see this notebook and help me to make it call the tool just once

**Comment by lalanikarim** [comment]
@baskaryan @ccurme @hwchase17 @efriis @eyurtsev 
I could really use some direction and feedback on this PR.
TIA

**Comment by lalanikarim** [comment]
@baskaryan @ccurme @hwchase17 @efriis @eyurtsev @jacoblee93 
I could really use some direction and feedback on this PR.
TIA

**Comment by colinmcnamara** [comment]
Checking in again, is there any feedback for this PR?

**Comment by lalanikarim** [comment]
@baskaryan @ccurme @hwchase17 @efriis @eyurtsev @jacoblee93
Since Ollama now has an official partner package and support for tool calling, I've updated my PR to exclude any Ollama related changes. 
I'd like to get some feedback on this and potentially a yay or nay on whether to continue with the PR.
TIA

**Comment by hwchase17** [comment]
i dont think we want to support this right now as part of langchain. the main reason is this is heavily prompt specific. depending on the model, certain variants of the prompts may be more or less necessary. we're trying to make langchain LESS prompt specific. this is a great effort, but probably not part of langchain (could be a package/wrapper on top)

**Pull request closed without merging**
