### PR TITLE
docs: integrations W&B update

### PR DESCRIPTION
**Pull request by leo-gan**
Issue: Here is an ambiguity about W&B integrations. There are two existing provider pages.
Fix: Added the "root" W&B provider page. Added there the references to the documentation in the W&B site. Cleaned up formats in existing pages. Added one more integration reference.

### CODE REVIEW

**Comment by eyurtsev** [comment]
@leo-gan PR seems like it has unintended changes?

**Comment by leo-gan** [comment]
@eyurtsev Yeah, sorry for the mess. Do you want me to recreate PR?

**Comment by leo-gan** [comment]
@eyurtsev I've mentioned that WandbCallbackHandler is deprecated in a couple of places.

**Comment by eyurtsev** [comment]
@parambharat -- could you please TAL at what should be done with W&B integration?

**Comment by eyurtsev** [comment]
@efriis re-assigning to you. I don't know what the status of wandb tracing is and we've got no response from @parambharat who was working on the wandb tracing in the w&b repo. 

I think that the community tracers are deprecated, and we should mark them as deprecated and probably remove some of them from docs, but don't know for sure

**Comment by eyurtsev** [comment]
@efriis created an issue on the W&B repository

**Review by efriis — APPROVED** [review]

**Comment by efriis** [comment]
for now this works

**Pull request merged**
