### PR TITLE
Adding retriever for AzureCosmosDB Vector Search

### PR DESCRIPTION
**Pull request by aayush3011**
This PR adds the retriever functionality for the Azure Cosmos DB Mongo vCore Vector Search. 

https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/ 
https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/vector-search 

Summary:
  - Description: Adding a retriever for the AzureCosmosDB Mongo vCore Vector Search
  - Tag maintainer: @hwchase17

### CODE REVIEW

**Comment by aayush3011** [comment]
@hwchase17 can you please review and approve this PR?

**Comment by aayush3011** [comment]
@baskaryan can you please help merge this PR?

**Comment by jcodella** [comment]
Ping on this thread, @baskaryan or @hwchase17 , can you please help review/merge this PR?

**Comment by aayush3011** [comment]
Added a new PR with more enchancements, including this one as well.

https://github.com/langchain-ai/langchain/pull/16856

**Pull request closed without merging**
