### PR TITLE
Async support for FAISS

### PR DESCRIPTION
**Pull request by thaiminhpv**
Following this tutoral about using OpenAI Embeddings with FAISS

https://python.langchain.com/docs/integrations/vectorstores/faiss

```python
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import FAISS
from langchain.document_loaders import TextLoader
from langchain.document_loaders import TextLoader

loader = TextLoader("../../../extras/modules/state_of_the_union.txt")
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()
```

This works fine

```python
db = FAISS.from_documents(docs, embeddings)
query = "What did the president say about Ketanji Brown Jackson"
docs = db.similarity_search(query)
```

But the async version is not

```python
db = await FAISS.afrom_documents(docs, embeddings)  # NotImplementedError
query = "What did the president say about Ketanji Brown Jackson"

docs = await db.asimilarity_search(query) # this will use await asyncio.get_event_loop().run_in_executor under the hood and will not call OpenAIEmbeddings.aembed_query but call OpenAIEmbeddings.embed_query
```

So this PR add async/await supports for FAISS

### CODE REVIEW

**Comment by eyurtsev** [comment]
@thaiminhpv thank you for the implementation. Would you be able to provide unit tests to cover the added functionality?

**Comment by thaiminhpv** [comment]
@eyurtsev Sure! I will have a look at it.

**Comment by thaiminhpv** [comment]
@eyurtsev I've written the tests and passed, please check it.
Thank you!

**Comment by eyurtsev** [comment]
@thaiminhpv thank you -- I'll try to review and merge over the next 2 days

**Comment by thaiminhpv** [comment]
@eyurtsev Please let me know if I can help anything. Thank you.

**Comment by thaiminhpv** [comment]
@eyurtsev @baskaryan  I've updated the code to up-to-date with the change in #10823 , please review this PR.
Thank you!

**Comment by eyurtsev** [comment]
Looks good -- moved docs to the correct place

**Review by eyurtsev — APPROVED** [review]
Can merge after tests pass

**Pull request merged**
