### PR TITLE
community: add integration with Nebius AI Studio for Chat & Embeddings endpoints

### PR DESCRIPTION
**Pull request by Aktsvigun**
### Description

Dear team, adding integration with Nebius AI Studio for Chat & Embeddings endpoints.

### CODE REVIEW

**Comment by Aktsvigun** [comment]
@baskaryan kindly review :)

**Comment by Aktsvigun** [comment]
Hey, @efriis @eyurtsev could you please review?

**Comment by Aktsvigun** [comment]
Apologies for many tags, @baskaryan, @efriis, @eyurtsev, @ccurme, @vbarda, @hwchase17 could you please approve the review?

**Comment by efriis** [comment]
Hey there! This PR is currently in "Needs support" per our review process: https://python.langchain.com/docs/contributing/reference/review_process/

It currently doesn't have enough upvotes to prioritize a review.

**Comment by Aktsvigun** [comment]
Hey @efriis , thank you for your reply! Can this issue have a review prioritized now? :)

**Comment by Aktsvigun** [comment]
Hey @efriis, any updates here?

**Comment by efriis** [comment]
hey there! sorry for the delay. This component architecture for the chat model doesn't work in community, and we'd recommend publishing a separate integration package and just contribute the docs! 

here's the guide: https://python.langchain.com/docs/contributing/how_to/integrations/

**Pull request closed without merging**
