### PR TITLE
feat: jina search tools integrating (jina reader)

### PR DESCRIPTION
**Pull request by Yash-1511**
- **PR title**: "community: add Jina Search tool"
-  **Description:** Added the Jina Search tool for querying the Jina search API. This includes the implementation of the JinaSearchAPIWrapper and the JinaSearch tool, along with a Jupyter notebook example demonstrating its usage.
- **Issue:** N/A
- **Dependencies:** N/A
- **Twitter handle:** [Twitter handle](https://x.com/yashp3020?t=7wM0gQ7XjGciFoh9xaBtqA&s=09)

- [x] **Add tests and docs**: If you're adding a new integration, please include
  1. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [ ] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

### CODE REVIEW

**Comment by Yash-1511** [comment]
Hey, @baskaryan 

can you review this PR.

**Review by ccurme — APPROVED** [review]
LGTM pending linting / formatting issues.

Please see our contribution guidelines [here](https://python.langchain.com/v0.2/docs/contributing/code/setup/#formatting-and-linting) for help resolving.

**Comment by Yash-1511** [comment]
> LGTM pending linting / formatting issues.
> 
> Please see our contribution guidelines [here](https://python.langchain.com/v0.2/docs/contributing/code/setup/#formatting-and-linting) for help resolving.

Done!

**Comment by Yash-1511** [comment]
> LGTM pending linting / formatting issues.
> 
> Please see our contribution guidelines [here](https://python.langchain.com/v0.2/docs/contributing/code/setup/#formatting-and-linting) for help resolving.

@ccurme please can you review this again! there are some linting errors but not from my newly added code.

**Comment by ccurme** [comment]
I see CI failing due to formatting in code added here. Could you please follow the instructions [here](https://python.langchain.com/v0.2/docs/contributing/code/setup/#formatting-and-linting) for formatting and linting?

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
