### PR TITLE
AzureChatOpenAI for Azure Open AI's ChatGPT API

### PR DESCRIPTION
**Pull request by ekzhu**
Add support for Azure OpenAI's ChatGPT API, which uses ChatML markups to format messages instead of objects. 

Related issues: #1591, #1659

### CODE REVIEW

**Comment by sheikalthaf** [comment]
Any updates on this? Need it badly @hwchase17

**Review by hwchase17 — APPROVED** [review]

**Comment by geg00** [comment]
I'm using [https://langchain.readthedocs.io/en/latest/modules/chat/examples/few_shot_examples.html](url) to test the chat option.
This is the error message that I'm getting
`---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
Cell In[5], line 4
      2 chain = LLMChain(llm=chat, prompt=chat_prompt)
      3 # get a chat completion from the formatted messages
----> 4 chain.run("I love programming.")

File c:\Users\AppData\Local\mambaforge\lib\site-packages\langchain\chains\base.py:213, in Chain.run(self, *args, **kwargs)
    211     if len(args) != 1:
    212         raise ValueError("`run` supports only one positional argument.")
--> 213     return self(args[0])[self.output_keys[0]]
    215 if kwargs and not args:
    216     return self(kwargs)[self.output_keys[0]]

File c:\Users\AppData\Local\mambaforge\lib\site-packages\langchain\chains\base.py:116, in Chain.__call__(self, inputs, return_only_outputs)
    114 except (KeyboardInterrupt, Exception) as e:
    115     self.callback_manager.on_chain_error(e, verbose=self.verbose)
--> 116     raise e
    117 self.callback_manager.on_chain_end(outputs, verbose=self.verbose)
    118 return self.prep_outputs(inputs, outputs, return_only_outputs)

File c:\Users\AppData\Local\mambaforge\lib\site-packages\langchain\chains\base.py:113, in Chain.__call__(self, inputs, return_only_outputs)
    107 self.callback_manager.on_chain_start(
    108     {"name": self.__class__.__name__},
    109     inputs,
...
    683         rbody, rcode, resp.data, rheaders, stream_error=stream_error
    684     )
    685 return resp

InvalidRequestError: Resource not found
`

With Azure you have to create a deployment deployment_id to use it.
I created under my account with Azure the same names as the models.
For exmaple:
deployment: text-davinci-003
model text-davinci-0003
deployment: text-embedding-ada-002
model: text-embedding-ada-002
however, gpt-3.5-turbo is not a valid option because of the '.' in 3.5

I hope this helps.

**Comment by ekzhu** [comment]
Azure just added a ChatCompletion API so I will submit another PR to fix this

**Comment by ekzhu** [comment]
Added PR https://github.com/hwchase17/langchain/pull/1902 to improve AzureChatOpenAI.

**Pull request merged**
