### PR TITLE
Added task orchestration chains

### PR DESCRIPTION
**Pull request by rbehal**
- This PR essentially implements the chains outlined in the [LangChain Wiki](https://python.langchain.com/en/latest/use_cases/agents/baby_agi.html), some slight modifications and re-factoring was done to get it to work with the standard `VectorStore` class and to have all the relevant functions in the same class as BabyAGI so that the chain could run effectively independently
- I think it is worth having these chains as a standalone on the LangChain repo, as orchestration is becoming huge, and there are a lot of other chains being built off of these as a base
- `make lint` and `make format` have been run locally and are succeeding

### CODE REVIEW

**Comment by vowelparrot** [comment]
Thanks for the PR, @rbehal ! We agree that task orchestration is becoming increasingly important. We are going to take a number of factors into consideration to make a better default agent, so it may take a bit to consider whether this is the ideal place to put this

**Comment by rbehal** [comment]
Sure sounds good! Let me know if I can help in any way or any modifications to be made that I can do

**Comment by hwchase17** [comment]
@rbehal we'll likely put this in a `langchain.experimental` folder - will get into wednesdays release

**Comment by fredzannarbor** [comment]
I took a look at the code in langchain.experimental, but I don't understand how to run langchain/babyagi from the command line, the way I would babyagi.  Can you add an illustration?

**Comment by rbehal** [comment]
Hi @fredzannarbor the class itself is not intended to be directly used from cli as BabyAGI is, it is still meant to be instantiated and run from within a Python script. I will add an example to the `README.md`, but here is a quick example of a Python file that when run will act like the babyagi you expect:

```
from typing import Optional
import os
import faiss
from langchain import OpenAI
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS
from langchain.docstore import InMemoryDocstore

from baby_agi import BabyAGI

def get_vector_store():
    # Define your embedding model
    embeddings_model = OpenAIEmbeddings()
    # Initialize the vectorstore as empty
    embedding_size = 1536
    index = faiss.IndexFlatL2(embedding_size)
    return FAISS(embeddings_model.embed_query, index, InMemoryDocstore({}), {})    

def main():
    OBJECTIVE = '''
    Develop a marketing plan for a software application
    '''

    llm = OpenAI(temperature=0)
    vectorstore = get_vector_store()
    # Logging of LLMChains
    verbose=False
    # If None, will keep on going forever
    max_iterations: Optional[int] = 8
    baby_agi = BabyAGI.from_llm(
        llm=llm,
        vectorstore=vectorstore,
        verbose=verbose,
        max_iterations=max_iterations
    )

    baby_agi({"objective": OBJECTIVE})

if __name__ == "__main__":
    main()
```

**Pull request merged**
