### PR TITLE
Made some changes to improve format

### PR DESCRIPTION
**Pull request by TheSeer507**
# Your PR Title (What it does)

Fixes # (issue)

## Who can review?

Community members can review the PR once tests pass. Tag maintainers/contributors who might be interested:

### CODE REVIEW

**Comment by dev2049** [comment]
cc @leo-gan

**Comment by leo-gan** [comment]
I'm not sure about these changes:
* The page title (marked with a single #) goes into the navbar. Why change it to ##? Because we don't like the font size? It should be controllable by CSS or something else, not by changes in semantic marking.
- changing "`Action Plan Generation` is.." to "Action Plan Generation is..." also breaks most of our notebook formats. I use backticks to mark the names of companies, packages, and systems everywhere.
- changing "[Paper]" to "[Memetic Proxy Paper]" for consistency? I'd rather change all paper references to "[Paper]" because usually "[Memetic Proxy Paper]" is just not correct. Most of the papers just mention the discussed term, they are not completely about discussed term.

I'm not commenting about syntactic changes, English is not my native language :)

**Comment by TheSeer507** [comment]
Hello,
Gotcha, yeah removed the `backticks` as I thought were kinda redundant wasnt aware about notebook format. Will keep that in mind for future changes. Will revise my pullrequest and make the changes accordingly.

**Comment by baskaryan** [comment]
stale, page has been removed

**Pull request closed without merging**
