### PR TITLE
langchain: Add a default description to the retriever tool

### PR DESCRIPTION
**Pull request by cbornet**

### CODE REVIEW

**Comment by eyurtsev** [comment]
What's the rational? I think this one is maybe OK without a default value so yours have to add a description? If multiple retrievers are used they will likely need to have different descriptions?

**Comment by cbornet** [comment]
I believe most of the time you'll have only one retriever and I felt that this description was a quite good default for that retriever, isn't it ?

**Comment by cbornet** [comment]
I saw that while assembling this tool with a self-query-retriever where the definition of how the docs were retrieved didn't seem important. The important thing is that this tool retrieves docs base on a query.

**Review by eyurtsev — APPROVED** [review]

**Comment by baskaryan** [comment]
my sense is in most production use cases it's worth setting a retriever-specific description that explains what types of documents are being retrieved. and i generally prefer not adding defaults that are usually overridden

**Pull request closed without merging**
