### PR TITLE
community: add InfinityRerank

### PR DESCRIPTION
**Pull request by baptiste-pasquier**
**Description:** 

- Add a Reranker for Infinity server.

**Dependencies:** 

This wrapper uses [infinity_client](https://github.com/michaelfeil/infinity/tree/main/libs/client_infinity/infinity_client) to connect to an Infinity server.

**Tests and docs**

- integration test: test_infinity_rerank.py
- example notebook: infinity_rerank.ipynb [here](https://github.com/baptiste-pasquier/langchain/blob/feat/infinity-rerank/docs/docs/integrations/document_transformers/infinity_rerank.ipynb)

### CODE REVIEW

**Comment by michaelfeil** [comment]
Thank you so much for the PR

**Review by Undertone0809 — APPROVED** [review]

**Comment by michaelfeil** [comment]
@cccs-eric @efriis I think this is an imporant PR for infinity integration + not sure why this status was assigned

**Review by michaelfeil — APPROVED** [review]

**Comment by efriis** [comment]
pretty sure this status is in line with the review process let me know if it's not https://python.langchain.com/docs/contributing/reference/review_process/

**Review by efriis — APPROVED** [review]

**Comment by efriis** [comment]
thanks and appreciate the patience!

**Pull request merged**
