### PR TITLE
Add ability to load (deserialize) objects from other namespaces

### PR DESCRIPTION
**Pull request by alecf**
I have some Prompt subclasses in my project that I'd like to be able to deserialize in callbacks. Right now `loads()`/`load()` will bail when it encounters my object, but I know I can trust the objects because they're in my own projects.

### CODE REVIEW

**Comment by alecf** [comment]
tagging @nfcampos because he's (hopefully) reviewing #7626 and @baskaryan for general utility stuff

**Comment by alecf** [comment]
I've moved this to be an isolated change since it seems like #7626 might be slightly controversial, but there isn't a way for me to work around this specific issue.

**Comment by alecf** [comment]
@baskaryan friendly ping!

**Review by nfcampos — APPROVED** [review]
This is great, thanks!

**Comment by alecf** [comment]
is there anything I need to do to get this merged? (it had merge conflicts at the time of approval, but the resolution was trivial/automatic as it was just from file moves)

**Comment by alecf** [comment]
@nfcampos can you merge this?

**Comment by nfcampos** [comment]
Done, sorry I thought I had merged this one already

**Pull request merged**
