### PR TITLE
feat(llms): add streaming support to textgen

### PR DESCRIPTION
**Pull request by uetuluk**
- Description: Added streaming support to the textgen component in the llms module.
  - Dependencies: websocket-client = "^1.6.1"

### CODE REVIEW

**Comment by uetuluk** [comment]
I am confused about the missing package, is websocket-client/websocket not a required dependency? 

https://github.com/langchain-ai/langchain/blob/4c2de2a7f28442896e06a6fc7c807cf611b0c780/poetry.lock#L3699-L3708

**Comment by uetuluk** [comment]
Added websocket-client = "^1.6.1" as a dependency

**Comment by uetuluk** [comment]
Fixed the linting error, but need helping with adding the dependency as possibly an optional dependency.

Tagging @eyurtsev for help with dependencies.

**Comment by uetuluk** [comment]
Fixed dependency error with optional import when streaming is used. 
 
All workflows passing on fork 

Screenshot 2023-08-18 at 12 00 46

**Comment by baskaryan** [comment]
looks awesome, thanks @uetuluk!

**Pull request merged**
