### PR TITLE
feat: Docusaurus Loader

### PR DESCRIPTION
**Pull request by leedotpang**
Added a Docusaurus Loader

Issue: #6353

I had to implement this for working with the Ionic documentation, and wanted to open this up as a draft to get some guidance on building this out further. I wasn't sure if having it be a light extension of the SitemapLoader was in the spirit of a proper feature for the library -- but I'm grateful for the opportunities Langchain has given me and I'd love to build this out properly for the sake of the community. 

Any feedback welcome!

### CODE REVIEW

**Comment by baskaryan** [comment]
@leedotpang feel free to ping when it's ready for review!

**Comment by leo-gan** [comment]
@leedotpang Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by leedotpang** [comment]
@leo-gan Absolutely! I pushed this to the backburner for a bit, but I was planning on adding docs and tests to fill it out more. Thanks for the follow-up

**Comment by slavakurilyak** [comment]
@leedotpang Yes, please. Integrating Docusaurus paves the way for a new document loader which expands coding-related use cases as LLMs gain direct access to new docs!

**Comment by leedotpang** [comment]
Thanks for your patience! Finally was able to make time for this. I'll keep my eyes peeled on updates here

**Comment by leedotpang** [comment]
That lint script was hanging locally -- finally got it working! Apologies for the oversight. I didn't realize that was failing!

**Comment by leedotpang** [comment]
@baskaryan I cleaned the implementation and docs up a bit, and I'm happy with it!

**Comment by leedotpang** [comment]
@baskaryan just following up here, let me know if there's more to be desired!

**Review by efriis — APPROVED** [review]
Thanks @leedotpang

**Pull request merged**
