### PR TITLE
fix: provider the latest duckduckgo_search API

### PR DESCRIPTION
**Pull request by Undertone0809**
# Provider the latest duckduckgo_search API

The Git commit contents involve two files related to some DuckDuckGo query operations, and an upgrade of the DuckDuckGo module to version 3.2.0. A suitable commit message could be "Upgrade DuckDuckGo module to version 3.2.0, including query operations". Specifically, in the duckduckgo_search.py file, a DDGS() class instance is newly added to replace the previous ddg() function, and the time parameter name in the get_snippets() and results() methods is changed from "time" to "timelimit" to accommodate recent changes. In the pyproject.toml file, the duckduckgo-search module is upgraded to version 3.2.0.

## Who can review?

@vowelparrot

### CODE REVIEW

**Comment by Undertone0809** [comment]
[duckduckgo_search readme attention](https://github.com/deedy5/duckduckgo_search): Versions before v2.9.4 no longer work as of May 12, 2023

**Comment by Undertone0809** [comment]
@vowelparrot I wonder why `duckduckgo_search` has release `v3.2.0` but checks failed and said `Because langchain depends on duckduckgo-search (^3.2.0) which doesn't match any versions, version solving failed.`

**Comment by vowelparrot** [comment]
The `poetry.lock` file needs to be updated as well! (running `poetry lock` will update)

**Comment by rrcgat** [comment]
We can harness the self.max_results to limit the search results, for example:

```python
    for i, res in enumerate(results, 1):
        snippets.append(res['body'])
        if i == self.max_results:
            break
    return snippets
```

Maybe we can use `Generator`:

```python
...
    for i, res in enumerate(results, 1):
        yield res['body']
        if i == self.max_results:
            return
...
```

In the latest version of duckduckgo_search, it is recommand to use context manager with `DDGS`:

```python
with DDGS() as ddgs:
    ddgs.text(...)
````

**Comment by Undertone0809** [comment]
Oh, I don't know why make so many commit. Perhaps I should create a new PR #6409

**Pull request closed without merging**
