### PR TITLE
community: allow SQLDatabase to run queries with parameters

### PR DESCRIPTION
**Pull request by danb27**
**Description:** Allow binding parameters in queries run by SQLDatabase
**Issue:** https://github.com/langchain-ai/langchain/issues/15449
**Dependencies:** N/A
**Twitter handle:** N/A

Let me know if you need me to write tests, it looks like this class doesn't have any tests.

### CODE REVIEW

**Comment by danb27** [comment]
Hello, @eyurtsev 

Been a few days - just bumping this up. Thanks!

**Comment by cbornet** [comment]
> cc @amotl @cbornet i know you're working on something similar

Indeed I think https://github.com/langchain-ai/langchain/pull/16655 has the same change

**Comment by amotl** [comment]
Hi. Yeah I guess GH-16655 implements this already, and more. I think the patch is ready, so may I ask someone with corresponding powers merge it?

**Comment by amotl** [comment]
Hi Dan. Thanks for your reply. This patch has now been merged already by @eyurtsev. Does it fulfill your needs already?

- GH-17191

**Comment by danb27** [comment]
Yup! Sure does.

**Comment by amotl** [comment]
Excellent, thanks, and enjoy! If you think it is appropriate to close this PR, please do, if @baskaryan or @cbornet don't have any objections.

**Pull request closed without merging**
