### PR TITLE
update cube_semantic.py

### PR DESCRIPTION
**Pull request by kunalvexpa**
changed condition to  "continue" only if type == view or else get the cube,measure and dimension values from dict

  - Description: changed condition to  "continue" only if type == view or else get the cube,measure and dimension values 
                         from dictionary, 
  - Issue: the issue was that the condition type!=view will meet the condition and skip all iterations because of the "continue" thus not extracting cube_name,dimension and measures from the cube iterator,
  - Dependencies: no dependencies,
  - Tag maintainer: @rlancemartin, @eyurtsev,
  - Twitter handle: I am fine without any mention haha. 

If no one reviews your PR within a few days, feel free to @-mention the same people again.

See contribution guidelines for more information on how to write/run tests, lint, etc: https://github.com/hwchase17/langchain/blob/master/.github/CONTRIBUTING.md
 -->

### CODE REVIEW

**Comment by kunalvexpa** [comment]
Can you please let me know if I should include anything else?

**Comment by baskaryan** [comment]
so was original implementation a bug?

not familiar with cube, but based on unit tests it seems like this was intended behavior (to only load when type is "view")

**Comment by leo-gan** [comment]
@kunalvexpa Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!
If this PR is not needed anymore, could you, please, let me know or close this PR?

**Comment by efriis** [comment]
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

**Pull request closed without merging**
