### PR TITLE
Community patch clickhouse make it possible to not specify index

### PR DESCRIPTION
**Pull request by mneedham**
Vector indexes in ClickHouse are experimental at the moment and can sometimes break/change behaviour. So this PR makes it possible to say that you don't want to specify an index type.

Any queries against the embedding column will be brute force/linear scan, but that gives reasonable performance for small-medium dataset sizes.

Previous PRs:

https://github.com/langchain-ai/langchain/pull/19527
https://github.com/langchain-ai/langchain/pull/18381

### CODE REVIEW

**Comment by mneedham** [comment]
@efriis  can you get the build to run on this version of the PR?

**Comment by mneedham** [comment]
@efriis did you get a chance to look at this?

**Comment by mneedham** [comment]
@efriis would you be able to kick off the build so that we can see if these changes work?

**Comment by mneedham** [comment]
@efriis any chance you can take a look at this?

**Review by efriis — APPROVED** [review]
looks great! Thanks for fixing the comment from #19527

**Pull request merged**
