### PR TITLE
Add Minimax llm model to langchain

### PR DESCRIPTION
**Pull request by hetaoBackend**
- Description: Minimax is a great AI startup from China, recently they released their latest model and chat API, and the API is widely-spread in China. As a result, I'd like to add the Minimax llm model to Langchain.
- Tag maintainer: @hwchase17, @baskaryan

### CODE REVIEW

**Comment by baskaryan** [comment]
seems to overlap with #6757, maybe worth coordinating with [Lukalukaxxx](https://github.com/Lukalukaxxx) to make sure all functionality gets in?

**Comment by hetaoBackend** [comment]
> thanks @hetaoBackend! seems to overlap with #6757, maybe worth coordinating with @Lukalukaxxx to make sure all functionality gets in?

Cool, I will coordinate with @Lukalukaxxx  to discuss it. Thanks for reviewing the PR.

**Comment by baskaryan** [comment]
think we can merge this in first and then #6757, thanks @hetaoBackend!

**Comment by hetaoBackend** [comment]
> think we can merge this in first and then #6757, thanks @hetaoBackend!

Thanks for merging it! @baskaryan. Since we could not contact the author of https://github.com/langchain-ai/langchain/pull/6757, may I create a new PR to cover it with some code changes? It would be genuinely appreciated if u could give some insights.

**Pull request merged**
