### PR TITLE
ZeroShotAgent prompt fixes

### PR DESCRIPTION
**Pull request by gregorio-clara**
- Description: Reformatting prompt for ZeroShotAgent. The current prompt for the ZeroShotAgent presents limitations when getting the response from the agents. The purpose of this PR is to be more specific in its prompt in order to achieve the response in the expected format.
  - Issue: None
  - Dependencies: None
  - Tag maintainer: @hinthornw (for Agents) @hwchase17 @baskaryan (for Prompts)
  - Twitter handle: @goyoreyes

### CODE REVIEW

**Comment by Malrama** [comment]
Any chance of this getting merges? Fixes some custom LLMs outputs for me

**Comment by gregorio-clara** [comment]
Hello! @hinthornw (for Agents) @hwchase17 @baskaryan (for Prompts)

Have you had the opportunity to check this Ticket?

Any comments are appreciated!

Thank you :)

**Comment by leo-gan** [comment]
@gregorio-clara Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by efriis** [comment]
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

**Pull request closed without merging**
