### PR TITLE
community: add default value to bing_search_url

### PR DESCRIPTION
**Pull request by mainred**
bing_search_url is an endpoint to requests bing search resource and is normally invariant to users, we can give it the default value to simply the uesages of this utility/tool

### CODE REVIEW

**Comment by ccurme** [comment]
Thanks @mainred, can you clarify - if that's the default for Bing, why override it instead of letting it be determined by Bing? Is it to enable users to set it with environment variables?

**Comment by mainred** [comment]
> Thanks @mainred, can you clarify - if that's the default for Bing, why override it instead of letting it be determined by Bing? Is it to enable users to set it with environment variables?

@ccurme , Currently there are two bing search services provided on Azure, [bing web custom search](https://learn.microsoft.com/en-us/bing/search-apis/bing-custom-search/overview) and [bing web search](https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/overview) if we focus on the web search part. And they all have constant endpoint, https://api.bing.microsoft.com/v7.0/custom/search for [bing custom web search](https://learn.microsoft.com/en-us/bing/search-apis/bing-custom-search/reference/endpoints#endpoints) and https://api.bing.microsoft.com/v7.0/search for [bing web search](https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/reference/endpoints#endpoints)

Before, bing search and custom search are integrated into azure cognitive service, and [the cognitive service endpoint varying from one cognitive service to another](https://github.com/Azure-Samples/cognitive-services-REST-api-samples/blob/master/python/Search/BingCustomSearchv7.py#L19), so our bing wrapper asks for an endpoint from env, but as bing search and bing web search are now standalone services, and we can default constant endpoint instead.
The user can still pick bing custom search through the endpoint env.

> Why we choose bing search by default instead of bing custom search?

Bing custom search requires a customConfig, which is not always the common case when people just make simple search results.

**Comment by mainred** [comment]
Not sure if it's valuable to put these into the code comments.

**Review by ccurme — APPROVED** [review]

**Comment by ccurme** [comment]
Thanks for the explanation. Will merge for now but could be helpful to add a comment as you suggest!

**Comment by mainred** [comment]
Created https://github.com/langchain-ai/langchain/pull/23523 to make bing web search as the option and added comment to explain why. 
@ccurme It may be a bit different from what I said earlier, which is to configurable but default value to bing web search considering bing custom search is not a common use case for bing search and requires additional custom search instance, which is so far not well supported. So I think people were just using bing search service.

**Pull request merged**
