### PR TITLE
Updated integration with Clarifai python SDK functions

### PR DESCRIPTION
**Pull request by mogith-pn**
Description :

Updated the functions with new Clarifai python SDK.
Enabled initialisation of Clarifai class with model URL.
Updated docs with new functions examples.

### CODE REVIEW

**Comment by mogith-pn** [comment]
@baskaryan could you please check and review this ? 
thanks !

**Comment by mogith-pn** [comment]
@efriis could you please check and review this ?
thanks !

**Comment by mogith-pn** [comment]
@hwchase17  Can I get a review please ? 
TIA !

**Review by efriis — COMMENTED** [review]
Hey @mogith-pn ! I think this will be a breaking change for people using their current version of the clarifai sdk (based on the changes of imports). Want to update it to use the old logic as a backup? I'm assuming the old SDK version is still out there in some form.

**Comment by mogith-pn** [comment]
Hey @efriis ,
Thanks for raising concern. We are moving away from using old SDK (which extensively used gRPC) with new developer friendly SDK and also with our new clarifai version bumps <9.10.2 these old functions might not work as well. Hence the migration was indeed planned one. 
So Kindly do the needful.

**Comment by efriis** [comment]
@mogith-pn could you fix the merge conflicts? I think some steps were also taken in #14215

**Comment by mogith-pn** [comment]
Hi @efriis ,
Thanks for the [fix](https://github.com/langchain-ai/langchain/pull/14215) , although this current PR will address the issue , since we have completely revamped the functions with our new clarifai-python SDK.

**Review by hwchase17 — APPROVED** [review]

**Pull request merged**
