### PR TITLE
core:Add optional max_messages to MessagePlaceholder

### PR DESCRIPTION
**Pull request by DaveDeCaprio**
- **Description:** Add optional max_messages to MessagePlaceholder
- **Issue:** [16096](https://github.com/langchain-ai/langchain/issues/16096)
- **Dependencies:** None
- **Twitter handle:** @davedecaprio

Sometimes it's better to limit the history in the prompt itself rather than the memory.  This is needed if you want different prompts in the chain to have different history lengths.

### CODE REVIEW

**Comment by DaveDeCaprio** [comment]
@baskaryan Do you not like the feature idea, or was it something about the submission?

**Comment by baskaryan** [comment]
not intentional, we can't reopen at the moment but will do so as soon as we can :/ See #16796

**Comment by psaks** [comment]
This is a great idea @DaveDeCaprio. However, I suggest that we make the window length consistent with the ConversationBufferWindowMemory below by renaming the max_messages to k and adding a factor 2, such that the actual number of messages loaded is 2 * k. What do you think? 

```class ConversationBufferWindowMemory(BaseChatMemory):
    """Buffer for storing conversation memory inside a limited size window."""

    human_prefix: str = "Human"
    ai_prefix: str = "AI"
    memory_key: str = "history"  #: :meta private:
    k: int = 5
    """Number of messages to store in buffer."""

    @property
    def buffer(self) -> Union[str, List[BaseMessage]]:
        """String buffer of memory."""
        return self.buffer_as_messages if self.return_messages else self.buffer_as_str

    @property
    def buffer_as_str(self) -> str:
        """Exposes the buffer as a string in case return_messages is True."""
        messages = self.chat_memory.messages[-self.k * 2 :] if self.k > 0 else []
        return get_buffer_string(
            messages,
            human_prefix=self.human_prefix,
            ai_prefix=self.ai_prefix,
        )```

**Comment by DaveDeCaprio** [comment]
@psaks Good idea.  I'll update the PR today.

**Review by hwchase17 — APPROVED** [review]

**Pull request merged**
