### PR TITLE
ArangoDB/AQL support for Graph QA Chain

### PR DESCRIPTION
**Pull request by aMahanna**
**Description**: Serves as an introduction to LangChain's support for [ArangoDB](https://github.com/arangodb/arangodb), similar to https://github.com/hwchase17/langchain/pull/7165 and https://github.com/hwchase17/langchain/pull/4881

**Issue**: No issue has been created for this feature

**Dependencies**: `python-arango` has been added as an optional dependency via the `CONTRIBUTING.md` guidelines 
 
**Twitter handle**: [at]arangodb

- Integration test has been added
- Notebook has been added: graph_arangodb_qa.ipynb

[Open In Collab](https://colab.research.google.com/github/arangodb/interactive_tutorials/blob/master/notebooks/Langchain.ipynb)

```
docker run -p 8529:8529 -e ARANGO_ROOT_PASSWORD= arangodb/arangodb
```

```
pip install git+https://github.com/amahanna/langchain.git
```

```python
from arango import ArangoClient

from langchain.chat_models import ChatOpenAI
from langchain.graphs import ArangoGraph
from langchain.chains import ArangoGraphQAChain

db = ArangoClient(hosts="localhost:8529").db(name="_system", username="root", password="", verify=True)

graph = ArangoGraph(db)

chain = ArangoGraphQAChain.from_llm(ChatOpenAI(temperature=0), graph=graph)

chain.run("Is Ned Stark alive?")
```

### CODE REVIEW

**Comment by baskaryan** [comment]
@aMahanna feel free to ping when it's ready

**Comment by aMahanna** [comment]
> @baskaryan 

will do, just waiting on some internal feedback - thanks

**Comment by aMahanna** [comment]
Ready for review @baskaryan, happy to address any feedback
Thanks

**Comment by baskaryan** [comment]
> Ready for review @baskaryan, happy to address any feedback Thanks
> 
> edit: Also wondering if it would make sense to have ArangoDB listed on the [Integrations page](https://python.langchain.com/docs/ecosystem/integrations)? Happy to add a `.ipynb` & `.mdx` file to `docs/extras/ecosystem/integrations` if so :)

an integrations docs page would be great! ipynb or mdx, whatever's easier. the integrations pages are usually a bit more high level explanatory and less technical, which is why most are mdx (not too much code)

**Comment by aMahanna** [comment]
@baskaryan 

> > Ready for review @baskaryan, happy to address any feedback Thanks
> > edit: Also wondering if it would make sense to have ArangoDB listed on the [Integrations page](https://python.langchain.com/docs/ecosystem/integrations)? Happy to add a `.ipynb` & `.mdx` file to `docs/extras/ecosystem/integrations` if so :)
> 
> an integrations docs page would be great! ipynb or mdx, whatever's easier. the integrations pages are usually a bit more high level explanatory and less technical, which is why most are mdx (not too much code)

great! File has been added, here is the [preview](https://langchain-git-fork-amahanna-master-langchain.vercel.app/docs/ecosystem/integrations/arangodb)

**Comment by baskaryan** [comment]
looks awesome, thanks @aMahanna!

**Comment by aMahanna** [comment]
Hey @baskaryan! checking if there's anything I can do on my end to unblock anything? more than happy to help

**Pull request merged**
