### PR TITLE
huggingface: fix tool argument serialization in  _convert_TGI_message_to_LC_message

### PR DESCRIPTION
**Pull request by sywangyi**
Currently `_convert_TGI_message_to_LC_message` replaces  `'` in the tool arguments, so an argument like "It's" will be converted to `It"s` and could cause a json parser to fail.

### CODE REVIEW

**Comment by sywangyi** [comment]
fix _convert_TGI_message_to_LC_message issue, which will replace all ' in content like It's to It"s and cause json parser fail

**Comment by efriis** [comment]
@Jofthomas

**Comment by yao-matrix** [comment]
ruff failed, pls fix it.

**Comment by yao-matrix** [comment]
@Jofthomas, could you pls review this PR? This makes some TGI-based RAG application failed, but vLLM is OK.

**Comment by yao-matrix** [comment]
@vbarda , gentle reminder, pls let @sywangyi  know anything more need her do, thx.

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
