### PR TITLE
Added GoogleApiClient and GoogleApiYoutubeLoader

### PR DESCRIPTION
**Pull request by thiloweiss**
The current youtube loader is not suitable for use in a production environment because it relies on an uncertified library to interact with the YouTube API. Additionally, it can only handle parsing YouTube links and not channels.

To address these issues, I created a new GoogleApiYoutubeLoader that is capable of building documents based on either a list of video IDs or all videos within a channel. Furthermore, I developed a GoogleApiClient that can be reused for other purposes and offers the necessary features required to run in a production environment.

One note is that I was unable to locate the directory where the tests for other dataloaders are located. If these tests do not exist, I am open to adding tests for my service to ensure its quality and reliability.

Thank you for considering my contributions, and please let me know if there are any further adjustments or concerns that need to be addressed before merging.

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
this looks great! i think adding an example (or a section to an existing example) would be awesome - would you be able to do that?

**Comment by Julianwustl** [comment]
Hey, yes, of course. I added the basic usage in the documentation. But I can add an example to the current version. I will do that in the next two hours.  And one more thing. Adding a generic Google client would be a good option, as you need a registered service for each productive use case.

**Comment by Julianwustl** [comment]
> this looks great! i think adding an example (or a section to an existing example) would be awesome - would you be able to do that?

Feel Free to Check it out. Hope this is okay. If not, i am open for advice

**Review by hwchase17 — APPROVED** [review]
this is great! will merge in tonight! thank you!

**Pull request merged**
