### PR TITLE
partner(zep): implement add_messages and aadd_messages

### PR DESCRIPTION
**Pull request by kaijietti**
This PR implement `add_messages` and `aadd_messages` to avoid unnecessary round-trips.

### CODE REVIEW

**Comment by kaijietti** [comment]
cc @danielchalef

**Comment by danielchalef** [comment]
@paul-paliychuk

**Comment by paul-paliychuk** [comment]
@kaijietti looks good to me!

**Comment by kaijietti** [comment]
@baskaryan PTAL, thanks!

**Comment by baskaryan** [comment]
cc @danielchalef

**Comment by danielchalef** [comment]
@baskaryan thanks for looping me in. @paul-paliychuk speaks for Zep here in approving the PR. :-)

**Pull request merged**
