### PR TITLE
qdrant: search by vector

### PR DESCRIPTION
**Pull request by otwieracz**
Added support to `search_by_vector` to Qdrant Vector store.

### Who can review
VectorStores / Retrievers / Memory
- @dev2049

### CODE REVIEW

**Review by kacperlukawski — CHANGES_REQUESTED** [review]
@otwieracz Looks fine. Thanks for implementing that! Could you please run `make format` and `make lint` (and fix the issues, if any)? Otherwise, it won't pass the CI checks. Once it's done, it is ready to be merged.

**Comment by kacperlukawski** [comment]
@otwieracz It seems the `similarity_search_by_vector` should return `List[Document]`, not `List[Tuple[Document, float]]`. That should be consistent with the supertype.

**Comment by otwieracz** [comment]
@kacperlukawski Thanks for pointing that. Fixed the type hint, reformatted and these are linter results:

```
All done! ✨ 🍰 ✨
1144 files would be left unchanged.
```

**Review by kacperlukawski — APPROVED** [review]
LGTM

**Comment by uayyagari** [comment]
@dev2049 Bumping up this request. Thanks in advance!

**Review by hwchase17 — APPROVED** [review]

**Pull request merged**
