### PR TITLE
SQLDatabase drop the column names in the result.

### PR DESCRIPTION
**Pull request by dudub12**
Fix for the following bug:
https://github.com/langchain-ai/langchain/issues/15360

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
if returning lots of rows, this may take up a lot of tokens, which is perhaps why this was omitted? maybe add a flag to enable this?

**Comment by dudu-upstream** [comment]
> if returning lots of rows, this may take up a lot of tokens, which is perhaps why this was omitted? maybe add a flag to enable this?

But it's not something that involve LLM, it's just a simple SQL response.. sure I can add a flag for that for backward compatibility.

**Comment by hwchase17** [comment]
> > if returning lots of rows, this may take up a lot of tokens, which is perhaps why this was omitted? maybe add a flag to enable this?
> 
> But it's not something that involve LLM, it's just a simple SQL response.. sure I can add a flag for that for backward compatibility.

yeah but practically the outputs are usually piped to an llm

**Comment by dudu-upstream** [comment]
> > > if returning lots of rows, this may take up a lot of tokens, which is perhaps why this was omitted? maybe add a flag to enable this?
> > 
> > 
> > But it's not something that involve LLM, it's just a simple SQL response.. sure I can add a flag for that for backward compatibility.
> 
> yeah but practically the outputs are usually piped to an llm

You are right but in that way the LLM don't know which value refers to which column some it may return incorrect results.
Anyway I will add the flag with a default value to give the ability to control that behavior.

**Review by hwchase17 — APPROVED** [review]

**Pull request merged**
