### PR TITLE
Improvements to llm/deepinfra

### PR DESCRIPTION
**Pull request by ichernev**
- replace `requests` package with `langchain.requests`
- add `_acall` support
- add `_stream` and `_astream`
- freshen up the documentation a bit
- update vendor doc

### CODE REVIEW

**Comment by yessenzhar** [comment]
@baskaryan Could you take a look? A few customers are really asking for async api to DeepInfra.

**Comment by NikolaBorisov** [comment]
@hwchase17 Any chance we can merge this? Should be low risk, and lots of our users are asking for this.

**Comment by baskaryan** [comment]
still seeing some lint issues, happy to take over and land if you'd like

**Comment by ichernev** [comment]
@baskaryan after the master was fixed it's golden ;-)

**Comment by ichernev** [comment]
@hwchase17 @baskaryan can we get this merged?

**Comment by ichernev** [comment]
@hwchase17 @baskaryan can we get a review, please?

**Comment by baskaryan** [comment]
apologies for delay, lgtm! thanks @ichernev

**Pull request merged**
