### PR TITLE
community: add LindormVector to vectorstores; also add Lindorm chat/embedding/rerank to chat_model/embedding/document_compressors

### PR DESCRIPTION
**Pull request by AlwaysBluer**
- [x] **PR title**: "community: add LindormVector to vectorstores; add Lindorm chat/embeeding/rerank"
- [x] **PR message**:
    - **Description:** Lindorm is a multi-model cloud-native database, supporting full-text search, vector-search. It also has AI engine , which could be used to import model or pre-train model inside Lindorm database.
   

- [x] **Add tests and docs**:
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

### CODE REVIEW

**Comment by AlwaysBluer** [comment]
Hi, I'm contributing a new vectordb and AI model provider integration,  but I failed in the integration_tests since it couldn't install the third party package required, what should I do to fix that or avoid that?

**Comment by AlwaysBluer** [comment]
@dosu, what's wrong with my failed checks, do you have any suggestions?

**Comment by AlwaysBluer** [comment]
@baskaryan, I'm sorry to bother you,  but I need you review the pr and give me some suggestions if there is anything wrong with my code

**Comment by efriis** [comment]
Hey! This adds a community integration, which is no longer recommended. Would you be interested in publishing your own integration package, and contributing docs via this guide? https://python.langchain.com/docs/contributing/how_to/integrations/

**Comment by ccurme** [comment]
Closing with recommendation of implementing this in a separate integration package (e.g., authoring `langchain-alibaba-cloud` or similar). There's a walkthrough in the link @efriis provided. Please let us know your feedback!

**Pull request closed without merging**
