### PR TITLE
Allow use of non-default QDrant vector key

### LINKED ISSUE #2594: [Q] How to re-use QDrant collection data that are created separatly with non-default vector name?
I'm trying to use `langchain` to replace current use QDrant directly, in order to benefit from other tools in `langchain`, however I'm stuck.

I already have this code that creates QDrant collections on-demand:
```python
    client.delete_collection(collection_name="articles")
    
    client.recreate_collection(
        collection_name="articles",
        vectors_config={
            "content": rest.VectorParams(
                distance=rest.Distance.COSINE,
                size=1536,
            ),
        },
    )
    
    client.upsert(
        collection_name="articles",
        points=[
            rest.PointStruct(
                id=i,
                vector={
                    "content": articles_embeddings[article],
                },
                payload={
                    "name": article,
                    "content": articles_content[article],
                },
            )
            for i, article in enumerate(ARTICLES)
        ],
    )                                                                             
```

Now, if a I try to re-use `client` as explained in https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/qdrant.html#reusing-the-same-collection I hit the following error:
```
Wrong input: Default vector params are not specified in config
```

I seem to be able to overcome this by modifying the code for `QDrant` class in `langchain`, however, I'm asking if there's any argument that I overlooked to apply using `langchain` with this QDrant client config, or else I would like to contribute a working solution that involves adding new parameter.

### PR DESCRIPTION
**Pull request by mahmoudajawad**
- Context #2594
- This is continuation of #2751 which diverged so much from origin and was better to be re-started.

Fixes #2594

#### Who can review?
@kacperlukawski

### CODE REVIEW

**Comment by mahmoudajawad** [comment]
Hello, @kacperlukawski, I'm back on this and I would like to share my thought process:
- Since last time I looked at this file in code-base, a lot has changed, and so I began with re-implementing the first part I started with.
- Then, I began on the other part which I didn't implement which is allowing defining multiple vectors at time of injecting documents into QDrant (`from_texts` class method).
- Then, I realised defining `vector_key` at class level prevents `langchain` users from using different vectors in collection as all queries will now use `vector_key` from class, so I moved `vector_key` to `similarity_search` method.
- With that, I replaced `vector_key` from class constructor to `vectors_config`, and used it to check for its truthy value in `similarity_search` in order to raise either of two `ValueError` objects; `QDrant` class was initialised with `vectors_config` but value of `vector_key` wasn't provided, or `vector_key` is provided but it isn't one of the vectors defined in `vectors_config`.

With those changes:
- Users of `QDrant` vector store, can now re-use their current collections with the current data, even if it was originally created outside of `langchain`, with any of the vectors collection was defined with.
- It is possible to create a collection `from_documents` with multiple vectors now.
- Original behaviour is preserved.

That said, I'm yet to figure out the effect of this when `QDrant` class is in chain, as I just made this and tested it as a standalone object, not in a chain.

Am I on a path that is accepted by the project standards?

**Comment by mahmoudajawad** [comment]
@kacperlukawski, any chance you had a look at this?

**Comment by kacperlukawski** [comment]
@mahmoudajawad I had an initial look, but I want to cover it with some integration tests. I can hopefully do it over the weekend.

**Comment by kacperlukawski** [comment]
@mahmoudajawad I tried to cover the PR with some integration tests, but unfortunately, I found some issues hard to solve. I'll start a new PR to bring that functionality.

**Comment by mahmoudajawad** [comment]
@kacperlukawski, I really would like to contribute this. I just need directions since I don't want to just put my code in the codebase without pre-approval of an acceptable approach.

If you could confirm to me that my approach in general is acceptable, I would re-create this PR again, add necessary integration tests, and submit it all again.

**Comment by kacperlukawski** [comment]
@mahmoudajawad I just started a new PR that exposes just a vector name: #6871. Would appreciate your review on that.

**Comment by mahmoudajawad** [comment]
Closing this in favour of https://github.com/hwchase17/langchain/pull/6871

**Pull request closed without merging**
