### PR TITLE
Fix Lint: Bittensor llm

### PR DESCRIPTION
**Pull request by kdcokenny**
I fixed the lint so it passes checks for pull #7602 

I didn't remove the bearer key in the headers on line 58 in case it's there on purpose for whatever reason that could be. However, @Kunj-2206 if that's not left in on purpose, either reply here to remove it or git checkout this pull req and make a new one.

### CODE REVIEW

**Comment by Kunj-2206** [comment]
Hey @kdcokenny , that Bearer Key is on purpose. Thanks for updating the code in required format

**Comment by kdcokenny** [comment]
> Hey @kdcokenny , that Bearer Key is on purpose. Thanks for updating the code in required format So now it is ready for merge?

No, you will need to git checkout my pr, then add notebooks showing how it's used as well as some tests.

**Comment by Kunj-2206** [comment]
Hey @kdcokenny , I added test case and notebook and I commited everything in my PR can you please check that

**Comment by kdcokenny** [comment]
> Hey @kdcokenny , I added test case and notebook and I commited everything in my PR can you please check that
> 
> 

It lgtm, but your PR has been closed. Open it so the project maintainers can review & merge it

**Pull request closed without merging**
