### PR TITLE
[Community] PremAI Tool Calling Functionality

### PR DESCRIPTION
**Pull request by Anindyadeep**
This PR is under WIP and adds the following functionalities:

- [X] Supports tool calling across the langchain ecosystem. (However streaming is not supported)
- [X] Update documentation

### CODE REVIEW

**Comment by Anindyadeep** [comment]
> Hi, I am seeing one check is failing, but is unrelated with the changes I am done here.
> 
> ```
> tests/unit_tests/document_loaders/parsers/test_pdf_parsers.py::test_pdfminer_parser FAILED [ 36%]
> ```
> 
> Let me know if we can merge this or anything that I need to do from my side. Thanks
> 
> cc: @baskaryan

This is fixed, after pulling the latets changes from master. Thanks :)

**Comment by Anindyadeep** [comment]
Hi can some one please review this PR, since it has been a while. Thanks a ton :) 

cc: @baskaryan @startime-h

**Comment by Anindyadeep** [comment]
> Hi can some one please review this PR, since it has been a while. Thanks a ton :)
> 
> cc: @baskaryan @startime-h

Hi, it has been quite some days, it would be great if some one could review the PR. Thanks

**Comment by Anindyadeep** [comment]
Hi can some one please review this PR. Thanks Sorry I need to tag so much, however let me know if it can be merged. 

cc: @eyurtsev, @baskaryan

**Comment by ccurme** [comment]
Hi @Anindyadeep,

Do you want to add tests for the code changes here?

Langchain has a suite of standard tests for chat models in the [standard-tests](https://github.com/langchain-ai/langchain/tree/master/libs/standard-tests) library, which is already a test dependency of `langchain-community`. It includes tests for tool calling. What do you think about adding these for PremAI?

Here is an example implementation for integration tests: https://github.com/langchain-ai/langchain/blob/master/libs/partners/fireworks/tests/integration_tests/test_standard.py

And unit tests: https://github.com/langchain-ai/langchain/blob/master/libs/partners/fireworks/tests/unit_tests/test_standard.py

We can add `xfails` (as in the example) if needed where tests are failing. But this will at least illuminate the failures and provide tests for the functionality implemented here.

**Review by ccurme — APPROVED** [review]

**Pull request merged**
