### PR TITLE
community: adding AnySDK -- create toolkits from literally any SDK client

### PR DESCRIPTION
**Pull request by Barneyjm**
I've been building a lot of toolkits and found this was a quick and easy way to play with new SDKs without having to reinvent the wheel each time

Basic concept being:

```
client = SomeSdk()
anysdk = AnySdkWrapper(client=client)

agent.invoke(“perform tasks X, Y, then Z”)

(The agent will then go and use the SDK to perform those tasks)
```

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, hwchase17.

### CODE REVIEW

**Comment by Barneyjm** [comment]
@efriis If you have a moment to review, I'd appreciate it! Some documentation test (CI / test_doc_imports / check doc imports #3.11) is failing that I'm not sure I've touched.

**Review by hwchase17 — COMMENTED** [review]
this seems very cool! sorry for the delay in review

1) can we add an example notebook? I think it would help people understand this a lot better

2) this can obviously be pretty dangerous and potentially lead to CVEs. @eyurtsev what is our recomended way to handle?

**Comment by Barneyjm** [comment]
> this seems very cool! sorry for the delay in review
> 
> 
> 
> 1) can we add an example notebook? I think it would help people understand this a lot better
> 
> 
> 
> 2) this can obviously be pretty dangerous and potentially lead to CVEs. @eyurtsev what is our recomended way to handle? 

The CVE/performing write actions was something I considered and part of why I added the CrudControls class with sensible defaults (read only). Obviously it's not perfect but the user of this wrapper would have to opt into/manually change the CrudControls for "write/delete" things to happen. 

Obviously if the SDK client they wrap has CVEs in it, this class would actually prevent those from being in LangChain directly since the toolkits themselves are dynamically created on the client vs being baked into the community subpackage.

**Comment by Barneyjm** [comment]
@hwchase17 @eyurtsev updated AnySDK to use the new Tool stuff that's been introduced. 

also added example notebook. Please rereview when you have a moment! Thank you

**Comment by Barneyjm** [comment]
@baskaryan @eyurtsev Can I please get a review on this PR? Please note that I've addressed some of @hwchase17 comments and added an example notebook as well

Thank you!

**Comment by Barneyjm** [comment]
hi @baskaryan @efriis @eyurtsev @hwchase17 

can this be merged? Happy to address any outstanding issues if needed

**Review by efriis — COMMENTED** [review]
clever! I'd be ok with this in experimental. I think it's a bit brittle for non-experimental though.

Let me know if you're interested in moving it! Sorry for the delay

**Comment by efriis** [comment]
Also just clarifying the security implications of this - it's dynamically routing between commands on an sdk that might be unexpected to the user, hence the risk (not guaranteed vulnerability, but risk).

That's the desire to put in experimental

**Comment by efriis** [comment]
Will close for now and feel free to reopen in experimental if desired!

**Pull request closed without merging**
