### PR TITLE
community: Add the additonnal kward 'context' for openai

### PR DESCRIPTION
**Pull request by lucasiscovici**
- **Description:** 
Add the additonnal kward 'context' for openai into `convert_dict_to_message` and `convert_message_to_dict` functions.

### CODE REVIEW

**Comment by ccurme** [comment]
Hi @lucasiscovici, can you explain the motivation for this?

**Comment by lucasiscovici** [comment]
Hi @ccurme and @baskaryan,

Just following up to see if the motivation I shared addresses your questions. Let me know if there’s anything else I can clarify or adjust!

Thanks for your time! 😊

**Review by ccurme — APPROVED** [review]

**Comment by ccurme** [comment]
Hi @lucasiscovici,

Thanks for following up. Can you elaborate on how you are accessing the Azure chat-with-your-data service via LangChain?

Asking in case AzureChatOpenAI is involved, since the community version is [deprecated](https://python.langchain.com/api_reference/community/chat_models/langchain_community.chat_models.azure_openai.AzureChatOpenAI.html) in favor of the version in [langchain-openai](https://github.com/langchain-ai/langchain/tree/master/libs/partners/openai).

**Comment by lucasiscovici** [comment]
> Hi @lucasiscovici,
> 
> Thanks for following up. Can you elaborate on how you are accessing the Azure chat-with-your-data service via LangChain?
> 
> Asking in case AzureChatOpenAI is involved, since the community version is [deprecated](https://python.langchain.com/api_reference/community/chat_models/langchain_community.chat_models.azure_openai.AzureChatOpenAI.html) in favor of the version in [langchain-openai](https://github.com/langchain-ai/langchain/tree/master/libs/partners/openai).

Hi @ccurme, i create the PR for langchain-openai (partners)

**Pull request merged**
