### PR TITLE
add `load()` deserializer function that bypasses need for json serialization

### PR DESCRIPTION
**Pull request by alecf**
There is already a `loads()` function which takes a JSON string and loads it using the Reviver

But in the callbacks system, there is a `serialized` object that is passed in and that object is already a deserialized JSON-compatible object. This allows you to call `load(serialized)` and bypass intermediate JSON encoding.

I found one other place in the code that benefited from this short-circuiting (string_run_evaluator.py) so I fixed that too.

Tagging @baskaryan for general/utility stuff.

### CODE REVIEW

**Comment by nfcampos** [comment]
@alecf thanks for this. i do not want multiple functions with potentially diverging load or dump logic. We can only have one load function and one dump function, with any additional convenience methods calling the main one for the logic. So if you do think this is a significant performance improvement the way forward is to make the main load function call into your new one , if that makes sense

**Comment by alecf** [comment]
> @alecf thanks for this. i do not want multiple functions with potentially diverging load or dump logic. We can only have one load function and one dump function, with any additional convenience methods calling the main one for the logic. So if you do think this is a significant performance improvement the way forward is to make the main load function call into your new one , if that makes sense

that works too, let me re-work now!

**Comment by alecf** [comment]
@nfcampos ah wait, the reason I did it this way is that the JSON deserializer invokes the Reviver (which is the bulk of the shared code for deserialization) as it sees the native dictionary objects. 

If I were to make loads() call load(), it would mean that load() would have to recurse over the tree that was just rehydrated by the JSON `loads` call. IMO, what I've got here balances performance and shared logic.

The reason I'm concerned about performance here is that this load() method is very useful in callbacks, where you have a serialized object in the form of dict/lists. When using callbacks for monitoring where you often want to record everything going on in a chain and nested chains, the load/loads can be called many, many times by callback handlers (i.e. for the start of every chain, llm, agent action, etc) 

WDYT?

**Comment by alecf** [comment]
FWIW, this is what the diff to the above would look like, but you can see it means traversing the objects that the JSON deserializer already traversed: 
```diff
index 0c54c967..23afb4c4 100644
--- a/langchain/load/load.py
+++ b/langchain/load/load.py
@@ -90,7 +90,7 @@ def loads(
     Returns:
 
     """
-    return json.loads(text, object_hook=Reviver(secrets_map, valid_namespaces))
+    return load(json.loads(text))
 
 
 def load(
```

**Comment by alecf** [comment]
@nfcampos any thoughts here? I've shared as much of the implementation as I can here, and the tests will enforce that both produce the same behavior

**Comment by nfcampos** [comment]
@alecf hi, could you clarify the use case here again? You say this is is very useful in callbacks, but in callbacks we never call `load` on serialised objects, we only call `dump`

**Comment by alecf** [comment]
@nfcampos langchain itself never calls loads(), but consumers of on_chain_start can call loads() on the `serialized` argument.

**Pull request merged**
