### PR TITLE
feature: add `split_wrap_text` method to Recursive/CharacterTextSplitter

### PR DESCRIPTION
**Pull request by Yossef-Dawoad**
This method allows adding a `prefix` and a `suffix` to each split text.
This is useful for wrapping the text with special characters, tokens or formatting tags.

- This method implemented in `CharacterTextSplitter` and `RecursiveCharacterTextSplitter`
- The method `split_wrap_text` calls the existing `split_text` method internally and then adds the prefix and suffix
 to each element of the output list.
- The method has an optional parameters for the prefix and suffix, which default to empty strings.

#### Who can review?

Tag maintainers/contributors who might be interested: @eyurtsev, @vowelparrot

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
whats a use case for this?

**Comment by Yossef-Dawoad** [comment]
some embeddings require some special tokens or require the text to start with special word like `e5-large-v2` embeddings in the hugging Face Hub [Here](https://huggingface.co/intfloat/e5-large-v2), they stated, and I quote they usage case example: (read the code comments)
```python
# Each input text should start with "query: " or "passage: ".
# For tasks other than retrieval, you can simply use the "query: " prefix.

input_texts = ['query: how much protein should a female eat',
               'query: summit define',
               "passage: As a general guideline, the CDC's average requirement of protein for women ages 19 to 70 is 46 grams per day. But, as you can see from this chart, you'll need to increase that if you're expecting or training for a marathon. Check out the chart below to see how much protein you should be eating each day.",
               "passage: Definition of summit for English Language Learners. : 1  the highest point of a mountain : the top of a mountain. : 2  the highest level. : 3  a meeting or series of meetings between the leaders of two or more governments."]
```

**Comment by Yossef-Dawoad** [comment]
in my case I needed to index my documents with this `e5-large-v2` embedder and wrap each text with the word `passage: `
and that why tried to implement it.

**Comment by hwchase17** [comment]
i think probably easiest to transform the documents after splitting in this case

**Comment by Yossef-Dawoad** [comment]
Will the method also provide an easy and intuitive way to do it so why not I will say it's probably easier and more accessable for new comer of the library that could need it,
I see it also being used in preparing a data for fine tuning the LLM models such as ingesting special tokens before the text that separated with commas to indicate whether it's prompter text or assistant reply like in case of open assistant, at the end it's up to you to decide if it's helpful for the lib or not I understand that

**Comment by Yossef-Dawoad** [comment]
I have nicer refactoring for this method implementing it instead in `TextSplitter ` itself as separate method of any body needed it can be there what you think?

**Comment by eyurtsev** [comment]
@Yossef-Dawoad thanks for the contribution! 

For the text splitters, we want to limit to a single method responsible for splitting the `text`  (unless there's a compelling reason to do otherwise).

This will make it easier to compose together transformations sequentially and will allow defining a transformation once instead of having to re-implement it multiple times.

**Comment by eyurtsev** [comment]
@Yossef-Dawoad closing for now -- we may make the notion of transformation pipelines more official, which will accommodated your use case nicely

**Pull request closed without merging**
