### PR TITLE
Make SQLAlchemy wrapper class function distinct to allow more consistent filtering of tables 

### PR DESCRIPTION
**Pull request by jasonbhart**
The current wrapper class for SQLAlchemy is inconsistent in its usage of 'include_tables' and 'ignore_tables' class properties.  This pull request is meant to create a distinct function (get_usable_tables) so as to prevent the usage of tables which have been specifically excluded when the class is instantiated.  All function calls in the SQLDatabase base class and related tools have been ported to use new function.  This implementation still allows using the SQLAlchemy standard way to get all tables which exist in the database by using the original function get_all_tables(). 

This is my first pull request, so feedback is appreciated.

### CODE REVIEW

**Comment by hwchase17** [comment]
> This implementation still allows using the SQLAlchemy standard way to get all tables which exist in the database by using the original function get_all_tables().

maybe im missing someting, but doesnt this remove the get_all_tables function entirely?

**Comment by jasonbhart** [comment]
> > This implementation still allows using the SQLAlchemy standard way to get all tables which exist in the database by using the original function get_all_tables().
> 
> maybe im missing someting, but doesnt this remove the get_all_tables function entirely?

You are right.  For some reason in my testing it looked like Python was honoring overloading of the base class function based on the number of parameters used in get_all_tables(), but evidently this is not the case.  I'm happy to refactor if there is a better pattern to follow here.  Basically, the root issue I am trying to solve is get_all_tables() does not honor the 'include_tables' nor 'ignore_tables' properties of the instantiated class object.  This causes extra overhead by processing tables which should be ignored (very painful in my case where I have lots of tables in the database), and possibly allows access to tables which should be off limits for whatever reason.

**Comment by hwchase17** [comment]
got it, and so the main benefit is coming from this line: `self._metadata.reflect(bind=self._engine, only=self._usable_tables)`?

in that case, can we just keep the same naming as before (since that method isnt actually changing, and its a user facing method).

**Comment by jasonbhart** [comment]
@hwchase17 Yup. Just to confirm, you don't want to leave any access to the base class function of the same name?  It returns all possible tables.  This similar local function returns all curated (non-filtered) tables (taking into account the include and ignore statements from when the object was created).

**Comment by hwchase17** [comment]
> @hwchase17 Yup. Just to confirm, you don't want to leave any access to the base class function of the same name? It returns all possible tables. This similar local function returns all curated (non-filtered) tables (taking into account the include and ignore statements from when the object was created).

sorry i still dont think im understanding. if we reverted `get_usable_table_names` back to `get_table_names` would this change the functionality at all?

**Comment by jasonbhart** [comment]
@hwchase17 get_tables_names() exists in the SQLAlchemy base class, as well was the HEAD version of the wrapper class.  They differ in functionality.  The base class version returns all tables in the database.  The wrapper class returns a more constrained view of tables be removing tables which were specifically declared to be ignored (or explicitly included) at time of object creation.  The bug is introduced in this line:
`self._all_tables = set(self._inspector.get_table_names(schema=schema))`
...in the wrapper class, which seems to assume it is using the function defined in the wrapper class but in actuality is using the function defined in the SQLAlchemy base class.  Since these functions are named the same, I can see why that confusion was made. So this is why I took further steps to distinguish the function names in my changes.

**Comment by hwchase17** [comment]
> @hwchase17 get_tables_names() exists in the SQLAlchemy base class, as well was the HEAD version of the wrapper class. They differ in functionality. The base class version returns all tables in the database. The wrapper class returns a more constrained view of tables be removing tables which were specifically declared to be ignored (or explicitly included) at time of object creation.
> 
> The bug is introduced in this line: `self._all_tables = set(self._inspector.get_table_names(schema=schema))` ...in the wrapper class, which seems to assume it is using the function defined in the wrapper class but in actuality is using the function defined in the SQLAlchemy base class. Since these functions are named the same, I can see why that confusion was made. So this is why I took further steps to distinguish the function names in my changes.
> 
> It seems logical that if we ask for a catalog of the known universe (of tables) that we would adhere to any specific exclusions indicated at the time the object was created. This logic also follows over to the situation I am trying to rectify, which is that currently the wrapper class is trying to collect metadata about tables which are irrelevant to the operations of the object (its trying to query information about tables which were excluded from the object's context). In situations where there are a lot of tables, this wastes considerable setup time unnecessarily.

okay, lets do the naming BUT im going to add back the method, and just mark it as deprecated. that way this is backwards compatible, which is my main concern

**Comment by jasonbhart** [comment]
@hwchase17 Understood, and will try to follow a similar pattern for any future contributions.

**Pull request merged**
