### PR TITLE
Expose text-bison as chat model

### PR DESCRIPTION
**Pull request by lkuligin**
#8427

### CODE REVIEW

**Comment by baskaryan** [comment]
not sure i understand motivation, could you explain a bit more? you can already pass message to LLMs (predict_messages)

**Comment by lkuligin** [comment]
> not sure i understand motivation, could you explain a bit more? you can already pass message to LLMs (predict_messages)

oh, nice, I didn't see that actually.
but still, I'm not sure you can pass a system message (to wrap the history) to the `predict_messages` method.
plus it might be the case that the existing code expects to use `generate` method of the `ChatModel`, i.e. it adds additional burden to experiment with the text model in that case.

wdyt?

**Comment by baskaryan** [comment]
> > not sure i understand motivation, could you explain a bit more? you can already pass message to LLMs (predict_messages)
> 
> oh, nice, I didn't see that actually. but still, I'm not sure you can pass a system message (to wrap the history) to the `predict_messages` method. plus it might be the case that the existing code expects to use `generate` method of the `ChatModel`, i.e. it adds additional burden to experiment with the text model in that case.
> 
> wdyt?

you should be able to pass any messages (including system message) — was that not working for you?

**Comment by lkuligin** [comment]
OK, agreed. I'll close this one, but https://github.com/langchain-ai/langchain/pull/8529 would still make sense, wdyt?

**Pull request closed without merging**
