### PR TITLE
community: handle chatdeepinfra jsondecode error

### LINKED ISSUE #27602: ChatDeepInfra JSONDecode error when tool call args is empty string
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_community.chat_models.deepinfra import _convert_dict_to_message

response_dict = {
    "role": "assistant",
    "content": "",
    "tool_calls": [{"function": {"name": "get_something", "arguments": ""}}],
}

message = _convert_dict_to_message(response_dict)
```

### Error Message and Stack Trace (if applicable)

JSONDecodeError                           Traceback (most recent call last)
Cell In[19], [line 9](vscode-notebook-cell:?execution_count=19&line=9)
      [1](vscode-notebook-cell:?execution_count=19&line=1) from langchain_community.chat_models.deepinfra import _convert_dict_to_message
      [3](vscode-notebook-cell:?execution_count=19&line=3) response_dict = {
      [4](vscode-notebook-cell:?execution_count=19&line=4)     "role": "assistant",
      [5](vscode-notebook-cell:?execution_count=19&line=5)     "content": "",
      [6](vscode-notebook-cell:?execution_count=19&line=6)     "tool_calls": [{"function": {"name": "get_something", "arguments": ""}}],
      [7](vscode-notebook-cell:?execution_count=19&line=7) }
----> [9](vscode-notebook-cell:?execution_count=19&line=9) message = _convert_dict_to_message(response_dict)

File ~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:132, in _convert_dict_to_message(_dict)
    [129](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/shawn/sap/~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:129)     content = _dict.get("content", "") or ""
    [130](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/shawn/sap/~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:130)     tool_calls_content = _dict.get("tool_calls", []) or []
    [131](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/shawn/sap/~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:131)     tool_calls = [
--> [132](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/shawn/sap/~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:132)         _parse_tool_calling(tool_call) for tool_call in tool_calls_content
    [133](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/shawn/sap/~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:133)     ]
    [134](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/shawn/sap/~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:134)     return AIMessage(content=content, tool_calls=tool_calls)
    [135](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/shawn/sap/~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:135) elif role == "system":

File ~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:100, in _parse_tool_calling(tool_call)
     [98](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/shawn/sap/~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:98) name = tool_call["function"].get("name", "")
     [99](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/shawn/sap/~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:99) print(tool_call["function"]["arguments"])
--> [100](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/shawn/sap/~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:100) args = json.loads(tool_call["function"]["arguments"])
    [101](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/shawn/sap/~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:101) id = tool_call.get("id")
    [102](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/shawn/sap/~/sap/.venv/lib/python3.12/site-packages/langchain_community/chat_models/deepinfra.py:102) return create_tool_call(name=name, args=args, id=id)

File /usr/lib/python3.12/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    [341](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/__init__.py:341)     s = s.decode(detect_encoding(s), 'surrogatepass')
    [343](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/__init__.py:343) if (cls is None and object_hook is None and
    [344](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/__init__.py:344)         parse_int is None and parse_float is None and
    [345](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/__init__.py:345)         parse_constant is None and object_pairs_hook is None and not kw):
--> [346](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/__init__.py:346)     return _default_decoder.decode(s)
    [347](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/__init__.py:347) if cls is None:
    [348](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/__init__.py:348)     cls = JSONDecoder

File /usr/lib/python3.12/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    [332](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/decoder.py:332) def decode(self, s, _w=WHITESPACE.match):
    [333](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/decoder.py:333)     """Return the Python representation of ``s`` (a ``str`` instance
    [334](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/decoder.py:334)     containing a JSON document).
    [335](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/decoder.py:335) 
    [336](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/decoder.py:336)     """
--> [337](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/decoder.py:337)     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    [338](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/decoder.py:338)     end = _w(s, end).end()
    [339](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/decoder.py:339)     if end != len(s):

File /usr/lib/python3.12/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    [353](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/decoder.py:353)     obj, end = self.scan_once(s, idx)
    [354](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/decoder.py:354) except StopIteration as err:
--> [355](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/decoder.py:355)     raise JSONDecodeError("Expecting value", s, err.value) from None
    [356](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/usr/lib/python3.12/json/decoder.py:356) return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Description

I am using ChatDeepInfra to call the sql_db_list_tables tool from langchain's SQLDatabaseToolkit. This tool is invoked without any arguments, so tool_call["function"]["arguments"] is an empty string "", which causes an error when parsing the JSON.

Error parsing should be added, or we can just switch to something from langchain_core.output_parsers.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Fri Mar 29 23:14:13 UTC 2024
> Python Version:  3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]

Package Information
-------------------
> langchain_core: 0.3.12
> langchain: 0.3.4
> langchain_community: 0.3.3
> langsmith: 0.1.136
> langchain_text_splitters: 0.3.0
> langgraph: 0.2.39

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.10
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> httpx: 0.27.2
> jsonpatch: 1.33
> langgraph-checkpoint: 2.0.1
> langgraph-sdk: 0.1.33
> numpy: 1.26.4
> orjson: 3.10.9
> packaging: 24.1
> pydantic: 2.9.2
> pydantic-settings: 2.6.0
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.36
> tenacity: 9.0.0
> typing-extensions: 4.12.2

### PR DESCRIPTION
**Pull request by ShawnLJW**
Fixes #27602 

Added error handling to return empty dict if args is empty string or None.

### CODE REVIEW

**Review by efriis — APPROVED** [review]

**Comment by ShawnLJW** [comment]
@efriis not sure how this works since its my first PR to langchain. the PR was approved but isnt being merged cause of vercel check being cancelled, is there something i have to do?

**Comment by ShawnLJW** [comment]
@efriis can you approve the workflows

**Comment by ShawnLJW** [comment]
@efriis PR cannot be merged as the vercel deployment was cancelled again, is there something i should do differently?

**Comment by efriis** [comment]
merged! and fixing the case in the docs ignore step here: https://github.com/langchain-ai/langchain/pull/27971

**Pull request merged**
