### PR TITLE
Mask API Key for OpenAI based ChatModels (OpenAI,AzureOpenAi,Konko)

### PR DESCRIPTION
**Pull request by onesolpark**
- **Description:** Added API Key masking for all OpenAI based ChatModels (OpenAI, Azure OpenAI, Konko)  
     - Updated OpenAI Chat model to use SecretStr to mask sensitive API Key. (Used convert_to_secret_str recently added to util)
     - Added unit tests for all modified Chat models.
  - **Issue:** #12165 
  - **Dependencies:** None
  - **Tag maintainer:** @eyurtsev

Konko and OpenAI both implemented OpenAI, so needed to change all three to avoid errors.

### CODE REVIEW

**Comment by onesolpark** [comment]
Rebased and updated poetry.lock with changes to content-hash
@baskaryan Can you please another look at this?

**Comment by onesolpark** [comment]
@eyurtsev pinging for your help on workflow and merge :)

**Comment by onesolpark** [comment]
@eyurtsev lots of changes happened and I am trying to change accordingly and asking your opinion.

1) Konko no longer implements ChatOpenAI model #12948 (seems accidental as you mentioned)
    => Should I remove changes to Konko in this PR or just keep them.
2) AzureChatOpenAI derives from ChatOpenAI chat-model and needs both of them to get fixed to work correctly but ChatOpenAI seems like to be assigned to someone else. 
    => Is it okay to fix both of them in this PR?

Also this PR has a lot of commits that are predated, do you want me to create a new PR with the changes?

**Comment by hwchase17** [comment]
i would likely suggest close and open new ones, probably one for each model

thanks (and sorry!)

**Pull request closed without merging**
