### PR TITLE
community[patch]: baidu-qianfan: delete the default model value from langchain and discard the need fo…

### PR DESCRIPTION
**Pull request by Dobiichi-Origami**
- description: I remove the limitation of mandatory existence of `QIANFAN_AK` and default model name which langchain uses cause there is already a default model nama underlying `qianfan` SDK powering langchain component.

### CODE REVIEW

**Review by ccurme — APPROVED** [review]
Could you confirm that integration tests pass? CI doesn't run them.

**Comment by Dobiichi-Origami** [comment]
截屏2024-08-05 12 31 10
definitely. @ccurme

**Comment by ccurme** [comment]
Thanks @Dobiichi-Origami, would you mind running the tests in `tests.integration_tests.chat_models.test_qianfan_endpoint` as well? (It looks like there are two modules, should probably be consolidated.)

**Comment by Dobiichi-Origami** [comment]
> Thanks @Dobiichi-Origami, would you mind running the tests in `tests.integration_tests.chat_models.test_qianfan_endpoint` as well? (It looks like there are two modules, should probably be consolidated.)

Thx for your reminder :) @ccurme 

截屏2024-08-06 10 56 20

**Review by ccurme — APPROVED** [review]

**Pull request merged**
