### PR TITLE
Provides access to a Document page_content formatter in the AmazonKendraRetriever

### PR DESCRIPTION
**Pull request by wnleao**
- Description: 
    - Provides a new attribute in the AmazonKendraRetriever which processes a ResultItem and returns a string that will be used as page_content;
    - The excerpt metadata should not be changed, it will be kept as was retrieved. But it is cleaned when composing the page_content;
    - Refactors the AmazonKendraRetriever to improve code reusability;
- Issue: #7787 
- Tag maintainer: @3coins @baskaryan
- Twitter handle: wilsonleao

**Why?**

Some use cases need to adjust the page_content by dynamically combining the ResultItem attributes depending on the context of the item.

### CODE REVIEW

**Comment by baskaryan** [comment]
lgtm, thoughts @3coins?

**Comment by wnleao** [comment]
thanks @baskaryan ! I added a minor check for top_k and adjusted the result slice as well

**Comment by wnleao** [comment]
Hello, @3coins ! How is it going there? Any suggestions? Thanks in advance!

**Comment by wnleao** [comment]
Hey @baskaryan ! Is it okay if we move forward with this one?

**Review by hwchase17 — APPROVED** [review]
looks reasonable to me! thanks

**Comment by 3coins** [comment]
@wnleao 
Thanks for working on this. Sorry, I missed this in my notifications.

**Comment by wnleao** [comment]
No worries, @3coins ! 
I issued another PR with a small adjustment here https://github.com/langchain-ai/langchain/pull/8796. Thanks in advance!

**Pull request merged**
