### PR TITLE
The current version supports any number of fields

### PR DESCRIPTION
**Pull request by zhanghexian**
The current version supports any number of fields

### CODE REVIEW

**Comment by zhanghexian** [comment]
我已收到,谢谢!张和先.

**Comment by baskaryan** [comment]
@zhanghexian resolved all merge conflicts, does it still look good to you?

**Comment by zhanghexian** [comment]
我已收到,谢谢!张和先.

**Comment by zhanghexian** [comment]
yes.thanks!



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 2, 2024 09:24 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [langchain-ai/langchain] The current version supports any numberof fields (PR #12981)




 
@zhanghexian resolved all merge conflicts, does it still look good to you?

**Review by baskaryan — APPROVED** [review]

**Comment by zhanghexian** [comment]
Hello, vearch vector database has made the latest adjustment according to the latest version of python sdk, please check it, thank you!

**Comment by zhanghexian** [comment]
i am sorry,i can not find this file to slove it's problem(tests/unit_tests/vectorstores/test_public_api.py),and i found that lint rule of vearch.jupyter is different for different python version.Please tell me how to fix this ,thanks!

**Comment by ccurme** [comment]
> i am sorry,i can not find this file to slove it's problem(tests/unit_tests/vectorstores/test_public_api.py),and i found that lint rule of vearch.jupyter is different for different python version.Please tell me how to fix this ,thanks!

Please see contributor guidelines [here](https://python.langchain.com/v0.2/docs/contributing/code/setup/#formatting-and-linting) for formatting and linting.

**Comment by zhanghexian** [comment]
我已收到,谢谢!张和先.

**Comment by efriis** [comment]
closing due to still failing CI. Would recommend checking out the docs chester posted if you want to reopen!

Also, if you're interested in maintaining this integration without us in the loop, we'd love to get an integration package out! Future PRs against langchain would just be {docs updates, as well as registering your package in `libs/packages.yml`, deprecating this community integration in favor of your integration package}

Here's the guide, and if you have questions, feel free to leave them in the comments on those pages so others can see them! https://python.langchain.com/docs/contributing/how_to/integrations/

**Comment by zhanghexian** [comment]
我已收到,谢谢!张和先.

**Pull request closed without merging**
