### PR TITLE
community: add attribution_token within GoogleVertexAISearchRetriever

### PR DESCRIPTION
**Pull request by hsuyuming**
- [x] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [x]  **PR message**: ***Delete this entire checklist*** and replace with
    - **Description:** Add attribution_token within GoogleVertexAISearchRetriever so user can provide this information to Google support team or product team during debug session.
    
        Reference: https://cloud.google.com/generative-ai-app-builder/docs/view-analytics#user-events

        Attribution tokens. Attribution tokens are unique IDs generated by Vertex AI Search and returned with each search request. Make sure to include that attribution token as UserEvent.attributionToken with any user events resulting from a search. This is needed to identify if a search is served by the API. Only user events with a Google-generated attribution token are used to compute metrics.
    
    - **Issue:** No
    - **Dependencies:** No
    - **Twitter handle:** abehsu1992626

- [x] **Add tests and docs**: No new testcase
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

### CODE REVIEW

**Comment by hsuyuming** [comment]
@lkuligin @efriis Is it possible to help me review this PR when you are available?

**Comment by lkuligin** [comment]
Thank you @hsuyuming for working on this!
I like the idea very much, but maybe it's a little better to have a custom callback for that, wdyt? Such a callback can be used to gather some generation info (it might be expanded later) and to be aligned with how LC does things in general.

And on a separate note, we'll be moving (+ refactoring) this integration to `langchain-google` repo since there're some changes on the SDK side.

**Comment by hsuyuming** [comment]
Hi @lkuligin :

I thought about it as well. Unfortunately, i didn't find a way which allow me to do it. Currently, GoogleVertexAISearchRetriever is inherit from BaseRetriever, within get_relevant_documents, langchain initial their CallbackManager from line 218-232, so I can't provide my own  CallbackManager.  CallbackManager can use for on_retriever_start event, and on_retriever_start will return CallbackManagerForRetrieverRun, which allow you log on_retriever_end and on_retriever_error event. So i haven't find a way how can i implement the same logic by providing callback. Please let me know if you have other idea.
 
 @hwchase17  @efriis  @baskaryan If you can give me some direction, i will very appreciate your help 

https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/retrievers.py#L218-L232

https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/callbacks/manager.py#L1374-L1408

https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/callbacks/manager.py#L1081-L1116

**Comment by lkuligin** [comment]
afaik, when you invoke a retrieval, you can provide a config with the relevant callbacks.

so I'd suggest, in the `GoogleVertexAISearchRetriever`, add relevant info to the metadata of the generated Document (maybe under `generation_info` key)

and handle this key with your callback

@baskaryan pls, correct me if my approach is wrong

**Comment by hsuyuming** [comment]
@lkuligin :

Can you make sure if my understand is correctly?

You would like to put the information within document's metadata, in order to do that i need to extract attribution_token from  
response [1], then i need to add one function parameter for _convert_unstructured_search_response[2], _convert_structured_search_response[3] and _convert_website_search_response[4] in order to pass this informatoin. Then add attribution_token as metadata within each documents.

For example

```python
def _convert_unstructured_search_response(
        self, results: Sequence[SearchResult], chunk_type: str, attribution_token: str
    ) -> List[Document]:
        """Converts a sequence of search results to a list of LangChain documents."""
        from google.protobuf.json_format import MessageToDict

        documents: List[Document] = []

        for result in results:
            document_dict = MessageToDict(
                result.document._pb, preserving_proto_field_name=True
            )
            derived_struct_data = document_dict.get("derived_struct_data")
            if not derived_struct_data:
                continue

            doc_metadata = document_dict.get("struct_data", {})
            doc_metadata["id"] = document_dict["id"]
            doc_metadata["attribution_token"] = attribution_token

            if chunk_type not in derived_struct_data:
                continue

            for chunk in derived_struct_data[chunk_type]:
                chunk_metadata = doc_metadata.copy()
                chunk_metadata["source"] = derived_struct_data.get("link", "")

                if chunk_type == "extractive_answers":
                    chunk_metadata["source"] += f":{chunk.get('pageNumber', '')}"

                documents.append(
                    Document(
                        page_content=chunk.get("content", ""), metadata=chunk_metadata
                    )
                )

        return documents
```


[1] https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/retrievers/google_vertex_ai_search.py#L353

https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/retrievers/google_vertex_ai_search.py#L366

https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/retrievers/google_vertex_ai_search.py#L370

https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/retrievers/google_vertex_ai_search.py#L375

**Comment by baskaryan** [comment]
@hsuyuming ideally we don't make the retriever stateful, re-implemented so there was a separate method that returned the raw response (including attribution_tokens) along with the docs. does that fit your use case?

**Review by baskaryan — APPROVED** [review]

**Comment by hsuyuming** [comment]
Hi @baskaryan 
Sorry, i just saw your change, may i ask one question?
If user use ConversationalRetrievalChain, how can they get  attribution_tokens from response? Since ConversationalRetrievalChain execute _get_relevant_documents. Can you give me some suggestions?

**Pull request merged**
