### PR TITLE
community: support async streaming for VertexAI model.

### PR DESCRIPTION
**Pull request by bit-team-rakket**
**Description**
Support async streaming for VertexAI model. The async method implementations are now aligned with their non-async counterparts for consistency.

### CODE REVIEW

**Review by baskaryan — COMMENTED** [review]
cc @lkuligin @efriis

**Comment by baskaryan** [comment]
@bit-team-rakket we've moved the main Vertex integration to its own package in `libs/partners/google-vertexai`. Would you have any interest in moving this change to that package?

**Comment by bit-team-rakket** [comment]
Sure, I will update this PR to move the code changes.

**Comment by lkuligin** [comment]
@bit-team-rakket thanks for your contribution! linting is failing, but otherwise it looks good to me.

**Review by lkuligin — APPROVED** [review]

**Comment by efriis** [comment]
Should already be implemented in partner package! FYI it's now out of this repo: github.com/langchain-ai/langchain-google

**Pull request closed without merging**
