### PR TITLE
Fix region sagemaker

### PR DESCRIPTION
**Pull request by Khaliladib11**
I encountered an issue while working with the Sagemaker endpoint module and attempting to establish a connection to the client. 
The error message `"Failed to load credentials for AWS client authentication`" was being raised, despite passing the **`profile_name`** parameter. 

Upon reviewing the code, I realized that the error was caused by the omission of the **`region_name`** parameter. To address this, I introduced a validation step to ensure that the **`region_name`** parameter is provided, and I implemented an error-raising mechanism in case the parameter is found to be `None`. 

This adjustment effectively resolved the issue.

Thanks!

### CODE REVIEW

**Comment by baskaryan** [comment]
should we remove the default "" value if this is required? cc @3coins

**Comment by 3coins** [comment]
Re

> should we remove the default "" value if this is required? cc @3coins

`region_name` shouldn't be a required parameter, as the boto client should be able to pick the region defined in the default profile. It seems like in case of a named profile, if the default region is different from the named profile, boto doesn't pick up the region from the profile, instead uses the default region. Here is what I found on my machine.

#### Profiles
```
[default]
region = us-west-1
output = json

[profile bedrock-admin]
region = us-east-1
```

#### Sample code
```python
>>> import boto3
>>> session = boto3.Session('bedrock-admin')
>>> session.region_name
'us-west-1'
>>> 
```

The fix for now should be to only add that check for region inside the first if block if a named profile is passed. I will do some more investigation into this and see what the appropriate update should be. This could be a bug on the boto side, so will need some time to find the root cause.

**Comment by 3coins** [comment]
@Khaliladib11 
> that's correct we can get the region name from the boto session. I did what I did cz I saw that the region is one of the params.

As I stated earlier in my comments, current boto session is not bringing in the region_name associated with the named profile when session is created. Adding a check there and making sure region is passed would fix the experience for these users.

> can we just pass the sagemaker session as input?

Yes, you can create the SageMaker boto client outside of this class and pass as the `client` attribute, and that should work as well. However, not all users prefer that.

**Comment by leo-gan** [comment]
@Khaliladib11 If this PR is not needed anymore, could you, please, let me know or close this PR?
It is not clear do we need this PR or not.

**Comment by khalilfiremind** [comment]
@leo-gan as described above, the problem might be from boto3 side, but it's better to check the region param when passing the profile directly to the module

**Comment by leo-gan** [comment]
@Khaliladib11 Sorry, it is not clear what should be the next steps with this PR. Are you going to "check the region param when passing the profile directly to the module"? Or do you want help with this?

**Comment by khalilfiremind** [comment]
@leo-gan I've added the code to check the region, you can merge it if you want.

**Comment by leo-gan** [comment]
@baskaryan Could you, please, review it?

**Comment by efriis** [comment]
Hey @Khaliladib11 ! I'll close this because I don't think we actually want to globally raise this exception whenever region isn't set. Instead, I agree that boto3 could raise some more useful exceptions in this case.

Happy to discuss if you strongly disagree! If you want to open a PR against the langchain sagemaker docs describing this troubleshooting step, that could be an amazing way to help the community too :)

**Comment by khalilfiremind** [comment]
@efriis from what I can see in the code, there are three ways to create a session in the `SagemakerEndpoint`. 

1. First one is by passing the client directly to the interface.
2. Second one is by passing the `credentials_profile_name` to the interface, so the `SagemakerEndpoint` will use the profile name to initiate the session
3. lastly, if either the client is being pass directly neither the `credentials_profile_name`, a default session will be used, as we can see in picture. But the problem is when using the default session, when initialzing the `sagemaker-runtime`, a region name must be send with `SagemakerEndpoint`. In case the user didn't send it, the code will return an error, and because the code is wrapped inside try and expect block, it will return the following error:

```
                  "Could not load credentials to authenticate with AWS client. "
                    "Please check that credentials in the specified "
                    "profile name are valid."
```

in this case it's impossible to know that the problem was from `region_name`. That's why I did the PR to check the `region_name`. 

Back to your point, it wan't check the region at all time, it does it only when the default session is used.

Screenshot 2023-11-13 at 18 47 27

**Comment by Khaliladib11** [comment]
@efriis  from what I can see in the code, there are three ways to create a session in the `SagemakerEndpoint`.

1. First one is by passing the client directly to the interface.
2. Second one is by passing the `credentials_profile_name` to the interface, so the `SagemakerEndpoint` will use the profile name to initiate the session
3. lastly, if either the client is being pass directly neither the `credentials_profile_name`, a default session will be used, as we can see in picture. But the problem is when using the default session, when initialzing the `sagemaker-runtime`, a region name must be send with `SagemakerEndpoint`. In case the user didn't send it, the code will return an error, and because the code is wrapped inside try and expect block, it will return the following error:
```
                  "Could not load credentials to authenticate with AWS client. "
                    "Please check that credentials in the specified "
                    "profile name are valid."
```
in this case it's impossible to know that the problem was from region_name. That's why I did the PR to check the `region_name`.

Back to your point, it wan't check the region at all time, it does it only when the default session is used.

Screenshot 2023-11-13 at 18 57 09

**Comment by efriis** [comment]
Understood, but I believe it would still be a breaking change for people using the default session and relying on the default region when creating a `boto3` session in the way 3coins showed above. https://github.com/langchain-ai/langchain/pull/9269#issuecomment-1679723577

Given this is a developer experience issue with how boto uses the region, I think it should be addressed there, but if you want to land a PR documenting this in the LangChain sagemaker guide, that would be a good way to prevent people from running into the same bug.

**Comment by Khaliladib11** [comment]
@efriis  I don't think it will be a breaking change because if the user didn't send the `region_name` the code is impossible to work, because the default region is not being used. 

So what I can do is:

- update the code to use the default region when the `region_name`  is not being passed by the user
OR
- or just update the docs to add this hint.

**Comment by efriis** [comment]
You are correct. Appreciate your help walking me through this! Let me see if I can reproduce this edge case and get back to you.

It looks like the error if `region_name=None` is correct from botocore -> it correctly raises a NoRegionError.

But it sounds like there's something else going on when the session is loaded from a named profile.

**Comment by efriis** [comment]
Ok @Khaliladib11 - @langchain-infra and I can't seem to reproduce the ambiguous error you saw, so still going to close this. When no region is set in the profile and here, I get `NoRegionError: You must specify a region`, which feels clear enough to me.

If you have repro code like the following, that would be super helpful! Otherwise, I would recommend putting a PR up against `botocore` instead of LangChain to improve this unfortunate sdk error message.

```
import boto3

session = boto3.Session(profile_name='my-profile')
client = session.client('sagemaker-runtime', region_name=None)
```

**Pull request closed without merging**
