### PR TITLE
Add PandocRSTLoader

### PR DESCRIPTION
**Pull request by kdcokenny**
Note: I accidentally deleted the branch so the original request was automatically closed. Won't make that mistake again haha.

A loader that loads a .rst (reStructuredText) file, converts it into a markdown format and wraps it into a Document instance using the lazy-loading method.

It requires pypandoc

@eyurtsev @hwchase17

### CODE REVIEW

**Review by rlancemartin — APPROVED** [review]
lgtm

**Comment by rlancemartin** [comment]
@kdcokenny do you mind rebasing or merging `master` to resolve conflicts?

**Comment by kdcokenny** [comment]
> @kdcokenny do you mind rebasing or merging `master` to resolve conflicts?

Yeah, no problem

**Comment by rlancemartin** [comment]
> > @kdcokenny do you mind rebasing or merging `master` to resolve conflicts?
> 
> Yeah, no problem

@kdcokenny one thing to check: `UnstructuredRSTLoader` recently [went in](https://github.com/hwchase17/langchain/pull/6594) and produces some merge conflicts. Does `PandocRSTLoader ` have capabilities in addition to that? If so, we might simply add it to the existing `rst` notebook?

**Comment by rlancemartin** [comment]
@kdcokenny when you have a chance, please merge master and resolve conflict. We can then confirm tests pass and get this merged.

**Comment by rlancemartin** [comment]
@kdcokenny appreciate the work here. Given https://github.com/hwchase17/langchain/pull/6594, is there anything from this PR that we want to add that extends the functionality or clarity?

**Pull request closed without merging**
