### PR TITLE
Langchain/New-feature: Added Haskell support in langchain.text_splitter module

### PR DESCRIPTION
**Pull request by Nisarg1112**
- **Description:** Haskell language support added in text_splitter module
  - **Dependencies:** No
  - **Twitter handle:** @nisargtr

If no one reviews your PR within a few days, please @-mention one of @baskaryan, @eyurtsev, @hwchase17.

### CODE REVIEW

**Review by baskaryan — APPROVED** [review]
looks like there's some merge conflicts, but code lgtm! thank you @Nisarg1112!

**Comment by baskaryan** [comment]
if you have a chance would be great to add an example to `docs/docs/modules/data_connection/document_transformers/code_splitter.ipynb` page

**Comment by Nisarg1112** [comment]
> if you have a chance would be great to add an example to `docs/docs/modules/data_connection/document_transformers/code_splitter.ipynb` page

Sure, will add.

**Comment by fynnfluegge** [comment]
Hey @Nisarg1112, if you sync your master branch with latest langchain master branch I can add the examples to `code_splitter.ipynb`

**Comment by Nisarg1112** [comment]
@hwchase17 Hi, I was planning to sync this branch with the latest master. I noticed the pull request has been closed. Could you please share the reason behind the decision? Thank you for your time.

**Comment by baskaryan** [comment]
not intentional, we can't reopen at the moment but will do so as soon as we can :/ See #16796

**Comment by fynnfluegge** [comment]
@baskaryan thank you 🙏

**Comment by Nisarg1112** [comment]
@baskaryan Aplogies for the delay! I got stuck at work.

I've resolved conflicts and also added examples to the code_splitter notebook.
Can you please review these changes?

@fynnfluegge - Never mind - I've added example. Thanks!

**Comment by Nisarg1112** [comment]
@baskaryan Hey, Just a gentle ping on this. Is there any issue with this PR that needs to be addressed before merging it?

**Comment by Nisarg1112** [comment]
@baskaryan Hey, are we planning to merge this PR? We wanted to merge this PR to main branch for future purposes related to Haskell language.

**Comment by Nisarg1112** [comment]
@baskaryan Thanks for your support!

**Pull request merged**
