### PR TITLE
Update debugging image link for LangSmith Run

### PR DESCRIPTION
**Pull request by gyliu513**

### CODE REVIEW

**Comment by baskaryan** [comment]
@gyliu513 things in `static` directory treated as being in root by docusaurus, so `/img/...` is correct. were you seeing some issues?

**Comment by gyliu513** [comment]
Screenshot 2023-08-14 at 2 48 15 PM

When I was viewing it online, I found the image is empty, am I missing anything? Thanks

**Comment by leo-gan** [comment]
@gyliu513 Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

**Comment by gyliu513** [comment]
@leo-gan sorry for late, but it works well at https://python.langchain.com/docs/guides/debugging , seems not a problem, let me close it, thanks

**Pull request closed without merging**
