### PR TITLE
use openapi_pydantic

### PR DESCRIPTION
**Pull request by themrzmaster**

### CODE REVIEW

**Comment by baskaryan** [comment]
hey @themrzmaster thanks for the PR! could you provide some motivation for the switch?

**Comment by themrzmaster** [comment]
@baskaryan Hi! this version https://github.com/kuimono/openapi-schema-pydantic/issues/29 is a fork of the original repo, it works with pydantic 1 and 2 :)

**Comment by eyurtsev** [comment]
Looks like it's this repo: https://github.com/mike-oakley/openapi-pydantic

**Comment by leo-gan** [comment]
@themrzmaster If this PR is not needed anymore, could you, please, let me know or close this PR?

**Pull request closed without merging**
