### PR TITLE
Add Selenium tool to let autogpt agent use Chrome interactively

### PR DESCRIPTION
**Pull request by richardyc**
Adds a functionality to let autogpt agents use Chrome interactively. Now AutoGPT can browse the internet and click on buttons.

See an example video below of the agent booking a restaurant on Chrome:

Given a prompt "Find me a French restaurant that have availability on Apr 24th". It was able to go to Resy and click on the correct dates and see that there is no availability.
DEMO_AdobeExpress_AdobeExpress

### CODE REVIEW

**Comment by vowelparrot** [comment]
Great timing ([twin pr](https://github.com/hwchase17/langchain/pull/3262))! 

Will review in a bit

**Comment by richardyc** [comment]
> Great timing ([twin pr](https://github.com/hwchase17/langchain/pull/3262))!
> 
> Will review in a bit. Love the interactivity

haha awesome, the timing couldn't be better. ;-) will take a look at your PR too. Thanks!

**Comment by vowelparrot** [comment]
@richardyc thanks for your patience! We added the playwright browser - I'd love to add this as a notebook to start and then add a some more core selenium browser tools after the recent refactor

**Comment by richardyc** [comment]
> @richardyc thanks for your patience! We added the playwright browser - I'd love to add this as a notebook to start and then add a some more core selenium browser tools after the recent refactor

sounds good, I can add some new functionalities once the selenium tool is available, from my recent project at [Chrome-GPT](https://github.com/richardyc/Chrome-GPT).

**Pull request closed without merging**
