### PR TITLE
fix: add HuggingFacePipeline model_id parameter

### PR DESCRIPTION
**Pull request by NotShrirang**
**PR title**: "Fixes issue with model parameter not getting initialized correctly when passing transformers pipeline"
- Package: "langchain_huggingface"

- **Issue:** #25915
- **Dependencies:** None

The current version of the [code](https://github.com/langchain-ai/langchain/blob/master/libs/partners/huggingface/langchain_huggingface/llms/huggingface_pipeline.py) contains default parameter of `model_id` in `HuggingFacePipeline` class. If the user passes a transformers pipeline object, ideally the default value should get overridden, but it doesn't. This PR fixes it.

Cheers!

### CODE REVIEW

**Review by eyurtsev — CHANGES_REQUESTED** [review]
Should this not be fixed via the initialiaztion path instead?

i.e., create `__init__` or `@root_validator(pre=True)` and set model_id appropriately based on whether pipeline exists or whether a user provided a value for the model id

**Comment by NotShrirang** [comment]
@eyurtsev I have added the root initializer as you had suggested. Please review the changes.

**Comment by NotShrirang** [comment]
Hello @eyurtsev can you review the changes?

**Comment by eyurtsev** [comment]
Hi @NotShrirang, i re-merged the code against the updated master branch (which uses pydantic 2)

The original code did not look correct in terms of initialization logic since it was not handling the defaults properly -- i rewrote the code to match the description in the PR.

Given that the original PR had errors in it, could you please add a unit test before we can merge this PR that tests that initialization is working as expected.

**Pull request closed without merging**
