### PR TITLE
feat(llms): support vLLM's OpenAI-compatible server

### PR DESCRIPTION
**Pull request by mspronesti**
This PR aims at supporting [vLLM's OpenAI-compatible server feature](https://vllm.readthedocs.io/en/latest/getting_started/quickstart.html#openai-compatible-server), i.e. allowing to call vLLM's  LLMs like if they were OpenAI's. 

I've also udpated the related notebook providing an example usage. At the moment, vLLM only supports the `Completion` API.

### CODE REVIEW

**Comment by baskaryan** [comment]
very cool, thanks @mspronesti!

**Comment by RomainEconomics** [comment]
@mspronesti

This solution doesn't seem to work on my side.

I have my vllm running with the OpenAI-compatible server.

I can call it using curl or requests like this :

```
import requests


base_url = "SOME_URL/"
prompt = "Hello world"

resp = requests.post(
    f"{base_url}completions",
    headers={
        "content-type": "application/json",
    },
    json={
        "prompt": prompt,
        "max_tokens": 50,
        "temperature": 0.5,
        "model": "models/",
    },
)

print(resp.json()['choices'][0]['text'].strip())
```

This works fine and I received an OK response from the server :

```
INFO:     100.64.0.22:42816 - "POST /v1/completions HTTP/1.1" 200 OK
```


But when I call the server using langchain and the VLLMOpenAI, this doesn't work : 

```
from langchain.llms import VLLMOpenAI

llm = VLLMOpenAI(openai_api_base=base_url, openai_api_key="EMPTY", model_name="models/", temperature=0)
llm("Hello world!")
```

I get :

```
INFO:     100.64.0.22:59162 - "GET /v1/completions HTTP/1.1" 405 Method Not Allowed
```

Hence, I see that it is trying to make a GET request when a POST is expected

**Comment by mspronesti** [comment]
@RomainEconomics I can't reproduce your error. Using `models/` as `model_name` yields a 404 for me, even using the snippe that you provided.
Can you detail what model are you using and how are you running the openai-compatible server ? 

Here's my experimental setup

```shell
$ python -m vllm.entrypoints.openai.api_server --model "tiiuae/falcon-7b" --trust-remote-code
```

```py
from langchain.llms import VLLMOpenAI

base_url = "http://localhost:8000/v1"

llm = VLLMOpenAI(
    openai_api_base=base_url,
    openai_api_key="EMPTY",
    model_name="tiiuae/falcon-7b",
    temperature=0
)
llm("Hello world!")
```

from which I get 
```shell
INFO:     127.0.0.1:48452 - "POST /v1/completions HTTP/1.1" 200 OK
```

**Comment by RomainEconomics** [comment]
Thanks for your quick answer @mspronesti

Sorry for the confusion  with "models/", it was just a llama 2 model stored on disk.

I'm not sure what caused the error, but  by recreating a new venv, it now works.

**Comment by mspronesti** [comment]
Happy that worked :)

**Pull request merged**
