### PR TITLE
safely interrupt streaming requests

### PR DESCRIPTION
**Pull request by thehunmonkgroup**
# Safely interrupt streaming requests

Enables raising a `StreamInterruption` exception from a callback handler to interrupt streaming requests.

Handles cleanup of the underlying HTTP request.

### More details, example usage

Here's an example usage of a callback handler that I've tested as working:

```python
class VerboseStreamingStdOutCallbackHandler(StreamingStdOutCallbackHandler):
    @property
    def always_verbose(self) -> bool:
        """Whether to call verbose callbacks even if verbose is False."""
        return True

def make_interrupt_streaming_callback_handler(backend):
    class InterruptStreamingCallbackHandler(VerboseStreamingStdOutCallbackHandler):
        def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
            if not backend.streaming:
                message = "Request to interrupt streaming"
                backend.log.info(message)
                raise StreamInterruption(message)
    return InterruptStreamingCallbackHandler()
```

At this moment, I've only implemented the change for the `_generate` method in the OpenAI Chat LLM. I have not investigated the `_agenerate` method, or any other LLMs yet -- would like to get some feedback/confirmation on the approach first.

## Who can review?

Community members can review the PR once tests pass. Tag maintainers/contributors who might be interested:

@agola11

### CODE REVIEW

**Comment by agola11** [comment]
Thanks for your PR @thehunmonkgroup, I think the approach makes sense at a high level. One nit is that we no longer need to specify the `always_verbose` property as the verbose flag now only controls the `StdOutCallbackHandler`

We're in the process of rethinking our approach to streaming to make it easier for users to control what gets streamed/what doesn't. I should have a clearer idea of how to move forward by tomorrow so let me get back to you then.

**Comment by thehunmonkgroup** [comment]
@agola11 is there any update on this? Would really love to have a clean and sane way to stop streaming requests :)

**Comment by thehunmonkgroup** [comment]
@agola11 alrighty, I fixed an upstream conflict, this PR is in a good state again.

Can we move this feature forward? I'm happy to work on it to better prepare it for merge.

**Comment by thehunmonkgroup** [comment]
@agola11 Can you give me some  guidance on this PR? I've been maintaining it for two months with no feedback. Happy to put in the work, but I need your help!

**Pull request closed without merging**
