### PR TITLE
Fixes: community: fix AzureSearch Oauth with azure_ad_access_token

### PR DESCRIPTION
**Pull request by clairebehue**
**Description:** 
AzureSearch vector store: create a wrapper class on `azure.core.credentials.TokenCredential` (which is not-instantiable) to fix Oauth usage with `azure_ad_access_token` argument 

**Issue:**  [the issue it fixes](https://github.com/langchain-ai/langchain/issues/26216)

 **Dependencies:** None

- [x] **Lint and test**

### CODE REVIEW

**Comment by levalencia** [comment]
your fix seems more stable than mine, so go ahead and merge

**Comment by clairebehue** [comment]
@efriis since you reviewed https://github.com/langchain-ai/langchain/pull/24330 any chance you could take a look at this quick fix ? 🙏  (do not hesitate to indicate if i should follow a different process to get approval for this PR)

**Review by efriis — COMMENTED** [review]
since this doesn't work anyways, should we just remove it? 

The original justification was that this was an auth format that AzureOpenAI supports, and I'm starting to think it's an antipattern based on the difficulty to use it from the azure sdk

I think it's ok that Azure OpenAI service supports some different auth formats than azure vectorsearch given they're configured differently.

What are your thoughts?

**Comment by clairebehue** [comment]
> since this doesn't work anyways, should we just remove it?
> 
> The original justification was that this was an auth format that AzureOpenAI supports, and I'm starting to think it's an antipattern based on the difficulty to use it from the azure sdk
> 
> I think it's ok that Azure OpenAI service supports some different auth formats than azure vectorsearch given they're configured differently.
> 
> What are your thoughts?

what do you mean by it doesn't work anyway? this fix allows to use oauth token successfully.

**Comment by clairebehue** [comment]
@efriis can we proceed on this PR? we'd love to reuse it on our side (Dataiku company) to allow our customers to use oauth per user using the oauth tokens.

**Comment by SirSiLves** [comment]
@efriis is there any chance to get this PR merged soon? We have to use `azure_ad_access_token` cause our security too.

**Comment by efriis** [comment]
sorry for the delay. I still don't love these wrapper classes on tokens that are auto-computing expirations - hopefully the azure team has a better auth mechanism in store for some of the langchain-azure integrations!

**Pull request merged**
