### PR TITLE
Docs: update how to use agent in Slack's docs

### PR DESCRIPTION
**Pull request by taimo3810**
**Description:** update how to use agent in Slack's docs

### CODE REVIEW

**Review by rlancemartin — COMMENTED** [review]
Thanks for adding! 

(1) Do you mind added verbose output for one of the invocations?

We have that in other examples, as shown below:

https://python.langchain.com/docs/integrations/toolkits/multion

It can be helpful for folks to see the expected behavior.

**Comment by taimo3810** [comment]
@rlancemartin 
Thank you for reviewing my pull request and giving me the clear guide to improve the pull request!
I applied your feedback. Please review it!

**Comment by rlancemartin** [comment]
Added fmt to fix lint [here](https://github.com/langchain-ai/langchain/pull/16732) and will merge now.

**Comment by rlancemartin** [comment]
@taimo3810 I merged this update to the docs w/ minor formatting, so we can close this PR. Thank you!

**Pull request closed without merging**
