### PR TITLE
Chat integration for MistralAI API

### PR DESCRIPTION
**Pull request by thehunmonkgroup**
- **Description:** `ChatMistralAI` integration for https://docs.mistral.ai/api
  - **Dependencies:** Must install the `mistralai` package
  - **Tag maintainer:** @hwchase17

### CODE REVIEW

**Comment by thehunmonkgroup** [comment]
P.S. This is my first attempt at adding an integration and a notebook page for doc, happy to take feedback!

**Comment by thehunmonkgroup** [comment]
All the test failures are due to the `mistralai` package requiring Pydantic 2.x, while some of Langchain still requires 1.x.

**Comment by baskaryan** [comment]
@thehunmonkgroup thanks for the PR!

We've actually started pulling out certain integrations into their own packages. This allows us to explicitly specify their dependencies and independently version them, which should make them much more stable and reliable.

We just released this sort of package for google gemini models: langchain-google-genai
- code: https://github.com/langchain-ai/langchain/tree/master/libs/partners/google-genai
- docs: https://python.langchain.com/docs/integrations/chat/google_generative_ai
- api ref: https://api.python.langchain.com/en/latest/google_genai_api_reference.html

Would you be interested in starting a langchain-mistralai package like this (instead of adding the integration to langchain-community)? Started a PR for it, happy to land if you're onboard: #14783

**Comment by thehunmonkgroup** [comment]
Closing, as https://github.com/langchain-ai/langchain/pull/14783 solves the remaining issue with this code, work can continue over there. Thanks @baskaryan !

**Pull request closed without merging**
