### PR TITLE
Nemo embeddings for issue #16095

### PR DESCRIPTION
**Pull request by nvpranak**
This PR is adding support for NVIDIA NeMo embeddings issue #16095.

### CODE REVIEW

**Review by baskaryan — COMMENTED** [review]
@nvpranak feel free to ping when it's ready for review!

**Comment by nvpranak** [comment]
@baskaryan Could you please review the code changes?

**Review by baskaryan — COMMENTED** [review]
looks like there's a merge conflict, otherwise code lgtm! would be great to add a docs page to `docs/docs/integrations/text_embedding` section

**Comment by nvpranak** [comment]
@baskaryan 
- I resolved the merge conflict. I had to move the embeddings to ```langchain_community```.
- I added the documentation at ```docs/docs/integrations/text_embedding/nemo.ipnb```
Could you please review these? Thanks.

**Review by baskaryan — COMMENTED** [review]
can we remove the `libs/langchain` code? the models that are re-exported from there are for backwards compatibility, all new code only needs to live in libs/community. we'll be deleting the re-exports from libs/langchain next minor version release

**Comment by nvpranak** [comment]
@baskaryan  Thank you. I did not fully understand but now I do. I made the appropriate changes. could you please check.

**Review by baskaryan — APPROVED** [review]

**Comment by nvpranak** [comment]
@baskaryan Can you please advise on how to fix these failing CI/CD checks? Thanks.

**Pull request merged**
