### PR TITLE
Add async sql record manager and async indexing API

### PR DESCRIPTION
**Pull request by jvelezmagic**
- **Description:** Add support for a SQLRecordManager in async environments. It includes the creation of `RecorManagerAsync` abstract class.
- **Issue:** None
- **Dependencies:** Optional `aiosqlite`.
- **Tag maintainer:** @nfcampos 
- **Twitter handle:** @jvelezmagic

### CODE REVIEW

**Comment by eyurtsev** [comment]
@jvelezmagic thanks for the PR.

The dominant style in langchain is to keep the async and sync variants in the same namespace, with `async` variants receiving an extra `a` as a prefix. i think this should be safe here as well, as long as __ init __ does not cause any side effects, just need to figure out how to initialize conveniently.

Let me know if you're interested in working on this, if not, I'm happy to make the refactor.

Do you have corresponding indexing code for this as well?

**Comment by jvelezmagic** [comment]
Hi, @eyurtsev! OK, I thought something like that might happen. Just to be clear, are you referring to both levels, `RecordManager` and `SQLRecorManager` or just `RecordManager`? I can help with it.

**Comment by eyurtsev** [comment]
@jvelezmagic  Yeah let's do both the abstract interface (RecordManager) as well as the implementation (SQLRecordManager).

For indexing code -- do you have an async variant of this code: https://github.com/langchain-ai/langchain/blob/1b6577990520858b5910adcf11b37b655481916e/libs/langchain/langchain/indexes/_api.py#L166-L166 ?

**Comment by jvelezmagic** [comment]
Ok, let's do it! 

And, yes, I have the async implementation of the indexing too. I'll submit it.

**Comment by jvelezmagic** [comment]
@eyurtsev , I uploaded the requested changes. 

- Added `a` prefix to async variants.
- Single `RecordManager`
- Single `SQLRecordManager`
- `aindex` implementation.

Notes:
- `BaseLoader` would need to implement `alazy_load` or `aload` to be able to work with `aindex`.
- `VectorStore` would need to implement `adelete` to be able to work with 'aindex'.

Let me know what you think!

**Comment by eyurtsev** [comment]
@jvelezmagic Thanks for all your work :) let me know if you want me to make the last few changes so we can merge this code in!

**Comment by jvelezmagic** [comment]
@eyurtsev , thanks! Sure, go ahead with it. Let me know if I can help you with something else.

**Comment by eyurtsev** [comment]
@jvelezmagic let me know if this looks good, if so, I'll resolve poetry conflicts and merge

**Comment by jvelezmagic** [comment]
Hi, @eyurtsev , overall it looks great! Thanks for adding more tests!

I'm a bit puzzled about one aspect and hoped you could help me understand better. Towards the end, are we using the regular `load` and `lazy_load` methods in `BaseLoader` and then converting them to an async iterator shortly after?

If that’s the case, there might be a tiny hitch – the original iterator being synchronous could mean that fetching the next item might still block the event loop, even though the wrapper is asynchronous. Would love your thoughts on this! 🤔

Besides that, I think https://github.com/langchain-ai/langchain/pull/10726#discussion_r1337274418 subclassing could be a good approach to handle different interfaces and avoid runtime errors and unexpected outcomes when dealing with async on applications endpoints. Would love to hear more of it!

**Comment by eyurtsev** [comment]
@jvelezmagic I was thinking to accept a BaseLoader and eventually use an async implementation when it's available, but fall back on the sync for now. A user can leverage the async features by passing an async iterator directly (not a BaseLoader). If this is confusing, we could limit the async versio of the API to accept an async iterator or sync iterator, but not BaseLoader for the time being.

We definitely want to add support for async on the loaders as well, but it's touching the base schema so it's too big of a change for this PR.

**Comment by eyurtsev** [comment]
@jvelezmagic I made the changes above to restrict input types for the async version. I'll merge this in, and we can then focus on the core abstraction document loaders to add async support, and afterwards re-add the support in the async indexing api

**Pull request merged**
