### PR TITLE
community: deprecate ErnieBotChat and ErnieEmbeddings classes

### PR DESCRIPTION
**Pull request by axiangcoding**
- **Description:** add deprecated warning for ErnieBotChat and ErnieEmbeddings. 
    - These two classes **lack maintenance** and do not use the sdk provided by qianfan, which means hard to implement some key feature like streaming. 
    - The alternative `langchain_community.chat_models.QianfanChatEndpoint` and `langchain_community.embeddings.QianfanEmbeddingsEndpoint` can completely replace these two classes, only need to change configuration items.
  - **Issue:** None,
  - **Dependencies:** None,
  - **Twitter handle:** None

### CODE REVIEW

**Comment by leo-gan** [comment]
@axiangcoding It would be nice if the depreciation notes were added to the correspondent examples in the documentation.

**Comment by axiangcoding** [comment]
> @axiangcoding It would be nice if the depreciation notes were added to the correspondent examples in the documentation.

Of course. i will add it later. Thanks

**Comment by axiangcoding** [comment]
@leo-gan Hi, this PR is ready for merge. Please review. Thanks

**Review by leo-gan — APPROVED** [review]
LGTM
Thanks!

**Comment by axiangcoding** [comment]
@baskaryan Please merge this PR, thanks.

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
