### PR TITLE
Add Xorbits Dataframe as a Document Loader

### PR DESCRIPTION
**Pull request by yifeis7**
- [Xorbits](https://doc.xorbits.io/en/latest/) is an open-source computing framework that makes it easy to scale data science and machine learning workloads in parallel. Xorbits can leverage multi cores or GPUs to accelerate computation on a single machine, or scale out up to thousands of machines to support processing terabytes of data.

- This PR added support for the Xorbits document loader, which allows langchain to leverage Xorbits to parallelize and distribute the loading of data. 
- Dependencies: This change requires the Xorbits library to be installed in order to be used.
`pip install xorbits`
- Request for review: @rlancemartin, @eyurtsev
- Twitter handle: https://twitter.com/Xorbitsio

### CODE REVIEW

**Review by rlancemartin — APPROVED** [review]
thanks! lgtm.

**Comment by rlancemartin** [comment]
See Lint error 
```
langchain/document_loaders/xorbits.py:22:89: E501 Line too long (95 > 88 characters)
```

Run `poetry run ruff .` to check locally before pushing.

Also you can run `make format` to fix other formatting errors.

**Comment by yifeis7** [comment]
@rlancemartin
Thanks for your help! Bug fixed.

**Comment by qinxuye** [comment]
This PR is ready for merge, @rlancemartin Could you please merge it?

**Pull request merged**
