### PR TITLE
Seperator should be added at the end of each split

### PR DESCRIPTION
**Pull request by pushpendradahiya**
- **Description:** Seperator should be added at the end of each split,
  - **Issue:** None,
  - **Dependencies:** None,
  - **Twitter handle:** pushpndr

### CODE REVIEW

**Comment by pushpendradahiya** [comment]
EXAMPLE:
text_splitter = RecursiveCharacterTextSplitter(separators=["\. "], chunk_size=10, chunk_overlap = 0)
Input_text = """Madam Speaker, Madam Vice President, our First Lady and Second Gentleman. Members of Congress and the Cabinet. Justices of the Supreme Court. My fellow Americans. Last year COVID-19 kept us apart. This year we are finally together again. Tonight, we meet as Democrats Republicans and Independents. But most importantly as Americans. With a duty to one another to the American people to the Constitution."""
texts = text_splitter.split_text(text)
print(texts)

Earlier implementation Output: 
['Madam Speaker, Madam Vice President, our First Lady and Second Gentleman',
 '. Members of Congress and the Cabinet',
 '. Justices of the Supreme Court',
 '. My fellow Americans',
 '. Last year COVID-19 kept us apart',
 '. This year we are finally together again',
 '. Tonight, we meet as Democrats Republicans and Independents',
 '. But most importantly as Americans',
 '. With a duty to one another to the American people to the Constitution.']


Post changes Output:
['Madam Speaker, Madam Vice President, our First Lady and Second Gentleman. ',
 'Members of Congress and the Cabinet. ',
 'Justices of the Supreme Court. ',
 'My fellow Americans. ',
 'Last year COVID-19 kept us apart. ',
 'This year we are finally together again. ',
 'Tonight, we meet as Democrats Republicans and Independents. ',
 'But most importantly as Americans. ',
 'With a duty to one another to the American people to the Constitution.']

**Review by baskaryan — COMMENTED** [review]
could we add some unit tests?

**Comment by baskaryan** [comment]
@pushpendradahiya were you still working on this?

**Comment by ccurme** [comment]
Closing as this was added in https://github.com/langchain-ai/langchain/pull/21130 via `keep_separator="end"`.

**Pull request closed without merging**
