### PR TITLE
LangChain Community: VectorStores: Azure Cosmos DB Mongo vCore with DiskANN

### PR DESCRIPTION
**Pull request by fatmelon**
# Description
Add a new vector index type `diskann` to Azure Cosmos DB Mongo vCore vector store. Paper of DiskANN can be found here [DiskANN: Fast Accurate Billion-point Nearest Neighbor Search on a Single Node](https://proceedings.neurips.cc/paper_files/paper/2019/file/09853c7fb1d3f8ee67a61b6bf4a7f8e6-Paper.pdf).

## Sample Usage
```python
from pymongo import MongoClient

# INDEX_NAME = "izzy-test-index-2"
# NAMESPACE = "izzy_test_db.izzy_test_collection"
# DB_NAME, COLLECTION_NAME = NAMESPACE.split(".")

client: MongoClient = MongoClient(CONNECTION_STRING)
collection = client[DB_NAME][COLLECTION_NAME]

model_deployment = os.getenv(
    "OPENAI_EMBEDDINGS_DEPLOYMENT", "smart-agent-embedding-ada"
)
model_name = os.getenv("OPENAI_EMBEDDINGS_MODEL_NAME", "text-embedding-ada-002")

vectorstore = AzureCosmosDBVectorSearch.from_documents(
    docs,
    openai_embeddings,
    collection=collection,
    index_name=INDEX_NAME,
)

# Read more about these variables in detail here. https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/vector-search
maxDegree = 40
dimensions = 1536
similarity_algorithm = CosmosDBSimilarityType.COS
kind = CosmosDBVectorSearchType.VECTOR_DISKANN
lBuild = 20

vectorstore.create_index(
            dimensions=dimensions,
            similarity=similarity_algorithm,
            kind=kind ,
            max_degree=maxDegree,
            l_build=lBuild,
        )
```

## Dependencies
No additional dependencies were added

### CODE REVIEW

**Comment by fatmelon** [comment]
@baskaryan could you help review this PR? We have some users waiting for this feature, thanks :)

**Comment by fatmelon** [comment]
@efriis could you help review this PR? We have some users waiting for this feature, thanks :)

**Comment by fatmelon** [comment]
@eyurtsev could you help review this PR? We have some users waiting for this feature, thanks :)

**Comment by fatmelon** [comment]
hi  @ccurme , @vbarda , @hwchase17 could anyone review this PR? We have some users waiting for this feature, thanks :)

**Comment by fatmelon** [comment]
@isahers1 could you review this PR? I @-mention the recommended people, but they didn't come to see it ....

**Comment by fatmelon** [comment]
@baskaryan, @efriis, @eyurtsev, @ccurme, @vbarda, @hwchase17, could you help review this PR? We have some users waiting for this feature, thanks :)

**Comment by aayush3011** [comment]
Friendly ping @baskaryan for a review here.

**Review by efriis — APPROVED** [review]

**Comment by efriis** [comment]
Also, if you're interested in maintaining this integration without us in the loop, we'd love to get an integration package out! Future PRs against langchain would just be {docs updates, as well as registering your package in `libs/packages.yml`, deprecating this community integration in favor of your integration package}

Here's the guide, and if you have questions, feel free to leave them in the comments on those pages so others can see them! https://python.langchain.com/docs/contributing/how_to/integrations/

**Comment by efriis** [comment]
You should reach out to @marlenezw for help getting set up in the https://github.com/langchain-ai/langchain-azure repo if you want to host out of there!

**Comment by marlenezw** [comment]
Yup! @fatmelon let me know if you want to work on this. Happy to help you with the move.

**Pull request merged**
