### PR TITLE
Added RemoveQuotesOutputParser

### PR DESCRIPTION
**Pull request by JacobFV**
feature: #4252

Still need to add tests.

### CODE REVIEW

**Comment by JacobFV** [comment]
Added tests and ready to merge

**Comment by efriis** [comment]
See #4272

**Comment by JacobFV** [comment]
https://github.com/langchain-ai/langchain/pull/4272#issuecomment-1798056650

**Comment by JacobFV** [comment]
https://github.com/langchain-ai/langchain/pull/4272#issuecomment-1798056650

**Pull request closed without merging**
