### PR TITLE
"parse_json_markdown" function improved / fixed.

### PR DESCRIPTION
**Pull request by medram**
# "parse_json_markdown" function improved / fixed.

I've run into an LLm output parsing issue with an agent (type: conversational-react-description), it always raises llm output error/exception with this type of agent.
I couldn't wait for a fix to be released, so I fixed/improved the "parse_json_markdown" function to ensure parsing the json from LLM output, now it's working great for me, and I would like to contribute the fix :D

Note: I'm a Python expert, and I would like to contribute more, is there anyone that can help/guide me to do the testing for more complex contributions (any articles/blogs may help)?

## Before submitting
Thanks in advance :D

## Who can review?
@hwchase17
@vowelparrot

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
lets add a test for this before merging

**Comment by medram** [comment]
I've run a test on my local PC, and it seems that something is wrong with The Poetry configuration,
probably what caused Github testing got failed.

```bash
make test
poetry run pytest --disable-socket --allow-unix-socket tests/unit_tests/

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
  

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
make: *** [Makefile:38: test] Error 1

```

**Comment by hwchase17** [comment]
i added test cases in an attempt to fix this inside parse_json_markdown - can you review? if there are test cases that wont work, please add them! https://github.com/hwchase17/langchain/pull/5371

**Comment by hwchase17** [comment]
should be fixed by https://github.com/hwchase17/langchain/pull/5371

**Comment by schinto** [comment]
Please have a look at the proposed fix in [#5428](https://github.com/hwchase17/langchain/issues/5428)
The regex should be modified to do greedy matching up to the last triple backticks, otherwise if there is a code block included in the answer it stops the match at the start of the code block.

**Pull request closed without merging**
