### PR TITLE
community: add oracle graph class

### PR DESCRIPTION
**Pull request by sh-sho**
Thank you for contributing to LangChain!

- [ ] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [ ] **PR message**: 
    - **Description:** The purpose of this PR is to add the class for using graph in Oracle Database. This class will enable the creation of tables, the creation of graphs, and the execution of queries in Oracle Database.
    - **Twitter:** Sho Obata/@s_sho7777

- [ ] **Add tests and docs**: I have added docs for using the Oracle Graph Class. 

- [ ] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Comment by sh-sho** [comment]
@efriis @eyurtsev 
Could you review this PR? If someone else should handle it, please connect me with them.

**Comment by sh-sho** [comment]
@ccurme @vbarda 
Cloud you check this PR?

**Comment by sh-sho** [comment]
@efriis 
Could you review this pull request?

**Comment by efriis** [comment]
Hey! Here's a link to the review policy: https://python.langchain.com/docs/contributing/review_process/

Status is currently needs support

**Review by Undertone0809 — APPROVED** [review]
The add_graph_documents method is quite long. Consider breaking it down into smaller, more focused methods for better readability and maintainability.

**Comment by sh-sho** [comment]
Thanks for the comments and links!
I will shorten add_graph_documents and improve its readability and maintainability. I will commit it again.

**Comment by efriis** [comment]
Marking as stale and still in need of support, per the [review process](https://python.langchain.com/docs/contributing/reference/review_process/)

**Comment by efriis** [comment]
Hey! This adds a community integration, which is no longer recommended. Would you be interested in publishing your own integration package, and contributing docs via this guide? https://python.langchain.com/docs/contributing/how_to/integrations/

If you work at oracle, I believe there is an internal effort to do this if you're interested in contributing it there!

**Pull request closed without merging**
