### PR TITLE
Fixed adding float values into DynamoDB

### PR DESCRIPTION
**Pull request by VpkPrasanna**
Thank you for contributing to LangChain!

- [x] **PR title**: Add float Message into Dynamo DB
  -  community
  - Example: "community: Chat Message History 

- [x] **PR message**: 
    - **Description:** pushing float values into dynamo db creates error , solved that by converting to str type
    - **Issue:** Float values are not getting pushed
    - **Twitter handle:** VpkPrasanna
    
    
    Have added an utility function for str conversion , let me know where to place it happy to do an commit.
    
    This PR is from an discussion of #26543
    
    @hwchase17 @baskaryan @efriis

### CODE REVIEW

**Review by Undertone0809 — CHANGES_REQUESTED** [review]
image

Need to format the code.

If you have any questions, feel free to ask.

**Comment by VpkPrasanna** [comment]
> image
> 
> Need to format the code.
> 
> If you have any questions, feel free to ask.

How to verify it locally before i push ? and one more thing the issues shows only formatting but is there any other changes do i need to add because i have added an utility function to fix the issue and it is in the same file do i need to place it in other location or it is fine ?

**Comment by VpkPrasanna** [comment]
hi @Undertone0809 i have fixed the issue , can you review it again ?

**Comment by salisbbn** [comment]
Hi @VpkPrasanna  / @Undertone0809 -- my team is also affected by this issue. Any update here regarding merging this fix in?

**Comment by VpkPrasanna** [comment]
> Hi @VpkPrasanna / @Undertone0809 -- my team is also affected by this issue. Any update here regarding merging this fix in?

There is no response / update from the maaintainers

**Review by efriis — COMMENTED** [review]
hey there! sorry for the delay. Could we gate this behind an optional constructor variable to `coerce_float_to_decimal`? I don't love the `Decimal(str(item))` bit, but it's ok if it's off by default, and folks can enable it!

Also, if you're interested in maintaining this integration without us in the loop, we'd love to get an integration package out! Future PRs against langchain would just be {docs updates, as well as registering your package in `libs/packages.yml`, deprecating this community integration in favor of your integration package}

Here's the guide, and if you have questions, feel free to leave them in the comments on those pages so others can see them! https://python.langchain.com/docs/contributing/how_to/integrations/

Would likely be managed out of the `langchain-ai/langchain-aws` repo

**Comment by salisbbn** [comment]
When saving floating point values, boto3+DynamoDB doesn't support the `float` type at all though (only `Decimal` types, and will throw otherwise). So, hiding this behind an optional flag only serves to keep the current, errant behavior in place. Is there a good reason for that? 

I was also thinking about the `str` conversion as well, but then I realized it's likely there to prevent floating-point precision errors.

**Comment by efriis** [comment]
for the same reason that aws doesn't add this conversion to their sdks - it's unexpected behavior for people to store `float` datatypes, and when you retrieve them, they're `Decimal` types

I agree this is useful, so I think gating behind an attribute is good. And in the event Dynamo adds this feature to their sdk or service, it won't be a breaking change for folks to turn this off!

**Review by ccurme — APPROVED** [review]

**Comment by ccurme** [comment]
Gated behind a `coerce_float_to_decimal` parameter with default False for now. Suggest adding to [docs](https://python.langchain.com/docs/integrations/memory/aws_dynamodb/) to assist discoverability.

**Comment by VpkPrasanna** [comment]
Thank you @ccurme for merging the PR finally

**Comment by salisbbn** [comment]
Hi @VpkPrasanna -- have you been using this implementation? When I try to use it, I'm able to have the float values coerced and saved to DDB, but when the messages are subsequently queried from DDB and sent as message history to Bedrock, the Bedrock services throws the following error:

`Invalid type for parameter type: <class 'decimal.Decimal'>, valid types: <class 'str'>, <class 'int'>, <class 'bool'>, <class 'float'>, <class 'list'>, <class 'dict'>`

I think for this feature to be helpful, the `coerce_float_to_decimal` flag (or another flag) will also need to coercing Decimal values back to float values when messages are retrieved. What do you think?

**Comment by MatheusRDG** [comment]
@salisbbn same here, you found any solution?

**Comment by salisbbn** [comment]
Sorry, no, we stopped using Langchain and rolled our own lightweight orchestrator.

**Pull request merged**
