### PR TITLE
Add support for load_chat_model

### PR DESCRIPTION
**Pull request by shivamMg**
- Description:
  - Add `load_chat_model()` and `load_chat_model_from_config()` in `langchain.chat_model.loading` module
  - Update `_load_llm_chain()` to use the above functions in case of LLMs that are Chat Models
  - Fix warning while loading `AzureChatOpenAI` and `ChatOpenAI`: WARNING! engine is not default parameter.
  - **TODO**: I'll add/update unit tests once I get a go-ahead from maintainers for these new additions.
- Issue:
  - https://github.com/langchain-ai/langchain/issues/2627
  - Related PR that was closed: https://github.com/langchain-ai/langchain/pull/1715
- Dependencies: None
- Tag maintainer: @baskaryan
- Twitter handle: None

### CODE REVIEW

**Comment by shivamMg** [comment]
@nfcampos @hwchase17 Would love to hear your thoughts. Even if we're not inclined to support it the way I've implemented it here.

**Comment by nfcampos** [comment]
@shivamMg Hi, we're moving to a new serialization format, see https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/load/serializable.py so the previous serialisation methods you're extending here are deprecated

**Comment by hwchase17** [comment]
@needuv for OpenAI and AzureOpenAI its already supported!

```
from langchain.load.dump import dumps
from langchain.load.load import loads

loads(dumps(model))
```

**Comment by needuv** [comment]
@hwchase17, I noticed this serialization pattern isn't supported for chains. Specifically, I tried this on `RetrievalQA`, and when I deserialized the object using `loads`, it claims serialization/deserialization is not supported for this object type. Is this in your plans to support?

**Comment by needuv** [comment]
@hwchase17/@nfcampos, just want to know if the above will be supported?

**Comment by kyutcho** [comment]
@needuv did you find a workaround for this problem? I am trying to load `RetrievalQA` but still not working :(

**Comment by danilopeixoto** [comment]
I cannot load chains with llms from `langchain.chat_models` module exported by MLflow.  Is it possible to load llms from `chat_models` module?

I'm wondering if [libs/langchain/langchain/llms/loading.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/llms/loading.py) should also take `chat_models` into account.

**Pull request closed without merging**
