### PR TITLE
Fix for the broken Upsert method of Milvus class under VectorStores

### PR DESCRIPTION
**Pull request by dmjdarshan**
- [x] **PR title**: "community: Fix to broken upsert method of milvus vectorstore"

- [x] **PR message**: *
    - **Description:** The Upsert method of the Milvus class was calling the add_documents method of the Base class, which called add_texts abstract method in the Base class itself. Instead it was supposed to call the implemented add_texts class in the Milvus class. This has been fixed by overriding the add_documents class in the Milvus claas
    - **Issue:** the issue #19496 discussed has been fixed in this PR
    - **Dependencies:** None
    - **Twitter handle:** @dmjdarshan

### CODE REVIEW

**Review by baskaryan — COMMENTED** [review]
sorry not sure i understand, isn't this identical to the base VectorStore implementation?

**Comment by dmjdarshan** [comment]
The issue is with the flow of control inside Upsert class.
So the Upsert method in the milvus class has a call to add_documents method of the base class.

```python
try:
            return self.add_documents(documents=documents, **kwargs)
        except MilvusException as exc:
            logger.error(
                "Failed to upsert entities: %s error: %s", self.collection_name, exc
            )
            raise exc

```
The add_documents method of the Base class inturn calls add_texts method of the Base class

add_documents method of Base class:
```python
return self.add_texts(texts, metadatas, **kwargs)
```

This call to add_texts in Base class has not implementation. It is an Abstract class - 

```python
@abstractmethod
    def add_texts(
        self,
        texts: Iterable[str],
        metadatas: Optional[List[dict]] = None,
        **kwargs: Any,
    ) -> List[str]:
        """Run more texts through the embeddings and add to the vectorstore.

        Args:
            texts: Iterable of strings to add to the vectorstore.
            metadatas: Optional list of metadatas associated with the texts.
            kwargs: vectorstore specific parameters

        Returns:
            List of ids from adding the texts into the vectorstore.
        """
```

The implementation of this add_texts method has been done in the Mivus class itself. So the mistake in the flow is - 
Upsert class should have called the add_documents method of the Mivus class itself. But there wasnt overridden method of add_documents in the Milvus class. Hence I added the overriding method for add_documents


Before the Flow was - 
Upsert(Milvus) -> add_documents(Base) -> add_texts(Base : Which is not implemented)

Post the addition of method
Upsert(Milvus) -> add_documents(Milvus) -> add_texts(Base)

**Comment by dmjdarshan** [comment]
@hwchase17 @baskaryan @efriis

**Comment by zc277584121** [comment]
Sorry, there seems to be a problem with the Before the Flow
Upsert(Milvus) -> add_documents(Base) -> add_texts(Milvus: actually invoke subclass's add_texts method)
Is there any problem with the upsert method,  Could you please run this unit test to doublecheck it, https://github.com/langchain-ai/langchain/blob/30f1bf24ac5f62b17dd71bc341fd3dfadd03893f/libs/partners/milvus/tests/integration_tests/vectorstores/test_milvus.py#L187

BTW, new contribution should be placed into the libs/partner/milvus/langchain_milvus package

**Comment by efriis** [comment]
closing - feel free to reopen against the milvus partner package!

**Pull request closed without merging**
