### PR TITLE
docs: updated `YouTube` and `tutorial` video links

### PR DESCRIPTION
**Pull request by leo-gan**
updated `YouTube` and `tutorial` videos with new links.
Removed couple of duplicates.
Reordered several links by view counters
Some formatting: emphasized the names of products

### CODE REVIEW

**Comment by leo-gan** [comment]
@baskaryan Could you, please, review it?

**Comment by leo-gan** [comment]
@hwchase17  Could you, please, review it?

**Comment by leo-gan** [comment]
@eyurtsev Could you, please review the [outdated PRs](https://github.com/langchain-ai/langchain/pulls/leo-gan)?
Please, let me know if you don't need them and I close them.

**Comment by leo-gan** [comment]
@baskaryan Could you, please, review it?

**Review by hwchase17 — APPROVED** [review]
thanks

**Pull request merged**
