### PR TITLE
Replace self-built devcontainer with default python image

### PR DESCRIPTION
**Pull request by neo**
This replaces the custom docker image for devcontainer with the official python one with the `poetry` feature and `black-formatter` extension added, because:
- The current one is broken during building when opening in codespaces. I tried a few times and it errors out during poetry install colored for some reasons.
- It's faster to build and load when opening in codespaces.
- It's easier to maintain as it's composed from existing things pre-built by others.

#### Who can review?

Tag maintainers/contributors who might be interested:  - @vowelparrot

### CODE REVIEW

**Comment by leo-gan** [comment]
@neo Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by neo** [comment]
Hey Leo!

I'd love to do that, but I think it depends on the team's preference between a custom dockerfile image (the current way) and a more managed solution (the purposed way) because I feel the team seems pretty committed to the custom image.

From my understanding the managed image might be faster whereas the custom image can be utilized in other environments including local development to provide a consistent environment.

**Comment by neo** [comment]
Just to confirm, I guess the team decided to go with the custom image way?

**Comment by leo-gan** [comment]
cc @eyurtsev

**Pull request closed without merging**
