### PR TITLE
added redis method to delete entries by keys

### PR DESCRIPTION
**Pull request by ChrKahl**
In addition to my last pr (return keys of added entries), we also need a method to delete the entries by keys.

@dev2049

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
shouldnt this delete keys from the vectorstore that the wrapper is initialized with?

**Comment by rlancemartin** [comment]
Thanks for contributing! Do you also mind updating the redis example notebook to show usage of delete records by ID? (Semi-related: if easy, it would be helpful to explain how to create / connect to redis cloud or local DB in the notebook. Notebook currently only mentioned connection via url, but doesn't add much context about setting up the DB itself.)

https://github.com/hwchase17/langchain/blob/master/docs/extras/modules/data_connection/vectorstores/integrations/redis.ipynb

**Comment by ChrKahl** [comment]
> Thanks for contributing! Do you also mind updating the redis example notebook to show usage of delete records by ID? (Semi-related: if easy, it would be helpful to explain how to create / connect to redis cloud or local DB in the notebook. Notebook currently only mentioned connection via url, but doesn't add much context about setting up the DB itself.)
> 
> https://github.com/hwchase17/langchain/blob/master/docs/extras/modules/data_connection/vectorstores/integrations/redis.ipynb

I've added an example of the deletion of entries and how to create an instance with the classmethod `from_texts_return_keys` to get the keys while creating the instance itself.

To be honest I think it shouldn't be part of the notebook to explain how to setup the DB itself..

**Comment by rlancemartin** [comment]
> @rlancemartin 
> 
> > Thanks for contributing! Do you also mind updating the redis example notebook to show usage of delete records by ID? (Semi-related: if easy, it would be helpful to explain how to create / connect to redis cloud or local DB in the notebook. Notebook currently only mentioned connection via url, but doesn't add much context about setting up the DB itself.)
> 
> > 
> 
> > https://github.com/hwchase17/langchain/blob/master/docs/extras/modules/data_connection/vectorstores/integrations/redis.ipynb
> 
> 
> 
> I've added an example of the deletion of entries and how to create an instance with the classmethod `from_texts_return_keys` to get the keys while creating the instance itself.
> 
> 
> 
> To be honest I think it shouldn't be part of the notebook to explain how to setup the DB itself..

Great!

Notebook should give context on the redis_url. (Is this a local instance? How to context to a cloud hosted DB? Etc.) Many of the other DBs provide that. See the Elastic documentation for example. But of course it's not on you to add it and is unrelated to this PR, so of course no worries if you do not want to do it. We can get this PR merged without it obviously.

**Comment by rlancemartin** [comment]
@ChrKahl I merged this, and made some small changes in a follow-up (adding `delete` to several vectorDB).

Please have a quick look to ensure you are OK with the changes:

https://github.com/hwchase17/langchain/pull/6126

**Pull request merged**
