### PR TITLE
Update Poetry version, to current latest (1.8.4)

### PR DESCRIPTION
**Pull request by ulgens**
Update all Poetry versions to the current latest, 1.8.4 .

I was checking how lock files are managed and found out that even though the files are generated - updated with the current latest version of Poetry, the version used in CI and Dockerfile was outdated.

* https://github.com/langchain-ai/langchain/pull/28061/files#diff-e00422d37a73d07c174e7838ad7c30f642d06305aff8f9d71e1e84c6897efbffL1
* https://github.com/langchain-ai/langchain/pull/28070/files#diff-55267c883e58892916d5316bc029725fdeeba5a77e2557cf7667793823d9d9c6L1
* https://github.com/langchain-ai/langchain/pull/27991/files#diff-9f96b8fd39133c3f1d737e013c9042b065b42ae04b3da76902304f30cec136d8R1

### CODE REVIEW

**Comment by efriis** [comment]
was this creating issues? in general we don't update these versions for each release, because in CI `poetry` is just used for installing from lockfiles.

**Comment by ulgens** [comment]
@efriis I wasn't going for a fix, this was more of a maintenance task. As far as I understood, CI config has been neglected for a while. It's expected to install those lock files with the version that locked them because the file format changes by the versions and using the latest comes with performance issues.

I wouldn't push for updating the config with every patch release of the tools, but I think it's good to merge this PR for mainly two reasons:
* Having consistency across pipelines
* The oldest version that currently being used was released almost 2 years ago and poetry released 14 versions after that

**Comment by ulgens** [comment]
Hey again, I came up with another pro argument for this exact version.

https://github.com/python-poetry/poetry/releases/tag/1.8.4

Poetry validates Python 3.13 support with version 1.8.4, so any version older than that is not officially compatible with Python 3.13. Considering there are not many blockers for langchain's 3.13 support, 3.13 support at poetry level is a nice thing to have.

**Comment by efriis** [comment]
sounds good! will probably wait to merge this until after thanksgiving because I'm ooo next week, and we've had some unexpected issues pop up in the past with other CI pipelines that get impacted by poetry upgrades

**Review by efriis — APPROVED** [review]

**Comment by ulgens** [comment]
@efriis Thanks for the approval. I rebased the branch and solved the conflicts, it should be ready to merge now.

**Comment by efriis** [comment]
sounds good thanks!

**Pull request merged**
