### PR TITLE
langchain: Add PebbloRetrievalQA chain with Identity & Semantic Enforcement support

### PR DESCRIPTION
**Pull request by Raj725**
- **Description:** PebbloRetrievalQA chain introduces identity enforcement using vector-db metadata filtering
- **Dependencies:** None
- **Issue:** None
- **Documentation:** Added documentation for PebbloRetrievalQA chain
- **Unit tests:** New unit-tests added 
- **Twitter handle:** @Raj__725

### CODE REVIEW

**Comment by Raj725** [comment]
cc: @eyurtsev

**Comment by Raj725** [comment]
cc: @baskaryan

**Comment by sridhar-daxa** [comment]
@efriis Pls help to review this. @Raj725 moved the PR https://github.com/langchain-ai/langchain/pull/18812 to take it forward.

**Comment by srics** [comment]
@efriis Pls help to review this. This is the clone of PR https://github.com/langchain-ai/langchain/pull/18812 which @Raj725 will help to take it forward, thanks!

**Pull request closed without merging**
