### PR TITLE
docs: update baidu_qianfan_endpoint.ipynb doc 

### PR DESCRIPTION
**Pull request by Bigtable123**
- **Description:** Updated the docs for the chat integration module baidu_qianfan_endpoint.ipynb
  - **Issue:**  #15664 
  - **Dependencies:**N/A

### CODE REVIEW

**Comment by Bigtable123** [comment]
The stream mode of the baichuan model has a bug where it automatically adds the sentence_id when it returns, which may require modifying the source code of this model, I used a try-catch block to skip this Type error and it works fine.

**Comment by Bigtable123** [comment]
For the other model, baichuan, it is more problematic. Baichuan has updated their API and its usage rules, now they don't use the secret key anymore and the API base and usage rules have completely changed, the baichuan model code [libs/community/langchain_community/chat_models/baichuan.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/chat_models/baichuan.py) in the langchain community is completely outdated. It is not possible to update the doc for the baichuan model at this monment.

**Review by hwchase17 — COMMENTED** [review]
there is a stray file checked in. otherwise, lgtm

**Comment by Bigtable123** [comment]
I've removed that file.

**Comment by Bigtable123** [comment]
I uploaded some changes by mistake, I have reverted it.

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
