### PR TITLE
Add read only shared memory

### PR DESCRIPTION
**Pull request by yakigac**
Provide shared memory capability for the Agent.
Inspired by #1293 .

## Problem

If both Agent and Tools (i.e., LLMChain) use the same memory, both of them will save the context. It can be annoying in some cases.

## Solution

Create a memory wrapper that ignores the save and clear, thereby preventing updates from Agent or Tools.

### CODE REVIEW

**Comment by hwchase17** [comment]
oh interesting - i like it!. would be very helpful to have an example notebook for this. would you mind adding one? probably in docs/modules/agents/examples

**Comment by yakigac** [comment]
thanks! I'll add an example within this week.

**Comment by yakigac** [comment]
@hwchase17 I added an example. Could you review it?

**Review by hwchase17 — APPROVED** [review]
this is great!!! will merge in and release

**Comment by yakigac** [comment]
@hwchase17 Thanks!
Could you please let me know where you obtained my name and Twitter account information so that I can ensure it is properly referenced? I'd  like to prefer to be referred to as twitter.com/yakigac for the next tweet.

**Pull request merged**
