### PR TITLE
docs[patch]: Update OllamaFunctions docs to match chat model integration template

### PR DESCRIPTION
**Pull request by lalanikarim**
Added Tool Calling Agent Example with langgraph to OllamaFunctions documentation

### CODE REVIEW

**Comment by lalanikarim** [comment]
@baskaryan @ccurme can I get feedback on this PR please?

Thanks

**Comment by lalanikarim** [comment]
@efriis @baskaryan @ccurme 
Can I please get a review on this? 
Thanks

**Comment by lalanikarim** [comment]
@baskaryan @efriis @ccurme @hwchase17 
Can I please get feedback on this PR? TIA

**Comment by lalanikarim** [comment]
@baskaryan @efriis @ccurme @hwchase17
Can I please get feedback on this PR? TIA

**Comment by lalanikarim** [comment]
cc @jacoblee93

**Comment by jacoblee93** [comment]
Hey @lalanikarim! Thanks for this PR!

We're trying to keep the integration pages free of super detailed cookbook examples - adding the table is great as is showing off `.bind_tools()`, but it'd be better to just link to the how-to guide on tool calling/output formats in general.

Similarly, the LangGraph guide is also really great, but would be better as a cookbook rather than in the main integrations page:

https://github.com/langchain-ai/langgraph/tree/main/examples

You could then link to the cookbook in the docs page. Does that sound ok? I'd be happy to help reformat things.

CC @baskaryan

**Comment by lalanikarim** [comment]
> Hey @lalanikarim! Thanks for this PR!
> 
> We're trying to keep the integration pages free of super detailed cookbook examples - adding the table is great as is showing off `.bind_tools()`, but it'd be better to just link to the how-to guide on tool calling/output formats in general.
> 
> Similarly, the LangGraph guide is also really great, but would be better as a cookbook rather than in the main integrations page:
> 
> https://github.com/langchain-ai/langgraph/tree/main/examples
> 
> You could then link to the cookbook in the docs page. Does that sound ok? I'd be happy to help reformat things.
> 
> CC @baskaryan

Thanks for the feedback @jacoblee93 
I have removed the examples from the notebook per your recommendation. I'll submit a separate PRs for example notebooks.

Please let me know if any further adjustments are needed on this PR.

**Comment by jacoblee93** [comment]
Thank you!

**Pull request merged**
