### PR TITLE
Adding ChatLiteLLM model

### PR DESCRIPTION
**Pull request by ghost**
Description: Adding a langchain integration for the LiteLLM library 
Tag maintainer: @hwchase17, @baskaryan
Twitter handle: @krrish_dh / @Berri_AI

### CODE REVIEW

**Comment by baskaryan** [comment]
fixed some lint issues in #9098 if you wanna merge that in here

**Comment by krrishdholakia** [comment]
done @baskaryan any remaining blockers?

**Comment by krrishdholakia** [comment]
@baskaryan done - let me know if there's anything else needed on my end

**Comment by baskaryan** [comment]
oh the only other thing is it'd be great to add some documentation! can add a notebook to docs/extras/integrations/chat_models/...

**Comment by krrishdholakia** [comment]
Ok sounds good - I'll make a doc

**Comment by krrishdholakia** [comment]
Hey @baskaryan just added a tutorial

**Comment by baskaryan** [comment]
looks awesome, thanks @krrishdholakia!

**Pull request merged**
