### PR TITLE
refactor `community` memory

### PR DESCRIPTION
**Pull request by leo-gan**
- created `language_community.memory`
- moved zep and motorhed from `langchain.memory` to `language_community.memory`
- created `language_core.memory`
- moved several base classes into `language_core.memory`
- moved `ChatMessageHistory` from `langchain_community` to `langchain_core`

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
we specifically did not put these memory classes in core, we dont think they are production ready

**Comment by leo-gan** [comment]
> we specifically did not put these memory classes in core, we dont think they are production ready

Oh... Is it OK to move classes only to community?

**Comment by hwchase17** [comment]
> > we specifically did not put these memory classes in core, we dont think they are production ready
> 
> Oh... Is it OK to move classes only to community?

community is more for third party integrations

We will likely mark these as deprecated in 0.1, and then remove in 0.2

**Comment by leo-gan** [comment]
> > > we specifically did not put these memory classes in core, we dont think they are production ready
> > 
> > 
> > Oh... Is it OK to move classes only to community?
> 
> community is more for third party integrations
> 
> We will likely mark these as deprecated in 0.1, and then remove in 0.2

@hwchase17  I mean the `zep` and `motorhed`. They are the third party integrations. Can I move them to `community`?

**Comment by leo-gan** [comment]
I'll redo it only for `community` classes

**Pull request closed without merging**
