### PR TITLE
Cassandra Vector Store, add metadata filtering + improvements

### PR DESCRIPTION
**Pull request by hemidactylus**
This PR addresses a few minor issues with the Cassandra vector store implementation and extends the store to support Metadata search.

Thanks to the latest cassIO library (>=0.1.0), metadata filtering is available in the store.

Further,
- the "relevance" score is prevented from being flipped in the [0,1] interval, thus ensuring that 1 corresponds to the closest vector (this is related to how the underlying cassIO class returns the cosine difference);
- bumped the cassIO package version both in the notebooks and the pyproject.toml;
- adjusted the textfile location for the vector-store example after the reshuffling of the Langchain repo dir structure;
- added demonstration of metadata filtering in the Cassandra vector store notebook;
- better docstring for the Cassandra vector store class;
- fixed test flakiness and removed offending out-of-place escape chars from a test module docstring;

To my knowledge all relevant tests pass and mypy+black+ruff don't complain. (mypy gives unrelated errors in other modules, which clearly don't depend on the content of this PR).

Thank you!
Stefano

### CODE REVIEW

**Comment by hemidactylus** [comment]
Hello, @baskaryan , is there anything I can do to resolve the conflicts above? (which, I believe, appeared after I submitted the PR as master has been evolving meanwhile)

**Comment by prabhatjha** [comment]
Hello -- I would like to try this with Cassandra with the mainline langchain. Can you pls help expedite the approval process?

**Comment by hemidactylus** [comment]
Hello @baskaryan , may I ask you to check this PR, please? That would help us a lot.

**Comment by prabhatjha** [comment]
Hi peeps -- any ETA on when this PR can be merged?

**Pull request merged**
