### PR TITLE
Added custom retry decorator support in ChatOpenAI

### PR DESCRIPTION
**Pull request by rohan-uiuc**
Description: 
This PR adds the ability for users to provide a custom retry decorator when creating an instance of the ChatOpenAI class. The custom decorator will be used in the acompletion_with_retry and completion_with_retry methods to handle retries for the API calls. If a custom decorator is not provided, the default retry decorator will be used. This feature provides users the flexibility to handle specific use cases and errors in specific ways.

Issue: https://github.com/langchain-ai/langchain/issues/3109

Dependencies: No new dependencies are required for this change.

### CODE REVIEW

**Comment by eyurtsev** [comment]
@rohan-uiuc All LLMs are instances of runnables and expose a [with_retry method](https://github.com/langchain-ai/langchain/blob/ffe6a449e055d54c10c6a29ba98137ec95f531fa/libs/langchain/langchain/schema/runnable/base.py#L431-L431).  Would using that method work for your usecase?

**Comment by rohan-uiuc** [comment]
@eyurtsev thanks for a quick reply. My use case is running autonomous agents and I usually run into RateLimitError. It will be helpful to add support for infinite retries with exponential backoff ONLY if the error is RateLimitError. We do have stop_after_attempt arg where we could add a large number, but  there must be other scenarios where users want a custom retry mechanism on specific exceptions so it might be useful to add another argument in [RunnableRetry](https://github.com/langchain-ai/langchain/blob/ffe6a449e055d54c10c6a29ba98137ec95f531fa/libs/langchain/langchain/schema/runnable/retry.py#L37)  which can be used to set `kwargs["stop"] = stop_never` or exposing the `retry_decorator` as an argument. 

 Please let me know if you think this will help or if there is a better way to handle this and I will be happy to update my PR.

**Comment by eyurtsev** [comment]
Hi @rohan-uiuc

Try the following:

1) set max_retries to 0 on the llm, so there's no retrying logic on the llm itself
2) use the with_retry wrapper and set the number of attempts to some large integer (100_000) You may be able to pass math.inf, but depends on what tenacity allows (the function signature is for an int).

**Comment by eyurtsev** [comment]
@rohan-uiuc let me know if that works for your use case or if / why it fails for your use case. 

The considerations:

1)  we'd rather built in more functionality into RunnableRetrys so functionality can be rolled out to all LangChain objects at once rather than one particular LLM
2) we want to make sure that it's possible to trace all the retries for monitoring purposes

**Comment by rohan-uiuc** [comment]
@eyurtsev I agree that we should build the functionality into RunnableRetry.

Tenacity exposes `stop_never` as a `StopBaseT` type. Would it be possible to expose this in [RunnableRetry](https://github.com/langchain-ai/langchain/blob/ffe6a449e055d54c10c6a29ba98137ec95f531fa/libs/langchain/langchain/schema/runnable/retry.py#L37)
in the following way?

```
class RunnableRetry(RunnableBinding[Input, Output]):
    """Retry a Runnable if it fails."""

    retry_exception_types: Tuple[Type[BaseException], ...] = (Exception,)
    wait_exponential_jitter: bool = True
    max_attempt_number: int = 3
    stop: Optional[StopBaseT] = None

    @property
    def _kwargs_retrying(self) -> Dict[str, Any]:
        kwargs: Dict[str, Any] = dict()

        if self.stop:
            kwargs["stop"] = self.stop
        elif self.max_attempt_number:
            kwargs["stop"] = stop_after_attempt(self.max_attempt_number)

        if self.wait_exponential_jitter:
            kwargs["wait"] = wait_exponential_jitter()

        if self.retry_exception_types:
            kwargs["retry"] = retry_if_exception_type(self.retry_exception_types)

        return kwargs
```
This will provide more flexibility to use all the stop mechanisms available in [stop_base](https://github.com/jd/tenacity/blob/310058274ed22a345e9c3917c97b4afd6363d5a5/tenacity/stop.py#L27C7-L27C16) from tenacity.

**Comment by rohan-uiuc** [comment]
Hi @eyurtsev , I am facing the same issue as https://github.com/langchain-ai/langchain/issues/2922#issuecomment-1727457196 when trying to run with the approach you mentioned. For testing the use case can be as simple as this comment or you can refer to mine.

```
class WorkflowAgent:
    def __init__(self):
        self.llm: ChatOpenAI = ChatOpenAI(temperature=0, model="gpt-4-0613", request_timeout=60 * 3).with_retry(retry_if_exception_type=(openai.error.OpenAIError,), stop_after_attempt=1000, wait_exponential_jitter=True)  # type: ignore
        self.agent = self.make_agent()

    def run(self, input):
        result = self.agent.run(input)

        print(f"Result: {result}")
        return result

    def make_agent(self): 

        # TOOLS
        tools = get_tools(self.llm, sync=True)

        # PLANNER
        planner = load_chat_planner(self.llm, system_prompt=PLANNER_PROMPT)

        # EXECUTOR
        executor = load_agent_executor(self.llm, tools, verbose=True)

        # Create PlanAndExecute Agent
        workflow_agent = PlanAndExecute(planner=planner, executor=executor, verbose=True)


        return workflow_agent
 ```
 
 Error:
 ```
 Error: 1 validation error for LLMChain
llm
  Can't instantiate abstract class BaseLanguageModel with abstract methods agenerate_prompt, apredict, apredict_messages, generate_prompt, invoke, predict, predict_messages (type=type_error)
```

**Comment by eyurtsev** [comment]
@rohan-uiuc will take a look tomorrow, likely something is validating and requiring an LLM, and not accepting a runnable

**Comment by eyurtsev** [comment]
Hi @rohan-uiuc,

The code is using pydantic to do validation and one of the segments seems to instantiate LLMPlanner which expectes an LLMChain.

```
      # PLANNER
        planner = load_chat_planner(self.llm, system_prompt=PLANNER_PROMPT)
```

The best solution is to re-write the corresponding code using LCEL (it's likely simpler than you expect).

The planner is just an llm chain followed by a parser: 

```
    def plan(self, inputs: dict, callbacks: Callbacks = None, **kwargs: Any) -> Plan:
        """Given input, decide what to do."""
        llm_response = self.llm_chain.run(**inputs, stop=self.stop, callbacks=callbacks)
        return self.output_parser.parse(llm_response)
```

The equivalent of that in LCEL is: https://python.langchain.com/docs/expression_language/cookbook/prompt_llm_parser#prompttemplate--llm--outputparser

provide the parser, llm and prompt you need and chain them:

image

**Comment by baskaryan** [comment]
Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

**Comment by eyurtsev** [comment]
Going to close this PR for now due to lack of activity

**Pull request closed without merging**
