### PR TITLE
Adding Marqo to vectorstore ecosystem

### PR DESCRIPTION
**Pull request by tomhamer**
This PR brings in a vectorstore interface for [Marqo](https://www.marqo.ai/).

The Marqo vectorstore exposes some of Marqo's functionality in addition the the VectorStore base class. The Marqo vectorstore also makes the embedding parameter optional because inference for embeddings is an inherent part of Marqo.

Docs, notebook examples and integration tests included.

Related PR:
https://github.com/hwchase17/langchain/pull/2807

### CODE REVIEW

**Comment by tomhamer** [comment]
For now, I've moved this across to a new PR as the harrison/marqo branch needs substantial merging and can't automatically merged across. Do you prefer me to create a new PR to harrison/marqo?

**Comment by tomhamer** [comment]
@baskaryan I've fixed the poetry issue - can we rerun the check? Thanks a lot

**Comment by tomhamer** [comment]
@baskaryan @rlancemartin everything looks to be passing now. Let me know if there is anything more to be done on this, happy to do whatever is needed to get this across the line. Thanks so much!

**Comment by rlancemartin** [comment]
> @baskaryan @rlancemartin everything looks to be passing now. Let me know if there is anything more to be done on this, happy to do whatever is needed to get this across the line. Thanks so much! 

Great. Just kicked off tests and will merge once we confirm all pass.

**Comment by rlancemartin** [comment]
> > @baskaryan @rlancemartin everything looks to be passing now. Let me know if there is anything more to be done on this, happy to do whatever is needed to get this across the line. Thanks so much! 
> 
> Great. Just kicked off tests and will merge once we confirm all pass.

Please run "make format" to resolve Lint errors.

**Comment by tomhamer** [comment]
@rlancemartin sorry about that - completed now

**Comment by rlancemartin** [comment]
> @rlancemartin sorry about that - completed now

np! looks like an issue w/ `poetry.lock`?

```
Error: poetry.lock is not consistent with pyproject.toml. Run `poetry lock [--no-update]` to fix it.
```

try this:
```
git checkout master poetry.lock
poetry lock --no-update
```

gets the latest `poetry.lock` and updates it w/ your `pyproject.toml`.

**Review by hwchase17 — APPROVED** [review]
lgtm! thanks

**Comment by tomhamer** [comment]
Thanks for the help @hwchase17! I was just getting that fixed up but you're right ahead of me. Super impressive how helpful you've been.

**Comment by rlancemartin** [comment]
> Thanks for the help @hwchase17! I was just getting that fixed up but you're right ahead of me. Super impressive how helpful you've been.

A number of Lint errors [due to line length](https://github.com/hwchase17/langchain/actions/runs/5468243615/jobs/9955608505?pr=7068). One of us can take this if you don't have time to do it soon. We'll plan to get this merged today.

**Comment by tomhamer** [comment]
working on it now

**Comment by tomhamer** [comment]
`poetry run ruff .` now passing. @rlancemartin did you want to try triggering the workflow again? really appreciate it

**Comment by tomhamer** [comment]
sorry one moment, ive accidentally added some unneeded lock file changes

**Comment by tomhamer** [comment]
Done, should be good to go

**Comment by tomhamer** [comment]
Looks like I didnt lint the file in the correct way, going to try again with Black

**Comment by tomhamer** [comment]
@rlancemartin thanks so much for your help! Looks like everything passed 🎉

**Pull request merged**
