### PR TITLE
standardise metadata_field handling

### PR DESCRIPTION
**Pull request by anderson2805**
- **Description:** updated func max_marginal_relevance_search handling of metadata_field to be same as similarity_search_with_score. Allow flatten Opensearch mapping, where meta fields are not nested into any field.
 - **Issue:** #10524
 - **Maintainer:** @hwchase17, @baskaryan

### CODE REVIEW

**Comment by anderson2805** [comment]
[dosubot](https://github.com/apps/dosubot) Any issue with this commit?

**Comment by anderson2805** [comment]
@dosubot

**Comment by anderson2805** [comment]
@dosu-bot Any issue with this commit

**Comment by baskaryan** [comment]
resolved in #17878

**Pull request closed without merging**
