### PR TITLE
pinecone: Fix multiprocessing issue in PineconeVectorStore

### PR DESCRIPTION
**Pull request by Vwake04**
**Description:**

Currently, the `langchain_pinecone` library forces the `async_req` (asynchronous required) argument to Pinecone to `True`. This design choice causes problems when deploying to environments that do not support multiprocessing, such as AWS Lambda. In such environments, this restriction can prevent users from successfully using `langchain_pinecone`.

This PR introduces a change that allows users to specify whether they want to use asynchronous requests by passing the `async_req` parameter through `**kwargs`. By doing so, users can set `async_req=False` to utilize synchronous processing, making the library compatible with AWS Lambda and other environments that do not support multithreading.

**Issue:**
This PR does not address a specific issue number but aims to resolve compatibility issues with AWS Lambda by allowing synchronous processing.

**Dependencies:**
None, that I'm aware of.

### CODE REVIEW

**Review by efriis — APPROVED** [review]

**Comment by Vwake04** [comment]
@efriis could you please review this?

**Comment by Vwake04** [comment]
@efriis any updates on this?

**Comment by Vwake04** [comment]
Hey @efriis could you please review this PR and make the necessary approvals?

**Comment by Vwake04** [comment]
@efriis could you please review the changes and update the PR?

**Comment by Vwake04** [comment]
@efriis could you please have a look at this PR?

**Comment by Vwake04** [comment]
@efriis Any updates on this?

**Review by efriis — APPROVED** [review]

**Comment by Vwake04** [comment]
Thanks 🙏 @efriis

**Pull request merged**
