### PR TITLE
document loader as a retriever

### PR DESCRIPTION
**Pull request by leo-gan**
This unbraking change allows using every Document loader as a Retriever without any additional changes.
This change effectively increased number of the available retrievers from ~20 to 80+ 

`docs/extras/modules/data_connection/retrievers/how_to/document_loaders_as_retrievers.ipynb` provides explanations and a usage example.

Maintainer responsibilities:
  - DataLoaders / VectorStores / Retrievers: @rlancemartin, @eyurtsev
 It can be interesting for @hwchase17 and @dev2049

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
i think probably not ideal to have every document loader inherit from this, maybe we can make a mixin though? only for document laoders which actually have a query param

**Comment by leo-gan** [comment]
> i think probably not ideal to have every document loader inherit from this, maybe we can make a mixin though? only for document laoders which actually have a query param

Yeah, I like this idea. I'll try to do this.

**Comment by leo-gan** [comment]
I've added descriptions for the notebook. Please, let me know if this is enough or not.

**Comment by leo-gan** [comment]
Will follow the mixin option with a new PR.

**Pull request closed without merging**
