### PR TITLE
Azure Search: Remove select field restrictions and expand metadata to other fields, also expose kwargs to searches

### PR DESCRIPTION
**Pull request by reflection**
Description: 
If metadata field returned in results, previous behavior unchanged.  If metadata field does not exist in results, expand metadata to any fields returned outside of content field.

There's precedence for this as well, see the retriever: https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/azure_cognitive_search.py#L96C46-L96C46

Issue: 
#9765 - Ameliorates hard-coding in case you already indexed to cognitive search without a metadata field but rather placed metadata in separate fields.

@hwchase17

### CODE REVIEW

**Review by bn-msethuraman — APPROVED** [review]

**Review by bn-whughes — APPROVED** [review]

**Review by bn-gmoss — APPROVED** [review]
looks good to me, much needed fix

**Comment by baskaryan** [comment]
cc @ruoccofabrizio

**Comment by levalencia** [comment]
thumbs up, need this functionality

**Comment by levalencia** [comment]
Something worth mentioning, specially for the developers involved in azuresearch.py.

The add text method to add items to the azure index works fine, but thats only when in your use case you want to manually insert data into the vector index, in most scenarios, the indexer will connect to a data source (blob storare/sql, etc), and then execute a custom skill set to generate the chunks and the embeddings.

Microsoft has provided a custom skillset which is used in the indexers to chunk and generate the embeddings.
This skillset only uses langchain for splitting, it cant use add_texts because its job is to return content to the indexer and its actually the indexer who inserts data into the vector index.

For this reason I encourge the developers of this class Azure Search to take a look at the provided custom skill set
https://github.com/Azure-Samples/azure-search-power-skills/tree/main/Vector/EmbeddingGenerator

I implemented it this way for blob storage and it works really well.

**Comment by NatanMish** [comment]
Looks good!

**Comment by ruoccofabrizio** [comment]
> Something worth mentioning, specially for the developers involved in azuresearch.py.
> 
> The add text method to add items to the azure index works fine, but thats only when in your use case you want to manually insert data into the vector index, in most scenarios, the indexer will connect to a data source (blob storare/sql, etc), and then execute a custom skill set to generate the chunks and the embeddings.
> 
> Microsoft has provided a custom skillset which is used in the indexers to chunk and generate the embeddings. This skillset only uses langchain for splitting, it cant use add_texts because its job is to return content to the indexer and its actually the indexer who inserts data into the vector index.
> 
> For this reason I encourge the developers of this class Azure Search to take a look at the provided custom skill set https://github.com/Azure-Samples/azure-search-power-skills/tree/main/Vector/EmbeddingGenerator
> 
> I implemented it this way for blob storage and it works really well.

@levalencia As you pointed out, using an indexer eliminates the need to depend on the PUSH API or ACS SDK for adding documents to the index, since the indexer itself performs the insertion based on the custom skill's output. LangChain implementation serves as a wrapper for the SDK in situations where external control of ingestion is required, apart from the Indexer concept. This should be considered as an alternative to directly using the PUSH API or the SDK.

**Comment by levalencia** [comment]
> > Something worth mentioning, specially for the developers involved in azuresearch.py.
> > The add text method to add items to the azure index works fine, but thats only when in your use case you want to manually insert data into the vector index, in most scenarios, the indexer will connect to a data source (blob storare/sql, etc), and then execute a custom skill set to generate the chunks and the embeddings.
> > Microsoft has provided a custom skillset which is used in the indexers to chunk and generate the embeddings. This skillset only uses langchain for splitting, it cant use add_texts because its job is to return content to the indexer and its actually the indexer who inserts data into the vector index.
> > For this reason I encourge the developers of this class Azure Search to take a look at the provided custom skill set https://github.com/Azure-Samples/azure-search-power-skills/tree/main/Vector/EmbeddingGenerator
> > I implemented it this way for blob storage and it works really well.
> 
> @levalencia As you pointed out, using an indexer eliminates the need to depend on the PUSH API or ACS SDK for adding documents to the index, since the indexer itself performs the insertion based on the custom skill's output. LangChain implementation serves as a wrapper for the SDK in situations where external control of ingestion is required, apart from the Indexer concept. This should be considered as an alternative to directly using the PUSH API or the SDK.

Indeed, the issue is that the person who created the azuresearch.py file and the search methods I guess he/she assumed developers would use the push API (add_texts method), instead of the Open AI Embedding Generator developed by Microsoft, which works fantastic :)
Azuresearch.py should be able to handle different index schemas (field names) and also when metadata fields are not present.

**Comment by ruoccofabrizio** [comment]
> > > Something worth mentioning, specially for the developers involved in azuresearch.py.
> > > The add text method to add items to the azure index works fine, but thats only when in your use case you want to manually insert data into the vector index, in most scenarios, the indexer will connect to a data source (blob storare/sql, etc), and then execute a custom skill set to generate the chunks and the embeddings.
> > > Microsoft has provided a custom skillset which is used in the indexers to chunk and generate the embeddings. This skillset only uses langchain for splitting, it cant use add_texts because its job is to return content to the indexer and its actually the indexer who inserts data into the vector index.
> > > For this reason I encourge the developers of this class Azure Search to take a look at the provided custom skill set https://github.com/Azure-Samples/azure-search-power-skills/tree/main/Vector/EmbeddingGenerator
> > > I implemented it this way for blob storage and it works really well.
> > 
> > 
> > @levalencia As you pointed out, using an indexer eliminates the need to depend on the PUSH API or ACS SDK for adding documents to the index, since the indexer itself performs the insertion based on the custom skill's output. LangChain implementation serves as a wrapper for the SDK in situations where external control of ingestion is required, apart from the Indexer concept. This should be considered as an alternative to directly using the PUSH API or the SDK.
> 
> Indeed, the issue is that the person who created the azuresearch.py file and the search methods I guess he/she assumed developers would use the push API (add_texts method), instead of the Open AI Embedding Generator developed by Microsoft, which works fantastic :) Azuresearch.py should be able to handle different index schemas (field names) and also when metadata fields are not present.

@levalencia I developed the integration in collaboration with ACS Product Group :) 
This is an explicit choice aligned with LangChain pattern where the vector_store handles the ingestion while performing the embeddings creation. If you use the Custom Skill the embedding creation is already managed and the insertion is basically just formatting the result to be compliant to the expected output in the skillset definition. What would be the value of having the vector_store abstraction in that context?

**Comment by reflection** [comment]
Correct, the point of the PR is to expand retrieval to be useful for those (like @levalencia and my colleagues) who used the custom skillset when indexing without changing the behavior for those who used langchain for both.

**Comment by ruoccofabrizio** [comment]
> Correct, the point of the PR is to expand retrieval to be useful for those (like @levalencia and my colleagues) who used the custom skillset when indexing without changing the behavior for those who used langchain for both.

fully agree @reflection , what we were discussing with @levalencia is not strictly related to this PR that addresses the retrieval and not the ingestion.
My comment was about the below, as add_text is to not be used in the Skillset as it has another purpose by design. 
"This skillset only uses langchain for splitting, it cant use add_texts because its job is to return content to the indexer and its actually the indexer who inserts data into the vector index." quote @levalencia 

In terms of the actual PR, I'll have a look because I have some doubts that returning all the fields in the index is the most efficient way to achieve what you're looking for. e.g. you will always return the vector field as well, which may be not needed

**Comment by levalencia** [comment]
thanks for the feedback @ruoccofabrizio

**Comment by reflection** [comment]
> In terms of the actual PR, I'll have a look because I have some doubts that returning all the fields in the index is the most efficient way to achieve what you're looking for. e.g. you will always return the vector field as well, which may be not needed

Updated PR by filtering out vector field via dict comprehension for consideration.

**Comment by reflection** [comment]
@ruoccofabrizio Any other feedback?

My colleagues and I also need to expose search filters at the `_get_relevant_documents` level - all of the underlying searches, `vector_search(), hybrid_search(), semantic_hybrid_search()` support filters already.

**Comment by levalencia** [comment]
I wonder why this hasnt been merged, :) client need this :)

**Pull request merged**
