### PR TITLE
community: PremAI integration in LangChain

### PR DESCRIPTION
**Pull request by Anindyadeep**
### Prem SDK integration in LangChain

This PR adds the integration with [PremAI's](https://www.premai.io/) prem-sdk with langchain. User can now access to deployed models (llms/embeddings) and use it with langchain's ecosystem. This PR adds the following:

### This PR adds the following:

- [x]  Add chat support
- [X]  Adding embedding support
- [X]  writing integration tests
    - [X]  writing tests for chat 
    - [X]  writing tests for embedding
- [X]  writing unit tests
    - [X]  writing tests for chat 
    - [X]  writing tests for embedding
- [X]  Adding documentation
    - [X]  writing documentation for chat
    - [X]  writing documentation for embedding
- [X] run `make test`
- [X] run `make lint`, `make lint_diff` 
- [X]  Final checks (spell check, lint, format and overall testing)

### CODE REVIEW

**Comment by Anindyadeep** [comment]
Hi it would be great if this PR be started to get reviewed. 

Thanks 

cc: @efriis @hwchase17

**Review by baskaryan — APPROVED** [review]
@efriis know you're refactoring pyproject.toml files so will let you merge

**Review by efriis — COMMENTED** [review]
@Anindyadeep could you take a look at the checks? It's failing most of them (linting, testing, etc.)

**Comment by efriis** [comment]
Also looks like we don't have edit access to your branch. In the future, PRs from personal branches work better! Guide: https://python.langchain.com/docs/contributing/faq#how-do-i-allow-maintainers-to-edit-my-pr

**Comment by Anindyadeep** [comment]
Hi @efriis @baskaryan I have migrated the PR to this: #19113 to my personal account so that we can re-iterate on this faster and hopefully merge. 

Thanks

**Pull request closed without merging**
