### PR TITLE
Make openai chat configurable as openai llm

### PR DESCRIPTION
**Pull request by piEsposito**
This PR makes OpenAI Chat wrapper inherit from BaseOpenAI, which allows it to pass temperature and other configuration.

Still WIP.

### CODE REVIEW

**Comment by hwchase17** [comment]
is this just for better typing of the params? not all of them are the same

**Comment by piEsposito** [comment]
ChatCompletion does not accept `best_of`, so I can either do a dict comprehension to remove this key or code everything.

What do you think is better?

**Comment by hwchase17** [comment]
would rather just code everything (or rather, just the important ones)

**Comment by dev2049** [comment]
closing since OpenAIChat is deprecated

**Pull request closed without merging**
