### PR TITLE
Fix issue with openai-function-agent ai message parsing

### PR DESCRIPTION
**Pull request by homanp**
- Description: Fixes an issue when the function call arguments are not valid JSON 
  - Issue: #9307 
  - Tag maintainer: @hwchase17 @eyurtsev 
  - Twitter handle: @pelaseyed

### CODE REVIEW

**Comment by homanp** [comment]
@hwchase17 people stumbled upon this issue with `create_csv_agent` where the it would throw errors due to malformed arguments. I did some digging and basically I'm guessing this is due to the LLM not sending back valid JSON. I added a fix for that but perhaps you would like to handle this in some other manner somewhere else in the repo.

**Comment by baskaryan** [comment]
i imagine if model output is expected to be json (ie structured) and just a string is returned, something downstream will break? so probably better to raise the error, and if you want to automatically handle you could wrap the original output parser in something like the RetryOutputParser?

**Comment by homanp** [comment]
> i imagine if model output is expected to be json (ie structured) and just a string is returned, something downstream will break? so probably better to raise the error, and if you want to automatically handle you could wrap the original output parser in something like the RetryOutputParser?

It has nothing to do with the return `type` in itself imo. Also if you need to wrap this in something else, just to get it work, it makes more sense to do it here don't you think? 

We run this right now in production with significant usage with experiencing any downstream issues.

**Comment by homanp** [comment]
@baskaryan any updates on this?

**Comment by homanp** [comment]
@hwchase17 bump on this.

**Comment by homanp** [comment]
I did some logging and this issue seems to be more severe than I initially thought. Almost half the queries break the OutputParser. 

Example: https://smith.langchain.com/public/f6e0c4ee-6de7-4a7a-98c7-0e05d0f5e2df/r

Is there any chance we could get a fix in (doesn't have to be this PR) in order mitigate?

@hwchase17

**Comment by hwchase17** [comment]
https://github.com/langchain-ai/langchain/pull/9618 - i think this should fix it? or at least hopefully help substantially

**Comment by andreizet** [comment]
> #9618 - i think this should fix it? or at least hopefully help substantially

it doesn't.

**Comment by homanp** [comment]
@andreizet Works better for me at least. But there should be some more robustness around parsing arguments perhaps.

**Pull request closed without merging**
