### PR TITLE
Support multiple filters for ElasticVectorStore

### PR DESCRIPTION
**Pull request by moise-g**
This PR will
- Enable the ElasticVectorStore to support multiple filters (combine all the filters using `AND` operator)
- Put the query in a filter context ensuring that the scores of the retrieved documents are not affected by the number of filters.  (For reference on the difference between query context and filter context see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html#filter-context)
- add support for arbitrary elasticsearch query as filter using the `filter_is_es_query` toggle

 
@rlancemartin, @eyurtsev

### CODE REVIEW

**Comment by baskaryan** [comment]
cc @jeffvestal

**Comment by jeffvestal** [comment]
@moise-g do you have an example notebook or even some example code for testing the changes with different scenarios?

**Comment by joemcelroy** [comment]
With ElasticsearchStore, it now supports metadata filtering. [See documentation](https://python.langchain.com/docs/integrations/vectorstores/elasticsearch#filtering-metadata)

**Comment by leo-gan** [comment]
@moise-g Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by efriis** [comment]
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

**Pull request closed without merging**
