### PR TITLE
langchain: `tenacity` dependency to version `^=8.1.0,!=8.4.0`

### LINKED ISSUE #22972: It will occurred error if a dependent library `tenacity` is upgraded to `8.4.0`.
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```py
import tenacity
```

### Error Message and Stack Trace (if applicable)

> ```
> > import tenacity
> ...
> lib/python3.11/site-packages/tenacity/__init__.py", line 653, in <module>
>      from tenacity.asyncio import AsyncRetrying  # noqa:E402,I100
>      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  ModuleNotFoundError: No module named 'tenacity.asyncio'
> ```

### Description

Tenacity 8.4.0 has error.

https://github.com/langchain-ai/langchain/blob/892bd4c29be34c0cc095ed178be6d60c6858e2ec/libs/core/pyproject.toml#L15

https://github.com/jd/tenacity/issues/471

### System Info

- Python 3.11
- tenacity 8.4.0

### PR DESCRIPTION
**Pull request by itok01**
Fix https://github.com/langchain-ai/langchain/issues/22972.

- [x] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [x] **PR message**: ***Delete this entire checklist*** and replace with
    - **Description:** a description of the change
    - **Issue:** the issue # it fixes, if applicable
    - **Dependencies:** any dependencies required for this change
    - **Twitter handle:** if your PR gets announced, and you'd like a mention, we'll gladly shout you out!

- [x] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Review by nicoloboschi — COMMENTED** [review]
since it seems an unintended behaviour introduced by the library, I wonder if it'd be better to use 
``` 
tenacity = >=8.1.0,!=8.4.0
```
to keep upgrades moving automatically

**Comment by itok01** [comment]
Thanks for giving me a better solution!

> since it seems an unintended behaviour introduced by the library, I wonder if it'd be better to use
> 
> ```
> tenacity = >=8.1.0,!=8.4.0
> ```
> 
> to keep upgrades moving automatically

**Review by nicoloboschi — APPROVED** [review]
I think you also need to generate the poetry.lock files

**Comment by itok01** [comment]
I did it. Thank you.

**Review by cbornet — APPROVED** [review]
LGTM, great work !

**Review by eyurtsev — APPROVED** [review]

**Comment by eyurtsev** [comment]
Thank you!

Related issue from tenacity: https://github.com/jd/tenacity/issues/475

**Comment by NathanAP** [comment]
Hi @itok01 , sorry for the direct ping.

Can you have a look at [this](https://github.com/langchain-ai/langchain/discussions/25595)? 
Not really sure how complex is to update `tenacity`, but this is really important because we can't use `langchain` with `graphrag` in the same workflow.

**Comment by itok01** [comment]
Hello @NathanAP. Thank you for your message.

This PR states that it will change the version of tenacity to `>=8.1.0,<8.4.0`, but in reality, it will be `^=8.1.0,!=8.4.0`. (It excludes `8.4.0`.)

I will correct the PR title, which deviates from the actual content.

**Pull request merged**
