### PR TITLE
community[patch]: Fix chat openai unit test

### PR DESCRIPTION
**Pull request by LuizFrra**
- **Description:** 
  Actually the test named `test_openai_apredict` isn't testing the apredict method from ChatOpenAI. 
  - **Issue:**
  The test where its occur
  - **Dependencies:** 
  None

### CODE REVIEW

**Review by eyurtsev — APPROVED** [review]

**Comment by eyurtsev** [comment]
merge when unit tests pass

**Comment by eyurtsev** [comment]
@LuizFrra unit-tests fail so probably need to update some of the mocking code for the client as well?

**Comment by LuizFrra** [comment]
> @LuizFrra unit-tests fail so probably need to update some of the mocking code for the client as well?

Ok, I will work on thsi now

**Comment by LuizFrra** [comment]
I guess that's working now.
image

**Comment by LuizFrra** [comment]
i forgot to delete de open-api-key test

**Comment by LuizFrra** [comment]
@eyurtsev I also have added this env:
* `os.environ["OPENAI_API_KEY"] = "foo"`
The test was working before because the tests below set the environment before the execution of chat openai tests.
* `unit_tests/embeddings/test_openai.py`
* `unit_tests/llms/test_openai.py`

**Comment by eyurtsev** [comment]
Unit tests should generally not modify env variables in a way that affects them globally -- this can lead to hard to find bugs in unrelated tests. Can we pass an API key through init instead of modifying the environ?

**Comment by LuizFrra** [comment]
@eyurtsev I also removed the env from the others tests and I used the mock function to mock the environment just for the scope of the functions.

**Comment by eyurtsev** [comment]
@LuizFrra why not  pass the api key instead when instantiating the model? It will result in less code and keep the tests simpler. 

I think it's OK to touch the environment via local patch for unit tests that are specifically testing some interacting with the env, but unless the unit test is doing that, we should probably favor passing the api key through the init

**Comment by LuizFrra** [comment]
@eyurtsev I understand what you say, I did the changes that you had suggest.

**Review by eyurtsev — APPROVED** [review]
Thanks!

**Pull request merged**
