### PR TITLE
Resolved: Revert "Add ChatGLM for llm and chat_model by using ChatGLM API (#9797)" #10805

### PR DESCRIPTION
**Pull request by etveritas**
Resolved: Revert "Add ChatGLM for llm and chat_model by using ChatGLM API (#9797)" #10805

### CODE REVIEW

**Comment by baskaryan** [comment]
thanks @etveritas! could we add a notebook to the docs for the chat model (in `docs/docs/integrations/chat`)

**Comment by a289459798** [comment]
@etveritas 急需你这个，作者需要你补充一个文档

**Comment by baskaryan** [comment]
Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

**Comment by hwchase17** [comment]
closing due to inactivity and merge conflicts

**Pull request closed without merging**
