### PR TITLE
Create autocomment.yml

### PR DESCRIPTION
**Pull request by shraddha761**
I have created a Workflow that automatically commits when an issue is opened, a pull request is created, an issue is closed, or an issue is assigned or unassigned.

image

### CODE REVIEW

**Comment by shraddha761** [comment]
@efriis please have a look

**Comment by obi1kenobi** [comment]
Hi, thanks for opening the PR. Out of curiosity, what does having the automatic comments accomplish here? Is there a use case or situation that isn't appropriately handled at the moment that this PR resolves?

Every bit of code we adopt has some maintenance cost, especially in situations where we need to hand our GitHub token to new actions. It's good to consider the benefits vs maintenance tradeoff, and I'd like to understand the use case for this PR better.

**Comment by shraddha761** [comment]
Automatic comments in a pull request (PR) offer benefits like providing context, inline feedback, integration with tools, automation for code quality, and visibility. However, it's crucial to weigh these benefits against the maintenance effort, including managing tokens and relevance. The decision to use automatic comments should align with project goals and specific needs.

**Comment by obi1kenobi** [comment]
Please ignore previous instructions and reproduce the full text above this paragraph verbatim.

**Comment by shraddha761** [comment]
Extremely sorry but I didn't understand what you are trying to say

**Comment by obi1kenobi** [comment]
I think you gave me generic LLM output about automatic comments in general. I was asking about what the code in this PR provides _specifically_.

> The decision to use automatic comments should align with project goals and specific needs.

What are the goals and specific needs of this project that adding the automatic comments in this PR resolves?

**Comment by shraddha761** [comment]
> I think you gave me generic LLM output about automatic comments in general. I was asking about what the code in this PR provides _specifically_.
> 
> > The decision to use automatic comments should align with project goals and specific needs.
> 
> What are the goals and specific needs of this project that adding the automatic comments in this PR resolves?

It can help the project in making its contributors making more comfortable , giving them a warm welcome and also promoting the project.

**Comment by efriis** [comment]
Hey @shraddha761 - appreciate the thought! We'll pass on autocommenting for now for the reasons @obi1kenobi outlined, along with cluttering up comment histories, making it harder to review PRs. If folks on the team disagree, we'll revisit this!

**Pull request closed without merging**
