### PR TITLE
docs: nvidia: provider page update

### PR DESCRIPTION
**Pull request by leo-gan**
Nvidia provider page is missing a Triton Inference Server package reference.
Changes:
- added the Triton Inference Server reference
- copied the example notebook from the package into the doc files.
- added the Triton Inference Server description and links, the link to the above example notebook
- formatted page to the consistent format

NOTE:
It seems that the [example notebook](https://github.com/langchain-ai/langchain/blob/master/libs/partners/nvidia-trt/docs/llms.ipynb) was originally created in wrong place. It should be in the LangChain docs [here](https://github.com/langchain-ai/langchain/tree/master/docs/docs/integrations/llms). So, I've created a copy of this example. The original example is still in the nvidia-trt package.

### CODE REVIEW

**Comment by efriis** [comment]
@leo-gan should be fixed and will monitor!

https://pypi.org/project/langchain-nvidia-trt/ is not fully published yet (just an rc), so let's skip documenting it until then. Could you remove those? Love the other updates though!

**Comment by leo-gan** [comment]
@efriis I removed nvidia_trt artifacts.

**Comment by leo-gan** [comment]
@efriis PR is ready for review

**Comment by leo-gan** [comment]
@baskaryan  PR is ready for review

**Review by baskaryan — APPROVED** [review]

**Comment by leo-gan** [comment]
@baskaryan Thanks!

**Pull request merged**
