### PR TITLE
Added ItemParsedListOutputParser

### PR DESCRIPTION
**Pull request by JacobFV**
feature: #4258

Note: still need to write tests

### CODE REVIEW

**Comment by JacobFV** [comment]
Added tests and ready to merge

**Comment by efriis** [comment]
Hey @JacobFV ! Same question as #4272 - would you be interested in updating this to the current repo state, or would it be better to close this as a reference implementation for future work?

**Comment by JacobFV** [comment]
Close, now a better solution is to somehow get the json parser to work with
arbitrary items

**Comment by efriis** [comment]
Sounds great. Thanks!

**Pull request closed without merging**
