### PR TITLE
docs:  Adding Docs for new SQLServer Vector store package

### PR DESCRIPTION
**Pull request by Pookam90**
**Description:** Adding Documentation for new SQL Server Vector Store Package.

Changed files -
  Added new Vector Store - docs\docs\integrations\vectorstores\sqlserver.ipynb
 FeatureTable.Js - docs\src\theme\FeatureTables.js
Microsoft.mdx - docs\docs\integrations\providers\microsoft.mdx

Detailed documentation on API - https://python.langchain.com/api_reference/sqlserver/index.html

### CODE REVIEW

**Comment by Pookam90** [comment]
@baskaryan I am getting vercel deployment error for unrelated files I havent changed or touched https://langchain-hyca809rb-langchain.vercel.app

Could you help us with fixing this? 

Error: MDX compilation failed for file "/vercel/path0/docs/docs/langserve.md"
Cause: Docs markdown link couldn't be resolved: (MIGRATION.md) in source file "/vercel/path0/docs/docs/langserve.md" for version current
Details:
Error: Docs markdown link couldn't be resolved: (MIGRATION.md) in source file "/vercel/path0/docs/docs/langserve.md" for version current
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [Makefile:88: vercel-build] Error 1
error Command failed with exit code 2.

**Comment by JANHMS** [comment]
> @baskaryan I am getting vercel deployment error for unrelated files I havent changed or touched https://langchain-hyca809rb-langchain.vercel.app
> 
> Could you help us with fixing this?
> 
> Error: MDX compilation failed for file "/vercel/path0/docs/docs/langserve.md" Cause: Docs markdown link couldn't be resolved: (MIGRATION.md) in source file "/vercel/path0/docs/docs/langserve.md" for version current Details: Error: Docs markdown link couldn't be resolved: (MIGRATION.md) in source file "/vercel/path0/docs/docs/langserve.md" for version current error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. make: *** [Makefile:88: vercel-build] Error 1 error Command failed with exit code 2.

I had the same in my PR and I think other PRs have the same issue. 
https://github.com/langchain-ai/langchain/pull/28157

**Comment by Pookam90** [comment]
@baskaryan requesting help on this Vercel Failure

**Comment by yorek** [comment]
@efriis can you please help to have the PR unblocked? Thanks!

**Comment by Pookam90** [comment]
@eyurtsev @efriis could you help us with unblocking this PR please?

**Review by efriis — COMMENTED** [review]
any chance you could get rid of the huge vector in this?

**Review by efriis — APPROVED** [review]
for future reference this took a bit of work to get across the finish line! I think your editor might be adding some unusual html tags to the markdown cells (with style= vscode styling), as well as some issues with the format of the doc (huge embeddings, etc.).

Excited to work together, and just for future docs PRs! ^

**Comment by yorek** [comment]
Thanks a lot for the help Erick! Noted about the formatting issues, we'll double check next time

**Pull request merged**
