### PR TITLE
fix: calling the openai functions agent with an empty tool list crashes

### PR DESCRIPTION
**Pull request by willbackslash**
Fixes Issue https://github.com/langchain-ai/langchain/issues/8080

No new dependencies have been added.

@baskaryan

### CODE REVIEW

**Comment by baskaryan** [comment]
out of curiosity, why run the agent with no tools?

**Comment by willbackslash** [comment]
> out of curiosity, why run the agent with no tools?



> out of curiosity, why run the agent with no tools?
To be honest is only for testing purposes, people want to see how it answers with and without the tools

https://github.com/langchain-ai/langchain/issues/8080#issuecomment-1650969282

**Comment by leo-gan** [comment]
@baskaryan Could you, please, review it?

**Comment by efriis** [comment]
Hey @willbackslash ! Appreciate the contribution and read through #8080 . If I'm understanding correctly (and from running the repro code from the issue), this is because OpenAI returns a 400 when you pass an empty functions list.

I think this (`_completion_with_retry`) is not the right place we'd want to fix this, if the main place we want this handled is for OpenAI functions agent. **Would you be willing to open a new PR fixing it over in the agent?** We don't want to preempt errors from OpenAI too generally for this, as this implementation wouldn't be able to tolerate a future where OpenAI actually does accept an empty list of functions, or the error message has some useful information for debugging.

Happy to discuss and reopen if I misunderstood something!

**Pull request closed without merging**
