### PR TITLE
Fix IndexError when input_list is Empty in prep_prompts

### LINKED ISSUE #1733: list index out of range error if similarity search gives 0 docs
https://github.com/hwchase17/langchain/blob/276940fd9babf8aec570dd869cc84fbca1c766bf/langchain/vectorstores/milvus.py#L319

I'm using milvus where for my question I'm getting 0 documents and so index out of range error occurs

Error line:
https://github.com/hwchase17/langchain/blob/276940fd9babf8aec570dd869cc84fbca1c766bf/langchain/chains/llm.py#L95

### PR DESCRIPTION
**Pull request by sgroenjes**
This MR corrects the IndexError arising in prep_prompts method when no documents are returned from a similarity search.

Fixes #1733 

#### Who can review?

Tag maintainers/contributors who might be interested:

  @hwchase17 - project lead

  VectorStores / Retrievers / Memory
  - @dev2049

### CODE REVIEW

**Review by hwchase17 — APPROVED** [review]
seems reasonable, thanks

**Comment by tomassommareqt** [comment]
Hi @hwchase17 ! Can this be included in the next release?

**Comment by Sharvin26** [comment]
Is this fix available on the latest release? I am facing this issue on version 0.0.220.

**Comment by siddarthvader** [comment]
@hwchase17 any plan to merge this? i face the same error.

**Comment by dcieslak19973** [comment]
@hwchase17 - I'm running into the same error; can this get merged soon?

**Comment by lance-miles** [comment]
First and foremost, thank you @hwchase17 and the entire community for rapidly building such an incredible package/framework for interfacing with LLMs.

I am currently running into this issue in our system as well. I've put in a temporary fix but would love if we can get this fix merged @hwchase17 and @sgroenjes.

**Comment by baskaryan** [comment]
thanks @sgroenjes!

**Pull request merged**
