### PR TITLE
docs change for instruct embeddings

### PR DESCRIPTION
**Pull request by sanzgiri**
This adds a docs change for instruct embeddings - the `InstructorEmbbeding` python package is also required.

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
seems like the dalle stuff snuck in here as well?

**Comment by sanzgiri** [comment]
Sorry not sure how to just cherry pick a new commit to this PR if the previous one was not merged to master.

**Comment by sanzgiri** [comment]
Hi @hwchase17 - sorry to bug you, but I don't see a way to contribute additional changes, since my master already has the dalle changes and those have not been merged into master on langchain. Would appreciate any pointers.

**Comment by hwchase17** [comment]
i would do your development off of branches! rather than master

for this commit in particular, ill open up a separate pr to fix it

**Comment by sanzgiri** [comment]
Thanks, got it! I read up the docs at https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks and understand the forking workflow now.

**Pull request closed without merging**
