### PR TITLE
Broadcast operation failure while using simsimd beyond v3.7.7

### PR DESCRIPTION
**Pull request by joydeepbroy-zeotap**
- [ ] **Packages affected**: 
  - community: fix `cosine_similarity` to support simsimd beyond 3.7.7
  - partners/milvus: fix `cosine_similarity` to support simsimd beyond 3.7.7
  - partners/mongodb: fix `cosine_similarity` to support simsimd beyond 3.7.7
  - partners/pinecone: fix `cosine_similarity` to support simsimd beyond 3.7.7
  - partners/qdrant: fix `cosine_similarity` to support simsimd beyond 3.7.7

- [ ] **Broadcast operation failure while using simsimd beyond v3.7.7**: 
    - **Description:** I was using simsimd 4.3.1 and the unsupported operand type issue popped up. When I checked out the repo and ran the tests, they failed as well (have attached a screenshot for that). Looks like it is a variant of https://github.com/langchain-ai/langchain/issues/18022 . Prior to 3.7.7, simd.cdist returned an ndarray but now it returns simsimd.DistancesTensor which is ineligible for a broadcast operation with numpy. With this change, it also remove the need to explicitly cast `Z` to numpy array
    - **Issue:** #19905
    - **Dependencies:** No
    - **Twitter handle:** https://x.com/GetzJoydeep

Screenshot 2024-05-29 at 2 50 00 PM

- [ ] **Considerations**: 
  1. I started with community but since similar changes were there in Milvus, MongoDB, Pinecone, and QDrant so I modified their files as well. If touching multiple packages in one PR is not the norm, then I can remove them from this PR and raise separate ones
  2. I have run and verified that the tests work. Since, only MongoDB had tests, I ran theirs and verified it works as well. Screenshots attached :
Screenshot 2024-05-29 at 2 52 13 PM
Screenshot 2024-05-29 at 3 33 51 PM
  

I have added a test for simsimd. I feel it may not go well with the CI/CD setup as installing simsimd is not a dependency requirement. I have just imported simsimd to ensure simsimd cosine similarity is invoked. However, its not a good approach. Suggestions are welcome and I can make the required changes on the PR. Please provide guidance on the same as I am new to the community.

### CODE REVIEW

**Comment by joydeepbroy-zeotap** [comment]
@efriis @baskaryan please review

**Review by baskaryan — COMMENTED** [review]
cc @ashvardanian

**Comment by ashvardanian** [comment]
Patches make sense to me 🤗

**Comment by joydeepbroy-zeotap** [comment]
Thanks @baskaryan for the unit test fix. Is the poetry.lock file also need to be checkedin?

**Pull request merged**
