### PR TITLE
Feature/implement multi query rerank fusion retrieval

### PR DESCRIPTION
**Pull request by dmenini**
Hi, I added the `MultiQueryRankFusionRetriever`, which inherits from the `MultiQueryRetriever` but uses a different merge strategy, i.e. rerank fusion instead of unique union. For the rerank algorithm itself I reused the implementation in EnsembleRetriever (I moved it in a separate file to reuse it). 
To save some code duplication, I adapted the return types of the `retrieve_documents` function to return a `List[List[Document]]`, so that the rerank fusion works out of the box.

Additional changes:
* Optionally append original query to query variations
* Fix docstrings
* Use kwargs in classmethod to allow some freedom in the class creation

Thanks for your reviews @hwchase17, @baskaryan

### CODE REVIEW

**Comment by Vanekkk1** [comment]
This is an amazing feature !!  Would be also cool to implement rerank in basic retrievers, such as from Pinecone or FAISS

**Comment by hwchase17** [comment]
i like this feature, although perhaps could be made more general by making the reranking function configurable

**Review by ccurme — COMMENTED** [review]
Given the changes to `EnsembleRetriever`, I'm not sure we can land this without tests.

**Comment by ccurme** [comment]
Closing but will re-open if there's desire to keep iterating on this.

**Pull request closed without merging**
