### PR TITLE
feat: implement max marginal relevance for momento vector index

### PR DESCRIPTION
**Pull request by malandis**
**Description**

Implements `max_marginal_relevance_search` and `max_marginal_relevance_search_by_vector` for the Momento Vector Index vectorstore.

Additionally bumps the `momento` dependency in the lock file and adds logging to the implementation.

**Dependencies**

✅ updates `momento` dependency in lock file

**Tag maintainer**

@baskaryan 

**Twitter handle**

Please tag @momentohq for Momento Vector Index and @mloml for the contribution 🙇

### CODE REVIEW

**Comment by malandis** [comment]
Looks like there is some churn going on with the core refactor. I merged master and have some broken imports. Will loop back later as I believe these issues will be fixed in ongoing PRs.

**Comment by malandis** [comment]
@baskaryan ✅ integration tests pass and merge conflicts resolved by merging with latest master. Good to go on my end.

**Comment by malandis** [comment]
@baskaryan @eyurtsev this is good to go now. There was some thrashing as I submitted this around the time the `langchain_core` refactor was going on, then the CI issues were sorted out. All clear now 👍

**Comment by malandis** [comment]
@hwchase17 pinging for review. This has been good to go 👍 🙇

**Review by hwchase17 — APPROVED** [review]

**Pull request merged**
