### PR TITLE
Community: Add OceanBase Vector Store

### PR DESCRIPTION
**Pull request by GITHUBear**
This pull request introduces [OceanBase](https://github.com/oceanbase/oceanbase) as an alternative vector store.  The vector storage capability of `OceanBase` is still being enhanced, and currently has the following limitation:

- Cosine vector distance function is not yet supported for vector index. Currently only inner product distance and Euclidean distance are supported, and Euclidean distance is used by default. **This issue will lead to two requirements: 1) When initializing OceanBase, `normalize=True` needs to be set to normalize the Euclidean distance. 2) When using `similarity_search_with_relevance_scores`, `score_threshold` may need to be set to a smaller value than when using cosine distance.**

We will support cosine distance soon. 

Simple example of using `OceanBase` as vector store:

```python
from langchain_community.vectorstores.oceanbase import OceanBase
from tests.integration_tests.vectorstores.fake_embeddings import FakeEmbeddings

texts = ["foo", "bar", "baz"]
metadatas = [{"page": str(i)} for i in range(len(texts))]
docsearch = OceanBase.from_texts(
    texts=texts,
    embedding=FakeEmbeddings(),
    metadatas=metadatas,
    connection_args=CONNECTION_ARGS,
    drop_old=True,
    normalize=True,
)
output = docsearch.similarity_search("foo", k=1)
```

### CODE REVIEW

**Comment by GITHUBear** [comment]
Hi @baskaryan , could you please take a look at this PR? I’d appreciate your feedback. Thank you!

**Comment by powerfooI** [comment]
I need this feature very much, can you merge it ASAP?

**Comment by GITHUBear** [comment]
We eagerly hope that this PR can make progress. Your review would be greatly appreciated, thanks in advance! @baskaryan @efriis

**Comment by GITHUBear** [comment]
We make more modifications to pass CI checks now. Can you spare some time to help with the PR? Thanks a lot! @isahers1 @baskaryan @efriis

**Comment by efriis** [comment]
Hey! This adds a net-new community integration or feature, which has been replaced by dedicated integration packages. I'll close this PR, and would recommend reopening with just docs updates, as well as registering your package in `libs/packages.yml`! We'll be able to review simple PRs that only modify these two things much faster :)

Here's the guide, and if you have questions, feel free to leave them in the comments on those pages so others can see them! https://python.langchain.com/docs/contributing/how_to/integrations/

**Pull request closed without merging**
