### PR TITLE
Fixed sparql SELECT and UPDATE query function

### PR DESCRIPTION
**Pull request by aditya-29**
- Description: Changed "SELECT" and "UPDTAE" intent check from "=" to "in",
  - Issue: Based on my own testing, most of the LLM (StarCoder, NeoGPT3, etc..) doesn't return a single word response ("SELECT" / "UPDATE") through this modification, we can accomplish the same output without curated prompt engineering.
  - Dependencies: None
  - Tag maintainer: @baskaryan
  - Twitter handle: @aditya_0290

Thank you for maintaining this library, Keep up the good efforts.

### CODE REVIEW

**Comment by aditya-29** [comment]
Fixed a bug which makes the _intent_ returns None

**Comment by baskaryan** [comment]
thanks @aditya-29!

**Comment by felixocker** [comment]
@aditya-29 do you have some examples of what was returned by the models you tried? I guess there must have been additional words if the `strip()` was insufficient.
if so, what was your experience with the generated queries - were they executable if the model did not even manage to follow the intent recognition prompt?

**Comment by aditya-29** [comment]
Hi @felixocker, I tried starcoderLLM and GPT Neo from HugginFaceto classify the question "what is a DNA?" into a SELECT or UPDATE query. The response I got was "The SELECT will be a appropriate query for this question" instead of just the word "SELECT". Most of the LLMs (including Bard) does not return a single word response for the given prompt.

**Comment by felixocker** [comment]
I see, cool that you tried it with several models.
What about the generated SPARQL queries? Did you get executable ones from these models?

**Comment by aditya-29** [comment]
Yes! The models were able to generate the SPARQL queries for simple questions, but they failed to comprehend complex questions

**Comment by felixocker** [comment]
Makes sense, still cool though!

**Comment by i-arnab** [comment]
Is this issue resolved? I am currently using GraphSparqlQAChain and passing a rdf graph .nt file as input. On running this model, everytime the intent is becoming UPDATE despite even clearly engineering the prompt to make the model choose SELECT as intent. I am currently looking for a solution and couldnt find anything online except this git thread. Please if anyone can help me out, that would be great! 

P.S - I am very much new to using LLms with graph data. Please let me know

**Comment by felixocker** [comment]
> 

PR #8521 should fix the issue, but it has not yet been merged
If you need to get it working quickly, you could install langchain with the PR; for instructions using pip see [this discussion](https://stackoverflow.com/questions/13561618/pip-how-to-install-a-git-pull-request)

**Pull request merged**
