### PR TITLE
community: Bug Fix, in Neo4j VectorStore when having multiple indexes the sort is not working and the store that returned is random

### PR DESCRIPTION
**Pull request by ehude**
Bug fix: when having multiple indexes the sort is not working and the store that returned is random.
The following small fix resolves the issue.

### CODE REVIEW

**Comment by baskaryan** [comment]
cc @tomasonjo

**Comment by tomasonjo** [comment]
@ehude looks ok. Can you please add a test

**Comment by ehude** [comment]
@tomasonjo thanks for the info.
I've added the relevant test, let me know if that is ok.

**Comment by tomasonjo** [comment]
You need to create two indexes, but then use `from_existing_index` and check if it picked the correct one :)

**Comment by ehude** [comment]
make more sense indeed :)
fixed and pushed.

**Comment by tomasonjo** [comment]
Awesome, thank you!

**Comment by ehude** [comment]
Glad I could help :)
BTW, any idea when is the next release or where I can update on upcoming released?

**Comment by tomasonjo** [comment]
@ehude can you check the lint error, so that we can get this in? Thanks

**Comment by ehude** [comment]
@tomasonjo Sure, will fix it tomorrow

**Comment by ehude** [comment]
@tomasonjo 
Pushed a fix and tested locally with `make lint_package`.
Please let me know if need to run anything else to check.

**Comment by tomasonjo** [comment]
> 1 file would be reformatted, 599 files already formatted


seems like formatting is missing. If you run `make format`, it should be fixed.

**Comment by ehude** [comment]
done

**Comment by tomasonjo** [comment]
Thanks @ehude . @baskaryan LGTM!

**Comment by tomasonjo** [comment]
Can you move it from unit tests to integration tests, and then it should pass all checks :)

**Comment by ehude** [comment]
Thanks
Done :)

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
