### PR TITLE
[Core]: Fix `add_ai_message_chunks` usage_metadata combining

### PR DESCRIPTION
**Pull request by keenborder786**
- **Description:** Checking If other `AIMessageChunk` usage_metadata keys are null before combing them.
- **Issue:** #26348

### CODE REVIEW

**Comment by keenborder786** [comment]
@eyurtsev

**Comment by keenborder786** [comment]
@eyurtsev can you review this?

**Review by eyurtsev — CHANGES_REQUESTED** [review]
Fix does not appear to be in the correct place, and no unit tests

**Comment by keenborder786** [comment]
@eyurtsev okay

**Pull request closed without merging**
