### PR TITLE
Add SQL Docstore

### PR DESCRIPTION
**Pull request by pprados**
**Description:**
The storage package propose 
- Redis
- AstraDB

I propose to add an SQLStore.
@baskaryan

### CODE REVIEW

**Comment by cbornet** [comment]
Similar PR: https://github.com/langchain-ai/langchain/pull/15909
I think it would be good to have only one consistent implementation.

**Comment by pprados** [comment]
Another [PR](https://github.com/langchain-ai/langchain/pull/15909) is merged

**Comment by pprados** [comment]
@efriis 
I reopen this PR, because the [PR15909](https://github.com/langchain-ai/langchain/pull/15909) presents some problems.

**Review by efriis — COMMENTED** [review]
Hey @pprados ! I think this implementation has some similar issues, and it also looks incomplete (lots of commented out code).

The main issue with a SQL store is that it may need db migrations down the line, so very inconspicuous changes can result in large breaking changes for people using it.

Would you be open to completing the implementation in a template instead, so people can pull it locally and deal with those migrations themselves?

**Pull request closed without merging**
