### PR TITLE
Feat: Cache text only option

### PR DESCRIPTION
**Pull request by keenborder786**
### Description

This pull request addresses issue #25912, which suggests that caching only the text content of messages would be more efficient than caching the entire serialized message. 

**Summary of Changes:**

- Introduces a new attribute, `cache_text_only`, to control caching behavior.
- When `cache_text_only` is set to `True`, the cache will store only the `text` content of the message, rather than the entire serialized message.

**Rationale:**

Storing only the text content of messages can lead to significant improvements in cache efficiency and performance. By focusing on just the text, we reduce the cache size and potentially decrease retrieval times.

**Implementation Details:**

- Added the `cache_text_only` attribute to the relevant configuration.
- Updated cache handling logic to check the value of `cache_text_only` and store only the message `text` if the attribute is `True`.
- Ensured backward compatibility by defaulting `cache_text_only` to `False`, thus preserving the existing behavior.

### CODE REVIEW

**Comment by Undertone0809** [comment]
Some benchmarking may be required to quantify the actual performance gains.

**Review by Undertone0809 — COMMENTED** [review]
1. Performance impact: Some benchmarking may be required to quantify the actual performance gains.
2. You may want to consider some boundary cases, such as how the message content will behave if it is empty or very long.
3. Cache consistency: You need to ensure that cache consistency is not affected when switching cache_text_only Settings.
4. Documentation update: Need to add docs.

I personally do not recommend this usage, adding complexity to the API usage. Given that LangChain is a general-purpose framework, it may be more important to provide flexibility. But at the same time, we have to weigh the costs of increased complexity.


Suggest:
- Consider implementing a more general cache preprocessing hook that allows users to customize how cached content is generated. This satisfies both users who want to cache only text and users who need more control.
- At the same time, several preset caching strategies can be provided, such as "text only", "full object", etc., to meet common requirements.

**Comment by keenborder786** [comment]
Okay

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by efriis** [comment]
leaving as needs support and can return if folks have some good motivating examples.

In general, I think if you want custom caching behavior like this, it doesn't make sense to use the main LC caching abstraction. Keeping the cache contents in sync with "which caching strategy you're using" will create a lot more confusing errors than usefulness it provides imo

**Comment by keenborder786** [comment]
@efriis keeping it open then.

**Pull request closed without merging**
