### PR TITLE
add FunctionMessage support to `_convert_dict_to_message()` in OpenAI chat model

### PR DESCRIPTION
**Pull request by thehunmonkgroup**
Already supported in the reverse operation in `_convert_message_to_dict()`, this just provides parity.

@hwchase17
@agola11

### CODE REVIEW

**Review by vowelparrot — APPROVED** [review]

**Review by hwchase17 — COMMENTED** [review]
wont we want to include additional_kwargs?

Can we add unit test?

**Comment by thehunmonkgroup** [comment]
> wont we want to include additional_kwargs?

@hwchase17  none of the other elements of that function add `additional_kwargs` besides the `function_call` in the `AIMessage` conversion. It's not clear to me what we would even add to `additional_kwargs` in the `FunctionMessage` case.

Here's the example code from OpenAI, looks like passing a function message is just the `role`, `name`, and `content` to me:

```json
{
  "model": "gpt-3.5-turbo-0613",
  "messages": [
    {"role": "user", "content": "What is the weather like in Boston?"},
    {"role": "assistant", "content": null, "function_call": {"name": "get_current_weather", "arguments": "{ \"location\": \"Boston, MA\"}"}},
    {"role": "function", "name": "get_current_weather", "content": "{\"temperature\": "22", \"unit\": \"celsius\", \"description\": \"Sunny\"}"}
  ],
  "functions": [
    {
      "name": "get_current_weather",
      "description": "Get the current weather in a given location",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "The city and state, e.g. San Francisco, CA"
          },
          "unit": {
            "type": "string",
            "enum": ["celsius", "fahrenheit"]
          }
        },
        "required": ["location"]
      }
    }
  ]
}
```
If you could confirm that the existing code is correct, I'll try to work up a unit test, first time contributor, so I'll need to fumble my way through it ;)

**Comment by thehunmonkgroup** [comment]
> Can we add unit test?

@hwchase17 well there wasn't even a unit test file for `chat_models/test_openai.py` ;)

I think I got a correct test written and it's passing.

Let me know if you need anything else to get this PR in.

**Review by hwchase17 — APPROVED** [review]

**Comment by hwchase17** [comment]
> > wont we want to include additional_kwargs?
> 
> @hwchase17 none of the other elements of that function add `additional_kwargs` besides the `function_call` in the `AIMessage` conversion. It's not clear to me what we would even add to `additional_kwargs` in the `FunctionMessage` case.
> 
> Here's the example code from OpenAI, looks like passing a function message is just the `role`, `name`, and `content` to me:
> 
> ```json
> {
>   "model": "gpt-3.5-turbo-0613",
>   "messages": [
>     {"role": "user", "content": "What is the weather like in Boston?"},
>     {"role": "assistant", "content": null, "function_call": {"name": "get_current_weather", "arguments": "{ \"location\": \"Boston, MA\"}"}},
>     {"role": "function", "name": "get_current_weather", "content": "{\"temperature\": "22", \"unit\": \"celsius\", \"description\": \"Sunny\"}"}
>   ],
>   "functions": [
>     {
>       "name": "get_current_weather",
>       "description": "Get the current weather in a given location",
>       "parameters": {
>         "type": "object",
>         "properties": {
>           "location": {
>             "type": "string",
>             "description": "The city and state, e.g. San Francisco, CA"
>           },
>           "unit": {
>             "type": "string",
>             "enum": ["celsius", "fahrenheit"]
>           }
>         },
>         "required": ["location"]
>       }
>     }
>   ]
> }
> ```
> 
> If you could confirm that the existing code is correct, I'll try to work up a unit test, first time contributor, so I'll need to fumble my way through it ;)

ah right sorry, got confused

thanks!

**Pull request merged**
