### PR TITLE
Add a full PostgresSQL syntax database 'AnalyticDB' as vector store.

### PR DESCRIPTION
**Pull request by wangxuqi**
Hi there！
I'm excited to open this PR to add support for using a fully Postgres syntax compatible database 'AnalyticDB' as a vector.
As AnalyticDB has been proved can be used with AutoGPT, ChatGPT-Retrieve-Plugin, and LLama-Index, I think it is also good for you.
AnalyticDB is a distributed Alibaba Cloud-Native vector database. It works better when data comes to large scale. The PR includes:

- [x]  A new memory: AnalyticDBVector
- [x]  A suite of integration tests verifies the AnalyticDB integration

I have read your [contributing guidelines](https://github.com/hwchase17/langchain/blob/72b7d76d79b0e187426787616d96257b64292119/.github/CONTRIBUTING.md). And I have passed the tests below
- [x]  make format
- [x]  make lint
- [x]  make coverage
- [x]  make test

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
this looks pretty good - can you add an example notebook? that will help greatly with documentation and discoverability!

**Comment by wangxuqi** [comment]
> this looks pretty good - can you add an example notebook? that will help greatly with documentation and discoverability!

@hwchase17 OK, I'm willing to do it.

**Comment by wangxuqi** [comment]
@hwchase17 Done! I have  add an example notebook and add related document

**Review by hwchase17 — APPROVED** [review]
thanks!

**Pull request merged**
