### PR TITLE
feat: prompt laboratory

### PR DESCRIPTION
**Pull request by formidable-stella**
- Description: implement `PromptLaboratory` similar to `ModelLaboratory`, which facilitates experimenting with different prompts on one model.
- Example usage can be checked with `docs/extras/guides/prompt_laboratory.ipynb`
- Tag maintainer:   @hwchase17, @dev2049

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
couldn't we keep one object and just add a `from_prompts` method (similar to the existing `from_llms` method)?

**Comment by dubuduru** [comment]
hmm yes, that could be a better option.
Then you mean to add functions to the object (ModelLaboratory) that supports the followings?
- multiple llm, one prompt
- one llm, multiple prompt
- multiple llm, multiple prompt

**Comment by leo-gan** [comment]
@dubuduru Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

**Comment by efriis** [comment]
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

**Pull request closed without merging**
