### PR TITLE
experimental: Enhance LLMGraphTransformer with async processing and improved readability

### PR DESCRIPTION
**Pull request by jjovalle99**
- [x] **PR title**: "experimental: Enhance LLMGraphTransformer with async processing and improved readability"

- [x] **PR message**: 
    - **Description:** This pull request refactors the `process_response` and `convert_to_graph_documents` methods in the LLMGraphTransformer class to improve code readability and adds async versions of these methods for concurrent processing.
    The main changes include:
  - Simplifying list comprehensions and conditional logic in the process_response method for better readability.
  - Adding async versions aprocess_response and aconvert_to_graph_documents to enable concurrent processing of documents.
  These enhancements aim to improve the overall efficiency and maintainability of the `LLMGraphTransformer` class.
  - **Issue:** N/A
  - **Dependencies:** No additional dependencies required.
  - **Twitter handle:** @jjovalle99

- [x] **Add tests and docs**: N/A (This PR does not introduce a new integration)

- [x] **Lint and test**: Ran make format, make lint, and make test from the root of the modified package(s). All tests pass successfully.

Additional notes:

- The changes made in this PR are backwards compatible and do not introduce any breaking changes.
- The PR touches only the `LLMGraphTransformer` class within the experimental package.

### CODE REVIEW

**Comment by jjovalle99** [comment]
@efriis

**Comment by jjovalle99** [comment]
FYI ~ Fixed the linting issue from last nigth.

**Comment by jjovalle99** [comment]
@hwchase17

**Comment by jjovalle99** [comment]
@efriis

**Comment by jjovalle99** [comment]
@baskaryan

**Comment by jjovalle99** [comment]
Hello LC Team! Just wanted to add visibility to this one @efriis! Have a good day!

**Review by baskaryan — COMMENTED** [review]
cc @tomasonjo

**Review by tomasonjo — APPROVED** [review]
LGTM!

**Comment by Kurumindla-Kranthivardhan** [comment]
llm = OpenAI(model_name="gpt-4-0125-preview")
llm_transformer = LLMGraphTransformer(llm=llm)
graph_documents = llm_transformer.convert_to_graph_documents(pages)

raise NotImplementedError()
NotImplementedError


hey team can you help me with this error

**Comment by tomasonjo** [comment]
```
from langchain_openai import ChatOpenAI
llm = ChatOpenAI(model_name="gpt-4-0125-preview")

```

**Comment by Kurumindla-Kranthivardhan** [comment]
Screenshot 2024-04-05 at 3 30 19 PM
Hey can you help me with this errors

**Comment by Kurumindla-Kranthivardhan** [comment]
> Screenshot 2024-04-05 at 3 30 19 PM Hey can you help me with this errors

image

**Pull request merged**
