### PR TITLE
Community: add new integration Novita AI

### PR DESCRIPTION
**Pull request by jasonhp**
Thank you for contributing to LangChain!

- [x] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, etc. is being modified. Use "docs: ..." for purely docs changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [x] **PR message**: 
    - **Description:** Add new integration Novita AI
    - **Twitter handle:** @novita_ai_labs

- [x] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Comment by nikolay-phxa** [comment]
Calling the agent ChatNovita with messages with large context (around 10000 tokens) with a normal format is returning gibberish such as:

"Swith Due Date being fund (and email.Aaron WFormated Interstate, withApiOperation"

Token usage: {'completion_tokens': 19, 'prompt_tokens': 10096, 'total_tokens': 10115, 'completion_tokens_details': None, 'prompt_tokens_details': None}

Using llama3.1 70b.

The Due Date and Aaron are in the text of the SystemMessage. 
Essentially, we ask a questions to be answer based on a context embedded in the SystemMessage. 
Same works with openai, runpod docker Llama, Ollama local, Groq all works with the same context. 

For a simple questions with no large contact, the agent works.

**Comment by efriis** [comment]
Hey! This adds a community integration, which is no longer recommended. Would you be interested in publishing your own integration package, and contributing docs via this guide? https://python.langchain.com/docs/contributing/how_to/integrations/

**Comment by jasonhp** [comment]
> Calling the agent ChatNovita with messages with large context (around 10000 tokens) with a normal format is returning gibberish such as:
> 
> "Swith Due Date being fund (and email.Aaron WFormated Interstate, withApiOperation"
> 
> Token usage: {'completion_tokens': 19, 'prompt_tokens': 10096, 'total_tokens': 10115, 'completion_tokens_details': None, 'prompt_tokens_details': None}
> 
> Using llama3.1 70b.
> 
> The Due Date and Aaron are in the text of the SystemMessage. Essentially, we ask a questions to be answer based on a context embedded in the SystemMessage. Same works with openai, runpod docker Llama, Ollama local, Groq all works with the same context.
> 
> For a simple questions with no large contact, the agent works.



> Calling the agent ChatNovita with messages with large context (around 10000 tokens) with a normal format is returning gibberish such as:
> 
> "Swith Due Date being fund (and email.Aaron WFormated Interstate, withApiOperation"
> 
> Token usage: {'completion_tokens': 19, 'prompt_tokens': 10096, 'total_tokens': 10115, 'completion_tokens_details': None, 'prompt_tokens_details': None}
> 
> Using llama3.1 70b.
> 
> The Due Date and Aaron are in the text of the SystemMessage. Essentially, we ask a questions to be answer based on a context embedded in the SystemMessage. Same works with openai, runpod docker Llama, Ollama local, Groq all works with the same context.
> 
> For a simple questions with no large contact, the agent works.

Hey! Thanks for your feedback. Can you give me the usecase? Like how did you use our service in langchain, or what the request looks like?

**Comment by jasonhp** [comment]
> Hey! This adds a community integration, which is no longer recommended. Would you be interested in publishing your own integration package, and contributing docs via this guide? https://python.langchain.com/docs/contributing/how_to/integrations/

Okay, I will try to implement a integration package.

**Comment by jasonhp** [comment]
> Hey! This adds a community integration, which is no longer recommended. Would you be interested in publishing your own integration package, and contributing docs via this guide? https://python.langchain.com/docs/contributing/how_to/integrations/

Hello! Will this PR be merged or do I have to create an integration package and this PR will be closed?

**Comment by efriis** [comment]
that would be great!

This adds a net-new community integration or feature, which has been replaced by dedicated integration packages. I'll close this PR, and would recommend reopening with just docs updates, as well as registering your package in `libs/packages.yml`! We'll be able to review simple PRs that only modify these two things much faster :)

Here's the guide, and if you have questions, feel free to leave them in the comments on those pages so others can see them! https://python.langchain.com/docs/contributing/how_to/integrations/

**Pull request closed without merging**
