### PR TITLE
Adding a connector for CogniSwitch.ai

### PR DESCRIPTION
**Pull request by CogniJT**
- **Description:** CogniSwitch focusses on making GenAI usage more reliable. It abstracts out the complexity & decision making required for tuning processing, storage & retrieval. Using simple APIs documents / URLs can be processed into a Knowledge Graph that can then be used to answer questions.
  - **Dependencies:** No dependencies. Just network calls & API key required
  - **Tag maintainer:** @hwchase17
  - **Twitter handle:** @CogniSwitch
  - **Documentation:** Please check `docs/extras/use_cases/cogniswitch_chain_usage.ipynb`
  - **Tests:** Unit tests added within chains/ `test_cogniswitch_store` & `test_cogniswitch_answer` 
 
PR has passed linting and testing before this submission.

### CODE REVIEW

**Comment by CogniJT** [comment]
@hwchase17 could you help us understand what's failing here? Thanks

**Comment by CogniJT** [comment]
Bumping this up for some attention. Would appreciate a review. Thanks
@baskaryan @eyurtsev

**Comment by CogniJT** [comment]
Hey guys, it's been a few days. Bumping this up as requested. @hwchase17

**Comment by CogniJT** [comment]
@hwchase17 @baskaryan @eyurtsev 
Bumping this again for some attention. Do let us know the way forward. Any next steps or corrections to pass the bot checks. Thanks.

**Comment by CogniJT** [comment]
@nfcampos Hi requesting help on the Vercel deployment issue. We are unable to access details regarding this Vercel bot so cannot debug further. It's been close to a month so it'd be great to move ahead on this. Thanks

**Comment by baskaryan** [comment]
@CogniJT i'm wondering if this should be a Chain or a Tool? seems more like a Tool to me but maybe don't fully understand intended usage

**Comment by CogniJT** [comment]
Hi @baskaryan, thanks for your response. We were wondering the same thing. It could be both since LangChain allows Chains to be Tools as well, right? Basically we have 2 services, first to store & organize content in our Knowledge Graph, second to query that graph in Natural language & return an answer via LLM generation.

**Comment by CogniJT** [comment]
Hi @baskaryan what changes do you recommend in light of the above?

**Comment by CogniJT** [comment]
Hi @hwchase17 @baskaryan @nfcampos @eyurtsev 
Requesting help here to merge. If there's someone else who can help us with this issue, do point us in their direction. 

There must be some reason the deployment has failed. It's just not visible to us. Once we get that, we can work out a fix without troubling you. 

Hoping to get this done before the two month mark. We would appreciate your understanding & time on this. 

Cheers

**Comment by CogniJT** [comment]
@saiCogniswitch Some failing checks, please correct them. @hwchase17 thanks for your response & guidance, requesting help with the failing CI checks.

**Comment by CogniJT** [comment]
I'm not seeing our tool mentioned in the CI results. Do let us know if we can correct anything.

**Comment by CogniJT** [comment]
I'm also wondering if we should have a reviewer assigned to this PR.

**Comment by baskaryan** [comment]
fixed some tests and formatting in #13595 but still seeing some failing tests @CogniJT

**Comment by saiCogniswitch** [comment]
thanks @baskaryan , checking the tests, will resolve and update here

**Comment by saiCogniswitch** [comment]
Hi @baskaryan , I have updated the tests and resolved the issues, can you check and let me know if any more changes are required.
Thanks
Have a good day

**Comment by saiCogniswitch** [comment]
Hello Everyone
Good morning
Any update w.r.t the PR, Let us know if any changes are required.
Thanks 
Have a good day

**Comment by CogniJT** [comment]
Hi @hwchase17 & @baskaryan, requesting help with this. Thanks

**Comment by saiCogniswitch** [comment]
Hi Everyone,
requesting help with the PR, let us know if anything needs to be done.
Thanks,
Have a good day.

**Comment by CogniJT** [comment]
Hi @hwchase17 & @baskaryan, I think there's some confusion on this branch that @baskaryan tried: https://github.com/langchain-ai/langchain/pull/13595.

We have since updated the code. Refer: https://github.com/langchain-ai/langchain/pull/10862#issuecomment-1818409824
> Hi @baskaryan , I have updated the tests and resolved the issues, can you check and let me know if any more changes are required. Thanks Have a good day

At this point there seem to be no conflicts from the CI/CD bot. We've even updated the branch multiple times to sync with master. Do give this a check & let us know if we can do anything to see this through.

Cheers

**Comment by CogniJT** [comment]
Hi guys, any updates here? Please help.

**Comment by CogniJT** [comment]
Hi @hwchase17 @baskaryan @eyurtsev @langchain-infra, requesting help with this please. Thank you

**Comment by baskaryan** [comment]
Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

**Comment by saiCogniswitch** [comment]
hi @baskaryan, we have updated the code into langchain_community and put a PR here [17312](https://github.com/langchain-ai/langchain/pull/17312).
here all the checks have been passed except for vercel deployment, let us know how we can move forward with this.
Thank you 
have a good day.

**Comment by baskaryan** [comment]
closing in favor of https://github.com/langchain-ai/langchain/pull/17312

**Pull request closed without merging**
