### PR TITLE
Use `getLogger` instead of `basicConfig` in `multi_query.py`

### PR DESCRIPTION
**Pull request by zhichenggeng**
Remove `logging.basicConfig`, which turns on logging. Use `getLogger` instead.

cc @rlancemartin

### CODE REVIEW

**Comment by rlancemartin** [comment]
@zhichenggeng i no longer see logging in notebook as expected w/ this change.

did you test this?

**Comment by rlancemartin** [comment]
Needed to add:

```
import logging
# Set up basic configuration
logging.basicConfig()
# Set logging level for the specific logger
logging.getLogger('langchain.retrievers.multi_query').setLevel(logging.INFO)
```

To the notebook. Putting up a PR to fix this now.

**Comment by zhichenggeng** [comment]
@rlancemartin I have tested and no longer see the logging when I import `langchain.retrievers`. But I forgot to modify the notebook. Sorry for that.

**Comment by rlancemartin** [comment]
> @rlancemartin I have tested and no longer see the logging when I import `langchain.retrievers`. But I forgot to modify the notebook. Sorry for that.

np, thanks.

**Comment by rlancemartin** [comment]
Resolved! https://github.com/hwchase17/langchain/pull/7102

**Pull request merged**
