### PR TITLE
Add a utility to generate image from a prompt (OpenAI DALL-E)

### PR DESCRIPTION
**Pull request by sanzgiri**
This is a utility that allows you to generate an image from a prompt. It uses the OpenAI DALL-E image generator, which can take the same API key as the LLM. The output is a link to the generated image, which can be downloaded to a file or rendered depending on the use case. By default a single image of resolution 1024x1024 is generated.

### CODE REVIEW

**Comment by sanzgiri** [comment]
Sorry, I did not mean to the commit the "poetry.lock" file. Could it be removed from the PR?

**Comment by hwchase17** [comment]
> Sorry, I did not mean to the commit the "poetry.lock" file. Could it be removed from the PR?

yeah ill clean up

btw, thank you for this! very excited to get something for images in :)

**Comment by sanzgiri** [comment]
Thanks, I also have the dalle-image-generator set up as a tool that can be run from an agent and can also add a notebook showing the usage. Should I add them to this PR or wait until this one is in?

**Comment by hwchase17** [comment]
> Thanks, I also have the dalle-image-generator set up as a tool that can be run from an agent and can also add a notebook showing the usage. Should I add them to this PR or wait until this one is in?

oooo if you wanted to this pr that would be awesome. i was going to take a stab at that myself (i always find that an example notebook is super nice for showing off the new stuff) but if you already have it that is 💯

**Comment by sanzgiri** [comment]
I have added the code I mentioned and resolved the merge conflict.

**Pull request merged**
