### PR TITLE
Added facade classes: LLMFacade, ChatModelFacade

### PR DESCRIPTION
**Pull request by JacobFV**
feature: #4251

Note: still need to write tests

### CODE REVIEW

**Comment by JacobFV** [comment]
Added tests and ready to merge

**Comment by dev2049** [comment]
could you add some motivation? would be very helpful to see an example with and without these interfaces

**Comment by JacobFV** [comment]
Now that we have the call and call_with_messages, this is unnecessary. Closing

**Comment by JacobFV** [comment]
Now that we have the call and call_with_messages, this is unnecessary. Closing

**Pull request closed without merging**
