### PR TITLE
Add metadata filter capability to similarity search functions for Supabase

### PR DESCRIPTION
**Pull request by benharris2510**
Title:
Add metadata filtering capabilities to similarity search functions

Description:

This PR enhances the functionality of the similarity search methods in our codebase. Specifically, we now support optional metadata-based filtering in our search functions.

Details:

The affected functions include:

similarity_search
similarity_search_by_vector
similarity_search_with_relevance_scores
similarity_search_by_vector_with_relevance_scores
similarity_search_by_vector_returning_embeddings
For each of these functions, a new filter argument has been added. This argument accepts a dictionary that specifies metadata fields and their desired values.

When the filter dictionary is provided, the search functions will return documents that not only match the query based on similarity but also satisfy the metadata criteria defined by the filter.

Impact:

This change provides greater flexibility for users when conducting similarity searches. They can now refine their search results based on specific metadata properties, leading to more accurate and targeted results.

Tests:

Testing will involve invoking the modified functions with various filter criteria and verifying the returned documents meet both the similarity and metadata filter criteria.

  VectorStores / Retrievers / Memory
  - @dev2049 may be interested

### CODE REVIEW

**Comment by dev2049** [comment]
does supabase not have built-in filtering, so we don't have to do it on our side (which is probably slower and less expressive, and makes it difficult to return the correct number of documents)

**Comment by benharris2510** [comment]
I agree there is built-in filtering, however I don't see a way, not in any documentation at least, to specify the filter via Langchain. Example provided below:


```
supabase: Client = create_client(supabase_url, supabase_key)
embeddings = OpenAIEmbeddings()

# documents = supabase.table("documents").select("*").execute()['content']

db = SupabaseVectorStore(
    client=supabase,
    embedding=embeddings,
    table_name="documents"
)

docs = db.similarity_search(query)
# docs = db.similarity_search(query, filter={"user_id": user_id, "document_id": document_id})
```

However I could easily be missing something, let me know what you think.

**Comment by ShantanuNair** [comment]
Does this pull all embeddings, and then filter through them locally? I'm looking at the js implementation, but seems like it could get a tad messy with the typing.

**Comment by baskaryan** [comment]
looks like filter support was added in #7721, closing but let me know if i'm missing something!

**Pull request closed without merging**
