### PR TITLE
community: make LocalAIEmbeddings comaptible with openai>1.0 #17154

### PR DESCRIPTION
**Pull request by eahova**
** Copy of https://github.com/langchain-ai/langchain/pull/17154 with fixes (it was abandoned) **

Upgrade the LocalAIEmbeddings referencing to ChatOpenAI to make it working with openai>1.0.

### CODE REVIEW

**Comment by eahova** [comment]
This should fix issue #16442.

**Comment by eahova** [comment]
Please review: @baskaryan @eyurtsev @hwchase17

**Comment by imClumsyPanda** [comment]
Need this fix a lot

**Comment by di-rse** [comment]
Would be great to have this fixed!

**Comment by s-natsubori** [comment]
why this is not merged???

**Review by efriis — COMMENTED** [review]
does this integration do anything different than `OpenAIEmbeddings`? If so, could we deprecate this in favor of `langchain_openai.OpenAIEmbeddings`?

**Comment by efriis** [comment]
going with the above recommendation - let me know if there's something different!

Main reason this change would be bad is because it would be unexpectedly breaking for anyone still using with the expected (for this community integration) openai <1 client

let me know if you're interested in deprecating!

**Comment by mkhludnev** [comment]
Hi, faced the same problem, came up with https://github.com/mkhludnev/langchain-localai it's available via `pip` and referred by Langchain docs.

**Pull request closed without merging**
