### PR TITLE
community: enforce attribute validation in GoogleVertexAISearchRetriever

### PR DESCRIPTION
**Pull request by yoursemicolon**
This commit updates the GoogleVertexAISearchRetriever configuration to forbid unknown fields during initialization. This change ensures that users receive immediate feedback if they accidentally pass a wrong or misspelled attribute name, improving error handling and robustness of the initialization process.

The change modifies the Pydantic BaseModel configuration to set 'extra = Extra.forbid', which throws errors for any extraneous fields. This update is essential for preventing runtime errors related to attribute misconfigurations and is in line with best practices for Pydantic model setup.

### CODE REVIEW

**Comment by yoursemicolon** [comment]
>

**Comment by yoursemicolon** [comment]
@baskaryan please review

**Comment by yoursemicolon** [comment]
please review @efriis @hwchase17

**Comment by baskaryan** [comment]
this integration has been moved to https://github.com/langchain-ai/langchain-google/blob/main/libs/community/langchain_google_community/vertex_ai_search.py, could we make all changes against that?

**Comment by yoursemicolon** [comment]
> this integration has been moved to https://github.com/langchain-ai/langchain-google/blob/main/libs/community/langchain_google_community/vertex_ai_search.py, could we make all changes against that?

Thanks for the guidance. I will close this pull request and open a new one in the `langchain-google` repository.

**Pull request closed without merging**
