### PR TITLE
Improve prompt injection detection

### PR DESCRIPTION
**Pull request by asofter**
- **Description:** This is addition to [my previous PR](https://github.com/langchain-ai/langchain/pull/13930) with improvements to flexibility allowing different models and notebook to use ONNX runtime for faster speed. Since the last PR, [our model](https://huggingface.co/laiyer/deberta-v3-base-prompt-injection) got more than 660k downloads, and with the [public benchmark](https://huggingface.co/spaces/laiyer/prompt-injection-benchmark) showed much fewer false-positives than the previous one from deepset. Additionally, on the ONNX runtime, it can be running 3x faster on the CPU, which might be handy for builders using Langchain. 
 **Issue:** N/A
 - **Dependencies:** N/A
 - **Tag maintainer:** N/A 
- **Twitter handle:** `@laiyer_ai`

### CODE REVIEW

**Review by hwchase17 — APPROVED** [review]
thanks!

**Comment by michaelfeil** [comment]
@hwchase17 @asofter Looks like there are some issues in the codestyle - receiving some issues with this PR when I try to contribute to Langchain community:
```
Run make lint_package
poetry run ruff .
poetry run ruff format langchain_experimental --diff
[14](https://github.com/langchain-ai/langchain/actions/runs/7262057179/job/19784497915?pr=14846#step:9:15)2 files left unchanged
poetry run ruff --select I langchain_experimental
mkdir -p .mypy_cache; poetry run mypy langchain_experimental --cache-dir .mypy_cache
langchain_experimental/prompt_injection_identifier/hugging_face_identifier.py:14: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
langchain_experimental/prompt_injection_identifier/hugging_face_identifier.py:86: error: "str" not callable  [operator]
langchain_experimental/prompt_injection_identifier/hugging_face_identifier.py:86: error: "None" not callable  [misc]
Found 3 errors in 1 file (checked 142 source files)
make: *** [Makefile:45: lint_package] Error 1
Error: Process completed with exit code 2.
```
 https://github.com/langchain-ai/langchain/actions/runs/7262057179/job/19784497915?pr=14846

**Comment by asofter** [comment]
Hey @michaelfeil , thanks for reporting that. It's weird, as I see many errors in the code running on Python 3.8. I think with the next commit on your PR it should be gone. Otherwise, I can fix it.

**Comment by michaelfeil** [comment]
Nah, this is in any PR currently on Langchain - this needs to be solved by one distict PR. If i would solve this, would conflict with all other fixed. see: https://github.com/langchain-ai/langchain/pull/14884

**Comment by asofter** [comment]
I created another PR to fix this issue https://github.com/langchain-ai/langchain/pull/14910

But when scanning, found even more:

image

**Pull request merged**
