### PR TITLE
feat(llms): support ERNIE Embedding-V1 

### PR DESCRIPTION
**Pull request by axiangcoding**
- Description: support [ERNIE Embedding-V1](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/alj562vvu), which is part of ERNIE ecology
- Issue: None
- Dependencies: None
- Tag maintainer: @baskaryan

### CODE REVIEW

**Comment by baskaryan** [comment]
@axiangcoding is this ready for review?

**Comment by axiangcoding** [comment]
> @axiangcoding is this ready for review?

sorry, not yet. i will provide a notebook next.

**Comment by axiangcoding** [comment]
@baskaryan hi, this PR is ready now, please review!

**Comment by baskaryan** [comment]
thanks @axiangcoding!

**Pull request merged**
