### PR TITLE
refactor: enable connection pool usage in PGVector

### PR DESCRIPTION
**Pull request by dmazine**
- **Description:** `PGVector` refactored to use connection pool.
  - **Issue:** #11433,
  - **Tag maintainer:** @hwchase17 @eyurtsev,

### CODE REVIEW

**Comment by baron** [comment]
Is anything happening with this pull request?

**Comment by ricardoekm** [comment]
I'm interested in this PR too.

**Comment by dmazine** [comment]
Hello @hwchase17 @eyurtsev @nfcampos,

I have updated this PR in accordance with the last updates applied in master.

Could you guys review it?

Thanks a lot!

**Comment by dmazine** [comment]
Hi @hwchase17 @eyurtsev @nfcampos,

Could you guys review this PR?

Thanks a lot!

**Comment by dmazine** [comment]
Hi @hwchase17 @eyurtsev @nfcampos,

Do you need me to do anything else in this PR?

Thanks a lot!

**Comment by baron** [comment]
@hwchase17 @eyurtsev @nfcampos I would also appreciate attention to this PR. The PGVector's database connection is not usable at all and for many hobby projects a local database for vectors is the most accessible rather than paying for a cloud service. @dmazine did a wonderful service and without your attention or approval the codebase is going to drift again and just create more work. Please take a look.

**Comment by dmazine** [comment]
Hi @hwchase17 @eyurtsev @nfcampos,

Do you need me to do anything else in this PR?

Thanks a lot!

**Comment by dmazine** [comment]
Hello @hwchase17 @eyurtsev @nfcampos,

Can I do anything else in this PR?

Thanks a lot!

**Review by nfcampos — APPROVED** [review]
Thanks a lot for this! Sorry for the delay

**Comment by dmazine** [comment]
Thanks a lot @nfcampos!

**Pull request merged**
