### PR TITLE
feat(llms): add support for vLLM

### LINKED ISSUE #8729: VLLM
### Feature request

can we please get vllm support for faster inference 

### Motivation

faster inference speed compared to using hugging face pipeline 

### Your contribution

n/a

### PR DESCRIPTION
**Pull request by mspronesti**
Hello langchain maintainers, 
this PR aims at integrating [vllm](https://vllm.readthedocs.io/en/latest/#) into langchain. This PR closes #8729. 

This feature clearly depends on `vllm`, but I've seen other models supported here depend on packages that are not included in the pyproject.toml (e.g. `gpt4all`, `text-generation`) so I thought it was the case for this as well.

@hwchase17, @baskaryan

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
code looks reasonable, an example notebook probably needed

**Comment by mspronesti** [comment]
Hi @hwchase17, thanks for your review. I've just added one. Not sure why one of the workflows have failed, it seems like it failed while setting up python 3.11.

**Review by hwchase17 — APPROVED** [review]
lgtm! thanks

**Comment by mspronesti** [comment]
Thanks for approving! Not sure why one the checks failed though.

**Pull request merged**
