### PR TITLE
[Feat] Add optional client-side encryption to DynamoDB chat history memory

### PR DESCRIPTION
**Pull request by jplock**
**Description:** Added optional client-side encryption to the Amazon DynamoDB chat history memory with an AWS KMS Key ID using the [AWS Database Encryption SDK for Python](https://docs.aws.amazon.com/database-encryption-sdk/latest/devguide/python.html) 
**Issue:** #7886
**Dependencies:** [dynamodb-encryption-sdk](https://pypi.org/project/dynamodb-encryption-sdk/)
**Tag maintainer:**  @hwchase17 
**Twitter handle:** [@jplock](https://twitter.com/jplock/)

### CODE REVIEW

**Review by eyurtsev — APPROVED** [review]
Thank you!

**Comment by eyurtsev** [comment]
@jplock happy to merge as sono as linting is fixed. also I'm happy to handle the linting if you'd like

**Comment by jplock** [comment]
@eyurtsev I’m away from my laptop all day so if it’s an easy fix, feel free. I ran this through the formatted and linter so I’m surprised something popped up.

**Comment by baskaryan** [comment]
thank you @jplock!

**Comment by jplock** [comment]
Thank you for reviewing and merging!

**Pull request merged**
