### PR TITLE
Add summarization as supported task for hugging face pipelines (to be used with memory conversation)

### PR DESCRIPTION
**Pull request by QuentinAmbard**
Currently only `text2text-generation` and `text-generation` are supported with `HuggingFacePipeline`

This PR adds a new task `summarization`

This allows adding a custom hugging face model with `ConversationSummaryMemory` memory in our chain:

```
  pipe_summary = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6", tokenizer="sshleifer/distilbart-cnn-12-6")

  hf_summary = HuggingFacePipeline(pipeline=pipe_summary)
  memory = ConversationSummaryMemory(llm=hf_summary, memory_key="chat_history", input_key="human_input")
```

### CODE REVIEW

**Comment by dev2049** [comment]
this is great! could we add a simple integration test to `tests/integration_tests/llms/test_huggingface_pipeline.py`

**Comment by QuentinAmbard** [comment]
@dev2049 let me know if this looks ok ?

**Comment by QuentinAmbard** [comment]
I see it's being merged in another commit. Waana close this one ?

**Comment by leo-gan** [comment]
@QuentinAmbard Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that ping me and I push this PR for the review. Thanks!

**Comment by QuentinAmbard** [comment]
it's being merger already, see https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/llms/huggingface_pipeline.py#L92

**Pull request closed without merging**
