### PR TITLE
community: KuzuGraph needs allow_dangerous_requests, add graph documents via LLMGraphTransformer

### PR DESCRIPTION
**Pull request by prrao87**
- [x] **PR title**: "community: Kuzu - Add graph documents via LLMGraphTransformer"
    - This PR adds a new method `add_graph_documents` to use the `GraphDocument`s extracted by `LLMGraphTransformer` and store in a Kùzu graph backend.
    - This allows users to transform unstructured text into a graph that uses Kùzu as the graph store.

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

### CODE REVIEW

**Comment by prrao87** [comment]
Hi, could I please get an eta on when this could be merged?

**Comment by prrao87** [comment]
Hi again, checking in on the status of this PR. Thanks!

cc @baskaryan @eyurtsev

**Comment by prrao87** [comment]
Trying my luck with @hwchase17. I'd really apprecite it if this PR were reviewed and merged so that Kùzu users who are coming from LangChain can benefit. Cheers!

**Comment by alonsosilvaallende** [comment]
When can this be merged? Looking forward to it!

**Comment by ChuckNoelke** [comment]
Hi, when can the merge happen? At my company, we have would like to test it as soon as possible!

**Review by efriis — COMMENTED** [review]
hey! given this is very susceptible to sql injection in the `relationships` objects, would you be open to adding a `allow_dangerous_requests: bool` flag that is required to be true to the top-level class? Can also add to the `add_graph_documents` function just for this PR if that makes more sense to you

**Comment by prrao87** [comment]
Hi @efriis thanks for the response. I think it makes sense to add to the `add_graph_documents` function as this is the one that actually creates the graph using these f-string queries (I didn't have a choice as the table names need to be constructed dynamically in Kùzu). Could you advise on where the flag can be applied exactly and update this PR? Thanks!

**Comment by efriis** [comment]
ended up doing on the init - it looks like user-provided text can also be passed in query and others, so this can fix across!

**Pull request merged**
