### PR TITLE
community: Huridocs pdf loader more functionality added

### PR DESCRIPTION
**Pull request by ali6parmak**
- [ ] **PR title**: "community: Huridocs pdf loader and methods added"

- [ ] **PR message**:
    - **Description:** Integrated more functionality from Huridocs' [pdf-document-layout-analysis](http://github.com/huridocs/pdf-document-layout-analysis) tool to HuridocsPDFLoader.

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
can you add a documentation page?

**Comment by ali6parmak** [comment]
@hwchase17 Sure. This is my first contribution to langchain so just to make sure, I should put the documentation into docs/integrations/document_loaders as a .ipynb file, right?

**Comment by efriis** [comment]
[Needs support for review](https://python.langchain.com/v0.2/docs/contributing/review_process/)

Seems to implement same as #25348

**Comment by PabloKarpacho** [comment]
@efriis this is my PR https://github.com/langchain-ai/langchain/pull/25348 
I can remove it because the current PR is made by Huridocs developers

**Comment by ali6parmak** [comment]
@efriis We can help you in the review process if you need any help, we can even have a call to do it.

**Pull request closed without merging**
