### PR TITLE
Re-structure agent docs

### PR DESCRIPTION
**Pull request by rlancemartin**
1/ Update overview page for agents
2/ Move agent docs from use-cases to modules and consolidate there

### CODE REVIEW

**Review by rlancemartin — COMMENTED** [review]
@baskaryan looks like we lost the img links in ntbk.

Also, the colab link won't work until we merge (it points to where the ntbk will live on master).

**Comment by baskaryan** [comment]
> @baskaryan looks like we lost the img links in ntbk.
> 
> Also, the colab link won't work until we merge (it points to where the ntbk will live on master).

seeing image here https://langchain-6s0ybo59r-langchain.vercel.app/docs/use_cases/agents/

unfortunately not sure how to make image show up in docusaurus and as a notebook unless we host the images somewhere else. and would prefer for it to show up in actual docs if i had to choose

**Comment by rlancemartin** [comment]
Discussion w/ @baskaryan: I'm going to move this to `modules` [here](https://langchain-git-rlm-agentusecase-langchain.vercel.app/docs/modules/agents/agent_types/):

1/ agent stuff is not as hardened as other use-cases
2/ agent themselves are not really a use-case
3/ the overlap is confusing

**Comment by rlancemartin** [comment]
Note: discussed w/ @baskaryan and we'll move these back to use cases but under a tab that collects more experimental use cases (agents, code gen, etc).

**Pull request closed without merging**
