### PR TITLE
Recursive url loader w/ test

### PR DESCRIPTION
**Pull request by finger-bone**
Description: Due to some issue on the test, this is a separate PR with the test for #8502

Tag maintainer: @rlancemartin

### CODE REVIEW

**Comment by rlancemartin** [comment]
Thanks. When the other PR lands, we can merge master, leaving only the test with this PR.

**Comment by rlancemartin** [comment]
The test will pass if we remove `--disable-socket`:

``` 
poetry run pytest --allow-unix-socket tests/unit_tests/
```

But there are other issues, so it need some deeper attention:

```
4.61s call     tests/unit_tests/retrievers/test_tfidf.py::test_from_texts
4.01s call     tests/unit_tests/llms/test_openai.py::test_openai_async_retries
4.01s call     tests/unit_tests/llms/test_openai.py::test_openai_retries
3.09s call     tests/unit_tests/document_loaders/test_recursive_url_loader.py::test_sync_recursive_url_loader
1.88s call     tests/unit_tests/vectorstores/test_sklearn.py::test_sklearn
============================================================ short test summary info =============================================================
FAILED tests/unit_tests/test_pytest_config.py::test_socket_disabled - Failed: DID NOT RAISE <class 'pytest_socket.SocketBlockedError'>
============================================ 1 failed, 1023 passed, 85 skipped, 40 warnings in 33.80s ============================================
(llama) rlm@Rs-MacBook-Pro langchain % poetry run pytest --allow-unix-socket tests/unit_tests/
```

I'll discuss w/ @baskaryan about how we can modify tests to enable socket connections.

**Comment by rlancemartin** [comment]
Discussed w/ @baskaryan: we'll make this one of our first additions for integration tests.

Planning to add integration tests fairly soon.

**Comment by baskaryan** [comment]
moved to integration test for now, once we've made sure scheduled integration tests work we can add to those so that they actually get run in CI

**Pull request merged**
