### PR TITLE
fix markdown text splitter horizontal lines

### LINKED ISSUE #5614: MarkdownTextSplitter: multiple repeat at position 4 (line 3, column 2)
### System Info

langchain 0.0.188
python 3.8.10

### Who can help?

_No response_

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.docstore.document import Document
from langchain.text_splitter import MarkdownTextSplitter

# of course this is part of a larger markdown document, but this is the minimal string to reproduce
txt = "\n\n***\n\n" 

doc = Document(page_content=txt)
markdown_splitter = MarkdownTextSplitter(chunk_size=1000, chunk_overlap=0)
splitted = markdown_splitter.split_documents([doc])
```

```
Traceback (most recent call last):
  File "t.py", line 9, in <module>
    splitted = markdown_splitter.split_documents([doc])
  File "/home/richard/.local/lib/python3.8/site-packages/langchain/text_splitter.py", line 101, in split_documents
    return self.create_documents(texts, metadatas=metadatas)
  File "/home/richard/.local/lib/python3.8/site-packages/langchain/text_splitter.py", line 88, in create_documents
    for chunk in self.split_text(text):
  File "/home/richard/.local/lib/python3.8/site-packages/langchain/text_splitter.py", line 369, in split_text
    return self._split_text(text, self._separators)
  File "/home/richard/.local/lib/python3.8/site-packages/langchain/text_splitter.py", line 346, in _split_text
    splits = _split_text(text, separator, self._keep_separator)
  File "/home/richard/.local/lib/python3.8/site-packages/langchain/text_splitter.py", line 37, in _split_text
    _splits = re.split(f"({separator})", text)
  File "/usr/lib/python3.8/re.py", line 231, in split
    return _compile(pattern, flags).split(string, maxsplit)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 671, in _parse
    raise source.error("multiple repeat",
re.error: multiple repeat at position 4 (line 3, column 2)
```

### Expected behavior

splitted contains splitted markdown and no errors occur

### PR DESCRIPTION
**Pull request by IlyaMichlin**
Fixes #5614 

#### Issue

The `***` combination produces an exception when used as a seperator in `re.split`. Instead `\*\*\*` should be used for regex exprations.

#### Who can review?

@eyurtsev

### CODE REVIEW

**Review by devstein — COMMENTED** [review]
Thanks for fixing this! MO more future proof solution is to use [re.escape](https://docs.python.org/3/library/re.html#re.escape) on _all_ language separators

**Comment by IlyaMichlin** [comment]
@devstein, I appreciate your suggestion, but using re.escape would also escape the '\' character in '\n', which isn't the intended behavior. It's important to note that these strings are regular expressions, so they should be explicitly defined for the sake of clarity and to better comprehend their functionality.

**Review by hwchase17 — COMMENTED** [review]
can we add a test for this?

**Comment by IlyaMichlin** [comment]
@hwchase17 I added a test for Markdown splilitter.
I fixed additional issues with the Markdown regex. The test covers all of them.

**Comment by IlyaMichlin** [comment]
@hwchase17 I added a test for markdown.
There were a few issues with the regex expressions for RST and Markdown which I fixed and added test covering this.

**Review by hwchase17 — APPROVED** [review]
thanks

**Pull request merged**
