### PR TITLE
Changed the metadata source from temporary file location to original …

### PR DESCRIPTION
**Pull request by pranavpandey2511**
Changed the metadata source from temporary file location to original url/path in PyMuPDf
Issue: #7034
@rlancemartin , @eyurtsev

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
i think these are the same:

```
    @property
    def source(self) -> Optional[str]:
        """The source location of the blob as string if known otherwise none."""
        return str(self.path) if self.path else None
```

**Comment by pranavpandey2511** [comment]
It was indeed same, original web_path is present is set as the source value in BasePDFLoader, set the blob source to that.

**Comment by leo-gan** [comment]
@pranavpandey2511 Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by efriis** [comment]
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

**Pull request closed without merging**
