### PR TITLE
The _convert_message_to_dict function of the ErnieBotChat module does not process the SystemMessage, resulting in an error message.

### PR DESCRIPTION
**Pull request by xy200303**
The _convert_message_to_dict function of the ErnieBotChat module does not process the SystemMessage, resulting in an error message.

### CODE REVIEW

**Comment by xy200303** [comment]
The ErnieBotChat module already supports the ChatGLM2-6B-32K model, which can be added for more people to call

**Review by baskaryan — APPROVED** [review]

**Comment by baskaryan** [comment]
@axiangcoding based on unit tests seems like raising error on system message is actually intended behavior, is that correct?

**Comment by axiangcoding** [comment]
> @axiangcoding based on unit tests seems like raising error on system message is actually intended behavior, is that correct?

In the past, several of Ernie's models did not support SystemMessage, that is why i add some testcase to prevent it. But now some models are starting to support it.
@xy200303 can you please also modify the unit tests? Thanks.

**Comment by xy200303** [comment]
> > @axiangcoding based on unit tests seems like raising error on system message is actually intended behavior, is that correct?
> 
> In the past, several of Ernie's models did not support SystemMessage, that is why i add some testcase to prevent it. But now some models are starting to support it. @xy200303 can you please also modify the unit tests? Thanks.

Ok, I've handled these tests correctly

**Comment by baskaryan** [comment]
closing since ErnieBot has been deprecated in favor of QianfanChatEndpoint

**Pull request closed without merging**
