### PR TITLE
core[patch]: improve index/aindex api when batch_size<n_docs

### PR DESCRIPTION
**Pull request by federico-pisanu**
- **Description:** prevent index function to re-index entire source document even if nothing has changed.
- **Issue:** #22135

I worked on a solution to this issue that is a compromise between being cheap and being fast.
In the previous code, when batch_size is greater than the number of docs from a certain source almost the entire source is deleted (all documents from that source except for the documents in the first batch)
My solution deletes documents from vector store and record manager only if at least one document has changed for that source.

Hope this can help!

### CODE REVIEW

**Review by baskaryan — COMMENTED** [review]
could we add unit tests for this?

**Comment by federico-pisanu** [comment]
@baskaryan  yeah sure!
I checked the current tests and noticed that they where not properly testing the functionality. Patching the timestamps but not changing the patch between the "index" calls it was not properly simulating consequent calls. The test were passing but they were not testing the right thing.
Updating the tests was sufficient to check that the new code works and fixes the old behavior.

**Comment by federico-pisanu** [comment]
Hi @eyurtsev can i do something to make it easier to merge?

**Comment by eyurtsev** [comment]
Standby we're working on the 0.3 release so there was an effective code freeze for the past 2 weeks

**Comment by eyurtsev** [comment]
Hi @federico-pisanu,

Thank you for the PR! In order to merge the changes, the code would need to do the following:

1. Apply similar changes to the `aindex` API
2. Revert modifications to existing unit tests (these modifications make it look like the PR is introducing a new bug!)
3. Add a new unit tests that cover the relevant scenario.

**Comment by eyurtsev** [comment]
@federico-pisanu let me double check the existing unit tests to make sure they were wrong

**Comment by eyurtsev** [comment]
@federico-pisanu OK confirmed -- no action is required from you at this time. I'll re-apply changes on aindex

**Comment by federico-pisanu** [comment]
@eyurtsev Isn't it already done?

**Review by eyurtsev — APPROVED** [review]

**Comment by eyurtsev** [comment]
@federico-pisanu yep didn't notice -- looks good added unit tests to cover the optimization -- i.e., we get different results based on which batch was mutated

**Pull request merged**
