### PR TITLE
Fixed a similarity score calculation bug in Chroma module

### PR DESCRIPTION
**Pull request by boxcounter**
The `_results_to_docs_and_scores()` function should have returned the similarity score (higher values indicating more similarity), but erroneously returned the distance (higher values indicating less similarity).

@rlancemartin, @eyurtsev

### CODE REVIEW

**Comment by hinthornw** [comment]
I think most of the vector stores "scores" by default are distances, though it sometimes depends on how you configure the underlying index. This is why the relevance scores method was created, as an api that enforces an interpretation of what score means

**Comment by boxcounter** [comment]
I agree with you that most of the vector stores "scores" by default are distance. 

If we want to use distance as the score as well, then we should modify the [comparison operation](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/base.py#L173)  in `VectorStore.similarity_search_with_relevance_scores()` from 
`if similarity >= score_threshold` to `if distance_score <= score_threshold`. 



> I think most of the vector stores "scores" by default are distances, though it sometimes depends on how you configure the underlying index. This is why the relevance scores method was created, as an api that enforces an interpretation of what score means

**Comment by rlancemartin** [comment]
> I agree with you that relevance scores method was created to enforce an interpretation of what score means.
> 
> At the same time, I also think that since `VectorStore.similarity_search_with_relevance_scores()` treats score uniformly as similarity, the underlying implementation (Chroma in this case) should also return similarity instead of distance.
> 
> https://github.com/hwchase17/langchain/blob/64039b9f112653d686bbcdd980fa90ad2f3eb9fc/langchain/vectorstores/base.py#L168-L174
> 
> > I think most of the vector stores "scores" by default are distances, though it sometimes depends on how you configure the underlying index. This is why the relevance scores method was created, as an api that enforces an interpretation of what score means

Yes, https://github.com/hwchase17/langchain/pull/6570 has a fix for this.

**Comment by boxcounter** [comment]
> @boxcounter please confirm that #6570 implements what you need. Will work with @raymond-yuan to get this in.

Great, that's what I need. And it's a much more complete implementation. Nice work!

**Comment by boxcounter** [comment]
Fixed in v0.0.230. Close this PR.

**Pull request closed without merging**
