### PR TITLE
feat: ParallelChain

### PR DESCRIPTION
**Pull request by mbchang**
Similarly to how sequential chains connect chains in series, I thought we could have `ParallelChain`s connect chains in parallel. This is a useful abstraction when you want to independently process the same input with multiple different chains, possibly asynchronously. 

This was largely inspired by the `ConcatenateChain` example [here](https://langchain.readthedocs.io/en/latest/modules/chains/getting_started.html#create-a-custom-chain-with-the-chain-class), although I thought that it would be good to have a generic class for handling multiple chains in parallel, to make nested composition easier. The larger intent is to compose chains similar to how `nn.Sequential` and `nn.Parallel` allowed for composing neural modules in series and in parallel in Torch7.

Here is an example (which is added to the docs)

```
from langchain.llms import OpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain, SimpleParallelChain

llm = OpenAI(temperature=0.9)

prompt_1 = PromptTemplate(
    input_variables=["product"],
    template="What is a good name for a company that makes {product}?",
)
chain_1 = LLMChain(llm=llm, prompt=prompt_1)

prompt_2 = PromptTemplate(
    input_variables=["product"],
    template="What is a good slogan for a company that makes {product}?",
)
chain_2 = LLMChain(llm=llm, prompt=prompt_2)

parallel_chain = SimpleParallelChain(
    chains=[chain_1, chain_2],
    input_variables=['product'],
    output_variables=['name', 'slogan'],
    verbose=True
)
output = parallel_chain("colorful socks")
print(f"Output:\n{output}")
```
which produces the output:
```
> Entering new SimpleParallelChain chain...

> Finished chain.
Output:
{'product': 'colorful socks', 'name': '\n\nLively Sockery.', 'slogan': '\n\n"Step Into Color with Our Socks!"'}
```

If having a class like this would be useful, there a few design choices I'd love to discuss: 
1. Would it make more sense to have all the chains define their own input variables manually, or should we let the parallel chain define the input variables once and propagate that to all the child chains? An argument for the former would be that it follows the existing convention I've seen in defining chains so far. An argument for the latter would be that it would allow the user to define the input variables to the entire parallel block in one place (which would make the ParallelChain abstraction more powerful), without having to copy the same input variables for all child chains.
2. Any thoughts on whether it makes sense for this to be refactored in as a subcomponent of the MapReduceChain? The main reason for replacing the map component of the mapreduce by a ParallelChain would be that users can use ParallelChain for use cases other than applying the same llm for reducing a set of documents with the same prompt - they would instead be able to use multiple chains with different prompts each.
3. Any thoughts on how we would want to support multiple outputs for each child chain, i.e. how we would want to format the output of the ParallelChain? One possibility is to do a nested dict, like:
```
{
    'output_for_chain_1: {'chain_1_output_1': str, 'chain_1_output_2': str, ... },
    'output_for_chain_2: {'chain_2_output_1': str, 'chain_2_output_2': str, ... },
}
```
or flatten the keys with a delimiter, like:
```
{
    'output_for_chain_1/chain_1_output_1': str, 'output_for_chain_1/chain_1_output_2': str, ... },
    'output_for_chain_2/chain_2_output_1': str, 'output_for_chain_2/chain_2_output_2': str, ... },
}
```

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
seems like a lot of files have unintentionally changed?

**Comment by mbchang** [comment]
Oops, apologies. It should be fixed now. We should expect four files to have changed.

**Review by hwchase17 — COMMENTED** [review]
isnt this a bit misleading since its not actually run in parallel? like they are still run sequentially (unless i am misunderstanding something? or rather i guess the outputs are produced side-by-side and then merged together... but the actually computation is still sequential, and not actually parrellizing the code

is there a slightly better name to reflect this?

**Comment by mbchang** [comment]
Yes good point. I was originally thinking about pushing this pull request to establish the parallel abstraction to start, and then adding the asynchronous feature in a follow-up pull request (where asynchronous execution can be toggled on or off when initializing the ParallelChain), but I can add the asynchronous feature in this one, if you think it would be more appropriate. 

The parallel abstraction itself has some open design choices I'd like to get your perspective on, reproduced here: 
1. Would it make more sense to have all the chains define their own input variables manually, or should we let the parallel chain define the input variables once and propagate that to all the child chains? An argument for the former would be that it follows the existing convention I've seen in defining chains so far. An argument for the latter would be that it would allow the user to define the input variables to the entire parallel block in one place (which would make the ParallelChain abstraction more powerful), without having to copy the same input variables for all child chains.
2. Any thoughts on whether it makes sense for this to be refactored in as a subcomponent of the MapReduceChain? The main reason for replacing the map component of the mapreduce by a ParallelChain would be that users can use ParallelChain for use cases other than applying the same llm for reducing a set of documents with the same prompt - they would instead be able to use multiple chains with different prompts each.
3. Any thoughts on how we would want to support multiple outputs for each child chain, i.e. how we would want to format the output of the ParallelChain? One possibility is to do a nested dict, like:
```
{
    'output_for_chain_1: {'chain_1_output_1': str, 'chain_1_output_2': str, ... },
    'output_for_chain_2: {'chain_2_output_1': str, 'chain_2_output_2': str, ... },
}
```
or flatten the keys with a delimiter, like:
```
{
    'output_for_chain_1/chain_1_output_1': str, 'output_for_chain_1/chain_1_output_2': str, ... },
    'output_for_chain_2/chain_2_output_1': str, 'output_for_chain_2/chain_2_output_2': str, ... },
}
```

**Comment by mbchang** [comment]
I have just updated the code to allow for concurrent execution. It is also possible to nest `ParallelChain`s inside other `ParallelChain`s, all executing concurrently. See documentation in the PR for an example.

**Comment by mbchang** [comment]
Hey @agola11, thanks for the comments, and thanks for introducing the async api to the LangChain library. I have rewritten the multithreading code to only use the same `asyncio` functions that have been used in the rest of the repo. I'll address some of your comments below. I also get a chance to chat with @hwchase17 on this at the F.Inc. office hours. Let me know what you guys think.

# Why `ParallelChain` is needed 
One goal of LangChain is to provide abstractions that makes it easy for users to compose LLMs together. The two main topologies for composition are composition in series and composition in parallel. These two topologies are the building blocks of building complex networks, including electronic circuits and neural networks. LangChain already has `SequentialChain` for composition in series, but we do not have an abstraction for composition in parallel, which is the problem that this pull request addresses.

There are many cases where the user might want to process the same input with multiple chains in parallel.
 - processing different chunks of a document 
 - asking different questions about the same observation (hypothesis generation)
 - grouping a set of independent chains together that operate on the same inputs

What we want is a way to abstract the independent execution of multiple related chains together - the parallel topology. This would allow us to treat such a group of chains as itself a chain that can be composed as a primitive with other chains. For example, in the docs I've given an example of how we can nest a `ParallelChain` inside another `ParallelChain`.

## The difficulties with the current async api
Ideally, the code the user writes should separate the chain network topology from how the network is executed. However, the current async api for LangChain does not yet do enough to support this. The current async API requires the user to add the async decorator all the way up to the top-level function, which prevents the user from creating nested chain networks easily. This is because it entangles the code for expressing the topology with the code for how the topology should be executed. The user may want to express a parallel topology to connect various LLMs without wanting to execute them asynchronously.

## `ParallelChain` as a solution
The goal of the `ParallelChain` is to be an abstraction of the parallel topology and is useful whether or not the child chains in the `ParallelChain` are executed concurrently. By providing an abstraction of the parallel topology, `ParallelChain` abstraction allows the user to toggle concurrency on or off for a group of chains connected in parallel, without changing the code the user needs to write.

## Updates
1. I have updated the code to remove multithreading, using only the same `asyncio` functions that have been used in the rest of the repo.
2. After talking with @hwchase17, I changed the output of the `ParallelChain` to be a nested dict:
```
{
    'output_for_chain_1: {'chain_1_output_1': str, 'chain_1_output_2': str, ... },
    'output_for_chain_2: {'chain_2_output_1': str, 'chain_2_output_2': str, ... },
}
```
3. I removed the restriction for all child chains to take the same inputs, which would allow for more flexible composition.

**Comment by fielding** [comment]
> I have found myself wanting this behavior, or perhaps it's the lack of not knowing how to achieve it exactly yet given the current code base, but when I have been internally (lol in my head) thinking of it as a "side chain"

**Comment by leo-gan** [comment]
@mbchang Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by baskaryan** [comment]
preferred way to do this is with `RunnableParallel`

**Pull request closed without merging**
