### PR TITLE
Implemented MongoDB Atlas Self-Query Retriever

### PR DESCRIPTION
**Pull request by AthulVincent**
# Description 
This PR implements Self-Query Retriever for MongoDB Atlas vector store.

I've implemented the comparators and operators that are supported by MongoDB Atlas vector store according to the section titled "Atlas Vector Search Pre-Filter" from https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-stage/. 

Namely:
```
allowed_comparators = [
      Comparator.EQ,
      Comparator.NE,
      Comparator.GT,
      Comparator.GTE,
      Comparator.LT,
      Comparator.LTE,
      Comparator.IN,
      Comparator.NIN,
  ]

"""Subset of allowed logical operators."""
allowed_operators = [
    Operator.AND,
    Operator.OR
]
```
Translations from comparators/operators to MongoDB Atlas filter operators(you can find the syntax in the "Atlas Vector Search Pre-Filter" section from the previous link) are done using the following dictionary:
```
map_dict = {
            Operator.AND: "$and",
            Operator.OR: "$or",
            Comparator.EQ: "$eq",
            Comparator.NE: "$ne",
            Comparator.GTE: "$gte",
            Comparator.LTE: "$lte",
            Comparator.LT: "$lt",
            Comparator.GT: "$gt",
            Comparator.IN: "$in",
            Comparator.NIN: "$nin",
        }
```

In visit_structured_query() the filters are passed as "pre_filter" and not "filter" as in the MongoDB link above since langchain's implementation of MongoDB atlas vector store(libs\langchain\langchain\vectorstores\mongodb_atlas.py) in _similarity_search_with_score() sets the "filter" key to have the value of the "pre_filter" argument. 
```
params["filter"] = pre_filter
```
Test cases and documentation have also been added.

# Issue
#11616 

# Dependencies
No new dependencies have been added.

# Documentation
I have created the notebook mongodb_atlas_self_query.ipynb outlining the steps to get the self-query mechanism working.

I worked closely with [@Farhan-Faisal](https://github.com/Farhan-Faisal) on this PR.

### CODE REVIEW

**Comment by AthulVincent** [comment]
@baskaryan I've added more details to the PR description. Test and linting checks seem to pass so this PR is ready for review. Happy to add more details or make changes to get this merged.

**Comment by AthulVincent** [comment]
@baskaryan I missed the import block is sorting. I have fixed it now. Thanks

**Comment by AthulVincent** [comment]
@baskaryan I am not entirely sure why, but make lint, make format returned different outputs on my windows machine compared to output on the CI system. So I ran `make lint_diff`, `make lint`, `make format`, `make test` on an Ubuntu VM to fix format, linting issue caused by this PR. The code should pass CI systems tests now. Thanks

**Review by hwchase17 — APPROVED** [review]

**Comment by hwchase17** [comment]
sorry for delay @AthulVincent - lgtm!

**Comment by AthulVincent** [comment]
@hwchase17 Thank you for taking the time to review my PR! Looking forward to making more contributions to Langchain in the future!

**Pull request merged**
