### PR TITLE
Feature/4257 enum output parser

### PR DESCRIPTION
**Pull request by JacobFV**
Feature: #4257 

Notes: Still need to add tests

### CODE REVIEW

**Comment by JacobFV** [comment]
Added tests and ready to merge

**Comment by hwchase17** [comment]
adding https://github.com/hwchase17/langchain/pull/5165 in place of this

**Comment by leo-gan** [comment]
@JacobFV Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by JacobFV** [comment]
Don't have time to finish

**Pull request closed without merging**
