### PR TITLE
Accept uuid argument when calling weaviate.from_documents

### PR DESCRIPTION
**Pull request by khajavi**
The `weaviate.from_documents` api should accept the `uuid` argument.

### CODE REVIEW

**Comment by khajavi** [comment]
It is ready for review and I need this change for the next release.

**Comment by khajavi** [comment]
@hwchase17 why did you close it?

**Comment by efriis** [comment]
Hey @khajavi ! This package is actually being moved out into its own repo by @hsm207 . Feel free to put up a PR over there, or @hsm207 may have already implemented it in the new version!

https://github.com/langchain-ai/langchain-weaviate

**Comment by hsm207** [comment]
fyi, this is already supported in the new repo. See [here](https://github.com/langchain-ai/langchain-weaviate/blob/cbd458f3ad422b8b70239206cdc73e918b41956b/tests/integration_tests/test_vectorstores.py#L730-L737) for an example.

Feel free to raise an issue for any questions/feedback

**Pull request closed without merging**
