### PR TITLE
Add `top_k` and `filter` fields to `ChatGPTPluginRetriever`

### PR DESCRIPTION
**Pull request by tasansal**
This allows to adjust the number of results to retrieve and filter documents based on metadata.

### CODE REVIEW

**Comment by tasansal** [comment]
@hwchase17 @dev2049 is there anything else I need to do for workflows to run?

**Review by dev2049 — COMMENTED** [review]
we shouldn't change these function signatures here given they're implementing abstract methods from parent class. convention so far has been to add `top_k` as instance variable (see `PineconeHybridSearchRetriever` for example). `filter` is trickier because that probably does need to be variable. @hwchase17 have we thought about updating BaseRetriever.get_relevant_documents() to support metadata filtering?

**Comment by tasansal** [comment]
@dev2049 makes sense! Didn't think about checking the ABC! I will make the top_k an instance variable as you suggested. What should I do for filtering for now? We were hoping to use it in one of the apps we are building now.

**Comment by hwchase17** [comment]
> @dev2049 makes sense! Didn't think about checking the ABC! I will make the top_k an instance variable as you suggested. What should I do for filtering for now? We were hoping to use it in one of the apps we are building now.

could you clarify the use case?

**Comment by tasansal** [comment]
> > @dev2049 makes sense! Didn't think about checking the ABC! I will make the top_k an instance variable as you suggested. What should I do for filtering for now? We were hoping to use it in one of the apps we are building now.
> 
> 
> 
> could you clarify the use case?

Sure. The ChatGPT retrieval plug-in allows you to return the top_k matches and takes it as a parameter during query time. Default is 3. The filter parameter allows you to filter queries by document metadata. Let's say you have 10-K filings for two related companies but when I ask about one specifically, I don't want the other one's matches to contaminate the results. In this case you can put some identifier in the metadata filter later. 

Here is from their readme:

The endpoint expects a list of queries in the request body, each with a query and optional filter and top_k fields. The filter field should contain a subset of the following subfields: source, source_id, document_id, url, created_at, and author.

Pinecone has this too; theirs is more flexible:

https://docs.pinecone.io/docs/metadata-filtering

**Comment by tasansal** [comment]
I'm leaning more towards making both an instance variable. What do you all think?

The caveat is, if filtering is required it would need a new instance.

**Comment by tasansal** [comment]
@hwchase17 @dev2049 I moved parameters to instance variables and now it conforms to ABC. Linter also run ok so tests should pass.

**Review by hwchase17 — APPROVED** [review]
thanks, this looks great!

**Comment by tasansal** [comment]
@hwchase17 it looks like #2859 broke my changes and messed up data models.

What happened here? What's the best way to fix it? I can just do a new PR

**Pull request merged**
