### PR TITLE
add documents of baidu bos directory and file document_loader

### PR DESCRIPTION
**Pull request by wemysschen**
**Description:**
add documents of baidu bos directory and file document_loader.

### CODE REVIEW

**Comment by wemysschen** [comment]
@baskaryan Could you please review this PR for documents of baidu bos doucment loader?

**Comment by wemysschen** [comment]
@baskaryan  Could you please review this PR for documents of baidu bos doucment loader?

**Comment by wemysschen** [comment]
@efriis  Could you please review or assign a reviewer to review this PR for documents of baidu bos document loader?

**Review by hwchase17 — COMMENTED** [review]
why is docs/api_reference/guide_imports.json changing?

**Pull request closed without merging**
