### PR TITLE
first draft

### PR DESCRIPTION
**Pull request by donaldziff**
There is a long way to go on this!

### CODE REVIEW

**Comment by hwchase17** [comment]
this is awesome @donaldziff !

how are you thinking about merging this in? im pretty fine to merge in and publicize and get others feedback... unless you wanted to try to formalize/generalize some parts?

**Comment by hwchase17** [comment]
> * If it were merged soon, would the place I chose ([docs/modules/agents/agents/wikibase_agent.ipynb](https://github.com/hwchase17/langchain/tree/master/docs/modules/agents/agents)) be the right one?

Yeah that place seems good for now!


> * I would like to formalize/generalize and write proper code like [langchain/agents/agent_toolkits/sql.](https://github.com/hwchase17/langchain/tree/master/langchain/agents/agent_toolkits/sql). But if I could get feedback sooner, that would be great. Should I enumerate some of my open questions in the notebook?

Yeah questions in notebook sounds great. My main questions are what parts are generalizable vs specific to this data?

> * What forum do you recommend for feedback? A github "discussion"? Discord? Should I invite that in the notebook?

i dont think we have a great/standardized way, so for now I would say whatever is most convinient for you

> * I am quite puzzled why the agent performs fairly predictably using davinci but becomes unpredictable using turbo or 4. It seems that those models hallucinate tool steps that are not among the possibilities I list. Do you have any ideas about that? Can this be solved by prompt engineering?

probably prompt engineering... have heard this from other ppl as well

**Comment by hwchase17** [comment]
should we merge this in? updated thoguhts?

**Comment by donaldziff** [comment]
Yes, it's ready to go! Thanks for your patience

**Comment by hwchase17** [comment]
> Yes, it's ready to go! Thanks for your patience

thank you! will share it tmrw

**Pull request merged**
