### PR TITLE
Refactor: use SecretStr for tongyi chat-model

### PR DESCRIPTION
**Pull request by chyroc**

### CODE REVIEW

**Review by leo-gan — COMMENTED** [review]
ut?

**Review by leo-gan — APPROVED** [review]
LGTM
Thanks!

**Comment by chyroc** [comment]
@hwchase17 can this merged, thanks.

**Comment by hwchase17** [comment]
there was a big refactor to tongyi, may need to be merged in

**Comment by chyroc** [comment]
@hwchase17 Sorry to bother you, can you review this PR?

**Review by hwchase17 — APPROVED** [review]
thanks!

**Pull request merged**
