### PR TITLE
ConvoOutputParser: Handle multiline Action Input + potential hallucin…

### PR DESCRIPTION
**Pull request by mkorpela**
…ated Observation

  - **Description:** Handle multiline Action Inputs.
  - **Issue:** Fixes cases where our agent made multiline Action Input (specifically contained python code)
  - **Dependencies:** --
  - **Tag maintainer:** @hwchase17
  - **Twitter handle:** All the credits to @robocorp

Note: I did not fully get where the tests should go so that is my best effort.

### CODE REVIEW

**Comment by Undertone0809** [comment]
This situation shouldn't happen, do we have a mechanism for stopping words. Can you reveal more details?

**Review by hwchase17 — COMMENTED** [review]
also had same question - why is the special handling of the observation stop word needed?

**Comment by mkorpela** [comment]
I believe I have observed hallucinated observation. It became relevant to handle it because of the multiline nature of the Action Input.

**Comment by hwchase17** [comment]
pulled in tests to https://github.com/langchain-ai/langchain/pull/15082

not handling partial printing of Observation... not sure why that would happen

**Comment by mkorpela** [comment]
Thanks! Maybe the Observation part was our changes.

**Pull request closed without merging**
