### PR TITLE
Invalid `tool_choice` being passed to `ChatLiteLLM`

### PR DESCRIPTION
**Pull request by keenborder786**
- **Description:** Invalid `tool_choice` is given to `ChatLiteLLM` to `bind_tools` due to it's parent's class default value being pass through `with_structured_output`.
- **Issue:** #28176

### CODE REVIEW

**Comment by keenborder786** [comment]
@efriis

**Comment by keenborder786** [comment]
@efriis any updates please

**Review by ccurme — COMMENTED** [review]
Issue https://github.com/langchain-ai/langchain/issues/28176 mentions that things work fine with Anthropic. I think OpenAI uses ["required"](https://platform.openai.com/docs/api-reference/chat/create#chat-create-tool_choice) instead of "any" for this purpose.

It's not clear to me that we should categorically change everything to "auto", since this makes things worse for other providers that do support "any". We might special-case specific providers like OpenAI instead.

[LiteLLM docs](https://docs.litellm.ai/docs/completion/input) also suggest that dict format should be compatible. We handle this in some other providers, could do something similar here. See for example: https://github.com/langchain-ai/langchain/blob/ec205fcee093e6bea3e8a5c36a2e81f9a3fe803b/libs/partners/openai/langchain_openai/chat_models/base.py#L1108-L1118

**Comment by keenborder786** [comment]
@ccurme I verified each of the Providers and OpenAI is the only exception for when tool_choice is `any`. Therefore I have changed my code to account for this i.e switch to `required` if the model is from OpenAI. Also if it is a bool value than in case of OpenAI it switches to `required` as well.

**Comment by keenborder786** [comment]
@ccurme  To verify that call is actually coming from OpenAI, given ChatLiteLLM I could only use `model` or `model_name`

**Comment by keenborder786** [comment]
@ccurme  does this look good to you?

**Comment by keenborder786** [comment]
@ccurme

**Comment by tvvignesh** [comment]
@ccurme Can this be reviewed and merged please if it works - I am facing the same issue as well when trying to invoke tool in OpenAI from langchain with ChatLiteLLM

**Comment by keenborder786** [comment]
@ccurme

**Review by ccurme — APPROVED** [review]

**Comment by danielbichuetti** [comment]
Hello! I wanted to let you know that this issue also appears when using VertexAI. Here’s the error message I’m getting:

`litellm.UnsupportedParamsError: VertexAI doesn't support tool_choice=any. Supported tool_choice values=['auto', 'required', json object].`

**Comment by Drummersbrother** [comment]
The list of openai models should be updated, newer model strings like `o3-mini` need the same treatment (i understand that there's not much other than this list of model strings available to check if model is from openai at the moment)

**Pull request merged**
