### PR TITLE
Return PK in similarity search Document

### PR DESCRIPTION
**Pull request by hasansustcse13**
Issue: #17390

### CODE REVIEW

**Comment by hasansustcse13** [comment]
@dosu-bot can you assign this to someone to review?

**Comment by hasansustcse13** [comment]
@eyurtsev Could you please look into this PR?

**Comment by hasansustcse13** [comment]
@efriis

**Comment by hasansustcse13** [comment]
@baskaryan Could please have a look?

**Review by yiwangdr — APPROVED** [review]

**Pull request merged**
