### PR TITLE
Update base.py

### PR DESCRIPTION
**Pull request by redreamality**
as per definition, `include_df_in_prompt` should either be true or false

### CODE REVIEW

**Review by efriis — APPROVED** [review]
Thanks @redreamality

**Review by efriis — COMMENTED** [review]
Actually will confirm this one tomorrow because #11678 implements the precise opposite of this, making me think the `is not None` could actually be the correct one.

**Comment by efriis** [comment]
Yes looks like this is a confusing implementation! If you check out `_get_single_prompt`, for example, you'll see that the existing check is intentional. Let me know if you disagree!

**Comment by redreamality** [comment]
If user specifies a suffix,  it'll be better to leave the choice to the user to decide whether to include df_head in prompt. which can actually be inferred from the suffix prompt.

In the current implementation, the user prompt without a {df_head}  will raise an unexpected error, (because you cannot set it to false).   Therefore, I draft this PR to solve this problem.


maybe in line 76,  `_get_single_prompt` function
```
    if suffix is not None:
        suffix_to_use = suffix
        include_df_head = True
```
should be changed to 

   ```
 if suffix is not None:
        suffix_to_use = suffix
        include_df_head = include_df_in_prompt

```

**Comment by efriis** [comment]
I'm not sure I follow - this PR only handled the case of `include_df_in_prompt=False` and `suffix is not None`

If you've found a different error related to `include_df_head`, maybe open an issue or PR?

**Pull request closed without merging**
