### PR TITLE
Feat: support OpenAIAssistantRunnable async

### LINKED ISSUE #15299: Cannot specify asyn clienct for OpenAIAssistantRunnable
### System Info

langchain = "^0.0.352"

@agola11 

### Who can help?

@agola11 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Specify async open ai client upon intialization

        client = openai.AsyncOpenAI()
        assistant = OpenAIAssistantRunnable(assistant_id=self.assistant_id,as_agent=as_agent,client=client)
        
        
   Produces error

pydantic.v1.errors.ConfigError: field "client" not yet prepared so type is still a ForwardRef, you might need to call OpenAIAssistantRunnable.update_forward_refs().

### Expected behavior

expect intialization to be successful

### PR DESCRIPTION
**Pull request by chyroc**
fix https://github.com/langchain-ai/langchain/issues/15299

### CODE REVIEW

**Comment by OlajideOgun** [comment]
LGTM

**Review by OlajideOgun — APPROVED** [review]

**Comment by OlajideOgun** [comment]
Would this be the correct way to use this now?
```

    async def execute_agent(agent: OpenAIAssistantRunnable, tools: List[Tool], input: Dict[Any, Any]):
        from langchain_core.agents import AgentFinish

        tool_map = {tool.name: tool for tool in tools}
        response =  await agent.ainvoke(input)
        logger.debug(f"Initial Response: {response}")

        while not isinstance(response, AgentFinish):
            tool_outputs = []
            for action in response:
                logger.debug(f"Action: {action}")

                tool_output =  await tool_map[action.tool].ainvoke(action.tool_input)
                logger.debug(f"Tool: {action.tool}, Input: {action.tool_input}, Output: {tool_output}")

                tool_outputs.append(
                    {"output": tool_output, "tool_call_id": action.tool_call_id}
                )

            response =  await agent.ainvoke(
                {
                    "tool_outputs": tool_outputs,
                    "run_id": action.run_id,
                    "thread_id": action.thread_id,
                }
            )
            logger.debug(f"Response after tool execution: {response}")

      assistant = await OpenAIAssistantRunnable.acreate_assistant(name="TAI EDUCATIONAL assistant",instructions="You are tutor.",tools=tools,model="gpt-4-1106-preview",as_agent=True)

      response = await TAIConversation.execute_agent(agent=assistant, tools = tools, input= self.assistant_input)

        logger.debug(response)



```

I dont get any error but i just gets stuck and nothing happens when running this code in a fast api async endpoint. Nothing happens even with this PR

**Review by baskaryan — APPROVED** [review]
thanks @chyroc!

**Review by baskaryan — APPROVED** [review]

**Comment by baskaryan** [comment]
thanks @chyroc!

**Pull request merged**
