### PR TITLE
langchain: Add callback support for tool calling agent

### PR DESCRIPTION
**Pull request by billpku**
Description:
This PR updates the `create_tool_calling_agent` function to support setting callbacks for each component of the agent, allowing for more granular tracing and monitoring of the agent's process using `LangSmith`.

The main changes include:
- Adding an optional `callbacks` parameter to the `create_tool_calling_agent` function
- Applying the provided callbacks to the `LLM`, `RunnablePassthrough`, and `ToolsAgentOutputParser` components
- Introducing a helper method `_apply_callbacks` to apply callbacks to a component if provided

With these changes, users can now pass a `CallbackManagerForChainRun` to the `create_tool_calling_agent` function, which will propagate the callbacks to each supported component of the agent. 

This enables more detailed tracing and monitoring of the agent's process, including LLM calls, intermediate steps, and output parsing.

Before passing the callback:
image

After passing the callback to the agent(with more detail log):
image

### CODE REVIEW

**Review by eyurtsev — CHANGES_REQUESTED** [review]
Can you pass callbacks a run time parameter?

**Comment by eyurtsev** [comment]
Here's a how-to guide https://python.langchain.com/v0.2/docs/how_to/callbacks_runtime/ for passing callbacks at run time

**Comment by billpku** [comment]
> Here's a how-to guide https://python.langchain.com/v0.2/docs/how_to/callbacks_runtime/ for passing callbacks at run time

Hi @eyurtsev,

**Thank you for your help! Your solution is more elegant and efficient.👍**

To provide more context:

- We used different `LangSmith` project names to log different agents, tools, and chains in one project.
- Previously, I set up different `callbacks` with project names for each component.
- Now, with your solution, it's more efficient. Thank you!

In case others have a similar problem and want to set different callbacks for specific agents in one project, here's an example code:
```python
import json
from typing import Any, Dict, List

from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain.callbacks.tracers import LangChainTracer
from langchain.schema import AgentAction, AgentFinish, LLMResult
from langchain_core.callbacks import BaseCallbackHandler
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder

class LoggingHandler(BaseCallbackHandler):
    def __init__(self, project_name: str):
        self.tracer = LangChainTracer(project_name=project_name)

    def on_llm_start(
        self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any
    ) -> None:
        self.tracer.on_llm_start(serialized, prompts, **kwargs)
        # The print one is for showcase, so that you can track if the LoggingHandler take effect
        print(">>>>ON LLM START")

    def on_llm_end(self, response: LLMResult, **kwargs: Any) -> None:
        self.tracer.on_llm_end(response, **kwargs)
        print(">>>>ON LLM END")

    def on_llm_error(self, error: Exception, **kwargs: Any) -> None:
        self.tracer.on_llm_error(error, **kwargs)
        print(">>>>ON LLM ERROR")

    def on_chain_start(
        self, serialized: Dict[str, Any], inputs: Dict[str, Any], **kwargs: Any
    ) -> None:
        self.tracer.on_chain_start(serialized, inputs, **kwargs)
        print(">>>>ON CHAIN START")

    def on_chain_end(self, outputs: Dict[str, Any], **kwargs: Any) -> None:
        self.tracer.on_chain_end(outputs, **kwargs)
        print(">>>>ON CHAIN END")

    def on_chain_error(self, error: Exception, **kwargs: Any) -> None:
        self.tracer.on_chain_error(error, **kwargs)
        print(">>>>ON CHAIN ERROR")

    def on_tool_start(
        self, serialized: Dict[str, Any], input_str: str, **kwargs: Any
    ) -> None:
        self.tracer.on_tool_start(serialized, input_str, **kwargs)
        print(">>>>ON TOOL START")

    def on_tool_end(self, output: str, **kwargs: Any) -> None:
        self.tracer.on_tool_end(output, **kwargs)
        print(">>>>ON TOOL END")

    def on_tool_error(self, error: Exception, **kwargs: Any) -> None:
        self.tracer.on_tool_error(error, **kwargs)
        print(">>>>ON TOOL ERROR")

    def on_text(self, text: str, **kwargs: Any) -> None:
        self.tracer.on_text(text, **kwargs)
        print(">>>>ON TEXT")

    def on_agent_action(self, action: AgentAction, **kwargs: Any) -> None:
        self.tracer.on_agent_action(action, **kwargs)
        print(">>>>ON AGENT ACTION")

    def on_agent_finish(self, finish: AgentFinish, **kwargs: Any) -> None:
        self.tracer.on_agent_finish(finish, **kwargs)
        print(">>>>ON AGENT FINISH")


class DemoAgent:
    def __init__(self, tool_store, llm_operator):
        self._tool_store = tool_store 
        self._llm_operator = llm_operator
        self._agent_prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    """You are a helpful assistant.""",
                ),
                ("human", "{input}"),
                MessagesPlaceholder("agent_scratchpad"),
            ]
        )

        self._logging_handler = LoggingHandler(project_name="YOUR_LANGSMITH_PROJECT")
        self._agent = create_tool_calling_agent(
            llm=self._llm_operator._chat_model, # e.g, the OpenAI ChatModel
            tools=self._tool_store.get_tools(), # List of Tools
            prompt=self._agent_prompt,
        )
        
        # With this setting, the whole agent's related process component will share the same callback config
        self._agent_executor = AgentExecutor(
            agent=self._agent,
            tools=self._tool_store.get_tools(),
            verbose=True,
            callbacks=[self._logging_handler],
        )

    def invoke_agent(self, query: str) -> str:
        result = self._agent_executor.invoke(
            {"input": query},
            config={"callbacks": [self._logging_handler]},
        )
        return result["output"]
   ```
   
In this example:

- The `LoggingHandler` class is defined with a constructor that takes the project_name parameter. It creates an instance of LangChainTracer with the specified project name and delegates the calls to the corresponding methods of the tracer.
- The `DemoAgent` class initializes the agent with the `LoggingHandler` instance, passing the desired LangSmith project name.
- The `invoke_agent'`method passes the LoggingHandler instance as the callbacks argument in the config parameter when invoking the agent executor.

With this setup, all the processes related to the agent will share the same callback configuration, and the logs will be sent to the specified LangSmith project.

I hope this helps others facing similar challenges! 😊

**Comment by eyurtsev** [comment]
@billpku 

You can do this to dynamically change project:

```
from langchain_core.runnables import RunnableLambda
from langchain_core.tracers.context import tracing_v2_enabled

@RunnableLambda
def foo(x: str):
    return x

with tracing_v2_enabled(project_name='project1'):
    foo.invoke('hello')

with tracing_v2_enabled(project_name='project2'):
    foo.invoke('goodbye')
```

If you want to see what's going on under the hood, you can also use set_debug(True)

```python
from langchain_core.globals import set_debug
set_debug(True)
```

**Pull request closed without merging**
