### PR TITLE
Feat: add embedding callback

### LINKED ISSUE #15253: Callbacks for embeddings
### Feature request

Similar to the way callbacks are implemented in BaseLLM the embedding class should also support callbacks.

### Motivation

When using embedding models in a RAG application it would be useful to track e.g. the number of tokens.
Callbacks can be used to log usage details to monitoring services (eg Langsmith).

### Your contribution

There is a closed PR adressing the same topic https://github.com/langchain-ai/langchain/pull/7920

### PR DESCRIPTION
**Pull request by chyroc**
copy from #7920 which closed and no updated. and fix https://github.com/langchain-ai/langchain/issues/15253 .
If this has any issues, I'll fix the code and update.
If this offends anyone I will close it immediately.

### CODE REVIEW

**Comment by chyroc** [comment]
@leo-gan can Can you help me review this PR? Thank you very much.

**Comment by hwchase17** [comment]
as a heads up, we've considered this in the past but didnt feel the ROI was high enough. not sure if enough has changed to change our position on that

**Comment by chyroc** [comment]
It seems that it can be used to implement token recording and trace recording, so that related functions such as billing, current limiting, and link tracking can be implemented.

related issues:
- https://github.com/langchain-ai/langchain/issues/15253
- https://github.com/langchain-ai/langchain/issues/11093
- https://github.com/langchain-ai/langchain/issues/8564
- https://github.com/langchain-ai/langchain/issues/8569

**Comment by lkNGAT** [comment]
Hi,
Could someone take a look at this.

**Comment by pietro1996** [comment]
Hi, I wanted to know if there is any news regarding this feature, it would be very useful

**Comment by efriis** [comment]
Hey there! Closing in same vein as harrison's comment above + lots of merge conflicts

**Pull request closed without merging**
