### PR TITLE
docs: Adding Azure Database for PostgreSQL Example Notebook

### PR DESCRIPTION
**Pull request by AbeOmor**
Thank you for contributing to LangChain!

This PR to show support for the Azure Database for PostgreSQL Vector Store and  pgVector in a Notebook

[Azure Database for PostgreSQL - Flexible Server](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/service-overview)
[Azure Database for PostgreSQL pgvector extension](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-use-pgvector)

**Description:** Added vector store and memory usage documentation for Azure Database for PostgreSQL
 **Twitter handle:** [@_aiabe](https://x.com/_aiabe)

### CODE REVIEW

**Comment by AbeOmor** [comment]
@ccurme for docs review on addition of Postgres docs for Microsoft into LangChain

**Comment by AbeOmor** [comment]
Will reopen PR. due to new commits

**Comment by AbeOmor** [comment]
Notebook is ready to merge! @ccurme

**Comment by AbeOmor** [comment]
@efriis or @ccurme. Can you please take? 
Our team @ Azure has a few customers super excited about using LangChain and Azure Postgres, however this PR has been pending review for almost 2 months.

**Comment by ccurme** [comment]
This docs page appears unusual in that the only LangChain vector store it showcases is `PGVector`, which already has its own [integration page](https://python.langchain.com/docs/integrations/vectorstores/pgvector/).

As I understand it the new content here is demonstrating how to construct a SQLAlchemy engine and/or URI for Azure Postgres. Why is the LangChain docs the right place for this?

**Comment by AbeOmor** [comment]
> This docs page appears unusual in that the only LangChain vector store it showcases is `PGVector`, which already has its own [integration page](https://python.langchain.com/docs/integrations/vectorstores/pgvector/).
> 
> As I understand it the new content here is demonstrating how to construct a SQLAlchemy engine and/or URI for Azure Postgres. Why is the LangChain docs the right place for this?

Hi @ccurme Thanks for the reply, here is our reasoning for adding Azure Postgres with PgVector to the LangChain docs.

Azure Postgres full supports the use of `PGVector` for connections and auth, hence we didn't build a specify connector for LangChain, instead we have opted to use what already exists with `PGVector` and added documentation on how you can use Langchain's PGVector with Azure Postgres.

**Why is the LangChain docs the right place for this?**
1. When reading LangChain docs our customers would like to know how to integrate LangChain with their Azure resources. This docs show them exactly how and also how to use Microsoft Entra ID (sonething that is not in the current PGVector docs)
2. Visibility - We want to make show and LangChain users opting to use Azure Postgres for their Vector Store can find the docs in the [Vectorstore integrations page](https://langchain-git-fork-abeomor-master-langchain.vercel.app/docs/integrations/vectorstores/). the only reference to the use of Azure Postgres with LangChain is buried in the [LangChain Microsoft Docs](https://python.langchain.com/docs/integrations/providers/microsoft/#azure-database-for-postgresql)

**Comment by efriis** [comment]
hey there! we probably won't add a dedicated page for this, but you're welcome to link to the azure docs from the pgvector page as an "example" host!

**Pull request closed without merging**
