### PR TITLE
Add Geopandas.GeoDataFrame Document Loader

### PR DESCRIPTION
**Pull request by brendancol**
Adds Document Loader support for [Geopandas.GeoDataFrames](https://geopandas.org/)

Example:
- [x] stub out `GeoDataFrameLoader` class
- [x] stub out integration tests
- [ ] Experiment with different geometry text representations
- [ ] Verify CRS is successfully added in metadata
- [ ] Test effectiveness of searches on geometries
- [ ] Test with different geometry types (point, line, polygon with multi-variants).
- [ ] Add documentation

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
this seems awesome! excited to get this in. happy to help in whatever way

an example notebook would be awesome (and is probably something you are better situated to do than me)

**Comment by zzsi** [comment]
@brendancol this is awesome, do you have an example use case and data in mind to demo? Happy to help put together a jupyter notebook.

**Comment by mwharton3** [comment]
I'd also love this feature! 👌

**Comment by brendancol** [comment]
@zzsi great idea.  I'm going to carve out some time this week to experiment with this document loader.

For tracking purposes:

- [ ] Add Jupyter notebook example using default geopandas datasets

**Comment by rlancemartin** [comment]
I've used Geopandas in the past and am a fan! Can help get this in.

Looks like we need a notebook.

**Comment by rlancemartin** [comment]
Added example notebook that shows how to create geopandas DF and then load it.

A use-case example showing chat over structured data that includes lat, lng would be fun.

image

**Pull request merged**
