### PR TITLE
Fix tool arguments formatting in StructuredChatAgent

### PR DESCRIPTION
**Pull request by skozlovf**
In the `FORMAT_INSTRUCTIONS` template, 4 curly braces (escaping) are used to get single curly brace after formatting:

```
"{{{ ... }}}}" -> format_instructions.format() ->  "{{ ... }}" -> template.format() -> "{ ... }".
```

Tool's `args_schema` string contains single braces `{ ... }`, and is also transformed to `{{{{ ... }}}}` form. But this is not really correct since there is only one `format()` call:

```
"{{{{ ... }}}}" -> template.format() -> "{{ ... }}".
```

As a result we get double curly braces in the prompt:
````
Respond to the human as helpfully and accurately as possible. You have access to the following tools:

foo: Test tool FOO, args: {{'tool_input': {{'type': 'string'}}}}    # <--- !!!
...
Provide only ONE action per $JSON_BLOB, as shown:

```
{
  "action": $TOOL_NAME,
  "action_input": $INPUT
}
```
````

This PR fixes curly braces escaping in the `args_schema` to have single braces in the final prompt:
````
Respond to the human as helpfully and accurately as possible. You have access to the following tools:

foo: Test tool FOO, args: {'tool_input': {'type': 'string'}}    # <--- !!!
...
Provide only ONE action per $JSON_BLOB, as shown:

```
{
  "action": $TOOL_NAME,
  "action_input": $INPUT
}
```
````

### CODE REVIEW

**Comment by skozlovf** [comment]
I also noted that there is no space between ` ``` ` and `then` in the `SUFFIX`:

```
... Format is Action:```$JSON_BLOB```then Observation:
```

I'm not sure if that was intended.

**Comment by Hackerbond1** [comment]
question: does this fixes the issue with STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION output parser where the action is not correctly parsed as:
Action: ```
            json
             ```
?
I'm trying to figure out how to correct this and I have seen several posts with similar fixed on other agents, but im still having issues. (and im not sure how to fix it either). If its of any help, im using v0.0.287

**Comment by skozlovf** [comment]
@Hackerbond1 No, I don't think so. This fix generates more consistent instructions for calling tools.

PS
`STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION` sometimes works strangely because LLM may call a tool incorrectly. Looks like LLM just doesn't understand JSON Schema well. If your args schema is `{"param": {"type": "XX"}}` then it may call as `{"param": "..."}` or `{"param": {"type": "..."}}` or `{"type": "..."}`. `OPENAI_FUNCTIONS` works better.

**Comment by skozlovf** [comment]
@baskaryan What do you think?

**Comment by skozlovf** [comment]
@hwchase17 ping

**Comment by baskaryan** [comment]
thank you @skozlovf! looks like the branch needs to be updated, happy to take over if you'd like

**Comment by skozlovf** [comment]
@baskaryan updated, check plz.

**Pull request merged**
