### PR TITLE
core: added an extra input param to RunnableWithMessageHistory

### PR DESCRIPTION
**Pull request by Abd-elr4hman**
# Description 
Added a new input argument to RunnableWithMessageHistory: extra_input_keys, the extra_input_keys will define prompt keys ignored by the get_input_schema method.
## The issue it solves
The current RunnableWithMessageHistory definition only makes use of an input key from the prompt, adds it to the input schema and ignores others. 
to illustrate:
* if I replicate the following example from [RunnableWithMessageHistory](https://python.langchain.com/v0.1/docs/expression_language/how_to/message_history/) docs :
```
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_openai.chat_models import ChatOpenAI
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_core.chat_history import BaseChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory

model = ChatOpenAI()
prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You're an assistant who's good at {ability}. Respond in 20 words or fewer",
        ),
        MessagesPlaceholder(variable_name="history"),
        ("human", "{input}"),
    ]
)
runnable = prompt | model

store = {}

def get_session_history(session_id: str) -> BaseChatMessageHistory:
    if session_id not in store:
        store[session_id] = ChatMessageHistory()
    return store[session_id]


with_message_history = RunnableWithMessageHistory(
    runnable,
    get_session_history,
    input_messages_key="input",
    history_messages_key="history",
)
```
and then run
```
with_message_history.get_input_schema().schema_json()
```
I get the following output
```
{
  "title": "RunnableWithChatHistoryInput",
  "type": "object",
  "properties": {
    "input": {
      "title": "Input",
      "anyOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/definitions/BaseMessage"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BaseMessage"
          }
        }
      ]
    }
  },...
```
**With only one property(input)** on the input schema, **despite the prompt containing others (ability)**

## Further issue with langserve
when I try to use RunnableWithMessageHistory with langserve in the example below
```
from pydantic.v1 import BaseModel
from fastapi import FastAPI
from fastapi.responses import RedirectResponse
from langserve import add_routes
from chain import with_message_history

app = FastAPI()

@app.get("/")
async def redirect_root_to_docs():
    return RedirectResponse("/docs")

# Edit this to add the chain you want to add
add_routes(app, with_message_history)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
```
The fastapi docs shows the input schema without "ability" in the example above
Screenshot 2024-08-26 at 6 16 18 PM

## Functionality with the added param extra_input_keys:
After adding the param above I can specify "ability" by passing a list of strings (keys in the prompt templates) for the RunnableWithMessageHistory to include in input schema

 * If I replicate the same example from [RunnableWithMessageHistory](https://python.langchain.com/v0.1/docs/expression_language/how_to/message_history/) docs above:
```
with_message_history = RunnableWithMessageHistory(
    runnable,
    get_session_history,
    input_messages_key="input",
    history_messages_key="history",
    extra_input_keys=["ability"]
)
``` 
I get the follwoing ouput:
```
{
  "title": "RunnableWithChatHistoryInput",
  "type": "object",
  "properties": {
    "input": {
      "title": "Input",
      "anyOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/definitions/BaseMessage"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BaseMessage"
          }
        }
      ]
    },
    "ability": {
      "title": "Ability",
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      ]
    }
  },...
```
I now get both input and ability in the input schema, And I am able to use langserve with no issues.

  - **Issue:** #24370 
  - **Discussions:** 
  #22468 
  #22464

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Comment by hwchase17** [comment]
this is a great write up and good issue to identify. can we resolve more automatically though? eg can we infer other inputs from the underlying schema?

would be helfpul to write unit tests for this as well so we can test different approaches

**Comment by Abd-elr4hman** [comment]
Will try to infer the inputs without the need for an extra param.

**Comment by hwchase17** [comment]
still too prompt specific i think

also should have unit tests

**Comment by Abd-elr4hman** [comment]
Yes! I found this example [here](https://github.com/langchain-ai/langchain/discussions/16582#discussioncomment-8248587) of using retrieval with history... 

The input schema on chain looks like this:
```
{
  "title":"RunnableSequenceInput",
  "type":"object",
  "properties":{
    "ability":{
      "title":"Ability",
      "type":"string"
      },
    "history":{
      "title":"History",
      "type":"array",
      "items":{}
      },
    "question":{
      "title":"Question",
      "type":"string"
      }
 },
```

My latest commit would result in the output:
```
{
  "title": "RunnableWithChatHistoryInput",
  "type": "object",
  "properties": {
    "question": {
      "title": "Question",
      "anyOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/definitions/BaseMessage"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BaseMessage"
          }
        }
      ]
    },
    "ability": {
      "title": "Ability",
      "type": "string"
    },
    "context": {
      "title": "Context",
      "type": "string"
    }
  },...
```
which is incorrect...

The inputs should be inferred from the input schema directly.

**Comment by Abd-elr4hman** [comment]
would love to get feedback on the current changes in this pr. Do you think I can further improve this code?

**Comment by eyurtsev** [comment]
@Abd-elr4hman  Apologies for the delay. The timing for the PR landed exactly during the release of langchain 0.3.0 which involved upgrading to pydantic 2 internally. `get_input_schema` has been updated for this release, so you'll likely need to re-merge your changes.

I think the approach in the PR is good. If you're interested in fixing this, you could continue in this PR (and resolve merge conflicts) or open another PR  can open another PR, the following things need to be done:

1. Use a private attribute instead of a public attribute and wrap the underlying Runnable.

```
history_messages_key: Optional[str] = None
history_factory_config: Sequence[ConfigurableFieldSpec]
_underlying_runnable: Runnable
```

2. get_input_schema will look something like this:

```    def get_input_schema(
        self, config: Optional[RunnableConfig] = None
    ) -> type[BaseModel]:
        from langchain_core.messages import BaseMessage

        fields: dict = {}
        if self.input_messages_key and self.history_messages_key:
            fields[self.input_messages_key] = (
                Union[str, BaseMessage, Sequence[BaseMessage]],
                ...,
            )
        elif self.input_messages_key:
            fields[self.input_messages_key] = (Sequence[BaseMessage], ...)
        else:
            return create_model_v2(
                "RunnableWithChatHistoryInput",
                module_name=self.__class__.__module__,
                root=(Sequence[BaseMessage], ...),
            )

        underlying_input_schema = self._underlying_runnable.get_input_schema()
        # Need to figure out what to do here w/ respect to RootModel vs non Root model
        if issubclass(underlying_input_schema, RootModel):
            schema_to_use = underlying_input_schema.root
        else:
            schema_to_use = underlying_input_schema

        if issubclass(schema_to_use, BaseModel):
            for (
                field_name,
                field_info,
            ) in schema_to_use.model_fields.items():
                if field_info.is_required():
                    fields[field_name] = (field_info.annotation, ...)
                else:
                    if field_info.default is not PydanticUndefined:
                        fields[field_name] = (field_info.annotation, field_info.default)
                    else:  # Default factory
                        # We'll skip supporting this for now
                        continue

        return create_model_v2(  # type: ignore[call-overload]
            "RunnableWithChatHistoryInput",
            field_definitions=fields,
            module_name=self.__class__.__module__,
        )

```

3. Resolve the kinks above with `RootModel` (you should see that some unit-tests fail) and or have schema that doesn't make sense. I'd recommend replacing 

```python
    assert _schema(with_history.get_input_schema()) == _schema(...)
```

with

```python
    assert _schema(with_history.get_input_schema()) == {}  #<-- the actual expected JSON Schema
```

to make sure that the inputs are as expected. 

We'd definitely want to preserve the types for the inputs (in the original PR all the types were marked as strings, which is something that we'd need to address)

**Review by eyurtsev — CHANGES_REQUESTED** [review]
General approach is OK, but we need to preserve the types of the various inputs if we want to get the correct input schema.

**Comment by Abd-elr4hman** [comment]
@eyurtsev  will try to make use of the changes you provided to merge this...

currently I am faced with this issue:
https://github.com/langchain-ai/langchain/issues/27283

it might be helpful to clear it first to continue this pr as it relates to how RunnableWithMessageHistory will deal with RootModel schemas

**Pull request closed without merging**
