### PR TITLE
Allow disablling `safe_len_embeddings`(OpenAIEmbeddings)

### PR DESCRIPTION
**Pull request by mokeyish**
For servers compatible with OpenAI API may not support `safe_len_embedding`.

With this PR, we can add `disable_safe_len_embeddings=True` to `OpenAIEmbeddings(...)` to disable using `safe_len_embedding`.

### CODE REVIEW

**Comment by mokeyish** [comment]
@baskaryan, @eyurtsev, @hwchase17 Hi, please review this PR.

**Comment by mokeyish** [comment]
@baskaryan, @eyurtsev, @hwchase17 Hi, is this ready to merge?

**Comment by mokeyish** [comment]
@baskaryan Could you merge this PR? Without this PR, my application would report an error, forcing me to maintain a separate langchain branch myself.

**Comment by chiragjn** [comment]
+1 on this
This might need some refactoring to embed in batches but other than that I need this feature too

**Comment by mokeyish** [comment]
moving to here https://github.com/langchain-ai/langchain/pull/19743

**Pull request closed without merging**
