### PR TITLE
Create ChatEverlyAI

### PR DESCRIPTION
**Pull request by david-huge**
- Description: Adds the ChatEverlyAI class with llama-2 7b  on [EverlyAI Hosted
Endpoints](https://everlyai.xyz/)
- It inherits from ChatOpenAI and requires openai (probably unnecessary
but it made for a quick and easy implementation)

### CODE REVIEW

**Comment by efriis** [comment]
Hey @david-huge ! Is this something people can generally use? When I tried to test it, the app just brings me to a google form

**Comment by david-huge** [comment]
Hi @efriis, thanks a lot for the quick review. I have updated the pull request to include a colab.

To use hosted endpoints, you would only need to create an api key in the account settings. Could you help verify if you are able to access that? We will give each new users ~3M free tokens very soon. So I would suggest you try with the free credit :)

You onnly need to create a project if you want to host your own model. Since we are receiving many new users, we have to accept them gradually. Therefore the waitlist Google form.

Thanks
David

**Comment by efriis** [comment]
Sounds good @david-huge - I'll wait for that and re-review!

In the meantime, I would recommend adding some error logic for the format of everly errors, which don't match the openai ones (when the Balance too low one comes back, the openai handler gets tripped up and returns KeyError("choices")).

**Comment by david-huge** [comment]
Hi @efriis We give every new users 8M free tokens now. Please help take a look. (You may need to use a different account though.)

**Pull request merged**
