### PR TITLE
Eden AI (LLM + embeddings) integration

### PR DESCRIPTION
**Pull request by SamyMe**
# Eden AI - Integration

This PR adds [EdenAI](https://edenai.co) as an LLM and Embeddings provider. 
Eden AI is a Meta API regrouping all the best AI APIs in the market (Amazon, Open AI, Cohere, Google, Anthropic, DeepL, AssemblyAI  ...etc) into one. Users can access all the AI tasks you need with a single account giving them total freedom switch between providers and combine them.

This allows langchain users to :
 💪 Increase Accuracy & Reduce Cost by choosing the right AI API for each AI task
 ☮️ Gain peace of mind with centralized usage restrictions & cost monitoring 
 🌐 Continually explore emerging AI capabilities in the market
 
Here is an example of how it's called:

```python
from langchain.llms import EdenAI

llm = EdenAI( edenai_api_key="...",
            provider="openai", 
            params={"temperature" : 0.2,"max_tokens" : 250})
```

It can also be used for text2image : 

```python
imagemodel = EdenAI( feature="image" ,   provider= "stabilityai",  
                                       params={  "resolution" : "512x512"  })

```

 A detailed notebook was added.
 
 No dependencies are added as we call a rest API.
 
**Upcoming** : This PR starts by adding the LLM and Embeddings capabilities and will be followed by a utilities PR to give agents new capabilities like : explicit content detection (image, texts and videos), speech to text and text to speech, pdf parsing (invoice, ID, resume...etc ) and a lot of other tasks (+50) from top AI APIs providers.
 
 
Ping: @hwchase17, @baskaryan

### CODE REVIEW

**Comment by baskaryan** [comment]
looking pretty good! happy to take over and land if you'd like

**Comment by SamyMe** [comment]
Oh great! Thank you @baskaryan !:)

**Comment by baskaryan** [comment]
landed #8670, thank you all!!

**Comment by SamyMe** [comment]
Incredible responsiveness ! Thanks a lot @baskaryan.

**Pull request closed without merging**
