### PR TITLE
community: replace it with Tencent Cloud SDK

### PR DESCRIPTION
**Pull request by yanchunan**
Description: The old method will be discontinued; use the official SDK for more model options.
Issue: None
Dependencies: None
Twitter handle: None

### CODE REVIEW

**Comment by yanchunan** [comment]
Hi @eyurtsev I'm sorry to bother you, but how can I merge this PR?

**Comment by eyurtsev** [comment]
@yanchunan could you share the a URL to the relevant API documentation

**Comment by yanchunan** [comment]
> @yanchunan could you share the a URL to the relevant API documentation

Currently, only Chinese documentation is provided. 
The API documentation is https://cloud.tencent.com/document/product/1729/105701, 
and the SDK is https://github.com/TencentCloud/tencentcloud-sdk-python/tree/master/tencentcloud/hunyuan

**Comment by wxg0103** [comment]
Your submission will be of great help to me. I hope it can be merged as soon as possible. Of course, if you can provide a complete example, I will be very grateful.

**Comment by wxg0103** [comment]
By the way, is there no embedding that supports the hunyuan model?

**Comment by yanchunan** [comment]
> By the way, is there no embedding that supports the hunyuan model?

It hasn't been provided yet, but more features will be added gradually in the future.

**Comment by wxg0103** [comment]
@baskaryan, @efriis, @eyurtsev, @ccurme, @vbarda, @hwchase17 Could you guys help me to review this PR?
Thanks

**Review by ccurme — COMMENTED** [review]
Could you confirm that you've run the integration tests and they pass? (Langchain CI does not run integration tests for community integrations.)

Does the documentation [here](https://python.langchain.com/v0.2/docs/integrations/chat/tencent_hunyuan/) need to be updated at all? Notebook is here: https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/chat/tencent_hunyuan.ipynb

**Comment by yanchunan** [comment]
> integration
@ccurme 
Yes, all the integration tests have passed. 
image
This update is compatible with older versions, so the documentation does not need to be updated.

**Review by ccurme — APPROVED** [review]

**Pull request merged**
