### PR TITLE
similarity search by vector chroma

### PR DESCRIPTION
**Pull request by claust**
This is an implementation of the similarity search by vector in Chroma, as referenced in #1450.

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
can we change `similarity_search_with_score` to call this method now? to avoid duplicated code

**Comment by claust** [comment]
> can we change `similarity_search_with_score` to call this method now? to avoid duplicated code

Hmm, the `similarity_search_with_score`  needs the scores, which are not returned by the `similarity_search_by_vector`, at least not with its current signature. Also, the `filter` argument of `similarity_search_with_score` is not present in `similarity_search_by_vector` so it would have to taken from `kwargs`?
I have instead extracted the mapping of the query result to documents and scores, so this is no longer duplicated.  Does this make sense?

**Comment by hwchase17** [comment]
huh what happened to the merge conflicts here?

**Comment by claust** [comment]
This PR is replaced by #1568 to fix my mistaken commits resulting in merge commits, sorry.

**Pull request closed without merging**
