### PR TITLE
docs: hide `More/Changelog` menu item

### PR DESCRIPTION
**Pull request by leo-gan**
The `Changelog` page is not supported. It is confusing to show this page to users.

### CODE REVIEW

**Comment by leo-gan** [comment]
Close temporarily till the dependency rules are clear.

**Comment by eyurtsev** [comment]
image

**Comment by eyurtsev** [comment]
We should probably fix the change log page instead -- it already has content right now and hiding it will break existing links.

Link breaking is something we want to avoid as much as possible

**Comment by eyurtsev** [comment]
I suspect that we want to create an issue for this and get CI to start populating the page cc @efriis

**Comment by leo-gan** [comment]
@eyurtsev Not sure we need it here. All this information is free on [GitHub](https://github.com/langchain-ai/langchain/pulse).
Anyway, if we create it it should be something with different goals than the GitHub info.

**Comment by eyurtsev** [comment]
Some GitHub features don't work well for mono repo architecture. I'll let others weigh in -- my suspicion is that a dedicated page will produce a better UI than what GitHub can do right now

**Comment by leo-gan** [comment]
@eyurtsev I agree. 
Returning back to the problem of hiding the outdated page. The **manual** generation is not feasible for the Changelog, 100%. If we don't have automatic generation, we'd rather hide it. It is confusing.

**Comment by leo-gan** [comment]
stalled

**Comment by leo-gan** [comment]
@hwchase17  The Changelog page is not supported. We don't need `stalled` items in documentation.

**Comment by eyurtsev** [comment]
I think this was addressed during Jacob's refactor

**Comment by leo-gan** [comment]
@eyurtsev Thanks!

**Pull request closed without merging**
