### PR TITLE
feat: Add Notion database document loader

### PR DESCRIPTION
**Pull request by sbusso**
This PR adds Notion DB loader for langchain. 

It reads content from pages within a Notion Database. It uses the Notion API to query the database and read the pages. It also reads the metadata from the pages and stores it in the Document object.

### CODE REVIEW

**Comment by sbusso** [comment]
# NotionDBLoader

`NotionDBLoader` is a Python class for loading content from a Notion database. It retrieves pages from the database, reads their content, and returns a list of `Document` objects.

## Requirements

- A Notion Database
- Notion Integration Token

## Setup

### 1. Create a Notion Table Database

Create a new table database in Notion. You can add any column to the database and they will be treated as metadata. For example you can add the following columns:

- Title: set Title as the default property.
- Categories: A Multi-select property to store categories associated with the page.
- Keywords: A Multi-select property to store keywords associated with the page.

Add your content to the body of each page in the database. The NotionDBLoader will extract the content and metadata from these pages.

### 2. Create a Notion Integration

To create a Notion Integration, follow these steps:

1. Visit the (Notion Developers)[https://www.notion.com/my-integrations] page and log in with your Notion account.
2. Click on the "+ New integration" button.
3. Give your integration a name and choose the workspace where your database is located.
4. elect the require capabilities, this extension only need the `Read content` capability
5. Click the "Submit" button to create the integration.

Once the integration is created, you'll be provided with an `Integration Token` (API key). Copy this token and keep it safe, as you'll need it to use the NotionDBLoader.

### 3. Connect the Integration to the Database

To connect your integration to the database, follow these steps:

1. Open your database in Notion.
2. Click on the three-dot menu icon in the top right corner of the database view.
3. Click on the "+ New integration" button.
4. Find your integration, you may need to start typing its name in the search box.
5. Click on the "Connect" button to connect the integration to the database.

### 4. Get the Database ID

To get the database ID, follow these steps:

1. Open your database in Notion.
2. Click on the three-dot menu icon in the top right corner of the database view.
3. Select "Copy link" from the menu to copy the database URL to your clipboard.
4. The database ID is the long string of alphanumeric characters found in the URL. It typically looks like this: https://www.notion.so/username/8935f9d140a04f95a872520c4f123456?v=.... In this example, the database ID is 8935f9d140a04f95a872520c4f123456.

With the database properly set up and the integration token and database ID in hand, you can now use the NotionDBLoader code to load content and metadata from your Notion database.

## Usage

NotionDBLoader is part of the `langchain` package's document loaders. You can use it as follows:

```python
from langchain.docstore.document import Document
from langchain.document_loaders import NotionDBLoader

integration_token = "your_notion_api_key"
database_id = "your_notion_database_id"
loader = NotionDBLoader(integration_token, database_id)
docs = loader.load()
```

**Comment by sbusso** [comment]
@hwchase17 where is it best to add the setup instructions?

**Comment by hwchase17** [comment]
i would add a notebook showing how to use this, and put the instructions there!

since there are such detailed instructions in the pr description, i can also do it

**Comment by sbusso** [comment]
A notebook sounds good, I will add one and fix the linting issues

**Comment by sbusso** [comment]
@hwchase17, notebook added and lint errors fixed

**Review by hwchase17 — APPROVED** [review]
awesome! thanks so much - this is great and much appreciated :)

**Comment by kermankohli** [comment]
Getting timeout errors while using this. Any ideas? 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.notion.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kermankohli/dev/langchain-fun-2/main.py", line 7, in <module>
    docs = loader.load()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/document_loaders/notiondb.py", line 46, in load
    return list(self.load_page(page_id) for page_id in page_ids)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/document_loaders/notiondb.py", line 46, in <genexpr>
    return list(self.load_page(page_id) for page_id in page_ids)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/document_loaders/notiondb.py", line 74, in load_page
    data = self._request(PAGE_URL.format(page_id=page_id))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/document_loaders/notiondb.py", line 144, in _request
    res = requests.request(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.notion.com', port=443): Read timed out. (read timeout=10)
```

Thinking it might be you need to paginate through the API or something but thought I'd ask in case I'm the only one running into these issues

**Comment by dakipro** [comment]
This is very much appreciated. May I ask what would man do now with documents created by this loader?
I got up to here so far :) 

``` 
NOTION_TOKEN = getpass()
DATABASE_ID = getpass()

loader = NotionDBLoader(NOTION_TOKEN, DATABASE_ID)
docs = loader.load()
```
what now?

**Comment by jacobSingh** [comment]
I tried this.  Ran into an issue when trying to load the metadata into chromadb.  Tags is a list and that won't work for chroma (at least).

**Comment by jacobSingh** [comment]
Okay, ran into a few issues here.  One is around handling of metadata.  The code has cases for multi-select, richtext and title.... but there are several other built-in types - plus the default vector store for langchain (chromadb) doesn't handle things stored as List or None... so this makes it very hard to get started with.  I fixed a few things and added a fallback str conversion for all scalars... I can submit a PR for the same.

However, I'm also hitting timeouts regularly touching the API.  For this to be really usable, we'll need to support idempotency and some kind of retry mechanism.

I'm not sure I've got the time to work on it TBH, but leaving here for some other poor soul if they decide to.   The Directory exporter does the job more or less and could be edited to support metadata from the csv export, but of course it doesn't provide real-time updates.

**Comment by sbusso** [comment]
Thanks @jacobSingh, for sharing your experience. I will look at the metadata issue if I find the time. I can't find a reference on Chromadb as the default vector store, but I see metadata handled by `Optional[List[dict]]` in wrappers. 

How big is your notion database? I haven't encountered a time-out yet and will be interested in reproducing it.

**Comment by jacobSingh** [comment]
350 nodes. Lots if properties and blocks. I found in my case the magic
number was 60 nodes at a time. Manually paginated by overriding the number
of docs to process in one go and got them all in.

**Comment by sbusso** [comment]
note for the thread, Notion has requests limits and needs to handle retry https://developers.notion.com/reference/request-limits

**Pull request merged**
