### PR TITLE
Add memory to sql chain

### PR DESCRIPTION
**Pull request by keenborder786**
continuation of PR #8550

@hwchase17 please see and merge. And also close the PR #8550.

### CODE REVIEW

**Comment by keenborder786** [comment]
@hwchase17 please merge

**Comment by keenborder786** [comment]
@hwchase17 please merge

**Comment by keenborder786** [comment]
@hwchase17 please merge, I really need this.

**Comment by lior-mintapp** [comment]
I need this :)

**Comment by vitaly-fundcount** [comment]
Hello everyone. Any chance to get it merged into the upstream? 🙏

**Comment by leo-gan** [comment]
@baskaryan Could you, please, review it?

**Review by efriis — APPROVED** [review]

**Review by efriis — COMMENTED** [review]
sorry for the delay - just looking at the docs updates on this actually!

**Comment by umamaheswareada550** [comment]
I need this

**Review by efriis — APPROVED** [review]

**Comment by efriis** [comment]
Thanks @keenborder786 !

**Comment by claraisrael** [comment]
does this work with SQL Agent? or just with SQL Chain?

**Pull request merged**
