### PR TITLE
community: Add llm-extraction option to FireCrawl Document Loader

### PR DESCRIPTION
**Pull request by shivendrasoni**
**Description:** This minor PR aims to add `llm_extraction` to Firecrawl loader.  This feature is supported on API and PythonSDK, but the langchain loader omits adding this to the response.
**Twitter handle:** [scalable_pizza](https://x.com/scalablepizza)

### CODE REVIEW

**Review by ccurme — COMMENTED** [review]
Thanks for this. `llm_extraction` is not an attribute of [Document](https://api.python.langchain.com/en/latest/documents/langchain_core.documents.base.Document.html). Was the intent here to store `doc.get("llm_extraction")` in the document metadata?

**Comment by shivendrasoni** [comment]
> Thanks for this. `llm_extraction` is not an attribute of [Document](https://api.python.langchain.com/en/latest/documents/langchain_core.documents.base.Document.html). Was the intent here to store `doc.get("llm_extraction")` in the document metadata?

Hi, yes and I realized it just now. I am just thinking going by the API response schema `llm_extraction`, should be parallel to the page_content, but I realized that even thought Document allows kwargs, it isn't getting set for this arbitrary param.

Do you think saving it in meta is semantically correct?

**Comment by ccurme** [comment]
Is `llm_extraction` serializable? Do you have an example? Document metadata isn't very opinionated and there aren't many constraints on it. If it's useful metadata about the document and is serializable then makes sense to me.

**Comment by shivendrasoni** [comment]
> Is `llm_extraction` serializable? Do you have an example? Document metadata isn't very opinionated and there aren't many constraints on it. If it's useful metadata about the document and is serializable then makes sense to me.

Hi, yes, llm_extraction is serializable since it is always guaranteed to be a valid json object.

**Review by ccurme — APPROVED** [review]

**Pull request merged**
