### PR TITLE
Templates/rag lancedb

### PR DESCRIPTION
**Pull request by akashAD98**
added template code for lancedb

### CODE REVIEW

**Comment by akashAD98** [comment]
regarding testing 
cd templates/rag-lancedb

added openai-api key inside chain.py
```
openai_api_key='sHx')
```

then runned 
```
langchain template serve
```


& im getting below error

```
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/akash/anaconda3/lib/python3.11/site-packages/langchain_cli/dev_scripts.py", line 26, in create_demo_server
    mod = __import__(package["module"], fromlist=[package["attr"]])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'rag_pinecone'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/akash/anaconda3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/akash/anaconda3/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/akash/anaconda3/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/akash/anaconda3/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/akash/anaconda3/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/akash/anaconda3/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = self.loaded_app()
                      ^^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/lib/python3.11/site-packages/langchain_cli/dev_scripts.py", line 43, in create_demo_server_configurable
    return create_demo_server(config_keys=["configurable"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/lib/python3.11/site-packages/langchain_cli/dev_scripts.py", line 37, in create_demo_server
    raise ImportError("Could not import module defined in pyproject.toml") from e
ImportError: Could not import module defined in pyproject.toml

```


here i tried pinecone code & my lanced c ode getting same error.




please let me knoiw how can i test it & also i tested it on collab its working fine
image

**Comment by efriis** [comment]
Hey @akashAD98 ! These templates are a bit different than notebooks. They have some unique requirements about their format outlined [here](https://github.com/langchain-ai/langchain/blob/master/templates/docs/CONTRIBUTING.md).

In this particular case, you're testing with the old `.run` interface, which LangServe doesn't use (it uses the new LCEL `.ainvoke` `.astream` and `abatch` instead).

Would you prefer to upload this as an example notebook as part of the LanceDB docs at https://python.langchain.com/docs/integrations/vectorstores/lancedb ?

For support getting LangServe/templates set up to be able to test your PRs, discord is probably the best forum! If you get set up, happy to take another look. Otherwise, I'll probably close this PR because it won't work for users :(

**Comment by akashAD98** [comment]
@efriis i dont know i saw all other implementation & they are following same structure 

i tried to do the same using this https://github.com/langchain-ai/langchain/blob/master/templates/docs/CONTRIBUTING.md
& updated my code in chain.py

my lancedb rag has similar strture like rag-chroma
https://github.com/langchain-ai/langchain/tree/master/templates/rag-chroma

this is 3rd time you closed my pr ,it would be great if you can add support for lancedb from your end or please guide me to do it . thanks a lot

**Comment by akashAD98** [comment]
@efriis i want to add support for this please help me i saw lots of other db are already there

**Comment by akashAD98** [comment]
@efriis also tell me where i need to add opeani key?
templates/.env & add openai_api_key there or insdie the rag-chroma/.env ?
tried both still getting same error

image

please help me for this issue

**Comment by efriis** [comment]
Hey @akashAD98 ! Discord is your best bet for getting help with these issues. On the environment variable, you can try `export OPENAI_API_KEY=...` before starting the server.

**Comment by efriis** [comment]
https://discord.gg/cU2adEyC7w

**Comment by akashAD98** [comment]
@efriis im also getting same json issue. its issue related to langchain i guess

**Comment by akashAD98** [comment]
@efriis no response in Discord also. :(

**Pull request closed without merging**
