### PR TITLE
Virtual column name for self-querying retrievers

### PR DESCRIPTION
**Pull request by mpskex**
Self query retrievers are powerful and it can be even stronger than before. Taking MyScale as an example, sometimes the user may add complex SQL function to a column name. So we add a `VirtualColumnName` for self-query retriever to reduce token usage with extra functionality.

1. a function that dynamically creates function mapped column names, which becomes handy when the user want to compare between current time / location or other attributes along with a column.
2. complex function call in plain string can now be replaced with a shorter nickname in prompt, which saves number of token for very long function names.
3. refined the logic in MyScale translator to meet this standard.

This change will not affect other self query retrievers as it preserves the original plain string interface under comparison. The actual difference happens under `QueryTransformer` in `query_construct.parser` for `Lark` parser.

`Comparator.attribute` can now be either a string or a `VirtualColumnName`. I have defined the default behaviour which stops the user to use `VirtualColumnName` under other vectorstores than MyScale.

This functionality will boost the self-query retrievers as a bridge between text and simple SQL query. And we believe this will help users to expand their usage to this retriever. Other SQL vector database is theoretically compatible to this new feature as well.

Hope you find this interesting.
@hwchase17  @baskaryan 

Our contact on twitter: @MyScaleDB @mpsk_liu

### CODE REVIEW

**Comment by baskaryan** [comment]
thanks for the pr @mpskex! just to make sure i'm understanding correctly, the main purpose of this is to decouple the actual attribute name from the attribute name passed into the prompt, correct?

**Comment by mpskex** [comment]
> thanks for the pr @mpskex! just to make sure i'm understanding correctly, the main purpose of this is to decouple the actual attribute name from the attribute name passed into the prompt, correct?

Exactly.

**Comment by mpskex** [comment]
We updated implementations for every self-querying retrievers. Including:
- `Pinecone`
- `Chroma`
- `DashVector`
- `Weaviate`
- `Vectara`
- `Qdrant`
- `DeepLake`
- `ElasticsearchStore`
- `Milvus`
- `SupabaseVectorStore`

Now all self-querying retrievers are capable of having nicknames for columns and full name in column. This isolates the data schema and prompting.

**Comment by chtlp** [comment]
Hi @baskaryan, our customers on AWS are needing this feature to handle complex column names. Would you review and merge this feature into the main branch? It will quite useful in many real-world cases.

**Comment by mpskex** [comment]
To be honest, we have been using this PR for 3 months for [ChatData](https://github.com/myscale/ChatData) and some of our clients have been using this from our preview branch. I would love to see it inside LangChain's master as it will help many more developers to build their apps with more possibilities.

I also mentioned this PR at #5799. It seems we can expand SQL-based retrievers into a new level with this virtual column name! I think not only us, but also PostgreSQL and other SQL based knowledge bases are also interested in this feature. 

We would like to have close relationship to LangChain, and therefore, we contributed features like bringing more data types into LangChain self querying retrievers. We also thought LangChain is a such open platform as it was advertised and now we still believe in it. Hope we can make things happened, across different tries we made to keep in touch and stay connected.

All the best,

MyScale AI Team

**Review by efriis — COMMENTED** [review]
Hey team! Sorry for the delay on this one. In order to be mergable, this PR needs to be trimmed down in a way that only implements this for MyScale and won't change any of the general business logic.

That being said, virtual column names seem valuable and worth exploring a bit more for the general case! I'll play a bit with ways we can recommend formatting column names like this using LCEL, which is likely preferable as a general case (easier to understand than the VirtualColumnName class here).

That being said, if you need this for your MyScale integration, I would recommend making it a new optional kwarg on myscale's `from_components` that wouldn't modify behavior for existing implementations.

Is that something you'd want to pursue, or would you prefer to chat about ways you could get the same effect with an LCEL chain?

**Comment by mpskex** [comment]
I will start a new PR for this. Closing the current one to avoid duplication.

**Pull request closed without merging**
