### PR TITLE
community: Adds Llamafile as an LLM

### PR DESCRIPTION
**Pull request by k8si**
* **Description:** Adds a simple LLM implementation for interacting with [llamafile](https://github.com/Mozilla-Ocho/llamafile)-based models. 
* **Dependencies:** N/A
* **Issue:** N/A

**Detail**
[llamafile](https://github.com/Mozilla-Ocho/llamafile) lets you run LLMs locally from a single file on most computers without installing any dependencies.

To use the llamafile LLM implementation, the user needs to:

1. Download a llamafile e.g. https://huggingface.co/jartine/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/TinyLlama-1.1B-Chat-v1.0.Q5_K_M.llamafile?download=true
2. Make the file executable.
3. Run the llamafile in 'server mode'. (All llamafiles come packaged with a lightweight server; by default, the server listens at `http://localhost:8080`.)

```bash
wget https://url/of/model.llamafile
chmod +x model.llamafile
./model.llamafile --server --nobrowser
```

Now, the user can invoke the LLM via the LangChain client:

```python
from langchain_community.llms.llamafile import Llamafile

llm = Llamafile()

llm.invoke("Tell me a joke.")
```

### CODE REVIEW

**Review by baskaryan — APPROVED** [review]
looks awesome, thank you @k8si!

**Comment by baskaryan** [comment]
believe CI issue was caused in master and is unrelated to this pr. Should be fixed, if you merge in master and push should pass all CI

**Comment by vlasvlasvlas** [comment]
this is amazing i was looking forward for this. thanks a lot!

**Comment by vlasvlasvlas** [comment]
sorry,how about llamafile setup config? like temperature,etc?

**Pull request merged**
