### PR TITLE
Adds vocode callback handler

### PR DESCRIPTION
**Pull request by ajar98**
[Vocode](https://github.com/vocodedev/vocode-python) provides a unified interface to many different TTS providers - this PR allows Langchain interactions to speak via a CallbackHandler.

Adds `VocodeCallbackHandler` with two helper methods: `speak` and `speak_in_thread`:

Params:
- `synthesizer: BaseSynthesizer`, which is the vocode abstraction of the TTS provider that will push audio to the output device - supports Azure, ElevenLabs, Play.ht, Rime, Google, gTTS
- `output_device: Optional[BaseOutputDevice]`, a vocode abstraction that knows how to play audio - when not passed in, uses the default speaker on the user's computer

Users can subclass `VocodeCallbackHandler` and set up how they'd like to hear the progress of the LLM / chain / agent:

```python
from langchain.callbacks.vocode_callback import VocodeCallbackHandler
from langchain.chat_models import ChatOpenAI
from langchain.schema import HumanMessage
from typing import Any, Dict, List, Optional, Union
from uuid import UUID
from vocode.turn_based.synthesizer.gtts_synthesizer import GTTSSynthesizer

class MySpeakingCallbackHandler(VocodeCallbackHandler):
    def on_llm_start(self, *args, **kwargs: Any) -> Any:
        self.speak_in_thread("Starting LLM")

# To enable streaming, we pass in `streaming=True` to the ChatModel constructor
# Additionally, we pass in a list with our custom handler
chat = ChatOpenAI(max_tokens=25, streaming=True, callbacks=[MySpeakingCallbackHandler(GTTSSynthesizer())])

chat([HumanMessage(content="Tell me a joke")])
```

### CODE REVIEW

**Comment by baskaryan** [comment]
Hey @ajar98, sorry for missing this one! Think this is pretty cool, thoughts on adding a notebook to docs? 

Also think you could probably implement some of the methods on the VocodeCallbackHandler itself, e.g. speaking prompts in on_llm_start and outputs in on_llm_end. imagine that's how vast majority of folks would use

**Comment by leo-gan** [comment]
@ajar98 Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

**Comment by leo-gan** [comment]
CC @baskaryan

**Comment by efriis** [comment]
Discussed in slack!

**Pull request closed without merging**
