### PR TITLE
Param name change

### PR DESCRIPTION
**Pull request by sangwongenip**
- Description: Changed parameter name 'model_name' to 'model_name_or_path' of HuggingFaceEmbeddings / HuggingFaceInstructEmbeddings / HuggingFaceBgeEmbeddings modules since it can take and process local model files as input, without any change of code! 
 - Issue: Prevent confusion of users 
 - Dependencies: Not at all!

### CODE REVIEW

**Review by baskaryan — COMMENTED** [review]
changing param names is a breaking change, im not sure it's justified here — could we just clarify the docstring?

**Comment by sangwongenip** [comment]
> changing param names is a breaking change, im not sure it's justified here — could we just clarify the docstring?

Target modules run inference based on SentenceTransformer module. In the original code, param : model_name passed to the self.client, which is a SentenceTransformer instance. It is the only usage of the 'model_name' param. 

However, below is the annotation for the 'model_name_and_path' param of  SentenceTransformer module, in which the 'model_name' param of our original code putted. 
":param model_name_or_path: If it is a filepath on disc, it loads the model from that path. If it is not a path, it first tries to download a pre-trained SentenceTransformer model. If that fails, tries to construct a model from Huggingface models repository with that name."

'model_name_and_path' is way more natural.

**Comment by sangwongenip** [comment]
> changing param names is a breaking change, im not sure it's justified here — could we just clarify the docstring?

Is there any problem, please let me know :)

**Comment by efriis** [comment]
Hey @sangwongenip ! Closing this for the reason @baskaryan outlined above. This change will break any users who have something like `HuggingFaceEmbeddings(model_name=...)` in their code, and while I agree the new name is clearer, that clarity is not worth breaking the code of anyone using it like this.

If you're interested in helping out with this, I would recommend a followup PR clarifying that a path can be passed (and how to format it) in the docstring, or adding it to the docs :)

**Pull request closed without merging**
