### PR TITLE
docs: Added providers page for Pebblo and docs for PebbloRetrievalQA

### PR DESCRIPTION
**Pull request by Raj725**
- **Description:** Added providers page for Pebblo and docs for PebbloRetrievalQA
- **Issue:** NA
- **Dependencies:** None
- **Unit tests**: NA

### CODE REVIEW

**Comment by Raj725** [comment]
cc: @eyurtsev

**Comment by ccurme** [comment]
Hi, can you move this to the integrations section of the docs? Thanks.

**Comment by Raj725** [comment]
> Hi, can you move this to the integrations section of the docs? Thanks.

@ccurme Moved, please review.

**Comment by ccurme** [comment]
Hi @Raj725, instead of putting this in its own folder, I'd making a providers page for Pebblo in `providers/`. If desired you could make a short intro page to Pebblo and have a sub-page with this document-- see [Vectara](https://github.com/langchain-ai/langchain/tree/master/docs/docs/integrations/providers/vectara) for an example.

**Comment by Raj725** [comment]
> Hi @Raj725, instead of putting this in its own folder, I'd recommend making a providers page for Pebblo in `providers/`. If desired you could make a short intro page to Pebblo and have a sub-page with this document-- see [Vectara](https://github.com/langchain-ai/langchain/tree/master/docs/docs/integrations/providers/vectara) for an example.

Sure, I will make the changes and let you know. Thanks!

**Comment by Raj725** [comment]
> Hi @Raj725, instead of putting this in its own folder, I'd recommend making a providers page for Pebblo in `providers/`. If desired you could make a short intro page to Pebblo and have a sub-page with this document-- see [Vectara](https://github.com/langchain-ai/langchain/tree/master/docs/docs/integrations/providers/vectara) for an example.

@ccurme Thank you for your feedback. I just wanted to let you know I've updated the PR accordingly. Please review the changes and let me know if any further adjustments are needed.

**Comment by srics** [comment]
Pebblo maintainer here.
@Raj725 contents LGTM, approved

**Review by ccurme — APPROVED** [review]

**Comment by ccurme** [comment]
Thanks for iterating!

**Pull request merged**
