### PR TITLE
WIP - Sequentail chain with previous context

### PR DESCRIPTION
**Pull request by BenderV**
I tried to do something I thought would be trivial but couldn't figure a way to do it.

I wanted to be able to have my successive call keep the previous query (prompt & response)

first call
"""
queryA
-> ResponseA
"""

second call
"""
queryA
-> ResponseA 

query B
-> ResponseB
"""

Test code
```python
llm = OpenAI(temperature=0.9)

chains = []
templateA = """query A {title}: """
promptA = PromptTemplate(
    template=template,
    input_variables=["title"],
)
chainA = LLMChain(llm=llm, prompt=promptA, output_key="responseA")
chains.append(chainA)

templateB = """query B {description}: """
promptB = PromptTemplate(
    template=template,
    input_variables=["description"],
)
chainB = LLMChain(llm=llm, prompt=promptB, output_key="responseB")
chains.append(chainB)

fchain = SequentailChainWithPreviousContext(
    chains=chains,
    verbose=True,
    input_variables=["title", "description"],
    output_variables=["responseA", "responseB"],
)
```

### CODE REVIEW

**Comment by hwchase17** [comment]
hmmm so i think i see what you are getting at, first, some clarifying questions/assumptions:

1) are the chains you always want to join together going to be LLM chains? given that you are call .prompt it seems yes

If so, i think it is totally valid to want a "chain of prompts" basically where you just append to the previous prompt. but i would do it in a constructor, rather than its own chain. what i mean by that is, i would:

1. add a `extend_prompt` method to the base prompt class, which takes in a template and input vairables and extends the previous prompt (this is because there are different types of prompt classes, not all have a `.template`
2. add a constructor method to sequential chain that takes in an initial prompt and then follow up strings and creates a chain, eg

```
def from_prompt_chain(cls, llm: LLM, initial_prompt: PromptTemplate, extensions: List[Tuple[str, List[str]]]):
      chains = [LLMChain(llm=llm, prompt=initial_prompt]
      current_prompt = initial_prompt
      for template, input_vars in extensions:
            current_prompt = current_prompt.extend_prompt(template, input_vars)
            chains.append(current_prompt)
      return cls(chains)
```

does that make sense? happy to help with this - a few other folks had brought up similar things so i do think it would be good to get in!

**Comment by BenderV** [comment]
@hwchase17 
> are the chains you always want to join together going to be LLM chains? given that you are call .prompt it seems yes
Interesting question. 
I guess it's LLMChain, but those could be embedded in other chain (Like LLMRequestsChain) ?

For exemple, if you do:
```python
template = """Between >>> and <<< are the raw search result text from google.
Extract the answer to the question '{query}' or say "not found" if the information is not contained.
Use the format
Extracted:<answer or "not found">
>>> {requests_result} <<<
Extracted:"""

template_follow_up = """
What is the total size of their population ?
"""
```
I would want to get the LLMRequestsChain prompt & response (via LLMRequestsChain.llm_chain)
(A) Do you think we should try to handle this use case or too hard for now?

> add a extend_prompt method to the base prompt class, which takes in a template and input vairables and extends the previous prompt (this is because there are different types of prompt classes, not all have a .template
Agree with you its imperfect. I don't like to recreate the prompt here. Maybe we should store prompt inside the LLMResult and use that as the base to access the prompt given. (B) Do you think there is an issue with this approach?

> add a constructor method to sequential chain that takes in an initial prompt and then follow up strings and creates a chain, eg
The issue I see here is that we couldn't specify the different call output names (in my example responseA & responseB), that we may want to get too. (I do)

**Comment by hwchase17** [comment]
@BenderV maybe im not completely understanding what you're asking, but would something like this work? https://github.com/hwchase17/langchain/pull/384

**Comment by BenderV** [comment]
@hwchase17 hey... try to dig up a bit this old PR...

I'm still struggling to see what's best, and how does it fit in the global philosophy of the library. I think we should probably be cautious about this one. 🤔 

Regarding your PR https://github.com/hwchase17/langchain/pull/384, it's missing some features comparing to the current solution
1. ability to retrieve intermediary outputs
2. ability to use intermediary input
3. ability to use different chain configuration 
4. ability to use something different from LLMChain

I have added an example with the point 1, 2 & 3 (but I guess you will understand the 4 based on the 3)
https://gist.github.com/BenderV/15d9a58d88318034c6ef27db5219bba7

To put some context, I had the need for the project https://generator.universaldata.io, where I had multiple steps, and I wanted an easy way to join them.
Here an extract of the code in question https://gist.github.com/BenderV/1ab57ad175c0c1385ae7c4fad1d9224b

You might notice that I didn't use SequentailChainWithPreviousContext for the last call, simply because I need to add some custom rules/processing on one of the intermediary inputs... (which let me to think that we might think bigger ?)

**Pull request closed without merging**
