### PR TITLE
Fixes hwchase17/langchain#1211

### PR DESCRIPTION
**Pull request by cs0lar**
### Background

This pull request pertains to fixing issue #1211 

### Changes

- The `from_texts` class method has been implemented. Tests for the weaviate vector store provider have been added in `langchain/test/integration_tests/vectorstores/test_weaviate.py`. 
- A docker compose file required for the tests has been added in `langchain/tests/integration_tests/vectors/docker_compose/weaviate.yml`.
- Test dependency has been added in `pyproject.toml` and `poetry.lock`

### Test Plan
Initial tests for the Weaviate vector store integration have been added.

### Change Safety

- [x] I have added tests to cover my changes

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
adding the `similarity_search_by_vector` changes the current functionality a good bi

is it possible to not change that?

**Comment by cs0lar** [comment]
@hwchase17 yes it can. However the original functionality uses the nearText query which requires a vectorizer to be specified and a module to be loaded in weaviate. If you want I can add the text2vec-openai module in the docker compose file and revert the original function.

**Comment by cs0lar** [comment]
@hwchase17 actually, I think I may have misunderstood you. Could you please clarify what you mean in your comment?

**Comment by cs0lar** [comment]
@hwchase17 the original `similarity_search` has been reinstated and added a note that weaviate must be installed with a vectorizer module for it to work (weaviate can be installed without support modules).
As a side note, do you think support for [Embedded Waviate](https://weaviate.io/developers/weaviate/installation/embedded) would be desirable?

**Pull request merged**
