### PR TITLE
core[patch]: allowing latest `packaging` versions

### PR DESCRIPTION
**Pull request by jamesbraza**
Allowing version 24 of https://github.com/pypa/packaging

### CODE REVIEW

**Comment by jamesbraza** [comment]
@hinthornw @efriis @baskaryan based on latest mergers to the `pyproject.toml`

**Comment by hinthornw** [comment]
What was the issue motivating the change?

**Comment by hinthornw** [comment]
Thank you! 🙏

**Comment by efriis** [comment]
Thanks @jamesbraza !

**Comment by efriis** [comment]
added an upper bound incase version 25 has any compatibility issues. Considering adding some daily CI that lets us know when our version constraints block the latest version of a package in order to address this sooner

**Pull request merged**
