### PR TITLE
Allow users to pass local embeddings to Weaviate Hybrid Search Retriever #5539

### PR DESCRIPTION
**Pull request by nerd4me**
#5539

### CODE REVIEW

**Comment by baskaryan** [comment]
cc @hsm207

**Comment by mfmezger** [comment]
any news on that? :).

**Comment by ChristianWeyer** [comment]
This is a very welcomed and important addition. Any chance it gets merged @hwchase17?
Thanks!

**Comment by baskaryan** [comment]
the main weaviate integration has been separated out into it's own repo that can be co-maintained by langchain and weaviate, could we port this pr over there? https://github.com/langchain-ai/langchain-weaviate

**Comment by baskaryan** [comment]
> the main weaviate integration has been separated out into it's own repo that can be co-maintained by langchain and weaviate, could we port this pr over there? https://github.com/langchain-ai/langchain-weaviate

closing per ^

**Pull request closed without merging**
