### PR TITLE
Add batch processing and wait time to FAISS from_texts method

### PR DESCRIPTION
**Pull request by syusuke9999**
Description: This pull request introduces two new optional parameters to the from_texts method in the FAISS class: batch_size and wait_time. When both parameters are provided, the method will process the texts in batches, waiting for a specified amount of time between each batch. This can be useful when dealing with rate-limited APIs such as the OpenAI API. If tqdm is not installed, an ImportError will be raised.

Issue: This change addresses the issue of handling large volumes of text processing when using rate-limited APIs (solution to issue #634).

Dependencies: This change requires the tqdm module.

Tag maintainer: @rlancemartin, @eyurtsev (as this change is related to VectorStores)

Twitter handle: @syusuke7777

### CODE REVIEW

**Comment by hwchase17** [comment]
imo this is something better handled on the embedding class. for example, OpenAIEmbeddings has a parameter called chunk_size which does this

Was the motivation for this PR OpenAIEmbeddings or a separate one?

**Comment by syusuke9999** [comment]
The motivation for my PR was indeed related to the OpenAIEmbeddings class. I encountered rate limit errors when trying to perform a large number of embeddings at once using the OpenAI API. Initially, I considered making modifications to the VectorStore class, but I was concerned about how these changes would affect derived classes. Therefore, I decided to make changes to the FAISS class, which I commonly use. However, I agree that making changes to the OpenAIEmbeddings class would be more consistent. I can make modifications to OpenAIEmbeddings instead and submit a new PR.

**Comment by hwchase17** [comment]
> The motivation for my PR was indeed related to the OpenAIEmbeddings class. I encountered rate limit errors when trying to perform a large number of embeddings at once using the OpenAI API. Initially, I considered making modifications to the VectorStore class, but I was concerned about how these changes would affect derived classes. Therefore, I decided to make changes to the FAISS class, which I commonly use.
> 
> However, I agree that making changes to the OpenAIEmbeddings class would be more consistent. I can make modifications to OpenAIEmbeddings instead and submit a new PR.

You should be able to set it already with `chunk_size`! i dont think too many changes will be needed. ill close pr - but if other changes are needed feel free to open a new one

**Comment by syusuke9999** [comment]
@abhinavsood

As hwchase17 says, you can use the chunk_size parameter to avoid the API rate limit error.
The parameter can be specified as follows
embeddings = OpenAIEmbeddings(chunk_size=10)

By creating an embeddings chain in this way, you can avoid or mitigate API rate-limiting errors associated with storing in a vector store using this chain.

Exponential back-off does not help avoid rate-limiting errors associated with continuous API calls.

As long as the chunk_size parameter is present, I think it is better to use the chunk_size parameter to avoid making the Langchain structure more complex than necessary.

**Pull request closed without merging**
