### PR TITLE
feat: add markdown list parser

### PR DESCRIPTION
**Pull request by fapont**
**Description:** add `MarkdownListOutputParser` as a new `ListOutputParser`
 **Issue:** #11410

### CODE REVIEW

**Review by efriis — APPROVED** [review]
Thanks! Should mostly work as-is. Some suggestions for further work if you wanna get really deep in the markdown spec!

```
- markdown supports indentation
  - like this
+ markdown also supports starting lists with
* 3 different starting "dots"
```

But by and large, LLMs seem to mostly output `-` as you have here :)

**Comment by fapont** [comment]
> Thanks! Should mostly work as-is. Some suggestions for further work if you wanna get really deep in the markdown spec!
> 
> ```
> - markdown supports indentation
>   - like this
> + markdown also supports starting lists with
> * 3 different starting "dots"
> ```
> 
> But by and large, LLMs seem to mostly output `-` as you have here :)

This could be a good improvement. Would you like me to work on adding these features? Or maybe create a new "good first issue", or just wait until someone needs these use cases? As you prefer :)

**Comment by efriis** [comment]
No strong preference - up to you! I think the current state of it solves the main use of this output parser, and if we hear people are pushing the limits of it, we can post an issue to improve it :)

**Comment by fapont** [comment]
> No strong preference - up to you! I think the current state of it solves the main use of this output parser, and if we hear people are pushing the limits of it, we can post an issue to improve it :)

Sounds good to me, thanks !

**Comment by fapont** [comment]
Do I need to close the related issue ? https://github.com/langchain-ai/langchain/issues/11410

**Pull request merged**
