### PR TITLE
Vectara rag mq

### PR DESCRIPTION
**Pull request by ofermend**
- **Description:** another Vectara template for MultiQuery RAG flow
  - **Twitter handle:** @ofermend

### CODE REVIEW

**Review by efriis — COMMENTED** [review]
Hey @ofermend ! Could you please fix check out the lint errors?

**Comment by ofermend** [comment]
Erick - sorry, when I run "make lint" locally I only see other (non-vectara-related) files that come up as issues. The failues above say:

Creating virtualenv langchain-monorepo in /home/runner/work/langchain/langchain/.venv
poetry lock --check is deprecated, use `poetry check --lock` instead.
Error: poetry.lock is not consistent with pyproject.toml. Run `poetry lock [--no-update]` to fix it.
Error: Process completed with exit code 1.

Again, not sure how to fix it. Can you please advise?

**Comment by ofermend** [comment]
Looks like it's all good now

**Comment by efriis** [comment]
Hey @ofermend ! I unfortunately don't have push access to the vectara repo to fix a few more things. See the PR mentioned ^

Will land today!

**Pull request closed without merging**
