### PR TITLE
Add Connery Tool and Toolkit

### PR DESCRIPTION
**Pull request by machulav**
## Summary

This PR implements the "Connery Action Tool" and "Connery Toolkit". Using them, you can integrate Connery actions into your LangChain agents and chains.

Connery is an open-source plugin infrastructure for AI.

With Connery, you can easily create a custom plugin with a set of actions and seamlessly integrate them into your LangChain agents and chains. Connery will handle the rest: runtime, authorization, secret management, access management, audit logs, and other vital features. Additionally, Connery and our community offer a wide range of ready-to-use open-source plugins for your convenience.

Learn more about Connery:

- GitHub: https://github.com/connery-io/connery-platform
- Documentation: https://docs.connery.io
- Twitter: https://twitter.com/connery_io

## TODOs

- [x] API wrapper
   - [x] Integration tests
- [x] Connery Action Tool
   - [x] Docs
   - [x] Example
   - [x] Integration tests
- [x] Connery Toolkit
  - [x] Docs
  - [x] Example
- [x] Formatting (`make format`)
- [x] Linting (`make lint`)
- [x] Testing (`make test`)

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
assuming lint passes, looks reasonable to me!

**Review by hwchase17 — APPROVED** [review]

**Comment by machulav** [comment]
@hwchase17 thank you for the review! Is there anything I still need to do to merge this PR?

**Comment by machulav** [comment]
@baskaryan @nfcampos Hey folks, may I ask you to merge this PR? It's approved already, but it stuck unmerged for some reason. Some of our customers want to use the Toolkit but are blocked by the PR.

**Comment by hwchase17** [comment]
@machulav waiting for CI to pass, then will merge in if it does

**Comment by machulav** [comment]
Alright, sorry, my bad. It seems the test stopped passing at some point, and I didn't notice it's related to my code.
Let me check them.

**Comment by machulav** [comment]
@hwchase17 CI is fixed now

**Comment by baskaryan** [comment]
thank you @machulav!

**Comment by machulav** [comment]
Thank you! 😍

**Pull request merged**
