### PR TITLE
fix: pgvector hang risk if table not exist #3883

### PR DESCRIPTION
**Pull request by hanguofeng**

### CODE REVIEW

**Review by hwchase17 — APPROVED** [review]
thanks!

**Comment by esko22** [comment]
FYI - had an error pop up after upgrading to the latest rev - works fine after commenting out the commit.

```
langchain/vectorstores/pgvector.py", line 168, in create_tables_if_not_exists
    self._conn.commit()
AttributeError: 'Connection' object has no attribute 'commit'
```

**Comment by esko22** [comment]
Hi @hanguofeng ,

Appreciate the quick response. You are spot on, updating SQLAlchemy did the trick. 

Thank you for your help.

-krb

**Comment by esko22** [comment]
I bumped up SQLAlchemy from 1.4.47 to 2.0.12
using PGVector 0.1.6, LangChain 0.0.160

**Pull request merged**
