### PR TITLE
Gracefully degrade when model asks for nonexistent tool

### PR DESCRIPTION
**Pull request by johnmcdonnell**
Not yet tested, but very simple change, assumption is that we're cool with just producing a generic output when tool is not found

### CODE REVIEW

**Comment by hwchase17** [comment]
this is great! thanks!

unit test might be nice - is it easy to add one?

**Comment by johnmcdonnell** [comment]
@hwchase17 I think this should be ready to go now

**Comment by hwchase17** [comment]
fyi running `make format` should fix black/isort issues, while `make lint` should run linting locally

**Comment by johnmcdonnell** [comment]
Ugh one last test! Checks pass

**Pull request merged**
