### PR TITLE
Fix python-openai v1.x.x doesn't work in langchain

### LINKED ISSUE #12967: AttributeError: module 'openai' has no attribute 'Completion'
### System Info

Downloading langchain-0.0.331-py3-none-any.whl (2.0 MB)
Downloading openai-1.1.1-py3-none-any.whl (217 kB)

### Who can help?

_No response_

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Run the following code in colab:

```
!pip install langchain
!pip install openai

from langchain.llms import OpenAI

OpenAI().predict("hoge")
```

You'll get:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-0eec0f4f0523>](https://localhost:8080/#) in <cell line: 4>()
      2 from langchain.llms import OpenAI
      3 
----> 4 OpenAI().predict("hoge")

3 frames
[/usr/local/lib/python3.10/dist-packages/langchain/llms/openai.py](https://localhost:8080/#) in validate_environment(cls, values)
    264             import openai
    265 
--> 266             values["client"] = openai.Completion
    267         except ImportError:
    268             raise ImportError(

AttributeError: module 'openai' has no attribute 'Completion'
```

### Expected behavior

This was working until yesterday. It's likely due to the openai dependency update.

### PR DESCRIPTION
**Pull request by dosuken123**
Fix https://github.com/langchain-ai/langchain/issues/12967

Replace this entire comment with:
  - **Description:** Fix python-openai v1.x.x doesn't work in langchain, See https://github.com/langchain-ai/langchain/issues/12967
  - **Issue:** https://github.com/langchain-ai/langchain/issues/12967
  - **Dependencies:** openai-python v1.x.x which was released a few hours ago
  - **Tag maintainer:** @baskaryan, @eyurtsev, @hwchase17
  - **Twitter handle:** @dosuken123 

Please make sure your PR is passing linting and testing before submitting. Run `make format`, `make lint` and `make test` to check this locally.

See contribution guidelines for more information on how to write/run tests, lint, etc: 
https://github.com/langchain-ai/langchain/blob/master/.github/CONTRIBUTING.md

If you're adding a new integration, please include:
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/extras` directory.

If no one reviews your PR within a few days, please @-mention one of @baskaryan, @eyurtsev, @hwchase17.

### CODE REVIEW

**Comment by dosuken123** [comment]
Confirmed that it's working in my local environment:

```
from langchain.llms import OpenAI
import os

os.environ["OPENAI_API_KEY"] = "[REDACTED]"

print(OpenAI().predict("Who's the president of the united states?"))
=> The President of the United States is Joe Biden.
```

However, I appreciate it if someone can verify if there is a better way than this. Also, we should test on chat models as well

**Comment by dosuken123** [comment]
cc @baskaryan, @eyurtsev, @hwchase17

**Comment by dosuken123** [comment]
Closing in favor of https://github.com/langchain-ai/langchain/pull/12969

**Comment by emhagman** [comment]
> /close

I'm confused. That PR does not address this issue as far as I can tell. It was just released and I am still running into issues. https://github.com/langchain-ai/langchain/pull/12969 only tackles the issues with embeddings.

**Comment by dosuken123** [comment]
@baskaryan Should I reopen this PR and refactor like https://github.com/langchain-ai/langchain/commit/8e0cb2eb84539b249198f98f7647a1f24b2392c2 and https://github.com/langchain-ai/langchain/pull/12969? It seems we've not deliberately fixed `llms.OpenAI` class, which is corresponding to this client https://github.com/openai/openai-python/blob/main/src/openai/resources/completions.py. If no one is tracking the issue, I'm happy to contribute if it makes sense.

**Pull request closed without merging**
