### PR TITLE
docs: API Ref navbar update

### PR DESCRIPTION
**Pull request by leo-gan**
Now the navbar items are too long and are not visible.
image

I'm trying to cut the top-level part of the namespace in items.

### CODE REVIEW

**Comment by leo-gan** [comment]
@efriis Please, check if it works or not.

**Comment by leo-gan** [comment]
@efriis Please, check if it works or not for you.

**Comment by leo-gan** [comment]
@efriis Please, check if it works or not for you.

**Comment by efriis** [comment]
Will start a test deploy when readthedocs recognizes my new branch!

**Comment by efriis** [comment]
I think it will show here: https://api.python.langchain.com/en/erick-api-ref-navbar-update/langchain_api_reference.html

Will take an hour or so before showing up

**Comment by leo-gan** [comment]
> I think it will show here: https://api.python.langchain.com/en/erick-api-ref-navbar-update/langchain_api_reference.html
> 
> Will take an hour or so before showing up
@efriis It is a link to the latest docs. Master does not have this PR change. Did I miss something?

**Comment by leo-gan** [comment]
@efriis any new comments?

**Comment by efriis** [comment]
@leo-gan did you look at the preview? I don't think this worked https://api.python.langchain.com/en/erick-api-ref-navbar-update/langchain_api_reference.html

**Comment by leo-gan** [comment]
> @leo-gan did you look at the preview? I don't think this worked https://api.python.langchain.com/en/erick-api-ref-navbar-update/langchain_api_reference.html

@efriis  Ohh... I didn't mention the .../erick-... part. I thought it is just a link to the existing docs. Sorry. Yeah, it doesn't work.

**Comment by leo-gan** [comment]
@efriis I'm trying another option. Can you generate API again, please?

**Comment by leo-gan** [comment]
@efriis I've tried another option. Can you generate the API Refs again and check if it works or not, please?

**Comment by efriis** [comment]
Rebuilding. Should be up in ~1hr unless it fails

**Comment by efriis** [comment]
Build failed I think for unrelated reasons

**Comment by leo-gan** [comment]
@efriis Can you try to build it again, please?

**Comment by leo-gan** [comment]
@efriis Can you try to build it again, please? Thanks!

**Comment by efriis** [comment]
Going to close this for now. We don't have a great way of testing this with the new build flow at this time, and I'll reopen this PR when that's addressed to give it a go!

**Pull request closed without merging**
