### PR TITLE
fix: too many values to unpack (expected 2)

### PR DESCRIPTION
**Pull request by gazedreamily**

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
hmmm when does this happen? lets add a test?

**Comment by leo-gan** [comment]
@gazedreamily Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!
If this PR is not needed anymore, could you, please, let me know or close this PR?

**Comment by gazedreamily** [comment]
@leo-gan maybe it is fixed by #8716

**Comment by leo-gan** [comment]
@gazedreamily Yes it was fixed. Thank you for pointing! Closing

**Pull request closed without merging**
