### PR TITLE
Added Memory Parameter to SQL-Chain

### PR DESCRIPTION
**Pull request by keenborder786**
- Description:  SQL Database Chain and Agent does not allow to pass in memory therefore added this feature with additional tests.
- Issue:  #6918
- Tag maintainer: @hwchase17

### CODE REVIEW

**Comment by baskaryan** [comment]
hey @keenborder786, thanks for PR!

could you explain your use case a bit more? i don't think we want to pass memory to the LLMChain directly, since the AgentExecutor already takes care of keeping track of the agent's sequence of thoughts and passing those back to the LLM.

**Comment by keenborder786** [comment]
Hey @baskaryan. 
When we create `AgentExecutor` from `create_sql_agent` or when you directly create the SQLChain from either `SQLDatabaseChain` or `SQLDatabaseSequentialChain`, I noticed there was no option of directly passing the memory whatsoever. Even though one of the [guides](https://python.langchain.com/docs/modules/agents/how_to/add_memory_openai_functions) shows how you can utilize memory through  OPENAI_FUNCTION agent but still giving the user the ability to pass in memory explicitly in both the SQL-agent and chain makes more sense.

Plus there were no tests for the sql-db-chains so I added them as well.

Cheers,

**Comment by keenborder786** [comment]
Also when I tried the original agent-executor returned by `create_sql_agent`, it was not understanding the previous context which showed there was some memory issue but after explicitly passing the memory to the executor, the issue got resolved.

**Comment by keenborder786** [comment]
@baskaryan makes sense?

**Comment by keenborder786** [comment]
@hwchase17, any updates.

**Comment by keenborder786** [comment]
@baskaryan @hwchase17. Please have a look.

**Comment by keenborder786** [comment]
@baskaryan @hwchase17. I know have been bothering you guys a lot. But please let me know of the feedback. Will be really grateful.

**Comment by keenborder786** [comment]
@hwchase17 please give me an update

**Comment by keenborder786** [comment]
@hwchase17 Can you please give me an update.

**Comment by keenborder786** [comment]
Please please review this: @hwchase17

**Comment by keenborder786** [comment]
@baskaryan @hwchase17, let me explain in detail why this PR needs to be merged. 

Currently, there are four different ways in Langchain that allow you to interact with the SQL-Database.

The first two methods involve making direct SQL-Chains, either of type `SQLDatabaseChain` or `SQLDatabaseSequentialChain`. However, these two types of chains do not make use of memory. I tried passing the memory object in the `from_llm` method, but it was clear that the underlying LLM chain was not utilizing the memory object. Including `memory_key` in the prompt was raising a validation error. However, when I explicitly passed the memory in the underlying LLM chain of both `SQLDatabaseChain` and `SQLDatabaseSequentialChain`, there was no validation error, and the `memory_key` variable was being filled in the prompt.

1- SQLDatabaseChain with memory:

```python
PROMPT_SUFFIX = """
Relevant piece of previous conversation that you can use.
{history}

Only use the following tables:
{table_info}

Question: {input}"""
_DEFAULT_TEMPLATE = """Given an input question, first create a syntactically correct {dialect} query to run, then look at the results of the query and return the answer. Unless the user specifies in his question a specific number of examples he wishes to obtain, always limit your query to at most {top_k} results. You can order the results by a relevant column to return the most interesting examples in the database.

Never query for all the columns from a specific table, only ask for a the few relevant columns given the question.

Pay attention to use only the column names that you can see in the schema description. Be careful to not query for columns that do not exist. Also, pay attention to which column is in which table.

Use the following format:

Question: Question here
SQLQuery: SQL Query to run
SQLResult: Result of the SQLQuery
Answer: Final answer here

"""

PROMPT = PromptTemplate(
    input_variables=["input", "table_info", "history", "dialect", "top_k"],
    template=_DEFAULT_TEMPLATE + PROMPT_SUFFIX,
)

db_chain = SQLDatabaseChain.from_llm(
    llm,
    db,
    prompt=PROMPT,
    memory=ConversationBufferMemory(input_key="input", memory_key="history") # this is being pass directly to underlying LLM,
    verbose=True,
)
```
2- Similar is the case for SQLDatabaseSequentialChain. Note that I am only passing the query_memory for the underlying SQLDatabaseChain and no memory for the decider chain. When I tried it out, the context building was the same, but extra tokens were being used; therefore, I removed the decider_memory.


```python
PROMPT_SUFFIX = """
Relevant piece of previous conversation that you can use.
{history}

Only use the following tables:
{table_info}

Question: {input}"""
_DEFAULT_TEMPLATE = """Given an input question, first create a syntactically correct {dialect} query to run, then look at the results of the query and return the answer. Unless the user specifies in his question a specific number of examples he wishes to obtain, always limit your query to at most {top_k} results. You can order the results by a relevant column to return the most interesting examples in the database.

Never query for all the columns from a specific table, only ask for a the few relevant columns given the question.

Pay attention to use only the column names that you can see in the schema description. Be careful to not query for columns that do not exist. Also, pay attention to which column is in which table.

Use the following format:

Question: Question here
SQLQuery: SQL Query to run
SQLResult: Result of the SQLQuery
Answer: Final answer here

"""

query_prompt = PromptTemplate(
    input_variables=["input", "table_info", "history", "dialect", "top_k"],
    template=_DEFAULT_TEMPLATE + PROMPT_SUFFIX,
)


_DECIDER_TEMPLATE = """Given the below input question and list of potential tables, output a comma separated list of the table names that may be necessary to answer this question.

Question: {query}

Table Names: {table_names}

Relevant Table Names:"""
DECIDER_PROMPT = PromptTemplate(
    input_variables=["query", "table_names"],
    template=_DECIDER_TEMPLATE,
    output_parser=CommaSeparatedListOutputParser(),
)


db_chain = SQLDatabaseSequentialChain.from_llm(
    llm,
    db,
    query_prompt=query_prompt,
    query_memory=ConversationBufferMemory(input_key="input", memory_key="history") # this is being passed to the underlying SQLDatabaseChain,
    verbose=True,
)
```

I hope this clarifies the changes in SQL-chains. In summary, there was no passing of memory to the SQL Chains; therefore, they were not able to build onto the previous context.

Now, I want to point out some details about the `create_sql_agent` that allow you to build either ZERO_SHOT_REACT_DESCRIPTION or OPENAI_FUNCTIONS agents with SQLDatabaseToolKit to interact with SQL-Databases.

1- For the ZERO_SHOT_REACT_DESCRIPTION created SQL-Agent using create_sql_agent, you can pass memory in the parameter agent_executor_kwargs, and it will build onto the context therefore @baskaryan  you were actually right in pointing our that for agent we don't need to have separate memory input. However, this needs to be documented somewhere, as it is not clear to the user. I have mentioned this in #6918. Just to showcase, the following ZERO_SHOT_REACT_DESCRIPTION SQL-Agent is able to use a memory object:


```python
SQL_SUFFIX = """Begin!

History: {history}
Question: {input}
Thought: I should look at the tables in the database to see what I can query. Then I should query the schema of the most relevant tables.
{agent_scratchpad}"""

agent = create_sql_agent(
    llm,
    SQLDatabaseToolkit(db=db, llm=llm),
    AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    agent_executor_kwargs={
        "memory": ConversationBufferMemory(
            input_key="input", memory_key="history", return_messages=True
        )
    },
    suffix=SQL_SUFFIX,
    input_variables=["input", "history", "agent_scratchpad"],
    verbose=True,
)

```

2- However, OPENAI_FUNCTIONS is more problematic. First, I noticed that for this, there is no MessagesPlaceholder for memory_key. I changed the `create_sql_agent` where I modified the messages list to something like this:

```python
messages = [
    SystemMessage(content=prefix),
    HumanMessagePromptTemplate.from_template("{input}"),
    AIMessage(content=suffix or SQL_FUNCTIONS_SUFFIX),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
    MessagesPlaceholder(variable_name=agent_executor_kwargs.get("memory"), memory_key) # added this
]
```
Then I tried the modified `create_sql_agent`

```python

agent = create_sql_agent(
    llm,
    SQLDatabaseToolkit(db=db, llm=llm),
    AgentType.OPENAI_FUNCTIONS,
    agent_executor_kwargs={'memory': ConversationBufferMemory(input_key='input', memory_key='memory', return_messages=True)},
    input_variables=['input', 'memory', 'agent_scratchpad'],
    verbose=True
)

```

Note that I am passing the memory as an input_variable, and a memory_key placeholder has been created for OPENAI_FUNCTIONS agent. However, for some reason, if the agents construct a wrong query, it keeps invoking the sql_db_query tool again and again without actually correcting the query by invoking other tools in SQLToolKits (I have no idea why this was happening).  Therefore this modification of passing in memory_key as MessagesPlaceholder for OPENAI_FUNCTIONS did not work.

Fortunately, when I followed the instructions in this [documentation](https://python.langchain.com/docs/modules/agents/how_to/add_memory_openai_functions), the agent seemed to work. However, note that the agent in the above documentation is using a memory-less SQLChain as a tool and not the SQLToolkit tools. Fortunately, the solution works with the OPENAI_FUNCTIONS agent.

As a result, if a user tries to pass memory in create_sql_agent while creating an OPENAI_FUNCTIONS agent, I raise a value error and point them to the above doc-link. The reason why I did not change the code for this part was that create_sql_agent is designed to work with the SQLToolkit tool and not other tools. Of course, we can augment create_sql_agent by giving it the ability to pass in additional input tools, but that's for another PR. Regardless, for the OPENAI_FUNCTIONS agent type in create_sql_agent, memory is not working even when passed as an argument and a placeholder is created. But it works with other tools as described above.

I hope this clarifies things.

Cheers,

**Comment by keenborder786** [comment]
@baskaryan please see

**Comment by keenborder786** [comment]
@baskaryan please see. Many people are facing this issue.

**Comment by keenborder786** [comment]
@baskaryan please see.

**Comment by maaz1m** [comment]
@baskaryan I'm facing issues due to the lack of memory as well. Please review and merge this PR.

**Comment by knaquin** [comment]
I'm using nodejs and langchain (v0.0116) but this works for me...

In the prompt template, I had to add the "history" input. 
```
You are a PostgreSQL expert...

{history}

Question {input}
```

Then, when setting things upfor the chain...

```
const memory = new BufferMemory({
	inputKey: "input",
	outputKey: "result"
});

const chain = new SqlDatabaseChain({
	database: database,
	inputKey: 'input',
	llm: new OpenAI({ 
		modelName: 'gpt-3.5-turbo',
		temperature: 0 
	}),
	memory: memory,
	prompt,
	sqlOutputKey: 'sql',
	verbose: true
});
```
```
const result = await chain.call({
        input: <question 1>
 });
console.log(result);

const result2 = await chain.call({
	input: <question 2>
});
console.log(result2);
```

I can see the output of question 1 as part of the prompt input for result 2.

**Comment by tn-Jagdesh** [comment]
does any got solution for this,please let me know how to pass memory to create_sql_agent

**Comment by Reon750** [comment]
@tn-Jagdesh Were you able to put the memory into the create_sql_agent? If not, were you able to do it another way?
It would help me a lot to know how to insert a chat history to a sql agent.
Thanks in advance.

**Comment by m0han22** [comment]
@keenborder786 , Hi, I have tried different approaches, create_sql_agent is storing the previous chat_history, but llm is unable to unable to understand the previous context. And tried with different approaches like RunnableWithMessageHistory. With that, I am getting an error "Agent stopped due to max iterations.". 

```
When I am trying the below code
agent_executor = create_sql_agent(
    toolkit=toolkit,
    llm=llm,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    suffix = suffix,
    input_variables=["input", "agent_scratchpad", "history"],
    agent_executor_kwargs={'memory': memory}
)

```
I am getting this error, `To answer the question "what is his job," I need more context or information about the person being referred to as "his." Without additional details, such as a name or identifier, I cannot determine the job of the individual in question. Could you please provide more information?``

Is there any alternative.

**Pull request closed without merging**
