### PR TITLE
Change in method name for creating an issue on JIRA

### PR DESCRIPTION
**Pull request by varun1505**
The awesome JIRA tool created by @zywilliamli calls the `create_issue()` method to create issues, however, the actual method is `issue_create()`. 

Details in the Documentation here: https://atlassian-python-api.readthedocs.io/jira.html#manage-issues

### CODE REVIEW

**Comment by dev2049** [comment]
good catch! should we add an integration test to make sure?

**Comment by varun1505** [comment]
Sure. Will add it and update the PR.

**Comment by varun1505** [comment]
@dev2049 Integration Tests would mean we'll have to manage JIRA API keys. Not sure how to do that. :/ 
Any thoughts?

**Comment by dev2049** [comment]
> @dev2049 Integration Tests would mean we'll have to manage JIRA API keys. Not sure how to do that. :/
> Any thoughts?

integration tests aren't actually run in CI or anything at the moment. they just make it easy to test things locally. so as long as you had jira keys in your env and ran the integration test it would work. see the other `tests/integration_tests/utilities/...` for examples

**Comment by varun1505** [comment]
@dev2049 I added the tests. Let me know if this is good to go.

**Comment by varun1505** [comment]
Thanks for the pointer @dev2049 . I've added the tests. Let me know if this is good to go!

**Comment by dev2049** [comment]
Thanks @varun1505!

**Pull request merged**
