### PR TITLE
openai[patch]: add vllm to openai

### PR DESCRIPTION
**Pull request by Samoed**
**Description:** Add VLLMOpenAI compatible client with additional parameters

### CODE REVIEW

**Comment by Samoed** [comment]
@ccurme

**Comment by Samoed** [comment]
@efriis

**Comment by Samoed** [comment]
@efriis

**Comment by efriis** [comment]
Howdy! This is not the pattern we want followed with the openai partner package. Feel free to contribute new features to the VLLM connector in the community package if that's what is desired!

**Comment by Samoed** [comment]
Hi! Yes, that's what I intended, but this client would require langchain_openai. I could add this dependency for the langchain community or copy-paste the OpenAI client, but I don't think either solution is ideal.

**Pull request closed without merging**
