### PR TITLE
Fix handling of ServerDisconnectedError in AsyncHtmlLoader that crash…

### PR DESCRIPTION
**Pull request by daniellefranca96**
I've updated the WebResearchRetriever to address a bug where it would crash if unable to retrieve content from a URL. I've implemented error handling and added checks to prevent this issue.

 @rlancemartin, @eyurtsev, @agola11

### CODE REVIEW

**Comment by baskaryan** [comment]
hm are we sure we wouldn't want to raise an error in this case? after all you can't really do anything without loading content

**Comment by daniellefranca96** [comment]
> hm are we sure we wouldn't want to raise an error in this case? after all you can't really do anything without loading content

the way it is now if it could not capture none of the urls it would return a empty array on async_loader, i put a if on webresearchretriever so it also return a  empty array in this case.
what could be done is raise an exception on async_loader if the array is empty instead of return it, do you thik it would be better?
@baskaryan

**Comment by leo-gan** [comment]
@daniellefranca96 Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by efriis** [comment]
Looks like this isn't being worked on anymore. I'll close for now, and if you resume work, feel free to reopen!

**Pull request closed without merging**
