### PR TITLE
add initial prompt stuff

### PR DESCRIPTION
**Pull request by hwchase17**

### CODE REVIEW

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing PR description...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing PR description...

**Comment by Arjun7A** [comment]
Preparing PR description...

**Comment by Arjun7A** [comment]
Preparing PR description...

**Comment by Arjun7A** [comment]
Preparing PR description...

**Comment by Arjun7A** [comment]
Preparing PR description...

**Comment by Arjun7A** [comment]
Preparing PR description...

**Comment by Arjun7A** [comment]
Preparing PR description...

**Comment by Arjun7A** [comment]
Preparing PR description...

**Comment by Arjun7A** [comment]
## PR Reviewer Guide 🔍

#### (Review updated until commit https://github.com/langchain-ai/langchain/commit/270fc8d0f9a0c1330a14ab6eef236f250ab44557)


<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 4 🔵🔵🔵🔵⚪</td></tr>
<tr><td>🧪&nbsp;<strong>PR contains tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>⚡&nbsp;<strong>Key issues to review</strong><br><br>

<a href='https://github.com/langchain-ai/langchain/pull/1/files#diff-fa4663200815e5d89d54ecfea8b43774d8fe7bc93557c65a9ff69597fa722e08R12-R18'><strong>Code Smell</strong></a><br>The `StrictFormatter` class does not handle the case where `args` is not empty and `kwargs` is empty. It only checks if `args` is not empty, but does not check if `kwargs` is empty.

<a href='https://github.com/langchain-ai/langchain/pull/1/files#diff-32f68c7c1915597ac0527feef3929ccc2a07b0b7cd9c3a0884834ec72ef326b0R18-R27'><strong>Possible Bug</strong></a><br>The `Prompt` class does not validate if the `input_variables` are actually used in the `template`. It only checks if the `template` is valid with dummy inputs.

<a href='https://github.com/langchain-ai/langchain/pull/1/files#diff-e8022e562111699dbc25e174ab7ea6a23f78ee911343d420ee6a418ffdff0749R1-R22'><strong>Test Coverage</strong></a><br>The tests for `StrictFormatter` do not cover all possible scenarios, such as testing with an empty `template` or with a `template` that has multiple placeholders.

</td></tr>
</table>

**Comment by Arjun7A** [comment]
**[Persistent review](https://github.com/langchain-ai/langchain/pull/1#issuecomment-4070562346)** updated to latest commit https://github.com/langchain-ai/langchain/commit/270fc8d0f9a0c1330a14ab6eef236f250ab44557

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by Arjun7A** [comment]
Preparing review...

**Comment by fjcobu14** [comment]
benchmark test comment - verification only

**Comment by sailikhithlilly** [comment]
test

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
x

**Comment by gaoanze888** [comment]
Verified this against `upstream/master` (`3478c28ef`), including the regression surface.

| scenario | master | this PR |
| --- | --- | --- |
| list-content chunk | `[]` | `[['red'], ['blue']]` |
| string chunk (control) | same | same |

No regression on the string path, and the tool-call-only chunk contributes nothing rather
than injecting a stringified call.

_Disclosure: AI-assisted review; every table above is from runs I did locally against the
commit named._

**Comment by gaoanze888** [comment]
Verified this against `upstream/master` (`3478c28ef`), including the regression surface.

| scenario | master | this PR |
| --- | --- | --- |
| list-content chunk | `[]` | `[['red'], ['blue']]` |
| string chunk (control) | same | same |

No regression on the string path, and the tool-call-only chunk contributes nothing rather
than injecting a stringified call.

_Disclosure: AI-assisted review; every table above is from runs I did locally against the
commit named._

**Comment by gaoanze888** [comment]
Verified this against `upstream/master` (`3478c28ef`), including the regression surface.

| scenario | master | this PR |
| --- | --- | --- |
| list-content chunk | `[]` | `[['red'], ['blue']]` |
| string chunk (control) | same | same |

No regression on the string path, and the tool-call-only chunk contributes nothing rather
than injecting a stringified call.

_Disclosure: AI-assisted review; every table above is from runs I did locally against the
commit named._

**Comment by gaoanze888** [comment]
Verified this against `upstream/master` (`3478c28ef`), including the regression surface.

| scenario | master | this PR |
| --- | --- | --- |
| list-content chunk | `[]` | `[['red'], ['blue']]` |
| string chunk (control) | same | same |

No regression on the string path, and the tool-call-only chunk contributes nothing rather
than injecting a stringified call.

_Disclosure: AI-assisted review; every table above is from runs I did locally against the
commit named._

**Comment by gaoanze888** [comment]
Verified this against `upstream/master` (`3478c28ef`), including the regression surface.

| scenario | master | this PR |
| --- | --- | --- |
| list-content chunk | `[]` | `[['red'], ['blue']]` |
| string chunk (control) | same | same |

No regression on the string path, and the tool-call-only chunk contributes nothing rather
than injecting a stringified call.

_Disclosure: AI-assisted review; every table above is from runs I did locally against the
commit named._

**Comment by gaoanze888** [comment]
Verified this against `upstream/master` (`3478c28ef`), including the regression surface.

| scenario | master | this PR |
| --- | --- | --- |
| list-content chunk | `[]` | `[['red'], ['blue']]` |
| string chunk (control) | same | same |

No regression on the string path, and the tool-call-only chunk contributes nothing rather
than injecting a stringified call.

_Disclosure: AI-assisted review; every table above is from runs I did locally against the
commit named._

**Comment by gaoanze888** [comment]
Verified this against `upstream/master` (`3478c28ef`), including the regression surface.

| scenario | master | this PR |
| --- | --- | --- |
| list-content chunk | `[]` | `[['red'], ['blue']]` |
| string chunk (control) | same | same |

No regression on the string path, and the tool-call-only chunk contributes nothing rather
than injecting a stringified call.

_Disclosure: AI-assisted review; every table above is from runs I did locally against the
commit named._

**Comment by gaoanze888** [comment]
Verified this against `upstream/master` (`3478c28ef`), including the regression surface.

| scenario | master | this PR |
| --- | --- | --- |
| list-content chunk | `[]` | `[['red'], ['blue']]` |
| string chunk (control) | same | same |

No regression on the string path, and the tool-call-only chunk contributes nothing rather
than injecting a stringified call.

_Disclosure: AI-assisted review; every table above is from runs I did locally against the
commit named._

**Comment by gaoanze888** [comment]
Verified this against `upstream/master` (`3478c28ef`), including the regression surface.

| scenario | master | this PR |
| --- | --- | --- |
| list-content chunk | `[]` | `[['red'], ['blue']]` |
| string chunk (control) | same | same |

No regression on the string path, and the tool-call-only chunk contributes nothing rather
than injecting a stringified call.

_Disclosure: AI-assisted review; every table above is from runs I did locally against the
commit named._

**Comment by gaoanze888** [comment]
Verified this against `upstream/master` (`3478c28ef`), including the regression surface.

| scenario | master | this PR |
| --- | --- | --- |
| list-content chunk | `[]` | `[['red'], ['blue']]` |
| string chunk (control) | same | same |

No regression on the string path, and the tool-call-only chunk contributes nothing rather
than injecting a stringified call.

_Disclosure: AI-assisted review; every table above is from runs I did locally against the
commit named._

**Pull request merged**
