### PR TITLE
Add default K in Retriever

### PR DESCRIPTION
**Pull request by vnk8071**
- Description: add default class variable for inheriting BaseRetriever 
  - Issue: issue #7922 ,
  - Dependencies: no,
  - Tag maintainer: @rlancemartin, @eyurtsev

### CODE REVIEW

**Comment by baskaryan** [comment]
with VectorStoreRetriever you can already pass in k via search_kwargs, would that work for your use case?

**Comment by vnk8071** [comment]
I have tried search_kwargs with the key "k" before, but the object keeps the default value of 4. I want to pass these values initially by overriding them when using VectorStoreRetriever. Maybe I will recheck it and thank @baskaryan for the quickly reply.

**Comment by baskaryan** [comment]
> I have tried search_kwargs with the key "k" before, but the object keeps the default value of 4. I want to pass these values initially by overriding them when using VectorStoreRetriever. Maybe I will recheck it and thank @baskaryan for the quickly reply.

hm that's strange. if 
```python
vecstore = XYZVectorStore(...)
retriever = vecstore.as_retriever(search_kwargs={"k": 10})
```
doesn't work for you let me know!

**Comment by vnk8071** [comment]
Oh, this work already @baskaryan. I have passed the value is **{"k": 10} and it still keeps the default is 10

**Comment by vnk8071** [comment]
Can we pass easily like k default in VectoreStoreRetriver? Because it is an important parameter when using search_kwargs without the correct order as VectorStore.

**Comment by hwchase17** [comment]
search_kwargs is the way to do it

if you want to change the default, you can change the default of search_kwargs

**Pull request closed without merging**
