### PR TITLE
Respect User-Specified User-Agent in WebBaseLoader

### LINKED ISSUE #4167: User Agent on WebBaseLoader does not set header_template when passing `header_template`
### System Info

Hi Team, 

When using WebBaseLoader and setting header_template the user agent does not get set and sticks with the default python user agend. 

```
loader = WebBaseLoader(url, header_template={
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36',
  }) 

  data = loader.load()
```

printing the headers in the INIT function shows the headers are passed in the template

BUT in the load function or scrape the self.sessions.headers shows 

FIX set the default_header_template in INIT if header template present

NOTE: this is due to Loading a page on WPENGINE who wont allow python user agents

LangChain 0.0.158
Python 3.11

### Who can help?

_No response_

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Hi Team, 

When using WebBaseLoader and setting header_template the user agent does not get set and sticks with the default python user agend. 

`loader = WebBaseLoader(url, header_template={
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36',
  }) 

  data = loader.load()`

printing the headers in the INIT function shows the headers are passed in the template

BUT in the load function or scrape the self.sessions.headers shows 

FIX set the default_header_template in INIT if header template present

NOTE: this is due to Loading a page on WPENGINE who wont allow python user agents

LangChain 0.0.158
Python 3.11

### Expected behavior

Not throw 403 when calling loader. 

Modifying INIT and setting the session headers works if the template is passed

### PR DESCRIPTION
**Pull request by lyz1990**
# Respect User-Specified User-Agent in WebBaseLoader
This pull request modifies the `WebBaseLoader` class initializer from the `langchain.document_loaders.web_base` module to preserve any User-Agent specified by the user in the `header_template` parameter. Previously, even if a User-Agent was specified in `header_template`, it would always be overridden by a random User-Agent generated by the `fake_useragent` library. 

With this change, if a User-Agent is specified in `header_template`, it will be used. Only in the case where no User-Agent is specified will a random User-Agent be generated and used. This provides additional flexibility when using the `WebBaseLoader` class, allowing users to specify their own User-Agent if they have a specific need or preference, while still providing a reasonable default for cases where no User-Agent is specified.

This change has no impact on existing users who do not specify a User-Agent, as the behavior in this case remains the same. However, for users who do specify a User-Agent, their choice will now be respected and used for all subsequent requests made using the `WebBaseLoader` class.

Fixes #4167

## Before submitting

============================= test session starts ==============================
collecting ... collected 1 item

test_web_base.py::TestWebBaseLoader::test_respect_user_specified_user_agent 

============================== 1 passed in 3.64s ===============================
PASSED [100%]

## Who can review?

Community members can review the PR once tests pass. Tag maintainers/contributors who might be interested: @eyurtsev

### CODE REVIEW

**Comment by eyurtsev** [comment]
@lyz1990 change looks good -- thanks for helping out!! Would you be able to resolve the linting issue and then we can merge?

**Comment by lyz1990** [comment]
> @lyz1990 change looks good -- thanks for helping out!! Would you be able to resolve the linting issue and then we can merge?

Sure, I'd be glad to address the linting issue. I'll update the PR shortly. Thank you for the feedback!

**Comment by lyz1990** [comment]
> @lyz1990 change looks good -- thanks for helping out!! Would you be able to resolve the linting issue and then we can merge?

Updated. The function `test_respect_user_specified_user_agent` in TestWebBaseLoader now has a return type annotation.
Please let me know if there are any other changes that need to be made.

**Comment by gauravkesharwani** [comment]
please merge this fix, waiting for the fix

**Comment by lyz1990** [comment]
> please merge this fix, waiting for the fix

While we're waiting for the merge by @eyurtsev , you can use a workaround to manually set the User-Agent in your application code. Here's an example:

```python
loader = WebBaseLoader(url, header_template=your_headers)
loader.session.headers['User-Agent'] = "your user agent"
```

This way, you can specify your own User-Agent for the time being. Hope this helps!

**Comment by gauravkesharwani** [comment]
Many thanks for this, Can you add a feature for 'continue_on_failure' like we have in llamaindex. This is will be much more useful in case there is a list of urls passed, and you dont know on which url the parser will fail.

**Pull request merged**
