### PR TITLE
community: BM25Retriever preservation of document id

### PR DESCRIPTION
**Pull request by TupleType**
Currently this retriever discards document ids

### CODE REVIEW

**Comment by TupleType** [comment]
Hey @baskaryan could you please review?
Thank you!

**Review by efriis — COMMENTED** [review]
could you add a unit test?

**Comment by TupleType** [comment]
> could you add a unit test?

Done

**Comment by TupleType** [comment]
> > could you add a unit test?
> 
> Done

@efriis

**Review by efriis — APPROVED** [review]

**Pull request merged**
