### PR TITLE
community:Breebs docs retriever

### PR DESCRIPTION
**Pull request by Poissecaille**
- **Description:** Implementation of breeb retriever with integration tests -> libs/community/tests/integration_tests/retrievers/test_breebs.py and documentation (notebook) -> docs/docs/integrations/retrievers/breebs.ipynb.
  - **Dependencies:** None

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
please do NOT add a langchain entrypoint, only add to community package

other than that looks reasonable

**Comment by Poissecaille** [comment]
> please do NOT add a langchain entrypoint, only add to community package
> 
> other than that looks reasonable
Hi thank you very much for your answer!
This is my firt open source project PR i think i correctly removed the langchain entrypoint as you asked.

**Review by hwchase17 — APPROVED** [review]
lgtm, thanks!

**Review by hwchase17 — COMMENTED** [review]
just need to add it to the test for imports, and then should be good!

**Pull request merged**
