### PR TITLE
Restore self message sent before OSX 12 Monterey

### PR DESCRIPTION
**Pull request by idvorkin**

### CODE REVIEW

**Comment by idvorkin** [comment]
Still need to add unit tests, any other changes 

This depends on #14818 (I'm new here, what's the correct workflow for that?) 

FYI @YaySushi  @baskaryan

**Comment by baskaryan** [comment]
> Still need to add unit tests, any other changes
> 
> This depends on #14818 (I'm new here, what's the correct workflow for that?)
> 
> FYI @YaySushi @baskaryan

did you mean #14804?

**Comment by idvorkin** [comment]
@baskaryan  - These for merging the other one! Any other changes here before I resolve conflicts/add tests?

**Comment by baskaryan** [comment]
> @baskaryan - Thanks for merging the other one! Any other changes here before I resolve conflicts/add tests?

lgtm!

**Comment by idvorkin** [comment]
@baskaryan  - can you squash when merging, I made a bad merge :)

**Pull request merged**
