### PR TITLE
partners/mongodb: Improved search index commands

### PR DESCRIPTION
**Pull request by caseyclements**
Hardens index commands with try/except for free clusters and optional waits for syncing and tests.

[efriis](https://github.com/efriis) These are the upgrades to the search index commands (CRUD) that I mentioned.

### CODE REVIEW

**Comment by caseyclements** [comment]
@efriis I'll discuss with my team how best to make tests non-trivial  in the morning and get back to you.

**Comment by caseyclements** [comment]
Ok. Added an additional exception to pytest.raises. That's sufficient to capture all cases that I want to test that shouldn't work.

**Comment by caseyclements** [comment]
@efriis If you have a spare minute, would you please merge this? It will make the Retrievers one cleaner.

**Comment by caseyclements** [comment]
@eyurtsev Hi Eugene, would you please take a look at this? Quick and easy, and it will really help me deal with merge conflicts on #23237 (or what will be our HybridSearchRetriever PR).

**Review by efriis — APPROVED** [review]
just updated some kwargs to be keyword only (to avoid a breaking change in future of reordering positionals on things that should be kw-only)

**Comment by caseyclements** [comment]
Thanks, @efriis . Appreciate the review and additional commits.

**Pull request merged**
