### PR TITLE
Confluence DL retry/backoff

### PR DESCRIPTION
**Pull request by Jflick58**
Implemented a retry/backoff logic in response to #2473

### CODE REVIEW

**Comment by vowelparrot** [comment]
What would this look like if we used the `tenacity`'s `retry` helper (can see it used in the [openai llm](https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py))?

**Comment by Jflick58** [comment]
Interesting. I wasn’t aware of this in the codebase. I’m open to refactoring it if there is belief that tenacity offers some unique value over the current implementation.

**Comment by hwchase17** [comment]
> Interesting. I wasn’t aware of this in the codebase. I’m open to refactoring it if there is belief that tenacity offers some unique value over the current implementation.

i think main value is to just avoid having multiple implementatons of same thing. happy to help with swtiching to use that though

**Comment by Jflick58** [comment]
No worries, I’ll refactor. Probably worth learning a real package and not the same decorator function I’ve been using for years haha

**Review by hwchase17 — APPROVED** [review]
thanks!

**Pull request merged**
