### PR TITLE
Add no_avx2 to FAISS vector store

### PR DESCRIPTION
**Pull request by AliMirlou**
# Add no_avx2 to FAISS vector store

This PR adds the `no_avx2` argument and `FAISS_NO_AVX2` environment variable to `dependable_faiss_import` function to not load FAISS vector store with AVX2 optimization.

This option comes in handy when the developer wants to save the vector store to a file and load it on somewhere else. Most modern CPUs have AVX2 optimization but there are situations where the hardware is old, the `faiss-cpu` pypi package is not compiled with AVX2 flag or this feature is disabled for some reason.

I encountered this issue on a PaaS where FAISS pickle and database files created by `save_index` in Colab could not be loaded inside the Docker containers due to the platform not supporting AVX2.

@dev2049

### CODE REVIEW

**Comment by dev2049** [comment]
lgtm, thanks @AliMirlou!

**Comment by dev2049** [comment]
fixed lint and merged in #4895!

**Comment by AliMirlou** [comment]
@dev2049 Too bad though that my name didn't make it to the releases 😅

**Comment by AliMirlou** [comment]
Can I ask to become a collaborator? I'm deeply involved into LangChain now and I like to contribute more.

**Comment by dev2049** [comment]
We're really trying to keep the collaborator team small and tight-knit at the moment, so we're only considering folks who have made a good number of contributions. Definitely open to it as time goes on, but want to work with you some more first.

But we really do appreciate contributions from anyone and everyone and will do our best to review asap!

**Pull request closed without merging**
