### PR TITLE
Add integration to collect feedback on documentation

### PR DESCRIPTION
**Pull request by Anshuman71**
## Background

LangChain has become widely popular and adopted by developers. The documentation of any developer product plays a crucial role in the developer experience. Collecting feedback on the LangChain documentation will further improve the developer experience and help the community.

## Description

[Docsly](https://docsly.dev) is a feedback tool crafted for developer documentation. It lets the readers leave contextual feedback  (comments) on the documentation website and helps the maintainer by showing the feedback exactly where the user left it.

The feedback feature (like/dislike) gives a general sense of whether users are finding a particular page helpful.

  - Dependencies: Installed `@docsly/react` in the Docusaurus project
  - Tag maintainer: @baskaryan
  - Twitter handle: [sun_anshuman](https://twitter.com/sun_anshuman)

### Example project for preview

[Clerk](https://clerk.com/docs), [Tigris](https://www.tigrisdata.com/docs/), and [Dyte](https://docs.dyte.io) are using docsly in production already.

### Todo

- [ ] Sign up on [docsly.dev ](https://docsly.dev/dashboard)for a fresh account for maintainers

### Cost implications

[Docsly](https://docsly.dev) is free to use for open-source projects.

### CODE REVIEW

**Comment by Anshuman71** [comment]
Hi @baskaryan, checking in to see if I can provide any additional information for the review.

**Comment by Anshuman71** [comment]
Hi @rlancemartin, can you provide some feedback/help with this PR?

**Comment by leo-gan** [comment]
@baskaryan This PR seems important for docs.

**Comment by efriis** [comment]
Hey @Anshuman71 ! Appreciate the thought. If we decide to integrate Docsly in the future, we'll reach out!

**Pull request closed without merging**
