### PR TITLE
feat (documents): add a source code loader based on AST manipulation

### PR DESCRIPTION
**Pull request by cristobalcl**
#### Summary

A new approach to loading source code is implemented:

Each top-level function and class in the code is loaded into separate documents. Then, an additional document is created with the top-level code, but without the already loaded functions and classes.

This could improve the accuracy of QA chains over source code.

For instance, having this script:

```
class MyClass:
    def __init__(self, name):
        self.name = name

    def greet(self):
        print(f"Hello, {self.name}!")

def main():
    name = input("Enter your name: ")
    obj = MyClass(name)
    obj.greet()

if __name__ == '__main__':
    main()
```

The loader will create three documents with this content:

First document:
```
class MyClass:
    def __init__(self, name):
        self.name = name

    def greet(self):
        print(f"Hello, {self.name}!")
```

Second document:
```
def main():
    name = input("Enter your name: ")
    obj = MyClass(name)
    obj.greet()
```

Third document:
```
# Code for: class MyClass:

# Code for: def main():

if __name__ == '__main__':
    main()
```

A threshold parameter is added to control whether small scripts are split in this way or not.

At this moment, only Python and JavaScript are supported. The appropriate parser is determined by examining the file extension.

#### Tests

This PR adds:

- Unit tests
- Integration tests

#### Dependencies

Only one dependency was added as optional (needed for the JavaScript parser).

#### Documentation

A notebook is added showing how the loader can be used.

#### Who can review?

@eyurtsev @hwchase17

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
@rlancemartin we have the concept of parsers - how does this relate to that?

**Comment by hwchase17** [comment]
cc @eyurtsev for his thoughts as well

**Comment by cristobalcl** [comment]
> @rlancemartin we have the concept of parsers - how does this relate to that?

AFAIK parsers are used in LangChain to process the output of a model response and convert it to a Python struct.

In the context of this PR, parser refers to the manipulation of a source code written in a programming language, in order to separate chunks of text in a meaningful way.

Any suggestion about naming is welcome :smile:

**Comment by dev2049** [comment]
> @rlancemartin we have the concept of parsers - how does this relate to that?

@hwchase17 you're referring to BlobParsers here, right (not OutputParser)

**Comment by rlancemartin** [comment]
Nice work! Interesting PR. 

Suggestion: we can re-organize the code slightly to fit into a `loader` -> `parser` workflow as we do [here](https://github.com/hwchase17/langchain/blob/master/docs/extras/modules/data_connection/document_loaders/integrations/youtube_audio.ipynb).

(1) You should be able to use existing `FileSystemBlobLoader` [here](https://github.com/hwchase17/langchain/blob/master/langchain/document_loaders/blob_loaders/file_system.py) to load the .js or .py files. No new code should be required for loading.

(2) Then, just move your parsing logic into a new parser file in the directory [here](https://github.com/hwchase17/langchain/tree/master/langchain/document_loaders/parsers).

The UX is simple and we reduce code duplication (no new loading code). Specifically, the UX can follow what we do [here](https://github.com/hwchase17/langchain/blob/master/docs/extras/modules/data_connection/document_loaders/integrations/youtube_audio.ipynb) where the loader and parser are called:

```
# Transcribe the videos to text
loader = GenericLoader(YoutubeAudioLoader(urls, save_dir), OpenAIWhisperParser())
docs = loader.load()
```

In this case, of course it will look like:
```
# Parse js or py to docs
loader = GenericLoader(FileSystemBlobLoader(path="",glob=""), <New_Code_Parser>())
docs = loader.load()
```

Thoughts?

**Comment by cristobalcl** [comment]
Oh, right! That makes much more sense. I wasn't familiar with GenericLoader, and I wasn't sure how parsers were used. Now that's clear.

Let me refactor the code.

**Comment by cristobalcl** [comment]
Done! It's much better now, in my opinion.

One thing to note: I've reused `langchain.text_splitter.Language` to avoid duplicate things, but maybe that class should be moved to a global module.

More suggestions are welcome!

**Comment by cristobalcl** [comment]
Exactly, it only splits, or segments, the source code based on top-level classes and functions, and the remaining code.

I've edited the documentation trying to make it more straightforward. Also, the docstring mentions the only parameters that can be configured: `language` and `parser_threshold`.

Should I add an example in the notebook like the one I mention in the first post in this PR? I thought that the code and the results would be self-explanatory, but perhaps it's not clear enough.

**Comment by rlancemartin** [comment]
> Exactly, it only splits, or segments, the source code based on top-level classes and functions, and the remaining code.
> 
> I've edited the documentation trying to make it more straightforward. Also, the docstring mentions the only parameters that can be configured: `language` and `parser_threshold`.
> 
> Should I add an example in the notebook like the one I mention in the first post in this PR? I thought that the code and the results would be self-explanatory, but perhaps it's not clear enough.

 Nice work! No need to add more examples. I'm running tests now and will plan to merge this once they all pass.

**Comment by cristobalcl** [comment]
Nice, thanks for your help, and for that last fixes! :smiley:

**Pull request merged**
