### PR TITLE
Support for PDF in WebResearchRetriever (plus sources fix)

### PR DESCRIPTION
**Pull request by BabellDev**
**Description:**
-  `WebResearchRetriever` would fail on PDF documents.  To address this I have created a new `async_pdf` document loader and integrated with `WebResearchRetriever`.  There is a lot of similarity with `async_html`, and certainly opportunity to share code via base class (or consolidate both into a single `async_web` class).  
- The `async_pdf` class has its own PDF download code, rather than use `PyPDFLoader` directly to download the remote file.  This is because `PyPDFLoader` does not currently support timeouts or optional SSL verify (no timeouts can result in infinite hang).
- Added a new method that inspects the content-type of the remote URL and only keeps known types.  This should reduce content decoding errors
- Also added a small fix for missing sources coming from `RetrievalQAWithSourcesChain`.  The regex in `_split_sources` would get confused if there is a newline between "SOURCES:" and the source strings in the answer.

**Issues:**  https://github.com/langchain-ai/langchain/issues/11031, https://github.com/langchain-ai/langchain/issues/10575

### CODE REVIEW

**Comment by BabellDev** [comment]
@hwchase17 please review/merge when you are able to, thanks!

**Comment by hschmied** [comment]
very nice; this would fix a big issue for me... just wondering if there's some idea when this PR might make it into a release (and wait for it), or am I better of patching it on my own. thx!

**Comment by BabellDev** [comment]
@hschmied I can't say when this might get merged,  that will be up to @hwchase17 and the other maintainers.  If you need this fix soon then you should probably patch manually.  Unfortunately this PR was created back in Sept 2023, so it's out of sync with the main branch now.  You shouldn't have too much trouble integrating it with the latest code though.  

I'm happy to answer any questions you may have if you run into trouble.

**Comment by baskaryan** [comment]
Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

**Comment by bbellcopperleaf** [comment]
> Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

No problem @baskaryan, I will resolve the conflicts. I likely won't have time to look at it until tomorrow though.  Thanks!

**Comment by BabellDev** [comment]
> > Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve
> 
> No problem @baskaryan, I will resolve the conflicts. I likely won't have time to look at it until tomorrow though. Thanks!

That was probably confusing, I forgot I was signed in with my work account.  🤦‍♂️  bbellcopperleaf and I are one and the same

**Comment by BabellDev** [comment]
> Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

Just had a look.  Things have deviated so much since the creation of this PR, that I think the path of least resistance might be to abandon this PR and start fresh.

**Pull request closed without merging**
