### PR TITLE
milvus: add_db_milvus_connection

### PR DESCRIPTION
**Pull request by venkatram-dev**
Thank you for contributing to LangChain!

- [x] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"
  - "libs: langchain_milvus: add db name to milvus connection check"

- [x] **PR message**: ***Delete this entire checklist*** and replace with
    - **Description:**  add db name to milvus connection check
    - **Issue:** https://github.com/langchain-ai/langchain/issues/25277

- [x] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Comment by venkatram-dev** [comment]
@baskaryan , made a commit to fix linting errors. Please retry the CI checks.

**Comment by zc277584121** [comment]
LGTM

**Comment by hasansustcse13** [comment]
This problem was reported by me in Milvus. This fix now create new instance every time as milvus team doesn't provide db_name in the connection list yet. I am wondering why this pr has been merged despite dependency of milvus. 
https://github.com/milvus-io/pymilvus/issues/2161
@efriis

**Comment by efriis** [comment]
hey! if there are outstanding issues, please open them against the https://github.com/langchain-ai/langchain-milvus repo, which is primarily maintained by the milvus team including @zc277584121 who approved this PR

**Comment by hasansustcse13** [comment]
@efriis First Pymilvus team need to adjust the problem. Then We can integrate in langchain/ langchain milvus (which already done in this pr) . I have reported this a long time ago but they didn't fix it. That's why I have made a merge request in milvus-io. Let's see when they merge it

https://github.com/milvus-io/pymilvus/pull/2285

**Pull request merged**
