### PR TITLE
Added ChoiceOutputParser

### PR DESCRIPTION
**Pull request by JacobFV**
feature: #4256

Note: Still need to add tests

### CODE REVIEW

**Comment by JacobFV** [comment]
These checks are failing because I added the `python-levenshtein` package to `pyproject.toml`:

```
Because langchain depends on python-levenshtein (^0.21.0) which doesn't match any versions, version solving failed.
Error: Process completed with exit code 1.
```

How can I fix this?

**Comment by vowelparrot** [comment]
> These checks are failing because I added the `python-levenshtein` package to `pyproject.toml`:
> 
> ```
> Because langchain depends on python-levenshtein (^0.21.0) which doesn't match any versions, version solving failed.
> Error: Process completed with exit code 1.
> ```
> 
> How can I fix this?

We use lazy imports for non-core dependencies! See e.g., https://github.com/hwchase17/langchain/blob/6f386628c2fc7e7dd45262c8c2a29b07c46f70ef/langchain/vectorstores/opensearch_vector_search.py#L20

**Comment by JacobFV** [comment]
Fixed dep import issue

**Comment by JacobFV** [comment]
> > These checks are failing because I added the `python-levenshtein` package to `pyproject.toml`:
> > ```
> > Because langchain depends on python-levenshtein (^0.21.0) which doesn't match any versions, version solving failed.
> > Error: Process completed with exit code 1.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How can I fix this?
> 
> We use lazy imports for non-core dependencies! See e.g.,
> 
> https://github.com/hwchase17/langchain/blob/6f386628c2fc7e7dd45262c8c2a29b07c46f70ef/langchain/vectorstores/opensearch_vector_search.py#L20
> 
> Though also - `python-levenshtein` is GPL licensed, which means people wouldn't be able to use it for commercial use. We may be able to do something simple with jaccard similarity over character bigrams if we we want, or could re-implement somewhere

Done

**Comment by leo-gan** [comment]
@JacobFV Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

**Comment by JacobFV** [comment]
Don't have time to finish

**Pull request closed without merging**
