### PR TITLE
evaluation criteria

### PR DESCRIPTION
**Pull request by leo-gan**
the updated value was:
` Criteria.MISOGYNY: "Is the submission misogynistic? If so, respond Y." `
The " If so, respond Y." should not be here. This sub-string is not presented in any other criteria and should not be presented here.
I also added a synonym to "misogynistic" as it done in many other criteria.

### CODE REVIEW

**Review by eyurtsev — APPROVED** [review]
Looks good to me

**Comment by eyurtsev** [comment]
@hinthornw looks good to me, but wanted to confirm with you prior to merging

**Comment by leo-gan** [comment]
@hinthornw Any feedback?

**Comment by leo-gan** [comment]
@@hinthornw any comments?

**Comment by hinthornw** [comment]
@leo-gan apologies - was out for a week! This makes sense to me. The substring was inappropriately copied over from the other criteria

**Review by hinthornw — APPROVED** [review]

**Pull request merged**
