### PR TITLE
Batching added for ChromaDB Similarity Search

### PR DESCRIPTION
**Pull request by berkedilekoglu**
ChromaDB supports batching queries for efficient searching. Currently, the APIs used for OpenAI also support batching, so I have added batching functions for OpenAI embeddings. However, the batching implementation may vary depending on the device or API used for HuggingFace, so I haven't made any additions for that. Therefore, the functions check the embedding being used.

**_Current Situation:_**
Since there is no batching, each query is sent and processed individually.

**_Test Case:_**
I have a query set consisting of 1500 questions. In the current situation, when I retrieve the answers without batching, it takes 8.5 minutes to process all 1500 questions.

**_With Batching:_**
ChromaDB already has a query function that supports batching. Utilizing that, I have added `similarity_search_by_batch` and `similarity_search_with_score_by_batch` functions in addition to `similarity_search` and `similarity_search_with_score` functions. Since the output types of the functions will change, I didn't want to write them within the same function. If you want, we can also update it that way.

**_Test Case:_**

**_After Implementing Batching:_**

when I retrieve the answers with a batch size of 256, all 1500 questions are processed in 12 seconds. When using a batch size of 512, the answers are returned in 6 seconds.

_It is also important for decreasing request number for OpenAI API._ 

Additionally, I updated the `_results_to_docs_and_scores` function to `_results_to_docs_and_scores_for_batches`. Now the function works appropriately for batching and returns the results. Since the returned value has changed from `List[Tuple[Document, float]]` to `List[List[Tuple[Document, float]]],` I have written a separate function for handling this conversion.

my twitter: [berkedilekoglu](https://twitter.com/berkedilekoglu)

_**TEST AND DOCUMENTS**_

I think it will be necessary to add test cases for these functions, but I would greatly appreciate your help since I haven't written tests before :)

If you're okay with these changes, I can add the necessary examples to the documentation!

Thank you very much!
Berke

  VectorStores / Retrievers / Memory
  - @dev2049, @hwchase17

### CODE REVIEW

**Comment by hwchase17** [comment]
whats the main use case for batch searching?

**Comment by berkedilekoglu** [comment]
Wouldn't this approach make sense for the update_document function below as well? 

https://github.com/hwchase17/langchain/blob/2a4b32dee24c22159805f643b87eece107224951/langchain/vectorstores/chroma.py#L355-L375

Currently, the defined update_document function only takes a single document and its ID for updating. However, Chroma can update multiple documents by taking a list of IDs and documents for batch updates. 

I update the Chroma vectorstore with refreshed information from my website every 20 minutes. Updating the update_document function to perform simultaneous updates for each changed piece of information would significantly reduce the update time in such use cases.

If it makes sense I can work on it within this request.

@hwchase17

**Comment by leo-gan** [comment]
@berkedilekoglu Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by berkedilekoglu** [comment]
@leo-gan Hi, I fix merging issues and reopened that pr. However have been a long time since created that one. 

- When I wrote this pr, only openai embeddings supports batching. Because of that reason my function in this pr checks used embeddings and only supports OpenAI. If now the other embeddings support batching I can update.

**Pull request closed without merging**
