### PR TITLE
partners: replace deprecated .dict() with .model_dump() in openai base.py

### PR DESCRIPTION
**Pull request by SavvasMohito**
- **Description:** Same as #15489 but under the correct package this time. Using pydantic's new `.model_dump()` function. It produces the same result as `.dict()` without throwing a deprecation warning message, 
  - **Issue:** #15997 ,
  - **Dependencies:** None,
  - **Twitter handle:** @mantzouranidis

Thanks :)

### CODE REVIEW

**Comment by eyurtsev** [comment]
LangChain needs to be both pydantic 1 and 2 compatible for now.

Running tests expecting the tests to fail. If they don't fail we should confirm why not.

**Comment by SavvasMohito** [comment]
@eyurtsev The tests do fail as you suspected. I made an additional commit to satisfy both v1 and v2 (and 3) but also avoid the deprecation warnings. Local tests do not throw any errors on my end

**Comment by SavvasMohito** [comment]
so no merge @baskaryan? 😔

**Comment by sam-cohan** [comment]
When do we expect this to be solved, it is peppering our code with lots of warnings...

**Comment by sam-cohan** [comment]
btw, Ideally the PR should cover all instances of this problem (for example the embeddings module has the same issue)

**Comment by baskaryan** [comment]
@eyurtsev i actually think any OpenAI-returned object, whether you've got pydantic v1 or v2 installed, should support model_dump https://github.com/openai/openai-python/blob/d231d1fa783967c1d3a1db3ba1b52647fff148ac/src/openai/_models.py#L150

**Comment by SavvasMohito** [comment]
great observation @baskaryan. they seem to be using .dict() under the hood [here](https://github.com/openai/openai-python/blob/d231d1fa783967c1d3a1db3ba1b52647fff148ac/src/openai/_models.py#L189) but through the model_dump() function name in case of pydantic v1.

**Comment by eyurtsev** [comment]
Ah if OpenAI already supports it we can just upgrade

**Comment by SavvasMohito** [comment]
Closed by mistake, re-opened in #17404. Sorry 😢

**Pull request closed without merging**
