### PR TITLE
Harrison/improve cache

### PR DESCRIPTION
**Pull request by hwchase17**
make it so everything goes through generate, which removes the need for two types of caches

### CODE REVIEW

**Comment by hwchase17** [comment]
@BenderV this has the effect of removing the need for two separate types of LLM caches. thoguths?

**Comment by agola11** [comment]
This LGTM overall but the naming convention for base classes inconsistent. We should pick a convention and stick with it. For chain the base is `Chain`, for agents, the base is `Agent`, for llms the base is `BaseLLM` according to this PR?

**Comment by hwchase17** [comment]
> This LGTM overall but the naming convention for base classes inconsistent. We should pick a convention and stick with it. For chain the base is `Chain`, for agents, the base is `Agent`, for llms the base is `BaseLLM` according to this PR?

great point, made an issue https://github.com/hwchase17/langchain/issues/373 (we should do base imo)

**Comment by BenderV** [comment]
Amazing 👍

**Pull request merged**
