### PR TITLE
community[patch]: add missing chunk parameter for _stream/_astream

### PR DESCRIPTION
**Pull request by mackong**
- Description: Add missing chunk parameter for _stream/_astream for some chat models, make all chat models in a consistent behaviour.
- Issue: N/A
- Dependencies: N/A

### CODE REVIEW

**Review by eyurtsev — APPROVED** [review]

**Comment by eyurtsev** [comment]
@mackong thank you very much for the patch!

There's another issue with most of these models. They should be calling the callback prior to yielding the chunk rather than after yielding the chunk

**Comment by eyurtsev** [comment]
@mackong if your'e able to resolve the linting error, we can merge right away

**Comment by mackong** [comment]
> @mackong if your'e able to resolve the linting error, we can merge right away

Fixed.

**Comment by mackong** [comment]
> @mackong thank you very much for the patch!
> 
> There's another issue with most of these models. They should be calling the callback prior to yielding the chunk rather than after yielding the chunk. If you have interest, we'd appreciate another PR for that as well :)

OK, I'll fix it in another PR.

**Review by eyurtsev — APPROVED** [review]

**Comment by eyurtsev** [comment]
merge when tests pass

**Pull request merged**
