### PR TITLE
partner: Add Naver partner package v1

### PR DESCRIPTION
**Pull request by hyper-clova**
Description: add Naver partner packages including ChatClovaX, ClovaXEmbeddings
Dependencies: langchain-core, httpx, httpx-sse

- [x] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [x] **PR message**: ***Delete this entire checklist*** and replace with
    - **Description:** a description of the change
    - **Issue:** the issue # it fixes, if applicable
    - **Dependencies:** any dependencies required for this change
    - **Twitter handle:** if your PR gets announced, and you'd like a mention, we'll gladly shout you out!

- [x] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [ ] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Comment by efriis** [comment]
Hello! Please move this implementation to the community package, as directed [here](https://python.langchain.com/v0.2/docs/contributing/integrations/#partner-package-in-langchain-repo)

If I'm mistaken and you're in contact with someone else on our team, please let me know! Happy to reopen :)

**Comment by hyper-clova** [comment]
I didn't know that contact had to be done first. Could you please guide me on how to contact to apply partner package?

**Comment by hyper-clova** [comment]
@efriis Hello, I was informed that `Julia Schottenstein` ([julia@langchain.dev](mailto:julia@langchain.dev)) had been in contact with our representative `Joohee Ahn`([joohee.ahn@navercorp.com](mailto:joohee.ahn@navercorp.com)) from April to May.

**Comment by efriis** [comment]
Looks like she gave the same recommendation to implement it as a community package :)

**Comment by hyper-clova** [comment]
Hello @efriis ,

It seems there may have been some miscommunication both in our teams and between your team and us. We've been trying to reconnect with Julia regarding the process for registering our partner package after submitting this PR but still waiting for a response. 

While email might be a more effective channel for detailed discussions, we consider going as a partner package for the first option as our service includes unique base chat models and embedding models with a significant user base (> 3k enterprise clients). Additionally, we are also integrating the models (possibly using LangChain) with the services of NAVER, a leading online platform with ~43M MAUs.

We believe this could be mutually beneficial, enhancing LangChain’s market and geographic presence, particularly in Korea and East Asia as we are already sponsoring LangChain communities in Korea (such as LangChain KR), and will expand these kinds of efforts hereafter registering the partner package.

Thanks in advance for considering this, and we look forward to your guidance on how best to proceed.

**Pull request closed without merging**
