### PR TITLE
langchain_community.vectorstores.azuresearch: Raise LangChainException instead of bare Exception

### PR DESCRIPTION
**Pull request by marcgibbons**
Raise `LangChainException` instead of `Exception`. This alleviates the need for library users to use bare try/except to handle exceptions raised by `AzureSearch`.

### CODE REVIEW

**Review by eyurtsev — APPROVED** [review]

**Comment by eyurtsev** [comment]
Closing PR due to lack of resolving the failed tests

**Comment by marcgibbons** [comment]
@eyurtsev It's unclear that these test failures are related to changes this PR? 

https://github.com/langchain-ai/langchain/actions/runs/10051417176/job/27780988076

**Comment by eyurtsev** [comment]
@marcgibbons you're correct -- just need to update the branch

**Comment by marcgibbons** [comment]
@eyurtsev 🤞

**Pull request merged**
