### PR TITLE
Add callback to preprocess agent scratchpad data

### PR DESCRIPTION
**Pull request by prakashar11**
**Requirement**

Invoke data scan & mask guardrails before agent scratchpad data is included in the prompt. This would be useful to either mask different sensitive data or to maintain audit logs of the agent generated data in prompts 

**Proposed Changes**

Invoke preprocess callback method during preparation of prompt.

**How to use** 

Sample data mask callback manager to mask AWS account numbers included as agent output

````
class BaseMaskerHandler(BaseCallbackHandler):
  ....
  def on_selected_inputs_preprocess_for_prompt(
            self, 
            text: str,
            **kwargs: Optional[str],
    ) -> Any:
        if 'agent_scratchpad' in text:
            if text['agent_scratchpad']:
                text_of_interest = text['agent_scratchpad']
                import re
                # replace AWS account number
                to_mask = re.findall(r"(\d{12})", text_of_interest)
                for i, item in enumerate(to_mask):
                    lookup_name = f"aws_account_{i+1}"
                    text_of_interest = text_of_interest.replace(item, lookup_name)
                text['agent_scratchpad'] = text_of_interest

### CODE REVIEW

**Comment by hwchase17** [comment]
interesting idea. im not sure this is the right place to put it tbh. i feel like this is probably something that belongs on the tool wrapper

**Comment by prakashar11** [comment]
thank you @hwchase17. I agree, a similar callback should also be available as agent wrapper as treatment for data could be different for different agents. However, from InfoSec/privacy team perspective, to begin with, having a centralized callback helps in consolidating governance policies. Thanks once again!

**Comment by prakashar11** [comment]
Hi @agola11 , please let me know whether there is an interest to accept this PR. thanks in advance

**Comment by baskaryan** [comment]
like @hwchase17 said, probably something that should be handled in more core agent/tooling logic. but definitely open to more work in this direction! closing for now but let me know if I'm missing anything

**Pull request closed without merging**
