### PR TITLE
Support for SPARQL

### PR DESCRIPTION
**Pull request by felixocker**
# [SPARQL](https://www.w3.org/TR/rdf-sparql-query/) for [LangChain](https://github.com/hwchase17/langchain)

## Description
LangChain support for knowledge graphs relying on W3C standards using RDFlib: SPARQL/ RDF(S)/ OWL with special focus on RDF \
* Works with local files, files from the web, and SPARQL endpoints
* Supports both SELECT and UPDATE queries
* Includes both a Jupyter notebook with an example and integration tests

## Contribution compared to related PRs and discussions
* [Wikibase agent](https://github.com/hwchase17/langchain/pull/2690) - uses SPARQL, but specifically for wikibase querying
* [Cypher qa](https://github.com/hwchase17/langchain/pull/5078) - graph DB question answering for Neo4J via Cypher
* [PR 6050](https://github.com/hwchase17/langchain/pull/6050) - tries something similar, but does not cover UPDATE queries and supports only RDF
* Discussions on [w3c mailing list](mailto:semantic-web@w3.org) related to the combination of LLMs (specifically ChatGPT) and knowledge graphs

## Dependencies
* [RDFlib](https://github.com/RDFLib/rdflib)

## Tag maintainer
Graph database related to memory -> @hwchase17

### CODE REVIEW

**Review by hwchase17 — APPROVED** [review]
this looks fantastic! thanks so much

**Comment by marioscrock** [comment]
@felixocker thank you for this PR! I would like to kindly ask if you can help me with a related issue. I keep receiving warning messages from rdflib when loading an RDF file even if URIs are valid.
```
<http://xmlns.com/foaf/0.1/title does not look like a valid URI, trying to serialize this will break.
<http://xmlns.com/foaf/0.1/title> ( does not look like a valid URI, trying to serialize this will break.
<http://xmlns.com/foaf/0.1/title> (title does not look like a valid URI, trying to serialize this will break.
<http://xmlns.com/foaf/0.1/title> (title,  does not look like a valid URI, trying to serialize this will break.
<http://xmlns.com/foaf/0.1/title> (title, ) does not look like a valid URI, trying to serialize this will break.
```
I did some tests locally and it seems to me that the problem may be related to the implementation of the `_res_to_str` function. I modified this as follows and it seems to work fine (`return f"<{res[var]}> ({self._get_local_name(res[var])}, {str(res['com'])})"`).

**Comment by felixocker** [comment]
@marioscrock thanks! yeah, seems like this is due to the concatenation of strings and the URI in the `_res_to_str` function. I just created PR #8025 with a fix

**Comment by marioscrock** [comment]
@felixocker thank you for the quick feedback and fix!

**Pull request merged**
