### PR TITLE
Google Search API integration with serper.dev (wrapper, tests, docs, …

### PR DESCRIPTION
**Pull request by rogerserper**
Adds Google Search integration with [Serper](https://serper.dev) a low-cost alternative to SerpAPI (10x cheaper + generous free tier). Includes documentation, tests and examples. Hopefully I am not missing anything.

Developers can sign up for a free account at [serper.dev](https://serper.dev) and obtain an api key.

## Usage

```python
from langchain.utilities import GoogleSerperAPIWrapper
from langchain.llms.openai import OpenAI
from langchain.agents import initialize_agent, Tool

import os
os.environ["SERPER_API_KEY"] = ""
os.environ['OPENAI_API_KEY'] = ""

llm = OpenAI(temperature=0)
search = GoogleSerperAPIWrapper()
tools = [
    Tool(
        name="Intermediate Answer",
        func=search.run
    )
]

self_ask_with_search = initialize_agent(tools, llm, agent="self-ask-with-search", verbose=True)
self_ask_with_search.run("What is the hometown of the reigning men's U.S. Open champion?")
```

### Output
```
Entering new AgentExecutor chain...
 Yes.
Follow up: Who is the reigning men's U.S. Open champion?
Intermediate answer: Current champions Carlos Alcaraz, 2022 men's singles champion.
Follow up: Where is Carlos Alcaraz from?
Intermediate answer: El Palmar, Spain
So the final answer is: El Palmar, Spain

> Finished chain.

'El Palmar, Spain'
```

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
awesome!

let's not change the self_ask_with_search.ipynb file - no reason to. otherwise lgtm!

**Comment by rogerserper** [comment]
Thanks for the quick feedback! I reverted self_ask_with_search.ipynb and fixed the types + linting issues.

**Comment by rogerserper** [comment]
@hwchase17 could you review again?

**Review by hwchase17 — APPROVED** [review]
looks great - thanks!

**Pull request merged**
