### PR TITLE
Feature/4250 concise api

### PR DESCRIPTION
**Pull request by JacobFV**
feature: 4250

Note: still need to write tests

### CODE REVIEW

**Comment by JacobFV** [comment]
Added tests and ready to merge

**Comment by JacobFV** [comment]
Added tests. Working on notebook.

**Comment by JacobFV** [comment]
Just to clarify, this branch is not ready to merge. Need to wait until the llm cache (breaking commit merged into master sometime today) is fixed. Then i need to prompt engineer the rulex and other functions

**Comment by leo-gan** [comment]
@JacobFV Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by JacobFV** [comment]
Don't have time to finish

**Pull request closed without merging**
