### PR TITLE
openai, azure: update model_name in ChatResult to use name from API response

### PR DESCRIPTION
**Pull request by isatyamks**
The response.get("model", self.model_name) checks if the model key exists in the response dictionary. If it does, it uses that value; otherwise, it uses self.model_name.

### CODE REVIEW

**Comment by isatyamks** [comment]
@efriis, please proceed with the merge if the changes are accurate and appropriate.

**Review by ccurme — APPROVED** [review]
This will change model names for aliases (e.g., "gpt-4o" -> "gpt-4o-2024-05-13") and for Azure ("gpt-35-turbo" -> "gpt-3.5-turbo").

I think this is an improvement but let's change the title before merging so the impact is clear to users, e.g., `openai, azure: update model_name in ChatResult to use name from API response`

**Comment by bantucaravan** [comment]
resolves #22516

**Comment by bantucaravan** [comment]
Thanks for fixing this and merging this so quickly, this was my first issue and it was so nice to see it acted on so fast @isatyamks @ccurme

**Pull request merged**
