### PR TITLE
community[patch]: fix sqlalchemy v1

### PR DESCRIPTION
**Pull request by efriis**

### CODE REVIEW

**Review by eyurtsev — APPROVED** [review]

**Comment by eyurtsev** [comment]
Do we need a try import to support more than one version of sqlalchemy?

**Review by hwchase17 — APPROVED** [review]

**Comment by Jflick58** [comment]
Hoping this is merged and released soon... this is blocking a deployment internally at my org.

**Comment by efriis** [comment]
Oh this store was actually deleted yesterday instead due to some other issues with it as well that will be difficult to mitigate once people store lots of data with it and need to migrate their dbs. Next release will be fixed for you unless you were relying on the sql store! #16912

**Comment by Abe410** [comment]
> Oh this store was actually deleted yesterday instead due to some other issues with it as well that will be difficult to mitigate once people store lots of data with it and need to migrate their dbs. Next release will be fixed for you unless you were relying on the sql store! #16912

I am still getting the module import error.

```python
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/home/airflow/.local/lib/python3.10/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/airflow/.local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    config.load()
  File "/home/airflow/.local/lib/python3.10/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/airflow/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/airflow/tm-ml-chat/main.py", line 6, in <module>
    import chat
  File "/home/airflow/chat.py", line 84, in <module>
    from langchain.retrievers.web_research import WebResearchRetriever
  File "/home/airflow/.local/lib/python3.10/site-packages/langchain/retrievers/__init__.py", line 29, in <module>
    from langchain.retrievers.multi_vector import MultiVectorRetriever
  File "/home/airflow/.local/lib/python3.10/site-packages/langchain/retrievers/multi_vector.py", line 11, in <module>
    from langchain.storage._lc_store import create_kv_docstore
  File "/home/airflow/.local/lib/python3.10/site-packages/langchain/storage/__init__.py", line 15, in <module>
    from langchain.storage.file_system import LocalFileStore
  File "/home/airflow/.local/lib/python3.10/site-packages/langchain/storage/file_system.py", line 8, in <module>
    from langchain.storage.exceptions import InvalidKeyException
  File "/home/airflow/.local/lib/python3.10/site-packages/langchain/storage/exceptions.py", line 1, in <module>
    from langchain_community.storage.exceptions import InvalidKeyException
  File "/home/airflow/.local/lib/python3.10/site-packages/langchain_community/storage/__init__.py", line 14, in <module>
    from langchain_community.storage.sql import (
  File "/home/airflow/.local/lib/python3.10/site-packages/langchain_community/storage/sql.py", line 9, in <module>
    from sqlalchemy import JSON, UUID
ImportError: cannot import name 'UUID' from 'sqlalchemy' (/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/__init__.py)
```

I am on langchain 0.1.5.

**Pull request closed without merging**
