### PR TITLE
refactor: Code Refactoring of Vertex AI Components

### LINKED ISSUE #11961: Issue: TypeError: TextGenerationModel.predict() got an unexpected keyword argument 'candidate_count'
### Issue you'd like to raise.

I got this error when I built a ChatBot with Langchain using VertexAI. I'm seeing this error and couldn't find any details so far.

File /opt/conda/lib/python3.10/site-packages/langchain/llms/vertexai.py:100, in completion_with_retry.<locals>._completion_with_retry(*args, **kwargs)
     98 @retry_decorator
     99 def _completion_with_retry(*args: Any, **kwargs: Any) -> Any:
--> 100     return llm.client.predict(*args, **kwargs)

TypeError: TextGenerationModel.predict() got an unexpected keyword argument 'candidate_count'

### Suggestion:

_No response_

### PR DESCRIPTION
**Pull request by holtskinner**
- Improved Readability/Efficiency by Code Refactoring of Vertex AI Components
- Fixes #11961
  - Adds error handling for aiplatform versions <1.35.0

### CODE REVIEW

**Comment by holtskinner** [comment]
@baskaryan, @eyurtsev, @hwchase17 ready for review

**Comment by holtskinner** [comment]
@lkuligin Could you also take a look?

**Comment by holtskinner** [comment]
@baskaryan @hwchase17 @leo-gan This is ready for review

**Comment by lkuligin** [comment]
SGTM, thanks!

**Comment by holtskinner** [comment]
@baskaryan @eyurtsev can this please be reviewed?

**Comment by efriis** [comment]
@holtskinner or @lkuligin - sorry for the delay! Looks like there are some conflicts with #13917 in llms/vertexai.py that I'd love some help resolving before merging. Assuming some of the other changes are still valuable at a minimum!

**Pull request closed without merging**
