### PR TITLE
Framework for supporting more languages in LanguageParser

### LINKED ISSUE #8405: Add more CodeSegmenters
### Feature request

I'm interested in the code segmenters created. So far we have python and javascript. I'm looking for a typescript one in particular, the JS one marks my typescript as invalid. But in general, having the language support shown in the text splitter Language enum would be ideal but with full on parsing. 

### Motivation

This call is ok to start: 
`RecursiveCharacterTextSplitter.get_separators_for_language(Language.JS)`
but when we're splitting by the word function we're cutting off `export async` or `default`, and especially JsDoc, which is probably the best think to start a chunk of a function with. 

Splitting by keywords like this is kinda clunky as a long term solution because of the above cases and others, having something that's more carefully splitting files up would be better. 

### Your contribution

Maybe instead of a parser like eprisma, there's just a generic one that's powered by an LLM.

### LINKED ISSUE #10996: Support for CPP in LangaugeParser is not complete
### System Info

Langchain v0.0.225

### Who can help?

_No response_

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.text_splitter import Language
from langchain.document_loaders.generic import GenericLoader
from langchain.document_loaders.parsers import LanguageParser

loader = GenericLoader.from_filesystem(
    repo_path,
    glob="**/*",
    suffixes=[".h", ".c"],
    parser=LanguageParser(language=Language.CPP)
)

File ~/ML/llama-venv/lib64/python3.11/site-packages/langchain/document_loaders/parsers/language/language_parser.py:116, in LanguageParser.lazy_parse(self, blob)
    107     yield Document(
    108         page_content=code,
    109         metadata={
   (...)
    112         },
    113     )
    114     return
--> 116 self.Segmenter = LANGUAGE_SEGMENTERS[language]
    117 segmenter = self.Segmenter(blob.as_string())
    118 if not segmenter.is_valid():

**KeyError: <Language.CPP: 'cpp'>**

### Expected behavior

Currently only JS and Python are supported in LANGUAGE_SEGMENTERS and the ask is to support CPP as well.

### LINKED ISSUE #11229: Add support for a variety of languages to LanguageParser
### Feature request

[LanguageParser](https://github.com/langchain-ai/langchain/blob/e9b51513e9bab738c741a348ffbf0f36ce19faf6/libs/langchain/langchain/document_loaders/parsers/language/language_parser.py#L21C7-L21C21) is a parser for Document Loaders that, given source code, splits each top-level function or class into separate documents. As stated in its documentation:

> This approach can potentially improve the accuracy of QA models over source code.
>
> Currently, the supported languages for code parsing are Python and JavaScript.

We would like to add support for additional languages, such as C, C++, Rust, Ruby, Perl, and so on.

### Motivation

There is an [open request](https://github.com/langchain-ai/langchain/issues/10996) for "CPP" (presumably C++) support. By integrating a generic parsing library (such as [tree-sitter](https://github.com/tree-sitter/py-tree-sitter#py-tree-sitter)), we could make LanguageParser work with many more languages, and thus be more generally useful.

### Your contribution

We intend to submit a pull request for this issue no later than mid-November, and likely sooner.

### PR DESCRIPTION
**Pull request by ThatsJustCheesy**
## Description

I am submitting this for a school project as part of a team of 5. Other team members are @LeilaChr, @maazh10, @Megabear137, @jelalalamy. This PR also has contributions from community members @Harrolee and @Mario928.

Initial context is in the issue we opened (#11229).

This pull request adds:

- Generic framework for expanding the languages that `LanguageParser` can handle, using the [tree-sitter](https://github.com/tree-sitter/py-tree-sitter#py-tree-sitter) parsing library and existing language-specific parsers written for it
- Support for the following additional languages in `LanguageParser`:
  - C
  - C++
  - C#
  - Go
  - Java (contributed by @Mario928 https://github.com/ThatsJustCheesy/langchain/pull/2)
  - Kotlin
  - Lua
  - Perl
  - Ruby
  - Rust
  - Scala
  - TypeScript (contributed by @Harrolee https://github.com/ThatsJustCheesy/langchain/pull/1)

Here is the [design document](https://docs.google.com/document/d/17dB14cKCWAaiTeSeBtxHpoVPGKrsPye8W0o_WClz2kk) if curious, but no need to read it.

## Issues

- Closes #11229
- Closes #10996
- Closes #8405

## Dependencies

`tree_sitter` and `tree_sitter_languages` on PyPI. We have tried to add these as optional dependencies.

## Documentation

We have updated the list of supported languages, and also added a section to `source_code.ipynb` detailing how to add support for additional languages using our framework.

## Maintainer

- @hwchase17 (previously reviewed https://github.com/langchain-ai/langchain/pull/6486)

Thanks!!

## Git commits

We will gladly squash any/all of our commits (esp merge commits) if necessary. Let us know if this is desirable, or if you will be squash-merging anyway.

### CODE REVIEW

**Comment by LeilaChr** [comment]
Hi @eyurtsev I noticed that you reviewed the COBOL parser PR. Pinging if you have time to review this, which is similar :)

**Comment by eickeBuecking** [comment]
Hi @eyurtsev , is there a chance to move this one forward? It would be nice to get a couple of languages more covered! Thanks in advance!

**Comment by oatsvine** [comment]
I've been working from this branch but it's falling behind. I hesitate to spend time solving merge conflicts. Is this likely to be merge or are you going in a different direction to support language parsers?

**Comment by Harrolee** [comment]
@rlancemartin can you give us feedback on this PR?

**Comment by santhoshraje** [comment]
Is there any update on this PR? Is it going to be merged or closed?

**Comment by LeilaChr** [comment]
Hi @baskaryan I fixed the lint issues and our tests pass locally, we would appreciate if you could take another look at our PR.

**Comment by Microsvuln** [comment]
@baskaryan It would be great if can check the PR :-)

**Comment by ThatsJustCheesy** [comment]
@Microsvuln it's merged now :)

**Comment by Microsvuln** [comment]
@ThatsJustCheesy That's awesome, thanks!

**Pull request merged**
