### PR TITLE
community: Milvus supports add & delete texts by ids

### LINKED ISSUE #30112: [Feature]: Delete entities by ID
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

For use with langchain's indexing API, it would be necessary to be able to delete entities by ID: https://python.langchain.com/docs/modules/data_connection/indexing
[Current documentation of deleting data](https://milvus.io/docs/delete_data.md) doesn't show any possibility to do so.

### Describe the solution you'd like.

Entities can also be deleted by a known ID.

### Describe an alternate solution.

_No response_

### Anything else? (Additional Context)

_No response_

### PR DESCRIPTION
**Pull request by jaelgu**
# Description

To support [langchain indexing](https://python.langchain.com/docs/modules/data_connection/indexing) as requested by users, vectorstore Milvus needs to support:
- document addition by id (`add_documents` method with `ids` argument)
- delete by id (`delete` method with `ids` argument)

Example usage:

```python
from langchain.indexes import SQLRecordManager, index
from langchain.schema import Document
from langchain_community.vectorstores import Milvus
from langchain_openai import OpenAIEmbeddings

collection_name = "test_index"
embedding = OpenAIEmbeddings()
vectorstore = Milvus(embedding_function=embedding, collection_name=collection_name)

namespace = f"milvus/{collection_name}"
record_manager = SQLRecordManager(
    namespace, db_url="sqlite:///record_manager_cache.sql"
)
record_manager.create_schema()

doc1 = Document(page_content="kitty", metadata={"source": "kitty.txt"})
doc2 = Document(page_content="doggy", metadata={"source": "doggy.txt"})

index(
    [doc1, doc1, doc2],
    record_manager,
    vectorstore,
    cleanup="incremental",  # None, "incremental", or "full"
    source_id_key="source",
)
```

# Fix issues

Fix https://github.com/milvus-io/milvus/issues/30112

### CODE REVIEW

**Comment by adhirpotdarbito** [comment]
## PR Analysis

- **Main theme:** Addition of document and deletion by ID functionality for Milvus in LangChain
- **PR summary:** This PR introduces new features to the Milvus vectorstore within the LangChain library, specifically enabling the addition of documents by ID and the deletion of documents by ID. It also includes updates to the documentation and integration tests to reflect these new capabilities.
- **Type of PR:** Enhancement
- **[Score ](https://docs.bito.ai)(0-100, higher is better):** 85
- **Relevant tests added:** Yes
- **[Estimated effort to review ](https://docs.bito.ai)(1-5, lower is better):** 3
The PR involves significant changes to data handling and requires thorough validation, especially concerning the new ID management and deletion features. The changes are well-scoped, but careful attention is needed to ensure data integrity and compatibility with existing systems.
## PR Feedback

- **General suggestions:** The PR effectively introduces the ability to add and delete documents by ID in the Milvus vectorstore, which is a significant enhancement for the LangChain library. However, there are several areas where the implementation can be improved to ensure robustness, maintainability, and adherence to best practices. Specifically, the changes related to handling IDs require careful consideration to prevent potential issues with data integrity and compatibility with other parts of the system. Additionally, the PR should be reviewed to ensure that it aligns with the overall design principles of the LangChain library and does not introduce any performance regressions.
## Code feedback

## file: libs/community/langchain_community/vectorstores/milvus.py

- **Suggestions:**



 1. Consider validating the format of the provided IDs to ensure they meet the expected criteria (e.g., length, characters) before insertion. This can prevent potential issues with ID handling down the line. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 465
 ```
+ ids: Optional[List[str]] = None,
 ```


 2. It's important to handle the case where both `ids` and `expr` are provided in the `delete` method more gracefully. Logging a warning is a good start, but the method should also clearly document the precedence of parameters and possibly raise an exception if conflicting parameters are passed to avoid silent unexpected behavior. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 864
 ```
+ expr: Optional[str] = None,
 ```


 3. The change from auto_id to manual ID management increases the risk of ID collisions. Implement a mechanism to check for existing IDs before insertion to avoid overwriting existing documents. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 329
 ```
+ self._primary_field, DataType.VARCHAR, is_primary=True, auto_id=False, max_length=65_535
 ```


 4. Ensure that the `max_length` for the `VARCHAR` primary field is consistent with the expected ID format and does not impose unnecessary limitations or allow excessively long IDs that could affect performance. [medium] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 329
 ```
+ self._primary_field, DataType.VARCHAR, is_primary=True, auto_id=False, max_length=65_535
 ```
## file: libs/community/tests/integration_tests/vectorstores/test_milvus.py

- **Suggestions:**



 1. Expand integration tests to cover edge cases, such as attempting to delete non-existent IDs or adding documents with duplicate IDs, to ensure the robustness of the new ID handling features. [important] **Relevant line**:In libs
 ```

 ```

**Comment by bitomukesh** [comment]
## PR Analysis

- **Main theme:** Enhancing Milvus vector store functionality
- **PR summary:** This PR introduces the ability to add and delete documents by ID in the Milvus vector store, aligning with user requests for more flexible data handling in langchain indexing.
- **Type of PR:** Enhancement
- **[Score ](https://docs.bito.ai)(0-100, higher is better):** 85
- **Relevant tests added:** Yes
- **[Estimated effort to review ](https://docs.bito.ai)(1-5, lower is better):** 2
The PR is well-scoped, focusing on a specific enhancement with clear use cases. The changes are significant but not overly complex, requiring a moderate level of effort to review thoroughly.
## PR Feedback

- **General suggestions:** The PR successfully implements the requested features for document addition and deletion by ID in the Milvus vector store. It's important to ensure that the new functionality doesn't introduce breaking changes to existing implementations and that the changes are well-documented for users to understand how to use the new features. Additionally, consider adding more comprehensive tests to cover edge cases, such as adding documents with duplicate IDs, or attempting to delete documents with IDs that do not exist.
## Code feedback

## file: libs/community/langchain_community/vectorstores/milvus.py

- **Suggestions:**



 1. Consider validating the `ids` list to ensure all IDs are unique before insertion to prevent potential conflicts or unexpected behavior in the database. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 465
 ```
+ ids: Optional[List[str]] = None,
 ```


 2. Implement error handling for the `delete` method to manage cases where the provided IDs do not exist in the database. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 864
 ```
+ def delete(self,
 ```


 3. Ensure thread safety when generating default IDs using `uuid4` in a multi-threaded environment to avoid potential race conditions. [medium] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 520
 ```
+ self._primary_field: ids or [str(uuid4()) for _ in texts],
 ```


 4. Add input validation for the `max_length` parameter of the `VARCHAR` data type to ensure it doesn't exceed the maximum allowed by Milvus. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 329
 ```
+ self._primary_field, DataType.VARCHAR, is_primary=True, auto_id=False, max_length=65_535
 ```


 5. Review the necessity of removing the primary field from the `fields` list after the schema change, as this might affect other parts of the code that rely on the `fields` attribute. [medium] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 369
 ```
- self.fields.remove(self._primary_field)
 ```
## file: libs/community/tests/integration_tests/vectorstores/test_milvus.py

- **Suggestions:**



 1. Expand the test cases to cover scenarios where the `delete` method is called with invalid or non-existent IDs to ensure the method behaves as expected. [important] **Relevant line**:In libs/community/tests/integration_tests/vectorstores/test_milvus.py at line 29
 ```
+def test_milvus_with_metadata() -> None:
 ```

**Comment by bitomukesh** [comment]
## PR Analysis

- **Main theme:** Integration of document addition and deletion by ID in Milvus vector store
- **PR summary:** This PR introduces the capability to add and delete documents by ID in the Milvus vector store, which is a part of the Langchain library. It modifies the existing code to support varchar primary keys and adds new methods to handle document operations with IDs.
- **Type of PR:** Enhancement
- **[Score ](https://docs.bito.ai)(0-100, higher is better):** 85
- **Relevant tests added:** Yes
- **[Estimated effort to review ](https://docs.bito.ai)(1-5, lower is better):** 3
The PR is well-structured with a clear description of the new features. However, it introduces significant changes to the data schema and functionality that require thorough review and testing.
## PR Feedback

- **General suggestions:** Overall, the PR successfully implements the requested features for document addition and deletion by ID in the Milvus vector store. However, there are a few areas where the implementation could be improved for better performance, maintainability, and error handling. It's important to ensure that the changes are backward compatible and do not introduce breaking changes to existing implementations. Additionally, providing more comprehensive tests to cover edge cases and failure scenarios would be beneficial.
## Code feedback

## file: libs/community/langchain_community/vectorstores/milvus.py

- **Suggestions:**



 1. Consider validating the `ids` parameter to ensure that it matches the length of `texts` and `metadatas` when provided. This will prevent potential data inconsistencies. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 465
 ```
+ ids: Optional[List[str]] = None,
 ```


 2. Implement error handling for potential exceptions that could be thrown during the `delete` operation, such as invalid `ids` or issues with the Milvus server. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 864
 ```
+ def delete(self,
 ```


 3. Ensure that the change from `DataType.INT64` to `DataType.VARCHAR` for the primary key does not adversely affect existing collections and indexes. This might require a migration strategy for current users. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 329
 ```
+ self._primary_field, DataType.VARCHAR, is_primary=True, auto_id=False, max_length=65_535
 ```


 4. Optimize the deletion by using batch operations if a large number of `ids` are provided, to improve performance and reduce the number of requests to the Milvus server. [medium] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 864
 ```
+ def delete(self,
 ```


 5. Review the consistency of the `ids` parameter across different methods and classes to ensure a uniform interface, which will make the API easier to use and maintain. [medium] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 864
 ```
+ def delete(self,
 ```
## file: libs/community/tests/integration_tests/vectorstores/test_milvus.py

- **Suggestions:**



 1. Expand the test cases to include scenarios where `ids` are not provided, as well as cases with invalid `ids`, to ensure robust error handling and validation. [important] **Relevant line**:In libs/community/tests/integration_tests/vectorstores/test_milvus.py at line 11
 ```
+ metadatas: Optional[List[dict]] = None, ids: Optional[List[str]] = None, drop: bool = True
 ```

**Comment by adhirpotdarbito** [comment]
## PR Analysis

- **Main theme:** Adding support for document addition and deletion by id in Milvus vectorstore
- **PR summary:** This PR introduces new functionality to the Milvus vectorstore to allow the addition and deletion of documents by id, which is necessary for integration with langchain indexing. The changes include modifications to method signatures, addition of new methods, and updates to the documentation to reflect the supported vectorstores.
- **Type of PR:** Enhancement
- **[Score ](https://docs.bito.ai)(0-100, higher is better):** 82
- **Relevant tests added:** Yes
- **[Estimated effort to review ](https://docs.bito.ai)(1-5, lower is better):** 3
The PR introduces several changes to the core functionality which require careful review to ensure proper integration with existing code and to avoid potential regressions.
## PR Feedback

- **General suggestions:** The PR successfully adds the required functionality for document manipulation by id in the Milvus vectorstore. However, there are some concerns regarding the use of VARCHAR as the primary key data type, the handling of ids in method signatures, and the potential side effects on existing data and indexes. It is crucial to ensure that the changes are backward compatible and that they do not negatively impact the performance of the system. Additionally, the PR should address the potential risks associated with the use of VARCHAR for primary keys, such as performance implications and limitations on the size of the primary key.
## Code feedback

## file: libs/community/langchain_community/vectorstores/milvus.py

- **Suggestions:**



 1. Consider using a more efficient data type for the primary key, such as INT64 with a unique constraint, to ensure better performance and scalability. VARCHAR may not be the optimal choice for large datasets. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 329
 ```
+ self._primary_field, DataType.VARCHAR, is_primary=True, auto_id=False, max_length=65_535
 ```


 2. Ensure that the change from auto_id=True to auto_id=False is backward compatible with existing collections that were using auto-generated ids. This may require additional migration steps or compatibility checks. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 329
 ```
+ self._primary_field, DataType.VARCHAR, is_primary=True, auto_id=False, max_length=65_535
 ```


 3. Implement error handling for cases where ids are not provided but are required due to the auto_id being set to False. This will prevent runtime errors and ensure data integrity. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 520
 ```
+ self._primary_field: ids or [str(uuid4()) for _ in texts],
 ```


 4. Add validation to ensure that the length of the provided ids list matches the number of texts being added. This can prevent mismatches and potential data loss. [medium] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 520
 ```
+ self._primary_field: ids or [str(uuid4()) for _ in texts],
 ```


 5. Review the necessity of removing the primary field from the list of fields in the _extract_fields method. This change may have unintended consequences on methods that rely on the complete list of fields. [medium] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 369
 ```
- self.fields.remove(self._primary_field)
 ```


 6. Add tests to cover scenarios where the delete method is called with both ids and expr parameters, to ensure that the logic behaves as expected and that the warning message is triggered appropriately. [medium] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 864
 ```
+ ids: Optional[List[str]] = None,
 ```

**Comment by adhirpotdarbito** [comment]
## PR Analysis

- **Main theme:** Addition of document handling by id and deletion by id in Milvus vectorstore
- **PR summary:** The PR introduces new functionality to the Milvus vectorstore to handle document addition and deletion by specific ids, which aligns with the requirements of langchain indexing. This includes changes to the Milvus schema and updated methods for adding and deleting documents.
- **Type of PR:** Enhancement
- **[Score ](https://docs.bito.ai)(0-100, higher is better):** 80
- **Relevant tests added:** Yes
- **[Estimated effort to review ](https://docs.bito.ai)(1-5, lower is better):** 3
The PR includes several enhancements that require careful review of the new logic, schema changes, and potential edge cases, especially concerning the new id handling and deletion logic.
## PR Feedback

- **General suggestions:** The PR successfully implements the requested features, but there are a few areas where improvements can be made to ensure robustness and maintainability. Specifically, consider adding more comprehensive tests to cover edge cases, such as the behavior when both 'ids' and 'expr' are provided in the delete method. Additionally, ensure that the changes made to the schema are thoroughly documented and communicated to users, as they may impact existing collections and data retrieval processes.
## Code feedback

## file: libs/community/langchain_community/vectorstores/milvus.py

- **Suggestions:**



 1. Consider adding a check to ensure 'ids' provided are unique to prevent potential primary key conflicts. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 465
 ```
+ ids: Optional[List[str]] = None,
 ```


 2. Implement input validation for 'ids' to ensure they comply with the maximum length defined for the VARCHAR DataType. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 329
 ```
+ self._primary_field, DataType.VARCHAR, is_primary=True, auto_id=False, max_length=65_535
 ```


 3. The deletion logic should handle the case where both 'ids' and 'expr' are provided more gracefully. Consider throwing an exception if both are provided to avoid unexpected behavior. [medium] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 864
 ```
+ expr: Optional[str] = None,
 ```


 4. Add logging or an exception for the case when 'ids' is provided but is empty, as this would result in an ineffective operation. [medium] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 864
 ```
+ ids: Optional[List[str]] = None,
 ```


 5. Update the method documentation to explain the behavior and requirements of the 'ids' parameter in more detail, including format and uniqueness constraints. [medium] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 465
 ```
+ ids: Optional[List[str]] = None,
 ```


 6. Ensure that the changes made to the schema are backward compatible or provide a migration path for existing data. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 329
 ```
+ self._primary_field, DataType.VARCHAR, is_primary=True, auto_id=False, max_length=65_535
 ```

**Review by baskaryan — COMMENTED** [review]
cc @zc277584121

**Comment by adhirpotdarbito** [comment]
## PR Analysis

- **Main theme:** Enhancing Milvus vector store compatibility and functionality
- **PR summary:** This PR introduces the ability to add and delete documents by ID in the Milvus vector store, improving its compatibility with the langchain indexing feature. It includes changes to the primary field data type and adds the necessary methods for document management by ID.
- **Type of PR:** Enhancement
- **[Score ](https://docs.bito.ai)(0-100, higher is better):** 85
- **Relevant tests added:** Yes
- **[Estimated effort to review ](https://docs.bito.ai)(1-5, lower is better):** 2
The PR is well scoped and the changes are clear, but careful attention is needed to ensure the new functionality integrates smoothly with the existing codebase.
## PR Feedback

- **General suggestions:** The PR effectively introduces new functionalities for adding and deleting documents by ID, which is a significant enhancement. However, there are some concerns regarding the data type changes and potential edge cases that might not be covered by the current implementation. It's also important to ensure that the new features are compatible with existing data and to consider the implications of changing the primary key data type on existing collections.
## Code feedback

## file: libs/community/langchain_community/vectorstores/milvus.py

- **Suggestions:**



 1. Consider validating the `ids` list to ensure all provided IDs are unique to prevent potential primary key conflicts. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 465
 ```
+ ids: Optional[List[str]] = None,
 ```


 2. Ensure that the `max_length` for the `DataType.VARCHAR` is consistent with the expected ID sizes to avoid truncation issues. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 329
 ```
+ self._primary_field, DataType.VARCHAR, is_primary=True, auto_id=False, max_length=65_535
 ```


 3. Add error handling for the `delete` method to manage cases where deletion fails due to missing or incorrect IDs. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 864
 ```
+ def delete(self,
 ```


 4. Review the necessity of removing the primary field from the output fields in the `similarity_search_with_score_by_vector` method, as this might be useful information for the user. [medium] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 700
 ```
+ output_fields = [x for x in self.fields if x != self._primary_field]
 ```


 5. Consider implementing a migration strategy for collections that were created with the previous `INT64` primary key type to the new `VARCHAR` type. [important] **Relevant line**:In libs/community/langchain_community/vectorstores/milvus.py at line 329
 ```
+ self._primary_field, DataType.VARCHAR, is_primary=True, auto_id=False, max_length=65_535
 ```
## file: libs/community/tests/integration_tests/vectorstores/test_milvus.py

- **Suggestions:**



 1. Expand the test coverage to include scenarios where documents are added with duplicate IDs and ensure the system behaves as expected. [important] **Relevant line**:In libs/community/tests/integration_tests/vectorstores/test_milvus.py at line 11
 ```
+def _milvus_from_texts(
 ```

**Review by baskaryan — APPROVED** [review]
updated to avoid any breaking changes (changing order of positional vars is breaking), lgtm now!

**Comment by jaelgu** [comment]
@baskaryan updated to resolve conflicts due to recent commits in master

**Comment by jaelgu** [comment]
@baskaryan updated to resolve conflicts with master again

**Comment by axiangcoding** [comment]
@jaelgu @baskaryan hi all, this PR is incompatible with old version, and aslo not working even set `auto_id=False`. 

Please take a look.

**Pull request merged**
