### PR TITLE
Add `openaichat` to llms class mapping

### PR DESCRIPTION
**Pull request by bowenliang123**
- **Description:**
The `get_type_to_cls_dict` method provides type to class mapping. This PR fixes the missing `openaichat` type for importer for `OpenAIChat`.

### CODE REVIEW

**Comment by bowenliang123** [comment]
cc @hwchase17

**Comment by baskaryan** [comment]
OpenAIChat is deprecated (in favor of ChatOpenAI) so we probably don't want to add it here

**Comment by bowenliang123** [comment]
Hi, thanks for the reply.
For llm level, as the `llms.OpenAIChat` uses `openai.chatCompletions` while `llms.OpenAI` uses `openai.chat`, the latter one should be deprecated which is requesting `/completions` (the former one requests latest `/chat/completions`).
That's the main reason I raised this PR.

As for `ChatOpenAI`, that's the chat model level API, not on llm level. In some popular LLM applications , the are still rely on llm level but not the chat model level API

**Comment by hwchase17** [comment]
agree with @baskaryan original comment, should not be added here

**Comment by bowenliang123** [comment]
OK, thanks for the review.

**Pull request closed without merging**
