### PR TITLE
community: add support for Mistral on Bedrock

### PR DESCRIPTION
**Pull request by n1lanjan**
- **Description:** Bedrock has added Mistral models but Langchain module does not support it yet. This PR adds support for Mistral through Bedrock.
- **Issue:**  #18461 #18451

### CODE REVIEW

**Comment by miroslavtushev** [comment]
Can we have this merged asap, please?

**Comment by 3coins** [comment]
@n1lanjan 
Does this cover the changes needed for the BedrockChat class as well?

**Comment by 3coins** [comment]
@n1lanjan 
Follow updates on PR [#18756](https://github.com/langchain-ai/langchain/pull/18756), it's easier to provide feedback in one place. You might have some useful code for the async streaming support that I have asked the author to include.

**Comment by n1lanjan** [comment]
@3coins Thanks for checking, by the way, I'm using this code on my production, so I've tested this to be working.

**Comment by efriis** [comment]
Going with #18756

**Pull request closed without merging**
