### PR TITLE
langchain-robocorp: remove toolkit return content max length

### PR DESCRIPTION
**Pull request by tonnitommi**
Robocorp (action server) toolkit had a limitation that the content length returned by the tool was always cut to max 5000 chars. This was from the time when context windows were much more limited.

This PR removes the limitation. Whatever the underlying tool provides gets sent back to the agent.

As the robocorp toolkit no longer restricts the content, the implication is that either the Action (tool) developer or the agent developer needs to be aware of potentially oversized tool responses. Our point of view is this should be the agent developer's responsibility, them being in control of the use case and aware of the context window the LLM has.

### CODE REVIEW

**Review by ccurme — APPROVED** [review]

**Comment by ccurme** [comment]
Thanks @tonnitommi. It looks like we haven't released `langchain-robocorp` in about [a month](https://pypi.org/project/langchain-robocorp/#history). I'll plan to release in an hour to pick up this change, but let me know if you have additional changes you want to get in ahead of that (can also cut additional releases).

**Comment by tonnitommi** [comment]
Thanks @ccurme, we are happy with this change for now. :)

Swift turnaround is very much appreciated here in our camp! 🙇

**Comment by ccurme** [comment]
Hi @tonnitommi, this is now released in `langchain-robocorp==0.0.6`. Would you mind testing to confirm the issue is resolved? Thanks.

**Comment by tonnitommi** [comment]
@ccurme sorry took a while, but the PR indeed fixed what it was supposed to do. :)

**Pull request merged**
