### PR TITLE
Lint Python notebooks with ruff.

### PR DESCRIPTION
**Pull request by obi1kenobi**
The new ruff version fixed the blocking bugs, and I was able to fairly easily us to a passing state: ruff fixed some issues on its own, I fixed a handful by hand, and I added a list of narrowly-targeted exclusions for files that are currently failing ruff rules that we probably should look into eventually.

I went pretty lenient on the docs / cookbooks rules, allowing dead code and such things. Perhaps in the future we may want to tighten the rules further, but this is already a good set of checks that found real issues and will prevent them going forward.

### CODE REVIEW

**Comment by obi1kenobi** [comment]
Somehow, linting with `black`'s jupyter integration doesn't run into all these errors. It only finds one formatting issue, which it's able to resolve.

**Comment by efriis** [comment]
I think @rlancemartin is going to try to merge some last notebooks that should be reformatted as part of this too, so the formatting doesn't introduce annoying merge conflicts in the other direction :)

**Comment by obi1kenobi** [comment]
Not a problem. I see at least one such got merged and I'll fix the conflict. Are there more @rlancemartin ? No worries if so, just give me a ping when you're all set.

**Comment by efriis** [comment]
Merge it! Can sort out merge conflicts for the remaining ones (there's quite a few) by just formatting the changed versions for now.

**Comment by obi1kenobi** [comment]
> Merge it! Can sort out merge conflicts for the remaining ones (there's quite a few) by just formatting the changed versions for now.

Happy to help with that if you'd like a hand, I've got the process down from practicing it over the last few days :)

**Pull request merged**
