### PR TITLE
bug fix for sagemakerendpoint streaming

### PR DESCRIPTION
**Pull request by lyoh001**

### CODE REVIEW

**Comment by lyoh001** [comment]
I've discovered a bug in the code for the recent sagemaker endpoint streaming.
Fixed it based on AWS code found here (https://aws.amazon.com/blogs/machine-learning/elevating-the-generative-ai-experience-introducing-streaming-support-in-amazon-sagemaker-hosting/)
Thank you

**Comment by lyoh001** [comment]
Here is a demo video of running the new code, streaming from AWS Sagemaker Endpoint.
[https://www.youtube.com/watch?v=bD2Rrbw0fF0]

**Comment by baskaryan** [comment]
cc @3coins

**Comment by lyoh001** [comment]
modified lines 52, & 55 for return type annotations. opened up #11999 (https://github.com/langchain-ai/langchain/pull/11999)

**Pull request closed without merging**
