### PR TITLE
community: better support of pathlib paths in document loaders

### PR DESCRIPTION
**Pull request by mmajewsk**
So this arose from the https://github.com/langchain-ai/langchain/pull/18397 problem of document loaders not supporting `pathlib.Path`.

This pull request provides more uniform support for Path as an argument.
The core ideas for this upgrade: 
- if there is a local file path used as an argument, it should be supported as `pathlib.Path`
- if there are some external calls that may or may not support Pathlib, the argument is immidiately converted to `str`
- if there `self.file_path`  is used in a way that it allows for it to stay pathlib without conversion, is is only converted for the metadata.

Twitter handle: https://twitter.com/mwmajewsk

### CODE REVIEW

**Comment by eyurtsev** [comment]
Looks good for scanning quickl

**Comment by mmajewsk** [comment]
@eyurtsev i think this may be ready to merge now

**Comment by mmajewsk** [comment]
@efriis I think this is ready to merge

**Comment by mmajewsk** [comment]
I'm trying to mention someone else: @baskaryan can you merge this?

**Comment by eyurtsev** [comment]
I'll try to merge tomorrow added myself as reviewer

**Comment by eyurtsev** [comment]
tomorrow is relative i guess

**Comment by eyurtsev** [comment]
sorry for the delay @mmajewsk and thanks for the contribution!

**Pull request merged**
