### PR TITLE
chore(openllm): make sure to download the model if not exists

### PR DESCRIPTION
**Pull request by aarnphm**
OpenLLM Runner now include a ensure_available argument to separate the process
of automatic setup of the given model. This was introduced to allow better UX
with openllm.

I updated the OpenLLM accordingly, since we are just loading the model into
memory in "local" mode, `ensure_available` should set to `True`

cc @dev2049

Signed-off-by: Aaron <29749331+aarnphm@users.noreply.github.com>

### CODE REVIEW

**Comment by dev2049** [comment]
do we need to update openllm package version in pyproject.toml?

**Comment by aarnphm** [comment]
oh right let me do that as well

**Comment by aarnphm** [comment]
cc @dev2049 ready for merge

**Comment by dev2049** [comment]
> cc @dev2049 ready for merge

you'll want to run `poetry lock --no-update` to update poetry.lock

**Comment by baskaryan** [comment]
resolved merge conflict and landed in #6960

**Comment by aarnphm** [comment]
Thanks for helping

**Pull request closed without merging**
