### PR TITLE
community: adding Unify AI Support

### PR DESCRIPTION
**Pull request by paras55**
**Description:** Added support for Unify, an LLM dynamic router with single-sign-on for all providers + models
**Dependencies:** unifyai
**Twitter handle:** @parasmadan9 / @letsunifyai

### CODE REVIEW

**Comment by vedpatwardhan** [comment]
Hey @efriis, we have added unify as a community integration as you had suggested [here](https://github.com/langchain-ai/langchain/pull/19953). Let us know if any changes are required. Thanks 😄

**Comment by efriis** [comment]
Marking as stale and still in need of support, per the [review process](https://python.langchain.com/docs/contributing/reference/review_process/)

**Comment by efriis** [comment]
howdy! happy to take this across the finish line for you because of the back and forth (apologies for the delay the last few months). However, if you're interested in maintaining this integration without us in the loop, we'd love to get an integration package out! Future PRs against langchain would just be {docs updates, as well as registering your package in `libs/packages.yml`}

Here's the guide, and if you have questions, feel free to leave them in the comments on those pages so others can see them! https://python.langchain.com/docs/contributing/how_to/integrations/

Let me know!

**Comment by efriis** [comment]
will close for now - let me know what you'd like to do, and maintenance-wise best path forward is doing the integration package!

**Pull request closed without merging**
