### PR TITLE
Initial commit for comprehend moderator

### PR DESCRIPTION
**Pull request by nikhilkjha**
This PR implements a custom chain that wraps Amazon Comprehend API calls. The custom chain is aimed to be used with LLM chains to provide moderation capability that let’s you detect and redact PII, Toxic and Intent content in the LLM prompt, or the LLM response. The implementation accepts a configuration object to control what checks will be performed on a LLM prompt and can be used in a variety of setups using the LangChain expression language to not only detect the configured info in chains, but also other constructs such as a retriever. 
The included sample notebook goes over the different configuration options and how to use it with other chains.

###  Usage sample
```python
from langchain_experimental.comprehend_moderation import BaseModerationActions, BaseModerationFilters

moderation_config = { 
        "filters":[ 
                BaseModerationFilters.PII, 
                BaseModerationFilters.TOXICITY,
                BaseModerationFilters.INTENT
        ],
        "pii":{ 
                "action": BaseModerationActions.ALLOW, 
                "threshold":0.5, 
                "labels":["SSN"],
                "mask_character": "X"
        },
        "toxicity":{ 
                "action": BaseModerationActions.STOP, 
                "threshold":0.5
        },
        "intent":{ 
                "action": BaseModerationActions.STOP, 
                "threshold":0.5
        }
}

comp_moderation_with_config = AmazonComprehendModerationChain(
    moderation_config=moderation_config, #specify the configuration
    client=comprehend_client,            #optionally pass the Boto3 Client
    verbose=True
)

template = """Question: {question}

Answer:"""

prompt = PromptTemplate(template=template, input_variables=["question"])

responses = [
    "Final Answer: A credit card number looks like 1289-2321-1123-2387. A fake SSN number looks like 323-22-9980. John Doe's phone number is (999)253-9876.", 
    "Final Answer: This is a really shitty way of constructing a birdhouse. This is fucking insane to think that any birds would actually create their motherfucking nests here."
]
llm = FakeListLLM(responses=responses)

llm_chain = LLMChain(prompt=prompt, llm=llm)

chain = ( 
    prompt 
    | comp_moderation_with_config 
    | {llm_chain.input_keys[0]: lambda x: x['output'] }  
    | llm_chain 
    | { "input": lambda x: x['text'] } 
    | comp_moderation_with_config 
)

response = chain.invoke({"question": "A sample SSN number looks like this 123-456-7890. Can you give me some more samples?"})

print(response['output'])


```
### Output
```
> Entering new AmazonComprehendModerationChain chain...
Running AmazonComprehendModerationChain...
Running pii validation...
Found PII content..stopping..
The prompt contains PII entities and cannot be processed
```

### CODE REVIEW

**Comment by baskaryan** [comment]
looking very cool! think we'll probably want to put this in `libs/experimental` not `libs/langchain`

**Comment by 3coins** [comment]
@baskaryan 
Thanks for that info, I am inclined to that. How does that affect user experience? 
Does experimental have any code that breaks regular langchain APIs, for example if I want to use a specific chain with the code in this PR, that would not work because experimental has a different interface?

**Comment by baskaryan** [comment]
> @baskaryan
> Thanks for that info, I am inclined to that. How does that affect user experience?
> Does experimental have any code that breaks regular langchain APIs, for example if I want to use a specific chain with the code in this PR, that would not work because experimental has a different interface?

everything in `experimental` should work with what's in `langchain`. experimental is meant to house more novel and use case-specific code that may not be as well maintained as more low-level, core components. experimental shouldn't be changing any existing interfaces

**Comment by 3coins** [comment]
@baskaryan 
A few questions came up while discussing with the team:
1. What is the frequency of release for the experimental package?
2. What is the primary reason for moving to experimental? Is LangChain team planning to build a better interface for handling moderation, and having this change in experimental for now will help users have a placeholder while they migrate to the new interface?
3. Is there any timeline for building such an interface?

I don't see any user impact with moving to experimental, but do want to make sure we communicate this clearly to the team internally.

**Comment by baskaryan** [comment]
> @baskaryan A few questions came up while discussing with the team:
> 
> 1. What is the frequency of release for the experimental package?
> 2. What is the primary reason for moving to experimental? Is LangChain team planning to build a better interface for handling moderation, and having this change in experimental for now will help users have a placeholder while they migrate to the new interface?
> 3. Is there any timeline for building such an interface?
> 
> I don't see any user impact with moving to experimental, but do want to make sure we communicate this clearly to the team internally.

1. We release experimental on same schedule as langchain (assuming something has been added to experimental)

2 + 3. Truthfully we haven't given a moderation interface too much thought yet, and we want to make sure that anything that goes into langchain is fairly stable. So main motivation for putting in experimental for now is to indicate that this is an interface that's liable to change. But like you said, the fact that the AmazonComprehendModerationChain is in experimental shouldn't really affect the user experience

**Comment by 3coins** [comment]
@baskaryan 
I have moved the code to experimental. I am getting a weird error that we did not see before, none of the code has changed, so not sure if this is related to any recent release in LangChain. The notebook is attached, I am getting this error on running cell 5. Can you help us narrow down the issue?

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 20
     15 llm = FakeListLLM(responses=responses)
     17 llm_chain = LLMChain(prompt=prompt, llm=llm)
     19 chain = (
---> 20     prompt 
     21     | comprehend_moderation 
     22     | {llm_chain.input_keys[0]: lambda x: x['output'] }  
     23     | llm_chain 
     24     | { "input": lambda x: x['text'] } 
     25     | comprehend_moderation 
     26 )
     27 try:
     28     response = chain.invoke({"question": "A sample SSN number looks like this 123-456-7890. Can you give me some more samples?"})

TypeError: unsupported operand type(s) for |: 'PromptTemplate' and 'AmazonComprehendModerationChain'
```

**Comment by baskaryan** [comment]
> @baskaryan We have moved the code to experimental but getting a weird error that we did not see before, none of the code has changed, so not sure if this is related to any recent release in LangChain. The notebook is attached, I am getting this error on running cell 5. Can you help us narrow down the issue?
> 
> ```python
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> Cell In[5], line 20
>      15 llm = FakeListLLM(responses=responses)
>      17 llm_chain = LLMChain(prompt=prompt, llm=llm)
>      19 chain = (
> ---> 20     prompt 
>      21     | comprehend_moderation 
>      22     | {llm_chain.input_keys[0]: lambda x: x['output'] }  
>      23     | llm_chain 
>      24     | { "input": lambda x: x['text'] } 
>      25     | comprehend_moderation 
>      26 )
>      27 try:
>      28     response = chain.invoke({"question": "A sample SSN number looks like this 123-456-7890. Can you give me some more samples?"})
> 
> TypeError: unsupported operand type(s) for |: 'PromptTemplate' and 'AmazonComprehendModerationChain'
> ```

wasn't able to reproduce TypeError. was getting a circular import that i think i fixed, after that things worked. are you still seeing it?

**Comment by 3coins** [comment]
@baskaryan 
Still getting that error. I have tried this in a fresh codespaces env, so pretty sure this is not related to any local env issues.
```python
Python 3.11.4 (main, Jun  7 2023, 18:32:58) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> comprehend_client = boto3.client('comprehend', region_name='us-east-1')
>>> from langchain_experimental.comprehend_moderation import AmazonComprehendModerationChain
>>> comprehend_moderation = AmazonComprehendModerationChain(
...     client=comprehend_client, #optional
...     verbose=True
... )
>>> from langchain import PromptTemplate, LLMChain
>>> from langchain.llms.fake import FakeListLLM
>>> from langchain_experimental.comprehend_moderation.base_moderation_exceptions import ModerationPiiError
>>> 
>>> template = """Question: {question}
... 
... Answer:"""
>>> 
>>> prompt = PromptTemplate(template=template, input_variables=["question"])
>>> 
>>> responses = [
...     "Final Answer: A credit card number looks like 1289-2321-1123-2387. A fake SSN number looks like 323-22-9980. John Doe's phone number is (999)253-9876.", 
...     "Final Answer: This is a really shitty way of constructing a birdhouse. This is fucking insane to think that any birds would actually create their motherfucking nests here."
... ]
>>> llm = FakeListLLM(responses=responses)
>>> 
>>> llm_chain = LLMChain(prompt=prompt, llm=llm)
>>> 
>>> chain = (
...     prompt 
...     | comprehend_moderation 
...     | {llm_chain.input_keys[0]: lambda x: x['output'] }  
...     | llm_chain 
...     | { "input": lambda x: x['text'] } 
...     | comprehend_moderation 
... )
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: unsupported operand type(s) for |: 'PromptTemplate' and 'AmazonComprehendModerationChain'
>>> try:
...     response = chain.invoke({"question": "A sample SSN number looks like this 123-456-7890. Can you give me some more samples?"})
... except ModerationPiiError as e:
...     print(e.message)
... else:
...     print(response['output'])
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: name 'chain' is not defined
>>> chain = prompt | comprehend_moderation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'PromptTemplate' and 'AmazonComprehendModerationChain'
>>> 
```

**Comment by 3coins** [comment]
@baskaryan 
I think I found the root cause of my error. The default version for `langchain` dependency seems to be 0.0.239, which is a much older version.

```
[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.239"
```

Should this always track the latest LangChain version, somehow this always installs the lowest compatible version `0.0.239`. Upgrading the LangChain version `pip install -U langchain` fixes the errors.

**Comment by 3coins** [comment]
@baskaryan 
We are done with our updates, and checked on my machine that there are no lint errors. The lint errors here seems to be related to `cpal`. Let us know if there is anything we can do to move this PR forward.
```
langchain_experimental/cpal/models.py:142: error: No overload variant of "root_validator" matches argument type "Callable[[StoryModel, Dict[Any, Any]], Dict[Any, Any]]"  [call-overload]
langchain_experimental/cpal/models.py:142: note: Possible overload variants:
langchain_experimental/cpal/models.py:142: note:     def root_validator(*, skip_on_failure: Literal[True], allow_reuse: bool = ...) -> 
```

**Comment by baskaryan** [comment]
looks awesome, thanks @nikhilkjha and @3coins!!

**Comment by 3coins** [comment]
@baskaryan 
Thanks for merging the change. Noticed that there was a release for langchain earlier today, but did not see one for experimental. Is there a release for experimental scheduled for today?

**Comment by wricktalukdar** [comment]
We have a dependency on a post which is planned to be launched 08/30. Can you confirm if the change is scheduled, and if so when?

**Pull request merged**
