### PR TITLE
core: Move document loader interfaces to core

### PR DESCRIPTION
**Pull request by cbornet**
This is needed to be able to move document loaders to partner packages.

### CODE REVIEW

**Comment by cbornet** [comment]
There's a circular dependency since  BaseLoader uses TextSplitter which is in the langchain package. How should it be handled ?

**Comment by cbornet** [comment]
I opted for moving  TextSplitter and RecursiveCharacterTextSplitter to core.
Is that OK ?

**Comment by cbornet** [comment]
[The text splitters ](https://github.com/langchain-ai/langchain/pull/18346) moved the text splitters to their own package.
I'll update the PR accordingly.

**Comment by cbornet** [comment]
Rebased to use langchain-text-splitters

**Comment by hemidactylus** [comment]
LGTM, thank you for identifying the problem and coming up with an elegant solution!

**Comment by eyurtsev** [comment]
Fantastic I've been wanting to do this for a while!

**Comment by eyurtsev** [comment]
OK document loaders is good according to @baskaryan

**Review by eyurtsev — APPROVED** [review]

**Pull request merged**
