### PR TITLE
templates: optimize RAG Performance using Intel Gaudi Accelerator

### PR DESCRIPTION
**Pull request by lvliang-intel**
Description:
This template utilizes Chroma and TGI (Text Generation Inference) to execute RAG on the Intel Gaudi Accelerator. It serves as a demonstration for users, illustrating the deployment of the RAG service on the Intel Gaudi Accelerator and showcasing the resulting performance enhancements.

Issue:
None

Dependencies:
The template contains the poetry project requirements to run this template.

image

### CODE REVIEW

**Comment by hshen14** [comment]
@efriis Please help review and let us know your comments. Thanks.

**Comment by hshen14** [comment]
Hi @efriis, we wanted to check the issues reported by Vercel. Unfortunately, it seems the log is not available even we registered the account. Could you please share some notes on how to get the Vercel logs?

**Comment by efriis** [comment]
Here's the broken link error!

Screenshot 2024-03-27 at 12 20 03 PM

**Comment by efriis** [comment]
Hey team - I don't think this makes sense as an official LangChain Template because it needs to run on specific hardware that most people will not be using to get started with LangChain. If you want to host it in a separate repo, you can recommend people install it with the CLI using the following command

```
langchain app new my-app
cd my-app
langchain app add --repo=githubhandle/githubrepo 
```

**Pull request closed without merging**
