### PR TITLE
Added Streaming Capability to SageMaker LLMs

### PR DESCRIPTION
**Pull request by dazajuandaniel**
This PR adds the ability to declare a Streaming response in the SageMaker LLM by leveraging the `invoke_endpoint_with_response_stream` capability in `boto3`. It is heavily based on the AWS Blog Post announcement linked [here](https://aws.amazon.com/blogs/machine-learning/elevating-the-generative-ai-experience-introducing-streaming-support-in-amazon-sagemaker-hosting/).

It does not add any additional dependencies since it uses the existing `boto3` version.

### CODE REVIEW

**Comment by baskaryan** [comment]
cc @3coins

**Review by 3coins — APPROVED** [review]
@dazajuandaniel 
This is awesome! Thanks for adding this. I don't have a model setup to test, but code looks good. 🚀 

One minor suggestion for a follow up PR, would be nice to move the streaming/non-streaming  parts to separate private functions for better readability.

**Comment by dazajuandaniel** [comment]
> @dazajuandaniel This is awesome! Thanks for adding this. I don't have a model setup to test, but code looks good. 🚀
> 
> One minor suggestion for a follow up PR, would be nice to move the streaming/non-streaming parts to separate private functions for better readability.

Hey @3coins,
Thanks for approving this PR!

Yes, I agree. I am happy to work on the follow up PR, no issues. I tried to follow the pattern that [`replicate`](https://github.com/langchain-ai/langchain/blob/f9f13402083ac537cd85b8098ffbe2e9c6317fee/libs/langchain/langchain/llms/replicate.py#L125C5-L125C5) has.

**Comment by dazajuandaniel** [comment]
@baskaryan - please let me know if anything is missing :)

**Comment by baskaryan** [comment]
lgtm aside from linting issues. would also be nice to factor out stream implementation into the `_stream` method defined on parent class, but can also do that in follow up pr

**Comment by pinak-p** [comment]
@dazajuandaniel, @3coins - Is this good to be merged ?

**Comment by 3coins** [comment]
@baskaryan 
This has been open for a while, is there anything needed to merge this?

**Comment by dazajuandaniel** [comment]
@pinak-p I was missing a mypy fix, I've done it now

**Comment by baskaryan** [comment]
sorry for the delay, thank you @dazajuandaniel!

**Comment by jay2jp** [comment]
Is there any documentation on this? I cant seem to find any.

**Pull request merged**
