### PR TITLE
refactor `langchain.prompts.example_selector`

### PR DESCRIPTION
**Pull request by leo-gan**
The `langchain.prompts.example_selector` [still holds several artifacts](https://api.python.langchain.com/en/latest/langchain_api_reference.html#module-langchain.prompts) that belongs to `community`. If they moved to `langchain_community.example_selectors`, the `langchain.prompts` namespace would be effectively removed which is great.
- moved a class and afunction to `langchain_community`

Note:
- Previously, the `langchain.prompts.example_selector` artifacts were moved into the `langchain_core.exampe_selectors`. See the flattened namespace (`.prompts` was removed)!
Similar flattening was implemented for the `langchain_core` as the `langchain_core.exampe_selectors`.

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
i think this make sense to me... thoughts @baskaryan ?

**Comment by leo-gan** [comment]
@hwchase17 Any new comments?

**Comment by leo-gan** [comment]
@baskaryan Any new comments?

**Review by efriis — APPROVED** [review]
1 nit

**Comment by leo-gan** [comment]
@efriis Thanks!!!!

**Pull request merged**
