### PR TITLE
core[patch]: preserve inspect.iscoroutinefunction with @beta decorator

### LINKED ISSUE #16402: preserve inspect.iscoroutinefunction with @beta decorator
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Same as #16295 for `@beta` decorator

### PR DESCRIPTION
**Pull request by Lord-Haji**
Adjusted deprecate decorator to make sure decorated async functions are still recognized as "coroutinefunction" by inspect

Addresses #16402

### CODE REVIEW

**Comment by baskaryan** [comment]
thanks @Lord-Haji! could we add some simple unit tests?

**Comment by Lord-Haji** [comment]
Probably done here I think @baskaryan . Weird thing from the first commit was. ruff didnt throw any sort of error locally but somehow ruff seemed to fail on the GitHub Actions Workflow

**Comment by Lord-Haji** [comment]
Idk why I did that. Should be all good now

**Comment by Lord-Haji** [comment]
I'm not sure how ruff didn't throw me the error when I ran it locally.

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
