### PR TITLE
Add async support to SelfQueryRetriever

### PR DESCRIPTION
**Pull request by asai95**
### Description

SelfQueryRetriever is missing async support, so I am adding it.
I also removed deprecated predict_and_parse method usage here, and added some tests.

### Issue
N/A

### Tag maintainer
Not yet

### Twitter handle
N/A

### CODE REVIEW

**Review by nfcampos — APPROVED** [review]
Thanks!

**Comment by asai95** [comment]
Hey @nfcampos!
Apologies for the ping, just wonder if there is anything else I need to do with the PR?

**Comment by asai95** [comment]
Hey @nfcampos !
I resolved the conflict, could you please merge if everything is ok?

**Comment by baskaryan** [comment]
this is awesome, thank you @asai95 and apologies for the delay!

**Pull request merged**
