### PR TITLE
Fix import in Doc Notebook for textgen webui integration

### PR DESCRIPTION
**Pull request by sumukshashidhar**
- **Description:** Fix the integration library import for the Oobagooba Textgeneration webui

Self explanatory fix - it seems like the paths were changed.

### CODE REVIEW

**Review by baskaryan — COMMENTED** [review]
thanks for contribution @sumukshashidhar! what error were you seeing? you should be able to import from `langchain.llms`

**Comment by sumukshashidhar** [comment]
Hey @baskaryan. Have you verified that the import from `langchain.llms` works as you expect it to? When I was working with langchain a few days ago, I was not able to import due to an `import error`. I was on the latest branch of langchain as well. 

Doing the above seemed to fix the issue.

If you're unable to replicate, I can perhaps try this again and paste the error stack

**Comment by baskaryan** [comment]
> If you're unable to replicate, I can perhaps try this again and paste the error stack

Unfortunately can't repro, trace and env info would be great if you're still seeing this 🙏 
Screenshot 2023-10-16 at 8 14 01 PM

**Comment by efriis** [comment]
Hey @sumukshashidhar ! Closing this for now. If you're still seeing this issue, we'll try to fix this in the `langchain.llms` model!

**Pull request closed without merging**
