### PR TITLE
Buckler/dynamic retriever parameters

### PR DESCRIPTION
**Pull request by Buckler89**
Description: Enhance kwargs Support in Internal Retriever Method for EnsembleRetriever and MergerRetriever Classes

This pull request introduces a valuable enhancement to the EnsembleRetriever and MergerRetriever classes by allowing the seamless flow of keyword arguments (**kwargs) to the internal _get_relevant_document method. This improvement empowers these classes with greater flexibility and customization when invoking the _get_relevant_document method.

Changes Made:

Previously, the internal _get_relevant_document method within the EnsembleRetriever and MergerRetriever classes did not directly receive keyword arguments. This enhancement addresses this limitation by enabling the propagation of **kwargs directly to the said method. This enables developers to conveniently pass additional arguments and options, extending the capabilities of these retriever classes.

Benefits:

Enhanced Flexibility: With this enhancement, users can now pass arbitrary keyword arguments when calling the _get_relevant_document method within the EnsembleRetriever and MergerRetriever classes. This facilitates customizations, configuration adjustments, and integration with other components in a more seamless manner.

  - Tag maintainer:  @baskaryan 
  - Twitter handle: Buckler89

### CODE REVIEW

**Comment by Buckler89** [comment]
Hi @baskaryan I have run the tests in my local environment (make format, make lint, and make test). All of them have passed. How do I check for the tests that did not pass on GitHub?

**Comment by Buckler89** [comment]
Hi @baskaryan I fixed all the failed test. Let me know if you thinks it is mergable.
Thanks

**Review by hwchase17 — COMMENTED** [review]
we want to keep the high level interface of `get_relevant_documents` not accepting kwargs. this is because oftentimes this interface is nested within many layers of a chain, and so we want kwargs to be attached to the class.

for example, in this pr we'd prefer that `retrievers_kwargs` be a property on these classes

**Comment by Buckler89** [comment]
@hwchase17  Thank you for your response. I understand your rationale for keeping the high-level interface of `get_relevant_documents` free from accepting kwargs, considering its nested nature within multiple layers of a chain.

However, I would like to discuss a use case I am working on, where dynamic changes in metadata filters are required. In this scenario, users can select various tags, and only files with the selected tags are used by the retrieval system to generate responses. The tag selection can vary with each interaction, depending on the user's needs.

With the current setup, I am able to achieve this requirement by calling the `get_relevant_documents` method of my retriever (for instance, `VectorStoreRetriever`) which in turn calls `_get_relevant_documents`, passing it kwargs. This flow allows for dynamic parameterization which I find crucial for my use case.

However, without the proposed changes (or an alternative), this dynamic parameterization becomes unachievable when `MergerRetriever` or `EnsembleRetriever` are used. It seems limiting for these types of retrievers to not have the capability to dynamically parameterize the `_get_relevant_documents` call, particularly when `BaseRetriever` allows it.

Could you possibly suggest an alternative solution that would still allow for such dynamic behavior? I am open to any suggestions and eager to collaborate on a solution that would work best in this context.

**Pull request closed without merging**
