### PR TITLE
community: add Intel GPU support to `ipex-llm` llm integration

### PR DESCRIPTION
**Pull request by Oscilloscope98**
**Description:** [IPEX-LLM](https://github.com/intel-analytics/ipex-llm) is a PyTorch library for running LLM on Intel CPU and GPU (e.g., local PC with iGPU, discrete GPU such as Arc, Flex and Max) with very low latency. This PR adds Intel GPU support to `ipex-llm` llm integration.
**Dependencies:** `ipex-llm`
**Contribution maintainer**: @ivy-lv11 @Oscilloscope98
**tests and docs**: 
- Add: langchain/docs/docs/integrations/llms/ipex_llm_gpu.ipynb
- Update: langchain/docs/docs/integrations/llms/ipex_llm_gpu.ipynb
- Update: langchain/libs/community/tests/llms/test_ipex_llm.py

### CODE REVIEW

**Comment by Oscilloscope98** [comment]
Hi @baskaryan!

Would you kindly let us know if there are any further actions needed on my part to finalize this PR? Thank you again :)

**Review by ccurme — COMMENTED** [review]
Sorry for the delay @Oscilloscope98. LGTM if you add the GPU doc as a sub-section of the existing `ipex_llm` doc.

**Comment by Oscilloscope98** [comment]
> Sorry for the delay @Oscilloscope98. LGTM if you add the GPU doc as a sub-section of the existing `ipex_llm` doc.

Thank you for the comment! Will update the doc soon :)

**Comment by Oscilloscope98** [comment]
Hi @ccurme, I have updated the document based on comments :) Please let me know for any further things needed to be updated. Thank you.

**Review by ccurme — APPROVED** [review]

**Pull request merged**
