### PR TITLE
community: `NeptuneGraph` fix

### PR DESCRIPTION
**Pull request by leo-gan**
Issue: the `service` optional parameter was mentioned but not used.
Fix: added this parameter.

### CODE REVIEW

**Comment by leo-gan** [comment]
@baskaryan Any comments? Thanks! :smile:

**Comment by leo-gan** [comment]
@ccurme Can you review, please?

**Review by ccurme — APPROVED** [review]
`service` appears to have been removed by a contributor from AWS in [this PR](https://github.com/langchain-ai/langchain/pull/20047), I don't feel we have context to override that.

**Comment by leo-gan** [comment]
@ccurme Thanks!

**Pull request merged**
