### PR TITLE
Add SQLiteChatMessageHistory

### PR DESCRIPTION
**Pull request by scientist1642**
It's based on already existing `PostgresChatMessageHistory`

Use case somewhere in between multiple files and Postgres storage.

### CODE REVIEW

**Review by agola11 — COMMENTED** [review]
Thanks for this. I think what might be best if we just use SqlAlchemy, then we could basically use the same class to persist chat history in a variety of sql dbs like postgres, sqlite, mysql etc.

**Comment by francisjervis** [comment]
I just came across this looking for a solution to store users' chat histories - in order to replicate eg the ChatGPT history feature, you want the table to store user id's as well as sessions, and the delete-on-close functionality is not desirable. Would also be better to get the table name from config/ENV than have it hard-coded.

**Comment by scientist1642** [comment]
> Thanks for this. I think what might be best if we just use SqlAlchemy, then we could basically use the same class to persist chat history in a variety of sql dbs like postgres, sqlite, mysql etc.

Good idea, especially since SqlAlchemy is already a dependency. 

> I just came across this looking for a solution to store users' chat histories - in order to replicate eg the ChatGPT history feature, you want the table to store user id's as well as sessions, and the delete-on-close functionality is not desirable. Would also be better to get the table name from config/ENV than have it hard-coded.

I guess in that case one can make a separate table `chat` himself that would have user_id session_id fields. It probably comes down to how general / simple langchain wants to be. As for the table name - you can pass it to a constructor right now.

**Comment by scientist1642** [comment]
Hmm, why didn't running lint locally caught this?

**Review by hwchase17 — APPROVED** [review]

**Pull request merged**
