### PR TITLE
Scores are explained in vectorestore docs

### PR DESCRIPTION
**Pull request by berkedilekoglu**
# Scores in Vectorestores' Docs Are Explained

Following vectorestores can return scores with similar documents by using `similarity_search_with_score`:
- chroma
- docarray_hnsw
- docarray_in_memory
- faiss
- myscale
- qdrant
- supabase
- vectara
- weaviate

However, in documents, these scores were either not explained at all or explained in a way that could lead to misunderstandings (e.g., FAISS). For instance in FAISS document: if we consider the score returned by the function as a similarity score, we understand that a document returning a higher score is more similar to the source document. However, since the scores returned by the function are distance scores, we should understand that smaller scores correspond to more similar documents.

For the libraries other than Vectara, I wrote the scores they use by investigating from the source libraries. Since I couldn't be certain about the score metric used by Vectara, I didn't make any changes in its documentation. The links mentioned in Vectara's documentation became broken due to updates, so I replaced them with working ones.

VectorStores / Retrievers / Memory
  - @dev2049

my twitter: [berkedilekoglu](https://twitter.com/berkedilekoglu)

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
this is awesome!

would it be possible to update the docstrings in the files themselves as well?

**Comment by berkedilekoglu** [comment]
> this is awesome!
> 
> would it be possible to update the docstrings in the files themselves as well?

Of course! I'm on it.

**Comment by berkedilekoglu** [comment]
I updated the docstrings in the relevant functions in vectorestore files.
@hwchase17

**Review by hwchase17 — APPROVED** [review]
this is greatly appreciated - thanks!

**Pull request merged**
