### PR TITLE
Convenient filter pass to as_retriver() for vectorstores

### PR DESCRIPTION
**Pull request by Bytestorm5**
**Description:** Makes it more intuitive to pass filters to VectorStore Retrievers from `as_retriever`, by allowing for it to be passed as an argument separately from search_kwargs.

This is related to #7002, but I wouldn't resolve because that calls for taking all search arguments as direct keyword arguments, while this is currently only for filters. Other arguments seem to be mostly primitive types which aren't as unwieldy to pass as a dict- with the docstring it should hopefully be clearer how to pass those arguments.

### CODE REVIEW

**Comment by Bytestorm5** [comment]
@eyurtsev

**Review by hwchase17 — COMMENTED** [review]
the docstring definitely helps, but idk if popping `filter` and putting it there does

if anything. i would just beef up the docstring and NOT change any code. that should help make it clearer and also avoid some black magic/confusion about where to pass filter (by itself? in search_kwargs?)

**Comment by Bytestorm5** [comment]
Yeah that's fair, I guess it is rather weird to have only that one parameter be separate from the other keyword arguments. I'll revert the changes to the method itself in a minute

**Review by hwchase17 — APPROVED** [review]
lgtm - i think even better would be to add a concrete example, but im also happy to add

**Comment by Bytestorm5** [comment]
Yeah I'm looking for somewhere to put an example, I'm not sure where though. I was thinking to put it under the RetrievalQA Use Case but I'm not sure.

**Comment by Bytestorm5** [comment]
I think it makes sense to put it after the Custom Prompts section of [QA using a Retriever](https://python.langchain.com/docs/use_cases/question_answering/how_to/vector_db_qa)- working on the section now

**Comment by Bytestorm5** [comment]
@hwchase17 I think it's good to go, lmk what you think

**Pull request merged**
