### PR TITLE
core: fixed circular dependency with json schema

### PR DESCRIPTION
**Pull request by thebhulawat**
**Description:** Circular dependencies when parsing references leading to `RecursionError: maximum recursion depth exceeded` issue. This PR address the issue by handling previously seen refs as in any typical DFS to avoid infinite depths. 

**Issue:** https://github.com/langchain-ai/langchain/issues/12163

 **Twitter handle:** https://twitter.com/theBhulawat 

- [x] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

### CODE REVIEW

**Comment by eyurtsev** [comment]
Awesome @namsgit would you be wiliing to add a unit test and type hints?

**Comment by namsgit** [comment]
@eyurtsev Thank you. I have added tests.

**Comment by namsgit** [comment]
@eyurtsev Requesting for your review.

**Comment by thebhulawat** [comment]
@baskaryan Sorry if I am bothering but if you or eyurtsev can have a look at the PR, would be great!

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
