### PR TITLE
Extend OpenAIEmbeddings class to support non-`tiktoken` based embeddings

### PR DESCRIPTION
**Pull request by xychelsea**

### CODE REVIEW

**Comment by xychelsea** [comment]
I'm having a bad day with the linter

**Comment by baskaryan** [comment]
running `make format` and `make lint` from `libs/langchain` should let you fix and test things locally! also happy to help fix things if you want to give me write access to your fork (or can merge into a branch of my own and land from there)

**Comment by xychelsea** [comment]
I wasn't going to set up a whole dev environment for this, but I shall now

**Comment by baskaryan** [comment]
if helpful
```bash
cd libs/langchain
poetry install --with dev,lint,test,typing
make format
make lint
```

**Review by hwchase17 — APPROVED** [review]
thanks!

**Pull request merged**
