### PR TITLE
Use bulk to complete Elasticsearch batch deletion.

### PR DESCRIPTION
**Pull request by dm57**
This PR is to complete todo in 'langchain/vectorstores/elastic_vector_search.py' that want use bulk to complete Elasticsearch batch deletion.

By the way:  this PR is passing linting and testing before submitting.  already run `make format`, `make lint` and `make test` locally.

### CODE REVIEW

**Comment by joemcelroy** [comment]
Yep supports [bulk deletes](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/elasticsearch.py#L730). 

See https://python.langchain.com/docs/integrations/vectorstores/elasticsearch#im-using-elasticvectorsearch on how to migrate. 

I recommend you use Approx instead rather than brute force (which is what the ElasticVectorSearch does via script_score)

**Comment by leo-gan** [comment]
@dm57 Hi , could you, please, address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

**Comment by eyurtsev** [comment]
@joemcelroy does the previous implementation still have users? Should we add the bulk functionality anyway?

**Comment by joemcelroy** [comment]
hey @eyurtsev - we're tracking usage atm to see how big usage is. We would prefer them to move over to ElasticsearchStore (which supports everything ElasticVectorSearch has and more) but if usage is still high, something we should consider again. 

Will let you know in a couple of weeks.

**Comment by efriis** [comment]
@joemcelroy any update on the usage numbers?

**Comment by joemcelroy** [comment]
@efriis will share some stats offline but TLDR the ElasticsearchStore is showing much higher usage compared with ElasticVectorStore, to a point we much rather developers use ElasticsearchStore as has all the bulk batching support,

**Comment by efriis** [comment]
Sounds good. Closing! @dm57 looks like you should migrate to that if you haven't yet :)

**Pull request closed without merging**
