### PR TITLE
community:ChatZhipuAI:ADAPTS to new version zhipuai library

### PR DESCRIPTION
**Pull request by ptonlix**
- **Description:**  Due to the upgrade of the zhipuai library to version 2.0.1, the original code is no longer suitable. The new code supports ZhiPu GLM-3-turbo and GLM4.
Zhipuai library information: https://pypi.org/project/zhipuai/
Zhipuai official API documentation: https://open.bigmodel.cn/dev/api#glm-3-turbo
  - **Issue:**  #16330
  - **Twitter handle:** @ptonlix

### CODE REVIEW

**Comment by LuckyLearning** [comment]
检查一下你的文档，你把秘钥弄上去了

**Comment by Astlvk** [comment]
@ptonlix 大佬，单元测试没过，看起来是单元测试这边的依赖没有更新到zhipu 2.0.1。

**Comment by ptonlix** [comment]
> 检查一下你的文档，你把秘钥弄上去了 @ptonlix

谢谢 没注意～

**Comment by ptonlix** [comment]
> @ptonlix 大佬，单元测试没过，看起来是单元测试这边的依赖没有更新到zhipu 2.0.1。
有点难顶，依赖冲突了 
Because no versions of zhipuai match >2.0.1,<3.0.0
 and zhipuai (2.0.1) depends on pydantic (>=2.5.2), zhipuai (>=2.0.1,<3.0.0) requires pydantic (>=2.5.2).
And because javelin-sdk (0.1.8) depends on pydantic (>=1.10.7,<2.0.0)
 and no versions of javelin-sdk match >0.1.8,<0.2.0, zhipuai (>=2.0.1,<3.0.0) is incompatible with javelin-sdk (>=0.1.8,<0.2.0).
So, because langchain-community depends on both javelin-sdk (^0.1.8) and zhipuai (^2.0.1), version solving failed.

**Comment by Astlvk** [comment]
> > @ptonlix 大佬，单元测试没过，看起来是单元测试这边的依赖没有更新到zhipu 2.0.1。
> 
> 有点难顶，依赖冲突了。zhipuai 所需pydantic版本太高 Because no versions of zhipuai match >2.0.1,<3.0.0 and zhipuai (2.0.1) depends on pydantic (>=2.5.2), zhipuai (>=2.0.1,<3.0.0) requires pydantic (>=2.5.2). And because javelin-sdk (0.1.8) depends on pydantic (>=1.10.7,<2.0.0) and no versions of javelin-sdk match >0.1.8,<0.2.0, zhipuai (>=2.0.1,<3.0.0) is incompatible with javelin-sdk (>=0.1.8,<0.2.0). So, because langchain-community depends on both javelin-sdk (^0.1.8) and zhipuai (^2.0.1), version solving failed.

难顶，看来只能抄下大佬代码，先用着了。

**Comment by Shkklt** [comment]
> [@ptonlix](/ptonlix) [ptonlix](/ptonlix) changed the title ~community:ChatZhipuAI:ADAPTS to new version zhipuai libraryNew version ChatZhipuAI~ community:ChatZhipuAI:ADAPTS to new version zhipuai library [Jan 24, 2024](#event-11572610109)

大佬代码在哪里？

**Comment by ptonlix** [comment]
> > [@ptonlix](/ptonlix) [ptonlix](/ptonlix) changed the title ~community:ChatZhipuAI:ADAPTS to new version zhipuai libraryNew version ChatZhipuAI~ community:ChatZhipuAI:ADAPTS to new version zhipuai library [Jan 24, 2024](#event-11572610109)
> 
> 大佬代码在哪里？

看一下我的commit

**Comment by web4zn** [comment]
```python
glm = ChatZhipuAI(
    temperature=0.5,
    api_key=zhipuai_api_key,
    model="chatglm_turbo",
)

from langchain_core.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_messages([
    ("system", "You are world class technical documentation writer."),
    ("user", "{input}")
])

chain = prompt | glm
chain.invoke({"input": "how can langsmith help with testing?"})
```

@ptonlix 你好，我在学习langchain过程，替换你的代码之后，正常的invoke是没有问题的，但是用chain遇到以下报错，但是我没找到问题在哪，你有遇到这个问题吗？

`zhipuai.core._errors.APIRequestFailedError: Error code: 400, with error text {"error":{"code":"1214","message":"history参数非法。请检查文档。"}} `

**Comment by lonffreytu** [comment]
> ```python
> glm = ChatZhipuAI(
>     temperature=0.5,
>     api_key=zhipuai_api_key,
>     model="chatglm_turbo",
> )
> 
> from langchain_core.prompts import ChatPromptTemplate
> prompt = ChatPromptTemplate.from_messages([
>     ("system", "You are world class technical documentation writer."),
>     ("user", "{input}")
> ])
> 
> chain = prompt | glm
> chain.invoke({"input": "how can langsmith help with testing?"})
> ```
> 
> @ptonlix 你好，我在学习langchain过程，替换你的代码之后，正常的invoke是没有问题的，但是用chain遇到以下报错，但是我没找到问题在哪，你有遇到这个问题吗？
> 
> `zhipuai.core._errors.APIRequestFailedError: Error code: 400, with error text {"error":{"code":"1214","message":"history参数非法。请检查文档。"}} `

 模型名称“chatglm_turbo”已过期。现在仅支持glm-3-turbo或以上模型。具体可参考官方api文档 https://open.bigmodel.cn/dev/api#language

另外感谢楼主开源出适配最新gml的版本

**Comment by baskaryan** [comment]
hey @ptonlix, is this pr still needed?

**Comment by linancn** [comment]
> hey @ptonlix, is this pr still needed?

@ptonlix  @baskaryan This PR should be closed, already solved by #16695.

**Comment by baskaryan** [comment]
> > hey @ptonlix, is this pr still needed?
> 
> @ptonlix @baskaryan This PR should be closed, already solved by #16695.

closing per ^

**Pull request closed without merging**
