### PR TITLE
Docugami DataLoader

### PR DESCRIPTION
**Pull request by tjaffri**
### Adds a document loader for Docugami

Specifically:

1. Adds a data loader that talks to the [Docugami](http://docugami.com) API to download processed documents as semantic XML
2. Parses the semantic XML into chunks, with additional metadata capturing chunk semantics
3. Adds a detailed notebook showing how you can use additional metadata returned by Docugami for techniques like the [self-querying retriever](https://python.langchain.com/en/latest/modules/indexes/retrievers/examples/self_query_retriever.html)
4. Adds an integration test, and related documentation

I ran the following locally:

- make format
- make lint
- poetry run pytest tests/integration_tests/document_loaders/test_docugami.py

Here is an example of a result that is not possible without the capabilities added by Docugami (from the notebook):

image

### CODE REVIEW

**Comment by tjaffri** [comment]
Thank you in advance for your review @dev2049 @eyurtsev. I just marked this draft PR ready for review, so please let me know if I can add any other details, or any feedback I can resolve quickly.

**Comment by tjaffri** [comment]
@dev2049 @eyurtsev would really appreciate your feedback on this. Excited to hear what you think, would love to move quickly to address any feedback you may have.

Also, @hwchase17 I have been watching your recents posts regarding the self-querying retriever on twitter, e.g. this one from yesterday: https://twitter.com/hwchase17/status/1656791492579713024 so you might want to check out the notebook in this PR which uses metadata from other parts of the document via the self-querying retriever.

Also I noticed you will be speaking about retrieval on June 8: https://twitter.com/zilliz_universe/status/1657084479993683969 and we would love to help however we can. Docugami was created by documents experts, including [Jean Paoli](https://en.wikipedia.org/wiki/Jean_Paoli) who is one of the authors of the XML standard, and drove the creation of the OpenXML format (i.e. docx) and we believe we have a few things to say about the space.

**Comment by eyurtsev** [comment]
@tjaffri thanks for submitting the PR! I'll review on Monday (maybe before if I find enough time). Apologies for the delay!

**Comment by eyurtsev** [comment]
Merged on separate branch

**Pull request closed without merging**
