### PR TITLE
Add a SQL agent for interacting with SQL Databases and JSON Agent for interacting with large JSON blobs

### PR DESCRIPTION
**Pull request by agola11**
This PR adds 

* `ZeroShotAgent.as_sql_agent`, which returns an agent for interacting with a sql database. This builds off of `SQLDatabaseChain`. The main advantages are 1) answering general questions about the db, 2) access to a tool for double checking queries, and 3) recovering from errors
* `ZeroShotAgent.as_json_agent` which returns an agent for interacting with json blobs.
* Several examples in notebooks

### CODE REVIEW

**Comment by fpingham** [comment]
Awesome work!

Been trying out, have two suggestions that I would add to the prompt:
1. "When possible, don't query exactly but use 'LIKE' to make your queries more robust."
2. "Query for only as many columns you need to answer the question, not more. When possible, avoid using 'SELECT *' and instead specify which columns you need."

I can commit them myself afterwards though if you agree.

**Comment by agola11** [comment]
@fpingham thanks for the suggestions! I'll add them in to this PR

**Comment by agola11** [comment]
@fpingham -- I didn't have much luck with "When possible, don't query exactly but use 'LIKE' to make your queries more robust." but feel free to experiment and add in a follow up PR!

**Comment by fpingham** [comment]
@agola11 I missed this message, that's fine! Actually @jzluo added a better way to limit the number of rows that works cross-dialect so I might add it later to the agent as well.

**Pull request merged**
