### PR TITLE
[bug-fix] langchain-Fix bug in OutputFixingParser

### PR DESCRIPTION
**Pull request by ZhangShenao**
#24219  Fix bug in OutputFixingParser.
The full error stack have been shown in issue #24219 
The param `input` should be `completion`

### CODE REVIEW

**Comment by ZhangShenao** [comment]
@efriis Please review

**Comment by ZhangShenao** [comment]
#24219

**Comment by ZhangShenao** [comment]
@baskaryan  @efriis Is there any problems, please?

**Comment by lynscott** [comment]
I am experiencing this bug as well. Is there a temp work around you have found @ZhangShenao ?

**Review by efriis — APPROVED** [review]
Would love to get @hmasdev or @eyurtsev eyes to make sure this wasn't intentional on #19792

**Comment by ZhangShenao** [comment]
@lynscott I encountered this problem in my own project

**Comment by ZhangShenao** [comment]
@efriis OK

**Comment by hmasdev** [comment]
Thanks for fix @ZhangShenao 


@efriis 

> Would love to get @hmasdev or @eyurtsev eyes to make sure this wasn't intentional on #19792

this PR looks correct to me.
'input' keyword was not intentional in #19792.
I already created #23967 with tests.

**Comment by lynscott** [comment]
@ZhangShenao well yes of course, so have I.
I was asking if you've found a temporary solution to the problem until your fix is merged, but I'll patch your fix myself for now. Thanks

**Comment by efriis** [comment]
ah great merging in the one with unit tests!

**Pull request closed without merging**
