### PR TITLE
set litellm max_tokens=None

### PR DESCRIPTION
**Pull request by zhangnew**
- **Description:** The default value of the `max_tokens` for litellm is 256. It should be increased to avoid truncation of replies.

### CODE REVIEW

**Comment by baskaryan** [comment]
cc @krrishdholakia, seems reasonable to me

**Comment by krrishdholakia** [comment]
If you set max_tokens = None, this will cause errors for models like Anthropic which require it to be passed in. @zhangnew why not set it higher for your use-case? 

or do you need a controllable default across multiple LLMs?

**Comment by zhangnew** [comment]
I just feel that 256 is too small, and setting it to a larger value may be a good solution. However, I don't know what value would be appropriate. I'm using LangChain through another project, and it took me some time to realize that the issue was due to the limitation of max_tokens=256 here.

**Comment by krrishdholakia** [comment]
Hey @zhangnew sounds good. let's go with this approach if it helps you, and we can resolve anything that comes up.

**Comment by baskaryan** [comment]
Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

**Pull request closed without merging**
