### PR TITLE
community: Add Baichuan Text Embedding Model and Baichuan Inc introduction

### PR DESCRIPTION
**Pull request by baichuan-assistant**
- **Description:** Adding Baichuan Text Embedding Model and Baichuan Inc introduction.

 Baichuan Text Embedding ranks #1 in C-MTEB leaderboard: https://huggingface.co/spaces/mteb/leaderboard

### CODE REVIEW

**Review by baskaryan — COMMENTED** [review]
can we remove the changes to `libs/langchain`? only `libs/community` needs to be updated for new code, the imports in `libs/langchain` are only kept around for backwards compatibility and will be removed in the next minor version release

**Comment by baichuan-assistant** [comment]
> can we remove the changes to `libs/langchain`? only `libs/community` needs to be updated for new code, the imports in `libs/langchain` are only kept around for backwards compatibility and will be removed in the next minor version release

Sure thing. Done.

**Review by baskaryan — APPROVED** [review]
thanks @baichuan-assistant!

**Comment by yhfwww** [comment]
Why I can't find BaichuanTextEmbeddings in langchain v0.1.4

**Comment by baichuan-assistant** [comment]
> Why I can't find BaichuanTextEmbeddings in langchain v0.1.4

This PR was merged 2 days ago. You might need to wait for the next langchain release :)

**Pull request merged**
