### PR TITLE
Change Anthropic LLM and Chat to be LangFlow friendly

### PR DESCRIPTION
**Pull request by jimwhite**
Change the Anthropic LLM and Chat classes to use model_name and default parameters the same way others do like OpenAI, Cohere, etc.  Added an alias for model to model_name for backwards compatibility.  By following the common pattern this will enable the Anthropic PR I'm working on for LangFlow (https://github.com/jimwhite/langflow/tree/anthropic) to work as expected.

#### Who can review?

Tag maintainers/contributors who might be interested:

  Models
  - @hwchase17
  - @agola11

### CODE REVIEW

**Review by hwchase17 — APPROVED** [review]
lgtm - thanks!

**Comment by jimwhite** [comment]
Friendly ping.

**Comment by leo-gan** [comment]
@jimwhite Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by jimwhite** [comment]
Actually I don't think this PR is needed anymore.  After resolving the conflict I see the conflict was with another change doing the same thing with Field(... alias).

**Pull request closed without merging**
