### PR TITLE
Pinecone: Support starter tier

### LINKED ISSUE #7472: Pinecone: Support V4
### Feature request

Adapt the pinecone vectorstore to support upcoming V4. The changes are related to removing namespaces and `delete by metadata` feature.

### Motivation

Indexes in upcoming Pinecone V4 won't support:  
* namespaces
* `configure_index()`
* delete by metadata
* `describe_index()` with metadata filtering
* `metadata_config` parameter to `create_index()`
* `delete()` with the `deleteAll` parameter

### Your contribution

I'll do it.

### PR DESCRIPTION
**Pull request by StankoKuveljic**
* Resolves #7472
* Remove `namespace` usage in Pinecone vectorstore
* Remove delete by metadata filter

@rlancemartin, @eyurtsev

### CODE REVIEW

**Comment by jamescalam** [comment]
@rlancemartin noting that I've also taken a look at this from Pinecone side and all looks good

**Review by rlancemartin — APPROVED** [review]
Thanks!

**Comment by jamescalam** [comment]
hey @rlancemartin — I realize this change is not needed. For more context, this change was made proactively in preparation for upcoming changes to our Starter (free) plan. It does not apply to our standard and enterprise plans

Could we revert this PR while we discuss a better way of handling this, thanks

**Comment by PlatosTwin** [comment]
+1 to @jamescalam's note. The change in [9d13dcd](https://github.com/hwchase17/langchain/commit/9d13dcd17c2dfab8f087bcc37e99f1181dfe5c63) is a breaking change and will cause users who currently initialize their Pinecone vector store with a `namespace` argument to face a `TypeError`. @rlancemartin, I recommend rolling back this change.

**Comment by DennisPeeters** [comment]
Yep, I got the namespace error already, reverting back would be nice

**Comment by levalencia** [comment]
same issue here, I had to go back to 0.0.229

**Comment by kkbpower** [comment]
Thank you very much

**Comment by rlancemartin** [comment]
Revert is done.

@jamescalam let's have a look at the integration test: why didn't it catch the breakage?

https://github.com/hwchase17/langchain/blob/master/tests/integration_tests/vectorstores/test_pinecone.py

**Pull request merged**
