### PR TITLE
Support for a PowerBI agent and toolkit

### PR DESCRIPTION
**Pull request by eavanvalkenburg**
Initial version of support to have a bot talk to powerbi, docs still to be added.

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
this is absolutely awesome

i want to spend a more time tmrw/this weekend looking at it, but at first glance seems pretty good. love the notebook. is there anything missing in your mind or is this good to go?

**Comment by eavanvalkenburg** [comment]
Mostly some notes on best practices and on authentication, for in the notebook and I do want to test with a more complex dataset, plan to do that early next week, this might cause some prompt changes, especially for the query checker. I noticed at times that that just gives back the same thing each time and then it doesn't make sense to keep running those queries, so that should be improved.

But, overall it seems to work well already!

**Comment by hwchase17** [comment]
> Mostly some notes on best practices and on authentication, for in the notebook and I do want to test with a more complex dataset, plan to do that early next week, this might cause some prompt changes, especially for the query checker. I noticed at times that that just gives back the same thing each time and then it doesn't make sense to keep running those queries, so that should be improved.
> 
> But, overall it seems to work well already!

cool! should i hold off on landing until early next week then?

**Comment by eavanvalkenburg** [comment]
Just also added some refinement, but give me till next week to finish.

**Comment by hwchase17** [comment]
> Just also added some refinement, but give me till next week to finish.

sounds great!

**Comment by eavanvalkenburg** [comment]
@hwchase17 this is now good to go, also includes async support and I've split the few-shot examples out so that you can supply your own which makes the recognition much better! Still getting some weird pydantic error that I can't figure out, maybe you know more!

**Comment by eavanvalkenburg** [comment]
apparently pydantic didn't like new style typing with __future__.annotations, after reverting it works now!

**Comment by hwchase17** [comment]
gonna try to fix and merge in!

**Comment by poweihuang0817** [comment]
@eavanvalkenburg Hello, when I run example code, it shows this. Do you know how to solve this?

Traceback (most recent call last):
  File ".py", line 20, in <module>
    powerbi=PowerBIDataset(None, "b0c0d9dc-726e-4bf5-8344-e6cc807c4a75", ['tableName'], DefaultAzureCredential()),
  File "pydantic\main.py", line 332, in pydantic.main.BaseModel.__init__
TypeError: __init__() takes exactly 1 positional argument (5 given)

**Comment by eavanvalkenburg** [comment]
fixed in #3426

**Pull request merged**
