### PR TITLE
Feature faiss delete

### PR DESCRIPTION
**Pull request by fqassemi**

### CODE REVIEW

**Comment by fqassemi** [comment]
I have fixed the issues, unfortunately some of the imports were not pushed correctly .

**Review by hwchase17 — APPROVED** [review]
made some comments and fixed

**Comment by imClumsyPanda** [comment]
Great work! Really need this class method!

**Comment by KevinZhang19870314** [comment]
@fqassemi @hwchase17 After remove the ids, its necessary to re-indexing index_to_docstore_id. Otherwise, we will get the Key not found error when loop index_to_docstore_id next time. See https://github.com/langchain-ai/langchain/issues/2699#issuecomment-1618163649.

**Pull request merged**
