### PR TITLE
feat: add BigFramesLLM integration

### PR DESCRIPTION
**Pull request by ashleyxuu**
This PR adds [Bigframes (BigQuery DataFrames)](https://cloud.google.com/python/docs/reference/bigframes/latest) integration to Langchain. BigQuery DataFrames provides a Pythonic DataFrame and machine learning (ML) API powered by the BigQuery engine. BigFrames supports manipulating data in the DataFrame to build LLM prompts, and sending DataFrame prompts to the LLM model using [text-bison model of the PaLM API](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/text)

### CODE REVIEW

**Review by baskaryan — COMMENTED** [review]
thanks for pr @ashleyxuu! what's the benefit of using this versus the VertexAI LLM directly?

**Comment by ashleyxuu** [comment]
> thanks for pr @ashleyxuu! what's the benefit of using this versus the VertexAI LLM directly?

BigFrames is a unified Python API on top of BigQuery’s managed storage and BigLake tables. BigFrames lets Python developers discover, describe, and understand the data available to them in BigQuery by providing a Python compatible API that can automatically scale to BigQuery sized datasets. VertexAI LLM is just the model.

So, BigFrames is a pivotal bridge connecting Google BigQuery with the diverse Python open source software ecosystem for data scientists. 

Our next goal is to support `_generate()` with DataFrame as input and output for large datasets. We can talk more about those use cases. My email is ashleyxu@google.com.

**Comment by baskaryan** [comment]
@ashleyxuu added a `generate_df` method that takes dataframes as input and returns dataframes as output — is that what you had in mind?

**Comment by ashleyxuu** [comment]
> thanks for pr @ashleyxuu! what's the benefit of using this versus the VertexAI LLM directly?

Yes, exactly. But the problem is: `generate_df` and `_generate` methods will then return a `bigframes.pandas.DataFrame` type rather than `LLMResult` type. However, the LLMChain class needs a `LLMResult` type to get it `run` or `invoke`. Any ideas about that? Should I redefine a `BigFramesChain`?

**Comment by ashleyxuu** [comment]
> @ashleyxuu added a `generate_df` method that takes dataframes as input and returns dataframes as output — is that what you had in mind?

Yes, exactly. But the problem is: generate_df and _generate methods will then return a bigframes.pandas.DataFrame type rather than LLMResult type. However, the LLMChain class needs a LLMResult type to get it run or invoke. Any ideas about that? Should I redefine a BigFramesChain?

**Comment by baskaryan** [comment]
> > @ashleyxuu added a `generate_df` method that takes dataframes as input and returns dataframes as output — is that what you had in mind?
> 
> Yes, exactly. But the problem is: `generate_df` and `_generate` methods will then return a `bigframes.pandas.DataFrame` type rather than `LLMResult` type. However, the LLMChain class needs a `LLMResult` type to get it run or invoke. Any ideas about that? Should I redefine a BigFramesChain?

the _geneate method is still returning an LLMResult

**Comment by ashleyxuu** [comment]
@baskaryan

- I added `_generate_df()`, `_generate_df_helper`, and `generate_df_prompt` for DataFrames generation. 
- I added `BigFramesChain` for the DataFrame use cases, and `test_bigframesllm` for testing using BigFramesChain.
- I added a sample notebook demonstrating the use cases (All the code are runnable)

Would you mind reviewing and also helping with formatting to pass the tests? Appreciate it!

**Comment by baskaryan** [comment]
Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

**Pull request closed without merging**
