### PR TITLE
Documentation change for OracleDB

### PR DESCRIPTION
**Pull request by rohanaggarwal7997**
Thank you for contributing to LangChain!

Documentation change for OracleDB

Fixed several things in Oracle Documentation.

### CODE REVIEW

**Comment by rohanaggarwal7997** [comment]
Hi Can the reviewers check one thing ? Please see the image for the code - the code has correct link but the vercel is generating it incorrectly
Screenshot 2024-05-15 at 9 34 23 PM

https://langchain-j4ca7bsvg-langchain.vercel.app/v0.2/docs/integrations/vectorstores/oracle/

**Comment by hwchase17** [comment]
thanks for flagging that link, @efriis will look into it

**Comment by rohanaggarwal7997** [comment]
@hwchase17 @efriis we are getting a lot of pings from internal oracle customers that need these documentation changes in. Many people are doing pocs with oracle and langchain. Can we please get this in with the link fix as soon as possible. I’ll be grateful.

**Comment by efriis** [comment]
Fixing link rewrite in #21775

**Comment by rohanaggarwal7997** [comment]
@efriis since https://github.com/langchain-ai/langchain/pull/21775 merged - can you merge this now

**Comment by rohanaggarwal7997** [comment]
@hwchase17 @efriis can we please merge this ?

**Comment by rohanaggarwal7997** [comment]
@hwchase17 @efriis Can we please merge this ?

**Review by baskaryan — APPROVED** [review]

**Pull request merged**
