### PR TITLE
test: linting

### PR DESCRIPTION
**Pull request by eyurtsev**
cd libs/communuity

```
grit check 
```

---

@morgante I can't figure out how to the following:

1. Configure `grit check` to work so that it goes through all the patterns in the directory
2. Add a helpful error message that explains the pattern violation and include instructions for the user

Would you be willing to point me to any documentation for this?

### CODE REVIEW

**Comment by eyurtsev** [comment]
cc @efriis

**Comment by eyurtsev** [comment]
Apologies failure to read instructions -- going to follow https://docs.grit.io/guides/config first

**Comment by morgante** [comment]
Using a Markdown file is the easiest.

Ex create .grit/patterns/pydantic.md:
````
---
level: error
---

# Pydantic Usage

Only use allowed Pydantic classes and functions.

```grit
engine marzano(0.1)
language python


`from pydantic import $y` where {
    $y <: ! every contains or  {"model_validator", "BaseModel", "field_validator", "SecretStr", "ValidationError", "Field", "ConfigDict", "PrivateAttr"}
}
```

````

**Comment by eyurtsev** [comment]
Closing for now, we will resurrect if we implement the linting rules

**Pull request closed without merging**
