### PR TITLE
Nested models & exclude fields

### PR DESCRIPTION
**Pull request by L4rryFisherman**
Description:
Add functionalities to the parser and output formatter:
- Recursively retrieves fields from any nested models
- Takes an optional list of fields of the (nested) model(s) to be excluded.
- If any `required` fields are specified as excluded, the class will throw a warning and create a new Pydantic model is created for output instructions, and to parse against.

Dependencies: 
- `warnings`

Tag maintainer: 
@baskaryan 

Please let me know if I should satisfy any additional requirements! :)

### CODE REVIEW

**Comment by L4rryFisherman** [comment]
Added a commit to address lint errors:

- Explicitly prevent `in` on optional lists
- Provide type for `json_object`

**Comment by baskaryan** [comment]
not sure i fully understand the use case — could you provide an example of how new functionality would be used?

would also be great to add some unit tests, imagine those would also clarify

**Comment by leo-gan** [comment]
@L4rryFisherman Hi , could you, please, resolve the merging issues and address the last comments (if needed)? After that, ping me and I push this PR for the review. Thanks!

**Comment by efriis** [comment]
Closing because the PR wouldn't line up with the current directory structure of the library (would need to be in /libs/langchain/langchain instead of /langchain). Feel free to reopen against the current head if it's still relevant!

**Pull request closed without merging**
