### PR TITLE
core: [Vector Store] Optimize in memory vector store

### PR DESCRIPTION
**Pull request by ZhangShenao**
- Change memory store to Dict[str, Document]
- Save embedded vector in metadata.
- Add unit test for getting vector

### CODE REVIEW

**Review by baskaryan — COMMENTED** [review]
what's the motivation for this pr?

**Review by eyurtsev — CHANGES_REQUESTED** [review]
Hi thanks for the contribution!

This change was not done to avoid making a breaking change in `self.store` since it's possible that some users rely on the existing format.

The vector embedding should not be a part of the metadata.

**Comment by ZhangShenao** [comment]
> Hi thanks for the contribution!
> 
> This change was not done to avoid making a breaking change in `self.store` since it's possible that some users rely on the existing format.
> 
> The vector embedding should not be a part of the metadata.

Thank you for your guidance. Could you please help modify this PR?

**Comment by hwchase17** [comment]
> * Change memory store to Dict[str, Document]

I dont think we want to make this change at the moment - it would be a break change
> * Save embedded vector in metadata.

Currently not where we put vectors

> * Add unit test for getting vector

This may be useful, but should be separate pr

**Pull request closed without merging**
