### PR TITLE
feat: Google Vertex AI Search Retriever - Add support for Website Data Stores

### PR DESCRIPTION
**Pull request by holtskinner**
- Only works for Data stores with Advanced Website Indexing
  - https://cloud.google.com/generative-ai-app-builder/docs/about-advanced-features
- Minor restructuring - Follow up to #10513
  - Remove outdated docs (readded in https://github.com/langchain-ai/langchain/pull/11620)
  - Move legacy class into new py file to clean up the directory
    - Shouldn't cause backwards compatibility issues as the import works the same way for users

### CODE REVIEW

**Comment by holtskinner** [comment]
@baskaryan

**Comment by holtskinner** [comment]
@baskaryan @leo-gan Can I get a review on this, please?

**Review by baskaryan — APPROVED** [review]
would note that it's technically still breaking if someone was importing from file directly (instead of from retrievers module). but will let you decide if that's ok

**Comment by holtskinner** [comment]
Nobody should be importing from the file directly. All of the documentation/samples have always been using the retrievers module. And I checked throughout the LangChain codebase to make sure that all other usage is from the retrievers module.

**Comment by holtskinner** [comment]
@baskaryan If there's an issue with the file restructuring, I can revert those changes.

Is there anything blocking this from merging now?

**Comment by baskaryan** [comment]
sorry for delay, thanks @holtskinner!

**Pull request merged**
