### PR TITLE
add neo4j query constructor for self query

### PR DESCRIPTION
**Pull request by moyid**
- [x]  **PR title - community: add neo4j query constructor for self query**

- [x] **PR message**
    - **Description:** adding a Neo4jTranslator so that the Neo4j vector database can use SelfQueryRetriever
    - **Issue:** this issue had been raised before in #19748
    - **Dependencies:** none. 
    - **Twitter handle:** @moyi_dang
    - p.s. I have not added the query constructor in BUILTIN_TRANSLATORS in this PR, I want to make changes to only one package at a time.

- [x] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Comment by moyid** [comment]
Hi @ccurme,

I’ve made a small contribution to the LangChain community and would appreciate it if you could help approve the workflows.

Thank you for your support!

**Comment by baskaryan** [comment]
cc @tomasonjo @jexp

**Comment by tomasonjo** [comment]
Thanks for your PR... can you please fix notebook as it has import error and can you leave all the outputs, so that people know what to expect.

I'll try it out later!

**Comment by moyid** [comment]
@tomasonjo thanks for taking an initial look! I have fixed the notebook, it's working now!

**Review by tomasonjo — APPROVED** [review]
Thanks!

**Comment by tomasonjo** [comment]
Btw... i think file 'libs/community/file::memory:?cache=shared' should be deleted

**Review by ccurme — APPROVED** [review]

**Pull request merged**
