### PR TITLE
partners: add safety_settings parameter for ChatGoogleGenerativeAI

### PR DESCRIPTION
**Pull request by wengcan**

### CODE REVIEW

**Comment by darrenchiu** [comment]
this feature is useful! hope to get it merged soon. Google's default setting is too sensitive on safety that it even block a local news article summary on the death of a celebrity.

**Comment by darrenchiu** [comment]
@efriis sorry for tagging. I am new to this repo but just want to see when can I expect this to be merged? Not trying to push and understand that you are probably busy with a lot of PR. But if it is going to take a while, I might look for an alternative workaround for now.

Thanks a lot!

**Comment by wengcan** [comment]
> @efriis sorry for tagging. I am new to this repo but just want to see when can I expect this to be merged? Not trying to push and understand that you are probably busy with a lot of PR. But if it is going to take a while, I might look for an alternative workaround for now.
> 
> Thanks a lot!

@darrenchiu  if you use pipenv, You can incorporate this into your Pipfile as a temporary workaround :
` langchain-google-genai = {git = "https://github.com/wengcan/langchain.git", editable = true, subdirectory = "libs/partners/google-genai"}`

**Comment by efriis** [comment]
#16836

**Pull request closed without merging**
