### PR TITLE
core: prevent `'NoneType' object is not iterable` when using HumanMessagePromptTemplate and ImagePromptTemplate in combination

### PR DESCRIPTION
**Pull request by joegoldin**
- **Description:** prevent `'NoneType' object is not iterable` when using HumanMessagePromptTemplate and ImagePromptTemplate in combination
  - **Issue:** 
      - fixes #20820
      - related to #22024
  - **Dependencies:** none
  - **Twitter handle:** @joegoldin

### CODE REVIEW

**Review by eyurtsev — APPROVED** [review]
This looks great any chance you could add a unit test?

**Comment by thdesc** [comment]
@eyurtsev Can you have a look at this one please #22613 ? It is related to the this one.

**Comment by joegoldin** [comment]
> This looks great any chance you could add a unit test?

Yep, will get to that asap tonight, thanks!

**Comment by joegoldin** [comment]
@eyurtsev apologies, haven't had any free time lately to get to this!

**Comment by baskaryan** [comment]
believe this was fixed in #22613. let me know if i'm misunderstanding!

**Pull request closed without merging**
