### PR TITLE
Fixed import typo 

### PR DESCRIPTION
**Pull request by MattiaSangermano**
Fixed small import typo in react_docstore documentation

### CODE REVIEW

**Comment by DayuanJiang** [comment]
The submit seems import new typo, could you check it again?

**Comment by MattiaSangermano** [comment]
Yes, sorry you are right, now it works successfully

**Review by eyurtsev — CHANGES_REQUESTED** [review]
@MattiaSangermano something is off with your editor I think. new imports look wrong

**Comment by MattiaSangermano** [comment]
Hi Eugene, what's wrong? I installed langchain using the method described inside the [CONTRIBUTING.md](https://github.com/langchain-ai/langchain/blob/master/.github/CONTRIBUTING.md). I have also tried using a different editor but everything works smoothly.

**Comment by eyurtsev** [comment]
@MattiaSangermano I was wrong looks great! I was confused by the diff view for notebooks which

**Review by eyurtsev — APPROVED** [review]

**Pull request merged**
