### PR TITLE
[hotfix] Deep Lake fails on newer version due to hardcode

### PR DESCRIPTION
**Pull request by davidbuniat**
Hot Fixes for Deep Lake [would highly appreciate expedited review]

* deeplake version was hardcoded and since deeplake upgraded the integration fails with confusing error
* an additional integration test fixed due to embedding function
* Additionally fixed docs for code understanding links after docs upgraded
* notebook removal of public parameter to make sure code understanding notebook works

#### Who can review?
  @hwchase17  @dev2049

### CODE REVIEW

**Review by vowelparrot — APPROVED** [review]

**Review by hwchase17 — APPROVED** [review]
thanks

**Comment by davidbuniat** [comment]
thanks @hwchase17 @vowelparrot for your prompt follow up!

**Comment by karencfisher** [comment]
I just encountered this with version 3.6.5. Version check has not been updated, and is inconsistent as well. I.e., in deeplake.py, 127-132:

```
version = deeplake.__version__
if version != "3.6.2":
       raise ValueError(
            "deeplake version should be = 3.6.3, but you've installed"
             f" {version}. Consider changing deeplake version to 3.6.3 ."
        )
```
(This check will fail if version is 3.6.3!)

Suggestion (tested on my local installation):

1) define minimum_version globally, e.g., about line 23:

```
minimum_version = "3.6.3"
```

2) Modify version check to:

```
version = deeplake.__version__
if not version >= minimum_version:      
       raise ValueError(
            f"deeplake version should be >= {minimum_version}, but you've installed"
            f" {version}. Consider changing deeplake version to {minimum_version} or later ."
        )
```

3) Update one line of code when updating version, if necessary.

**Comment by davidbuniat** [comment]
@karencfisher which version of langchain are you using?

**Pull request merged**
