### PR TITLE
Langchain: FAISS Translator for Self Query Retriver

### PR DESCRIPTION
**Pull request by keenborder786**
**Description:** Issue #15331 pointed out that there was no support for FAISS for `SelfQueryRetriever`. Therefore, I decided to add the desired support. I understand that FAISS does not have an internal query language like other vector stores (e.g., Chroma), but I noticed that the current implementation of the `FAISS` VectorStore Class in Langchain allows the user to filter documents based on given metadata attributes. Therefore, the translator simply translates the structured query according to the logic of filtering defined in `similarity_search_with_score_by_vector` and `max_marginal_relevance_search_with_score_by_vector`, which filters the documents for the specific values present in metadata keys.

**Issue:** #15331

PS: I have not added the docs for this one. Only once you see the value in adding this translator, I will add the docs.

### CODE REVIEW

**Comment by keenborder786** [comment]
@hwchase17

**Comment by keenborder786** [comment]
@baskaryan

**Review by hwchase17 — COMMENTED** [review]
i def see the value

will defer to @baskaryan on correct way to implement

**Comment by CanIbeyourdog** [comment]
Thanks for your code! 
  When I use FAISS for Self-Query Retriver of official demo(https://python.langchain.com/docs/modules/data_connection/retrievers/self_query),I got a blank list.But Chroma works.

**Pull request closed without merging**
