### PR TITLE
Add oobabooga/text-generation-webui support as a llm

### PR DESCRIPTION
**Pull request by lonestriker**
Add oobabooga/text-generation-webui support as an LLM.  Currently, supports using text-generation-webui's non-streaming API interface.  Allows users who already have text-gen running to use the same models with langchain.

#### Before submitting

Simple usage, similar to existing LLM supported:

```
from langchain.llms import TextGen
llm = TextGen(model_url = "http://localhost:5000")
```
#### Who can review?

 @hwchase17 - project lead

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
lets add an example notebook as well

**Comment by lonestriker** [comment]
> lets add an example notebook as well

Thanks for the review. I've fixed the Black formatting and have added an example notebook.

**Comment by lonestriker** [comment]
Can a maintainer kick off the workflows?  I believe I've fixed the previous errors.

**Comment by lonestriker** [comment]
@hwchase17 can you help kick off the workflows for this PR? I believe I've fixed up all of the errors.

**Review by hwchase17 — APPROVED** [review]
looks reasonable, thanks!

**Pull request merged**
