### PR TITLE
Enhanced functionality of PostgresChatMessageHistory

### PR DESCRIPTION
**Pull request by rajib76**
- Description : The PostgresChatMessageHistory will be more useful if it stores the timestamp of each message. While retrieving the messages, it is currently retrieved ordering it by session id. However, in an actual chat, the sessionid will be maintained for the duration of the chat. So, the messages will need to b retrieved after sorting it by the timestamp. The enhancement that I have pushed adds timestamp as a field in the table. Also added a function messages_order_by_time which orders the messages by timestamp(either desc or asc based on the parameter passed)
-  Issue: NA
- Dependencies: datetime package,
- Tag maintainer: @hwchase17
- Twitter handle: NA

### CODE REVIEW

**Comment by rajib76** [comment]
@hwchase17 - Hi Harrison, can you please review and approve this for merge if you see this is useful. I have this now as a custom code, but would like to directly take it from langchain package

**Comment by rajib76** [comment]
@baskaryan 
@hwchase17 

I am using the same pull request(since it is still open) to request for merging another commit. This will be very useful and is actually required for auditability.

SQLDBCHAIN is now part of the experimental package. It uses the SQLDatabase class in the utilities package. Currently, the SQLDatabase does not take a parameter for "query tags". Most of the modern datawarehouses(and in this commit I have made the change for snowflake) support setting up a "query tag" to track where the query is being coming from. As part of this new commit I have added a parameter "query tag" as shown below


class SQLDatabase:
    """SQLAlchemy wrapper around a database."""

    def __init__(
        self,
        engine: Engine,
        schema: Optional[str] = None,
        metadata: Optional[MetaData] = None,
        ignore_tables: Optional[List[str]] = None,
        include_tables: Optional[List[str]] = None,
        sample_rows_in_table_info: int = 3,
        indexes_in_table_info: bool = False,
        custom_table_info: Optional[dict] = None,
        view_support: bool = False,
        max_string_length: int = 300,
        **query_tag: Optional = 'gen_ai_query'**    
    ):

and then set it up as below

            if self.dialect == "snowflake":
                print("metadata is ", self._metadata.schema)
                **connection.exec_driver_sql(
                    f"ALTER SESSION SET QUERY_TAG = '{self._query_tag}'"
                )**

Now, when I will execute the SQL Chain, all the queries generated by the LM will be tagged with the query tag. This will help monitor what queries are being triggered by the LM

**Comment by rajib76** [comment]
@hwchase17 - Hi Harrison, apologies for being a pest on this. Can you please help review the postgresqlmessagehistory and see if this can be approved. It will be a great help as I do not want to use much custom code but use as much as possible directly fRom the package

**Comment by leo-gan** [comment]
@rajib76 Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by rajib76** [comment]
@leo-gan [eo-gan](https://github.com/leo-gan) Hi Leonid, can you please check now. I did a fresh commit pulling the latest code.

**Comment by leo-gan** [comment]
@rajib76 Hi , could you, please, resolve the merging issues? After that ping me and I push this PR for the review. Thanks!

**Comment by rajib76** [comment]
@leo-gan - Hi Leonid, I did not see any merge issue. Where did you check the merge issues

**Comment by leo-gan** [comment]
@rajib76 There are the lint and test errors. [For example](https://github.com/langchain-ai/langchain/actions/runs/6307455547/job/17124115106?pr=8804).

**Comment by efriis** [comment]
Looks like this isn't being worked on anymore. I'll close for now, and if you resume work and fix those lint errors, feel free to reopen!

**Pull request closed without merging**
