### PR TITLE
Add basic functionality to call the oobabooga/text-generator-webui API

### PR DESCRIPTION
**Pull request by atisharma**
Only synchronous calls are implemented.

### CODE REVIEW

**Comment by atisharma** [comment]
This solves issue #3499

**Review by hwchase17 — COMMENTED** [review]
would be very helpful to have an example notebook

**Comment by atisharma** [comment]
There are example in the server repository[server repository](https://github.com/oobabooga/text-generation-webui/blob/main/api-example.py)

**Comment by matatonic** [comment]
FYI, I updated #3499 with an update on the openai api for oobabooga/text-generator-webui.

**Comment by atisharma** [comment]
@hwchase17 bump for kind review

**Comment by atisharma** [comment]
Since matatonic's openai-compatible API has now been merged into oobabooga/text-generator-webui, there's not much point merging this. So, I'll close it.

**Pull request closed without merging**
