### PR TITLE
experimental: add max_chunk_size to SemanticChunker

### PR DESCRIPTION
**Pull request by RafaelXokito**
**Description:** 
This PR adds a `max_chunk_size` parameter to the `SemanticChunker` class. The `max_chunk_size` ensures that no chunk exceeds the specified size, splitting larger chunks accordingly. This feature enhances the chunking process by maintaining manageable chunk sizes.

**Issue:** 
Fixes #18014

### CODE REVIEW

**Comment by SatyamMattoo** [comment]
It will be really helpful if this feature gets added. For now, the Semantic Chunker returns very large chunks in some cases and the only way to limit that is creating a custom class I guess?

**Comment by gustavz** [comment]
Can we please get this in @hwchase17 ? thanks!

**Comment by repoofideas** [comment]
Waiting for this feature to be implemented.

**Comment by efriis** [comment]
closing and feel free to reopen against the langchain-experimental repo (this package moved)! https://github.com/langchain-ai/langchain-experimental

regarding max_chunk_size, wouldn't it be more effective to just pass the output of semanticchunker to one of the other text splitters that follows a strict chunk-size strategy? that way the user can decide which strategy to use to keep the chunks below a given size! this pr would be prescriptive if I understand correctly

**Pull request closed without merging**
