### PR TITLE
docstrings `document_loaders` 3

### PR DESCRIPTION
**Pull request by leo-gan**
- Updated docstrings for `document_loaders`
- Mass update `"""Loader that loads` to `"""Loads`

@baskaryan  - please, review

### CODE REVIEW

**Comment by rlancemartin** [comment]
Thanks for these updates; a few merge conflicts w/ `master` (perhaps after merging the other two docstring PRs). 

Do you mind merging / rebasing `master` and resolving?

**Comment by leo-gan** [comment]
@rlancemartin Done

**Comment by leo-gan** [comment]
@baskaryan Please review it. Thanks! Merging conflict is resolved.

**Comment by leo-gan** [comment]
@baskaryan Please review it. Thanks! Merging conflict is resolved.

**Review by rlancemartin — APPROVED** [review]

**Pull request merged**
