### PR TITLE
community[integrations]: add persistable implementation of bm25 retriever

### PR DESCRIPTION
**Pull request by mspronesti**
- **Description:** This PR adds an alternative (**additional**, i.e. not a replacement of the existing one) implementation of the BM25 based on [`bm25s`](https://github.com/xhluca/bm25s) retriever which addresses the following two problems:
   * `rank_bm25` - the package the currently implementation is based on - is undermantained, as noted in #18086
   * The current version of that retriever is not persistable, which makes it practically unusable as noted in #26112
- **Issue:**  #18086 #26112
- **Dependencies:** `bm25s`

### CODE REVIEW

**Comment by mspronesti** [comment]
@ccurme @efriis @baskaryan

**Comment by mspronesti** [comment]
@ccurme @baskaryan @efriis

**Comment by mspronesti** [comment]
Hi, can you have a look at this PR @efriis @ccurme @baskaryan?

**Comment by mspronesti** [comment]
@ccurme sorry for pinging you again. Just wondering if this PR was of interest, otherwise please feel free to close to :)

**Comment by efriis** [comment]
is this implementable as an improvement to the existing instead of a replacement?

**Comment by mspronesti** [comment]
@efriis yes. As I said, this version is faster (see  the paper for benchmarks),  maintained and persistable (most important feature to notice imho). 

The existing version based on `rank_bm25` was unusable for me: I had to recreate the index everytime I had to run an experiment.

**Comment by mspronesti** [comment]
@efriis I'm not sure. As mentioned above, the original is based on `rank_bm25` which is undermaintained. To supporto this feature one needs to first implement it in rank_bm25 or to have this functionality in the langchain integration.
On the other hand, `bm25s` natively supports persistance. It also comes with additional improvements in execution time (see benchmarks in their paper or project readme).

**Comment by mspronesti** [comment]
@efriis I just wanted to follow up on the above.

**Comment by efriis** [comment]
got it. Rationale for having a separate one makes sense to me. In general we're moving towards dedicated externally-maintained integration packages instead of community ones for things like this, so would recommend launching a `langchain-bm25s` type integration package. I'll close this PR, and would recommend reopening with just docs updates, as well as registering your package in `libs/packages.yml`! We'll be able to review simple PRs that only modify these two things much faster :)

Here's the guide, and if you have questions, feel free to leave them in the comments on those pages so others can see them! https://python.langchain.com/docs/contributing/how_to/integrations/

**Pull request closed without merging**
