### PR TITLE
Vearch vectorstore

### PR DESCRIPTION
**Pull request by zhanghexian**

### CODE REVIEW

**Comment by zhanghexian** [comment]
我已收到,谢谢!张和先.

**Comment by zhanghexian** [comment]
Add Vearch in langchain, which  is a scalable distributed system for efficient similarity search of deep learning vectors.
Added integration tests for the vector store.
Added jupyter notebook with the example.
Please check,Thanks!

**Comment by zhanghexian** [comment]
I don not know why "make lint" show this error:Import block is un-sorted or un-formatted.  I checked many methods  but i do not find where is wrong,please give me a hint,thanks!

**Comment by baskaryan** [comment]
thanks @zhanghexian!

**Pull request merged**
