### PR TITLE
Add pg_hnsw vectorstore integration

### PR DESCRIPTION
**Pull request by raoufchebri**
Hi @rlancemartin, @eyurtsev!

  - Description: Adding HNSW extension support for Postgres. Similar to pgvector vectorstore, with 3 differences 
      1. it uses HNSW extension for exact and ANN searches, 
      2. Vectors are of type array of real
      3. Only supports L2
      
  - Dependencies: [HNSW](https://github.com/knizhnik/hnsw) extension for Postgres
  
  - Example:
  ```python
    db = HNSWVectoreStore.from_documents(
      embedding=embeddings,
      documents=docs,
      collection_name=collection_name,
      connection_string=connection_string
  )
  
  query = "What did the president say about Ketanji Brown Jackson"
  docs_with_score: List[Tuple[Document, float]] = db.similarity_search_with_score(query) 
  ```

The example notebook is in the PR too.

### CODE REVIEW

**Review by rlancemartin — APPROVED** [review]
Nice work! 

Nit: clean up logging (e.g., on pip packages) in the notebook. Show `from_documents` and `similarity_search_with_score` as you have but remove logging of the various docs. You can see [Pinecone notebook](https://github.com/hwchase17/langchain/blob/master/docs/extras/modules/data_connection/vectorstores/integrations/pinecone.ipynb) as an example.

**Comment by raoufchebri** [comment]
Hi @rlancemartin. Thanks for your feedback! 
I removed the logging in the notebook and added a section on how to create HNSW index with `create_hnsw_index` function.

**Comment by raoufchebri** [comment]
Hey @rlancemartin, fixed some lint errors that didn't appear locally.

**Comment by raoufchebri** [comment]
Hi @rlancemartin, @eyurtsev 
I apologies in advance, we had to change the name of the extension from `hnsw` to `pg_embedding`.  It still uses `hnsw` index, so no changes there.

I reflected that in the code. I also changed the file name and updated the Jupyter Notebook.

**Comment by rlancemartin** [comment]
> Hi @rlancemartin, @eyurtsev 
> 
> I apologies in advance, we had to change the name of the extension from `hnsw` to `pg_embedding`.  It still uses `hnsw` index, so no changes there.
> 
> 
> 
> I reflected that in the code. I also changed the file name and updated the Jupyter Notebook.

Sounds good. Just kicked off tests. Is everything set to merge if tests pass?

**Comment by raoufchebri** [comment]
@rlancemartin reformatted with black again.

**Comment by rlancemartin** [comment]
Please see Lint errors: run "make format" and see unused import and line length errors.

**Comment by raoufchebri** [comment]
@rlancemartin ran `make format` and `poetry run black . --check`
```
All done! ✨ 🍰 ✨
1625 files would be left unchanged.
```

**Comment by raoufchebri** [comment]
🎉

**Pull request merged**
