### PR TITLE
Remove save function for ChatPromptTemplate

### LINKED ISSUE #13794: ChatPromptTemplate save method not implemented
### System Info

master branch

### Who can help?

@hwchase17

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

https://github.com/langchain-ai/langchain/blob/751226e067bc54a70910763c0eebb34544aaf47c/libs/core/langchain_core/prompts/chat.py#L653-L659

ChatPromptTemplate override save method as NotImplementedError, while the base class `BasePromptTemplate` has a default implementation of `save` method https://github.com/langchain-ai/langchain/blob/751226e067bc54a70910763c0eebb34544aaf47c/libs/core/langchain_core/prompts/base.py#L157-L192. It should just depend on the implementation of `_prompt_type` property, where ChatPromptTemplate already implemented here https://github.com/langchain-ai/langchain/blob/751226e067bc54a70910763c0eebb34544aaf47c/libs/core/langchain_core/prompts/chat.py#L648-L651.

If removing the override save function, ChatPromptTemplate could be saved correctly. 

### Expected behavior

We should be able to save ChatPromptTemplate object into a file.

### PR DESCRIPTION
**Pull request by serena-ruan**
Fixes https://github.com/langchain-ai/langchain/issues/13794

### CODE REVIEW

**Comment by hwchase17** [comment]
i dont think we handle all the serialization correctly, which is why this exists

**Comment by wangwei1237** [comment]
Although this can be solved, we found another issue. 

For the chat type of prompt, when **_message_list_** has only one _message_, `save()` and `load_prompt()` can run correctly. 

However, when **_message_list_** has more than one _message_, the role of the _message_ is not specified in the file saved by `save()`, and `load_prompt()` can only load the first _message_.

```python
from langchain.prompts import ChatPromptTemplate
prompt = ChatPromptTemplate.from_messages(
    [
        ("assistant", "hello"),
        ("human", "{query}"),
    ]
)
prompt.save("chat_template.json")
```

The result is as the following:

```
{
    "input_variables": [
        "query"
    ],
    "input_types": {},
    "output_parser": null,
    "partial_variables": {},
    "messages": [
        {
            "prompt": {
                "input_variables": [],
                "input_types": {},
                "output_parser": null,
                "partial_variables": {},
                "template": "hello",
                "template_format": "f-string",
                "validate_template": false,
                "_type": "prompt"
            },
            "additional_kwargs": {}
        },
        {
            "prompt": {
                "input_variables": [
                    "query"
                ],
                "input_types": {},
                "output_parser": null,
                "partial_variables": {},
                "template": "{query}",
                "template_format": "f-string",
                "validate_template": false,
                "_type": "prompt"
            },
            "additional_kwargs": {}
        }
    ],
    "validate_template": false,
    "_type": "chat"
}
```

Load the prompt from `chat_template.json`.

```
from langchain.chat_models import ErnieBotChat
from langchain.prompts import load_prompt

llm = ErnieBotChat()
prompt = load_prompt('chat_template.json')
print(prompt)
```

The result as the following:

```
input_variables=[] messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], template='hello'))]
```

**Comment by vigneshgarrapally** [comment]
So, how to save and load the ChatPromptTemplate into json or yaml.

**Comment by wangwei1237** [comment]
The best way is to use the  LangSmith as https://docs.smith.langchain.com/how_to_guides/prompts/pull_push_a_prompt.

```
from langchain import hub

# pull a private prompt
prompt = hub.pull("my-private-prompt")
print(prompt)

# pull a public prompt
public_prompt = hub.pull("efriis/my-first-prompt")
print(public_prompt)
```

**Pull request closed without merging**
