### PR TITLE
templates: Lanceb RAG  template

### PR DESCRIPTION
**Pull request by akashAD98**
Thank you for contributing to LangChain!

- [x] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [x] **PR message**: ***Delete this entire checklist*** and replace with
    - **Description:** a description of the change
    - **Issue:** the issue # it fixes, if applicable
    - **Dependencies:** any dependencies required for this change
    - **Twitter handle:** if your PR gets announced, and you'd like a mention, we'll gladly shout you out!

- [x] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, hwchase17.

### CODE REVIEW

**Comment by akashAD98** [comment]
@efriis  using new version of lancedb its solved & working fine.
fixed issue https://github.com/langchain-ai/langchain/pull/17181
image

**Comment by akashAD98** [comment]
@efriis @hwchase17 can you merge it?

**Comment by akashAD98** [comment]
@efriis @hwaking any chance to merge this?

**Comment by akashAD98** [comment]
@baskaryan @eyurtsev can you review my pr

**Comment by akashAD98** [comment]
i knoq you hav lots of pr pending but atleast you should check this.its benn pending from 2 weeks  ^ this is important pr for lancedb

**Review by efriis — APPROVED** [review]
works this time!

**Comment by akashAD98** [comment]
@efriis thank you.

**Pull request merged**
