### PR TITLE
add streaming tokens and model_name

### PR DESCRIPTION
**Pull request by lvisdd**
(#4583)
@hwchase17, @baskaryan

My test code is as follows.

```python
import asyncio
from langchain.callbacks import get_openai_callback
from langchain.chat_models import ChatOpenAI
from langchain.schema import (
    HumanMessage,
    SystemMessage
)

example_messages = [
    SystemMessage(content="You are a helpful, pattern-following assistant that translates corporate jargon into plain English."),
    #SystemMessage(name="example_user", content="New synergies will help drive top-line growth."),
    #SystemMessage(name="example_assistant", content="Things working well together will increase revenue."),
    #SystemMessage(name="example_user", content="Let's circle back when we have more bandwidth to touch base on opportunities for increased leverage."),
    #SystemMessage(name="example_assistant", content="Let's talk later when we're less busy about how to do better."),
    HumanMessage(content="This late pivot means we don't have time to boil the ocean for the client deliverable."),
]

async def main():
    
    for model in [
        "gpt-3.5-turbo-0301",
        #"gpt-3.5-turbo-0613",
        #"gpt-3.5-turbo",
        #"gpt-4-0314",
        #"gpt-4-0613",
        #"gpt-4",
        ]:
        print(model)

        with get_openai_callback() as cb:
            chat = ChatOpenAI(model_name=model, streaming=False, temperature=0, max_tokens=100)

            resp = chat.generate([example_messages])
            print()
            print(resp)

            print("prompt_tokens : " + str(cb.prompt_tokens))
            print("completion_tokens : " + str(cb.completion_tokens))
            print("total_tokens : " + str(cb.total_tokens))
            print("total_cost : " + str(cb.total_cost))

        with get_openai_callback() as cb:
            chat = ChatOpenAI(model_name=model, streaming=False, temperature=0, max_tokens=100)

            resp = await chat.agenerate([example_messages])
            print()
            print(resp)

            print("prompt_tokens : " + str(cb.prompt_tokens))
            print("completion_tokens : " + str(cb.completion_tokens))
            print("total_tokens : " + str(cb.total_tokens))
            print("total_cost : " + str(cb.total_cost))

        with get_openai_callback() as cb:
            chat = ChatOpenAI(model_name=model, streaming=True, temperature=0, max_tokens=100)

            resp = chat.generate([example_messages])
            print()
            print(resp)

            print("prompt_tokens : " + str(cb.prompt_tokens))
            print("completion_tokens : " + str(cb.completion_tokens))
            print("total_tokens : " + str(cb.total_tokens))
            print("total_cost : " + str(cb.total_cost))

        with get_openai_callback() as cb:
            chat = ChatOpenAI(model_name=model, streaming=True, temperature=0, max_tokens=100)

            resp = await chat.agenerate([example_messages])
            print()
            print(resp)

            print("prompt_tokens : " + str(cb.prompt_tokens))
            print("completion_tokens : " + str(cb.completion_tokens))
            print("total_tokens : " + str(cb.total_tokens))
            print("total_cost : " + str(cb.total_cost))

        print()

if __name__ == '__main__':
    asyncio.run(main())
```

### CODE REVIEW

**Comment by lvisdd** [comment]
If these changes look risky, I have prepared a CustomCallback sample as another solution.

```
import asyncio
from langchain.callbacks.base import BaseCallbackHandler
from langchain.callbacks.openai_info import *
from langchain.chat_models import ChatOpenAI
from langchain.schema.output import ChatGenerationChunk, GenerationChunk
from langchain.schema import (
    BaseMessage,
    HumanMessage,
    SystemMessage
)
from typing import Any, Optional, Union
from uuid import UUID

class CustomCallbackHandler(BaseCallbackHandler):
    completion_tokens: int = 0

    def on_llm_new_token(
        self,
        token: str,
        *,
        chunk: Optional[Union[GenerationChunk, ChatGenerationChunk]] = None,
        run_id: UUID,
        parent_run_id: Optional[UUID] = None,
        **kwargs: Any,
    ) -> Any:
        #print(f"'{token}'")
        print(f"\033[36m'{token}'\033[0m")
        if token is not None and token != "":
            self.completion_tokens += 1
        
        return super().on_llm_new_token(
            token, chunk=chunk, run_id=run_id, parent_run_id=parent_run_id, **kwargs
        )

def get_openai_token_cost(chat: ChatOpenAI, model_name: str, messages: List[BaseMessage]):
    prompt_tokens = chat.get_num_tokens_from_messages(messages=example_messages)
    completion_tokens = chat.callbacks[0].completion_tokens
    total_tokens = prompt_tokens + completion_tokens

    total_cost: float = 0.0
    if model_name in MODEL_COST_PER_1K_TOKENS:
        completion_cost = get_openai_token_cost_for_model(
            model_name, completion_tokens, is_completion=True
        )
        prompt_cost = get_openai_token_cost_for_model(model_name, prompt_tokens)
        total_cost = prompt_cost + completion_cost

    return (
        f"Tokens Used: {total_tokens}\n"
        f"\tPrompt Tokens: {prompt_tokens}\n"
        f"\tCompletion Tokens: {completion_tokens}\n"
        f"Total Cost (USD): ${total_cost}\n"
    )

example_messages = [
    SystemMessage(content="You are a helpful, pattern-following assistant that translates corporate jargon into plain English."),
    #SystemMessage(name="example_user", content="New synergies will help drive top-line growth."),
    #SystemMessage(name="example_assistant", content="Things working well together will increase revenue."),
    #SystemMessage(name="example_user", content="Let's circle back when we have more bandwidth to touch base on opportunities for increased leverage."),
    #SystemMessage(name="example_assistant", content="Let's talk later when we're less busy about how to do better."),
    HumanMessage(content="This late pivot means we don't have time to boil the ocean for the client deliverable."),
]

async def main():
    
    for model_name in [
        "gpt-3.5-turbo-0301",
        #"gpt-3.5-turbo-0613",
        #"gpt-3.5-turbo",
        #"gpt-4-0314",
        #"gpt-4-0613",
        #"gpt-4",
        ]:
        print(model_name)

        chat = ChatOpenAI(model_name=model_name, streaming=True, callbacks=[CustomCallbackHandler()], temperature=0, max_tokens=100)

        resp = chat.generate([example_messages])
        print(resp)
        print(get_openai_token_cost(chat, model_name, example_messages))

        chat = ChatOpenAI(model_name=model_name, streaming=True, callbacks=[CustomCallbackHandler()], temperature=0, max_tokens=100)

        resp = await chat.agenerate([example_messages])
        print(resp)
        print(get_openai_token_cost(chat, model_name, example_messages))

if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by nfcampos** [comment]
Id be wary of calling the tokeniser for every token, would slow down everyone else's apps

**Comment by lvisdd** [comment]
> Id be wary of calling the tokeniser for every token, would slow down everyone else's apps

Thanks for your comment.

The function `get_num_tokens_from_messages` is called only once, outside of the chunk loop. It's not being called for each token, so I believe the latency should be minimal. What do you think?

**Comment by lvisdd** [comment]
I think the latency depends on the OpenAI API when streaming=true.

- Before

```
gpt-3.5-turbo-0301
i : 0
generate timediff : 0.9258830547332764
agenerate timediff : 0.9537229537963867
i : 1
generate timediff : 0.915074348449707
agenerate timediff : 0.9698758125305176
i : 2
generate timediff : 0.9312689304351807
agenerate timediff : 1.018787145614624
i : 3
generate timediff : 0.9073448181152344
agenerate timediff : 0.9569604396820068
i : 4
generate timediff : 1.0726542472839355
agenerate timediff : 0.8910963535308838

avg generate timediff : 0.9504450798034668
avg agenerate timediff : 0.9580885410308838
```

- after

```
gpt-3.5-turbo-0301
i : 0
generate timediff : 1.104553461074829
agenerate timediff : 0.8502066135406494
i : 1
generate timediff : 0.7971365451812744
agenerate timediff : 0.753244161605835
i : 2
generate timediff : 0.759894609451294
agenerate timediff : 0.6960177421569824
i : 3
generate timediff : 0.8439314365386963
agenerate timediff : 0.6662440299987793
i : 4
generate timediff : 0.6385622024536133
agenerate timediff : 0.8396048545837402

avg generate timediff : 0.8288156509399414
avg agenerate timediff : 0.7610634803771973
```

- test code

```
import asyncio
import statistics
import time
from langchain.callbacks import get_openai_callback
from langchain.chat_models import ChatOpenAI
from langchain.schema import (
    HumanMessage,
    SystemMessage
)

example_messages = [
    SystemMessage(content="You are a helpful, pattern-following assistant that translates corporate jargon into plain English."),
    SystemMessage(name="example_user", content="New synergies will help drive top-line growth."),
    SystemMessage(name="example_assistant", content="Things working well together will increase revenue."),
    SystemMessage(name="example_user", content="Let's circle back when we have more bandwidth to touch base on opportunities for increased leverage."),
    SystemMessage(name="example_assistant", content="Let's talk later when we're less busy about how to do better."),
    HumanMessage(content="This late pivot means we don't have time to boil the ocean for the client deliverable."),
]

async def main():
    
    for model in [
        "gpt-3.5-turbo-0301",
        #"gpt-3.5-turbo-0613",
        #"gpt-3.5-turbo",
        #"gpt-4-0314",
        #"gpt-4-0613",
        #"gpt-4",
        ]:
        print(model)

        t1 = []
        t2 = []
        for i in range(5):
            print(f"i : {i}")
            with get_openai_callback() as cb:
                chat = ChatOpenAI(model_name=model, streaming=True, temperature=0, max_tokens=100)

                start = time.time()
                resp = chat.generate([example_messages])
                end = time.time()
                timediff = end - start
                t1.append(timediff)
                print("generate timediff : " + str(timediff))

            with get_openai_callback() as cb:
                chat = ChatOpenAI(model_name=model, streaming=True, temperature=0, max_tokens=100)

                start = time.time()
                resp = await chat.agenerate([example_messages])
                end = time.time()
                timediff = end - start
                t2.append(timediff)
                print("agenerate timediff : " + str(timediff))
        
        print()
        print("avg generate timediff : " + str(statistics.mean(t1)))
        print("avg agenerate timediff : " + str(statistics.mean(t2)))

if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by usersina** [comment]
What's the progress on this?

**Comment by baskaryan** [comment]
Apologies for the slow review! Pr has some merge conflicts, happy to re-review if you'd like to resolve

**Comment by lvisdd** [comment]
@baskaryan 
Sorry for the late reply. Since OpenAI now supports stream_options, I believe it would be best to review the source code.
- https://community.openai.com/t/usage-stats-now-available-when-using-streaming-with-the-chat-completions-api-or-completions-api/738156
- https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream_options

However, because Azure OpenAI Service does not yet support stream_options, I have not been able to consider it.
- https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions

I would like to close this merge request.

**Comment by monuminu** [comment]
I see llm_output.usage as blank even if I use Langchain with OpenAI . Any plan on adding the same to Langchain ?

**Comment by lvisdd** [comment]
Sorry for the delayed reply. I mentioned below.
- https://github.com/langchain-ai/langchain/issues/4583#issuecomment-2485189046

**Pull request closed without merging**
