### PR TITLE
Add ChatModels wrapper for Cloudflare Workers AI

### PR DESCRIPTION
**Pull request by AkshataDM**
Thank you for contributing to LangChain!

- [x] **PR title**: "community: chat models wrapper for Cloudflare Workers AI"

- [x] **PR message**:
    - **Description:** Add chat models wrapper for Cloudflare Workers AI. Enables Langgraph intergration via ChatModel for tool usage, agentic usage.  

- [x] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [x] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Comment by AkshataDM** [comment]
@baskaryan could i get a review on this when you get a chance? thanks!

**Comment by AkshataDM** [comment]
hello, @eyurtsev could i get some reviews on this? thanks!

**Comment by Talador12** [comment]
Awesome work on this one, thank you for contributing this!

**Comment by AkshataDM** [comment]
@vbarda could I get a review on this when you get a chance please? 

PR has passed all lint and formatting tests. It has also community support of 5 upvotes on the PR.

**Review by efriis — APPROVED** [review]

**Comment by AkshataDM** [comment]
@efriis thanks for looking into this PR! Looks like a few linting checks failed on the documentation notebook. I will be looking into this but in the meantime if you have any other suggestions please let me know

**Review by ccurme — APPROVED** [review]

**Pull request merged**
