### PR TITLE
Office365 Tool

### PR DESCRIPTION
**Pull request by sdelgadoc**
#### Background
With the development of [structured tools](https://blog.langchain.dev/structured-tools/), the LangChain team expanded the platform's functionality to meet the needs of new applications. The GMail tool, empowered by structured tools, now supports multiple arguments and powerful search capabilities, demonstrating LangChain's ability to interact with dynamic data sources like email servers.

#### Challenge
The current GMail tool only supports GMail, while users often utilize other email services like Outlook in Office365. Additionally, the proposed calendar tool in PR https://github.com/hwchase17/langchain/pull/652 only works with Google Calendar, not Outlook.

#### Changes
This PR implements an Office365 integration for LangChain, enabling seamless email and calendar functionality with a single authentication process.

#### Future Work
With the core Office365 integration complete, future work could include integrating other Office365 tools such as Tasks and Address Book.

#### Who can review?
@hwchase17 or @vowelparrot can review this PR

#### Appendix
@janscas, I utilized your [O365](https://github.com/O365/python-o365) library extensively. Given the rising popularity of LangChain and similar AI frameworks, the convergence of libraries like O365 and tools like this one is likely. So, I wanted to keep you updated on our progress.

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
this is pretty awesome! some minor lint issues but otherwise looks great

**Comment by sdelgadoc** [comment]
Made lint-recommended changes. If this is good to merge, and you guys are OK with posting on Twitter, my Twitter account is @santiagodc. Thanks!

**Comment by sdelgadoc** [comment]
Thanks @dev2049 for the formatting updates. They looks good!

**Comment by sdelgadoc** [comment]
@hwchase17 let me know if I need to work on anything else to merge. @dev2049 was very helpful with formatting edits, and it looks like Vercel didn't find any issues.

**Pull request merged**
