### PR TITLE
community: Add tools calls to `ChatEdenAI`

### PR DESCRIPTION
**Pull request by KyrianC**
### Description  
Add tools implementation to `ChatEdenAI`:
- `bind_tools()`
- `with_structured_output()`

### Documentation 
Updated `docs/docs/integrations/chat/edenai.ipynb`

### Notes
We don´t support stream with tools as of yet. If stream is called with tools we directly yield the whole message from `generate` (implemented the same way as Anthropic did).

### CODE REVIEW

**Comment by startime-h** [comment]
Preparing review...

**Comment by startime-h** [comment]
Preparing review...

**Comment by baskaryan** [comment]
nice! if you add ChatEdenAI to the CHAT_MODEL_TABLE here https://github.com/langchain-ai/langchain/blob/master/docs/scripts/model_feat_table.py it'll get noted in this page https://python.langchain.com/v0.2/docs/integrations/chat/

**Comment by KyrianC** [comment]
> nice! if you add ChatEdenAI to the CHAT_MODEL_TABLE here https://github.com/langchain-ai/langchain/blob/master/docs/scripts/model_feat_table.py it'll get noted in this page https://python.langchain.com/v0.2/docs/integrations/chat/

done!

**Pull request merged**
