### PR TITLE
Bedrock llm and embeddings

### PR DESCRIPTION
**Pull request by 3coins**
# Bedrock LLM and Embeddings
This PR adds a new LLM and an Embeddings class for the [Bedrock](https://aws.amazon.com/bedrock) service. The PR also includes example notebooks for using the LLM class in a conversation chain and embeddings usage in creating an embedding for a query and document.

**Note**:  AWS is doing a private release of the Bedrock service on 05/31/2023; users need to request access and added to an allowlist in order to start using the Bedrock models and embeddings. Please use the [Bedrock Home Page](https://aws.amazon.com/bedrock) to request access and to learn more about the models available in Bedrock.

### CODE REVIEW

**Review by hwchase17 — COMMENTED** [review]
looks pretty clean and straightforward to me! still marked as draft, so assuming its awaiting something more?

**Comment by jasondotparse** [comment]
> looks pretty clean and straightforward to me! still marked as draft, so assuming its awaiting something more?

Still adding a few more notes, and ensuring all parties have had a chance to add theirs as well :)

**Comment by 3coins** [comment]
@hwchase17 
Thanks for responding so quickly to the PR. I will move it out of draft shortly, once some internal folks have reviewed.

**Comment by ellisonbg** [comment]
Looks good to me! As folks try this out, please let us (myself, @3coins, @jasondotparse) know if you run into issues by opening issues on this repo and @ mentioning us.

**Review by hwchase17 — APPROVED** [review]
lgtm! thanks!

**Pull request merged**
