### PR TITLE
Add templates

### PR DESCRIPTION
**Pull request by eyurtsev**
Add documentation templates

### CODE REVIEW

**Comment by eyurtsev** [comment]
@baskaryan  do you know how to turn this option: 

image

----

I think except for showing the init parameters, most things should be cleaned up

TypedDicts:

https://api.python.langchain.com/en/eugene-update_reference_rst/evaluation/langchain.evaluation.agents.trajectory_eval_chain.TrajectoryEval.html?highlight=trajectory#langchain.evaluation.agents.trajectory_eval_chain.TrajectoryEval
image

Enums:

https://api.python.langchain.com/en/eugene-update_reference_rst/agents/langchain.agents.agent_types.AgentType.html#langchain.agents.agent_types.AgentType
image

**Review by baskaryan — APPROVED** [review]
looks great
https://api.python.langchain.com/en/eugene-update_reference_rst/api_reference.html

**Comment by 3coins** [comment]
@eyurtsev 
Thanks for fixing this. The classes are captured correctly now. I see some errors while running the `api_docs_build`. Are these expected?
```
Error: Unable to import module 'vectorstores._pgvector_data_models' with error: No module named 'pgvector'
Error: Unable to import module 'autonomous_agents.hugginggpt.task_planner' with error: No module named 'langchain_experimental'
Error: Unable to import module 'autonomous_agents.hugginggpt.hugginggpt' with error: No module named 'langchain_experimental'
Error: Unable to import module 'autonomous_agents.hugginggpt.task_executor' with error: No module named 'langchain_experimental'
Error: Unable to import module 'autonomous_agents.hugginggpt.repsonse_generator' with error: No module named 'langchain_experimental'
Error: Unable to import module 'autonomous_agents.baby_agi.task_prioritization' with error: No module named 'langchain_experimental'
Error: Unable to import module 'autonomous_agents.baby_agi.task_creation' with error: No module named 'langchain_experimental'
Error: Unable to import module 'autonomous_agents.baby_agi.baby_agi' with error: No module named 'langchain_experimental'
Error: Unable to import module 'autonomous_agents.baby_agi.task_execution' with error: No module named 'langchain_experimental'
Error: Unable to import module 'autonomous_agents.autogpt.memory' with error: No module named 'langchain_experimental'
Error: Unable to import module 'autonomous_agents.autogpt.prompt_generator' with error: No module named 'langchain_experimental'
Error: Unable to import module 'autonomous_agents.autogpt.output_parser' with error: No module named 'langchain_experimental'
Error: Unable to import module 'autonomous_agents.autogpt.agent' with error: No module named 'langchain_experimental'
Error: Unable to import module 'autonomous_agents.autogpt.prompt' with error: No module named 'langchain_experimental'
Error: Unable to import module 'tot.controller' with error: No module named 'langchain_experimental'
Error: Unable to import module 'tot.memory' with error: No module named 'langchain_experimental'
Error: Unable to import module 'tot.prompts' with error: No module named 'langchain_experimental'
Error: Unable to import module 'tot.thought' with error: No module named 'langchain_experimental'
Error: Unable to import module 'tot.thought_generation' with error: No module named 'langchain_experimental'
Error: Unable to import module 'tot.base' with error: No module named 'langchain_experimental'
Error: Unable to import module 'tot.checker' with error: No module named 'langchain_experimental'
Error: Unable to import module 'plan_and_execute.agent_executor' with error: No module named 'langchain_experimental'
Error: Unable to import module 'plan_and_execute.schema' with error: No module named 'langchain_experimental'
Error: Unable to import module 'plan_and_execute.executors.agent_executor' with error: No module named 'langchain_experimental'
Error: Unable to import module 'plan_and_execute.executors.base' with error: No module named 'langchain_experimental'
Error: Unable to import module 'plan_and_execute.planners.chat_planner' with error: No module named 'langchain_experimental'
Error: Unable to import module 'plan_and_execute.planners.base' with error: No module named 'langchain_experimental'
Error: Unable to import module 'cpal.models' with error: No module named 'langchain_experimental'
Error: Unable to import module 'cpal.constants' with error: No module named 'langchain_experimental'
Error: Unable to import module 'cpal.base' with error: No module named 'langchain_experimental'
Error: Unable to import module 'cpal.templates.univariate.query' with error: No module named 'langchain_experimental'
Error: Unable to import module 'cpal.templates.univariate.narrative' with error: No module named 'langchain_experimental'
Error: Unable to import module 'cpal.templates.univariate.intervention' with error: No module named 'langchain_experimental'
Error: Unable to import module 'cpal.templates.univariate.causal' with error: No module named 'langchain_experimental'
Error: Unable to import module 'prompts.load' with error: No module named 'langchain_experimental'
Error: Unable to import module 'llms.llamaapi' with error: No module named 'langchain_experimental'
Error: Unable to import module 'llms.anthropic_functions' with error: No module named 'langchain_experimental'
Error: Unable to import module 'llms.rellm_decoder' with error: No module named 'langchain_experimental'
Error: Unable to import module 'llms.jsonformer_decoder' with error: No module named 'langchain_experimental'
Error: Unable to import module 'generative_agents.memory' with error: No module named 'langchain_experimental'
Error: Unable to import module 'generative_agents.generative_agent' with error: No module named 'langchain_experimental'
Error: Unable to import module 'pal_chain.math_prompt' with error: No module named 'langchain_experimental'
Error: Unable to import module 'pal_chain.colored_object_prompt' with error: No module named 'langchain_experimental'
Error: Unable to import module 'pal_chain.base' with error: No module named 'langchain_experimental'
Error: Unable to import module 'sql.base' with error: No module named 'langchain_experimental'
```

**Comment by eyurtsev** [comment]
If you install `langchain_experimental` it should be able to import those modules

**Pull request merged**
