### PR TITLE
Added example usage for Python REPL tool

### PR DESCRIPTION
**Pull request by Robert-Jia00129**
Thank you for contributing to LangChain!

- [ ] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [ ] **PR message**: ***Delete this entire checklist*** and replace with
    - **Description:** a description of the change
    - **Issue:** the issue # it fixes, if applicable
    - **Dependencies:** any dependencies required for this change
    - **Twitter handle:** if your PR gets announced, and you'd like a mention, we'll gladly shout you out!

- [ ] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [ ] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

### CODE REVIEW

**Review by eyurtsev — APPROVED** [review]
Hi @Robert-Jia00129 thanks for the contribution! I accepted this PR -- you can use `make format` to get the content linted to pass the PR. 

However, I am not sure what the ideal format for the tool integrations is -- I think it is reasonable for the tool documentation to just show case the tool without showing it in the context of the agent, since the documentation is about the tool and how to use it, rather than how to use it within an agent.

**Comment by Robert-Jia00129** [comment]
Make sense. Thanks. I'll change it.

**Comment by baskaryan** [comment]
agree with eugene re focusing on the tool itself. We've also come up with a standard tool integration format, could we follow that here? here's a good example of it: https://python.langchain.com/v0.2/docs/integrations/tools/tavily_search/

**Comment by eyurtsev** [comment]
Going to close this PR for now -- @Robert-Jia00129 if you'd like to update to follow the tool format that bagatur suggested please let us know (and feel free to open a new PR request)

**Pull request closed without merging**
