### PR TITLE
adding max_marginal_relevance_search method to MongoDBAtlasVectorSearch

### PR DESCRIPTION
**Pull request by P-E-B**
Adding a maximal_marginal_relevance method to the MongoDBAtlasVectorSearch vectorstore enhances the user experience by providing more diverse search results

Issue: #7304

@rlancemartin, @eyurtsev --> Please make sure that I'm using correctly the maximal_marginal_relevance (from utils).

### CODE REVIEW

**Comment by P-E-B** [comment]
@rlancemartin I fixed the linting. LGTM

**Review by rlancemartin — COMMENTED** [review]
thanks! looks like there may be a formatting error w/ the notebook? i see invalid JSON when trying to view it.

**Comment by P-E-B** [comment]
> thanks! looks like there may be a formatting error w/ the notebook? i see invalid JSON when trying to view it.

@rlancemartin interesting, I am not seeing any error, it prints well on my screen. What error is mentionned? Invalid JSON?

**Comment by baskaryan** [comment]
thanks @P-E-B!

**Pull request merged**
