### PR TITLE
Allow FAISS score_threshold

### PR DESCRIPTION
**Pull request by simonfromla**
Allow FAISS's similarity_search_with_score_by_vector to accept kwargs, specifically: `score_threshold`.
Fixes error for document compression users in cases where there are no relevant docs - for instance:  

```
human_message: "hi" (<--  will return no relevant docs depending on score_threshold)
> IndexError: index 0 is out of bounds for axis 0 with size 0
```

Combined with the new merger_retriever, FAISS users can now perform more granular vectorstore retrieving based on score_threshold:  

```
store_1 = st[0][1].as_retriever(search_type="similarity_score_threshold", search_kwargs={"score_threshold": .8, "k": 3})
store_2 = st[1][1].as_retriever(search_type="similarity_score_threshold", search_kwargs={"score_threshold": .3, "k": 3})
store_3 = st[2][1].as_retriever(search_type="similarity_score_threshold", search_kwargs={"score_threshold": .5, "k": 3})

merged = MergerRetriever(retrievers=[store_1, store_2, store_3])
pipeline_compressor = prep_compressor()
compression_retriever = ContextualCompressionRetriever(base_compressor=pipeline_compressor, base_retriever=merged)

chain = ConversationalRetrievalChain.from_llm(OpenAI(temperature=0), chain_type="stuff", retriever=compression_retriever)
```

@dev2049 or @hwchase17 would appreciate a check if available. Thanks.

### CODE REVIEW

**Comment by simonfromla** [comment]
Related to issue: #6167

**Review by hwchase17 — APPROVED** [review]

**Comment by paplorinc** [comment]
I'm still getting the error with version 202

**Comment by simonfromla** [comment]
> I'm still getting the error with version 202

Looks like it was added in .203. Try with latest.

**Comment by paplorinc** [comment]
It's working with the latest (yesterday I couldn't access anything newer than 202), thanks

**Pull request merged**
