### PR TITLE
Refactor: Improve logic for parsing google-Style docstrings

### LINKED ISSUE #28628: core: make docstring parsing more robust
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Valid Google-style docstrings with descriptions > 1 paragraph are not supported.

Example failure:

```python
from langchain_core.tools import tool


@tool(parse_docstring=True)
def search(query: str) -> None:
  """Searches for information based on the query.

  Use this tool to look up factual information or search for relevant content.

  Args:
    query: The search query. A good query is a clear and concise question or statement.

  Returns:
    A list of documents that match the query.
  """
  pass
```

Root cause is raising an error when second `\n\n`-delimited block does not start with `Args`: https://github.com/langchain-ai/langchain/blob/ec9b41431ea8bccccc3b9f1679c1e1e16c26e23e/libs/core/langchain_core/utils/function_calling.py#L618

### PR DESCRIPTION
**Pull request by isatyamks**
Thank you for contributing to LangChain!

- [x] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, etc. is being modified. Use "docs: ..." for purely docs changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

Description:  
Improved the `_parse_google_docstring` function in `langchain/core` to support parsing multi-paragraph descriptions before the `Args:` section while maintaining compliance with Google-style docstring guidelines. This change ensures better handling of docstrings with detailed function descriptions.

Issue:  
Fixes #28628

Dependencies:  
None.

Twitter handle:  
@isatyamks

### CODE REVIEW

**Review by efriis — COMMENTED** [review]
could you add some unit tests on cases that currently fail?

**Comment by isatyamks** [comment]
> could you add some unit tests on cases that currently fail?

Hi @ccurme,Thank you for the feedback! I’m not very familiar with writing unit tests for this type of case. Could you please guide me.

**Comment by efriis** [comment]
you can add some tests to `libs/core/tests/unit_tests/utils/test_function_calling.py` that call `_parse_google_docstring` that fail in the current version of langchain but this PR fixes. i'm curious what this actually fixes because there are a bunch of docstrings that are parsed correctly that have multiple paragraphs e.g. https://python.langchain.com/api_reference/openai/chat_models/langchain_openai.chat_models.azure.AzureChatOpenAI.html

and I'm curious what this aims to fix. If you can do it before the holidays let me know! Otherwise we can close this one and reopen with tests whenever you have time to do so!

**Comment by isatyamks** [comment]
@efriis I’ve added tests to validate the updated _parse_google_docstring function, but some checks are failing. Could you help identify what’s going wrong?

**Comment by efriis** [comment]
fixed the lint errors but the tests you added are failing. You can run them locally with
```
cd libs/core
poetry install --with lint,typing,test --sync
make test
```
and for future reference you can run format/lint (what i fixed) with:
```
cd libs/core
poetry install --with lint,typing,test --sync
make format lint
```

**Comment by isatyamks** [comment]
@efriis, I believe all tests have now passed. Huge thanks to you and @ccurme for your  help!

**Review by ccurme — APPROVED** [review]

**Pull request merged**
