### PR TITLE
community: (neo4j) support semantic filtering with vector indexes

### PR DESCRIPTION
**Pull request by mtrinell**
Extends/Improves `GraphCypherQAChain` to perform queries based on semantics via vector indexes (listed from auto-generated schema), instead of generating queries with strict/exact matching filters which fail on some use cases.
 
This means having the following user's query:
```python
chain.invoke("What are the issues that relate to the issue about the 'vote' web app?")
```
resulting to:
```python
> Entering new GraphCypherQAChain chain...
Generated Cypher:

CALL db.index.vector.queryNodes('issue_description_idx', 5, $search_emb) YIELD node, score
MATCH (node:Issue)-[:DEPENDS_ON]->(related:Issue)
RETURN related.description AS text, score

Generated Filter:
'vote web app'

Full Context:
...
```

Embeddings are then computed for generated filter and passed as `search_emb` parameter in `queryNodes`.

Without this improvement, the same input resulted to the query below, which fails to respond to user's input.

```python
> Entering new GraphCypherQAChain chain...
Generated Cypher:
cypher
MATCH (i:Issue)-[:DEPENDS_ON]->(related:Issue)
WHERE i.description CONTAINS 'vote web app'
RETURN related

Full Context:
[]
```

Change is backward compatible (selection of prompt and further logic is based on passing an `embeddings` model (optional)

```python
chain = GraphCypherQAChain.from_llm(
    llm, graph=graph, verbose=True, allow_dangerous_requests=True, embeddings=embeddings
)
```

### CODE REVIEW

**Comment by efriis** [comment]
Putting in needs support but for neo4j contributions you might want to put them against the integration package. You can find the integration package here: https://github.com/langchain-ai/langchain-neo4j

Once that's released the community integration will be deprecated

**Comment by mtrinell** [comment]
> Putting in needs support but for neo4j contributions you might want to put them against the integration package. You can find the integration package here: https://github.com/langchain-ai/langchain-neo4j
> 
> Once that's released the community integration will be deprecated

Hi Erick, thanks for your comment.

I've moved this to langchain-neo4j and opened a PR: https://github.com/langchain-ai/langchain-neo4j/pull/2

Note that in langchain-neo4j there are still references to langchain_community prompts: https://github.com/langchain-ai/langchain-neo4j/blob/main/libs/neo4j/langchain_neo4j/chains/graph_qa/cypher.py#L10

As part of this change I've created a new prompt `CYPHER_FILTER_GENERATION_PROMPT` which is part of this PR. Then I guess some more refactoring is needed to bring only neo4j prompts in `langchain_neo4j`.

Also, let me know if you prefer that I revert these changes in this PR for `cypher.py` and `neo4j_graph.py` (moved to langchain-neo4j)

**Comment by efriis** [comment]
let's actually get those added to the langchain-neo4j package too! long-term requiring adding those prompts to the community package (and getting them released) shouldn't block the neo4j package

I think long-term a lot of the community versions of those will be copied over to langchain-neo4j, and deprecated from community (assuming only neo4j relies on them)

**Comment by alexthomas93** [comment]
> let's actually get those added to the langchain-neo4j package too! long-term requiring adding those prompts to the community package (and getting them released) shouldn't block the neo4j package
> 
> I think long-term a lot of the community versions of those will be copied over to langchain-neo4j, and deprecated from community (assuming only neo4j relies on them)

Hi @efriis @mtrinell both `CYPHER_GENERATION_PROMPT` and `CYPHER_QA_PROMPT` are currently used in the other graph db integrations (Kùzu, FalkorDB, etc.) so I haven't moved them to `langchain-neo4j` yet and have just left them in community for now.

**Comment by mtrinell** [comment]
@efriis so I think with these 2 PRs (this one and https://github.com/langchain-ai/langchain-neo4j/pull/2) we are good?
Let me know if some other change is needed, otherwise I'll just wait for review. Thanks!

**Comment by efriis** [comment]
oop sorry for the delay on this one. from my understanding these functions have all been `@deprecated` in a separate PR, so this one isn't needed anymore. If that's not true ping me and I'll reopen!

**Pull request closed without merging**
