### PR TITLE
Update the parameters of the<openai. embedding. create>interface

### PR DESCRIPTION
**Pull request by WuKe-CN**
# Update the parameters of the<openai. embedding. create>interface,restored interface validity

I changed all the engine parameters in the program to modles, and marked out other unnecessary parameters. It should be noted that I did not add user to the parameter list because I was afraid of unexpected errors, as this parameter is not a required item. I used "/embedding/test_ openai.py" and it has been tested. the test results are normal

It should be noted that I use "make integration_tests" When testing, the program did not test"/embedding/test_ Openai.py", which resulted in the error report not mentioning this error. I think this may also be a bug. To verify the effectiveness of the modification, I debugged this separate test file and found that the existing version reported an error. After the modification, the test passed

I did not add a new integration, I only restored the effectiveness of the interface mentioned above. I tested the test units involved in the modified files separately and found that the modified files can pass the test normally!

-@hwchase17

-@agola11

### CODE REVIEW

**Comment by WuKe-CN** [comment]
The comments related to the AZURE section in the file I modified should also need to be modified, but this needs to be confirmed. The parameter user should also be submitted to openai together. However, in order to make this interface available in the released version faster, I hope to incrementally update this file.

**Comment by WuKe-CN** [comment]
My handling:
response = embed_with_retry(
                self,
                input=tokens[i : i + _chunk_size],
                model=self.model,
                # engine=self.deployment,
                # request_timeout=self.request_timeout,
                # headers=self.headers,
            )
openai Interface Introduction:
curl https://api.openai.com/v1/embeddings \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "input": "The food was delicious and the waiter...",
    "model": "text-embedding-ada-002"
  }'
Latest version of langchain:
response = embed_with_retry(
                self,
                input=tokens[i : i + _chunk_size],
                engine=self.deployment,
                request_timeout=self.request_timeout,
                headers=self.headers,
            )

**Comment by WuKe-CN** [comment]
I think Azure type requests and regular requests should be separated, but the code I applied for submission considers regular requests. However, Azure's request parameters seem to have changed, not the previous engine parameters. It should be possible to control which parameters are passed in through type, but I do not have the conditions to handle Azure embedding situations. In the future, PR can be merged to meet these two situations

**Comment by hwchase17** [comment]
why are the other parameters not neccesary?

**Comment by WuKe-CN** [comment]
sorry about that,I checked the code for OpenAI and my previous understanding was incorrect.

I have updated the code and only added a passing parameter 'model', which is necessary for non AZURE type calls. Otherwise, the requested 'url' path is' v1/engine/... ', and this path request has been deprecated, causing the program to report an error.

I guess the parameter 'deployment_id' needs to be added to adapt to the AZURE type embedding request, but I am unable to test this type, so this part is not included in my code.

**Pull request closed without merging**
