### PR TITLE
Cassandra support for LLM cache (exact-match and semantic)

### PR DESCRIPTION
**Pull request by hemidactylus**
This PR implements two new classes in the cache module: `CassandraCache` and `CassandraSemanticCache`, similar in structure and functionality to their Redis counterpart: providing a cache for the response to a (prompt, llm) pair.

Integration tests are included. Moreover, linting and type checks are all passing on my machine.

Dependencies: the `pyproject.toml` and `poetry.lock` have the newest version of cassIO (the very same as in the Cassandra vector store metadata PR, submitted as #9280).

If I may suggest, this issue and #9280 might be reviewed together (as they bring the same poetry changes along), so I'm tagging @baskaryan who already helped out a little with poetry-related conflicts there. (Thank you!)

I'd be happy to add a short notebook if this is deemed necessary (but it seems to me that, contrary e.g. to vector stores, caches are not covered in specific notebooks).

Thank you!

### CODE REVIEW

**Comment by hemidactylus** [comment]
Hello, @baskaryan , could you please take a look at this? Prompt respose caching is something that can really make a difference in certain use cases :)

**Review by hwchase17 — APPROVED** [review]
lgtm - thanks

**Comment by baskaryan** [comment]
@hemidactylus if you have time would be great to add an example to https://github.com/langchain-ai/langchain/blob/master/docs/extras/integrations/llms/llm_caching.ipynb

**Comment by aj7tesh** [comment]
is it there in latest lanchain version ?

**Comment by hemidactylus** [comment]
> @hemidactylus if you have time would be great to add an example to https://github.com/langchain-ai/langchain/blob/master/docs/extras/integrations/llms/llm_caching.ipynb

Good idea, I'll address that as soon as #10563 is resolved one way or the other :)

**Comment by hemidactylus** [comment]
> is it there in latest lanchain version ?
> 
> also can it be used with ConversationalRetrievalChain I am getting exception KeyError: 'message' @hemidactylus

Hello, the CassandraCache and CassandraSemanticCache are in langchain, yes.
As for the error you see, this is addressed by #10563 , take a look on that one. Cheers!

**Pull request merged**
